### ISSUE TITLE
How to apply custom alignment to the pagination component

### ISSUE THREAD

**Issue by anujemc** [AllenFang/react-bootstrap-table#1000]
I have a requirement to change alignment of pagination (for example- left aligned rather than right), along with the other component like the page size selector etc. How I can customize alignment of these components. Could you please help with this.
![screenshot from 2017-01-31 04 16 35](https://cloud.githubusercontent.com/assets/19282193/22464552/46c1ebca-e76c-11e6-89d8-f893ce7c996e.png)

**Comment by AllenFang** [comment]
@anujemc, you can achieve your target on `v3.0.0-beta.9`, it's still on beta but very stable, give it a try. Check [these](https://github.com/AllenFang/react-bootstrap-table/tree/v3.0.0-dev/examples/js/custom/pagination) examples and let me know if you got trouble.

thanks

**Comment by 9005** [comment]
@AllenFang : In the link provided by you. i checked an example where you custmized pagination with function.But you did hardcode values of 25 and 3. Is their any chance we can dynamically pass both values.
