### ISSUE TITLE
Using react-bootstrap-table with mxstbr-react-boilerplate

### ISSUE THREAD

**Issue by StevenGuan1991** [AllenFang/react-bootstrap-table#1001]
I am fairly new to react, so please forgive me if my question seems simple. I am trying to recreate the  example in "getting started" with the mxstbr react-boilerplate (https://github.com/react-boilerplate/react-boilerplate). 

The column headers and sample data are rendered, but none of the CSS stylings are applied. I know that the mxstbr bp uses styled-components.

**Comment by AllenFang** [comment]
@StevenGuan1991, so there's a gap between table header and body? if yes, you need try to add css of `react-bootstrap-table`. BTW, it's a bootstrap table, you are suppose to add bootstrap css and js by default

BTW, if you try `v3.0.0-beta.9`, you don't need the `bootstrap.js` and `jquery` anymore, it's a one of enhancements in `v3.0.0`

Let me know if you still have any question, thank you
