### ISSUE TITLE
Force update RegexFilter

### ISSUE THREAD

**Issue by Nevenoe** [AllenFang/react-bootstrap-table#1002]
Hi Allen,

Firstly, Thanks for react bootstrap table! :)

I want to send values ​​from my store to a RegexFilter.
I correctly retrieve the value ​​from my store, and successfully pass the value ​​to the RegexFilter.
The text field of the filter updates, however the filter action on the items in the table does not work.

This is my code:

`    

    const mapStateToProps = (state) => {
      var flowNamesRegex = "";
      state.tibco.tablesCorrelation.map((item)=> {
        flowNamesRegex = flowNamesRegex + item + "|"
      });
      flowNamesRegex = flowNamesRegex.slice(0, -1);
      return {
        flowNames: flowNamesRegex
      }
    };
    // development react table
    export const DevelopmentList = React.createClass({
      componentDidUpdate(prevProps, prevState){
        this.refs.regexFlow.refs.regexFilter.refs.inputText.value = this.props.flowNames;
        //here maybe force filter action
      },
      render() {
        if (this.props.data.loading == true) {
          return <center>Wait please...</center>
        }
        return (
            <BootstrapTable
                data={this.props.data.developments}
                pagination
                striped
                hover
                condensed={false}
                selectRow={this.props.selectRowProp}
                bordered
                ref="table"
                options={options}
            >
              <TableHeaderColumn isKey width="50" dataField="id" dataSort hidden={false}>Id</TableHeaderColumn>
          <TableHeaderColumn hidden={false} ref="regexFlow" width="400" dataField="flow.name" dataSort
                             filter={{ type: "RegexFilter" }}>RegexFlow</TableHeaderColumn>
        </BootstrapTable>
        )
      }
    });
    export default connect(mapStateToProps)(DevelopmentList)

`
There is a way to force the filter action?

**Comment by AllenFang** [comment]
hi @Nevenoe, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/regex-filter-programmatically.js#L23) and let me know if you have any quesion 👍

**Comment by Nevenoe** [comment]
Ok... I was searching for a more difficult solution ! :'-)
In reality it's very simple! Thanks for your help, it work! :-)

**Comment by AllenFang** [comment]
dig the [example](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js) folder, you will find some useful and interesting things 👍

**Comment by Nevenoe** [comment]
Thank you for this folder 👍
