### ISSUE TITLE
this.refs.table.state.selectedRowKeys off by one

### ISSUE THREAD

**Issue by crowdwave** [AllenFang/react-bootstrap-table#1005]
When I get the selected row keys via this.refs.table.state.selectedRowKeys, if I have one row selected, then this.refs.table.state.selectedRowKeys is an empty array.

If I select 2 rows, the this.refs.table.state.selectedRowKeys contains the first row selected but not the second.

Any guesses as to why this is happening?

thanks

**Comment by AllenFang** [comment]
@crowdwave, ok I'll check this out, BTW, could you please show your code? I guess use put `this.refs.table.state.selectedRowKeys` at the wrong place.

**Comment by crowdwave** [comment]
I've tried putting it in the render function, and also in the  this.onRowSelect and this.onSelectAll functions but I can't find anywhere to put it that shows the actual number of rows selected.

WHere is the correct place in the code to put this?  thanks!

**Comment by AllenFang** [comment]
you can't put in the `onSelect` or `onSelectAll` event on `render`. People use `this.refs.table.state.selectedRowKeys` to get the current selected rows on different condition, for example, on sorting, paging, insert row etc. for example, I'm certainly sure that you will get the correct selected row data like following:
```js
<div>
        <button onClick={ () => console.log(this.refs.table.state.selectedRowKeys) }>Click</button>
        <BootstrapTable ref='table' data={ products } selectRow={ selectRowProp }>
            <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
            <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
            <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
        </BootstrapTable>
      </div>
```

But if you wanna get the current selected row , use `selectRow.onSelect` to collect the row which is select or not.

it's a [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/externally-managed-selection.js#L35) you can take it.

Let me know if you got any trouble on implement, thanks

**Comment by popaulina** [comment]
@crowdwave I had this issue as well, I'm using the table within a form and don't have access to this.refs.table.state.selectedRowKeys when I submit the form, so I instead get the keys onMouseLeave, if that's useful to you at all.

**Comment by AllenFang** [comment]
@popaulina, thanks your feedback :)

> don't have access to this.refs.table.state.selectedRowKeys

is that got undefined on `this.refs.table`? because people usually forgot the what's the current context of `this`

**Comment by popaulina** [comment]
@AllenFang with redux and redux-form, at the time that the submit button is clicked the table is not in scope, and the only data available is that which is saved by the form in the store. Because of this, the data needs to already be saved before the form is submitted.

**Comment by VarunVaro** [comment]
Hi AllenFang,
I am getting undefined when i try to get state i.e, this.refs.bootstrapTable.state. May i know the reason?

<BootstrapTable id="orderTable" keyField='_id' data={data.items} caption={<CaptionElement />} columns={_TableColumns1} 
                 noDataIndication="Table is Empty" hover pagination={ paginationFactory(this.paginationOption) } defaultSorted={ _DefaultSorted } bootstrap4 filter={ filterFactory() }
                 cellEdit={cellEdit} selectRow={ selectRow } rowEvents={ rowEvents } headerClasses="tableHeader" ref="bootstrapTable"
                 />
