### ISSUE TITLE
FilterFormatted does not work if formatter returns html

### ISSUE THREAD

**Issue by j0hny666** [AllenFang/react-bootstrap-table#1007]
Hello,
I am using react-bootstrap-table on my and am very satisfied with it so far, but there is one thing that bugs me lately. I want to have an image beside the text in one of my columns. I use a formatter to achieve this like this one (the data is only and ID of category, formatted value is its name and icon retrieved from props):
```

categoryFormatter(cell, row)
    {
        var category = this.props.categories[cell];
        return <span>
            <img src={c.icons_url + category.icon}
                style={{"width": '32px', "marginRight": '10px'}} />
            {category.name}
        </span>;
    }
```

Problem is that when I want to use the "filter" prop on TableHeaderColumn, I can only filter by the ID (which is not visible since the formatter replaces it with icon and name). Even when I use filter formatted, filter still works only for the ID. This issue disappears when I remove the html code from the formatted (the span and the img tags) and leave only the {category.name} code in there. Then filter starts filtering by the name instead of the id.

Thank you in advance for looking into this!
Best, Johny

**Comment by AllenFang** [comment]
@j0hny666, ok, I'll try to reproduce this issue, and did you only have two column, one is ID another is category? 
BTW, what's the type of the filter for category and could you please upgrade to `v2.11.0` and try it again?

Please let me know you have any trouble or the problem still remain, thank you 👍

**Comment by AllenFang** [comment]
> (the data is only and ID of category, formatted value is its name and icon retrieved from props

so your raw data is `{ id: 1, category: 'ABC' }` ?


> Problem is that when I want to use the "filter" prop on TableHeaderColumn, I can only filter by the ID

it's wired, your column have been replace by image DOM and category name, why you can still filter the ID?  is that means if you key in the `1` and the filter is work well?

**Comment by AllenFang** [comment]
@j0hny666, I thought you should use the `filterValue` instead of `filterFormatted`, because if the formatter is return a JSX element, it's a bad idea for text filtering, try to use `filterValue` on `TableHeaderColumn`

it's a [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/search-format-table.js#L51)

Feel free to discuss with me 👍  thanks

**Comment by anoop237** [comment]
I am facing the same issue..I am returning JSX from formatter function but not able to filter even after using filterValue
