### ISSUE TITLE
pagination component is not aligned with size per page component 

### ISSUE THREAD

**Issue by anujemc** [AllenFang/react-bootstrap-table#1008]
Thanks for your quick help for issue #1000 
I have face one more issue with pagination alignment. I have seen there is a extra top margin of 18px is there in the pagination component, and because of this its not aligned to the other size per page component. This same alignment issue you can see the pagination example as well. Could you please have a look and make it perfectly aligned by removing unnecessary top margin.  here are the examples for more clarification

![react-bootstrap-table](https://cloud.githubusercontent.com/assets/19282193/22584007/134001c2-ea16-11e6-81a0-ed61752068da.PNG)

same alignment issue in pagination example as well
http://allenfang.github.io/react-bootstrap-table/example.html#pagination

![pagination-from-example](https://cloud.githubusercontent.com/assets/19282193/22584085/7f748a02-ea16-11e6-93e3-53589d8d2f4e.PNG)

thanks in advance !!

**Comment by anujemc** [comment]
Meanwhile I have override .pagination class to fix this but Its good if you will fix this in library itself 😃

**Comment by AllenFang** [comment]
I saw it's from the `base.css` and where is it come from?

**Comment by anujemc** [comment]
Its come from the .pagination class which effects the alignment.

**Comment by AllenFang** [comment]
I know that, but `.pagination` selector is from the 'base.css` and my question is where is it come from? because `react-bootstrap-table` haven't this css file and doest define this `.pagination` selector, so I think your solution is correct but it's can't be fixed on `react-bootstrap-table`

**Comment by anujemc** [comment]
anyway thanks ..for your quick lookup

**Comment by divye01** [comment]
@anujemc How did you solve it?

**Comment by 9005** [comment]
@AllenFang 
I am facing issue . I need to make pagination list which is towards bottom right of table to center.How to apply style to it.Need help.

**Comment by nikd-developer** [comment]
Here is the solution
```
.react-bs-table-pagination div.row div.col-md-6:nth-child(2){
    text-align:left !important;

    .react-bootstrap-table-page-btns-ul{
        float: left !important;
        margin-left:-90px;
    }
}
```
