### ISSUE TITLE
Custom search widget

### ISSUE THREAD

**Issue by moimael** [AllenFang/react-bootstrap-table#101]
Hi,

I'd like to have a custom search widget for react-bootstrap-table. The widget would be located in a toolbar somewhere on the page.

Is there any hook to be able to bind it with the table search mechanism ?

Thanks !

**Comment by AllenFang** [comment]
HI @moimael, there's no any hook for your requirement. Do you want the global search or just column filter? I thinks this is available on this component, but it need some time. Anyway, I'm glad that you use this component :)

**Comment by AllenFang** [comment]
@moimael, you can do a custom search using <code>handleSearch('your_search_text')</code> on <code>BootstrapTable</code>
