### ISSUE TITLE
fresh browser will cause table colum width change

### ISSUE THREAD

**Issue by xiaoyue123789** [AllenFang/react-bootstrap-table#1013]
before fresh, the view like this:
![2017-02-07 12-35-04](https://cloud.githubusercontent.com/assets/19748708/22678028/0bdeb378-ed32-11e6-9343-17cd303d79c2.png)
when I fresh browser, the view like this: 
![2](https://cloud.githubusercontent.com/assets/19748708/22678143/dbed46f6-ed32-11e6-9ead-d5343b500b34.png)

**Comment by AllenFang** [comment]
@xiaoyue123789, what's version you use? browser? and could your please show me your code snippet? thanks

**Comment by AllenFang** [comment]
Close it deu to no response more than 7 days
