### ISSUE TITLE
Drop down

### ISSUE THREAD

**Issue by meghanarora** [AllenFang/react-bootstrap-table#1019]
If I have a tableheadercolumn, where one of the columns has a dropdown menu, the dropdown options are hidden behind the other table columns.

If i make the position absolute, the drop downmenu stays fixed as I scroll, which I don't want either.

Any ideas on how I can fix this or if its related to the tableheadercolumn at all?

**Comment by AllenFang** [comment]
@meghanarora, is about https://github.com/AllenFang/react-bootstrap-table/issues/530 ?

**Comment by meghanarora** [comment]
Yes, thank you!
