### ISSUE TITLE
Rows expanded by default?

### ISSUE THREAD

**Issue by celim307** [AllenFang/react-bootstrap-table#1020]
Have the option for expandable rows to load and initially render as open?

**Comment by AllenFang** [comment]
HI, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/manage-expanding.js#L52), Its a example for manage the expanding by state, it may not your wanted, but I thought I can support another props like `options.defaultExpanding` for a clear using

**Comment by AllenFang** [comment]
I'm not sure that I got understand what you said, you mean the `state.expanding` in your application is a data which fetched by remote?

**Comment by frankcalise** [comment]
I'm having the same issue, let me provide a snippet for some context. The option 'expanding' needs the keys of the table data to expand the row by default, correct? So at first I have a date string as my key, but I simplified it to just an index for now. 0, 1 and 2.

The following will have all rows collapsed:
```
let expandAll = Array(this.state.jobs.length).fill().map((_,i) => this.state.jobs[i].Index);
console.log(expandAll) // shows Array of 3 in console, [0, 1, 2]
let options = {
  expanding: expandAll
}
```

For it to work, I have to hardcode the expanding option to [0, 1, 2] and then it works. The same goes for if my values were date strings.

I think this is what @celim307  was trying to describe.

**Comment by AllenFang** [comment]
@frankcalise, for the async case, you haven't the data at initialization, so the `expanding` will be an empty array, but after the data fetched, you should set the `expanding` again from your state or your state management(flux), like the [example} I mentioned before

Hope I have the correct understanding for your problem, if any thing wrong, please tell me, thanks a lots !!

**Comment by AllenFang** [comment]
BTW, if the problem is when you click the row then to fetch the content of expanding, I think I may need to find some solution for this case.

**Comment by AllenFang** [comment]
Close by #1035

**Comment by frankcalise** [comment]
@AllenFang OK, I will look at properly setting my `expanding` from state and see if that fixes it. It wasn't for fetching on expanding, that is a different use case that I'm not speaking about.

**Comment by frankcalise** [comment]
@AllenFang I tried doing this as you explained and it doesn't work for me. Please see the following snippet to see if I'm doing something wrong.
```
  constructor(props) {
    super(props)

    this.state = {
      jobs: [],
      expanding: []
    }

    this.expandComponent = this.expandComponent.bind(this)
  }

  getJobs() {
    request.get(api.JOBS_BY_DATE_ENDPOINT)
      // other query params here
      .then((response) => {
        if (!response.ok) {
          throw Error(response.statusText)
        }

        if (response.body.IsSuccess == true) {
          let jobs = response.body.JobsByDate
          // one job comes back currently, Index 0
          let expandAll = Array(jobs.length).fill().map((_,i) => jobs[i].Index); // also tried hardcoding [0] here
          this.setState({
            jobs: jobs,
            expanding: expandAll               // also tried hardcoding [0] here
          })
        } else {
          notify.show('Error retrieving jobs', 'error')
        }
      }, (failure) => {
        notify.show('Error retrieving jobs', 'error')
      })
      .then(() => {
        this.setState({ isLoading: false })
      })
  }

  render () {
    const options = {
      expanding: [0]
    }

    return (
      <div className="agenda">
        <BootstrapTable
            data={this.state.jobs}
            striped={true}
            hover={true}
            options={ options }
            expandableRow={ this.isExpandableRow }
            expandComponent={ this.expandComponent }
            condensed
            >
            <TableHeaderColumn dataField="Index" isKey={ true } hidden={ true }>Index</TableHeaderColumn>
            <TableHeaderColumn row='1' dataField="Date" dataAlign="center" dataSort={true}>Date</TableHeaderColumn>
            <TableHeaderColumn row='1' dataField="Count">Count</TableHeaderColumn>
        </BootstrapTable>
      </div>
    )
```

Note the two comments in the `getJobs()` method where I tested hardcoding the value to contain one Index that I need to expand, it didn't work there either. Nor did setting the initial state in the constructor. Only when I manually set the `expanding` property in the `options` object in `render()` to [0] does it open up by default.

Thoughts?

**Comment by AllenFang** [comment]
@frankcalise, sorry for wrong understand for your case, 

I think your example may be wrong in the `options` object in the render function, check following

```js

  render () {
    const options = {
      expanding: this.state.expanding    //<<<< should be this.state.expanding ?
    }

    return (
      <div className="agenda">
        <BootstrapTable
            data={this.state.jobs}
            striped={true}
            hover={true}
            options={ options }
            expandableRow={ this.isExpandableRow }
            expandComponent={ this.expandComponent }
            condensed
            >
            <TableHeaderColumn dataField="Index" isKey={ true } hidden={ true }>Index</TableHeaderColumn>
            <TableHeaderColumn row='1' dataField="Date" dataAlign="center" dataSort={true}>Date</TableHeaderColumn>
            <TableHeaderColumn row='1' dataField="Count">Count</TableHeaderColumn>
        </BootstrapTable>
      </div>
    )
```

**Comment by frankcalise** [comment]
#1035 is not really my case. What I was doing was on load calling for the data, then just populating the table and expanding every row by default.

And you're right, this.state.expanding can go there in options. But what I was trying to show is when I did that, it didn't work. Only when I set it explicitly to [0] (and not build it via the callback and setting state) did the row expand automatically

**Comment by AllenFang** [comment]
`[0]` is very wired case, I've no idea about that. But it should be work if you want to control the expanding, just manage the expanding row in the state and pass it to `options.expanding`.

**Comment by ufukomer** [comment]
I need that [0] thing too +1
