### ISSUE TITLE
Add Column

### ISSUE THREAD

**Issue by Abuitime** [AllenFang/react-bootstrap-table#1021]
Hello,

Is there a way to add columns to the table?

-Alex

**Comment by AllenFang** [comment]
there's no api or exposed function to do it, only way is re-render the table by giving different `TableHeaderColumn`

Let me know if you have another question

**Comment by rohankk2** [comment]
How can i append a TableHeaderColumn to an existing instance of ReactBootStrapTable ?

**Comment by OctavioDuart** [comment]
> there's no api or exposed function to do it, only way is re-render the table by giving different `TableHeaderColumn`
> 
> Let me know if you have another question

Is this still necessary?
