### ISSUE TITLE
Change font-size of body and increase column width

### ISSUE THREAD

**Issue by sacredMonster** [AllenFang/react-bootstrap-table#1022]
Hello,
I am new to react-bootstrap-table and I am trying to figure out if there is a way I can change the font size of the body content only, not the header? Also, is there a way I can increase the width of one of the columns? I am using 2.11 version of react-bootstrap-table.
Thanks,
Karina

**Comment by AllenFang** [comment]
> is there a way I can increase the width of one of the columns?

set `width` on `TableHeaderColumn`

> change the font size of the body content only

`react-bootstrap-table` does not support this feature, but I think you can overwrite by css.

Let me know if you still have any issue, thanks

**Comment by emregurbulak** [comment]
yes you can overwrite by css for change the font size of the body content only.
I tried this block.I m using  4.3.1 version .

```
.bs-table{
		.react-bs-table-bordered{
			.react-bs-container-header{
				font-size: 13px; /* table header font size*/			}
			.react-bs-container-body{
				font-size: 11px; /* table rows font size*/
			}
		}
	}
```

I hope I could help you.

**Comment by werdze** [comment]
Where would I need to place that CSS? I tried putting it in a general.css file that I am importing into my react page, but it didn't seem to work.
