### ISSUE TITLE
Crashing on Internet Explorer

### ISSUE THREAD

**Issue by shogan94** [AllenFang/react-bootstrap-table#1024]
Hi, I've ran into a problem on IE. For some reason it doesn't render and this is the error in the console...
`ToastContainer.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.` 
I have react-toastr installed also. Have you seen this before? Is there an easy fix?

**Comment by AllenFang** [comment]
`react-toastr` is also a important dependency in `react-bootstrap-table`. But it should not only crash on IE, could you help me to test on the other modern browser?

**Comment by shogan94** [comment]
So I have react-toastr (`react-toastr": "^2.8.2"`), and I don't get the error on Chrome, FireFox, or Edge. Do I need to import `toastr` whenever I import `react-bootstrap-table`. 

(Love the table component by the way.)

**Comment by AllenFang** [comment]
@shogan94, sorry for lately reply, I think this issue may related with `react-toastr`, because I've no any logic to handle particular on IE. BTW, could you try a older version of `react-bootstrap-table`, try `v2.5.9` and tell me the result, thanks !!

**Comment by shogan94** [comment]
@AllenFang no worries. Ok, I'll check different versions of `react-bootstrap-table` and `react-toastr`. Is there a way that I can disable `react-bootstrap-table` from using `react-toastr`?

**Comment by shogan94** [comment]
BTW switching to `v2.5.9` seemed to do the trick... 
`    "react-toastr": "^2.8.2",
    "react-bootstrap-table": "2.5.9",` works

**Comment by AllenFang** [comment]
> Is there a way that I can disable react-bootstrap-table from using react-toastr?

sorry, it cant be done..



> BTW switching to v2.5.9 seemed to do the trick...
> "react-toastr": "^2.8.2", "react-bootstrap-table": "2.5.9", works

it's wired..... it a long story, At the time of `2.5.9`, we got a trouble if developer upgrade to react@15.4.x and it will crash because `react-bootstrap-table` depend on `react-toastr`, however, the crash is from `react-toastr` doesn't compatible with `react@15.4.x` and the creator still doesn't fix this issue until now..., so I decide to fork `react-toastr` and fix its react version to react@15.3.x then publish it as a scope module, so.. `react-bootstrap-table` now is depend on it, you can check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/package.json#L70) out

Anyway, I really have no idea to test your case... I've no IE to reproduce your issue.

**Comment by shogan94** [comment]
No worries! Glad you were able to help me get it running! I will look further into when I have the time, but for now downgrading works perfectly fine! Thank you

**Comment by AllenFang** [comment]
@shogan94, thanks, if you got any bug, I think a workaround is that you need to fork the newest `react-bootstrap-table` version and modified the `react-toastr` version to the upstream one or just remove the dependency and bundle with your application.

Please let me know if got any troubles.

**Comment by athenaxing** [comment]
Hi, @AllenFang, @shogan94 

It will throw an error in IE 11:
ToastContainer.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object

Fixed steps:
1 Change this code:
var _reactToastr = require('@'allenfang/react-toastr');
To:
_var reactToastr = require('react-toastr');

2 And install react-toastr
npm i --save react-toastr

**Comment by AllenFang** [comment]
Upgrade to `v4.0.1` may fix this issue
