### ISSUE TITLE
I got error after update

### ISSUE THREAD

**Issue by cyclops24** [AllenFang/react-bootstrap-table#1028]
Hi @AllenFang ,
I got this error on browser console after update my project.
This is chromium dev console error:
```
Uncaught TypeError: Cannot read property 'sortFunc' of undefined       TableDataStore.js:639
```
And it's firefox console error message:
```
TypeError: _colInfos$sortDetails is undefined
```
I think it's related to react-bootstrap-table. Is it a bug or new version not backward compatible?

**Comment by cyclops24** [comment]
Sorry man. It seems it's my code issue.

**Comment by const-g** [comment]
Hi, @cyclops24  I get this error too, can you explain why you think it was from your code?

**Comment by const-g** [comment]
Ha ok, I found out. As option, I removed the default SortName value ... Dump me.
