### ISSUE TITLE
Cannot read property "Component" and Slice errors

### ISSUE THREAD

**Issue by dnbr2002** [AllenFang/react-bootstrap-table#1032]
Probably not an issue with the table.  Not really sure.  Im still in development but i just started having a lot of problems.  I always get this error, usually on initial page load or refreshes.  Based on some research I've tried downloading the latest CSS and using different CDN's ( I prefer CDN's) but nothing seems to change the behavior.  

![select_row_header](https://cloud.githubusercontent.com/assets/19315113/22844103/7ddc373c-efaa-11e6-836e-6eeeddc95b86.JPG)
  
And now more often than not, i get this as well when i refresh the page.  I only included it just in case.  Ignore it if its 'unrelated'.  I think I have a undefined state value issue to deal with.   But this shouldn't be messing with my tables, right? 

![slice2](https://cloud.githubusercontent.com/assets/19315113/22855562/91273c82-f050-11e6-9e69-196d227d5c34.JPG)

im currently using these CDN's
  `<script src="https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap-table/2.11.2/react-bootstrap-table.js"></script>`

  `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap-table/2.11.2/react-bootstrap-table.min.css">`

The code for my page in question is here.  

https://github.com/dnbr2002/FE/blob/master/src/js/pages/EventerPage.js

If possible let me know if you see anything that would help me get these selectable tables more stable cause I was really liking them.  Thanks!

**Comment by AllenFang** [comment]
@dnbr2002, your example is async, so when the table is render, I guess the data is not prepared by `fetch` probably. so please confirm it firstly. I think it's helpful for your second error, but I've no idea for the first error and I think it's not related with `react-bootstrap-table`.

Let me know if you got any trouble on implement. Thanks !

**Comment by dnbr2002** [comment]
So regarding the first error, you were right it wasn't the react-bootstrap-table js or css files.  Oddly it I needed to add these references to my index.html for React and React-Dom.  This solved the first error.  

 <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom.js"></script>

I don't know how i got this far in my project without these CDN's but this resolved the first error.  

 <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom.js"></script>

Regarding the second error it is the Data im fetching for the tables that seems to be the issue.  Originally I had no issues fetching the test data in the component but this does not seem to be working anymore.  I guess I should be loading the data and confirming it before I ask for the table as you suggested.  Im still working out the the order of operation in Reacts data flow it seems.  Thanks

**Comment by AllenFang** [comment]
> I don't know how i got this far in my project without these CDN's but this resolved the first error.

Use webpack to bundle `react` & `react-dom` and manage and install them by `npm`, you should learn how to write a modern react application

for second error, you can give your data with an empty array as initial value, **do not pass empty object or null or undefined value to `data` props**

**Comment by dnbr2002** [comment]
I knew I had something misconfigured with webpack regarding react and react-dom.  Still new to React I find webpack to be confusing a bit because so many people seem to use it so many different ways which is prob why I prefer CDN's still but Im trying to get better with it.  Im just teaching myself as I go.  So sometimes for better sometimes for worst.  Thanks for the advice.  I have tried setting the data object as empty initially before but still seemed to have the problem but I may have missed something small.  I'll revisit that and see if I can't get it to become more stable in my app.  Thanks again @AllenFang !

**Comment by dnbr2002** [comment]
@AllenFang  I was setting the initial state of the data in the parent wrong.  Using {} instead of [].  You specifying me to set an 'empty array' focused me on the issue.  So now I have no more undefined slice issues in the tables!  Thanks!
