### ISSUE TITLE
exapand & striped not working together

### ISSUE THREAD

**Issue by AlexUnger** [AllenFang/react-bootstrap-table#1034]
when using both expand and striped the expanded row is in the color of the striped row..

**Comment by toandph** [comment]
@AlexUnger how do you fix this issue?

**Comment by AllenFang** [comment]
I think I should open this issue, it's a bug, because the expanding content is also a `tr`, so cause a wrong striped on table...

**Comment by AlexUnger** [comment]
Hi,
I fixed this by using trClassName

this is my code:

 class DataGrid extends Component {
...
trClassFormat(row, rowIndex) {
        // row is the current row data
        return rowIndex % 2 === 0
            ? "tr-odd"
            : "tr-even"; // return class name.
    }

    render() {
	return (
		BootstrapTable
                    ...
                    trClassName={trClassFormat}
		    ...
		)
	} 
}


and I gave different color to tr-odd and tr-even classes

Sorry for closing, I added a lot of stuff to the code and thought the problem was only for me.

**Comment by AllenFang** [comment]
yap, use `trClassName` is a good workaround, but I'll find a solution to fix this issue by `react-bootstrap-table` itself. Thanks your feedback

**Comment by AllenFang** [comment]
This issue seems hard to solve by `react-bootstrap-table` itself, so I wont fix this problem, but any idea is welcome, close it

Let me know if you guy have same problem and can't fix with @AlexUnger's workaround

**Comment by tmcdonnell87** [comment]
PSA: if the above workaround doesn't take on the first try, make sure your CSS isn't being overwritten by the quite specific Bootstrap table CSS selector. !important works.

**Comment by LRode** [comment]
In case anyone finds this issue through searching while using the updated version of this library, `react-bootstrap-table2` (like I did), the prop `trClassName` is now `rowClasses`. This workaround still works using that prop instead.
