### ISSUE TITLE
Bootstrap Table Warnings

### ISSUE THREAD

**Issue by sunnyownage** [AllenFang/react-bootstrap-table#1036]
Hi Allen,

Thanks again for taking your time everyday to read through these issues. It is much appreciated. I'm getting the following warnings when I render your tables:
![image](https://cloud.githubusercontent.com/assets/5956893/22916224/29ec5f8c-f24b-11e6-8720-2ee08081da2f.png)

This doesn't break the tables as of now, but is obviously a concern for the future.
Currently using version 2.11.0.

**Comment by AllenFang** [comment]
@sunnyownage, thanks, I'll improve it !

**Comment by talha131** [comment]
For anyone else who is hitting this issue, I fixed it by passing unit with the width for example `width='50px'` or `width='8%'`.

**Comment by sunnyownage** [comment]
@talha131 Great, that works! Thanks!

**Comment by AllenFang** [comment]
Fixed on `v3.0.0-beta.12`, BTW, `v3.0.0` ready to end the beta, will be release to production recently.
Thanks
