### ISSUE TITLE
Can't use both select-row option and expand-row option

### ISSUE THREAD

**Issue by dekelb** [AllenFang/react-bootstrap-table#1038]
When using both `expandableRow` and `selectRow` the expanding doesn't work:

    <BootstrapTable
        data={this.state.data}
        expandableRow={ this.isExpandableRow }
        expandComponent={ this.expandComponent }
        selectRow={ {mode: 'checkbox', clickToSelect: false} }>
        {columns_defs}
    </BootstrapTable>

It looks like the `onClick` event of the `selectRow` takes over the `expand`'s one.

**Comment by dekelb** [comment]
Missed the `clickToExpand` property of the `selectRow` :) All good.

**Comment by AllenFang** [comment]
Thanks your feedback :)
