### ISSUE TITLE
Indication about expanded rows

### ISSUE THREAD

**Issue by dekelb** [AllenFang/react-bootstrap-table#1039]
I'm looking for a way to add indication regarding an expanded row.
In the following example you can see that the first column is a +/- icon - tells if the current row is expanded or not.
![react-bootsrtap-table-expand-indication](https://cloud.githubusercontent.com/assets/6668575/22942576/b344b67e-f2f2-11e6-81b3-0f57d8dda6a6.png)

The problem is that I need this column to be first (before the `selectRow` column). Is there a way to do this?
I think this should be customized.

Thanks!

**Comment by AllenFang** [comment]
> I think this should be customized.

yap, you are absolutely right, I think this is a useful feature so that I'll add it. But,,,

I will be very busy in recent for my job and I'm also ready to release `v3.0.0` to production, so this feature will be pending after `v3.0.0` release, but I'll do my best :)

**Comment by dekelb** [comment]
A few notes:
1. I think it can be great if the state (regarding a row) is saved inside the store (this way you can know if the row is expanded or not).
2. It will be great if you can decide the position of that indication
   1. First column - as In my case
   2. Second column - if a user want first column to be the checkbox (select row)
   3. Last column - if you want to show the indication on the right instead of left.
3. If possible - give the user an option to generate the expand/collapsed content of the column as a custom component, like with the select: https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/custom-multi-select-table.js#L42

I'll try to provide a quick pull request to handle at least some of them. Let me know if you start work on this so we will not work on this feature together.

Thanks!

**Comment by AllenFang** [comment]
ok, thanks, PR is welcome 👍

**Comment by AllenFang** [comment]
Released on `v3.1.0`
