### ISSUE TITLE
Table resizing

### ISSUE THREAD

**Issue by marin101** [AllenFang/react-bootstrap-table#1040]
Hi, I've been using react-bootstrap-table and it's awesome.

However, there is a small bug annoying me. When I resize the browser window the table header and table body are scaled independently which results in a shift between them. I think this happens due to the line breaking when column width is too small for the column name. Here is a screenshoot:

![screenshot from 2017-02-14 21 02 22](https://cloud.githubusercontent.com/assets/22985405/22947357/f992caa0-f2fa-11e6-841f-7b6c77213e62.png)

You can see `Inserted rows` is break into two lines to fit the screen width.
It is manifested on Google Chrome and Firefox.

Also sometimes even when the screen is full width, and no line breaking took place, this kind of shift between table header and table body occurrs.

**Comment by AllenFang** [comment]
@marin101, you forgot to add css of `react-bootstrap-table`, check https://github.com/AllenFang/react-bootstrap-table#cimport-css.

Let me know if the problem still remain after you add css.  Thanks!

**Comment by marin101** [comment]
Shame on me. Sorry for the fake issue

**Comment by AllenFang** [comment]
that's ok :)

**Comment by yha1990** [comment]
Hi,
I'm just starting to use react-bootstrap-table, i want to be able to resize my columns, do you have any ideas on how to proceed?

Thanks

**Comment by AllenFang** [comment]
@yha1990, there's a PR already fix it but need some time, I've no schedule now, sorry.

**Comment by yha1990** [comment]
@AllenFang  thank you for your response :)

**Comment by noeljoaquin30** [comment]
follow-up on this issue ?
