### ISSUE TITLE
the validator doesn't work with customEditor?

### ISSUE THREAD

**Issue by bennnjamin** [AllenFang/react-bootstrap-table#1041]
I have a custom column like this:

```js
<TableHeaderColumn dataField="phone" editable={{validator: phoneNumberValidator}} dataSort={true} dataFormat={phoneFormatter} customEditor={ { getElement: createPhoneEditor } } editable={{validator: phoneNumberValidator}}>Phone Number</TableHeaderColumn>
```

However adding the validator does not do anything here. Do I need to add the validator to my phoneEditor class? Or how can I invoke the validator in a customEditor?

**Comment by AllenFang** [comment]
@bennnjamin, why you have two `editable` on a TableHeaderColumn and make sure the validator return a bool value or an object, the object format you can check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/advance/validator-table.js#L33) example

Let me know if you still got in stuck, thanks 👍

**Comment by bennnjamin** [comment]
@aaronhayes 

I have removed the second editable here:

`<TableHeaderColumn editable={{validator: phoneNumberValidator}} dataField="phone" dataSort={true} dataFormat={phoneFormatter} customEditor={ { getElement: createPhoneEditor } }>Phone Number</TableHeaderColumn>`

This is my validator, I copied it from your link and changed the name.

`function phoneNumberValidator(value){
  console.log("validating");
  const response = { isValid: true, notification: { type: 'success', msg: '', title: '' } };
  if (!value) {
    response.isValid = false;
    response.notification.type = 'error';
    response.notification.msg = 'Value must be inserted';
    response.notification.title = 'Requested Value';
  } else if (value.length < 100) {
    response.isValid = false;
    response.notification.type = 'error';
    response.notification.msg = 'Value must have 10+ characters';
    response.notification.title = 'Invalid Value';
  }
  return response;
}`

The function is still never called onBlur.

**Comment by AllenFang** [comment]
After my investigation, I found I dont call validator for the component which is custom by user, so this is a bug issue, BTW, I'll fix it but release it on `v3.0.0`, I've stop all the development for `v2.x` and ready for release `v3.0.0` to production.

Thanks

**Comment by bennnjamin** [comment]
Thanks for following up! I am currently using 3.0 beta so please let me know when you push a fix and I will install the latest version and test.

**Comment by AllenFang** [comment]
yap, I'll

**Comment by AllenFang** [comment]
Fixed on `v3.0.0-beta.12`, BTW, `v3.0.0` ready to end the beta, will be release to production recently

Thanks

**Comment by ramovald** [comment]
I'm using version 4.3.1 and
I'm having the same problem using validator on cell edit. console.log is never shown so the function is not being called. Could you please verify it is being called? 
Thanks.

**Comment by bennnjamin** [comment]
@ramovald This project is no longer being maintained. @AllenFang is recommending to switch to https://github.com/react-bootstrap-table/react-bootstrap-table2
