### ISSUE TITLE
Uncaught TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by shadeven** [AllenFang/react-bootstrap-table#1043]
@AllenFang I keep getting an error in my app. You can find the source code here:
https://gist.github.com/shadeven/a3eb44f83999df91f4f632f6e2195b08

See the error below. Your input would be appreciated. 
all_assess_view.bundle.js:52 Uncaught TypeError: Cannot read property 'slice' of undefined
    at new t (all_assess_view.bundle.js:52)
    at all_assess_view.bundle.js:44
    at s (all_assess_view.bundle.js:44)
    at h._constructComponentWithoutOwner (all_assess_view.bundle.js:44)
    at h._constructComponent (all_assess_view.bundle.js:44)
    at h.mountComponent (all_assess_view.bundle.js:44)
    at Object.mountComponent (all_assess_view.bundle.js:12)
    at h.performInitialMount (all_assess_view.bundle.js:44)
    at h.mountComponent (all_assess_view.bundle.js:44)
    at Object.mountComponent (all_assess_view.bundle.js:12)
t @ all_assess_view.bundle.js:52
(anonymous) @ all_assess_view.bundle.js:44
s @ all_assess_view.bundle.js:44
_constructComponentWithoutOwner @ all_assess_view.bundle.js:44
_constructComponent @ all_assess_view.bundle.js:44
mountComponent @ all_assess_view.bundle.js:44
mountComponent @ all_assess_view.bundle.js:12
performInitialMount @ all_assess_view.bundle.js:44
mountComponent @ all_assess_view.bundle.js:44
mountComponent @ all_assess_view.bundle.js:12
mountChildren @ all_assess_view.bundle.js:46
_createInitialChildren @ all_assess_view.bundle.js:45
mountComponent @ all_assess_view.bundle.js:45
mountComponent @ all_assess_view.bundle.js:12
performInitialMount @ all_assess_view.bundle.js:44
mountComponent @ all_assess_view.bundle.js:44
mountComponent @ all_assess_view.bundle.js:12
performInitialMount @ all_assess_view.bundle.js:44
mountComponent @ all_assess_view.bundle.js:44
mountComponent @ all_assess_view.bundle.js:12
i @ all_assess_view.bundle.js:41
perform @ all_assess_view.bundle.js:12
s @ all_assess_view.bundle.js:41
perform @ all_assess_view.bundle.js:12
batchedUpdates @ all_assess_view.bundle.js:46
a @ all_assess_view.bundle.js:11
_renderNewRootComponent @ all_assess_view.bundle.js:41
_renderSubtreeIntoContainer @ all_assess_view.bundle.js:41
render @ all_assess_view.bundle.js:41
(anonymous) @ all_assess_view.bundle.js:1
t @ all_assess_view.bundle.js:1
(anonymous) @ all_assess_view.bundle.js:1
(anonymous) @ all_assess_view.bundle.js:1

**Comment by AllenFang** [comment]
HI, I think the root cause is you dont pass the `data` as props into your `Table`, do `this.props.data` is `undefined`

**Comment by shadeven** [comment]
@AllenFang I passed `this.props.data` and `this.props.loading` to `Table`. However, the problem still persists. Please see Gist for changes.

**Comment by shadeven** [comment]
@AllenFang I figured it out. All good now. Thanks.
