### ISSUE TITLE
How to get key to use as URL query parameter inside another cell? 

### ISSUE THREAD

**Issue by devjeff** [AllenFang/react-bootstrap-table#1045]
Hi, Thanks for a great component. 

Is it possible to extract the key to use in another cell? The cell contents have a link but the link's URL needs the id as parameter.  In this example, is it possible for the colFormatter method to see the subjectId and pass it back in the link?

```
<BootstrapTable data={this.props.subjectList}  selectRow={{mode: 'checkbox'}} search={ true } multiColumnSearch={ true } striped hover responsive pagination bordered={ false } options={ { noDataText: 'No matching subjects found' } }>
  <TableHeaderColumn dataField='subjectId' isKey={ true } autoValue={ true } hidden >ID</TableHeaderColumn>
  <TableHeaderColumn dataField='subject' dataSort={ true }>Subj#</TableHeaderColumn>
  <TableHeaderColumn dataField='subjectTitle' dataFormat = { this.colFormatter} dataSort={ true }>Title</TableHeaderColumn>
</BootstrapTable>
```

**Comment by devjeff** [comment]
The solution is simple, in the function to format the column data, just pull the id from the row, so :

`colFormatter = (cell, row) => {
    return (

<Link to={{ pathname: '/SubjectDetails',  query: { instrOfferingId: row.instrOfferingId } }}>
        {cell} 
      </Link>
    )
  }`

**Comment by devjeff** [comment]
I thought the row parameter to format function was the row's index, but it's actually the whole object.  This opened up a whole new world. Many thanks @AllenFang.

**Comment by AllenFang** [comment]
@devjeff, great, let me know if you got any trouble:)
