### ISSUE TITLE
Reuse customEditor in insert modal?

### ISSUE THREAD

**Issue by bennnjamin** [AllenFang/react-bootstrap-table#1047]
Hello, I'm following these two examples here to create a custom Phone Number Input cell that automatically formats numbers and has validation. I have the cell edit part working fairly well, however when I go to insert a row into my table, the default insert modal just uses a text input instead of my custom cell. So I start trying to implement a custom input, however I can't find a way to reuse my Custom Cell as an input in my modal. 

https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/cell-edit/custom-cell-edit-table.js

https://gist.github.com/AllenFang/b07eb78dc052c7a6dc4d026cdc5eeb1b#file-custom-insert-modal-jsx

Looking at the source code for the default insert modal here, https://github.com/AllenFang/react-bootstrap-table/blob/master/src/toolbar/ToolBar.js#L315 it's much more robust than the custom insert. It will automatically create the correct input based on `editable.type`. Is there a way for me to create a custom modal that can access `customEditor.getElement` property or is there a better way?

**Comment by bennnjamin** [comment]
@AllenFang What's the best way to Insert A New Row when using a custom cell? The default insert modal just renders the custom cell as a text box. Without this functionality, it makes it so all the custom code in the cell is irrelevant when adding a new row.

**Comment by AllenFang** [comment]
That's said, the `customEditor` on the `TableHeaderColumn` only support cell editing, and For the default insert row modal, the `customEditor` will not be apply on the fields. 

And for `v3.0.0(Still on beta but pretty stable)`, now you can custom the modal by yourself. You can check [this exmaple](https://github.com/AllenFang/react-bootstrap-table/blob/v3.0.0-dev/examples/js/custom/insert-modal/custom-insert-modal-body.js#L24), so I think you can still reuse your custom editor in there.

BTW, I think your concern is right, the `customEditor` is supposed to be used in the insert modal also, I'll consider to support this feature but need some time.

Let me know if you get any trouble in the implement for customization for insert modal.
Thanks

**Comment by AaronONeill** [comment]
Just adding a +1 to this, currently looking at needing this exact functionality right now.

Any time frame on when we would be able to see this baked in? @AllenFang

**Comment by AllenFang** [comment]
Sorry, it really need some time, there're many issue need to fix and I'm busy on my work. so I have no any schedule but I'll work hard 👍

**Comment by AllenFang** [comment]
HI all, due to some issue, I decide not to use `customEditor` to custom both of cell editor and insert model field. Currently, you are able to custom the field in the insert modal via `customInsertEditor` prop on `TableHeaderColumn` and check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/insert-modal/custom-insert-modal-field.js) to learn how to use it and it's very simple and easy to understand, thanks

BTW, please upgrade to `v3.2.0`, and let me know if you have any question.
