### ISSUE TITLE
Selected className overwritten by stripped and hover

### ISSUE THREAD

**Issue by ZephD** [AllenFang/react-bootstrap-table#1049]
RE PR #490 

I would like to set the selected background colour via css, so I can uses my sass variable.

This means my selectedRowProp looks like this:
`const selectRowProp = {
  mode: 'checkbox',
  className: 'table-row-selected',
};`
and I have set the style for that class to:
`.table-row-selected {
  background-color: $gray-light;
}`
using my variable `$gray-light`.

This works, and the selected row is coloured correctly.

However, if the table is stripped, only every other row has the selected background.
Also, if i hover over a row, the 'hovered' row becomes the hover colour, not the selected colour.

![screenshot from 2017-02-16 12-26-54](https://cloud.githubusercontent.com/assets/1461917/23021398/a6d30880-f443-11e6-97d3-c754f669d064.png)

Note that 5 rows are selected. the 1st, 3rd and 5th are the "stripped" colour, and the 4th is the "hover" colour.
They should all be the selected colour (2nd).

I know of the prop variable "bgColor", but i cannot use my css variable here (without some crazy json stuff).

**Comment by ZephD** [comment]
Workaround: add !important to the css background color:
`.table-row-selected { background-color: $gray-light !important; }`

**Comment by AllenFang** [comment]
@ZephD, I'm gonna to fix this issue, because table stripped is a default bootstrap style and it have a higher priority for table, so your solution is correctly.

Just think if you have a native bootstrap table with stripped, and you want to have some row with bgcolor, you still overwrite it with `!important`.
