### ISSUE TITLE
Access state of parent component from within onSelect function

### ISSUE THREAD

**Issue by shoelessness** [AllenFang/react-bootstrap-table#105]
```javascript
var React = require('react');
var Panels = require('./panels');
var ReactBsTable = require("react-bootstrap-table");
var BootstrapTable = ReactBsTable.BootstrapTable;
var TableHeaderColumn = ReactBsTable.TableHeaderColumn;

module.exports = React.createClass({
	getInitialState: function(){
    return {
      table: {
        columns: [
          {
            name: "ID",
            id: "id"
          }, 
          {
            name: "Name",
            id: "name"
          }, 
          {
            name: "Price",
            id: "price"
          }
        ],
        data: [
          {
            id: 1,
            name: "Product1",
            price: 120
          },{
            id: 2,
            name: "Product2",
            price: 80
          },{
            id: 3,
            name: "Product3",
            price: 207
          },{
            id: 4,
            name: "Product4",
            price: 100
          },{
            id: 5,
            name: "Product5",
            price: 150
          },{
            id: 6,
            name: "Product6",
            price: 160
          }
        ]
      },
      selectedRow: {}
    }
  },
  selectRowProps: {
    mode: "radio",
    clickToSelect: true,
    bgColor: "rgb(238, 193, 213)",
    onSelect: function (row, isSelected) {
    console.log(row);
    console.log("selected: " + isSelected);
    // this.state.selectedRow = row; 
    console.log(this);
    }
  },
  render: function() {
    console.log(this);
		return <div className="wrapper">
      <BootstrapTable 
        data={this.state.table.data} 
        striped={true} 
        hover={true} 
        search={true}
        columnFilter={true}
        selectRow={this.selectRowProps}
      >
        {this.iterateAndMapColumns()}
      </BootstrapTable>
      {this.populatePanels}
    </div>
  },
  iterateAndMapColumns: function(){
    return this.state.table.columns.map(function(column){
      return <TableHeaderColumn 
      isKey={column.id==="id" ? true : false} 
      hidden={column.id==="id" ? true : false} 
      dataField={column.id}
      key={column.id}
      dataSort={true}
      >
        {column.name}
      </TableHeaderColumn>
    });
  },
  populatePanels: function(){
    return <Panels row={this.state.selectedRow}></Panels>
  }
});
```

My goal is to take the selected row in the table and display its contents outside of the table in a series of panels. In order to do this, I am trying to pass the selected row into a state value on the class, which I will then pass into the panels component.
The issue I am hitting is not being able to access the state of the the React class which I am creating within the onSelect function, however, as far as I can tell, due to onSelectRow being bound to its parent element (see BootstrapTable.js line 200), the use of the `this` keyword refers to the row which is selected.
Is there something elementary about how onSelect is supposed to be used which I am misunderstanding? Any assistance would be greatly appreciated.

**Comment by AllenFang** [comment]
Hi @shoelessness, try the following code and you need study more about <code>this</code> in javascript.
<pre>
var React = require('react');
var ReactBsTable = require("react-bootstrap-table");
var BootstrapTable = ReactBsTable.BootstrapTable;
var TableHeaderColumn = ReactBsTable.TableHeaderColumn;

module.exports = React.createClass({
    getInitialState: function(){
    return {
      table: {
        columns: [
          {
            name: "ID",
            id: "id"
          },
          {
            name: "Name",
            id: "name"
          },
          {
            name: "Price",
            id: "price"
          }
        ],
        data: [
          {
            id: 1,
            name: "Product1",
            price: 120
          },{
            id: 2,
            name: "Product2",
            price: 80
          },{
            id: 3,
            name: "Product3",
            price: 207
          },{
            id: 4,
            name: "Product4",
            price: 100
          },{
            id: 5,
            name: "Product5",
            price: 150
          },{
            id: 6,
            name: "Product6",
            price: 160
          }
        ]
      },
      selectedRow: []
    }
  },

  handleRowSelect: function(row, isSelected){
    console.log(row);
    console.log("selected: " + isSelected);
    // this.state.selectedRow = row;
    console.log(this.state);
  },

  render: function() {
    var selectRowProps =  {
      mode: "radio",
      clickToSelect: true,
      bgColor: "rgb(238, 193, 213)",
      onSelect: this.handleRowSelect
    };
        return &lt;div className="wrapper"&gt;
      &lt;BootstrapTable
        data={this.state.table.data}
        striped={true}
        hover={true}
        search={true}
        columnFilter={true}
        selectRow={selectRowProps}
      &gt;
        {this.iterateAndMapColumns()}
      &lt;/BootstrapTable&gt;
      {this.populatePanels}
    &lt;/div&gt;
  },
  iterateAndMapColumns: function(){
    return this.state.table.columns.map(function(column){
      return &lt;TableHeaderColumn
      isKey={column.id==="id" ? true : false}
      hidden={column.id==="id" ? true : false}
      dataField={column.id}
      key={column.id}
      dataSort={true}
      &gt;
        {column.name}
      &lt;/TableHeaderColumn&gt;
    });
  },
  populatePanels: function(){
    return &lt;Panels row={this.state.selectedRow}&gt;&lt;/Panels&gt;
  }
});
</pre>

**Comment by shoelessness** [comment]
I thought it might be something rudimentary. Thank you very much @AllenFang for your prompt assistance.

**Comment by AllenFang** [comment]
@shoelessness , thanks, welcome to ask more questions :)
