### ISSUE TITLE
How to show / hide Expand row onClick the button?

### ISSUE THREAD

**Issue by jmorozov** [AllenFang/react-bootstrap-table#1051]
Hello! I continue to enjoy the v3.0-beta. But I could not find how to show / hide Expand row onClick the button. Is it possible to do now? Can you give me a hint on this matter or to give an example of code, or to describe how I can do it?

**Comment by AllenFang** [comment]
@jmorozov, sorry just for not update the document yet... pretty busy ;(

check [this](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/expandRow) example folder, and actually you can find anything in the [examples](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js) folder

For a simplest expanding row case, just check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/expandRow.js#L78-L79

Let me know if you have any question :)
