### ISSUE TITLE
Uncaught TypeError: Cannot read property 'slice' of undefined     at new BootstrapTable

### ISSUE THREAD

**Issue by theotran** [AllenFang/react-bootstrap-table#1053]
Im getting this error when passing my data in the prop "data={}" for the BootstrapTable.
My data structure is just an array of objects passed from an Apollo Provider. Anyone else have this issue? 

`Uncaught TypeError: Cannot read property 'slice' of undefined
    at new BootstrapTable`

**Comment by AllenFang** [comment]
@theotran, `data` only accept an array, any object or empty object for table is invalid, but I'll try to improve this by some short circuit for `null` or `undefined` so in the future, the null or undefined or empty array is better if you have no data instead of empty object

**Comment by AllenFang** [comment]
Fixed on `v3.0.0-beta.12`,  null or undefined value will not cause this issue

BTW, `v3.0.0` ready to end the beta, will be release to production recently

**Comment by Patrik-Glendell** [comment]
this is very good , can you explain how you solved it , how should we deal with the empty state ?

**Comment by AllenFang** [comment]
@Patrik-Glendell, for you, just no any magic, remember assign your data with an empty array and fill data if you get from backend or somewhere. And I just use short circuit to avoid this issue :)

**Comment by theotran** [comment]
@AllenFang whats the best way to go about this? My data initially comes up as 'undefined' then becomes an array of objects with Apollo/Redux. Do I set an initial prop value of an empty array?

**Comment by AllenFang** [comment]
> Do I set an initial prop value of an empty array?

yes, but on the newest version of `v3.0.0-beta.12` I've fixed this issue for undefined and null value, But an empty array will be best!!

**Comment by theotran** [comment]
@AllenFang Thanks, how can I download the newest version of the Beta?

**Comment by AllenFang** [comment]
I've released `v3.0.0` to production yesterday, you can upgrade to `v3.0.0`. thanks

**Comment by Ukmandal** [comment]
Cannot read property 'slice' of undefined. Help here!
