### ISSUE TITLE
how to remove toastr dependency

### ISSUE THREAD

**Issue by pocesar** [AllenFang/react-bootstrap-table#1054]
I'm not using or planning to using it, and it's adding react and react-dom @ 15.3.2, making my build at least 150kb bigger. plus it's breaking SystemJS import with multiple react versions

**Comment by garethdown44** [comment]
Same - it's causing 15.3.2 to be pulled in. react-toastr should be an opt-in dependency. All I want is a grid with sorting and paging, I don't need toasts.

![image](https://cloud.githubusercontent.com/assets/145924/23086179/82fd7794-f563-11e6-9768-41f455676d88.png)

**Comment by pocesar** [comment]
solved it in JSPM using the map / dependency overrides (might be similar to webpack)

```json
"jspm": {
   "overrides": {
      "npm:@allenfang/react-toastr@2.8.2": {
        "dependencies": {
          "react": "^15.4.2",
          "react-dom": "^15.4.2",
          "react-addons-update": "^15.4.2",
          "classnames": "^2.2.5",
          "element-class": "^0.2.2",
          "lodash": "^4.17.0"
        },
        "map": {
          "./lib/ToastMessage": "./lib/ToastMessage/index",
          "react": "npm:react@15.4.2",
          "react-dom": "npm:react-dom@15.4.2",
          "react-addons-update": "npm:react-addons-update@15.4.2"
        }
      }
    }
  }
}
```

**Comment by AllenFang** [comment]
sorry for lately reply, I wanna drop it also, but it was deep dependency since a long time ago and even make some trouble by #838 #863 

Actually, I will spend some time to separate it but not now, so PR is welcome, maybe the worst solution I may need to separate two repo or event bundle two files.

**Comment by pocesar** [comment]
the roastr dependency SEEMS to work fine with React 15.4.2, the only problem is that the path to ReactDOM is wrong, it doesn't exist in `react/lib/ReactDOM` anymore but in react-dom dependency itself. the mappings hack did fix it, SystemJS is able to remap the dependency at will, but the proper way would be to remove the dependency on react / react-dom on roastr itself

**Comment by AllenFang** [comment]
yes, the problem is here:
`Module not found: Error: Cannot resolve module 'react-dom/lib/getVendorPrefixedEventName'`

So maybe I can try to fix `@allenfang/react-toastr` again... but It need some time(Start busy now for my work), so PR is welcome.

**Comment by celim307** [comment]
for webpack people, I ended up just aliasing react and react-dom to node modules in my config

      react: path.resolve(__dirname, '../node_modules/react'),
      'react-dom': path.resolve(__dirname, '../node_modules/react-dom'),

probably not best practice, if someone has a better idea i'd love to hear it.

**Comment by AllenFang** [comment]
@celim307, cool, it's also a workaround

**Comment by AllenFang** [comment]
please check #1216, if you have any concern or question, let me know in #1216

**Comment by AllenFang** [comment]
After `v4.0.0`, `react-bootstrap-table doesn't use `react-toastr` anymore.
