### ISSUE TITLE
How to change on-hover css styling for every row instead of cell?

### ISSUE THREAD

**Issue by Andriy-Kulak** [AllenFang/react-bootstrap-table#1055]
Below is the example provided in documentation to add class to a specific cell.

How can I add styling to the entire row? I want to create a custom 'on-mouse-over' css class that affects entire row as a whole instead of using default one provided by bootstrap.

Because the css only affects the specific cell in example below, only that row is highlighted when on-mouse-over event happens.
```
function columnClassNameFormat(fieldValue, row, rowIdx, colIdx) {
  // fieldValue is column value
  // row is whole row object
  // rowIdx is index of row
  // colIdx is index of column
  return rowIdx % 2 === 0 ? 'td-column-function-even-example' : 'td-column-function-odd-example';
}

class TrClassStringTable extends React.Component {
  render() {
    return (
      <BootstrapTable data={ products }>
          <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price' columnClassName={ columnClassNameFormat }>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
}
```

**Comment by Andriy-Kulak** [comment]
I realized 'trClassName' within the table is the feature I was looking for so this is no longer an issue. Thanks!

**Comment by AllenFang** [comment]
@Andriy-Kulak, great, let me know if you have any question :)
