### ISSUE TITLE
linking to my table with expandable row

### ISSUE THREAD

**Issue by ashabi** [AllenFang/react-bootstrap-table#1060]
hi.

i have an bootstrap table that sits within another bootstrap table and is visible using the expandRow.

Is there anyway I can link to the bootstrap table but have a specific expandRow be automatically opened based on a parameter that I send?

thanks.

**Comment by AllenFang** [comment]
> Is there anyway I can link to the bootstrap table but have a specific expandRow be automatically opened based on a parameter that I send?

sorry I cant got you, what's the means for link? Actually, you can control which which row is expanding by yourself. so I just doesn't know what did you want, maybe a use case will be good

thanks

**Comment by ashabi** [comment]
i need to link from a different page to a page with a bootstrap table but have a specific row (id that i pass) opened by default. is that more clear?

**Comment by ashabi** [comment]
never mind. I figured it out based on your example: https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/manage-expanding.js

**Comment by AllenFang** [comment]
ok, close it, feel free to discuss with me
