### ISSUE TITLE
Define Style for Individual Rows

### ISSUE THREAD

**Issue by kevinguard** [AllenFang/react-bootstrap-table#1061]
Hello Everyone!

I wonder if there is a way we could define each rows style and format individually. Although we can set headers and row data's style, I don;t seem to be able to find if there is a way we could set each rows format. Imagine we are showing a mail inbox content and would like to show different format and style for those mails that are unread as compared to those that are already read. Is there any way we could accomplish this?

Thanks,
Kevin

**Comment by AllenFang** [comment]
you can use `dataFormat` to custom your column, if you want to style your row, [There](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/style) are couples examples you can have a look

Let me know if you got any trouble on implementation
