### ISSUE TITLE
Add "Count" column dynamically

### ISSUE THREAD

**Issue by nitronick600** [AllenFang/react-bootstrap-table#1062]
Hello,
Thank you for such a high-quality library.  I really like it.  

Do you have any suggestions for adding a "count" column to the table?  I would like to show the item number in the list, but it's not included my data.

**Comment by AllenFang** [comment]
is like a summary area in the footer? or where?

**Comment by nitronick600** [comment]
Oh, I see, I didn't have my pagination set up properly.  Thanks!

![screen shot 2017-02-20 at 9 23 50 am](https://cloud.githubusercontent.com/assets/561911/23135686/692500c0-f74e-11e6-9b55-b0e8e1ae6290.png)
