### ISSUE TITLE
Table Header creation dynamically

### ISSUE THREAD

**Issue by shalinibajpai0310** [AllenFang/react-bootstrap-table#1068]
Hi,

I am having a json of Table Headers which i want to render at run time.
Till now we have to give all the table headers manually one by one , is there any possibility in react bootstrap table that we can pass the headers json into <BootstrapTable  headers={Headers}/> and our table will get rendered by the json.

Here is a sample of json might be like:
[{ dataField:'id01',name:'Abc' width:'100px'
} ,{ dataField:'id02',name:'Abc' width:'100px'},{ dataField:'id03',name:'Abc' width:'100px'}]

**Comment by AllenFang** [comment]
> is there any possibility in react bootstrap table that we can pass the headers json into and our table will get rendered by the json.

sure, just `map` them and return the `TableHeaderColumn`,

Let me know if you have any question, thanks
