### ISSUE TITLE
db connection issue

### ISSUE THREAD

**Issue by XZeroManiac** [AllenFang/react-bootstrap-table#1069]
hi
can delete button change the data of my db ? 
don't know how to do 
could you give me some advice ?
thanks

**Comment by AllenFang** [comment]
we don't support this kind of feature, but we enable `remote`, if enabling `remote`, you need to handle all the data changing by yourself(sort, insert, delete, paging, filter etc).

but in the newest `v3.0.0-beta.12`, you can choose some functionality to use remote or not, check [this](example) and [this](https://github.com/AllenFang/react-bootstrap-table/blob/v3.0.0-dev/examples/js/remote/remote-store-alternative.js), you can learn how to do this.

BTW, [There](https://github.com/AllenFang/react-bootstrap-table/tree/v3.0.0-dev/examples/js/remote) are some example you can have a look.

Thanks, let me know if you got any trouble on implements
