### ISSUE TITLE
Use fixed version of react-toastr module

### ISSUE THREAD

**Issue by iamyardem** [AllenFang/react-bootstrap-table#107]
Since there are problems with new version of react-toastr module, it is probably better to set fixed version (2.1.0) in packages.json

**Comment by AllenFang** [comment]
what's problem in <code>react-toastr@2.2.0</code>?

**Comment by iamyardem** [comment]
here is a link to issue. https://github.com/tomchentw/react-toastr/issues/42

**Comment by AllenFang** [comment]
how about upgrade to <code>v2.2.2</code>?

**Comment by tomchentw** [comment]
@iamyardem @AllenFang I just published [v2.2.2](https://github.com/tomchentw/react-toastr/releases/tag/v2.2.2) to npm and hope it'll fix the issue. Sorry I didn't meant to bring any breaking changes in patch commit. :(

**Comment by AllenFang** [comment]
Thanks @tomchentw

**Comment by iamyardem** [comment]
yes, currently everything is fine, thanks for support and instant reaction :)

**Comment by tomchentw** [comment]
I feels bad about screwing stuff out there. Thanks @iamyardem to point thing out timely and I could fix that. Really appreciated!
