### ISSUE TITLE
NO button will be displayed on top left when only customized buttons are provided. 

### ISSUE THREAD

**Issue by firestarman** [AllenFang/react-bootstrap-table#1070]
To display the button group, need to add at least one of these properties : 'insertRow, deleteRow, exportCSV ' .
Source code:

        let buttonBuilder = props => {
            return (
                <ButtonGroup>
                    <Link className="btn btn-primary" to="/home/advanced/userinfo">
                        <span><i className="glyphicon glyphicon-plus" />&nbsp;Add User</span>
                    </Link>
                    <Button
                        bsStyle="primary"
                        onClick={this.props.fetchUsers.bind(this)}>
                    <span><i className="glyphicon glyphicon-refresh" /> Refresh </span>
                    </Button>
                </ButtonGroup>
            );
        };

       <BootstrapTable
                        hover remote
                        data={list}
                        options={{
                            btnGroup: buttonBuilder
                        }}>

**Comment by AllenFang** [comment]
I'll check this out, thanks for feedback 👍

**Comment by AllenFang** [comment]
Released on `v3.1.0`
