### ISSUE TITLE
[Question or Feature Request] fully customize pagination

### ISSUE THREAD

**Issue by saeedjalali1** [AllenFang/react-bootstrap-table#1071]
Hi @AllenFang ,
First thanks for your awesome package.
I want use your component with Meteor and handle pagination server side (with Meteor publications).
I have some problem with this because your component page length is read from `data` props array length.
Can you help me to done this?
How we can set pagination manually?
Is it possible to fully customize pagination?

**Comment by cyclops24** [comment]
It's my question too. Is it any way to customize pagination totally?

**Comment by AllenFang** [comment]
It can be done in `v3.0.0`(Current version is beta, `v3.0.0-beta.12), check all the pagination customization examples at https://github.com/AllenFang/react-bootstrap-table/tree/v3.0.0-dev/examples/js/custom/pagination

[This](https://github.com/AllenFang/react-bootstrap-table/blob/v3.0.0-dev/examples/js/custom/pagination/custom-pagination-panel.js) is you guys answer!!

Please let me know if you have any questions, thanks
