### ISSUE TITLE
Customised Search input

### ISSUE THREAD

**Issue by abdelmoula** [AllenFang/react-bootstrap-table#1072]
@AllenFang Do you please have an example of using a custom searchField ? I can't get my input text field to call the right onSearchChange function onKeyUp.

**Comment by saesh** [comment]
Hey @abdelmoula, did you resolve your issue? And if yes, how?

**Comment by abdelmoula** [comment]
hey @saesh  yeah basically what I did is to add custom searchField then specify the function to call onKeyup which is props.search. example :
in options add this line
searchField: this.customSearchField,

then create the custom search function : 
  customSearchField(props) {
    return (
      <TextField floatingLabelText="Table Filter" className="search-input" onKeyUp={props.search}/>
    );
  },

**Comment by saschahagedorn** [comment]
Ah ok, thanks! 

I can't find anything on a custom search field in the [docs](https://allenfang.github.io/react-bootstrap-table/docs.html#options), that is why I am asking. `options.searchField` is the option prop on `BootstrapTable`?

**Comment by saesh** [comment]
Ah ok, thanks!

I can't find anything on a custom search field in the [docs](https://allenfang.github.io/react-bootstrap-table/docs.html#options). That is why I am asking. `options.searchField` is the prop on `BootstrapTable`?

**Comment by abdelmoula** [comment]
@saesh  yeah the props are defined in BootstrapTable.

**Comment by AllenFang** [comment]
thanks @abdelmoula, and @saesh, you can also check [here](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/custom/search) to learn how to custom search, and this is a docs missing, I'll update it, thank you both :)

**Comment by AllenFang** [comment]
Document updated http://allenfang.github.io/react-bootstrap-table/custom.html#searchfield

Sorry for forgetting mention here.
