### ISSUE TITLE
[Help Wanted] Is there a way to group column data in body

### ISSUE THREAD

**Issue by sacredMonster** [AllenFang/react-bootstrap-table#1073]
Hi,
I am trying to achieve the following grouping in the body of the container. I see that there is an example of header grouping but that considers my table field 1 (row='0' colSpan='3') as only a header and does not show it in the body. I need that field to be present in the body as well.
![image](https://cloud.githubusercontent.com/assets/14304071/23193006/7dc20466-f85b-11e6-8424-f3745aae6aa5.png)
Thanks,
Karina

**Comment by AllenFang** [comment]
yap, it will be nice if we can have this feature,for now, I think I've no time to do this, so PR is welcome.

**Comment by sacredMonster** [comment]
Thanks for the reply. I will try implementing this with my project and if it works create a PR for react-bootstrap-table.
