### ISSUE TITLE
Pagination not Working in InternetExplorer

### ISSUE THREAD

**Issue by JD2k** [AllenFang/react-bootstrap-table#1074]
Hello,

in chrome everything works fine. With Internet Explorer the pagination is not working if i try to get any page, the whole webpage got reloaded. 
Is this a known problem, exist any workaround or did i something wrong?
Already tried several bootstrap version (2.11.2 and 3.0.0-beta.6) with InternetExplorer 12.

Thanks in advance

**Comment by AllenFang** [comment]
@JD2k, could you please go to http://allenfang.github.io/react-bootstrap-table/example.html#pagination and try on your IE?

**Comment by JD2k** [comment]
Hi Allen, thanks for your quick reply. Your link is working fine, now iam wondering why it is not working in my solution. I rebuild your example and not even this is working. Do you happen to know if there is a problem with pagination and using meteor plattform?

My example code looks like that:
`import React from 'react';
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';

export default class TestTable extends React.Component {
    render() {
        let products = [
            {id: 0, name: 0,price: 0},
            {id: 1, name: 0,price: 0},
            {id: 2, name: 0,price: 0},
            {id: 3, name: 0,price: 0},
            {id: 4, name: 0,price: 0},
            {id: 5, name: 0,price: 0},
            {id: 6, name: 0,price: 0},
            {id: 7, name: 0,price: 0},
            {id: 8, name: 0,price: 0},
            {id: 9, name: 0,price: 0},
            {id: 10, name: 0,price: 0},
            {id: 11, name: 0,price: 0},
            {id: 12, name: 0,price: 0}
        ]

        return﻿(<div>
            <BootstrapTable
                data={ products }
                pagination>
                <TableHeaderColumn dataField='id' isKey>Product ID</TableHeaderColumn>
                <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
                <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
            </BootstrapTable>
        </div>)
    }
}`

**Comment by AllenFang** [comment]
sorry for lately reply due to my long trip ;)

I've no any experience with metoer and what's the version of your `bootstrap` and `react-bootstrap-table` ?

**Comment by JD2k** [comment]
No problem, iam glad that i got support from you at all :)

My bootstrap and table version are twbs:bootstrap 3.3.6 and react-bootstrap-table 3.0.0 .

**Comment by JD2k** [comment]
Hi Allen,

fortunately i could find the problem. The meteor router in combination with Internet Explorer handles a-tags without a link target in a wrong way. So the linked path is set to nothing and i got the described problem.

Solved this issue with a workaround:

`componentWillMount() {`
`       //Internet Explorer Fix`
`        this.replacePathHref("mousedown");`
`        this.replacePathHref("keydown");`
`    }`
``
`    replacePathHref(action) {`
`        $(document).on(action, 'a', function() {`
`            if (/#$/.test(this.href) && this.pathname === '') {`
`                this.pathname = location.pathname;`
`            }`
`        });`
`    }`

So this problem is not react-bootstrap-table related. Thank you very much for your help and thanks for this great table package.

Greetings
