### ISSUE TITLE
ExpandRow icon issue

### ISSUE THREAD

**Issue by shahromil88** [AllenFang/react-bootstrap-table#1076]
Hello,

I am using nested grid (parent/child). I have a separate column in parent grid to expand child grid. So, when user clicks on that icon, the child grid expands. 

Issue: I have also another column which has checkbox per row (to indicate row is selected for some operation). When I click on checkbox, it is expanding the child grid as well. I am not able to understand why this behavior is happening although I have separate column to expand row.

Sample Code Snippet:

<BootstrapTable
	ref="table"
	data={props.isRemoteData ? this.state.results : props.gridData}
	remote={props.isRemoteData}
	height={props.height}
	pagination={props.pagination}
	search={props.enableSearch}
	fetchInfo={{ dataTotalSize: this.state.totalDataSize }}
	selectRow={{
		mode: 'checkbox',
		clickToSelect: true,
		clickToExpand: true,
		bgColor: "rgb(207, 206, 230)",
		onSelect: this.onRowSelect,
		onSelectAll: this.onSelectAll,
		selected: this.state.selected
	}}
	exportCSV={props.exportCSV}
	expandableRow={props.expandableRow}
	expandComponent={props.expandComponent}
	options={{
		sizePerPage: this.state.externalResultsPerPage,
		sizePerPageList: [10, 25, 50, 100],
		page: this.state.currentPage,
		paginationSize: 5,
		paginationShowsTotal: true,
		expandBy: props.expandBy,
		onPageChange: props.isRemoteData ? this.onPageChange.bind(this) : null,
		onSortChange: props.isRemoteData ? this.onSortChange.bind(this) : null,
		onSearchChange: props.isRemoteData ? this.onSearchChange.bind(this) : null,
		onFilterChange: props.isRemoteData ? this.onFilterChange.bind(this) : null,
		onExportToCSV: props.isRemoteData ? this.onExportToCSV.bind(this) : null
	}}>
	
<TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
<TableHeaderColumn 
	dataField={column.field}
	key={column.field}
	width={column.width}
	isKey={column.isKey}
	dataSort={false}
	expandable={true}
	dataFormat={column.isExpand ? this.props.formatter : this.columnFormates(column.format)}
	tdAttr={'className': 'expander-style' } : null}
	filter={column.filter}>
	{column.displayName}
</TableHeaderColumn>
<TableHeaderColumn dataField='name' expandable={ false }>Product Name</TableHeaderColumn>
<TableHeaderColumn dataField='price' expandable={ false }>Product Price</TableHeaderColumn>
</BootstrapTable>

**Comment by dekelb** [comment]
I think you are looking for #1039 
I already made a pool request for this feature: #1075

Hope @AllenFang will merge this soon :)

**Comment by AllenFang** [comment]
yap, the PR will support this feature, I'll merge it as soon as possible

**Comment by AllenFang** [comment]
Released on `v3.1.0` and check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/expand-indicator.js) to lear how to enable expand column, and check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/custom-expand-indicator.js) to lear how to custom expand column.

Let me know if you got any troubles, thanks and thanks @dekelb's contribution.
