### ISSUE TITLE
onRowClick functionality

### ISSUE THREAD

**Issue by sunnyownage** [AllenFang/react-bootstrap-table#1078]
Hi Allen,

Is it possible to selectively call onRowClick? For example, for one of my columns I have a button but I don't want my onRowClick function to be called when I click the button. The issue is that onRowClick is executed before my button click.

Thanks!

**Comment by AllenFang** [comment]
@sunnyownage, currently is not, but I think you can use event object to distinguish them.

Let me know if you still have any question :)
