### ISSUE TITLE
Custom columns

### ISSUE THREAD

**Issue by calvinfroedge** [AllenFang/react-bootstrap-table#108]
Is it possible to have an extra column in a table for actions? For example, a button like "View Details" which we can attach an event to like showing a modal.

Example:

Table
THEAD Product ID | Product Name | Actions
TBODY  1 | My test product | Button('View All Sales of This Product')

**Comment by AllenFang** [comment]
you can just add a field(column) in your data and use <a href="http://allenfang.github.io/react-bootstrap-table/example.html#column-format">column formation</a> for that column. Anyway, column formation supported the HTML and React components.
