### ISSUE TITLE
Path /@allenfang/react-toastr not found in group repository

### ISSUE THREAD

**Issue by yenhsiac** [AllenFang/react-bootstrap-table#1081]
Hi Allen,

I encounter this error while trying to install the latest version of react-bootstrap-table through our private npm repository. 

Path /@allenfang/react-toastr not found in group repository.

I am able to install v2.3.0 w/o any problem. Any idea is appreciated. Thanks!

Claire

**Comment by yenhsiac** [comment]
We are using Sonatype Nexus™ 2.11.4-01 for private repository management. Any workaround?

**Comment by AllenFang** [comment]
@yenhsiac, I may check [this](https://github.com/AllenFang/react-bootstrap-table/issues/863), feel free to discuss with me

**Comment by yenhsiac** [comment]
@AllenFang Thank you. This is not an issue any more for now we are able to bypass our group repository. Thank you for your awesome work on this project!

**Comment by celim307** [comment]
For anyone curious, I had the same issue when upgrading past 2.6.xx. I just set registry to the public npm registry when installing non-private modules

**Comment by AllenFang** [comment]
Thanks you guy's feedback, I gonna close this and any feedback is welcome :)

**Comment by VP42** [comment]
I'm sorry but setting the registry to the public npm registry is not an option for me (behind a firewall in a company). Therefore, I still have this issue :( Any clue about this one? Thanks so much!

```
npm install

npm ERR! registry error parsing json
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/Valentin/.nvm/versions/node/v6.6.0/bin/node" "/Users/Valentin/.nvm/versions/node/v6.6.0/bin/npm" "install"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3

npm ERR! Unexpected token < in JSON at position 0
npm ERR! <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
npm ERR! <html><head>
npm ERR! <title>404 Not Found</title>
npm ERR! </head><body>
npm ERR! <h1>Not Found</h1>
npm ERR! <p>The requested URL /repository/node-global/@allenfang/react-toastr was not found on this server.</p>
npm ERR! </body></html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>```

**Comment by celim307** [comment]
@vp42 

Can you clone it as its own repo and use npm link?

**Comment by AllenFang** [comment]
sorry this issue make some people noisy, there're no any better workaround to fix this issue if you can't got the scope package though your firewall. so If you really want to use it, you can clone `react-bootstrap-table` and `@allenfang/react-toastr` to your own repo and change the `react-toastr` to yourself one. It's very hacky and you need fetch upstream every time if remote got some update.

Anyway, if the the original `react-boastr` can fit [this](https://github.com/AllenFang/react-bootstrap-table/issues/863) issue, I think the all the problem will disappear.

**Comment by AllenFang** [comment]
https://github.com/AllenFang/react-bootstrap-table/issues/1152

**Comment by AllenFang** [comment]
please check #1216, if you have any concern or question, let me know in #1216

**Comment by VP42** [comment]
Thank you for keeping us posted about this issue, this is truly valuable!
