### ISSUE TITLE
csvFormat can use formatExtraData?

### ISSUE THREAD

**Issue by BracWebb** [AllenFang/react-bootstrap-table#1086]
This is a question -- is it possible to use `formatExtraData` in `csvFormat` just like in `dataFormat`? Or is it possible to make the CSV export use what is returned in `dataFormat`?

**Comment by AllenFang** [comment]
@BracWebb, sure, I'll add it as soon as possible after I back from my travel. Thanks

**Comment by AllenFang** [comment]
Fixed on `v3.1.0` and check https://github.com/AllenFang/react-bootstrap-table/commit/e185529f37dfa6e85336a9942b6c4b3aa6f6284c for examples

Let me know if you have any questions, thanks.
