### ISSUE TITLE
Adding a ToolTip on Pagination( prev,next buttons)

### ISSUE THREAD

**Issue by shalinibajpai0310** [AllenFang/react-bootstrap-table#1090]
Hi Allen,

I need to add a tooltip on my pagination icons( <,>,<<,>>). Is there any possibility available in react bootstrap table.

**Comment by AllenFang** [comment]
@shalinibajpai0310, sorry for lately reply due to my long trip ;)
I can support this feature but It need some time because there are too many things need to do.

If you can't wait, upgrade to `v3.0.0` and custom a pagination by yourself. BTW, currently we only support custom the size per page dropdown and the whole pagination panel, but pagination list not yet, this is a enhancement in near future anyway.

Let me know if you got any questions, thanks

**Comment by AllenFang** [comment]
Released on `v3.1.0` check there have the default tooltip and you can it, please check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/pagination/custom-pagination-table.js#L49-L52).

**Comment by usdarji** [comment]
options = {
                        nextPageTitle: true,
                        prePageTitle: true,
                        firstPageTitle: true,
                        lastPageTitle: true,
                        nextPage: <span className="next pagination-tooltip">{'>'}</span>,
                        prePage: <span className="prev pagination-tooltip">{'<'}</span>,
                        firstPage: <span className="first-page pagination-tooltip">{'<<'}</span>,
                        lastPage: <span className="last-page pagination-tooltip">{'>>'}</span>,
                       }
`
.pagination-tooltip {
                  position: relative;
                  display: inline-block;
                  width: 100%;
                  height: 100%;
                  margin: -6px -16px -6px -23px;
                  padding: 6px 21px;

                  &:hover{

                    &::before {
                      content: "";
                      position: absolute;
                      color: #fff;
                      background-color: #00b7ff;
                      padding: 3px 7px;
                      top: -29px;
                      left: 4px;
                      border-radius: 5px;
                      font-size: 12px;
                    }

                    &::after {
                      content: "";
                      position: absolute;
                      border-top: 5px solid #00b7ff;
                      border-left: 5px solid transparent;
                      border-right: 5px solid transparent;
                      top: -6px;
                      left: 20px;
                    }

                  }

                  &.next {

                    &:hover {

                      &::before {
                        content: "Next";
                      }

                    }

                  }

                  &.prev {

                    &:hover {

                      &::before {
                        content: "Prev";
                      }

                    }

                  }
                  &.first-page {

                    &:hover {

                      &::before {
                        left: -11px;
                        width: 72px;
                        content: "First Page";
                      }

                    }

                  }
                  &.last-page {

                    &:hover {

                      &::before {
                        left: -11px;
                        width: 72px;
                        content: "Last Page";
                      }

                    }

                  }

                }`
