### ISSUE TITLE
noDataText set colSpan more than columns

### ISSUE THREAD

**Issue by Infemo** [AllenFang/react-bootstrap-table#1091]
![colspanbug](https://cloud.githubusercontent.com/assets/16117857/23362573/755a724e-fd07-11e6-90d1-e9e3e5da329e.png)

**Comment by Infemo** [comment]
Problem was in property `scrollTop={'Bottom'}`.

**Comment by Infemo** [comment]
Solved by dirty hack like:
`bodyStyle={this.state.data.length!=0 ? {overflow:'overlay'} : {overflow:'hidden'}`

**Comment by AllenFang** [comment]
could you please show you code? I wanna know the root cause, thanks

**Comment by sorahn** [comment]
@AllenFang I Ran into this same issue.  I think this happens when you use the `hidden` attribute on a `TableHeaderColumn`.

https://github.com/AllenFang/react-bootstrap-table/blob/master/src/TableBody.js#L194 doesn't look like it accounts for hidden columns.

**Comment by Infemo** [comment]
@sorahn yes, i use few dynamic hidden columns.

**Comment by sorahn** [comment]
@Infemo you should re-open the issue :)

**Comment by AllenFang** [comment]
sorry for lately reply, just busy on work, I will check this out, thanks

**Comment by AllenFang** [comment]
Fixed on `v3.1.2`, please have a look, thanks :)
