### ISSUE TITLE
How to change CSS class of exportCSV button?

### ISSUE THREAD

**Issue by Steffi3rd** [AllenFang/react-bootstrap-table#1096]
How to change CSS class of exportCSV button?

I don't want the use bootstrap CSS class for this use. Is the possible to replace these class by our own CSS class?

Thanks!

**Comment by AllenFang** [comment]
@Steffi3rd, sorry for lately reply due to my long trip ;)
Use `v3.0.0` and custom it by your self, check [examples](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/custom/csv-button)

Let me know if you got any trouble in implement, thanks
