### ISSUE TITLE
Cell edit on key Tab press problems

### ISSUE THREAD

**Issue by francescabassi** [AllenFang/react-bootstrap-table#1099]
Hi everyone, 

I have a strange behavior when I press the key Tab on cell editing: for example, if I'm editing the second cell on a row and I press tab the focus goes in the previous cell and the value of this cell becomes equal to the second cell (the cell I started edit before).

I'm using the 3.0.0-beta.11 version.

How can I resolve this? 

Thank you

**Comment by AllenFang** [comment]
@francescabassi, could you please upgrade to `v3.0.0` and try again, if the problem still remain, please show me your example code(Keep it minimal and simple) thanks 👍

**Comment by AllenFang** [comment]
Fixed on `v3.1.0`, please upgrade and check this out. thanks
