### ISSUE TITLE
Bug: Toastr Error Does Not Display When Editing Cell

### ISSUE THREAD

**Issue by bennnjamin** [AllenFang/react-bootstrap-table#1101]
If you go to Insert & Cell edit example here http://allenfang.github.io/react-bootstrap-table/example.html#advance

When you edit cell directly (not insert), the cell shakes but no Toastr error message appears. This used to work before 3.0.0.

**Comment by AllenFang** [comment]
I'll check this out, thanks :)

**Comment by celim307** [comment]
In my code I return true in the beforeCellEdit but I do not get a toastr underneath my edited field, just plain text of the title and message. 

![capture](https://cloud.githubusercontent.com/assets/1838895/23568861/318ba812-0022-11e7-86f4-bc4f93576607.PNG)

**Comment by bennnjamin** [comment]
@AllenFang any update on this? The bug is still present

**Comment by AllenFang** [comment]
sorry for lately fix... very busy for my work and I've fixed it on my local, will be release soon. Sorry

**Comment by AllenFang** [comment]
Fixed on `v3.1.2`, please have a look, thanks

**Comment by bennnjamin** [comment]
@AllenFang The code looks good. I will test today. Thanks for your quick response.
