### ISSUE TITLE
call csv export as a function

### ISSUE THREAD

**Issue by JWDobken** [AllenFang/react-bootstrap-table#1104]
Is it possible to call the table export button as a function?

What I actually want is to generate the table and csv export from another page, without showing the table itself,  and I think this would be an elegant solution.

**MWE**
This is my bootstrap data table with export button:

    <BootstrapTable key="datatable" data={data} exportCSV csvFileName='table-export.csv'>
      <TableHeaderColumn dataField="dataType" isKey={true}>Data type</TableHeaderColumn>
      <TableHeaderColumn dataField="startedAt">Started at</TableHeaderColumn>
    </BootstrapTable>

I would like to call a function, for example `this.datatable.exportcsv()`

**Comment by AllenFang** [comment]
check http://allenfang.github.io/react-bootstrap-table/docs.html#handleExportCSV, use react ref to call a exposed api

let me know if you have any question

**Comment by JWDobken** [comment]
@AllenFang actually I'm still struggling with the auto-CSV export without showing the table.
I would like to do something like:

    table = (
      <BootstrapTable data={data} exportCSV search={true} striped={true} csvFileName='locations.csv'>
        <TableHeaderColumn dataField="LocationID" isKey={true}>LocationID</TableHeaderColumn>
        <TableHeaderColumn dataField="ProjectID">ProjectID</TableHeaderColumn>
      </BootstrapTable>)
    renderTable = false
    return (
      <div>
        {renderTable ? table : table.handleExportCSV()}
      </div>
    );

**Comment by AllenFang** [comment]
you should render table then call the function, because `table` is a reference on that react component.
