### ISSUE TITLE
onFocus event is not triggering when we use activeFormatter to render a cell 

### ISSUE THREAD

**Issue by iiitmanikanta** [AllenFang/react-bootstrap-table#1107]
with the new keyboard navigation and activeFormatter ....if we click on the node rendered by activeFormatter the defautl onFocus event is not triggering

**Comment by AllenFang** [comment]
could you show me your example, I guess this was an issue about event propagation.

**Comment by iiitmanikanta** [comment]
activeFormatter = (cell, row, dataField, index) => {
  return (
    <div title={cell} className='sample'>
      {cell}
    </div>
  )
}

here when we click the 'div' element of which is inside of the <td>...

the onFocus event is not triggered but when i clicked the corner of cell , it is invoking because the child has some padding with <td>

**Comment by iiitmanikanta** [comment]
even i added jquery onclick listener to 'sample' class name but still it is not invoking

**Comment by AllenFang** [comment]
What's version your used?  if you use `v3.x`, could you please help me to downgrade and test it again? thanks
