### ISSUE TITLE
How do I customize the onSearchChange ?

### ISSUE THREAD

**Issue by ferrwanz** [AllenFang/react-bootstrap-table#1109]
Hello Allen.
Is there any way to customize the result of search field?
I want to customize a column of "Name" which its value is from "First Name" and "Last Name". For the view I customize it with `dataFormat`.
```javascript
const customComponent = (cell, row) => (
  <span>{row.first_name} {row.last_name}</span>
)

const users = [
  { first_name: 'User', last_name: 'Test' },
  { first_name: 'User', last_name: 'Fake' },
  { first_name: 'User', last_name: 'Example' },
]

<BootstrapTable data={users} search>
  <TableHeaderColumn dataFormat={customComponent}>Name</TableHeaderColumn>
</BootstrapTable>
```
For the default the search is based on `dataField` and in this case it's not possible the `dataField`'s value has like 'first_name last_name'. So how do I make the search to return value consist of `first_name` and `last_name`?

**Comment by AllenFang** [comment]
There're couple workarounds you can choose, 

1. merge your source data with your expectation before you put them into table. ex:
```js
const users = [
  { row: 'seq1', name: 'User Test' }
];
```

2. The `dataField` is a best to assign, so you can assign any field you like and use `filterFormatted` to tell `react-bootstrap-table` to filter/search that column with formatted data instead original data
```js
<BootstrapTable data={users} search>
  <TableHeaderColumn dataField='first_name' dataFormat={customComponent} filterFormatted>Name</TableHeaderColumn>
</BootstrapTable>
```

3. use `filterValue`, you can also check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/search-format-table.js

Let me know if you have any questions, thanks

**Comment by shubuu97** [comment]
Hi Allen, 
 I want to implement remote search on react-bootstrap-table. I am using react-bootsttrap-table version 4.3.1. Currently we have onSearchChange method but i want onEnter event. Is there any way to do that?
