### ISSUE TITLE
Hooks for Before Delete / Filter what items can be deleted.

### ISSUE THREAD

**Issue by Islati** [AllenFang/react-bootstrap-table#1111]
I'm building an app which users are able to manage individual inventories via a table. However, come of these items have a flag which make them available to every user (global).

Is there a way to filter the items for deletion, or, to flag certain items as "able to be deleted" in any way?

If not, perhaps a hook for "beforeDeletion(rows)" would be appropriate? Returning either a list of the rows to be deleted, or something of that nature?

**Comment by AllenFang** [comment]
@TechnicalBro, sorry we haven't this kind of feature currently. Actually, delete row was trigged by user to check the checkbox(So you need to enable `selectRow` also), then click the delete button. So you you dont want the user to select some row to delete, you can make some row as **unselectable**

it it a good solution for you?

> perhaps a hook for "beforeDeletion(rows)" would be appropriate? Returning either a list of the rows to be deleted

which means no matter what's rows that user select, `react-bootstrap-table` always use the return values as the delete rows?

**Comment by TechnicalBro** [comment]
@AllenFang 

>  So you you dont want the user to select some row to delete, you can make some row as unselectable

That is a perfect solution for this problem.

> which means no matter what's rows that user select, react-bootstrap-table always use the return values as the delete rows?

This would be a great implementation aswell, for various reasons. Despite both being able to conquer this specific issue, the above gives more control over the table, while the first simply restricts the user (bare minimum) security.

**Comment by AllenFang** [comment]
ok, so there's anything you think is worth to implement now?

**Comment by AllenFang** [comment]
Close it due to no response since from one month ago, let me know if you still have any questions, thanks
