### ISSUE TITLE
Any ways to hide toolbar buttons when printing?

### ISSUE THREAD

**Issue by excelarcelo** [AllenFang/react-bootstrap-table#1112]
Hi Allen,

I am very new to programming and still taking baby steps to create a new app for my company. I came across with react-bootstrap-table and I love it. However is there any way to hide the insert/delete toolbar buttons when priniting or saving it as pdf?

Already checked #645

**Comment by AllenFang** [comment]
I will try to add `hidden-print` class to toolbar to hide it on printing,

**Comment by excelarcelo** [comment]
Thanks Allen!

**Comment by AllenFang** [comment]
Released on `v3.1.1`, check https://github.com/AllenFang/react-bootstrap-table/commit/6e1350cd0bc8ebe8e69149ae1780bd4f24b7583a

**Comment by excelarcelo** [comment]
Great Allen thanks!
