### ISSUE TITLE
How to filter data programmatically without matching cell text

### ISSUE THREAD

**Issue by CoralSilver** [AllenFang/react-bootstrap-table#1114]
I would like to apply a filter based on button click that instead of matching cell text, performs a custom filter function (ie checks if a date in a column is in the past and returns that row if user has clicked "past" button).  How do I tell the table what to show in that case?  Right now I am adding buttons in the table header.  The closest example I could find was your Custom Filter and started modifying it.

``` 
  //   targetValue is value of each start date cell before it has been parsed
  isFiltered(targetValue) {
    const currentDate = new Date;
    if (!targetValue) {
        return (this.refs.tbd);
    } else if (moment(targetValue).isBefore(currentDate)) {
      return (this.refs.past);
    } else {
      return (this.refs.upcoming);
    }
  }

**Comment by AllenFang** [comment]
so `isFiltered` is your custom filter function, right? and what is the `this.refs.tbd`, `this.refs.past`, `this.refs.upcoming`

As I know, you can create a custom filter in the header column and do your filtering by your custom function, so you can do any filter logic you like, but I'm not very sure what's you want(Sorry, english is not good), could you please explain more clearly?

thanks

**Comment by AllenFang** [comment]
close due to no response.
