### ISSUE TITLE
Cannot read property 'headerText' of undefined

### ISSUE THREAD

**Issue by salahcoffye** [AllenFang/react-bootstrap-table#1115]
I'm getting this error when I add search to my table.

`TypeError: Cannot read property 'headerText' of undefined
    at http://localhost:3000/static/js/bundle.js:102201:27
    at Array.map (native)
    at BootstrapTable.renderToolBar (http://localhost:3000/static/js/bundle.js:102197:31)
    at BootstrapTable.render (http://localhost:3000/static/js/bundle.js:101417:27)
    at http://localhost:3000/static/js/bundle.js:26822:22
    at measureLifeCyclePerf (http://localhost:3000/static/js/bundle.js:26101:13)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:3000/static/js/bundle.js:26821:26)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:3000/static/js/bundle.js:26848:33)`

**Comment by AllenFang** [comment]
could you please show me your code and keep it minimal and simple, and what's version you used?

thanks

**Comment by BijayRai** [comment]
Hey i am getting same issue 

> > "Uncaught (in promise) TypeError: Cannot read property 'headerText' of undefined"


i am doing remote sorting, remote pagination and remote searching.. 
remote sorting and remote pagination works well whenever i place 

> > search={ true }


on options it gives me this error.. if i removed this from options then my table is working pretty cool..

**Comment by BijayRai** [comment]
when i do something like this it works perfectly (just an example)-->

```
<BootstrapTable data={ products } search={ true } options={ options }>
          <TableHeaderColumn dataField='id' isKey dataSort={true}>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name' dataSort={true}>Fruit Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price' dataSort={true}>Product Price</TableHeaderColumn>
      </BootstrapTable>
```
but when i use map function to populate TableHeaderColumn it gives me that error

```
render(){
             const TableBody = this.props.data.map(function (data) {
             return (<TableHeaderColumn key={data.key} dataField={data.key} 
                         filter={ {type: 'TextFilter'} } dataSort={true} >{data.title}
                         </TableHeaderColumn>)
		});
return(
               <BootstrapTable data={ products } search={ true } options={ options }>
                     <TableHeaderColumn dataField='id' isKey dataSort={true}>Product ID</TableHeaderColumn>
                     {TableBody}
              </BootstrapTable>
);
}
```

removing search={true} sorting and fliter is working perfectly over map function too..

**Comment by AllenFang** [comment]
> but when i use map function to populate TableHeaderColumn it gives me that error

I think this is maybe the root cause, I dont think the search is the problems here, if true, there're must have same issue at before.

@salahcoffye, could you please show me your case? thanks

**Comment by shyjal** [comment]
Same issue here. I can't use exportCSV while using map to render TableHeaderColumn

**Comment by AllenFang** [comment]
@shyjal, did you enable `search`?

**Comment by AllenFang** [comment]
ok, I got the problem, if you use map for creating the `TableHeaderColumn`, please do not doing this
```js
<BootstrapTable data={ products } search={ true } options={ options }>
   <TableHeaderColumn dataField='id' isKey dataSort={true}>Product ID</TableHeaderColumn>
   { columns }
</BootstrapTable>
```

Please use following, if you feel `isKey` is noisy, you can use `keyFile` on `BootstrapTable` instead.
```js
<BootstrapTable data={ products } search={ true } options={ options } keyField='id'>
   { columns }
</BootstrapTable>
```

Let me know if the problem still remain, thanks

**Comment by shyjal** [comment]
@AllenFang I enabled exportCSV and got this issue. Moved all TableHeaderColumn components inside map like you mentioned,now the issue is solved. Thank you.

**Comment by genau7** [comment]
What if I would like to to this (this is a pseudo code):
<BootstrapTable>
{mapped TableHeaderColumns}
<TableHeaderColumn dataField='id' isKey dataSort={true}>Product ID</TableHeaderColumn>
</BootstrapTable>

So basically I would like to map my data to header columns, but also have a custom column (in my case, a column containing delete buttons, one for each row). This is not working, Any suggestions?

**Comment by AllenFang** [comment]
@genau7, use `keyField` on `BootstrapTable` instead of `isKey` on `TableHeaderColumn`

Also, even if you have different custom children for `TableHeaderColumn`, I think you still can use in a map function, 

some pseudo code like this:

```js
headers.map(header => {
    return (
        <TableHeaderColumn key={header.key} dataField={header.key}>
            {   isFunction? header.title() : header.title  }
         </TableHeaderColumn>
    );
});

// header title if is a function, you can return a custom JSX or react component
```
