### ISSUE TITLE
Number of selected rows

### ISSUE THREAD

**Issue by SimonDKnight** [AllenFang/react-bootstrap-table#1119]
Hi, I am trying to make a child component for react bootstrap table which tells me how many rows have been selected once they have selected the select all button (like in gmail). The component looks something like this

return (<p> There are { this.refs.table.state.selectedRowKeys } selected out of { this.state.institutions.length } items.</p>)

The problem is I cannot seem to get access to this.refs.table.state.selectedRowKeys AFTER the state has updated to then update my component. If I look in the method onSelectAll(isSelected) its too early to see the number of rows selected?

Any ideas?

My main goal is that when the user selects the select all button some text appears saying "You have selected 10 of 1000 rows. Click here to select all 1000 rows."

Thanks

**Comment by AllenFang** [comment]
@SimonDKnight, how about use `onSelectAll` and you can get the select row quantity in the callback function, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/select-hook-table.js#L34 
So you can update your component after you get the quantity in this callback function

Let me know if you got any questions, thanks :)
