### ISSUE TITLE
Suggestion: Better title/explanation for example 'Disable Click to Trigger Navigation'

### ISSUE THREAD

**Issue by tomahawkzx** [AllenFang/react-bootstrap-table#1120]
Hi folks! First of all I want to give the congratulations to the team, I'm very impressed with this library!

By navigating through the examples, I've came across this one in particular that I cannot exactly tell what is its purpose. I've noticed that the keyboard navigation sometimes stops when you click in some check box, but is not a constant behavior. 

I think this deserves a better explanation for the newcomers (such me). Sorry if I'm questioning something too obvious, I didn't managed to understand what is the point of this sample.

Here is the link for the mentioned example:
http://allenfang.github.io/react-bootstrap-table/example.html#keyboard-navigation
"Disable Click to Trigger Navigation"

**Comment by AllenFang** [comment]
@tomahawkzx, sorry for lately reply, I'll check this out, because I'm pretty busy in recently, so need some time, sorry :(

**Comment by tomahawkzx** [comment]
Thank you @AllenFang.

I've take a look at it again, and now I've figured that it means to restrict the navigation to "keyboard only", disabling the navigation for mouse click.

At the samples you are already providing a better explanation. 

### react-bootstrap-table/blob/master/examples/js/keyboard-nav/demo.js

```
<Panel header={ 'Disable Click to Nav Example' }>
          { renderLinks('keyboard-nav/disable-click-to-nav-table.js') }
          <span>
            <code>keyBoardNav</code> accept a bool or object value<br/>
            Use <code>keyBoardNav.clickToNav</code> to disable the navigation on clicking cell<br/>
            If you disable it, you can still navigate with tab and left/right/up/down
          </span>
          <DisableClickToNavTable />
</Panel>
```

I think this description would be clear enough to explain this example. Just need to update it on examples website at http://allenfang.github.io/react-bootstrap-table/example.html
;)

**Comment by AllenFang** [comment]
ok, I'll, thanks 👍

**Comment by AllenFang** [comment]
Sorry for lately fix, the example on website updated.
