### ISSUE TITLE
handleAddRowAtBegin In Modal Adds Row To Table But Disappears When Modal Closed

### ISSUE THREAD

**Issue by AaronONeill** [AllenFang/react-bootstrap-table#1121]
Hey,

I am trying to dynamically insert a row in a table based on information the user enters in a form in a modal popup. Once the use has clicked save changes, I used the following code to create the object and pass it to the table via "handleAddRowAtBegin".

`var rowData = {
	postid: this.state.postid,
	cny_id: this.state.cny_id,
	cny_name: this.state.cny_name,
	update_date: this.state.update_date,
	update_comment: this.state.update_comment
};

var result = this.props.table.handleAddRowAtBegin(rowData);

if (result){  // some error happened, ex: didn't assign row key or row key was duplicated
	console.log('######### ERROR - Add Row To Table #############');
	console.log(result);
} else {
	 this.props.hide();
}`

The hide function which set the open state to false in order to hide the modal.

`hide() {
    this.setState({ open: false });
  }`

This seems to work perfectly until I try and close the modal popup. There is a state for "open" which is either true or false, whenever I try to set it to false dynamically the newly added row in the table disappears and I cannot figure out why. 

Any help here would be appreciated.

**Comment by AllenFang** [comment]
sorry for lately reply, I'm busy here for my work, so I'll have a look on it. I've some questions
1. the modal is all custom by yourself, is that the `react-bootstrap-table` insert modal?
2. did you enable pagination?

**Comment by AllenFang** [comment]
close it due to no any response since from 7 Mar
