### ISSUE TITLE
hideSelectColumn not working in table header 

### ISSUE THREAD

**Issue by ddorsett** [AllenFang/react-bootstrap-table#1122]
I am getting a blank table cell in the header row. It's appears to be coming from a SelectRowHeaderColumn component, although I am passing in mode: 'radio' and hideSelectColumn: true as part of the selectRow object in the table properties. 
When I don't include 'hideSelectColumn: true', the table header is fine. I really don't want the radio buttons (unneccessary waste of UI in my case)

**Comment by JohnUiterwyk** [comment]
I'm also having this issue

**Comment by ddorsett** [comment]
That patch did it for me- Thanks John!

**Comment by AllenFang** [comment]
sorry guys, I'm pretty busy on my job, I'll have a look for this PR and merge it as soon as possible. Thanks :)

**Comment by AllenFang** [comment]
Released on v3.1.1
