### ISSUE TITLE
how to select all data items

### ISSUE THREAD

**Issue by SimonDKnight** [AllenFang/react-bootstrap-table#1125]
Hi, thanks for answering all my previous questions, I appreciate it. I have one more question. How would I go about selecting all items in the table, not just those on the current page. I want to create a child component which has a link which when clicked will select all data items in the table.

Thanks again.

**Comment by AllenFang** [comment]
https://github.com/AllenFang/react-bootstrap-table/issues/537#issuecomment-237590036 is the same issue here, sorry for reply late, cause of busy on my job.


Let me know if you still have any questions, thanks :)
