### ISSUE TITLE
Expandable Row incompatible with Pagination

### ISSUE THREAD

**Issue by silentbobbert** [AllenFang/react-bootstrap-table#1127]
If you have more than 10 rows of data in your table, and the default pagination is 10 per page, the first 10 rows' "expandable" content appears as expected, but row 11 on-wards do not display the correct content in the expanded component element.

If you increase the items per page it doesn't really help either. I believe its repeating the content of the first 10, so item 11 would display content from the first item, item 12 from the second item and so on.

**Comment by dekelb** [comment]
Can you provide an example?

Basically the `expandComponent` property of the `BootstrapTable` gets a function that should receive the content of the expanded row based on the current row you clicked.

The `expandCompnent` function receives 1 argument which is the current row you are in:

	function expandComponentFunction(row) {
		return (
			<div>This is the expanded content for row { row.id }</div>
		);
	}

	<BootstrapTable
		...
		expandComponent={ expandComponentFunction }
		...
	>

**Comment by silentbobbert** [comment]
In body of class - same way you declare the render() function:
```
expandComponent(row) {
        return (
            <UpdatePackageComponent
                data={row}
                licenceTypes={this.props.licenceTypesData.licenceTypes}
                save={this.save}
            />
        );
    }
```

In render() method:
```
<BootstrapTable
    data={this.props.mapData(this.props.data)}
    striped={true} hover={true}
    search={true}
    exportCSV={true}
    options={options}
    expandableRow={() => { return true; }}
    expandComponent={this.expandComponent.bind(this)}
>
     <TableHeaderColumn dataFormat={this.expander} width="40" />
     <TableHeaderColumn dataField="packageName" isKey={true} dataSort={true} width="350">Name</TableHeaderColumn>
     <TableHeaderColumn dataField="packageVersion" dataSort={true} width="100">Version</TableHeaderColumn>
     <TableHeaderColumn dataField="packageSource" dataSort={true}>Source</TableHeaderColumn>
     <TableHeaderColumn dataField="licenceUrl" dataFormat={this.urlFormatter}>Licence</TableHeaderColumn>
     <TableHeaderColumn dataField="licenceType" dataFormat={this.licenceTypeFormatter} dataSort={true}>Licence Type</TableHeaderColumn>
</BootstrapTable>
```

Data that is mapped is just flattened using a mapping function.

`<UpdatePackageComponent />` 

Is a wrapper around a bunch of markup giving the expanded content some pretty look and feel, but the row data is passed down on props to the data prop.

I am using bind to control the context of "this" so that I have access to the props to pass down other functions/data to my markup component.

`expandComponent={this.expandComponent.bind(this)}`

**Comment by silentbobbert** [comment]
One thing I didn't notice - I only started using this package a few days ago and used the latest version which was 3.0.0 - I just noticed 3.1.0 came out and you have some commits in there to do with pagination in it - a quick test of 3.1.0 seems to show my problem has been resolved between versions. Thanks!
