### ISSUE TITLE
Hide column filter(search) input box

### ISSUE THREAD

**Issue by mswaminath** [AllenFang/react-bootstrap-table#1128]
How to achieve hiding the column filter(initially) and show it only on mouse over(or show some image) on column header?

**Comment by AllenFang** [comment]
I think u can use custom filter because we dont have this feature now and it's not worth to support it, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js to learn how to custom it.

Let me know if you got any questions, thanks

**Comment by mswaminath** [comment]
Alright, but how do I handle the filter with the table data's. Is there any method specified in the Docs so that I can write my own filter?

**Comment by mswaminath** [comment]
Or can you give an example for input box for custom filter?

**Comment by AllenFang** [comment]
just in the example I mentioned above, https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js#L34  line 34

**Comment by mswaminath** [comment]
Thanks for pointing out the line. I have achieved as a custom filter now. Just wanted to share this, the input text box value can be accessed with the refs as `this.refs.filterBox.value`.

Thanks a lot for this project, it helped a lot. Will share this custom textbox filter as one of the example if it's fine?

**Comment by AllenFang** [comment]
thanks your sharing 👍
