### ISSUE TITLE
How to tap into filteredData that is being display?

### ISSUE THREAD

**Issue by khinlatt** [AllenFang/react-bootstrap-table#113]
@AllenFang, is there an easy way to expose the filteredData (after searching) back out to the component, rendering BootstrapTable?

**Comment by AllenFang** [comment]
@khinlatt, maybe I can support the after filtering and searching hook and pass the filtered data as params

**Comment by khinlatt** [comment]
@AllenFang actually I am just going to make another PR instead. I think it will be a good feature to this component. It will print out whatever is on the table to CSV. Going to close this issue. Thanks.

**Comment by AllenFang** [comment]
OK, any problems about api design, you can ask me :)

**Comment by khinlatt** [comment]
great. will do. appreciate it.

**Comment by khinlatt** [comment]
@AllenFang hey when you say "pass the filtered data as params", could you explain a bit more? It would be of great help if I can access to the filteredData from my react components somehow.

**Comment by AllenFang** [comment]
I mean the <code>react-bootstrap-table</code> will take the filtered data as params and pass to the hook function, if I implemented, it will look like following:

```javascript
var options = {
    afterFilitering:  function(filteredData){
         //filteredData is data which apply your filter expression
    },
    afterSearch:  function(result){
        //result is searched result
    }
}
//..
<BootstrapTable options={options} ...>
```

**Comment by khinlatt** [comment]
Ah I see. That's pretty neat. I do have a follow-up question. When you also turn on pagination, filteredData will always be whatever on the first page. Correct? How can we also tap into all of the filteredData (from Search), not just the one on the first page.

"Export to CSV" should really be producing all the filteredData.

Thanks a lot.

**Comment by AllenFang** [comment]
It's correct, if you use the <code>store.get()</code> and enable pagination, the result will be the data which in current page, but you explain is right, I should support another function on <code>store</code> for get the all result(I'll do it in tomorrow). However, the after searching and filtering hook, did you implement? if not, I can do it in tomorrow :)

**Comment by khinlatt** [comment]
If you can look into that CSV PR and work on that store to get all the result. That would be great.

I will attempt at searching and filtering hook. Will keep you posted. Are searching and filtering actually two different things? Can you explain me the difference between those two? Thanks.

**Comment by AllenFang** [comment]
Searching and filtering is two different thing, so I will separate <code>afterSearchOrFilter</code> to <code>afterSearch</code> and <code>afterFilter</code> base on your PR #123

**Comment by AllenFang** [comment]
Close it, check <a href='https://github.com/AllenFang/react-bootstrap-table/blob/master/CHANGELOG.md'>CHANGELOG</a>. <code>afterSearch</code> & <code>afterColumnFilter</code> has been supported on v1.2.7
