### ISSUE TITLE
Multiple tables in one react page

### ISSUE THREAD

**Issue by Lukis90** [AllenFang/react-bootstrap-table#1131]
Hello,

I was trying to render several tables in one react page, but I am able to render only the first table. Is there a way to render several tables?

**Comment by devjeff** [comment]
I'm able to render multiple tables on one page (but using the same component). Are you referring to multiple instances of the same component, or multiple components?

**Comment by AllenFang** [comment]
Thanks @devjeff  reply, @Lukis90, I think you have something wrong, it's not a bug for `react-bootstrap-table`, you can check the examples on http://allenfang.github.io/react-bootstrap-table/example.html#basic, everything work fine

**Comment by shorif2000** [comment]
@AllenFang i have this same issue. i can render 1st bootstrap table but if i try to add another table in another component it does not work
