### ISSUE TITLE
How to support onClick function on link button formatter of column?

### ISSUE THREAD

**Issue by binbin78** [AllenFang/react-bootstrap-table#1132]
I have a  link button formatter on my column, I am trying to add onClick attribute on it. But it won't work and GUI hang.  

actionFormatter(cell, row) {
        return (

            <Button className="btn-link" onClick={this.onDetailsClicked()}>
                Details
            </Button>

        );
    }

**Comment by binbin78** [comment]
I also have rowSelection handler in my code. when I click the link button, it calls my rowselect function instead of button's onClick
  const selectRowProp = {
                mode: 'checkbox',
                clickToSelect: true,
                onSelect: this.onRowSelect
            };

**Comment by voidjumper** [comment]
The GUI hangs because the function is immediately invoked.
Just remove the brackets from the click handler and it should work:
`<Button className="btn-link" onClick={ this.onDetailsClicked }>Details</Button>`

**Comment by fgiarritiello** [comment]
I think the problem is that since clickToSelect is set to true when I click on the button both the button and the row are being clicked. The expected behavior should be that only the button should be clicked. Anyway to fix this?

**Comment by AllenFang** [comment]
hey guy, sorry for lately reply cause of busy job...

You can call the `e.stopPropagation` for you button or link click, it will stop the event bubble up for preventing the row selection.

Let me know if you have any questions, thanks

**Comment by fgiarritiello** [comment]
Thanks Allen, that worked.

**Comment by brunoguedao** [comment]
```
class GameList extends Component {
constructor(props) {
    this.columns = [
    {
      dataField: 'game',
      formatter: this.rowGame
    }
}

rowGame(cell, row) {
 
    return (
      <div><Button onClick={this.betGame.bind(this,row.id)}>Action</Button></div>
    );
  }
}
export default GameList;
```

Hello can anyone help me? I have this component, but i cant call the function inside the rowGame formatter function.

**Comment by Pratiktarade** [comment]
facing same issue
