### ISSUE TITLE
BUG: Tab between editable cells when editing

### ISSUE THREAD

**Issue by Siyfion** [AllenFang/react-bootstrap-table#1137]
Would it be possible to make it so that when you press Tab when editing a cell, it automatically switches to editing the next editable cell on the row, or, in the next row if not?

**Comment by AllenFang** [comment]
We already have this kind of feature, make sure you upgrade to `v3.x` and press tab on any editing cell. There's no any configuration, it's the default.

**Comment by Siyfion** [comment]
@AllenFang Well it's broken then, because it doesn't work that way in practice... I'll show a gif.

**Comment by Siyfion** [comment]
http://recordit.co/aLFFCA28z0

**Comment by Siyfion** [comment]
When the edit cell closes, that's me pressing the TAB key.

**Comment by AllenFang** [comment]
show me your code and please keep it simple and minimal for me to reproduce and understand, it's very important, I'm pretty busy so that no time to debug your code, so just a most simple case for me to reproduce it, thanks.

**Comment by Siyfion** [comment]
@AllenFang Ask and you shall receive: https://jsfiddle.net/c11xmswn/

Please can this issue be re-opened?

**Comment by AllenFang** [comment]
sure, I'll check this out, but maybe need some time, pretty busy for me, sorry

**Comment by AllenFang** [comment]
Fixed on `v3.1.4`, please have a look, thanks
