### ISSUE TITLE
Row select bug

### ISSUE THREAD

**Issue by marin101** [AllenFang/react-bootstrap-table#1138]
I think I've found a peculiar bug. I need to enable and disable row selection dynamically. I wasn't able to do this in any way so I opened an issue.

This is the code:
`const selectRowProp = {
	mode: "checkbox",

	onSelect: this.handleSelect,
	onSelectAll: this.handleSelectAll,

	selected: this.props.selectedSchemas
};`

`<BootstrapTable data={schemas} search condensed striped hover insertRow deleteRow
	selectRow={this.props.filter ? selectRowProp : {}}
	options={options} cellEdit={cellEditProp}>`

![screenshot from 2017-03-10 20 14 18](https://cloud.githubusercontent.com/assets/22985405/23810109/7fd61a44-05d0-11e7-8dca-499e2b299270.png)
![screenshot from 2017-03-10 20 14 30](https://cloud.githubusercontent.com/assets/22985405/23810111/8302d5c2-05d0-11e7-9dbc-213647586deb.png)

You can see the exception that is thrown when I disable the filter checkbox which should remove row selection checkboxes in the react-bootstrap-table. I presume this is due to some internal state in the react-bootstrap-table

**Comment by marin101** [comment]
I also tried:

`const selectRowProp = {
mode: "none",

onSelect: this.handleSelect,
onSelectAll: this.handleSelectAll,

selected: this.props.selectedSchemas
};`

`<BootstrapTable data={schemas} search condensed striped hover insertRow deleteRow selectRow={selectRowProp} options={options} cellEdit={cellEditProp}>`

**Comment by AllenFang** [comment]
@marin101, sorry for lately reply due to busy job...  from your behavior you mentioned above, is that you want to select/de-select all of the rows? if yes, could you please show me how you did it? thanks

**Comment by marin101** [comment]
@AllenFang, this is the desired behaviour :

Enabled rows selection (you can see the checkboxes on the left)
![screenshot from 2017-03-10 20 14 18](https://cloud.githubusercontent.com/assets/22985405/23860292/d032928c-0806-11e7-9369-5da8c05a8be8.png)

Disabled rows selection (no checkboxes on the left)
![screenshot from 2017-03-13 16 00 09](https://cloud.githubusercontent.com/assets/22985405/23860134/4fdfd982-0806-11e7-9237-776e79481ce4.png)

My use case demands that I have two modes of operation: when I have row selection enabled and when there is no point in selecting rows. Change between the two modes of operation occurrs dynamically when user selects/deselects the filter option listed in the table header.

I managed to circumvent this bug(if it is a bug) by conditionally rendering two different tables(one has selectRow prop, the other one doesn't) for now.

**Comment by AllenFang** [comment]
@marin101, sorry for reply late, I'll check this out, I guess this maybe a bug, but need some time to process it, I'm pretty busy, sorry guy.

**Comment by AllenFang** [comment]
Fixed on `v3.1.4`, please have a look, thanks
