### ISSUE TITLE
After install react-bootstrap-table: Error: Can't resolve 'react/lib/ReactDOM'

### ISSUE THREAD

**Issue by RluLee** [AllenFang/react-bootstrap-table#1139]
After install react-bootstrap-table: Error: Can't resolve 'react/lib/ReactDOM'
In the official example of the operation, also reported the same error

**Comment by RluLee** [comment]
ERROR in D:/text/my01/~/.15.3.2@react-dom/index.js
Module not found: Error: Can't resolve 'react/lib/ReactDOM' in 'D:\text\my01\nod
e_modules\.15.3.2@react-dom'
 @ D:/text/my01/~/.15.3.2@react-dom/index.js 3:17-46
 @ ./home.js

`import ReactDOM from 'react-dom';
import { Steps , Layout , Breadcrumb , Menu , Icon } from 'antd';
import 'antd/dist/antd.css';
import Btn from './Btn';`

**Comment by RluLee** [comment]
`"react": "^15.4.2",
    "react-bootstrap-table": "^3.1.1",
    "react-dom": "^15.4.2",
"webpack": "^2.2.1"`

**Comment by AllenFang** [comment]
I'm not sure what's the root cause, maybe with the `webpack2`? and there's any duplicated `react` or `react-dom` in your dependencies?

**Comment by XidongHuang** [comment]
Hi, @AllenFang 
Having the same problem here. 
My lib versions are:
```
"dependencies": {
    "axios": "0.16.0",
    "bootstrap": "3.3.7",
    "react": "15.5.4",
    "react-bootstrap": "0.31.0",
    "react-dom": "15.5.4"
  },
  "devDependencies": {
    "babel-core": "^6.24.1",
    "babel-loader": "^7.0.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "css-loader": "^0.28.1",
    "extract-text-webpack-plugin": "^2.1.0",
    "file-loader": "^0.11.1",
    "html-webpack-plugin": "^2.28.0",
    "jsx-loader": "^0.13.2",
    "react-hot-boilerplate": "^1.0.0",
    "react-hot-loader": "^1.3.1",
    "rimraf": "^2.6.1",
    "style-loader": "^0.17.0",
    "url-loader": "^0.5.8",
    "webpack": "^2.5.0",
    "webpack-dev-server": "^2.4.5"
  }
```
Once I try
`import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';`
Then in webpack-dev server
```
ERROR in ./~/react-modal/~/react-dom/index.js
Module not found: Error: Can't resolve 'react/lib/ReactDOM'
```
Any hints about this?
Thank you so much.

**Comment by AllenFang** [comment]
Good job @XidongHuang
