### ISSUE TITLE
When using a dataFormat column hiding breaks

### ISSUE THREAD

**Issue by tbaeg** [AllenFang/react-bootstrap-table#114]
When using a custom formatter, the ability to hide the column fails. The column header disappears as it should but data associated to the column does not.

**Comment by AllenFang** [comment]
You means you apply a formatter on a hidden column?

**Comment by tbaeg** [comment]
Hey @AllenFang thanks for your responsiveness! 

To clarify, no I mean when I apply a `dataFormatter` and through the `<TableColumnHeader />` component change the property of `hidden` the columns that should disappear fail to disappear. 

When I get a chance I'll give an example. Little tired at the moment.

**Comment by AllenFang** [comment]
OK, give me an examples in near days. Thanks :)

**Comment by bastiao** [comment]
this issue is still alive.

**Comment by AllenFang** [comment]
I've fix this issue, will release in near future.

**Comment by AllenFang** [comment]
I've released on ```v1.4.3``` for fixing this bug :)
