### ISSUE TITLE
Cannot read property 'isKey' of undefined

### ISSUE THREAD

**Issue by CoralSilver** [AllenFang/react-bootstrap-table#1140]
Where should I be loading remote data so that it loads before the table tries to render (mount I guess in React speak)?  I'm loading it in `componentWillMount` but I get a `Cannot read property 'isKey' of undefined` error before the data is loaded.  I'm initializing the property state as an empty array in the constructor:
```
export default class PendingPaymentsPage extends React.Component {
  constructor(props) {
        super(props);
        this.state = {
            checks: []
        };

        this.options = {
          defaultSortName: 'name',  // default sort column name
          defaultSortOrder: 'desc'  // default sort order
        }
    }
    ........
}
```
<img width="1251" alt="screen shot 2017-03-10 at 9 14 03 pm" src="https://cloud.githubusercontent.com/assets/6298173/23819787/4656e95c-05d9-11e7-948a-75e2f82e31b9.png">

And then an error that the component failed to update...
<img width="1261" alt="screen shot 2017-03-10 at 9 16 13 pm" src="https://cloud.githubusercontent.com/assets/6298173/23819789/589447c2-05d9-11e7-9c1a-72cc817f9dd5.png">

**Comment by AllenFang** [comment]
@CoralSilver, sorry for lately reply cause of my busy job..  could you please show me you code exmaples? and keep it simple and minimal for me to reproduce and understand. BTW, what's the version you used?

**Comment by CoralSilver** [comment]
Thanks I got it working

**Comment by dkhonig** [comment]
I'm having the same issue. I'm trying to pass in an empty array as the data parameter and this error gets thrown:
<img width="1646" alt="screen shot 2017-03-27 at 3 09 18 pm" src="https://cloud.githubusercontent.com/assets/2054377/24373485/7aaabbba-12ff-11e7-91ac-53fb54002333.png">

Here's the structure of the table I'm using, "assessment.routes" is an empty array.
<img width="719" alt="screen shot 2017-03-27 at 3 10 38 pm" src="https://cloud.githubusercontent.com/assets/2054377/24373547/aee81a6c-12ff-11e7-9d15-37e01e486c25.png">

**Comment by AllenFang** [comment]
I'm not sure how @CoralSilver  solve this issue, but for me, I think this is not a bug, so please make sure that you have empty array and only have one `isKey` defined on `TableHeaderColumn`. please let me know if the problem still remain after your checking.

BTW, `onChange` on `BootstrapTable`  is do nothing, we dont support `onChange` on `BootstrapTable`

**Comment by TMandzu** [comment]
I had the same problem:

<BootstrapTable key={ Utils.getRandomNumber(1000000000) }
                      data={ data }
                      hover
                      search>
       // some god damn comment here
        <TableHeaderColumn width='200px' dataField='id' isKey={ true }>id</TableHeaderColumn>
        <TableHeaderColumn width='200px' dataField='shard' filter={{type: 'RegexFilter'}}>shard</TableHeaderColumn>
        <TableHeaderColumn width='200px' dataField='source' dataFormat={ colorFormatter }>source</TableHeaderColumn>
        <TableHeaderColumn width='400px' dataField='target' dataFormat={ colorFormatter }>target</TableHeaderColumn>
      </BootstrapTable>

Then I guessed comment is not allowed there. So, this error might be syntax based error....

**Comment by TMandzu** [comment]
![selection_075](https://cloud.githubusercontent.com/assets/8290797/24480816/44d5aa7a-149b-11e7-9ec1-3132a7ef1d93.png)

I had the same problem. I then guessed comments are not allowed there. So, this problem might caused by syntax errors...

**Comment by stevelacerda7** [comment]
Interesting, same issue here. If there's comments, then I get an undefined key error.

**Comment by kishankhakhar747** [comment]
I have defined the keyField='EmployeeNumber' which is present in my data and still when I add search attribute, it throws the error of 
"Cannot read property 'isKey' of undefined".

Without the search attribute, everything works fine.
Any suggestions?

**Comment by GotUser** [comment]
In my case  it was because of

`<TableHeaderColumn dataField='AgentName' >Name</TableHeaderColumn></BootstrapTable>`  in which BootstrapTable's  Closing tag was on a same line .

it should be there on a new independent line.

for details check [Here](https://easytechnolearn.blogspot.com/2019/06/cannot-read-property-iskey-of-undefined.html)
