### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onToggleDropDown' of undefined

### ISSUE THREAD

**Issue by thangytp** [AllenFang/react-bootstrap-table#1141]
Hi all,

I tried to use react bootstrap table in my project and got this problem.

Any idea to fix it?

Thanks

**Comment by AllenFang** [comment]
could you please show your code and describe what condition or scenario you encounter? thanks

**Comment by thangytp** [comment]
Hi AllenFang,

Here is my code:

`onToggleDropDown(onToggleDropDown){
        // do your stuff here
        console.log('toggle dropdown');
        onToggleDropDown();
    }
    renderSizePerPageDropDown(props){
        return (
            <SizePerPageDropDown
                className='my-size-per-page'
                btnContextual='btn-warning'
                variation='dropup'
                onClick={ () => this.onToggleDropDown(props.onToggleDropDown) } />
        );
    }`
...
`render(){
const options = {
            sizePerPageDropDown: this.renderSizePerPageDropDown,
            defaultSortName: 'createDate',  // default sort column name
            defaultSortOrder: 'desc'  // default sort order
        };
return (
<BootstrapTable data={listUsers} striped={true} hover={true} options={ options } pagination selectRow={ selectRowProp }>
                            ...
                        </BootstrapTable>
);
}
`
I use it to paginate the list of users.

**Comment by thangytp** [comment]
When i click on toogle dropdown to select number of element perpage and got this line in console of browser:
Uncaught TypeError: Cannot read property 'onToggleDropDown' of undefined

**Comment by AllenFang** [comment]
I guess the problems is 

`onClick={ () => this.onToggleDropDown(props.onToggleDropDown) }`
change to 
`onClick={ () => this.onToggleDropDown(props. toggleDropDown) }`

Let me know if the problems still remain, thanks

**Comment by thangytp** [comment]
Hi AllenFang, it doesn't work

**Comment by thangytp** [comment]
Hi AllenFang.
Do you have any idea to fix it?

**Comment by AllenFang** [comment]
`onClick={ () => this.onToggleDropDown(props.toggleDropDown) }`

use this one is not work for you??  I cant reproduce this issue.

**Comment by thangytp** [comment]
Yes, I do the same with example but it doesn't work

**Comment by AllenFang** [comment]
what's version you used? and any full example for me to reproduce? keep it simple and minimal, thanks

**Comment by thangytp** [comment]
Hi AllenFang, I have checked your example and edit my code like your example and it work very well.
Thank you very much for considering my issue.

Great package and good support that I have met!
Once again, thank you! 👍

**Comment by AllenFang** [comment]
👍

**Comment by StohlmanMatteo** [comment]
Been looking everywhere and can't figure out why I am having this same issue. 
Here is my code:
class listElement extends Component{	
	constructor(props){
		super(props);
	}
	onToggleDropDown(toggleDropDown){
	  // do your stuff here
	  console.log('toggle dropdown');
	  toggleDropDown();
	}
	renderSizePerPageDropDown(props){
		console.log(this);
		return (
		<SizePerPageDropDown
		  className='my-size-per-page'
		  btnContextual='btn-warning'
		  variation='dropup'
		  onClick={ () => this.onToggleDropDown(props.toggleDropDown) }/>
		);
	}
	render(){
		var data=this.props.loads;
		const options = {
			sizePerPageList: [ 
								{
							      text: '10', value: 10
							    },
								{
							      text: '20', value: 20
							    }, 
							    {
							      text: '30', value: 30
							    }, 
							    {
							      text: 'All', value: data.length
							    } ],
			sizePerPage: 10,
			sizePerPageDropDown: this.renderSizePerPageDropDown
			};
		function objectFormat(data, cell) {
			if(data.constructor===Array){
				if(data[0]=='last'){
					return `<p>${cell[data.length-1][data[1]]}</p>`
				}
				return `<p>${cell[data[0]][data[1]]}</p>`
			}
			return `<p>${cell[data]}</p>`;
		}
		
		return(
			<div className='listWrapper'>
			<BootstrapTable 
				data={ data }
				striped
				hover
				condensed
				pagination
				insertRow
				search
				selectRow={selectRow}
				ignoreSinglePage
				options={ options }
				variation='dropup'
				//height='80%'
				//tableStyle={ { background: '#00ff00' } }
				className='listsTable'

				//containerStyle={ { height: '100%' } }
				>
			      <TableHeaderColumn hidden isKey dataField="id">Bill To Name</TableHeaderColumn>
			      <TableHeaderColumn dataField='freightBill' dataFormat={ objectFormat.bind(this, 'number')} filterValue={ objectFormat.bind(this, 'number')}>Freight Bill #</TableHeaderColumn>
			      <TableHeaderColumn dataField='tractor'>Tractor</TableHeaderColumn>
			      <TableHeaderColumn dataField='billOfLading'>BOL</TableHeaderColumn>
			      <TableHeaderColumn dataField='account'>Account</TableHeaderColumn>
			      <TableHeaderColumn dataField='stops' 
			      	dataFormat={ objectFormat.bind(this, [0,'dateTimeAddress'])} 
			      	filterValue={ objectFormat.bind(this, [0,'dateTimeAddress'])}
			      	//tdStyle={ { wordWrap: 'break-word' } }
			      	>Origin
			      </TableHeaderColumn>
			      <TableHeaderColumn dataField='stops' 
			      	dataFormat={ objectFormat.bind(this, [0,'dateTimeAddress'])} 
			      	filterValue={ objectFormat.bind(this, [0,'dateTimeAddress'])}>
			      	Destination
			      </TableHeaderColumn>
			      <TableHeaderColumn dataField='carrier'>Carrier</TableHeaderColumn>
			      <TableHeaderColumn dataField="billToName">Bill To Name</TableHeaderColumn>
			      <TableHeaderColumn dataField="state">State</TableHeaderColumn>

			      
			</BootstrapTable>
			</div>
		);
	}
}

Error I get:
Uncaught TypeError: Cannot read property 'onToggleDropDown' of undefined

**Comment by StohlmanMatteo** [comment]
Been trying to figure this out for hours now but can't find much. I am using almost exactly the code from your example page and receiving this same error. 
My Code:
`import React from 'react';
import { BootstrapTable, TableHeaderColumn, SizePerPageDropDown } from 'react-bootstrap-table';


const products = [];

function addProducts(quantity) {
  const startId = products.length;
  for (let i = 0; i < quantity; i++) {
    const id = startId + i;
    products.push({
      id: id,
      name: 'Item name ' + id,
      price: 2100 + i
    });
  }
}

addProducts(70);

export default class CustomSizePerPageDropDown extends React.Component {
  constructor(props) {
    super(props);
  }

  onToggleDropDown(toggleDropDown){
    // do your stuff here
    console.log('toggle dropdown');
    toggleDropDown();
  }

  renderSizePerPageDropDown(props){
    return (
      <SizePerPageDropDown
        className='my-size-per-page'
        btnContextual='btn-warning'
        variation='dropup'
        onClick={ () => this.onToggleDropDown(props.toggleDropDown) }/>
    );
  }

  render() {
    const options = {
      sizePerPageDropDown: this.renderSizePerPageDropDown
    };
    return (
      <div>
        <BootstrapTable
          data={ products }
          options={ options }
          pagination>
          <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
        </BootstrapTable>
      </div>
    );
  }
}
`
The Error I get:
Uncaught TypeError: Cannot read property 'onToggleDropDown' of undefined

**Comment by StohlmanMatteo** [comment]
unfortunately I really can't tell you why but I left this alone for a few days focusing on something else and now it's working. Must have been something else missing.
