### ISSUE TITLE
Sort by Date

### ISSUE THREAD

**Issue by zeusbangayan** [AllenFang/react-bootstrap-table#1142]
DO you have any examples by Sorting by Date? it seems it's sorted alphabetically instead of actual date. thanks!

**Comment by AllenFang** [comment]
I haven't this kind of example, if the default sorting behavior is not match with your, I think you can custom your sort function, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/custom-sort-table.js) for learn how to do it.

And let me know if your got any questions, thanks

**Comment by dileepmiahra** [comment]
i want to do sorting on datatime column.

**Comment by constance-gb** [comment]
Here is a solution to sort by dates formatted as DD/MM/YYYY:

```
<TableHeaderColumn 
        dataField='date' 
        dataSort={ true } 
        sortFunc={ this.sortDates }>Date
 </TableHeaderColumn>

[...]

 sortDates (a, b, order) {
    let indices = [6, 7, 8, 9, 3, 4, 0, 1];
    if (order === 'asc') {
      let r = 0;
      indices.find(i => r = a.date.charCodeAt(i) - b.date.charCodeAt(i));
      return r;
    } else if (order === 'desc') {
      let r = 0;
      indices.find(i => r = b.date.toString().charCodeAt(i) - a.date.toString().charCodeAt(i));
      return r;
    }
  }
```



Change indices to [6, 7, 8, 9, 0, 1, 3, 4] for dates formatted like MM/DD/YYYY

**Comment by ghost** [comment]
@constance-gb Is there a way, we can skip some rows and sort. So that skipped rows always comes on top ?

**Comment by Apatil15** [comment]
Following solution for date sorting working like a charm 

 ```
sortFunc: (a, b, order, dataField, rowA, rowB) => { 
      if (order === 'asc')
      {
        return Date.parse(a) - Date.parse(b)
      }
     else if (order === 'desc') {
        return  Date.parse(b) - Date.parse(a) 
      }
  }
```

**Comment by hauhuynh1208** [comment]
> Following solution for date sorting working like a charm
> 
> ```
> sortFunc: (a, b, order, dataField, rowA, rowB) => { 
>      if (order === 'asc')
>      {
>        return Date.parse(a) - Date.parse(b)
>      }
>     else if (order === 'desc') {
>        return  Date.parse(b) - Date.parse(a) 
>      }
>  }
> ```

Hi @Apatil15, your solution is working perfectly. However, if there is any (a) or (b) is empty string, your function will be crashed. I wonder if you have any solution for empty datetime?

**Comment by hammadahmad94** [comment]
@hauhuynh1208  did you find a fix for the issue you mentioned above?
