### ISSUE TITLE
Pagination error because a <div> before pagination's cols

### ISSUE THREAD

**Issue by migueloop** [AllenFang/react-bootstrap-table#1146]
Hi, I'm inserting a databable as the basic example and I'm getting this:

![image](https://cloud.githubusercontent.com/assets/409981/23893330/523f2848-089e-11e7-9adf-b113cf090bcf.png)

This div is the cause:
https://github.com/AllenFang/react-bootstrap-table/blob/master/src/pagination/PaginationList.js#L119

Maybe it's because I did something in my custom css?

**Comment by AllenFang** [comment]
> Maybe it's because I did something in my custom css?

I think so, if you have no idea for fixing it, you can custom the pagination panel by yourself, 

check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/pagination/custom-pagination-panel.js for learning how to custom the pagination panel.

Please let me know if you have any concern, thanks
