### ISSUE TITLE
requiring component via RequireJS does not work like CommonJS import

### ISSUE THREAD

**Issue by vpark** [AllenFang/react-bootstrap-table#115]
When I require the component in my React app, the file is loaded but exposed globally.

```javascript
define(['react', 'react-bootstrap-table', 'dbService', 'react-bootstrap'], function(React, RBTable, dbService, Bootstrap) {

// React is defined
// RBTable is undefined
// window.BootstrapTable is defined

});
```

Would it be possible to support requireJS compatibility? I believe this is creating a invariant violation error for me.

**Comment by AllenFang** [comment]
I think it is possible to support the RequireJS, but I'm not familiar with it, so I need some time to do it.

**Comment by AllenFang** [comment]
@vpark, I've release v1.3.0 for fixing this issue. Sorry for a later release ;(
