### ISSUE TITLE
CSV header problem

### ISSUE THREAD

**Issue by Sandip-pal** [AllenFang/react-bootstrap-table#1151]
Hi,

When I am using csvHeader attribute, it is creating header but i am getting two headers. One with dataField attribute and other is csvHeader. Below is the example:

Name														
name	empId	level	rating	comparatio	promotion	ctc	suggestedPromotion	

The 1st line is csvHeader and 2nd line is datafield.
Can i change all the column header in 2nd line instead of taking it from datafield

**Comment by Sandip-pal** [comment]
It was my mistake. It is solved.

**Comment by reetou** [comment]
How did you solve problem?
