### ISSUE TITLE
Making cell readonly

### ISSUE THREAD

**Issue by ibilanchuk** [AllenFang/react-bootstrap-table#1154]
Hello, I want to make some cells non editable. Not fully row, only one cell. Is there any solution this problem?

**Comment by bennnjamin** [comment]
Yes, set editable to false like this:

`<TableHeaderColumn dataField="name" editable={false} dataSort {true}>Name</TableHeaderColumn>`

**Comment by AllenFang** [comment]
@bennnjamin, great job 👍 

Let me know if you have any questions, thanks

**Comment by ibilanchuk** [comment]
@bennnjamin, your solution block editing on column. But i need block cell. For example cell is situated in [1,2] - first row,second column

**Comment by bennnjamin** [comment]
@ibilanchuk There is no way built in. The closest you can get is to implement `beforeSaveCell` http://allenfang.github.io/react-bootstrap-table/docs.html#beforeSaveCell and `return false` for the cells you do not want to save edits for. Otherwise you will have to implement this yourself.

**Comment by AllenFang** [comment]
sorry for lately, reply, actually, the `editable` can accept a bool value or a function, if you use the function, there're four arguments, `cellValue`, `row`, `rowIndex` and `columnIndex`. in addition, this function is supposed to be return a bool value to tell `react-bootstrap-table` this cell is editable or not.

Let me know if you got any questions, thanks

**Comment by AllenFang** [comment]
BTW, I should update the docs, so open issue again.

**Comment by AllenFang** [comment]
Docs updated for `editable`, check http://allenfang.github.io/react-bootstrap-table/docs.html#editable

**Comment by bennnjamin** [comment]
@AllenFang I discovered another issue with this. If you disable editing for the cell, there is no way to apply validation onAddRow. For example, what if you want to insert a new row into the table but after that you want the cell to be read only? You need validation on insert, but not the ability to edit the cell.
