### ISSUE TITLE
Sort by Component

### ISSUE THREAD

**Issue by Mikeg542** [AllenFang/react-bootstrap-table#1157]
I have a Component called <Rating score={##} /> where score is a number from 1-5. How can I make a table column of Rating Components sortable by the score value?

**Comment by bennnjamin** [comment]
@Mikeg542 You can implement a custom sort function (which is really a comparator). If you provide code for you component's data I can help more. http://allenfang.github.io/react-bootstrap-table/docs.html#sortFunc

**Comment by Mikeg542** [comment]
Exactly what I needed - thanks!

**Comment by AllenFang** [comment]
thanks @bennnjamin
