### ISSUE TITLE
How to format edited cell value

### ISSUE THREAD

**Issue by CoralSilver** [AllenFang/react-bootstrap-table#1158]
After user has edited cell content and it has been saved, I need to format the value to match the formatting that's been applied to the other cells in the column.  Is it possible to call my formatting function again without setting the change to state?  I'm setting the cellEditProps in the constructor.

```
this.cellEditProp = {
      mode: 'click',
      blurToSave: true,
      beforeSaveCell: this.onBeforeSaveCell,
      afterSaveCell: this.onAfterSaveCell
    }
```

**Comment by CoralSilver** [comment]
Nevermind, I didn't realize it calls it automatically. I was passing it wrong data type. Not sure why formatting function is also called on click of editable cell for all cells in column.

**Comment by AllenFang** [comment]
ok, let me know if you got any questions, thanks and sorry for lately reply, this is a busy month ;(
