### ISSUE TITLE
Flex box / changing height breaks responsiveness of the table

### ISSUE THREAD

**Issue by VictorChen** [AllenFang/react-bootstrap-table#1159]
If you resize the window, the table columns will adjust accordingly, HOWEVER, this breaks if the container height changes.

Reproducer:

https://jsfiddle.net/1s8reLw1/2/

After clicking on the `Fetch Data` button, the table no longer resize itself when you shrink the window.

**Comment by AllenFang** [comment]
sorry for lately reply, it's busy on this month and I'll spend some time to check this out. thanks

**Comment by AllenFang** [comment]
Fixed on `v3.1.4`, please have a look, thanks

**Comment by AllenFang** [comment]
Fixed on `v3.1.6`, please have a look, thanks :)

**Comment by VictorChen** [comment]
thank you!
