### ISSUE TITLE
onRowClick property in selectRow

### ISSUE THREAD

**Issue by tbaeg** [AllenFang/react-bootstrap-table#116]
I would like to invoke a function when a row is clicked, not selected. I did my own implementation by simply adding another property in the `selectRow` property called `onRowClick`. It was pretty simple and wondering if this is of use, let me know and I'll make proper changes and a pul request.

**Comment by AllenFang** [comment]
@tbaeg, thanks your contribution. Actually, you can just use <code>selectRow</code> and give the <code>hideSelectColumn</code> for hiding the select column, so it will exactly like the scenario which you want :)

**Comment by tbaeg** [comment]
So, my use case is different in that I want to be able to click the row to accomplish `myFunc`, with the caveat that I can still select the row via the checkbox input element. The `hideSelectColumn` would not be able to do this as this would just act as a pseudo `onRowClick` event, but then doesn't let me do row selection at all. If you need an example, let me know. I'll update my fork with changes when I get a chance. I actually modified the compiled code in `/lib` so I'll need to update the `/src`.

**Comment by AllenFang** [comment]
yes you r right, maybe you can give me a PR or your forks. Anyway, how about use the <code>radio</code> to make the single select and use <code>onSelect</code> for a after selection hook, in <code>onSelect</code> you can call your <code>myFunc</code>, and the <code>hideSelectColumn</code> just hide the unused selection column.?

**Comment by tbaeg** [comment]
Yup! Just made a PR for you to few. No need to merge, just felt it was probably easier to point to.

https://github.com/AllenFang/react-bootstrap-table/pull/118

Could you also change the status of this issue to open and switch to enhancement? Thanks!

**Comment by tbaeg** [comment]
@AllenFang Before I forget to say, *awesome* work on the component! Simple but feature rich. Lovin' the ES6 class usage as well.

**Comment by AllenFang** [comment]
Great, I'll review your codes, Anyway, thanks a lots:) If you love it , give a star :)

**Comment by tbaeg** [comment]
Can't believe I haven't starred it yet! Shame on me.

**Comment by tbaeg** [comment]
One last thing for the night. Thinking about it from a user perspective, I realized tables should probably provide some sort of double click feature on a table. I feel like it would be super valuable in terms of being a feature, similar to the `onRowClick` but `onRowDblClick`. Obviously, they are mutually exclusive as it's impossible to distinguish the two events. Implementation would be just as simple to integrate. Alright, good night!

**Comment by AllenFang** [comment]
Thanks :) i'll add this feature in near future :)

**Comment by AllenFang** [comment]
I've add <code>onRowClick</code> in v1.2.7, you can check <a href="https://github.com/AllenFang/react-bootstrap-table/blob/master/CHANGELOG.md">it</a>

**Comment by tbaeg** [comment]
+1 nice!
