### ISSUE TITLE
How to disable the toastr validation popup in the top right of the page?

### ISSUE THREAD

**Issue by crazyUI** [AllenFang/react-bootstrap-table#1163]
I want to customize the validation and want to hide the toastr popup in the top right of the page. Please help.

I am able to do it with css. Is there any other property available to disable it...

**Comment by AllenFang** [comment]
sorry for lately reply, busy on my job..., check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/advance/disable-toastr-table.js#L72) example, and let me know if you got any questions. thanks
