### ISSUE TITLE
Select All Check Box Performance

### ISSUE THREAD

**Issue by SimonDKnight** [AllenFang/react-bootstrap-table#1164]
Hi, I am having an issue with the performance of the select all check box. We are currently loading in around 11k records into our table in pagination mode. on the onSelectAll function we are selecting all the records using 

`return this.state.institutions.map(row => row.id);`

It is fine when we first check the select all the check boxe, but when we unselect the select all box it takes around 10-15 seconds to unselect every checkbox. Any idea what might be happening here? Where might the bottle neck be? Has anyone else run into this issue (and solved it)?

Thanks

Simon

**Comment by SimonDKnight** [comment]
Hi, so after some digging into the code I discovered the problem, and at the moment my solution is to just comment out the code (obvs not good). 

On file TableDataStore.js on line 115 we have this function which is called when you unselect the select all button.

`getRowByKey(keys) {
    return keys.map(key => {
      const result = this.data.filter(d => d[this.keyField] === key);
      if (result.length !== 0) return result[0];
    });
  }`

This is a very expensive function which in my case is iterating through 11k items and for each item it iterates over the data again (another 11k records), so 121 mil iterations.

Id be happy to try and help optimise this, could you explain what this function is doing if possible, and what impact its going to have with me just commenting it out.

Thanks again,

Simon

**Comment by AllenFang** [comment]
@SimonDKnight, sorry for lately reply, pretty busy on this month, and thanks your investigate. and this function seems like expensive like you said. this function is doing for if have the keys array 
`[1, 10, 20, 30, ...]` though this function will get the raw data like `[{ ... }, { ... }, { ... }, { ... }] `

and obviously, it need to enhance,

**Comment by AllenFang** [comment]
I do a little enhancement on it and released on `v3.1.7`.

**Comment by SimonDKnight** [comment]
Awesome thanks!!
