### ISSUE TITLE
Allow only a single row to expand at a time

### ISSUE THREAD

**Issue by subasing** [AllenFang/react-bootstrap-table#1166]
Hi Allen, Thanks a lot for putting the time into building something really great and useful. I'm throwing a quick dashboard together where "onRowClick" it needs to do a row expand and hide all the other expanded rows. Matching the row key and looping through the table works somewhat, but its not very stable. Occasionally needs to click twice to expand the row. Do you happen to have an example that might point me in the right direction? Thanks!

**Comment by tmcdonnell87** [comment]
+1

**Comment by AllenFang** [comment]
sorry for lately reply, busy on this month. @subasing, if I support this feature natively, is that ok for you? you dont implement `onRowClick` and handle expand by yourself, `react-bootstrap-table` will do it.

**Comment by tmcdonnell87** [comment]
I would support a native option as opposed to having to manage it externally

**Comment by subasing** [comment]
@AllenFang that sounds great!

**Comment by AllenFang** [comment]
I'll try to support it natively

**Comment by AllenFang** [comment]
Release on `v3.2.0`, assign true to `options.onlyOneExpanding` to allow single expand row, default is `false`
