### ISSUE TITLE
Batch requests for paginated data

### ISSUE THREAD

**Issue by Billy-** [AllenFang/react-bootstrap-table#1167]
Hi,

Is there any way to have the table fetch data for each page as it displays? We have a data consisting of thousands of items and we would rather get them 10 or so at a time (configurable with the items-per-page dropdown). Ideally we could also send through any values in the column filters with the request

Many thanks

**Comment by AllenFang** [comment]
Sorry for lately reply, busy on this month, try to use `remote` mode, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-paging.js and https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-paging.js

[here](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/remote) is all related with the `remote` functionality, let me know if you got any questions

**Comment by Billy-** [comment]
Awesome, that's exactly what we're looking for. Thanks!
