### ISSUE TITLE
Page scrolling to top on state change and column sort

### ISSUE THREAD

**Issue by Mikeg542** [AllenFang/react-bootstrap-table#1168]
I have an array of people that are displayed either as a react-bootstrap-table or a grid of a custom component. When I switch to the grid view, the page stays at the same spot, but switching to the react-bootstrap-table view scrolls up to the top of the page. 

Also, when I toggle the sort direction or the table, it takes me up to the top of the page as well. Some part of the table render is scrolling me to the top and I can't figure out what it is. Any direction would be helpful!

**Comment by AllenFang** [comment]
Sorry for lately reply du to my busy work, did you configure `scrollTop` on `react-bootstrap-table`? Because `react-bootstrap-table` does not doing the scroll when page load or sorting

**Comment by WillCDev** [comment]
Hey @Mikeg542 ,
Did you ever find an answer to this?
I have a similar issue where I have a table which is longer than the page, if a scroll down then sort, the render forces me back to the top of the page.
I've no idea why!
