### ISSUE TITLE
TypeError when changing dropdown before data is given

### ISSUE THREAD

**Issue by Billy-** [AllenFang/react-bootstrap-table#1169]
On first load, we pass in an empty array. Once we load the data (with the click of a button), it then gets a populated array. This works fine. However, if you change the items-per-page dropdown, and _then_ load the data in, we get a type error. I briefly stepped through the code and saw that the error is being thrown [here](https://github.com/AllenFang/react-bootstrap-table/blob/master/src/TableBody.js#L57), where `data` is undefined. on [line 55](https://github.com/AllenFang/react-bootstrap-table/blob/master/src/TableBody.js#L55), `this.props.data` is an array of `undefined` items

Many thanks.

**Comment by AllenFang** [comment]
sorry for lately reply, bust on this month, you got the error if you change size per page firstly and then load data?

**Comment by Billy-** [comment]
Yes, that's right. I will try to get a minimal example that reproduces the issue for you.

**Comment by AllenFang** [comment]
thanks, I'll also try to reproduce it, but need some time, there're a lots of issue was queued

**Comment by Billy-** [comment]
jsfiddle [here](http://jsfiddle.net/z0xpcsgm/4/) ([fullscreen](http://jsfiddle.net/z0xpcsgm/4/show/)). Working on some source code for you to clone

**Comment by Billy-** [comment]
I forked your repo and reproduced the bug in the basic pagination example. Hope this helps

**Comment by AllenFang** [comment]
ok, I can reproduce it and it absolutely is a bug, thanks

**Comment by AllenFang** [comment]
Fixed on `v3.1.3`, check it out 👍

**Comment by Billy-** [comment]
Awesome, that was quick! Thanks so much, will try it out tomorrow
