### ISSUE TITLE
onClick in dataFormat() fires without actual 'clicking'

### ISSUE THREAD

**Issue by QuanTumli** [AllenFang/react-bootstrap-table#117]
I define my `TableHeaderColumn` as follows:
```javascript
<TableHeaderColumn dataField="someData" dataFormat={this.valueFormatter}>Value</TableHeaderColumn>
```
As the `valueFormatter` I have following code:
```javascript
valueFormatter(cell, row){
  return (
    <p onClick={console.log('value clicked')}>{cell}</p>
    );
}
```

The table generates without errors but in the console I see `value clicked` 10x (as much as there are rows).
What I want: The function (in the above example a simple `console.log()`) should be called only if I click on the element.

What is wrong with my code, or is there another way to solve this?

**Comment by staminaloops** [comment]
Hello,
Try
```javascript
valueFormatter(cell, row){
  return (
    <p onClick={() => console.log('value clicked')}>{cell}</p>
    );
}
```
It worked for me.

**Comment by AllenFang** [comment]
This should be good for your case, 
```javascript
class ValueFormatter extends React.Component{

  handleClick(e){
    console.log('value clicked');
  }

  render(){
    return (
      <p onClick={this.handleClick.bind(this)}>{this.props.data}</p>
    );
  }
};

function valueFormatter(cell, row){
  return (
    <ValueFormatter data={cell}/>
  );
}
```

**Comment by staminaloops** [comment]
or that :stuck_out_tongue:

**Comment by AllenFang** [comment]
thanks @staminaloops :) your is more better :+1:

**Comment by staminaloops** [comment]
Np, tell me if I can help you in anything more in this project, its great (you have my twitter) :smile:

**Comment by AllenFang** [comment]
@staminaloops, coool, I'll contact you :)

**Comment by tbaeg** [comment]
This would be great to document as well.

**Comment by QuanTumli** [comment]
thank you guys! :) :+1:
I go with the solution of @staminaloops, much shorter and easy to understand.
