### ISSUE TITLE
Require solution to provide headers to the table using a synchronous API call

### ISSUE THREAD

**Issue by ashishd751** [AllenFang/react-bootstrap-table#1170]
Hello,
     Currently, i am using an asynchronous ajax call library (axios) to fetch the headers for my table. Problem that arises is that, since it is an async call being made in the componentWillMount() of the component, the render() function gets called before a response is returned by the API. Hence, initially, the headers are received by the bootstrap table as undefined, where the error is thrown and further execution of the program is halted.
      I was wondering if anyone has a solution for this dilemma. How to fetch the table headers from an API in a synchronous manner ?

**Comment by layneanderson** [comment]
Hi @ashishd751 ,

In your render function you can have something like this:
```
if (!data) { return ( <div>Loading...</div> ); }

return ( <BootstrapTable data={data} ...
```
There are multiple ways of doing it but this should get you started.

Cheers,

Layne

**Comment by AllenFang** [comment]
@ashishd751, I dont support this kind of feature, like @layneanderson, you can control it anything by yourself, this is not the main feature for `react-bootstrap-table`. thanks and let me know if you got another concern.
