### ISSUE TITLE
Does anyone know how to deal with this <div id="toast-container"> that is preventing me from tapping on the buttons ?

### ISSUE THREAD

**Issue by aziz-boudi4** [AllenFang/react-bootstrap-table#1171]
I added buttons to my table, but this <div id="toast-container"> is preventing me from tapping on the button.
What is the use of this <div  id="toast-container"> ?

![screen shot 2017-03-24 at 11 26 22 am](https://cloud.githubusercontent.com/assets/7435015/24308932/276123ce-1087-11e7-8dfe-629cfef53702.png)

**Comment by AllenFang** [comment]
sorry for lately reply, did you enable `insertRow` or `cellEdit`?

**Comment by AllenFang** [comment]
https://github.com/AllenFang/react-bootstrap-table/pull/1216
