### ISSUE TITLE
how to  select the rows use code

### ISSUE THREAD

**Issue by n0trace** [AllenFang/react-bootstrap-table#1173]
Hello, I didnt find the document how to  select the rows use code , so ask how to solve this question
look forward to reply
thanks

**Comment by AllenFang** [comment]
```js

this.ref.table.setState({
    selectedRowKeys: [ .... ]
})


<BootstrapTable ref='table' .. >
```

Let me know if you got any question. :)

**Comment by n0trace** [comment]
thanks
