### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isKey' of undefined when passing in an empty data array

### ISSUE THREAD

**Issue by dkhonig** [AllenFang/react-bootstrap-table#1176]
Hi,

I'm trying to load the BootstrapTable with an empty array. When I pass in an empty array to BootstrapTable like so, I get the following error:
<img width="719" alt="screen shot 2017-03-27 at 3 10 38 pm" src="https://cloud.githubusercontent.com/assets/2054377/24373682/1dd70776-1300-11e7-9c66-3d49b37c5540.png">
<img width="1646" alt="screen shot 2017-03-27 at 3 09 18 pm" src="https://cloud.githubusercontent.com/assets/2054377/24373686/26cf67c4-1300-11e7-91b8-15555dbff743.png">

**assessment.routes is an empty javascript array.

**Comment by Billy-** [comment]
The code you've shown looks fine. Try posting more code or even better would be a working example, you can use [this jsfiddle](http://jsfiddle.net/z0xpcsgm/6/) as a base to reproduce your issue

**Comment by dkhonig** [comment]
I took a look  at your example and it looks like this should work with an empty array. I must be doing something wrong elsewhere and I'm guessing my assessment.routes property must be coming in undefined.  The reason why I reported this was because when I log that object to the console it prints the object and assessement.routes is in fact an array within that object and not "undefined". I'll try to debug some more..thanks for the response.

**Comment by AllenFang** [comment]
> The reason why I reported this was because when I log that object to the console it prints the object and assessement.routes is in fact an array within that object and not "undefined". I'll try to debug some more

could you show your console result and make sure the data is an array instead of a plain object or null or undefined. 

I think this is not a bug, there must have something wrong, if the problem still remain, please show me your code more detail, thanks

**Comment by dkhonig** [comment]
Ok I figured out why I was getting the isKey of undefined error. One of those things where you need to look really hard at your code. If you look at the screenshot I attached on the third TableHeaderColumn there's an 's' character after the closing tag. Turn out of if you have text outside of the TableHeaderColumn it throws this error. Probably not that surprising but nice to know  in case anyone else runs into the same thing.
<img width="617" alt="screen shot 2017-04-04 at 8 55 45 pm" src="https://cloud.githubusercontent.com/assets/2054377/24685135/8d834100-1979-11e7-9cfb-ce3a74e9c1c5.png">

**Comment by AllenFang** [comment]
@dkhonig  Good sharing 👍

**Comment by fgheorghe** [comment]
@dkhonig Good sharing indeed - I had commented out code within the header, and had the same issue. 👍
