### ISSUE TITLE
Handling duplicate rows in custom modal body

### ISSUE THREAD

**Issue by crazyUI** [AllenFang/react-bootstrap-table#1181]
Thanks for excellent plugin!

I have a custom modal body for the 'insert row' and validator for the key field. How can I check if the entered key already exists and update the validateState?

Thanks for your help.

**Comment by AllenFang** [comment]
`validateState` is updated by `react-bootstrap-table` and if you click save button, I think `react-bootstrap-table` will call the validator(If defined) and check the row key is already exists.

so you just focus on the customization for your component content, layout, styling etc. The validation for exist key will be done by `react-bootstrap-table`.

Let me know if you still have any questions :)

**Comment by crazyUI** [comment]
Thanks for your response. When I attempt to add another row with same id, the modal freezes. If I click 'cancel', I see two rows with same key appear in the table. however if I attempt to select one of them, both of them will get selected. 

I have a custom modal body and custom validator for the key to check that it is not empty.

**Comment by AllenFang** [comment]
ok, I'll check this out and could you please show me your code? please keep it minimal and simple for me to reproduce

**Comment by crazyUI** [comment]
//Calling custom modal body
 this. createCustomModalBody = (columns, validateState, ignoreEditable) => {
            return (
                <CustomModal columns={ columns }
                              validateState={ validateState }
                              ignoreEditable={ ignoreEditable }/>
            );
        }

Custom modal code is same as the example -
https://gist.github.com/AllenFang/bb06cc4740762bfea8ac50c2d620cbb1#file-custom-insert-modal-body-jsx

Validator for the column -
 <TableHeaderColumn dataField='idKey'  editable={ { validator: this.idKeyValidator } } isKey>ID</TableHeaderColumn>

  this.idKeyValidator = (value) => {

            if (value.trim() =="") {
                return "ID already exists";
            }
            return true;
        }

Getting this warning in console -
Warning: Failed prop type: Invalid prop `validateState` of type `string` supplied to `InsertModal`, expected `object`.
    in InsertModal (created by ToolBar)
    in ToolBar (created by BootstrapTable)

Modal will not close or throw error while attempting to enter duplicate key.It will add two rows with same key.

**Comment by AllenFang** [comment]
HI, as I mentioned above, please follow [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/insert-modal/custom-insert-modal-body.js) examples and default `react-bootstrap-table` will help you to check the key exist or not, so no need to give the key validator for checking rowkey exist, and I follow your example to write, but it work well.

`js
class MyCustomBody extends Component {

  getFieldValue() {
    const newRow = {};
    this.props.columns.forEach((column, i) => {
      newRow[column.field] = this.refs[column.field].value;
    }, this);
    return newRow;
  }

  render() {
    const { columns, validateState } = this.props;
    return (
      <div className='modal-body'>
        <h2 style={ { color: 'red' } }>Custom body</h2>
        <div>
          {
            this.props.columns.map((column, i) => {
              const {
                editable,
                format,
                field,
                name,
                hiddenOnInsert
              } = column;

              if (hiddenOnInsert) {
                // when you want same auto generate value
                // and not allow edit, for example ID field
                return null;
              }
              const error = validateState[field] ?
                (<span className='help-block bg-danger'>{ validateState[field] }</span>) :
                null;
              return (
                <div className='form-group' key={ field }>
                  <label>{ name }</label>
                  <input ref={ field } type='text' defaultValue={ '' } />
                  { error }
                </div>
              );
            })
          }
        </div>
      </div>
    );
  }
}

export default class CustomInsertModalBodyTable extends React.Component {

  createCustomModalBody = (columns, validateState, ignoreEditable) => {
    return (
      <MyCustomBody columns={ columns }
        validateState={ validateState }
        ignoreEditable={ ignoreEditable }/>
    );
  }

  validator = (value) => {
    if (value === '') return 'ID already exists';
    return true;
  }

  render() {
    const options = {
      insertModalBody: this.createCustomModalBody
    };
    return (
      <BootstrapTable data={ products } options={ options } insertRow>
        <TableHeaderColumn dataField='id' isKey={ true } editable={ { validator: this.validator } }>Product ID</TableHeaderColumn>
        <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
        <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
}
`

**Comment by crazyUI** [comment]
Thanks for your response. I have hidden the toastr validation warning using css. I want the duplicate row message as part of the

    const error = validateState[field] ?
                (<span className='help-block bg-danger'>{ validateState[field] }</span>) :
                null;

I am not able to get it. And if I close the dialog, two rows are created

**Comment by AllenFang** [comment]
it's very wired.....  you means you can't get the duplicate row key message via `validateState` when you click the save button?  I still can not reproduce your issue, how about show me all your code, but keep it simple and minimal to easy to reproduce(**It's very important**)

**Comment by crazyUI** [comment]
Yes I am not able to get the duplicate row key message via validateState.

**Comment by AllenFang** [comment]
Thanks, I'll have a look on it 👍

**Comment by AllenFang** [comment]
After I checking the code, because `validateState` only preserve the error message via `editable.validator` and becuase the rowkey duplciated validation is not the part of  `editable.validator`, so that you cant get the error message via `validateState`.

Anyway, I'll find some solution.

**Comment by crazyUI** [comment]
Thank you for fixing this. Appreciate!

**Comment by AllenFang** [comment]
HI @crazyUI, please add `keyValidator` on your key column(`TableHeaderColumn`), it tell `react-bootstrap-table` handle the key validation automatically and push the error into `validateState`, please upgrade to `v3.1.7` and try it again, thanks

**Comment by crazyUI** [comment]
Works perfect. Thanks a lot !
