### ISSUE TITLE
Modify the text displayed in the column header tooltip

### ISSUE THREAD

**Issue by ptadas** [AllenFang/react-bootstrap-table#1182]
How would one modify the text displayed in the tooltip? I've tried using headerText, but it seems to have no effect when the column name is not an object. For instance, I'd like to name my column "YoY" and display "Year over year" in the tooltip. Thanks

**Comment by AllenFang** [comment]
HI, use `headerText` on `TableHeaderColumn`

**Comment by ptadas** [comment]
this does not seem to work for me. The text displayed when I hover over the column header is still the same as the text supplied to name

        <TableHeaderColumn
          headerText='Product Name'
          key={Math.random()}
          dataField={value.data}
          dataSort={true}
          export={value.export}
          hidden={value.hidden}
          isKey={index === 0}
          dataAlign={typeof value.align !== 'undefined' ? 'left' : 'right'}
          dataFormat={value.format}
          sortFunc={this.revertSortFunc}
        >
            {value.name}
        </TableHeaderColumn>

**Comment by AllenFang** [comment]
> Had to add headerTitle={ false } in order for the headerText to appear

There's a little bug I guess, I'll check this out, thanks 👍

**Comment by AllenFang** [comment]
Fixed on `v3.1.7`, please have a look on it, thanks 👍

**Comment by ajaykgp** [comment]
HeaderText also changes the header in the insert modal. Is there a way to keep the header in insert modal the same as in the name from the dataField?

**Comment by AllenFang** [comment]
@ajaykgp yes, there's default behavior, `react-bootstrap-table` will apply the header description to the input field in insert modal. there's only one way to do is custom the each field, you can check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/insert-modal/custom-insert-modal-field.js

in your custom input, add the placeholder will solve your requirement
