### ISSUE TITLE
Is it possible to create an end point, to let us build our customized row insert Modal?

### ISSUE THREAD

**Issue by wy19900814** [AllenFang/react-bootstrap-table#1185]
Currently we could use insertRow attribute.. The Creation Modal is nice but we always need more customized components, like select ... etc.

**Comment by AllenFang** [comment]
if you want to customize the insert modal, check [this](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/custom/insert-modal) to learn how to customize it, let me know if you have any questions, thanks 👍
