### ISSUE TITLE
Getting error while using date filter

### ISSUE THREAD

**Issue by Tommyhank** [AllenFang/react-bootstrap-table#1193]
I am getting error "targetVal.getDate is not a function" any time I try to use the date filter.

**Comment by AllenFang** [comment]
could you please show me your example? thanks

**Comment by Tommyhank** [comment]
![screen shot 2017-04-04 at 9 50 26 am](https://cloud.githubusercontent.com/assets/3987492/24660041/71948e8e-191c-11e7-963e-2e1efabb0a33.png)
![screen shot 2017-04-04 at 9 50 37 am](https://cloud.githubusercontent.com/assets/3987492/24660063/7e8a6794-191c-11e7-85db-73b5b9e70abe.png)

No matter what date I choose or what date filter operations I choose. It will throw this error

**Comment by AllenFang** [comment]
sorry for my unclear requirement, I means show your code exmaple, sorry about that, and i have following question:
1. the `Effecitve Date` and `Expiration Date` is share same `dataField`?
2. Does there any data which is not a [Javascript Date Object](https://www.w3schools.com/jsref/jsref_obj_date.asp)?

Actually, after the `v3.1.3`, I fixed a critical bug is that date filter will calculate wrong result if use "!=" and "=" comparators, you can check the [CHANGELOG](https://github.com/AllenFang/react-bootstrap-table/blob/master/CHANGELOG.md#bug-fixes-3). For fixing this bug, now I used the Date Object API to compare the date value for a more accurate result.

**Comment by Tommyhank** [comment]
Sorry, I forget to change the Date to Javascript Date Object...But I am still having previous  issue. If I try to filter a date equal to the some existing date, it's not working
![screen shot 2017-04-05 at 10 46 07 am](https://cloud.githubusercontent.com/assets/3987492/24711248/5ee93024-19ed-11e7-94fd-8626d33eed30.png)
![screen shot 2017-04-05 at 10 46 20 am](https://cloud.githubusercontent.com/assets/3987492/24711253/640b7904-19ed-11e7-83dc-ff627d8fe9d5.png)

**Comment by AllenFang** [comment]
it's wired, could you please make sure your `react-bootstrap-table` was newest? and maybe you can show me your raw data, thanks

**Comment by Tommyhank** [comment]
[ {
  "effectiveDate" : 1492685220000,
  "expirationDate" : 1492685220000,
  "orgName" : null,
  "orgType" : null
}, {
  "effectiveDate" : 1490295536757,
  "expirationDate" : 1490295536757,
  "orgName" : null,
  "orgType" : null
}, {
  "effectiveDate" : 1490634868616,
  "expirationDate" : 1490634868616,
  "orgName" : null,
  "orgType" : null
}, {
  "effectiveDate" : 1490110721820,
  "expirationDate" : 1490110721820,
  "orgName" : null,
  "orgType" : null
}, {
  "effectiveDate" : 1490006760000,
  "expirationDate" : 1490021161884,
  "orgName" : null,
  "orgType" : null
}, {
  "effectiveDate" : 1490295668476,
  "expirationDate" : 1490295668476,
  "orgName" : null,
  "orgType" : null
}, {
 
  "effectiveDate" : 1491249318227,
  "expirationDate" : 1491249318227,
  "orgName" : null,
  "orgType" : null
}, {
  "effectiveDate" : 1490298247093,
  "expirationDate" : 1490298247093,
  "orgName" : null,
  "orgType" : null
}, {
  "effectiveDate" : 1471219200000,
  "expirationDate" : 1471219200000,
  "orgName" : null,
  "orgType" : null
}, {
   "effectiveDate" : 1490287399984,
  "expirationDate" : 1490287399984,
  "orgName" : null,
  "orgType" : null
}, {
  "effectiveDate" : 1490295709553,
  "expirationDate" : 1490295709553,
  "orgName" : null,
  "orgType" : null
} ]


The raw data is like this, and I wrapped the date with new Date(), before putting it into the table. I double checked the version of react-bootstrap table, it is 3.1.6 which is the latest one

**Comment by AllenFang** [comment]
@Tommyhank, I random pick up 5 date and test on my local, but everything is fine, the "=" and "!=" work well, any idea or any I missing?

**Comment by matias91** [comment]
Hi! 
This is an old issue, but i'm experiencing this same problem:
`If I try to filter a date equal to some existing date, it's not working`

I'm using the newest version, and my data is like this: `"date": "2018/01/01"`
I followed the example in the docs, and there doesn't work either:
http://allenfang.github.io/react-bootstrap-table/example.html#column-filter

If you select "=" and filter the first date ("05/02/2016") it doesn't show.

Thanks in advance!

**Comment by AllenFang** [comment]
Sorry for lately reply, maybe you guys can take this example: https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/date-filter.js

pt just post your problems code here.  In the above example, I use the `Date` object and actually, in the `react-bootstrap-table`, we use the `Date` object's method to compare

https://github.com/AllenFang/react-bootstrap-table/blob/master/src/store/TableDataStore.js#L332
