### ISSUE TITLE
'selectRow' show on last column

### ISSUE THREAD

**Issue by thanhnhan2tn** [AllenFang/react-bootstrap-table#1194]
Hello,
by default, the select Row only show on first column, How can show this on last column like this:
![image](https://cloud.githubusercontent.com/assets/7343395/24646335/ba04258e-1945-11e7-99ec-2804e6968eca.png)

**Comment by AllenFang** [comment]
Currently, we dont support this kind of feature and may not support it in near future,  sorry about that and PR is welcome.

**Comment by AllenFang** [comment]
Close it due to duplicated with https://github.com/AllenFang/react-bootstrap-table/issues/1064
