### ISSUE TITLE
I can't load it with npm

### ISSUE THREAD

**Issue by clayboyd** [AllenFang/react-bootstrap-table#1204]
I can't load it with npm

npm install react-bootstrap-table --save

Npm says:

npm WARN package.json learning-flash@0.1.0 No repository field.
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-bootstrap-table" "--save"
npm ERR! node v4.8.1
npm ERR! npm  v2.15.11

npm ERR! Invalid name: "@allenfang/react-toastr"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by AllenFang** [comment]
HI @clayboyd, sorry for lately reply, maybe you can check https://github.com/AllenFang/react-bootstrap-table/issues/1152 and https://github.com/AllenFang/react-bootstrap-table/issues/1081.

**Comment by AllenFang** [comment]
please check #1216, if you have any concern or question, let me know in #1216
