### ISSUE TITLE
Edit only selected field of a table

### ISSUE THREAD

**Issue by nikhilbhawsinka** [AllenFang/react-bootstrap-table#1209]
Hi Allen,
I used the bootstrap table and its been very helpful. I am very new to coding so need some help from you on these points:
1) In the react bootstrap table, how can i make only one of the field editable and not the whole table. 2) How can i add custom buttons on top of the table (Just like export CSV occurs, i want to have my own custom button which call an api to fill the data for the table)
3) How can i centrally align the table (The buttons and search bar at the top need to be at relatively same position from the table). I tried text-align but it did not work; so i tried margin auto. It got the table in the middle but the exportcsv button was now misaligned.

Thanks

**Comment by genau7** [comment]
Regarding point 1, you can find the answer here:
http://allenfang.github.io/react-bootstrap-table/example.html#custom

(Look for Custom Button Group and/or Custom ToolBar)

**Comment by AllenFang** [comment]
Thanks @genau7's answer, for your second question, you can also [toolbar customization](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/custom/toolbar), default, `react-bootstrap-table` doesn't support the layout configuration, so please custom it.

Let me know if you have any questions, thanks
