### ISSUE TITLE
Hardcoded warning in ToolBar.js:

### ISSUE THREAD

**Issue by genau7** [AllenFang/react-bootstrap-table#1213]
Hello, I am creating a web app which can be viewed in many languages. While working with InsertModal and validation, I noticed that a warning pops up with a hardcoded message in ToolBar.js:

```
displayCommonMessage = () => {
    this.refs.notifier.notice(
      'error',
      'Form validate errors, please checking!',
      'Pressed ESC can cancel');
  }
```

Would it be possible for one of the library contributors to make those 3 strings customizable? And if not, could you please fix the error in the second string? (Please checking => Please check).

**Comment by AllenFang** [comment]
you can custom it via `editable.validator`, for [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/advance/validator-table.js#L32)

But it not a good idea to custom the notification, I'll find a better solution in near future

**Comment by AllenFang** [comment]
use `options.insertFailIndicator` to change the error message
