### ISSUE TITLE
Uncheck as well as disable checkbox when setting unselectable

### ISSUE THREAD

**Issue by CoralSilver** [AllenFang/react-bootstrap-table#1219]
I figured out one way of disabling checkboxes that have been checked after user presses a button outside the table.

I'm pushing the row id (key value) into state.selected.  After user presses the button I'm updating state like this: 

```
this.setState({
       unselectable: this.state.selected,
       selected: []
```
});

That works to disable the previously selected checkboxes, but those checkboxes are still checked.  How can I uncheck them without interacting directly with the DOM?

**Comment by CoralSilver** [comment]
I was able to figure out how to get it to work based on this example: [http://allenfang.github.io/react-bootstrap-table/advance.html#dynamic-select](url)

Just had to add a selected prop to my  `const selectRowProp`.

**Comment by AllenFang** [comment]
Cool and please let me know if you have any questions, thanks

**Comment by pyronlaboratory** [comment]
> I was able to figure out how to get it to work based on this example: [http://allenfang.github.io/react-bootstrap-table/advance.html#dynamic-select](url)
> 
> Just had to add a selected prop to my `const selectRowProp`.

@AllenFang This link is redirecting to an empty issues page. Do you know where I can find the correct link?
