### ISSUE TITLE
Use PaginationShowsTotal with a custom function in Typescript

### ISSUE THREAD

**Issue by Land3r** [AllenFang/react-bootstrap-table#1221]
Hello,

I tried to use the paginationShowsTotal with a custom function to appropriately render the pagination in TypeScript but couldn't get it to work.
It works fine with a Boolean value but cannot seem to understand a Function.

In the Typescript definition of the Options Interface, we can find the following code :
`paginationShowsTotal?: boolean | ReactElement<any>;`

I believe the correct definition should be :
`paginationShowsTotal?: boolean | Function;`
in order to work with custom functions.

**Comment by AllenFang** [comment]
@Land3r, I'm not familiar with TypeScript, and maybe you can upgrade the version of `react-bootstrap-table` for TS?  BTW, in the source code, I use Boolean and Function, 
`paginationShowsTotal: PropTypes.oneOfType([ PropTypes.bool, PropTypes.func ]),`

check https://github.com/AllenFang/react-bootstrap-table/blob/master/src/BootstrapTable.js#L1326
