### ISSUE TITLE
Possible to get event from beforeSaveCell?

### ISSUE THREAD

**Issue by CoralSilver** [AllenFang/react-bootstrap-table#1222]
Is there a way to get the event from the function called by beforeSaveCell?

From my constructor: 
```
    this.cellEditProp = {
      mode: 'click',
      blurToSave: true,
      beforeSaveCell: this.onBeforeSaveCell
    }  
```
If I pass in `e` to the below function it is undefined. I would like to show a confirmation popover before save is complete and need the event.target.  Also, would it be possible to reference `this.state` from inside this function somehow?
```
onBeforeSaveCell(row, cellName, cellValue) {
    // show confirmation popover
    this.setState({ target: e.target, show: !this.state.show }
);
```

**Comment by AllenFang** [comment]
I dont pass the event object to callback function, but if you just want to popup a modal, why need `e.target`??  it's not make sense, the `e` object will be the cell you are editing.

Let me know if you have any questions, thanks

**Comment by CoralSilver** [comment]
I want to pop a confirmation for the cell they are editing.

**Comment by AllenFang** [comment]
sure, but you can put your conform modal in other place, and trigger it if you want, so it's not necessary to use the event target, right?

**Comment by Domiii** [comment]
You can return `false` from `beforeSaveCell` ([see here](https://github.com/AllenFang/react-bootstrap-table/tree/master/src/BootstrapTable.js#L925)) to prevent editing right away, however I'm not sure if there is a way to start the editor later once the modal is confirmed.

I would complain about the fact that [the docs](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/cell-edit-props.html#celleditbeforesavecell-function) do not mention the return value behavior...
