### ISSUE TITLE
defaultSort different for each column

### ISSUE THREAD

**Issue by DevAxia** [AllenFang/react-bootstrap-table#1225]
Hello, is there a way to have defaultSort difference for each column using TableHeaderColumn ?

I tried to use sortFunc={ this.revertSortFunc } as seen in doc but if I revert sorting this way, I would still get a down arrao while trying to sort ascending.

My sample project would be a table which gives Points in last column and Rank in first column.  I would like to have my first click setting ASC order on Rank but DESC order on Points (without having the wrong sorting arrow in the header).

Is it possible as it is now ?
Thank you
DevAxia

**Comment by AllenFang** [comment]
@DevAxia, i think you case is multi sort, right? check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/multi-sort-table.js to learn how to configure the multi sort and check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/manage-multi-sort-external-table.js to learn how to manage multi sort by yourself.

Let me know if you have any questions, thanks
