### ISSUE TITLE
How to over-ride the default sort order when click on column header buttons?

### ISSUE THREAD

**Issue by jabberwo** [AllenFang/react-bootstrap-table#1227]
Hi,

Not talking about defaultSortOrder when you use defaultSortName.  That works fine.  But my data alphabetical; and the first time you click on the v^ buttons on a different column the default is to sort "desc".  I want the first click to be an 'asc' sort -- since that is most likely what my user wants.  

Could really use a another option for this, defaultColumnSortOrder or something...

thanks,
Jab

**Comment by AllenFang** [comment]
You mean you want to click any row to get the ASC order at firstly? If yes, I'll try to support this feature, thanks.

**Comment by jabberwo** [comment]
I'm clicking on the column header. When there is no sorting on that column you see both the asc and desc icons.  The first click always ends up in desc order.  I'd like that first click in the column header to be in asc order. 

Thanks,
Jab

**Comment by AllenFang** [comment]
Fixed on `v3.2.2`, use `defaultASC` on `TableHeaderColumn` to assign the column sort as ASC as default

**Comment by jabberwo** [comment]
Awesome! "When once you have tasted flight you will always walk the earth with your eyes turned skyward; for there you have been and there you will always be." Leonardo da Vinci 

    On Wednesday, April 26, 2017 9:03 AM, Allen <notifications@github.com> wrote:
 

 Fixed on v3.2.2, use defaultASC on TableHeaderColumn to assign the column sort as ASC as default—
