### ISSUE TITLE
Validation is ignored when you tab out of a cell to the next cell

### ISSUE THREAD

**Issue by ditmarh** [AllenFang/react-bootstrap-table#1228]
I have verified on the demo the same behaviour, to replicate go to:
http://allenfang.github.io/react-bootstrap-table/example.html#celledit
Scroll to the bottom of the page.  Job Status must be a number, but if I type 'abc' and hit tab it saves 'abc'.  If I hit enter the validation error shows up.  Many users will just tab to the next cell.
I am using "react-bootstrap-table": "^3.1.3"

**Comment by AllenFang** [comment]
@ditmarh, thanks, I'll check it out 👍

**Comment by Maethorin** [comment]
I found a workaround... if you return false from the beforeSaveCell, the  save is cancelled... so, you can do something like this:

```javascript
  _beforeSaveCell(row, cellName, cellValue) {
    let validationResult;
    if (cellName === "foo") {
      validationResult = this._validateFoo(cellValue, row);
    }
    if (cellName === "bar") {
      validationResult = this._validateBar(cellValue, row);
    }
    if (!validationResult.isValid) {
      return false;
    }
    // anthing else...
  }
```
And in your render:

```javascript
    const cellEditOption = {
      mode: 'click',
      beforeSaveCell: this._beforeSaveCell.bind(this)
    };

    return (
            <BootstrapTable data={rows} cellEdit={cellEditOption}>
              <TableHeaderColumn dataField="id" isKey={true} editable={false} hidden />
              <TableHeaderColumn dataField="foo" editable={{validator: this._validateFoo}}>Foo</TableHeaderColumn>
              <TableHeaderColumn dataField="bar" editable={validator: this._validateBar}}>Bar</TableHeaderColumn>
            </BootstrapTable>
    );
```
Waiting for final solution... :smile:

**Comment by AllenFang** [comment]
I'll try to fix it in these couple day, and thanks @Maethorin's workaround and yes, return a bool value will perform the save cell can be saved or not.

**Comment by AllenFang** [comment]
Fixed on `v3.2.2`, please have a look :)  thanks

**Comment by Maethorin** [comment]
Yeah! validation is working now with TAB keys. 

I just got another problem that I'm still trying to figure it out to be more precise. When I press the TAB key in an invalid cell, the validation get the error but the input field lose the focus...

**Comment by AllenFang** [comment]
> When I press the TAB key in an invalid cell, the validation get the error but the input field lose the focus...

I think it's a normal behavior, because you key down the TAB so cause focus out from the input tag.

**Comment by ditmarh** [comment]
Thanks Allen, works great now!
