### ISSUE TITLE
How to hide column using && and false variable

### ISSUE THREAD

**Issue by Kolyasya** [AllenFang/react-bootstrap-table#1229]
I've made component with reusable table.
Now I want to show/hide few columns with passed props value, for example.

I've tried this:
![image](https://cloud.githubusercontent.com/assets/3371143/25131688/5c69f29a-244f-11e7-8375-d94dc0a4745c.png)

And got an error `Uncaught TypeError: Cannot read property 'props' of null`

![image](https://cloud.githubusercontent.com/assets/3371143/25131752/9f17cfb8-244f-11e7-848c-546e3588bac6.png)

I found `hidden` property, but it hides column just visually.
Do you have any suggestions how to fix it?

**Comment by AllenFang** [comment]
@Kolyasya, for this case, we don't support this usage, you may need to do it like following

```js
const columns = your_columns_meta.map(column => {
    if (column.showColumn) { // some condition for displaying column or not
        return (
            <TableHeaderColumn ......>
        );
    }
});

<BootstrapTable>
    { columns }
</BootstrapTable>

```
