### ISSUE TITLE
pagination controls appear over table and search control

### ISSUE THREAD

**Issue by jcabrerazuniga** [AllenFang/react-bootstrap-table#1230]
I am using your react-boot strap table with:

	ReactDOM.render(
	<BootstrapTable data={users} height='120' scrollTop={ 'Bottom' } pagination={true} search={true}>
      <TableHeaderColumn isKey dataField='id' width='10'>User ID</TableHeaderColumn>
      <TableHeaderColumn dataField='firstName' dataSort={ true } width='30'>First Name</TableHeaderColumn>
      <TableHeaderColumn dataField='lastName' dataSort={ true }  width='30'>Last Name</TableHeaderColumn>
	</BootstrapTable>,

The pagination works but the pagination controls appear over the table instead of under the table:
![userstableexample](https://cloud.githubusercontent.com/assets/27739794/25148739/2a65b600-2439-11e7-9f87-053eb0ef8620.jpg)

Also, it seems that the search control is not working. Is there any special setting for this one?

**Comment by AllenFang** [comment]
Forgot to import css, check https://github.com/AllenFang/react-bootstrap-table#cimport-css
