### ISSUE TITLE
[BUG] Search and pagination not working together

### ISSUE THREAD

**Issue by Anima-t3d** [AllenFang/react-bootstrap-table#1232]
When I enable search without pagination the table works as expected. However the moment I add pagination and I key in a search, it will show 'There is no data to display'. After this point it will never go back to show all results, even if the search input is empty.

Possibly related to: https://github.com/AllenFang/react-bootstrap-table/issues/125

**Comment by amdrgoncalves** [comment]
Almost the same here!  Setup is simple: <BootstrapTable data={ products } pagination={true} search={true}>
But in my case the filtering actually works, as I can see number of pages changing while I type in the search field (while table shows 'no data'). Besides, if I change pages I can see data back (filtered) and it only disappears again if I retype something on the search box.

**Comment by Anima-t3d** [comment]
> But in my case the filtering actually works, as I can see number of pages changing while I type in the search field (while table shows 'no data'). Besides, if I change pages I can see data back (filtered) and it only disappears again if I retype something on the search box.

I can confirm seeing the same behaviour. In my original post I did not have enough data to generate more than 1 page.

**Comment by ahmedprohic** [comment]
Same happening here, and I can confirm it started with version 3.1.8.

**Comment by AllenFang** [comment]
I'll fix it quickly, so before `3.1.8`, is all fine.

**Comment by AllenFang** [comment]
Please upgrade to `v3.2.1` and let me know if the problem still remain. thank

**Comment by amdrgoncalves** [comment]
Problem solved after upgrade. Thank you Allen!
