### ISSUE TITLE
Table does not refresh automatically when I search for data

### ISSUE THREAD

**Issue by sabriBoussetha** [AllenFang/react-bootstrap-table#1234]
Hello, 
When I search for data, the table does not refresh automatically to display the results found and I have to change pagination or number of rows displayed to see the result.
I did not have this issue, but when I started using Tabs containing multiple Tab generated with a loop, it appeared. 
There is any custom options to fix it?
Thanks in advance for your reply.

**Comment by AllenFang** [comment]
I thinks it's a critical bug, whats version you used? `v3.1.8`? if yes, please go back to `3.1.7` for a workaround, I'll fix it quickly.

**Comment by AllenFang** [comment]
Please upgrade to `v3.2.1` and let me know if the problem still remain. thank

**Comment by sabriBoussetha** [comment]
I have upgraded to ```v3.2.1``` and it is working good. 
Thank you. :+1:
