### ISSUE TITLE
Can i Change the sizePerPageList to a Select Drop Down 

### ISSUE THREAD

**Issue by kamarajuPrathi** [AllenFang/react-bootstrap-table#1235]
Can i Change the sizePerPageList to a Select Drop Down  rather than a button

**Comment by AllenFang** [comment]
sure, you can custom it, check https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/custom/pagination

Please let me know if you got any questions. Thanks

**Comment by EkhatorOwen** [comment]
I need the table to be saved after I make a change in the dropdown. How can I do this?
