### ISSUE TITLE
UUid support for key values

### ISSUE THREAD

**Issue by jcabrerazuniga** [AllenFang/react-bootstrap-table#1236]
Could it be possible for you to add the option of generating a uuid for key values every time we want to add a new row to a table? The auto feature uses simple integers and this is kind of problematic for DB systems that use complex IDs
   There is a nice UUid library at: https://www.npmjs.com/package/uuid
thanks

**Comment by AllenFang** [comment]
I think it's not a critical feature, for your case, you can custom the key column when insert like following:

```js
const uuidV1 = require('uuid/v1');
//....

customKeyField = (column, attr, editorClass, ignoreEditable) => {
    const seqId = this.refs.table.state.data.length;
    return (
      <input type='text' { ...attr } disabled value={ uuidV1() } className={ `${editorClass}` }/>
    );
  }
render() {
    return (
      <BootstrapTable ref='table' data={ products } options={ options } insertRow>
        <TableHeaderColumn dataField='id' isKey={ true } customInsertEditor={ { getElement: this.customKeyField } }>Product ID</TableHeaderColumn>
        <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
        <TableHeaderColumn dataField='sales'>On Sales?</TableHeaderColumn>
        <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }

```

How about this solution for you, my concern is that I dont want to add too many dependency into this library. but if you dont want to this feature, I'll consider to integrate with `uuid`

**Comment by jcabrerazuniga** [comment]
After getting to know your React component it is truly not needed as the  key id  column is needed just to show all the db columns on the screen and I hided it. For the true ID db column I used the uuID4().
