### ISSUE TITLE
afterSearch hook

### ISSUE THREAD

**Issue by venkat-vs-id** [AllenFang/react-bootstrap-table#1239]
Hi Alan,

Looks like the afterSearch hook doesnt work in the new 3.x version. Can you please look into it? 
For this parameter I assigned a plain function with just console.log some text.
a) Log is getting printed the first time table is rendered, 
b) but after a search the log was not printed that means that function was not called.

Regards,
-Kat

**Comment by AllenFang** [comment]
@venkat-vs-id, what's version you used now? `v3.1.8`, if yes, could please go back to `v3.1.7` and try it again? thanks

**Comment by venkat-vs-id** [comment]
I recently synced my fork. So it sud be the latest. will try the other version tom.

**Comment by AllenFang** [comment]
thanks and could you please show me your code? because I just test `afterSearch` on my local repo but can not reproduce this issue.

**Comment by venkat-vs-id** [comment]
Sorry Mate, It was my bad. I had put the function handle in the options parameter wrongly. all good now. thanks.

**Comment by AllenFang** [comment]
👍
