### ISSUE TITLE
Expandable Row Sample Data

### ISSUE THREAD

**Issue by robertegnacheski** [AllenFang/react-bootstrap-table#1242]
I am trying the use the expandable row example, though there is no sample data for it.

I tried writing my own sample data with a multidimensional array though I am getting errors. Not sure if they are related to the data.

**# Warnings / Errors-**

warning  Useless constructor       no-useless-constructor
error    'BSTable' is not defined  react/jsx-no-undef

**# Data-**

var products = [
  { id: 0, name: "Banana", price: [
    {
      sale1: 2.99, sale2: 1.99, sale3: .99
    }
  ]
   },
   { id: 1, name: "Apple", price: [
     {
       sale1: 2.99, sale2: 1.99, sale3: .99
     }
   ]
    }

]

**# Example from React BootStrap Table-**

class ExpandRow extends React.Component {
  constructor(props) {
    super(props);
  }

  isExpandableRow(row) {
    if (row.id < 2) return true;
    else return false;
  }

  expandComponent(row) {
    return (
      <BSTable data={ row.expand } />
    );
  }

  render() {
    const options = {
      expandRowBgColor: 'rgb(242, 255, 163)'
    };
    return (
      <BootstrapTable data={ products }
        options={ options }
        striped
        expandableRow={ this.isExpandableRow }
        expandComponent={ this.expandComponent }
        search>
        <TableHeaderColumn dataField='id' isKey>Product ID</TableHeaderColumn>
        <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
        <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
}

**Comment by AllenFang** [comment]
hi @robertegnacheski, I think you can check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/expandRow.js) example and in [this](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/expandRow) folder, we have some useful example for expanding row.

Let me know if you got any questions, thanks.

**Comment by robertegnacheski** [comment]
thanks! I ended up finding that late last night and am using it. @AllenFang
