### ISSUE TITLE
Multi-line support

### ISSUE THREAD

**Issue by jcabrerazuniga** [AllenFang/react-bootstrap-table#1244]
While entering text I found that if I press Enter then the respective cell will be updated. But, is there any multi-line support? Some people might like to enter paragraphs in a cell.
Thanks

**Comment by AllenFang** [comment]
You can custom it via css, check following:
`<TableHeaderColumn dataField='name' tdStyle={ { whiteSpace: 'normal' } }>Product Name</TableHeaderColumn>`
