### ISSUE TITLE
Stretching the search field to 100%

### ISSUE THREAD

**Issue by orangecoding** [AllenFang/react-bootstrap-table#1247]
Hi,

I'm thinking of switching from griddle to your lib. Therefor I'd like to know whether you've implemented a possibility to not only have the search field on the top right, but have it stretched to 100% (the complete width of the table)?

Thanks

**Comment by AllenFang** [comment]
it's possible but you need to custom it by yourself.  BTW, I'm wondering why you want to switch from this. As i know, `griddle` is awesome, even https://github.com/adazzle/react-data-grid and https://github.com/tannerlinsley/react-table is also good. For `react-bootstrap-table`, I still have a long road to go and **only myself**. But for `react-table`, `react-data-grid` even `griddle`, they are all the org which means they have more and fast evaluation on their product.

Anyway, you can check https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/custom/toolbar to learn how to custom the toolbar. For the customization, it is a new feature for `v3.x`, so let me know if you have any concern. Thanks
