### ISSUE TITLE
Validator With BlurToSave

### ISSUE THREAD

**Issue by IHeartReact** [AllenFang/react-bootstrap-table#1249]
If you create an 'alert('This input is not valid') inside a Validator function, while BlurToSave is enable.

It will create an infinite loop that can't be exited without checking "dismiss further notifications".

(Clicking "ok" on alert box re-initiates BlurToSave Thus validator as well .)

**Comment by AllenFang** [comment]
could you show me your code? thanks

BTW, for the validator, you are supposed to be return a bool value to tell `react-bootstrap-table` this value is valid or not, or return a particular object format to display the custom toastr message.

**Comment by AllenFang** [comment]
Close it due to no response.
