### ISSUE TITLE
Can I make the elements in React BootstrapTable as links?

### ISSUE THREAD

**Issue by ajits731** [AllenFang/react-bootstrap-table#1259]
I would like to make the elements in a whole column in the React BootstrapTable as links which are clickable and can redirect the user to another page or can open a modal.
![links](https://cloud.githubusercontent.com/assets/25746981/25424878/918ff45e-2a87-11e7-9d25-a2e840565a07.jpg)

**Comment by AllenFang** [comment]
use `dataFormat` on `TableHeaderColumn`, check https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/column-format/

**Comment by JaiMangalSingh** [comment]
colFormatter = (cell, row) => {
  let link = `url`
  return (
    <Link to={link}>
      {cell}
    </Link>
  )
}
and

<TableHeaderColumn dataField='url' dataFormat={this.colFormatter}  filter={ { type: 'TextFilter', delay: 1000 } }>Field Name</TableHeaderColumn>

**Comment by allendol** [comment]
How about in react-bootstrap-table-next version

**Comment by moniqueboea** [comment]
Has anyone figured out how to do this with react-bootstrap-table-next?
