### ISSUE TITLE
Conversion from table to flexbox

### ISSUE THREAD

**Issue by tbaeg** [AllenFang/react-bootstrap-table#126]
Thoughts on converting from a table implementation to `flexbox`? You also wouldn't need to bind to resize events as shown [here](https://github.com/AllenFang/react-bootstrap-table/blob/master/src/BootstrapTable.js#L102). Also, I think would be a better solution going forward from a code maintainability stand point. Seems upstream [bootstrap](http://v4-alpha.getbootstrap.com/getting-started/flexbox/) is thinking the same thing. May as well stay in line with the future. :)

**Comment by AllenFang** [comment]
Thanks your suggestion, it's useful, but it's the first time to hear the flexbox for me, so I think I need study hard ;( but we can discuss more on it  :)

**Comment by allankikkas** [comment]
@tbaeg can you point out which parts of the table make sense to port to flexbox? I have hard time seeing any positive outcome from this regarding current setup. Bootstrap is not moving to flexbox regarding tables, it's just used where it makes sense.

**Comment by tbaeg** [comment]
Really old ticket but I figured I should go and clean things out. Agreed with what you mentioned @allankikkas and going to close this issue.
