### ISSUE TITLE
defaultSortName and defaultSortOrder for remote sorting

### ISSUE THREAD

**Issue by pinkynrg** [AllenFang/react-bootstrap-table#1261]
it would be nice to have defaultSortName and defaultSortOrder for remote table too. Now if I set them, I'm also supposed to check if they are set and change the query to fetch data accordingly. 

I would expect that, if they are set, also the method onSortChange is called or even better, something more efficient, in order not to do 2 api calls on component mounting.

**Comment by pinkynrg** [comment]
closing since I saw that someone else is talking about the same issue #1256

**Comment by pinkynrg** [comment]
actually it's only related by still I would like to have clarification if possibile.

**Comment by AllenFang** [comment]
@pinkynrg, I'll consider to add this feature, thanks. But this feature is not very critical so no schedule here.

**Comment by AllenFang** [comment]
@pinkynrg, could you upgrade and try again, I think it should be fixed on https://github.com/AllenFang/react-bootstrap-table/commit/a15c492dd1e4ceae05aabc1c2632f89b10258941
