### ISSUE TITLE
How to generate a header in loop?

### ISSUE THREAD

**Issue by unreg** [AllenFang/react-bootstrap-table#1265]
Hi!

I try:
```
const { rows, options } = this.props;
columns = ["Col1", "Col2", "Col3"];

return (
  <BootstrapTable data={rows} options={options} >
        <TableHeaderColumn dataField="num" isKey >#</TableHeaderColumn>
        {
          columns.map(function(item, i){
            return <TableHeaderColumn key={i}>{item}</TableHeaderColumn>
          })
        }
  </BootstrapTable>
)
```

and have error: `TypeError: props is undefined`

**Comment by AllenFang** [comment]
```js
 <BootstrapTable data={rows} options={options} keyField='num'>
        {
          columns.map(function(item, i){
            return <TableHeaderColumn key={i}>{item}</TableHeaderColumn>
          })
        }
  </BootstrapTable>
```

**Comment by tzarger** [comment]
@AllenFang I was trying to generate the TableHeaderColumn in a map function such as this and I received an error:

BootstrapTable.js:240 Uncaught Error: Error. No any key column defined in TableHeaderColumn.
            Use 'isKey={true}' to specify a unique column after version 0.5.4.

Did something change? I don't see "key" as a prop in the source code. Can that be added back?

**Comment by AllenFang** [comment]
@tzarger, you can try `keyField` on `BootstrapTable`
