### ISSUE TITLE
Is BootStrap table resetting after it gets unmount

### ISSUE THREAD

**Issue by jcabrerazuniga** [AllenFang/react-bootstrap-table#1271]
I created a React object R that will use two react components: C and B. C is used to select the columns to be shown on a table passed to B (this is the bootstrap table comp). After C is modified, every time R is rendered, B renders the columns filtrated by C but the columns of the table shown at B look quite messy respect of their widths. The definition of R looks like:

var R = React.createClass {
     ...
     render: function() {
           state S  to save the columns to be shown by B but that can be modified by C
          return (
             <C>
              < B >              
          )
     }
}

Here < B > is like
      < BootStrapTable .... >
              {function that assembles the TableHeaderColumn components that are filtered using S}
      < /BootStrapTable >

But I believe this happens because <BootStrapTable> is not reseted after this component is unmount,. All works well if I reload the page that calls R.

**Comment by jcabrerazuniga** [comment]
There is an ongoing discussion over this problem at:
http://stackoverflow.com/questions/43688956/un-mounting-a-react-component-from-somewhere/43689173?noredirect=1#comment74425333_43689173

**Comment by AllenFang** [comment]
@jcabrerazuniga, sorry for lately reply, could you please update your example code?  I really can not understand. thanks

**Comment by jcabrerazuniga** [comment]
At the next picture you can see my interface. There is a react Select component with the names of the table columns that are actually shown:
![start_table](https://cloud.githubusercontent.com/assets/27739794/25716960/38672306-30be-11e7-8551-cb5e9224b830.jpg)

After deleting some column names from the Select component I could get:
![some_deleted](https://cloud.githubusercontent.com/assets/27739794/25717002/63dcb956-30be-11e7-9bcf-41b564f2e361.jpg)

The problem happens when I start re-adding columns. I could see:
![after_erasing_adding_cols](https://cloud.githubusercontent.com/assets/27739794/25717062/8ea11c86-30be-11e7-82fa-fdf3e3438f82.jpg)

The code that basically governs this behavior is:

var UsersTable = React.createClass ({
	
	getInitialState: function() {
       return {sel_Options: this.props.ini_Options,             //all the possible columns
	           sel_valueArray: this.props.ini_valueArray        //selected user columns
			  };
    },

	handleSelectChange (value) {
		console.log('You\'ve selected: ');
		console.log(value);
		this.setState({sel_valueArray: value });
	},
	
	componentWillUpdate(nextProps, nextState){
       if(nextState.s != this.state.s)
               this.forceUpdate();
    },
	
	render: function() {
		const selectRow = {
			mode: 'checkbox',  // multi select
			bgColor: 'yellow',
			columnWidth: '60px'
		};
		
		return(
		
			<div>
			     <div>
				     <Select name = "form-field-name" options = {this.state.sel_Options}  value = {this.state.sel_valueArray} multi={true} onChange={this.handleSelectChange} searchable />					 
				 </div>
				 
				 <div>
					<BootstrapTable data={this.props.ini_usersTbl} striped search selectRow={ selectRow } cellEdit={ cellEditProp } height='600px' insertRow={ true } scrollTop={ 'Bottom' } multiColumnSearch={ true } options={ options } headerStyle = {{ background: '#ebf5ff'}} >		
						{   
							rAll_column_components(compsMap, this.state.sel_valueArray)
						}
					</BootstrapTable>
				 </div>
			</div>
				
	    );		
	}
});

the function   rAll_column_components(compsMap, this.state.sel_valueArray)   generates all the <TableHeaderColumn> components that the Bootstrap table needs to show. At present, all the returned <TableHeaderColumn> components always have the 'width' value the same, yet I can see the distortion:

![after_erasing_adding_cols](https://cloud.githubusercontent.com/assets/27739794/25717354/72ed0382-30bf-11e7-8d94-bd96536da45f.jpg)

Hope this helps to understand my problem.

**Comment by AllenFang** [comment]
@jcabrerazuniga, you means the each column width is not match to your configuration??

**Comment by AllenFang** [comment]
I wrote a quick example to reproduce issue, but everything is ok:

```js
class BasicTable extends React.Component {

  constructor(props) {
    super(props);
    console.log('==');
    this.state = {
      columns: [ {
        dataField: 'id',
        name: 'Product ID'
      }, {
        dataField: 'name',
        name: 'Product Name'
      }, {
        dataField: 'price',
        name: 'Product Price'
      }, {
        dataField: 'price1',
        name: 'Product Price One'
      }, {
        dataField: 'price2',
        name: 'Product Price Two'
      }, {
        dataField: 'price3',
        name: 'Product Price Three'
      } ]
    };
    this.renderColumn = this.renderColumn.bind(this);
  }

  lesscolumn = () => {
    this.setState({
      columns: [ {
        dataField: 'id',
        name: 'Product ID'
      }, {
        dataField: 'name',
        name: 'Product Name'
      }, {
        dataField: 'price1',
        name: 'Product Price One'
      }, {
        dataField: 'price3',
        name: 'Product Price Three'
      } ]
    });
  }

  morelcolumn = () => {
    this.setState({
      columns: [ {
        dataField: 'id',
        name: 'Product ID'
      }, {
        dataField: 'name',
        name: 'Product Name'
      }, {
        dataField: 'price',
        name: 'Product Price'
      }, {
        dataField: 'price1',
        name: 'Product Price One'
      }, {
        dataField: 'price2',
        name: 'Product Price Two'
      }, {
        dataField: 'price3',
        name: 'Product Price Three'
      } ]
    });
  }

  renderColumn() {
    return this.state.columns.map(column => {
      return (
        <TableHeaderColumn width='200' dataField={ column.dataField }>{ column.name }</TableHeaderColumn>
      );
    });
  }

  render() {
    const selectRow = {
      mode: 'checkbox',
      columnWidth: '50px'
    };
    return (
      <div>
        <button onClick={ this.lesscolumn }>Less Column</button>
        <button onClick={ this.morelcolumn }>More Column</button>
        <BootstrapTable keyField='id' data={ products } selectRow={ selectRow }>
          { this.renderColumn() }
        </BootstrapTable>
      </div>
    );
  }
}
```

Click "Less Column" will reduce some columns and click "More Column" will make columns size become original size.

Please show me how to reproduce this issue

**Comment by jcabrerazuniga** [comment]
Well, seems you are deleting just one column. In my case if I had 6 columns and deleted 4 or all of them. and added those again I obtained the problem. Let me see if I can reproduce the problem in another way. Thanks

**Comment by AllenFang** [comment]
I delete two columns `Product Price` and `Product Price Two`, you can check again.
