### ISSUE TITLE
Create table without having dataField values? 

### ISSUE THREAD

**Issue by shogan94** [AllenFang/react-bootstrap-table#1273]
Just curious if this is possible (and easily achievable). Currently working on the front-end side of things and would take time to get someone else to change the backend. But right now the data comes back as a list of strings for the headers (i.e. `Headers = ['First Name', 'Last Name', 'Phone Number']`) and then the data is just a list of a list of strings (i.e. `Rows = [['John', 'Doe', '123456789'],['Jane', 'Smith', '12345678']]`).

Can I use `react-bootstrap-table` without changing the data and adding field names to each?

**Comment by AllenFang** [comment]
You need to change the data on client side. Let me know if you still have any concern :)
