### ISSUE TITLE
clickToSelect is not working even when set to true

### ISSUE THREAD

**Issue by rohitb7** [AllenFang/react-bootstrap-table#1275]
I want the row to be clickable so that the user does not need to click the checkbox only. I am setting the clickToSelect to true. This is the way I have written the code. Am I doing something wrong or have missed anything?

       onRowClick (row, isSelected, e) {
              .................
       }

      const selectRow = {
          mode: 'checkbox',
          bgColor: 'pink',
          clickToSelect: true,
          clickToExpand: false
       }

        const options = {
          sortName: this.state.sortName,
          sortOrder: this.state.sortOrder,
          onSortChange
          onRowClick
        }

         <BootstrapTable
           selectRow={selectRow}
           options={options}
           >
        </BootstrapTable>

**Comment by AllenFang** [comment]
what version you used? and how about remove the `onRowClick` and try again?

**Comment by rohitb7** [comment]
I am using "^3.1.1".  I tried removing 'onRowClick' still it is not
working.

**Comment by AllenFang** [comment]
I think it's impossible, could you please show me you codes?

**Comment by rohitb7** [comment]
*I have created a component called DataTable.js*

class DataTable extends Component {
.....

const { onRowClick } = this.props

 const options = {
   sortName: this.state.sortName,
   sortOrder: this.state.sortOrder,
   onSortChange,
//   onRowClick
 }

 const selectRow = {
   mode: 'radio',
   bgColor: 'lightgrey',
   clickToSelect: true,
  // onSelect: onRowClick
 }

render () {
return (
    <BootstrapTable
      selectRow={selectRow}
      options={options}
       >
    </BootstrapTable>
}

}




*Then used the Datatable.js component like this.*

class UsersView extends Component {

...

onRowClick (row) {
  this.props.fullProfileSwitch(true) //selects individual row
}


render () {

  return (
          <DataTable
            onRowClick={this.onRowClick}
          />
    </div>
  )
}

}



I don't understand where to place the onRowClick in the options or in the
selectRow.

If I place onRowClick into the options, the onRowClick works and does
select the row but the checkbox remains unchecked of that row.

If I place onRowClick into the selectRow, the onRowClick works but I
specifically need to click only the checkbox and clicking anywhere on the
row does not work.

Thanks

**Comment by AllenFang** [comment]
1. we only have `options.onRowClick`.
2. I still can not reproduce your issue, can you go to http://allenfang.github.io/react-bootstrap-table/example.html#selection and find the "Click to Select" example and try it?

Because I can not reproduce it, so please give me more guideline, if I can reproduce it, I'll open this issue again.
