### ISSUE TITLE
Unselect all behavior is not consistent with select all when the data is filtered

### ISSUE THREAD

**Issue by victorbr** [AllenFang/react-bootstrap-table#1276]
The table is configured to have the selection enabled (`selectRow.mode = 'checkbox'`) and column filtering enabled as well.
Suppose the user filters some rows using column filters and presses the "select all" checkbox (at the selection column header).
As expected, only the visible rows are selected.
Now suppose the user changes the filter to display a different set of rows (possibly seeing some selected rows).
Now pressing the "unselect all" checkbox again unselects **all** rows of the table, both those that are visible and those that are not.
This behavior is surprising and not consistent with "select all" which selects only the visible rows.
I couldn't find a way to configure this behavior. Would it be possible to add a configuration option for this (I guess you couldn't just change it for compatibility reasons)? Thank you!

**Comment by AllenFang** [comment]
> I couldn't find a way to configure this behavior. Would it be possible to add a configuration option for this

sure, I'll try to support it, but need some time.

> I guess you couldn't just change it for compatibility reasons

Absolutely right

**Comment by AllenFang** [comment]
Fixed on `v3.3.1`, enable `selectRow.onlyUnselectVisible` will help you, thanks

**Comment by victorbr** [comment]
Thank you for the quick response! I just tried the new version but it doesn't seem simple. Consider the following scenario:

- Filter a set of items
- Press "select all" to select all of them
- Change the filter to select a different set of items (assume no selected among them)

The checkbox in the header now shows the "minus" sign (something is selected) and pressing it does nothing.

Another related problem (that I didn't mention in the original description) is the behavior when using paging. In that case the "select all" operation selects only the items visible on the current page. Is this intentional? Shall I open another issue so we wouldn't mix the two problems?

**Comment by AllenFang** [comment]
I'll handle it. 

> Is this intentional?

sure


> Shall I open another issue so we wouldn't mix the two problems?

yes your can.

**Comment by AllenFang** [comment]
Upgrade to `v3.3.2` and try again. thanks

**Comment by victorbr** [comment]
Thank you so much for that quick enhancement! Just checked it out and it works perfectly!
