### ISSUE TITLE
PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by shadow-identity** [AllenFang/react-bootstrap-table#1278]
Hello,
In 3.3.0, in SelectRowHeaderColumn proptypes defined as 
```
SelectRowHeaderColumn.propTypes = {
  children: _react.PropTypes.node,
  rowCount: _react.PropTypes.number
};
```
It causes Deprecation warning on React:

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

React recommends to use prop-types npm package: https://facebook.github.io/react/docs/typechecking-with-proptypes.html

**Comment by AllenFang** [comment]
There's a PR https://github.com/AllenFang/react-bootstrap-table/pull/1253 for fixing it, please wait, thanks

**Comment by aliceathens** [comment]
Do you have an ETA on this? Unit tests are failing because of this error. Thanks!

**Comment by AllenFang** [comment]
It was fixed on `v4.0.0-beta.5` and ETA may in the second or third week on June

**Comment by ofirgeller** [comment]
@AllenFang I think the dist files were not updated when v4.0.0-beta-6 (and 5) were commited. I checked and they still have ` React.PropTypes ` in them, you might not be seeing the warnings because you are running via a build system, but when I try depending on this commit I do get the warning.

**Comment by DavidDiscua** [comment]
@ofirgeller  Same issue for me.

**Comment by AllenFang** [comment]
I'll check, thanks 👍

**Comment by DavidDiscua** [comment]
I fix it using beta 6... 🤔.

**Comment by AllenFang** [comment]
@DavidDiscua, oh really, I doesn't check yet but it might be not a bug, @ofirgeller, could you please confirm this issue again, thanks

**Comment by ofirgeller** [comment]
@AllenFang  Fixed for me in 4.0.0-beta-6

**Comment by AllenFang** [comment]
@ofirgeller, nice 👍 thanks your response 👍

**Comment by pyronicide** [comment]
Looks broken again in 4.0.0-beta-7 again.

**Comment by jtheberge** [comment]
Also broken in beta-7 for me

**Comment by AllenFang** [comment]
hey folks, I'll fix it in next beta version, sorry

**Comment by AllenFang** [comment]
upgrade to `v4.0.0-beta.8`, let me know if the problems still remains, thanks

**Comment by jtheberge** [comment]
Hey @AllenFang! Unfortunately, the issue still exists for me in beta.8. Thanks for your work so far!

**Comment by AllenFang** [comment]
@jtheberge, thanks, Seems like i forgot change [this](https://github.com/AllenFang/react-bootstrap-table/blob/v4.0.0-dev/src/ExpandRowHeaderColumn.js#L1)   lol
