### ISSUE TITLE
Drop down filters above the table.

### ISSUE THREAD

**Issue by leonkalema** [AllenFang/react-bootstrap-table#1280]
Hello, much as I am new to react nothing has made my work easier than this amazing repo. 
However am kind in need to learn how best I can have the The Column Filters for example the drop down  above the table and not in that specific column. 

Thank you again for the amazing work.

**Comment by AllenFang** [comment]
for the column filter, we have text, regex, number, date and select filter, how about this [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/select-filter.js)? I think it's match your requirement, http://allenfang.github.io/react-bootstrap-table/example.html#column-filter have some filter examples.

Let me know if you still have any questions. thanks

**Comment by leonkalema** [comment]
Hello Allen, 

Thank you again. Probably my explanation was not that clear. What I seek to learn is how I can have the select filter on top of the table and not within that specific column. 

So that on the table I can have 

ADD Content Button , Search Form and the Also Select to Filter.

**Comment by AllenFang** [comment]
@leonkalema, sorry for misunderstand your requirement, actually, we dont have this kind of feature, but you can custom it by yourself and call the filter or search function exposed by `react-bootstrap-table`

check [this](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/custom/toolbar) to learn how to custom toolbar

check [this](http://allenfang.github.io/react-bootstrap-table/docs.html#handleSearch) to search table

check [this](http://allenfang.github.io/react-bootstrap-table/docs.html#handleFilterData) to filter by column

For me, I guess, you need to have a custom component and when use select some value, you need to do the search/filter, you can call `handleSearch` or `handleFilterData`, but you can also filter your data in your application.

Please let me know if you still have any question, thanks 👍

**Comment by smilingpigs** [comment]
@leonkalema, hello, even I have a similar requirement as you mentioned, did you implement it by any chance? Thanks in advance.

**Comment by AllenFang** [comment]
@smilingpigs, please check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js to learn how to custom column filter
