### ISSUE TITLE
sortFunc is not working

### ISSUE THREAD

**Issue by BhumiSukhadiya** [AllenFang/react-bootstrap-table#1281]
I want to add sorting on all data fields with same name where datafield is an object.
is there any solution for this issue?

**Comment by AllenFang** [comment]
`react-bootstrap-table` does not support same `dataField` in one table, it'll cause some bugs. https://github.com/AllenFang/react-bootstrap-table/issues/1113 I'll spend some time to support this feature but it is lower priority.
