### ISSUE TITLE
sizePerPageList

### ISSUE THREAD

**Issue by kamarajuPrathi** [AllenFang/react-bootstrap-table#1284]
@AllenFang  When sizePerPageList has a custom option like ALL(100) . When i delete a row ,the size per pagelist dropdown is clearing off instead of showing ALL(99).

Let me know if you did get my question.

**Comment by AllenFang** [comment]
@kamarajuPrathi, ok I'll check this, but could you show me your custom options? thanks

**Comment by kamarajuPrathi** [comment]
sizePerPageList: [
        { text: '10', value: 10 },
        { text: '25', value: 25 },
        { text: '50', value: 50 },
        { text: '100', value: 100 },
        { text: '200', value: 200 },
        { text: `no. of employees (${employeesCount}) `, value: employeesCount }

**Comment by kamarajuPrathi** [comment]
never mind employeesCount i was separteley calculating , if i change to employees.length it works fine .. thanks

**Comment by kamarajuPrathi** [comment]
Sorry for reopening it , @AllenFang it didnt work . Can you please look in to it

**Comment by AllenFang** [comment]
how did you handle the delete row? I think i need a small, simple, minimal example for me to reproduce this, thanks.

**Comment by AllenFang** [comment]
close it due to no response for a long time
