### ISSUE TITLE
"Show All/Show selected only"  label problem

### ISSUE THREAD

**Issue by jcabrerazuniga** [AllenFang/react-bootstrap-table#1285]
At   'Show Only Selected '  from

http://allenfang.github.io/react-bootstrap-table/example.html#selection

there is a button that allows to show just the selected elements or to show all the elements. Depending on the location, it could be usual to understand that the label of a button will execute the related action: i.e. if the button says "show all" then after pressing it, it will displayed all the elements of the table. If the button says: "show selected only" then after clicking on that button only the selected items will appear. However, as today, by default the inverse is happening with ReactBoothstrapTable. Is there anyway to change these values? It could be useful as I might like to use Spanish words to label those buttons. Thanks

**Comment by AllenFang** [comment]
I'll improve it. if you want to custom it, you can check [this](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/custom/show-only-select-button)

**Comment by AllenFang** [comment]
Fixed on `v4.0.0`
