### ISSUE TITLE
update documentation for autoValue

### ISSUE THREAD

**Issue by Bersam** [AllenFang/react-bootstrap-table#1287]
Seems autoValue can get a function:
https://github.com/AllenFang/react-bootstrap-table/blob/30cad00731488a2733a244e24ea861e4f7e47e00/src/toolbar/InsertModalBody.js#L15
it would be great add this information in document:
https://allenfang.github.io/react-bootstrap-table/docs.html#autoValue

**Comment by AllenFang** [comment]
I'll do it, thanks :)

**Comment by AllenFang** [comment]
Done, thanks you very much :)
