### ISSUE TITLE
TableHeaderColumn - expandable={false} is ignored

### ISSUE THREAD

**Issue by antetmc2** [AllenFang/react-bootstrap-table#1288]
Hey, I noticed an issue with expandable attribute when I'm using it in TableHeaderColumn. I'm using react-bootstrap-table (version 3.3.1) and I noticed that expandable={false} is ignored.

Basically, whenever I click any column that has expandable={false}, the row is expanded like it doesn't contain that attribute.

Here is an example of code:

    <BootstrapTable data={this.props.instances}
        bordered={false}
        hover
        expandableRow={this.isExpandableRow}
        expandComponent={this.expandComponent}>
        <TableHeaderColumn dataField='server' dataSort width='22%' filter={{ type: 'TextFilter', delay: 100 }}>Server</TableHeaderColumn>
        <TableHeaderColumn dataField='serverDatabase' dataSort width='22%' filter={{ type: 'TextFilter', delay: 100 }}>Database</TableHeaderColumn>
        <TableHeaderColumn dataField='integratedSecurity' dataSort width='14%' filter={{ type: 'SelectFilter', options: integratedSecurity }}>Integrated Security</TableHeaderColumn>
        <TableHeaderColumn dataField='userId' dataSort width='16%' expandable={false} dataFormat={this.loginInfo} filter={{ type: 'TextFilter', delay: 100 }}>User Id</TableHeaderColumn>
        <TableHeaderColumn dataField='password' dataSort width='16%' expandable={false} dataFormat={this.loginInfo} filter={{ type: 'TextFilter', delay: 100 }}>Password</TableHeaderColumn>
        <TableHeaderColumn dataField='id' isKey width='10%' expandable={false} dataFormat={this.actions}></TableHeaderColumn>
    </BootstrapTable>

**Comment by AllenFang** [comment]
Default expand is by `row`, if you want to expand by column, you should give `options.expandBy` to eq `column` then the `expandable can be work well on each column. Check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/expand-row-by-column.js

**Comment by antetmc2** [comment]
I just tried with options.expandBy and it works, thanks a lot! :D
