### ISSUE TITLE
No easy way to set default value in Insert Modal

### ISSUE THREAD

**Issue by p21asthana** [AllenFang/react-bootstrap-table#1294]

**Comment by p21asthana** [comment]
I want to set a default value for a column while adding a new row. I am not able to figure out any easy straight forward way to do so. The custom insert modal seems to be the only option

**Comment by AllenFang** [comment]
Currently, the most easy way is https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/insert-modal/custom-insert-modal-field.js, but I think i can support this feature in next or next two versions :)

**Comment by AllenFang** [comment]
@p21asthana, fixed on `v3.3.5`, check [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/advance/insert-default-value-table.js)

use `editable.defaultValue` to assign the default value in insert model field

**Comment by p21asthana** [comment]
Awesome.... Thanks a lot

**Comment by sunnybogawat** [comment]
I have used the default value as mentioned above 
`<TableHeaderColumn dataField="ttl" dataSort={true} editable={{defaultValue: '28800' }}>
            TTL
          </TableHeaderColumn>`
but when I click on New the form not showing default value in the textbox

**Comment by p21asthana** [comment]
After updating to the latest version, i am receiving the following error -
Module not found: Error: Cannot resolve module 'react-dom/lib/getVendorPrefixedEventName'

**Comment by AllenFang** [comment]
@sunnybogawat, try again with following?
`<TableHeaderColumn dataField="ttl" dataSort={true} editable={{ type: 'text', defaultValue: '28800' }}> TTL </TableHeaderColumn>`

@p21asthana, I've no idea about your error, I think its not related with this release.
