### ISSUE TITLE
When insert new record, the record can't save to the dataList

### ISSUE THREAD

**Issue by zhangwei8607** [AllenFang/react-bootstrap-table#1295]
Actually the new added record is shown in the table view, but when I update some value in the  state of the page, the new added record will miss.

**Comment by zhangwei8607** [comment]
Fixed by add method to props

`onAfterInsertRow(row) {
	var list = this.state.list;
	list.push(row);
	this.setState({list : list});
}

onAfterDeleteRow(rowKeys) {
  var list = this.state.list;
  list.forEach(function(c, i) {
	rowKeys.forEach(function(key) {
	  if(c.fieldName === key) {
		list.splice(i, 1);
	  }
	});
  });
  this.setState({list : list});
}

<BootstrapTable data={this.state.list} cellEdit={ cellEditProp } options={ {**paginationShowsTotal : false, afterDeleteRow : {this.afterDeleteRow.bind(this)}, afterInsertRow : {this.afterInsertRow.bind(this)}**} } insertRow deleteRow selectRow={ selectRowProp }>
`

**Comment by AllenFang** [comment]
ok, let me know if you still have any questions :)
