### ISSUE TITLE
Getting row index onRowClick

### ISSUE THREAD

**Issue by amx93** [AllenFang/react-bootstrap-table#1296]
onRowClick: this.modalClick()
modalClick(row, index){...

index value undefined

**Comment by AllenFang** [comment]
Too few information for me to reproduce, please shoe me your case due to [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/row-click-table.js) still work well.

close it because lack of information.

**Comment by prajapati-parth** [comment]
Hi @AllenFang, I just came across this issue. I think what @amx93 need was the rendered row index. 
Eg. If there are total 15 rows with 5 rows on each page, clicking on the 5th row of each index should get a number 4. 
Specifically the number that you use [here](https://github.com/AllenFang/react-bootstrap-table/blob/master/src/TableBody.js#L160)

This would be irrespective of the sort or pagination. Every time a visually displayed 3rd row is clicked, it's index 2 should be received even if it is sorted.

**Comment by prajapati-parth** [comment]
This can be solved by replacing [this line](https://github.com/AllenFang/react-bootstrap-table/blob/master/src/BootstrapTable.js#L665) with
```
options.onRowClick(row, columnIndex, rowIndex);
```
Thanks.

**Comment by AllenFang** [comment]
@prajapati-parth thanks your 👍   I'll add `rowIndex` as third parameter for `options.onRowClick`.

**Comment by AllenFang** [comment]
@prajapati-parth it was fixed on `v3.4.5`, thanks

**Comment by 9005** [comment]
For the below code I get undefined for columnIndex and rowIndex.
 onRowClick:function(row,columnIndex,rowIndex,e){
          console.log(`${columnIndex}`);
        }

need help!!

**Comment by PriyankaMGK** [comment]
How can i set the serial number starts from 1 dynamically in react bootstrap table.
my json would be getdata={  
   "data":{  
      "List":[  
         {  
            "name":"React"
         },
         {  
            "name":"Javascript"
         }
      ]
   }
};
<BootstrapTable data={ getdata } striped hover pagination={ true }  options={ options }  search={ true }>
<TableHeaderColumn true dataField='what' isKey={true} dataAlign="center">S.No</TableHeaderColumn>
 <TableHeaderColumn dataField='name' dataAlign="center" dataSort={ true }> Name</TableHeaderColumn>
</BootstrapTable>

**Comment by PriyankaMGK** [comment]
<TableHeaderColumn true dataField='what' isKey={true} dataAlign="center">S.No</TableHeaderColumn>
