### ISSUE TITLE
Setting unselectable is not working ,Who can help me? very urgent . react-bootstrap-table@3.3.3

### ISSUE THREAD

**Issue by martin-tian** [AllenFang/react-bootstrap-table#1297]
render() {
	  const selectRowProp = {
			mode: 'checkbox',
			clickToSelect: true,
			unselectable: [ 1, 3 ],
			bgColor: "rgb(238, 193, 213)" ,
			columnWidth: '60px',
			onSelect: this.handleRowSelect,
			onSelectAll: this.handleSelectAll
			
		};
    return (
      <BootstrapTable data={ this.state.products } selectRow={ selectRowProp } maxHeight='420px' >
          
          <TableHeaderColumn dataField='IP' isKey={ true }>网络IP</TableHeaderColumn>
          <TableHeaderColumn dataField='ID'>Node ID</TableHeaderColumn>
		  <TableHeaderColumn dataField='phone'>手机号</TableHeaderColumn>
		  <TableHeaderColumn dataField='status'>状态</TableHeaderColumn>
      </BootstrapTable>
    );

**Comment by AllenFang** [comment]
HI @martin-tian, so you still can select the item which rowkeys contain in the `unselectable` array?

Please make sure the id value is `number`, because the value in the `unselectable`  is a number array, so if the rowkey in your raw data is string, I guess it will be selectable.

**Comment by martin-tian** [comment]
HI @AllenFang First of all, thank you for your help ,The cause of the problem is the lack of index line ,like this :

addProducts=(quantity)=>{
		const startId = this.state.products.length;
		for (let i = 0; i < quantity; i++) {
			const id = startId + i;
			this.state.products.push({
			  index: id,                       **//this index Correspond to table  The first line** 
			  IP: '10.5.55.3' + id,
			  ID: 'fff32100' + i,
			  phone:1351111111+i , 
			  status:' '
			});
		}
	}
<BootstrapTable data={ this.state.products } selectRow={ selectRowProp } maxHeight='420px' >
  **<TableHeaderColumn dataField='index' isKey={ true }>ID</TableHeaderColumn>**   //this line
  <TableHeaderColumn dataField='IP' isKey={ false }>网络IP</TableHeaderColumn>
  <TableHeaderColumn dataField='ID'>Node ID</TableHeaderColumn>
  <TableHeaderColumn dataField='phone'>手机号</TableHeaderColumn>
  <TableHeaderColumn dataField='status'>状态</TableHeaderColumn>
</BootstrapTable>

**Comment by AllenFang** [comment]
@martin-tian, could you please give me an example to reproduce this issue? But please keep it simple and minimal, thanks 👍

**Comment by martin-tian** [comment]
@AllenFang like this :
       class ReproduceIssueDemo extends React.Component{
            constructor(props) {
            super(props);		
		this.addProducts = this.addProducts.bind(this);
		this.handleRowSelect = this.handleRowSelect.bind(this);
		this.handleSelectAll = this.handleSelectAll.bind(this);
		this.componentWillMount = this.componentWillMount.bind(this);
		this.state={products:[],unselectable:[]};
	      }
	addProducts=(quantity)=>{
		const startId = this.state.products.length;
		for (let i = 0; i < quantity; i++) {
			const id = startId + i;
			this.state.products.push({
			  index: id,
			  userName: 'Bomte' + id,
			  phone:1355667311+i,
			  status:''
			});
		}
	}
	
	
	componentWillMount=()=>{this.addProducts(20);}


	handleRowSelect(row, isSelected, e) {
		if(isSelected){
			this.state.unselectable.push(this.state.row.index);//禁止被选择
			this.setState({unselectable:this.state.unselectable});
		}
	
	}
	handleSelectAll(isSelected, rows) {
		console.log('rows:'+JSON.stringify(rows)+' isSelected:'+isSelected);
	}

	
	 render=()=>{

		 const selectRowProp = {
			mode: 'checkbox',
			clickToSelect: true,
			columnWidth: '60px',
			bgColor: "#f9f9f9" ,
			unselectable:this.state.unselectable,
			onSelect: this.handleRowSelect,
			onSelectAll: this.handleSelectAll
		};
		
		return (<Layout>
					<Content style={{ padding: '0 24px', minHeight: 505 }}>
						<BootstrapTable data={ this.state.products } selectRow={ selectRowProp } maxHeight='420px' >
							  # <TableHeaderColumn dataField='index' isKey>ID</TableHeaderColumn>  //Without this line, it will not work  
							  <TableHeaderColumn dataField='userName' >账号名称</TableHeaderColumn>
							  <TableHeaderColumn dataField='phone'>手机号</TableHeaderColumn>
							  <TableHeaderColumn dataField='status'>状态</TableHeaderColumn>
						</BootstrapTable>
						<Button onClick={this.okBtn} className='run_btn'>确定</Button>
						<Button onClick={this.cancelBtn} className='run_btn'>取消</Button>
					</Content>
				</Layout>)
		}
};

**Comment by AllenFang** [comment]
@martin-tian, according your example code, did you want to make the row was unselectable when it is selected immediately?

**Comment by martin-tian** [comment]
@AllenFang ,Yes , did you reproduce  this issue? The code in the above example ,Note this line:

" # <TableHeaderColumn dataField='index' isKey>ID</TableHeaderColumn>  //Without this line, it will not work "

**Comment by AllenFang** [comment]
of course, `react-bootstrap-table` need a key column. It is necessary, and if you have key column, everything is fine?

**Comment by martin-tian** [comment]
If I had the key column, that would be fine,

**Comment by AllenFang** [comment]
Of course, it's necessary
