### ISSUE TITLE
Expand component rendered at table construction?

### ISSUE THREAD

**Issue by RichardYang2016** [AllenFang/react-bootstrap-table#1299]
Hi there, 

So the scenario is, in my redux store I have a node for data of current expanded row, and all rows are expandable. 

In debug I find that, such component are constructed for each and every row of the table, even if the row is not expanded. Plus, my redux node of current opened row are rendered to all components for the rows. Only difference is the components are hidden except the current selected row. 

Is there a way to not render all those expand components at the construction of the table itself, but rather render it and destruct it every time I expand/collapse a row?

Thanks, Richard.

**Comment by AllenFang** [comment]
did you means you want to render the expanding content when the row is expanded?

**Comment by RichardYang2016** [comment]
@AllenFang Hi Allen 
Actually I did achieve my goal by moving the API call to onSelect event, and compare id of the row  to the fetched id to only render subcomponent for the current expanded row. 

but this brings another small issue, when click the row again to collapse, the API is triggered again. I don't see any information in the documentation that I can get indicators from any event to tell if a row is expanded or collapsed. for example, properties like row.expanded.  This could be a good enhancement if currently not supported. 

Thanks, Richard.

**Comment by AllenFang** [comment]
I think use `onSelect` is also a workaround, but not the best solution and maybe I can support a hook function for you, called `onExpand` or something. i think it's much intuitive for developer

**Comment by RichardYang2016** [comment]
That would be great Allen! Thanks a lot !

Regards, Richard.

**Comment by AllenFang** [comment]
hello @RichardYang2016, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/manage-expanding.js#L62), I support the `options .onExpand` on `v3.3.5`.

**Comment by RichardYang2016** [comment]
Thank you so much Allen!

**Comment by zillerium** [comment]
I am getting a similar issue with the expand causing the expandComponent to be accessed for every row regardless of whether the user clicked expand or now. How is the onExpand implemented? Here is my code - https://github.com/zillerium/zmes/tree/master/zmes/src

**Comment by AllenFang** [comment]
Hey fork, I've no time to check your repo, it too big to me, give me the point or check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/manage-expanding.js#L80) example, thanks

**Comment by zillerium** [comment]
Fork the entire repo for asking a question?

**Comment by RichardYang2016** [comment]
obviously he actually meant 'folk'...   don't be panic. 

anyway I do recommend you looking at the example provided. put a event handler for onExpand in place and put a debug point to look at the event itself you should be able to figure out how to use it. It does solve my problem earlier. pretty neat.

**Comment by eyalap** [comment]
@zillerium @RichardYang2016 
I experienced the same thing and ended up doing something similar to what Allen suggested.
I had a heavy component rendered in my expanded component and with a table of 50 rows it already got slow.
This way I can have multiple expanded rows with data, and even tough I still have a component rendered to the DOM it's an empty component which is cheap.
I still think it should be the default behavior and managed internally in the component and not like this.

this.state = {
      expanding: {},
    }

  handleExpand(rowKey, isExpand, e) {
    if (isExpand) {
      const newExpandingKeys = this.state.expanding;
      newExpandingKeys[rowKey] = true;
      this.setState({
        expanding: newExpandingKeys,
      })
    } else {
      const newExpandingKeys = this.state.expanding;
      delete newExpandingKeys[rowKey];
      this.setState({
        expanding: newExpandingKeys,
      })

    }
  }

  expandComponent(row) {
    return this.state.expanding[row._key] ? this.props.expandComponent(row) : null
  }

const options = {
      onExpand: this.handleExpand,
    };

<BootstrapTable ......  expandComponent={this.expandComponent} >

**Comment by kevin-daniel-hunt** [comment]
Rendering every expanded column at table construction and not rendering the expansion when the row is expanded is incredibly unintuitive and will cause serious load-time issues for me as well.  Is there still no workaround, implementation, or fix?
