### ISSUE TITLE
After search not always trigerred

### ISSUE THREAD

**Issue by asafweiss** [AllenFang/react-bootstrap-table#1302]
Hi.
We've been using react-bootstrap-table in three tabs on the same page in our project.
When we wanted to add search that will trigger filtering of all three tables at the same time we added references to the tables ,added a separate text input and set its 'onChange' to call the tables 'handleSearch'.
We also set a 'afterSearch' method to all tables that updates the state according to the search result (we use it to display a summary at the top of each tab).
The search works very well in general.

The only problem is that every 30 seconds or so we perform a background update of the data, and sometimes as a result the data for the tables change.
The change is reflected as expected in the tables (an item that was in one table moves to the other as it should), however the 'afterSearch' is not called and as a result the summary we display is now incorrect.

We used version 2.3.4 by I updated to 4.0.0-beta.1 and it didn't help.

Thanks :)

**Comment by AllenFang** [comment]
@asafweiss, you means *sometime*,  `afterSearch` doesn't be call when data change every 30 second?

and when the data changed every 30 second, you will call the `handleSearch` also?

**Comment by asafweiss** [comment]
Hi.

**Comment by asafweiss** [comment]
Hi.
I have a text box. Whenever the text changes I call 'handleSearch' for all tables.
And 'afterSearch' seems to never get called when data changes. only after I call 'handleSearch' myself.

**Comment by AllenFang** [comment]
> And 'afterSearch' seems to never get called when data changes.

got it, I'll check it, but if there's only one table, is `'afterSearch` will be called?

**Comment by asafweiss** [comment]
I didn't check. I'll check and send an update tomorrow.

??? ?? Outlook ???? Android<https://aka.ms/ghei36>

________________________________

**Comment by AllenFang** [comment]
@asafweiss, fixed on `v3.3.4`, please check, thanks 👍

**Comment by asafweiss** [comment]
First of all, thank you for the very quick response and for the effort, it is highly appreciated.

I tested version 3.3.4 however it renders my page unresponsive. It seems to be stuck in some kind of endless loop, or maybe waiting for something, but the page is completely unresponsive with this version.
In fact, any attempt to display a table with a search results in the page getting stuck, including pages with a single table with constant data.

Regards,

Asaf.

**Comment by asafweiss** [comment]
To be sure that it wasn't something else in my project I reverted back to 3.3.3 and everything worked as it did before, moved again to 3.3.4 and everything is stuck again.

**Comment by AllenFang** [comment]
I probably know the problems, but I seems like got something wrong about your requirement. 

1. did you use `remote` mode?
2. what's did you do in `afterSearch`??

I think I need more technical description and explain about your flow, thanks.

**Comment by asafweiss** [comment]
You're correct!

In my 'afterSearch' I update the state which triggers a render, and with your fix it now triggers the 'afterSearch' again and so on and so forth.
I added a simple 'if' to prevent this and now everything works fine.
Thanks :+1:

**Comment by AllenFang** [comment]
ok, please let me know if you still have any concern or trouble, thanks 👍

**Comment by supiash1** [comment]
@asafweiss Could you tell me what was the condition you put for it to not trigger aftersearch twice as am facing the same problem thanks

**Comment by AllenFang** [comment]
@supiash1, please let me know your problem and show me your code but please keep it simple and minimal, thanks
