### ISSUE TITLE
Remote alternative pagination to fix back button bug

### ISSUE THREAD

**Issue by eyerean** [AllenFang/react-bootstrap-table#1303]
I am trying this since yesterday, I have read [issue 1093](https://github.com/AllenFang/react-bootstrap-table/issues/1093), but I cannot yet fix the pagination without something breaking.

The main goal is to be able to click something from within the table that gets you to another page, and when going back _we want to be redirected to the correct page of the table we were before_. 

I'll post here what I've tried but if anyone has made it work please post some help :)

The most correct-looking code I've tried is the one I post here, and has the following bugs:
 - when changing the `sizePerPage` pages are being added in a wrong way in pagination
 - when changing the `sizePerPage` number of rows shown remain the same 
 - clicking on a page or a next/last/etc label in the pagination resets table to its initial looks which only 1 page shown

EDIT:
Images show it clearer:

Starting with correct state:
<img width="838" alt="screen shot 2017-05-11 at 10 28 53" src="https://cloud.githubusercontent.com/assets/924281/25939934/d1687084-3634-11e7-9770-1502a31d5684.png">

Clicking '50' as the number displayed doesn't change the data displayed but assumes we have 50 rows of data:
<img width="836" alt="screen shot 2017-05-11 at 10 29 09" src="https://cloud.githubusercontent.com/assets/924281/25939962/e2ac4d2a-3634-11e7-9e30-f8f314c33708.png">

Clicking a number from pagination panel changes correctly displayed data but with this result:
<img width="842" alt="screen shot 2017-05-11 at 10 31 11" src="https://cloud.githubusercontent.com/assets/924281/25940022/0dbfe422-3635-11e7-8de7-2fee0bf02b3b.png">

Should the complete set of data we pass to the table change according to the pagination or not? I would expect that we always provide the complete data and that we don't have to handle the splitting of the data to pages ourselves, but even if we do so, then 1. please explain in documentation 2. separate somehow data displayed per page and the complete set of data provided 3. it seems that the issues lies there, on the modification of the data provided to the table, since clicking to the pagination panel or the sizePerPage panel seems to be modifying the total amount of data shown. The `totalDataSize` remains correct but the data displayed each time is exactly the number clicked on the sizePerPage dropdown.

Extra note: if I set `remote={true}`, then bug is same as [issue 872](https://github.com/AllenFang/react-bootstrap-table/issues/872), and when changing `sizePerPage` data appear correct but pagination is still frozen to showing same number of pages and active only the first.

Code:

```
      <BootstrapTable 
        data={runs} 
        options={options} 
        pagination 
        remote={remote} 
        hover 
        fetchInfo={{dataTotalSize: totalDataSize}} //no documentation says why this is important or necessary
        trClassName={'clickable'}>
          // TableHeaderColumns here with filtering and sorting that i don't want to do remotely
      </BootstrapTable>
```

`remote` is: 
```
const remote = (remoteObj) => {
  remoteObj.paging = true;
  return remoteObj;
}
```

`options` are:

```
tableOptions = {,
    page: this.state.currentPage,
    sizePerPage: this.state.sizePerPage,
    sizePerPageList: [30, 50, 100],
    prePage: 'Prev',
    nextPage: 'Next',
    firstPage: 'First',
    lastPage: 'Last',
    paginationShowsTotal: this.renderPaginationShowsTotal,
    onPageChange: this.handlePageChange,
    onSizePerPageList: this.handleSizePerPageList
  };
```
```

  handlePageChange = (page, sizePerPage) => {
    const currentIndex = (page - 1) * sizePerPage;
    this.setState({
      runs: this.props.runs.slice(currentIndex, currentIndex + sizePerPage),
      currentPage: page
    });
  };

  handleSizePerPageList = (sizePerPage) => {
    const currentIndex = (this.state.currentPage - 1) * sizePerPage;
    this.setState({
      runs: this.props.runs.slice(currentIndex, currentIndex + sizePerPage),
      sizePerPage: sizePerPage
    });
  };
```

Any help is very much appreciated.

_________
PS: Extra tip: please include somewhere in the documentation all the different properties for the alternative remote, I had to try both `paging` and `pagination` and `filter` and `filtering` etc to figure out whice ones work...

**Comment by AllenFang** [comment]
HI @eyerean, I think this issue have too many things... and could you please give me a example code to reproduce this all issues? please keep it simple and minimal(without redux, db, react-router, etc), just focus on `react-bootstrap-table` and work with some fake data.

Sorry, I really have too much time to write a huge and unknown code to reproduce any issue. 

Thanks a ton

**Comment by eyerean** [comment]
Allright I'll post some code soon, thanks for your reply!
Could you first help me a bit, is the `remote` method correct?

```
const remote = (remoteObj) => {
  remoteObj.paging = true;
  return remoteObj;
}
```

Or is it maybe `remoteObj.page = true;` or something else?

Thanks again!

**Comment by AllenFang** [comment]
@eyerean 
`remoteObj.pagination = true`,

sorry this I seems like doesn't write a good document on [here](http://allenfang.github.io/react-bootstrap-table/docs.html#remote), I'll patch later.

Anyway, thanks your help.

**Comment by eyerean** [comment]
Thank you, I fixed it!!

What fixed the remote pagination bug I had to keep the table's `options` within the component that renders `BootstrapTable`, and handle all state changes of the current page and data etc in the parent component (if one wants to separate the logic).

In order to fix the bug of the back button, you have to store to the redux store the current page, current data and current sizePerPage properties, and fetch them on `componentWillReceiveProps`.

I hope this helps somebody in the future, and thanks Allen for your library!

**Comment by AllenFang** [comment]
@eyerean, thanks your sharing, please let me know if you have any question
