### ISSUE TITLE
Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React

### ISSUE THREAD

**Issue by laitang2000** [AllenFang/react-bootstrap-table#131]
Using the library as a Browser global I get the following error message

"Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React"

Script references are -

    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
    <script src="https://fb.me/react-0.14.2.min.js"></script>
    <script src="https://fb.me/react-dom-0.14.2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>
    <script src="underscore.js"></script>
    <script src="react-bootstrap-table.min.js"></script>

any ideas on how I can resolve this?

Thanks

**Comment by AllenFang** [comment]
HI, could you give me the sample code? and did you use RequireJS to import <code>react-bootstrap-table</code>?

**Comment by laitang2000** [comment]
Hi, 

The code I'm testing with  https://gist.github.com/laitang2000/dd5b67cc8a44cc2d3a86#file-example-html

The script and css references are all cdn except for your library.

No I'm not using RequireJs.

Thanks

**Comment by AllenFang** [comment]
Maybe you dont use this style(write down the code on html) to write you application, I'm not sure the problem, but I think you can use webpack or browserify to bundle you module and include to you html, this error should not be happened. Anyway, I'll find the root cause :)

**Comment by npillarikuppam** [comment]
I see the same problem - 
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

Please find the code base here - https://gist.github.com/npillarikuppam/104fe8f3fdee3535a24f

**Comment by AllenFang** [comment]
thanks, I'll spend some time on this problems.

**Comment by laitang2000** [comment]
Thanks, this library is pretty awesome :)

**Comment by ZtF** [comment]
+1

**Comment by AllenFang** [comment]
Fix it on v1.2.9
