### ISSUE TITLE
Issue while selecting all rows with local pagination

### ISSUE THREAD

**Issue by shalinibajpai0310** [AllenFang/react-bootstrap-table#1310]
Hi Allen,

Select all rows is not working in case of local pagination. PFB  below steps along with snapshots  to generate the issue:
Step 1). Select all row of page 1.
![step1](https://cloud.githubusercontent.com/assets/20796527/25948971/7e508b5e-3673-11e7-83b1-2fb45aeaeeaf.PNG)
Step2). Move to page 2 , you will see the select all icon is already selected . 
![step2](https://cloud.githubusercontent.com/assets/20796527/25949028/b6365e04-3673-11e7-902f-03645381f4fb.PNG)
Step 3).  In order to select all rows of page no.2 we have to double click on the checkbox.
![step3](https://cloud.githubusercontent.com/assets/20796527/25949036/c1d804ba-3673-11e7-8074-19ee46b707f7.PNG)
Step 4). Now come back to page no. 1 , all your initially selected rows will  be shown as non selected
![step4](https://cloud.githubusercontent.com/assets/20796527/25949077/f57df6d0-3673-11e7-833f-f005c18981ea.PNG)
 
Issue can be generated on below link : 
http://allenfang.github.io/react-bootstrap-table/example.html#selection( go to External Selection Management)
Requirement:
select all rows should be functional for each page number as well as we should be able to persist our selected rows of all the pages in case of local pagination

Kindly assist on the same

**Comment by AllenFang** [comment]
@shalinibajpai0310, thanks, I think it's a bug about that example, I'll fix it soon, thanks

**Comment by AllenFang** [comment]
@shalinibajpai0310, fixed on the website and also update the example code, thanks

**Comment by shalinibajpai0310** [comment]
@allenfang , thanks for your quick response on my request

**Comment by reyicare** [comment]
@AllenFang What is the solution for this problem? I tested with your exemple here : http://allenfang.github.io/react-bootstrap-table/example.html#selection at the end of the page but no success. When I check "All" I've this error : Uncaught Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development.

Can you help me? I need to checked all checkbox from the first page or another and select all with the pagination. Thanks
