### ISSUE TITLE
rendering of table with some columns having hidden=true, and width of select row column

### ISSUE THREAD

**Issue by jcabrerazuniga** [AllenFang/react-bootstrap-table#1311]
I made the columns of my react table to appear or dissapear thanks to a state called

                   colsHiddenStatus

that has a map like:

         [['id', true], ['firstName', false], ['lastName', false], ['phone', false], ['password', true], ['age', true]]

if true is given to an element of this map then that column will not be shown by making the respective  hidden field equal to true. For example, for the password column, I have:

      this.state.colsHiddenStatus.get('password')  = true

and the next column will be hidden:

          <TableHeaderColumn key={"070"} dataField={'password'}  hidden={this.state.colsHiddenStatus.get('password')}   columnClassName={'password'}    width={this.state.colsWidth.get('password')} dataSort headerAlign='left'  editable={JSON.parse('{"type": "textarea" }')}>{'Password'}</TableHeaderColumn>

However,  everytime columns like this with the hidden property = true are "called" for rendering. the table's headers appear misaligned respect to the data as with:

![image](https://cloud.githubusercontent.com/assets/27739794/25974876/75fd9d1c-3668-11e7-942d-f927340c3337.png)

On the other hand, if several rows get hidden one after another, the column that corresponds to the select row column gets too wide like at:
![image](https://cloud.githubusercontent.com/assets/27739794/25974945/cf11a178-3668-11e7-9eb3-08f2494c60e9.png)

**Comment by AllenFang** [comment]
can you try configure selection column? check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/selection-column-width-table.js#L24

if the problem still remain, please let me know, thank you

**Comment by jcabrerazuniga** [comment]
I created the next code:

-------------------------------------------------------------------------------------------------------
import React from 'react';
import ReactDOM from 'react-dom';
/*import App from './App';*/
import './index.css';
import '../node_modules/react-bootstrap-table/dist/react-bootstrap-table-all.min.css';
import '../node_modules/react-bootstrap-table/css/react-bootstrap-table.css';
import '../node_modules/react-bootstrap-table/css/toastr.css';
/*import '../../../node_modules/react-select/dist/react-select.css';*/


/* eslint max-len: 0 */

import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';
const uuidV4 = require('uuid/v4');
var generatePassword = require('password-generator');

const products = [];

function addProducts(quantity) {
  const startId = products.length;
  for (let i = 0; i < quantity; i++) {
    const rowTableNum = startId + i;
    products.push({
      rowNumber: rowTableNum,
      id: uuidV4(),
      firstName: 'Item first name ' + startId,
      lastName: startId + 'ItemLastName',
      price: 2100 + i,
      password: generatePassword(),
      email: i + '@' + 'test.com'
    });
  }
}

addProducts(20);

const selectRowProp = {
  mode: 'checkbox',
  columnWidth: '60px'
};

class SelectionColumnWidthTable extends React.Component {
  render() {
    return (
      <BootstrapTable data={ products } selectRow={ selectRowProp }>
          <TableHeaderColumn dataField='rowNumber' hidden= {true} isKey={ true }>RowNumber ID</TableHeaderColumn>
          <TableHeaderColumn dataField='id'        hidden = {false}>Id</TableHeaderColumn>
          <TableHeaderColumn dataField='firstName' hidden={false}>First Name</TableHeaderColumn>
          <TableHeaderColumn dataField='lastName'  hidden={false}>Last Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'     hidden={false}>Price</TableHeaderColumn>
          <TableHeaderColumn dataField='password'  hidden={true}>Password</TableHeaderColumn>
          <TableHeaderColumn dataField='email'     hidden={false}>Email</TableHeaderColumn>
          
      </BootstrapTable>
    );
  }
}





ReactDOM.render(
  <SelectionColumnWidthTable />,
  document.getElementById('root')
);

-------------------------------------------------------------------------------------------------------

Well, for some reason the React BootStrapTable styles are not being applied (I am importing them at the top). I am using: https://facebook.github.io/react/docs/installation.html#creating-a-new-application instructions to create a new react project. I added two react components: uuid (https://www.npmjs.com/package/uuid) and password-generator (https://www.npmjs.com/package/password-generator) to my project. This example should create the problem I mentioned.

**Comment by AllenFang** [comment]
> I am using the play-scala server and node_modules for react stuff.

I've no idea about this

> Is the react bootstrap table using some special fonts?

I dont think so



```js
import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
import '../node_modules/react-bootstrap-table/dist/react-bootstrap-table-all.min.css';
import '../node_modules/react-bootstrap-table/css/react-bootstrap-table.css';
import '../node_modules/react-bootstrap-table/css/toastr.css';
```

can be 

```js
import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
import '../node_modules/react-bootstrap-table/dist/react-bootstrap-table-all.min.css';
```

**Comment by AllenFang** [comment]
BTW, I think the error is dosen;t matter with this issue and I've no idea about if you have solved your problem via configuring `selectRow.columnWidth`. so close it.

**Comment by jcabrerazuniga** [comment]
On my local machine, the code I sent you is working (under Linux) but at my job's one (win) I have the problem with the columns using a similar program to the one I sent you. The interesting thing is that at my job's one if I start showing columns the heads get aligned with their columns. It might also be the version of NPM. Man, hope I will be able to get the problem

**Comment by AllenFang** [comment]
> The interesting thing is that at my job's one if I start showing columns the heads get aligned with their columns

so any problem here? the header get aligned is a good thing, right?

**Comment by jcabrerazuniga** [comment]
but if I start hidding them.... the problem shows again   at my job's code.

**Comment by AllenFang** [comment]
@jcabrerazuniga, I open an issue for this, https://github.com/AllenFang/react-bootstrap-table/issues/1320

But as i know, if the problem is related with unalign or column width, it's may not be easy to fix ;(

**Comment by jcabrerazuniga** [comment]
I found this: the error at my job's code and the next one:
[index.js.zip](https://github.com/AllenFang/react-bootstrap-table/files/999565/index.js.zip)


happened as soon as I the height parameter was added at:

<BootstrapTable data={ products } selectRow={ selectRowProp } search height={'800px'}>

In  fact, as soon as I deleted this parameter at my job's code, the problem stopped.
