### ISSUE TITLE
selectRow className prop. should support function types

### ISSUE THREAD

**Issue by tuucan** [AllenFang/react-bootstrap-table#1313]
bgColor property of selectRow accepts a function type as well as string type. 

If our requirements are much complex, it's more likely we need different classes than different background colors.

In my case, I needed selectRows to have different borders under different conditions. 
So I'd request that className property also accepts a function type.
```
const selectRow = {
    mode: 'radio', 
    className: function(row, isSelect){ ... },
}
```

[bgColor docs for reference](http://allenfang.github.io/react-bootstrap-table/docs.html#bgColor)

**Comment by AllenFang** [comment]
ok, I'll do it

**Comment by AllenFang** [comment]
Hello @tuucan, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/select-row-class-table.js#L47), this enhancement released on `v3.3.5`.

**Comment by tuucan** [comment]
Thank you Allen!

**Comment by tuucan** [comment]
I'm getting,

`ExpandComponent.js:47 Uncaught TypeError: Cannot read property 'className' of undefined`

error even when className is not defined or even when selectRowProp is not defined, at line;

```
var selectRowClass = typeof selectRow.className === 'function' ? selectRow.className(row, isSelected) : isSelected ? selectRow.className : null;
```

**Comment by AllenFang** [comment]
thank~ I'll going to check and fix on next version. sorry

https://github.com/AllenFang/react-bootstrap-table/issues/1327

**Comment by serjoshua** [comment]
@AllenFang hi allen, we're using this in our application and causing critical issues when deployed to our dev and qa environment (local is ok). keep us posted :)

**Comment by AllenFang** [comment]
@serjoshua, the critical issues is same for #1317?

**Comment by serjoshua** [comment]
@AllenFang no, i got the same error as with @tuucan 

TypeError: Cannot read property 'className' of undefined
    at t.value (ExpandComponent.js:47)
    at d._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:799)
    ...
    ...

it's working in my local though but when we deployed to our Dev and QA environment, i get the above error :(

**Comment by AllenFang** [comment]
sure, I reference wrong issue number, anyway, I'll fix it soon

**Comment by AllenFang** [comment]
HI all, Fixed on `v3.3.6`, let me know if the problem still there. thanks

**Comment by serjoshua** [comment]
thanks allen! will try to do it over the weekend. but we'll be able to test it at most monday 😊 will keep you posted.

**Comment by serjoshua** [comment]
hi @AllenFang 

issue is now fixed in QA and Dev :) thank you very much!!!
