### ISSUE TITLE
Update documentation for options.insertModal*

### ISSUE THREAD

**Issue by dennismphil** [AllenFang/react-bootstrap-table#1314]
The example shown [here](http://allenfang.github.io/react-bootstrap-table/example.html#custom) lists in `options`

`insertModalBody`
`insertModalFooter`

However, the docs page for [options](http://allenfang.github.io/react-bootstrap-table/docs.html#options) is missing these. 

It would be nice to see the documentation for these options also.

**Comment by AllenFang** [comment]
I'll improve it, thanks 👍

**Comment by AllenFang** [comment]
Fixed
