### ISSUE TITLE
Changing Color on selected filter

### ISSUE THREAD

**Issue by doshisunny** [AllenFang/react-bootstrap-table#1315]
I want to change the color of selected filter to a different color.  
For example see below. I selected filter for Run to Trial-Run-I . I would like to change color in text insider selected filter to something more visible color.  

![image](https://cloud.githubusercontent.com/assets/12001907/26015270/ffe1e0f2-3725-11e7-8b5b-b4cf50b4304a.png)

Is there any way to pass color for selected?

**Comment by AllenFang** [comment]
I'll support this, thank you :1+

**Comment by doshisunny** [comment]
Thank you !!

**Comment by AllenFang** [comment]
Fixed on `v3.3.5`, now all filter can configure the style, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/filter-style.js#L75)

**Comment by doshisunny** [comment]
Thank you so much.When are you planning to release it?

**Comment by AllenFang** [comment]
it was release on `v3.3.5`.
