### ISSUE TITLE
Conditionally specify columns does not work

### ISSUE THREAD

**Issue by kant2002** [AllenFang/react-bootstrap-table#1317]
I want conditionally specify which columns table will have.
Usually I use ternary operator to hide something in the React by this does not work with React Bootstrap table. See example below.

```
export const BetDistributionTable = (props: BetDistributionTableProperties) => {
    const betType = props.showBetType
        ? <TableHeaderColumn width="200" dataField="betType" dataSort={true} isKey={true}>Тип ставки</TableHeaderColumn>
        : null;
    return <BootstrapTable data={props.data} bordered condensed hover trClassName=""
        options={{ defaultSortName: "date", defaultSortOrder: "desc" }}>
        <TableHeaderColumn width="200" dataField="date" dataSort={true} isKey={true}
            dataFormat={dateFormatter}>Date</TableHeaderColumn>
        {betType}
    </BootstrapTable>;
}

```

**Comment by AllenFang** [comment]
Try to use `keyField` on `BootstrapTable` so that it can avoid you need to handle key column(`isKey`) particularly.

```js

generateColumns() {
    return mycolumn.map((column) => {
        return <TableHeaderColumn>....</TableHeaderColumn>
    });
}

<BootstrapTable data={ myData } keyField='id'>
    { this.generateColumns }
</BootstrapTable>
```
is that helpful for you?

**Comment by AllenFang** [comment]
and I saw your PR also, if you follow the solution above, is that still possible have null value in react childrens?

**Comment by kant2002** [comment]
The problem not in the isKey or such.
I think very often in React use following pattern
```
const header = showHeader ? <h1>Header</h1> : null
return <div>{header}</div>;
```
When I construct `<TableHeaderColumn>` objects like that React Bootstrap table does not like it.

I have table with 10 columns and couple of them could be shown/hidden as needed. I definitely could create workaround which will produce array of `<TableHeaderColumn>` components but think that RBT will benefit from having such simple way to dynamically create columns.

**Comment by AllenFang** [comment]
ok, got it, but one more question, if you used `hidden` on `TableHeaderColumn` is helpful for you?

**Comment by kant2002** [comment]
Let me try. I don't even consider this given how ingrained pattern which I show to you.
