### ISSUE TITLE
How to enable horizontal scroll in ReactBootstraptable after giving the width to the element?

### ISSUE THREAD

**Issue by ajits731** [AllenFang/react-bootstrap-table#1322]
<TableHeaderColumn width='150' dataField={column}>{column}</TableHeaderColumn>

**Comment by AllenFang** [comment]
@ajits731, https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/basic/demo.js#L47-L48

This is not a main feature for `react-bootstrap-table`, usually, you need to configure some columns width to make the table width exceed the outer.

**Comment by pirifan** [comment]
@AllenFang Hey Allen, I am testing the table right now and I can notice that setting the width of the columns works on Chrome and Edge, but doesn't work on Firefox. The horizontal scroll bar is not showing on Firefox. Can you help out with an advice?

Thanks.

**Comment by AllenFang** [comment]
@pirifan, could you please try this page on your firfox? it work well for me. and how you configure the `width`?

**Comment by pirifan** [comment]
` <BootstrapTable data={applications} pagination
                        striped={true}
                        hover={true}
                        search={true}
                        multiColumnSearch={true}
                        searchPlaceholder={"Search by Api Key, Application Name or Developer..."}
                        remote={this.remote}
                        fetchInfo={{ dataTotalSize: this.state.totalSize }}
                        options={options}
                    >
                        <TableHeaderColumn width='300px' dataField='value' isKey={true}>Api Key</TableHeaderColumn>
                        <TableHeaderColumn width='155px' dataField='applicationName'>Application Name</TableHeaderColumn>
                        <TableHeaderColumn width='155px' dataField='developerName'>Developer Name</TableHeaderColumn>
                        <TableHeaderColumn tdStyle={style} width='160px'
                            dataField='state'
                            filterFormatted
                            formatExtraData={applicationState}
                            dataFormat={this.formatApplicationState}
                            filter={{ type: 'SelectFilter', options: applicationState,  selectText: "All Applications"}}
                            searchable={false}
                        > </TableHeaderColumn>
                        <TableHeaderColumn width='100px' tdStyle={style} dataFormat={this.buttonAddRemoveBlacklist.bind(this)}></TableHeaderColumn>
                    </BootstrapTable>`


This is how I add the width, maybe I'm doing something wrong?

**Comment by AllenFang** [comment]
sorry, my bad == > try [this](https://allenfang.github.io/react-bootstrap-table/example.html#basic) page one firefox and check "Large Table" section

and if you change `width='300px'` to `width='300'`?  is it work?

**Comment by pirifan** [comment]
@AllenFang Still not working after changing to width='300' on firefox. However, the example you sent to me works correctly. Hmm, at the moment I have no idea what I am doing wrong, but tnx for the answer anyway!

**Comment by kunaltyagi9** [comment]
I am using React Bootstrap Table and I want to add Horizontal Scrollbar only to the last two columns. Last two columns should be wrapped in a scrollable container. How can we implement this?
