### ISSUE TITLE
How insert row working

### ISSUE THREAD

**Issue by sunnybogawat** [AllenFang/react-bootstrap-table#1326]
I need to create a custom form for inserting a new row along with setting some default value and adding some validation but I am unable to found any sample example or documentation demonstrating the same. If you any documentation to explain this customization please let's know.  I am looking for following things

- setting default value while inserting a new row
- validation for values 
- the custom save function where I will put my logic to save data
- the custom update function when user update any column value

**Comment by AllenFang** [comment]
1. check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/advance/insert-default-value-table.js#L56), use `editable.defaultValue`

2. check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/advance/validator-table.js#L61), use `editable.validator`

3. did you plan to use embed `insertRow` feature?? If not, I think you can control everything by yourself

4. we dont support update, only have cell edit feature.

**Comment by AllenFang** [comment]
BTW, https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js have all examples.

**Comment by sunnybogawat** [comment]
Thanks

**Comment by EktaDevop** [comment]
while inserting if the value is blank toast message is shown...can we customize that toast message?

**Comment by AllenFang** [comment]
@EktaDevop when the insert, the rowkey must have value.  There's some way to customize message https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/advance/insert-error-handle-table.js#L26-L29

However, this is not a good way, in [`react-bootstrap-table2`](https://github.com/react-bootstrap-table/react-bootstrap-table2) will be more easy to custom message even the way to show message.
But `react-bootstrap-table2` still in development

**Comment by EktaDevop** [comment]
thank you !
I am talking about the error message that you are showing if while inserting value is empty "Form validate errors, please checking!" i want to customise this message

**Comment by AllenFang** [comment]
@EktaDevop sorry for lately reply, try to assign a string value to `options.insertFailIndicator`. thanks
