### ISSUE TITLE
ExpandComponent.js:47 Uncaught TypeError: Cannot read property 'className' of undefined

### ISSUE THREAD

**Issue by AllenFang** [AllenFang/react-bootstrap-table#1327]
https://github.com/AllenFang/react-bootstrap-table/issues/1313#issuecomment-302098487

**Comment by wajipk** [comment]
Any luck with this one?

**Comment by jonesm33** [comment]
Also, seeing this same issue.

**Comment by AllenFang** [comment]
HI all, Fixed on `v3.3.6`, thank.

**Comment by adpeiter** [comment]
bootstrapVersion = parseInt($.fn.dropdown.Constructor.VERSION, 10);

parseInt at the line 15 maybe return NaN;

So, simply assing value 3 in 'bootstrapVersion' if it's NaN

**Comment by adpeiter** [comment]
There is a variable 'bs' that is set according to the bootstrap version.
However, the instruction:
`parseInt ($. fn.dropdown.Constructor.VERSION, 10) (at line 15)`
can return NaN and in this case 'bs' will be undefined.
When setting the default values of the module, the error occurs when trying to access bs.className or any other property.
If this happens just assign the value of your bootstrap version after the try block that contains this statement;

`if (bootstrapVersion == NaN)
  bootstrapVersion = myVersion;`
