### ISSUE TITLE
issues with expanding when the page loads

### ISSUE THREAD

**Issue by ashabi** [AllenFang/react-bootstrap-table#1328]
we have an issue with the expanding row.

when the page loads and the user clicks to expand a row it opens and then after a half a second or so it collapses the row you just clicked by itself and the user then has to click again to expand the row. we also noticed that the function isExpanded argument becomes true (just as it is supposed to) and then it becomes false by itself and so it collapses the row.

this only happens on the first initialization of the page. afterwards this strange phenomena does not happen again
any ideas? thanks

**Comment by AllenFang** [comment]
any example code for reproduce it? thank and keep it simple and minimal

**Comment by ashabi** [comment]
its quite difficult to send an example of the code but after inspecting it, the problem seems that I am passing the data for the outer rows and the inner rows through props. what happens is that i need to do some sort of loading in the render to make sure i received all the data information. 

if you take your example and add this code to the beginning of the render the issue will happen as well:
    if(!this.props.mainTable.length || !this.props.innerTable.length){
      return  (
              <div className="full-height">

                <div className="loading-gif">
                    <img src="/img/loading_anim.gif" />
                </div>
              </div>
              )
    }

**Comment by AllenFang** [comment]
@ashabi, I still cant not reproduce your issue, please base on following example and point me how to do it, thanks

https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/expandRow.js

I'll open issue until I can realize and reproduce this issue certainly.

**Comment by ashabi** [comment]
if I take your example and instead of the data being an object but rather from the props then the issue arises. the moment the data={this.props} it renders again the page and so if a user opened a row and it didn't finish bringing the props it will close the row automatically.

**Comment by AllenFang** [comment]
I dont think this is a bug, due to you rerender the table. if you want to keep the expand rows, you can use [`options.onExpand`](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/manage-expanding.js#L80) to save the expanded row and use [`options.https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/manage-expanding.js#L79`] to make that rows expand as default when render every time.
