### ISSUE TITLE
Sorting with custom dataField

### ISSUE THREAD

**Issue by krystofbe** [AllenFang/react-bootstrap-table#1332]
Hey there, 
thanks for this great component. I'm having an issue with sorting and a custom dataField
I'm combining `firstName` and `lastName` to a `fullName` column
```
                        <TableHeaderColumn
                            dataAlign="left"
                            headerAlign="left"
                            dataFormat={this.fullName}
                            dataSort={true}
                            sortFunc={this.sortFullName}> Name
                        </TableHeaderColumn>

    fullName(cell: any, row: any) {
        return `${row.firstName} ${row.lastName}`;
    }

    sortFullName(a: string, b: string, order: string) {
        if (order === 'desc') {
            return a.localeCompare(b)
        } else {
            return b.localeCompare(a);
        }
    }
```
However, clicking on the HeaderColumn gives me this error:
`      The type of sort field and order should be both with String or Array
`
That's because `sortField` is `undefined`

What can I do?

**Comment by AllenFang** [comment]
Hello, very sorry for late reply, I think this issue is `dataField` is necessary for `TableHeaderColumn`, so when trigger the sorting, `react-bootstrap-table` will get the value to sort or pass the value to your customization function.

**Comment by reactionic127** [comment]
@krystofbe 
I have same problem.
did you fixed the problem?

**Comment by krystofbe** [comment]
@reactionic127 Yup, just add `dataField`

Then something like this will work:

```
<TableHeaderColumn
              dataAlign="left"
              headerAlign="left"
              dataFormat={this.fullName}
              dataSort={true}
              sortFunc={this.sortFullName}
              dataField=""
            >{" "}Name
</TableHeaderColumn>

(... )

  fullName(cell: any, row: any) {
    return `${row.firstName} ${row.lastName}`;
  }

  sortFullName(a: any, b: any, order: string) {
    a = `${a.firstName} ${a.lastName}`;
    b = `${b.firstName} ${b.lastName}`;
    if (order === "desc") {
      return a.localeCompare(b);
    } else {
      return b.localeCompare(a);
    }
  }

```

**Comment by AdnanBoota** [comment]
Hey, any idea for just single nested field using dataFormat and formatExtraData?

The dataSort is not working?
![image](https://user-images.githubusercontent.com/14972616/54444952-18be8c80-4744-11e9-800f-6f46c14fd65d.png)
