### ISSUE TITLE
[ASK] Can i use it for nested Object

### ISSUE THREAD

**Issue by Ahershel** [AllenFang/react-bootstrap-table#1336]
Hi, sorry I'm newbie in react etc.. so please bear with me. *Pardon my english also
I want to ask wether i can use this component with my nested Object. Because I know this component use .slice, therefor when i try puting my nested object in the data property, it generates an error.

Is there some setting that i must change to do it or should I change my nested object to plain object?

Example of my nested object :
{
  'items': {
              'ID0001': {
                             'general': {
                                             'Iid': 'ID0001',
                                             'name' : 'Pencil'
                                            },
                            'price': {
                                         'retail': 1000,
                                         'distributor': 800
                                        }
                            },
             'ID0002': {
                             'general': {
                                             'Iid': 'ID0002',
                                             'name' : 'Book'
                                            },
                             'price': {
                                         'retail': 3500,
                                         'distributor': 2900
                                        }
                            }
            }
}

**Comment by AllenFang** [comment]
HI @Ahershel, we dont support nested object, `react-bootstrap-table` only accept an array without any nest  ed data field. If you really want to use this component, it's necessary to flatten your object firstly.
