### ISSUE TITLE
Bootstrap 4 Sorting Arrows not showing up

### ISSUE THREAD

**Issue by abrarazeem** [AllenFang/react-bootstrap-table#1339]
With bootstrap V4 Sorting arrows are missing, its mainly due to "caret" class has been removed from Bootstrap V4. Any plans to Upgrade this to Bootstrap V4.

**Comment by AllenFang** [comment]
currently I have no any plan to got for v4, but I will spend some time to handle this issue by some specified way.

**Comment by jtheberge** [comment]
This is because Glyphicons is being removed in v4 in exchange for Font Awesome.

**Comment by AllenFang** [comment]
Upgrade to `v4.0.0` and add `version='4'` on `BootstrapTable`

**Comment by Suban5** [comment]
I have upgraded to version 4.1.1 and added version='4' on BootstrapTable. But it is not working. It doesn't show any dropdown arrow.

<BootstrapTable ref='table' data={this.state.candidateScoreList} version='4' options={options}
                                condensed hover pagination={true} search={true}>....

**Comment by AllenFang** [comment]
umm..  it's wired,  what's version for bootrstrap and what browseer you used? thanks

**Comment by Suban5** [comment]
react-bootstrap-table": "^4.1.1"
"reactstrap": "^4.8.0"

and i am using chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by AllenFang** [comment]
I think it's irrelevant about broweser, could you please try to remove `reactstrap ` from your dependency and try it again? thanks

**Comment by chucktesejme** [comment]
Same problem here... removing reactstrap didn't help for me. 

    "bootstrap": "^4.0.0-beta.2",
    "react-bootstrap-table": "^4.1.5",
    "reactstrap": "^4.8.0",

    "react": "^16.1.1",
    "react-dom": "^16.1.1",
    "react-quill": "^1.2.0",
    "react-redux": "^5.0.6",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-spinkit": "^3.0.0",
    "react-transition-group": "^2.2.1",
    "react-widgets": "^4.1.1",
    "react-widgets-moment": "^4.0.4",
    "redux": "^3.7.2",
    "redux-form": "^7.1.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0"


```
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';

<BootstrapTable data={events} selectRow={ selectRow } striped hover pagination version='4'>
.....
</BootstrapTable>
```

**Comment by AllenFang** [comment]
@chucktesejme do you add bootstrap css to your HTML? and what's the version of bootstrap?

**Comment by chucktesejme** [comment]
bootstrap: ^4.0.0-beta.2
Yes, bootsrap css is present in HTML... other bootstrap stuff works fine ( grid, buttons etc.)

**Comment by AllenFang** [comment]
@chucktesejme it's a bug again, seems like something change when going to beta, because previous implement is base on alpha, I'll fix it ASAP.  Thank you very much

**Comment by AllenFang** [comment]
that's forward to https://github.com/AllenFang/react-bootstrap-table/issues/1783

**Comment by AllenFang** [comment]
@chucktesejme please check v4.3.1, thanks

**Comment by Suban5** [comment]
"antd": "^3.1.0",
    "bootstrap": "4.0.0-beta.2",
    "html-entities": "^1.2.1",
    "html-react-parser": "^0.4.1",
    "install": "^0.10.2",
    "jwt-decode": "^2.2.0",
    "material-ui": "^0.20.0",
    "material-ui-pagination": "^1.1.6",
    "moment": "latest",
    "react": "^16.2.0",
    "react-bootstrap-table": "^4.3.1",
    "react-dom": "^16.2.0",
    "react-iframe": "^1.1.0",
    "react-intl": "^2.4.0",
    "react-loader-advanced": "^1.7.1",
    "react-router-dom": "^4.2.2",
    "react-rte": "^0.15.0",
    "react-scripts": "1.0.17",
    "react-truncate": "^2.3.0",
    "reactstrap": "^5.0.0-alpha.4",
    "url-search-params": "^0.10.0"

caret is not showing, please help

**Comment by AllenFang** [comment]
@Suban5  I still cant reproduce this issue, any simple and minimal repo for reproducing this problem? thanks

**Comment by shanebrunette** [comment]
+1 I am also having this problem

**Comment by chamath95** [comment]
If You use boostrap 4 add below css query. Its working for me

.caret {
    display: inline-block;
    width: 0;
    height: 0;
    margin-left: 2px;
    vertical-align: middle;
    border-top: 4px dashed;
    border-top: 4px solid \9;
    border-right: 4px solid transparent;
    border-left: 4px solid transparent;
}

.dropup, .dropdown {
    position: relative;
}

.dropup .caret, .navbar-fixed-bottom .dropdown .caret {
    border-top: 0;
    border-bottom: 4px dashed;
    border-bottom: 4px solid \9;
    content: "";
}

**Comment by jakeleventhal** [comment]
@chamath95 if i add this css, then there is a second arrow added to the pagination icon at the bottom
<img width="141" alt="screen shot 2018-10-13 at 12 23 54 pm" src="https://user-images.githubusercontent.com/15133828/46909172-df5aca00-cee2-11e8-9a02-ff919ea9c8d6.png">

**Comment by andlon10** [comment]
> @chamath95 if i add this css, then there is a second arrow added to the pagination icon at the bottom
> <img alt="screen shot 2018-10-13 at 12 23 54 pm" width="141" src="https://user-images.githubusercontent.com/15133828/46909172-df5aca00-cee2-11e8-9a02-ff919ea9c8d6.png">

You can avoid this by prefixing that CSS styling with any parent element in the table, for example the "th"

**Comment by sonalyadav8924** [comment]
> > @chamath95 if i add this css, then there is a second arrow added to the pagination icon at the bottom
> > <img alt="screen shot 2018-10-13 at 12 23 54 pm" width="141" src="https://user-images.githubusercontent.com/15133828/46909172-df5aca00-cee2-11e8-9a02-ff919ea9c8d6.png">
> 
> You can avoid this by prefixing that CSS styling with any parent element in the table, for example the "th"

You use this to hide dropdown
.dropdown-toggle::after{
      border:none;
    }
