### ISSUE TITLE
Initial state with sort on column

### ISSUE THREAD

**Issue by danzawadzki** [AllenFang/react-bootstrap-table#1340]
Hello,
is there some option to set up defaut sort on column? I have columns with IDs in my table, at this moment to sort, user need to click on column heading. Can i somehow make initial state with sort active on IDs column?

Cheers!

**Comment by jabberwo** [comment]
Trivial, look in the docs: http://allenfang.github.io/react-bootstrap-table/docs.html#defaultSortName

**Comment by AllenFang** [comment]
@jabberwo, thanks, it's certainly answer :)
