### ISSUE TITLE
Edit Next Cell On Complete Edit

### ISSUE THREAD

**Issue by IHeartReact** [AllenFang/react-bootstrap-table#1343]
Select the next cell after clicking ('enter').

"EditNextCellOnCompleteEdit"

**Comment by AllenFang** [comment]
The **Select Next** you means for what??  For trigger cell editing?? or?

**Comment by IHeartReact** [comment]
In order to accomplish this I did 2 things.

**1.)**

I added offset to "__handleCellKeyDown__REACT_HOT_LOADER__"

`	      } else if (e.keyCode === 13) {
                offset = { x: 1, y: 0 };
	        var enterToEdit = (typeof keyBoardNav === 'undefined' ? 'undefined' : _typeof(keyBoardNav)) === 'object' ? keyBoardNav.enterToEdit : false;
	        if (cellEdit && enterToEdit) {
	          this.handleEditCell(e.target.parentElement.rowIndex + 1, e.currentTarget.cellIndex, '', e);
	        }
	      }`

**2.)**

I changed "__handleKeyPress__REACT_HOT_LOADER__" so that "tab" is always called.

`	      if (e.keyCode === 13 || e.keyCode === 9) {
	        // Pressed ENTER
                            var value = e.currentTarget.type === 'checkbox' ? this._getCheckBoxValue(e) : e.currentTarget.value;

                            if (!this.validator(value)) {
                                return;
                            }
	        
	          this.props.onTab(this.props.rowIndex + 1, this.props.colIndex + 1, 'tab', e);
                                e.preventDefault();
	      }`

**Comment by IHeartReact** [comment]
The purpose was to trigger cell editing, not just selection (after complete edit)

**Comment by AllenFang** [comment]
I'll support it in future but I think it's much minor, so may not support it soon
