### ISSUE TITLE
(Request) Conditional Formatting.

### ISSUE THREAD

**Issue by IHeartReact** [AllenFang/react-bootstrap-table#1344]
Need CellClassName return function.

**Comment by AllenFang** [comment]
What means for "Conditional Formatting"?? you means cell format?

**Comment by IHeartReact** [comment]
What I need is CellClassName (TdClassName) function.

It would solve this issue.

**Comment by AllenFang** [comment]
@IHeartReact, I think `dataFormat` can help you, check https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/column-format
