### ISSUE TITLE
column width

### ISSUE THREAD

**Issue by MichielDx** [AllenFang/react-bootstrap-table#1346]
I've seen many posts about this and tried a lot of examples but I keep getting this issue.

I've tried giving all columns a width, but this didn't help.

![image](https://cloud.githubusercontent.com/assets/18028456/26396301/1e7a85ae-4073-11e7-81b3-d6a05fa7114d.png)

![image](https://cloud.githubusercontent.com/assets/18028456/26396337/36ed4266-4073-11e7-9065-fef445ec0e4b.png)

**Comment by MichielDx** [comment]
fixed it by giving each column a width (with px like '150px') and giving the table containerStyle={{width:'100%'}}

**Comment by pedro-eira** [comment]
I used this table but all of the table contents is fit for the browser width.

![screen shot 2017-10-08 at 9 57 54 pm](https://user-images.githubusercontent.com/30698444/31323309-0e62a35a-ac74-11e7-8acc-70c3cc4fbf9a.png)

But I want like this. I don't mind the overflow. I want the overflow and scroll.
Exactly like this!

![screen shot 2017-10-08 at 9 58 40 pm](https://user-images.githubusercontent.com/30698444/31323332-582ebc3a-ac74-11e7-8b25-4ac4b4372812.png)

**Comment by prajapati-parth** [comment]
@pedro-eira Do you provide column width?

**Comment by pedro-eira** [comment]
Every column widths shouldn't be static. They should have adjustable width to their content. But there are lots of columns and it seems that each column has the same width (= viewport / columns count)

**Comment by AllenFang** [comment]
Currently, if you dont settiing the width, the with default is depends on the content length of header

**Comment by ziaulrehman40** [comment]
I strongly support @pedro-eira on this. And i am having exact same problem.

I would love the table to get responsive. I think that would not be hard to achieve with some css. I will post if I solve it someway. For the people until library is updated.

@AllenFang Please also consider this in next iteration, and re-open the issue. This is kind of enhancement not bug.

**Comment by ngobrendan** [comment]
I am having the same problem with the static column width. Has anyone solved it to make column width adjustable with the content?

**Comment by BugKiller-tech** [comment]
I also have same problem. :(

**Comment by cention-thinesh** [comment]
there is a solution here:
https://github.com/AllenFang/react-bootstrap-table/issues/379#issuecomment-365386318

**Comment by hseniht** [comment]
> there is a solution here: [#379 (comment)](https://github.com/AllenFang/react-bootstrap-table/issues/379#issuecomment-365386318)

thanks man!
