### ISSUE TITLE
Expandable row table doesn't work with striped

### ISSUE THREAD

**Issue by FRodrigues21** [AllenFang/react-bootstrap-table#1347]
**Issue**
Seems like the striped property of the react bootstrap table doesn't work on tables with expandable row option enabled.

**Example**
Even the examples of the expandable row tables that have the striped property with value true aren't actually striped tables.

**Comment by AllenFang** [comment]
it's a known issue, check [this](https://github.com/AllenFang/react-bootstrap-table/issues/1034). Currently, i still can not find a good solution, but there's a workaround, let me know if you have any questions.  Thanks
