### ISSUE TITLE
Validator with blurToSave dismisses error too quickly

### ISSUE THREAD

**Issue by bobics** [AllenFang/react-bootstrap-table#1349]
![2017-05-24 16_09_48](https://cloud.githubusercontent.com/assets/33119/26429660/00327c8a-409d-11e7-9793-a86b3f5e5e8f.gif)

**To reproduce:**
1. Enable `blurToSave: true`.
2. Click into a cell with a validation error.
3. Click into a different cell.

**Result:**
The error messages dismisses way too quickly sometimes when you click into another cell.

**Expected Result:**
The table should probably prevent you from clicking into the other cell.

_On react-bootstrap-table 3.3.5_

**Comment by AllenFang** [comment]
@bobics, I think it's a minor issue, due to you click another cell must trigger `blur` event and it will cause  the previous cell complete editing cell. Let me know you concern or consideration, thanks

**Comment by bobics** [comment]
I think validation should take precedence by default over triggering `blur`. Or at least the error message shouldn't disappear right away. As it is, the user may not even notice they entered invalid input because the error message disappear so quickly.
