### ISSUE TITLE
duplicated!

### ISSUE THREAD

**Issue by hellokitty111** [AllenFang/react-bootstrap-table#135]
please help, duplicated 
![document](https://cloud.githubusercontent.com/assets/7309084/11115102/309e2d5c-8964-11e5-8fae-d72c7a6942cf.png)

**Comment by AllenFang** [comment]
did you import <code>react-bootstrap-table-all.min.css</code>?

**Comment by AllenFang** [comment]
#136 #75

**Comment by hellokitty111** [comment]
Thanks a lot!
:heart:
