### ISSUE TITLE
how to display loading effects

### ISSUE THREAD

**Issue by GrandKai** [AllenFang/react-bootstrap-table#1350]
Table data is loading, how to display loading effects

**Comment by GrandKai** [comment]
第二个问题：checkbox那列支持自定义宽度不
第三个问题：鼠标旋停在cell上显示cell内容，类似title的效果

**Comment by GrandKai** [comment]
第二个问题：鼠标旋停在cell上显示cell内容，类似title的效果

**Comment by GrandKai** [comment]
第三个问题：怎么执行表格宽度

**Comment by AllenFang** [comment]
@GrandKai, currently, we dont support the loading effect, but have an option to custom default text when theres no any data in table, see [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/basic/no-data-table.js)

For second question, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column/column-title-table.js)

For third question, please check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column/column-width-table.js)

Let me know if you have any other questions, thanks
