### ISSUE TITLE
Edit in popup window

### ISSUE THREAD

**Issue by GDileepG** [AllenFang/react-bootstrap-table#1352]
We can edit the values inline in react-bootstrap-table. But it will not work in all time. Sometimes we list few columns in the grid and we need to edit the other fields also. We have checked for an option to edit the fields through the popup window, like adding a new row, by placing an Edit button in the row.. But we are not able to find the same.

Can you help us to configure the same?

Regards,
Dileep

**Comment by AllenFang** [comment]
@GDileepG, sorry for lately reply, editing in pop or modal is not possible by configuration in `react-bootstrap-table`, I doesn't support it, but you can custom it by yourself, Following example show you how to custom cell editor and I also point you how you custom a pop for editor, below is a real case:

https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/cell-edit/custom-cell-edit-table.js#L189
