### ISSUE TITLE
Selecting a row with a click

### ISSUE THREAD

**Issue by jcabrerazuniga** [AllenFang/react-bootstrap-table#1354]
Is there a way to select a row with a click on it?
Thx

**Comment by GrandKai** [comment]
<BootstrapTable  selectRow={ {
mode: 'checkbox',
      clickToSelect: true,
      selected: [], // default select on table
      bgColor: 'rgb(238, 193, 213)',
      columnWidth: "30px", // 指定 checkbox 宽度
} }

**Comment by GrandKai** [comment]
<BootstrapTable  selectRow={ { mode: 'checkbox',
      clickToSelect: true,
      selected: [], // default select on table
      bgColor: 'rgb(238, 193, 213)',
      columnWidth: "30px", // 指定 checkbox 宽度
} }

**Comment by GrandKai** [comment]
<BootstrapTable  selectRow={ { mode: 'checkbox',
      clickToSelect: true,
      selected: [], // default select on table
      bgColor: 'rgb(238, 193, 213)',
      columnWidth: "30px", // 指定 checkbox 宽度 } }

**Comment by jcabrerazuniga** [comment]
but this one selects only if you check the checkbox. I was thinking on to make the row select just with a click on it and unselect with another click if it was previously select.

**Comment by AllenFang** [comment]
@jcabrerazuniga, like @GrandKai's mention, configure `selectRow.clickToSelect` with true will help you.
