### ISSUE TITLE
Page change cannot finish, when call back calls setState in other component

### ISSUE THREAD

**Issue by zhahaoyu** [AllenFang/react-bootstrap-table#1357]
My situation is that I have some large amount of data, so I want to load them as I change pages, and if there is a promise pending I don't send another request until it is done. I try to implement a data container that is in charge of the data logic and pass down its data and fetchMoreData method as props to React-bootstrap-table. The issue is when we call fetchMoreData at page change, setState gets called in the data component, then react-bootstrap-table will hang, the button will grey out but no page change in UI.

<img width="1181" alt="screen shot 2017-05-26 at 11 17 50 am" src="https://cloud.githubusercontent.com/assets/13268361/26507406/1895815a-4205-11e7-95cb-0447d0f235f6.png">

My code for fetchMoreData in the container is 

    fetchMoreData(fetchSize: number) {

        if (!this.state.hasFetchedAll && !this.state.isLoading) {
            const newData = getMoreData();

            this.setState(
                {isLoading: true}
            );

            newData.then(this.onResolve)
                .catch(this.onError);

        }
    }

and the way to trigger this callback that is in a child component that wraps react-bootstrap-table, i have
`onPageChange: (page: number, sizePerPage: number) =>  {
                this.props.fetchMore(CACHE_SIZE);
        }`

and then I am expecting react-bootstarp-table to take _this.props.data_ in child component to reflect the data change.

 

    <BootstrapTable data={this.props.data} options={this.dataTableOptions}>
            <TableHeaderColumn dataField='messageIdentifier'>
                Message ID
            </TableHeaderColumn>
            <TableHeaderColumn dataField='creationTime'>
                Creation Time
            </TableHeaderColumn>
            <TableHeaderColumn dataField='messageContent'>
                Content
            </TableHeaderColumn>
     </BootstrapTable>
The issue is the table change does get reflected, more page options pop up, but the page change cannot finish. It works fine if I remove the "setState" statement in parent component.

**Comment by AllenFang** [comment]
HI, you should use `remote` mode for your case, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-paging.js) and also [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-paging.js)

In the remote mode, you are suppose to be handled all the data operation, ex: paging, sort, filtering, search, insert, delete etc. But if you want only some functionality go for `remote` mode, we support the alternative remote for you, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-alternative.js#L9).

Let me know if you have any concern. thanks

**Comment by zhahaoyu** [comment]
Hi I tried remote, but it shows all results on the first page without the paginator, and it shows "Showing rows 0 to 0 of 0", is there anything else I need to do besides setting the remote mode to be true and implement the OnPageChange function? 

<img width="1184" alt="screen shot 2017-05-28 at 3 51 17 am" src="https://cloud.githubusercontent.com/assets/13268361/26528148/f54f5fea-4358-11e7-933a-5d241ab12394.png">

**Comment by AllenFang** [comment]
@zhahaoyu, could you show me a example but please keep it simple and minimal(Without any dependencies or library, just a example can work on local)

**Comment by zhahaoyu** [comment]
Hi @AllenFang, please find below an example. If I call setState in fetch(), the paginator hangs, and if I set remote, the paginator disappears completely.

```javascript
      import React from 'react';
      import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';

      export class Table extends React.Component {
        constructor(props) {
          super(props);
          this.state = {
            data: [
              [0, 0, 0],
              [0, 0, 0],
              [1, 1, 1],
              [1, 1, 1]
            ],
            isLoading: false
          }
          this.onResolve = this.onResolve.bind(this);
          this.fetch =　this.fetch.bind(this);
        }

        fetch() {
          if (!this.state.isLoading) {
            //IF I CALL setState HERE, PAGE DOES NOT SWITCH
            this.setState({
              isLoading: true
            })
            new Promise((resolve, reject) => {
              setTimeout(function() {
                resolve([
                  [1,2,3],
                  [1,2,3],
                  [1,2,3]
                ]);
              }, 250);
            }).then(this.onResolve);
          }
        }

        onResolve(newData) {
          this.setState({
            data: [...this.state.data, ...newData],
            isLoading: false
          })
        }

        render() {
          return <DefaultPaginationTable data = {this.state.data} fetchMore = { this.fetch}/>
        }
      }

      class DefaultPaginationTable extends React.Component {
       dataOptions = {
          sizePerPage: 2,
          hideSizePerPage: true,
          paginationShowsTotal: true,
          onPageChange: (page, sizePerPage) => {
            this.props.fetchMore();
          }
        }

        render() {
          return (
            <div>
              <BootstrapTable
                data={ this.props.data }
                options={ this.dataOptions }
                condensed
                pagination
                >
                <TableHeaderColumn dataField='id' isKey dataFormat={(cell, row) => row[0]}>Product ID</TableHeaderColumn>
                <TableHeaderColumn dataField='name' dataFormat={(cell, row) => row[1]}>Product Name</TableHeaderColumn>
              </BootstrapTable>
            </div>
          );
        }
      }

```

**Comment by zhahaoyu** [comment]
What's interesting is that if I change the "isLoading" property to class variable instead of "react state", this works fine..

**Comment by zhahaoyu** [comment]
@AllenFang any updates?

**Comment by AllenFang** [comment]
hello, I think following is good, but actually I'm not very sure what's the problem now, maybe you can describe again step by step. Anyway, the following code work well when I navigate to next page, but actually, I still not sure if it is a correct behavior when I running your example.

```js
/* eslint max-len: 0 */
import React from 'react';
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';

export default class Table extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      data: [
        [ 0, 0 ],
        [ 0, 0 ],
        [ 1, 1 ],
        [ 1, 1 ]
      ],
      isLoading: false
    };
    this.onResolve = this.onResolve.bind(this);
    this.fetch = this.fetch.bind(this);
  }

  fetch() {
    if (!this.state.isLoading) {
      new Promise((resolve) => {
        setTimeout(function() {
          resolve([
            [ 1, 2 ],
            [ 1, 2 ],
            [ 1, 2 ]
          ]);
        }, 250);
      }).then(this.onResolve);
    }
  }

  onResolve(newData) {
    this.setState({
      data: [ ...this.state.data, ...newData ],
      isLoading: false
    });
  }

  render() {
    return <DefaultPaginationTable data={ this.state.data } fetchMore = { this.fetch }/>;
  }
}

class DefaultPaginationTable extends React.Component {
  render() {
    const dataOptions = {
      sizePerPage: 2,
      hideSizePerPage: true,
      paginationShowsTotal: true,
      onPageChange: () => {
        this.props.fetchMore();
      }
    };
    return (
      <div>
        <BootstrapTable
          data={ this.props.data }
          options={ dataOptions }
          condensed
          pagination>
          <TableHeaderColumn dataField='id' isKey dataFormat={ (cell, row) => row[0] }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name' dataFormat={ (cell, row) => row[1] }>Product Name</TableHeaderColumn>
        </BootstrapTable>
      </div>
    );
  }
}

```

**Comment by zhahaoyu** [comment]
Yes. This would work. The issue is I have to rely on the isLoading field to make sure multiple requests are not sent at the same time. It works if instead of this.state.isLoading, I use this.isLoading.

**Comment by AllenFang** [comment]
yes, you should use `this.state.isLoading` to avoid fetch again.
