### ISSUE TITLE
Two table headers are rendering.

### ISSUE THREAD

**Issue by amerdiglisic** [AllenFang/react-bootstrap-table#136]
My code renders two table headers with column names, on the first one sorting is working and on the second one it is not. So the issue is two table headers.

**Comment by AllenFang** [comment]
did you import <code>react-bootstrap-table-all.min.css</code>?

**Comment by amerdiglisic** [comment]
Later I saw this question and answer below :+1: 

Thanks a lot. 

Cheers !

**Comment by AllenFang** [comment]
Great! enjoy this component :)
