### ISSUE TITLE
Version 4.0.0: Validators don't work for inline edit

### ISSUE THREAD

**Issue by freeboarder42** [AllenFang/react-bootstrap-table#1360]
With the current version 4.0.0  validators work for the insert dialog, but not correctly for inline editing. Using a demo that works with version 3, validation errors don't show up when inline editing with version 4. When leaving the edit field using the TAB key, nothing happens, the validator function is not even invoked. When pressing ENTER, the validator function is invoked, but the validation message is not displayed.

**Comment by AllenFang** [comment]
@freeboarder42, I cant reproduce this issue via this [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/advance/validator-table.js) and also what beta version you used now??

Please give an example which can reproduce your issue, I will open again if I can confirm this is an issue certainly. Thanks

**Comment by freeboarder42** [comment]
Sorrym was my fault, I had beforeShowError assigned in my demo and returned false. Was a bit mislead that error alerts are shown anyway when inserting a row.
