### ISSUE TITLE
Extract CSV data without downloading?

### ISSUE THREAD

**Issue by reetou** [AllenFang/react-bootstrap-table#1361]
I want to extract CSV table in a variable without downloading it and then convert it to .xls, but I haven't found such method in API. How could I do that? Thanks in advance.

**Comment by AllenFang** [comment]
@reetou, we doesn't support this feature, sorry. and I think it's minor feature for `react-bootstrap-table` currently, so PR is welcome. thanks

BTW, actually, this feature can be done absolutely by your application, for `react-bootstrap-table`, we just give user a convince way to down table as CSV file.
