### ISSUE TITLE
If empty array is being passed as data, it is showing error with '_adjustHeaderWidth'

### ISSUE THREAD

**Issue by saikatcts** [AllenFang/react-bootstrap-table#1362]

**Comment by AllenFang** [comment]
Hello @saikatcts, what kind of error and I can't not reproduce it, I use this [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/basic/no-data-table.js)

**Comment by AllenFang** [comment]
Fixed on `v3.3.9`
