### ISSUE TITLE
Document links need to be modified

### ISSUE THREAD

**Issue by UncleYee** [AllenFang/react-bootstrap-table#1364]
Document links need to be modified into https://allenfang.github.io/react-bootstrap-table/

**Comment by AllenFang** [comment]
sorry, where's the link should be change? thanks

**Comment by UncleYee** [comment]
![image](https://cloud.githubusercontent.com/assets/24444901/26659981/8e66db94-46a7-11e7-969d-b2012e142679.png)
here!

**Comment by AllenFang** [comment]
Fixed it, thanks :)
