### ISSUE TITLE
Customize page button - Prop Type Error

### ISSUE THREAD

**Issue by MethodenMann** [AllenFang/react-bootstrap-table#1365]
We'd like to use font-awesome icons for pagination compoment.
It works like this:

```
 const options = {
     nextPage: <i className="fa fa-chevron-right"></i>
  };
```

Unfortunately we get a prop type warning:

> Warning: Failed prop type: Invalid prop `options.nextPage` of type `object` supplied to `BootstrapTable`, expected `string`.

Could you please make the proptypes less strict and allow jsx?

**Comment by AllenFang** [comment]
ok, it will be done in next version.

**Comment by MethodenMann** [comment]
cool. thank you very much!

**Comment by AllenFang** [comment]
Fixed on newest version, thanks

**Comment by achepey** [comment]
When trying to implement this on my own project, using the above syntax to inject an icon rather than a string, it seems to completely break the functionality.

@MethodenMann , were you able to get this working on the latest version?
