### ISSUE TITLE
Typescript Update

### ISSUE THREAD

**Issue by MarianoPrz** [AllenFang/react-bootstrap-table#1366]
Hi! can you update typings for typescript? i've been working with sharepoint framework, using your table that look's amazing, but typings aren't for v.3.0 and i cant import custom module, like "InsertButton" for instance. Thanks for your job,

**Comment by AllenFang** [comment]
HI @MarianoPrz, I dosen't support the TypeScript and I think maybe there's some people to do it?!   Let me know your concern because I'm not familiar with ts. thanks
