### ISSUE TITLE
Single TableHeaderColumns element not possible in BootstrapTable

### ISSUE THREAD

**Issue by oeph** [AllenFang/react-bootstrap-table#1367]
Due to the commit 9b748df5eb11dad1fe9c5c28044007dbae119b02 in BootstrapTable.js and the introduction of the filtering, the table will not work when this.props.children is not an array but instead an object (single element as children).

Solution: check if this.props.children is an array and else work on the object.

**Comment by AllenFang** [comment]
sorry, have any case can show what's the object children? I've no time to try this, thanks a lots

**Comment by oeph** [comment]
If an element in React has only one children, the call "this.props.children" does return the object and not an array with a single element inside.
Please look: https://facebook.github.io/react/docs/react-api.html#react.children

That is no edge case, but instead standard behavior.

**Comment by AllenFang** [comment]
why can I work well?!  I mean do you encounter any bug that that you can't render single column table? if yes, any case or example?

```js
BootstrapTable data={ products } keyField='id'>
    <TableHeaderColumn dataField='id'>Product ID</TableHeaderColumn>
</BootstrapTable>
```
or 

```js
// fields only have one column
<BootstrapTable data={ products } keyField='id'>
        {
          fields.map(f => <TableHeaderColumn dataField={ f }>Product ID</TableHeaderColumn>)
        }
      </BootstrapTable>
```

**Comment by oeph** [comment]
yes. with the version 3.3.7 i had a problem rendering for example 

```
<BootstrapTable data={ products } keyField='id'>
    <TableHeaderColumn dataField='id'>Product ID</TableHeaderColumn>
</BootstrapTable>
```

**Comment by AllenFang** [comment]
@oeph, for your example, it's work for me
```js
<BootstrapTable data={ products } keyField='id'>
    <TableHeaderColumn dataField='id'>Product ID</TableHeaderColumn>
</BootstrapTable>
```

any error message?

**Comment by oeph** [comment]
if _adjustHeaderWidth is called there is the error: "this.props.children.filter is undefined" because children is no array but an object. we use remote data and sorting, filtering. Thats why _adjustHeaderWidth could be called but not be called in your example.

i can send you a fiddle next week. but anyway: this.props.children should never be treated as an array without checking. https://facebook.github.io/react/docs/react-api.html#react.children

**Comment by oeph** [comment]
@AllenFang fiddle: https://jsfiddle.net/srj2rx2a/

**Comment by oeph** [comment]
@AllenFang fiddle: https://jsfiddle.net/50z47yg0/

**Comment by AllenFang** [comment]
yes, understand, I'll fix it, BTW, your example it's not good, you should not setState in `componentDidMount`, check https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-did-mount-set-state.md

**Comment by oeph** [comment]
Yes i know, but that was not the point about the issue. I needed the component to get new data after mounting. That can for example happen with the remote usage of the table. The usage of componentDidMount was just to make sure to change the data after it is mounted and so _adjustHeaderWidth will be called.

So yes the issue will dissappear, but data can be changed after mounting anyway. The issue is about the wrong this.props.children handling.

**Comment by AllenFang** [comment]
Hi, @oeph, check again on `v3.3.9`, thanks

**Comment by oeph** [comment]
@AllenFang, this can be another problem. But for me the fiddle that i used to show you the bug (https://jsfiddle.net/50z47yg0/) doesn't work anymore at all. Could you have a look please?

**Comment by AllenFang** [comment]
I'll check this, thanks
