### ISSUE TITLE
Assign className to clicked row on expand

### ISSUE THREAD

**Issue by CoralSilver** [AllenFang/react-bootstrap-table#1370]
Is there a way to add a custom background color or className to a row when a user clicks to expand it, in the same way that you can with the select row option?  I just want the row to expand, and not be selectable.

**Comment by AllenFang** [comment]
HI @CoralSilver, you can use `this.options.expandRowBgColor` to assign the bgcolor for expanding rows but currently, we don't support the className on expanding row yet, but I can support it in near future. is that `this.options.expandRowBgColor` helpful to you?

**Comment by CoralSilver** [comment]
Thanks Allen. Yes I am already using this.options.expandRowBgColor, but I wanted to be able to add a className to the row that it is expanding from so it is more visually obvious that they are connected.

**Comment by AllenFang** [comment]
sorry for lately reply, so you means add the class on original row instead of expanded one?

**Comment by CoralSilver** [comment]
Yes exactly.  And then remove it once the row is closed again.

**Comment by AllenFang** [comment]
@CoralSilver, got it, I'll try to support it as soon as possible.

**Comment by CoralSilver** [comment]
Thanks!

**Comment by AllenFang** [comment]
@CoralSilver, this feature was supported on `v3.4.0`, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/custom-expand-class.js) as example, thanks

**Comment by CoralSilver** [comment]
Thanks Allen. Works perfectly!

**Comment by supiash1** [comment]
@AllenFang  Thanks for your response, The class is added on the tr after expanding is there a way we could add the class when the table is rendered and stays whether it expands or not please?

**Comment by AllenFang** [comment]
@supiash1 Please check 
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/style/tr-class-string-table.js
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/style/tr-class-function-table.js

**Comment by supiash1** [comment]
@AllenFang Thanks for your response
![screen shot 2017-06-14 at 16 05 34](https://user-images.githubusercontent.com/18370888/27139633-7068a518-511b-11e7-8c61-2e9c75e7fe20.png)

As In the picture the expand component will be attached as tr in the main table and hidden next to the expandable row, i would like to add the class on it even when it is not expanded

The examples which you provided would add class to the tr on the expand component table which is inside the tr hidden in the main table(when not in expand state) 

thanks

**Comment by AllenFang** [comment]
You means you want to add a class on the expand row(`hidden` in your snapshot)? if yes, try [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/custom-expand-class.js#L73) and let me know if you have any question or unclear, thanks :)

**Comment by supiash1** [comment]
@AllenFang Thanks I have tried that but that adds class only on expand but i want it to add it even when its hidden please

**Comment by AllenFang** [comment]
@supiash1, I'll handle it. Because I force to add class on on expanding, in next version
I will pass isExpand flag to callback function and always the class on expand row. if you dont want to add the class on hidden, just return null or empty string.

**Comment by AllenFang** [comment]
https://github.com/AllenFang/react-bootstrap-table/issues/1409

**Comment by supiash1** [comment]
@AllenFang  Thank you

**Comment by AllenFang** [comment]
@supiash1, fixed on `v3.4.2` and check https://github.com/AllenFang/react-bootstrap-table/commit/0720e6019cd404b23431aec29d31e66759c4e8cd as example, thanks
