### ISSUE TITLE
Modal validation is triggered after save

### ISSUE THREAD

**Issue by michal84** [AllenFang/react-bootstrap-table#1372]
Hi,

I need to override save mechanism on save and I follow this url:

https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/insert-modal/custom-insert-modal.js

What I saw that when I check 
`this.props.validateState`
after
`onSave(newRow);`
all of my 
`validateState` are null. They are filled after I click second time Save button. 

Here is my component:

    export default class CustomerModal extends React.Component {

      handleSaveBtnClick = (onModalClose, columns, save) => {
        const row = {};
        columns.forEach((column, i) => {
          if(this.refs[column.field] !== undefined && this.refs[column.field].value !== undefined) {
            row[column.field] = this.refs[column.field].value;
          }
        }, this);
        save(row);

        post('/api/users', {
          email: row.email,
          first_name: row.firstname,
          last_name: row.lastname,
          phone_number: row.phone_number,
          active: true,
        })
        console.log(this.props.validateState);
      }

      render() {
        const {
          onModalClose,
          onSave,
          columns,
          validateState,
          ignoreEditable
        } = this.props;
        return (
          <div className='modal-content react-bs-table-insert-modal'>
            <InsertModalHeader
              title="Dodaj"
              onModalClose={onModalClose}
            />
            <div className="modal-body">
              {
                columns.map((column, i) => {
                  const {
                    editable,
                    format,
                    field,
                    name,
                    hiddenOnInsert
                  } = column;

                  if (hiddenOnInsert) {
                    return null;
                  }
                  const error = validateState[field] ?
                    (<span className='help-block bg-danger'>{ validateState[field] }</span>) :
                    null;
                  return (
                    <div className='form-group' key={ field }>
                      <label>{ name } : </label>
                      <input ref={ field } type='text' className="form-control editor edit-text" placeholder={name} defaultValue={ '' } />
                      { error }
                    </div>
                  );
                })
              }
            </div>
            <InsertModalFooter
              saveBtnText="Zapisz"
              closeBtnText="Zamknij"
              onModalClose={onModalClose}
              onSave={ () => this.handleSaveBtnClick(onModalClose, columns, onSave) }
            />
          </div>
        );
      }
    }

Maybe Im doing something wrong ?

**Comment by AllenFang** [comment]
@michal84, what version you used now?

**Comment by mpietraszneurosys** [comment]
`3.3.*`

**Comment by AllenFang** [comment]
> What I saw that when I check
> this.props.validateState
> after
> onSave(newRow);
> all of my
> validateState are null. They are filled after I click second time Save button.

This is no bug, it's right behavior, due to after `onSave` the table will trigger re-render again, so that you can get the newest `validateState` after re-rendering but you can not get the newest `validateState` after onSave immediately

**Comment by AllenFang** [comment]
BTW, if you want to do something after insert row, you can use `options.afterInsertRow` and if your operation is about remote data or operation, please consider to use `remote` props on `BootstrapTable`
