### ISSUE TITLE
Is it possible for clickToSelect only check the checkbox and not uncheck it?

### ISSUE THREAD

**Issue by kwingat** [AllenFang/react-bootstrap-table#1374]
I have a table with a column that has a dataFormat which returns a component. When clicked on, the component expands a div with clickable options.

I need for the column checkbox to be checked when the component is clicked, as it currently functions. However, when the options are being clicked, I can't have the checkbox on the row being unchecked/checked as it currently functions.

What appears to be the simplest solution would be that the clickToSelect only check the checkboxes and not toggle them. Is this possible?  -Thank you very much.

**Comment by AllenFang** [comment]
> What appears to be the simplest solution would be that the clickToSelect only check the checkboxes and not toggle them. Is this possible?

I think it's impossible currently. But I think following example will be helpful to you,

The idea is very easy, I guess you already use `selectRow.selected` to control which rows are being selected, for now, you can also use `selectRow.unselectable` to control which row cant be selected

```js
class Example extends React.Component {
  constructor(props) {
    super(props);
    this.onRowSelect = this.onRowSelect.bind(this);
    this.state = {
      selected: []
    };
  }

  onRowSelect({ id }, isSelected) {
    if (isSelected) {
      this.setState({
        selected: [ ...this.state.selected, id ].sort()
      });
    } else {
      this.setState({ selected: this.state.selected.filter(it => it !== id) });
    }
    return false;
  }

  render() {
    const selectRowProp = {
      mode: 'checkbox',
      clickToSelect: true,
      onSelect: this.onRowSelect,
      selected: this.state.selected,
      unselectable: this.state.selected
    };

    return (
      <BootstrapTable ref='table' data={ products } selectRow={ selectRowProp }>
        <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
        <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
        <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
   );
  }
}
```
Let me know if you still have any questions, thanks
