### ISSUE TITLE
Export with current style? (cvs/pdf)

### ISSUE THREAD

**Issue by rkdmen** [AllenFang/react-bootstrap-table#1375]
Hey Allen,

I want to export with current css style applied to it. Right now, it exports just as text without any styling at all. Is it possible to keep certain format? (font color/background color)?

Also, is there anyway to export as pdf as well? Thanks

**Comment by AllenFang** [comment]
@rkdmen, we don't support this kind of feature, PR will be welcome, thanks

**Comment by tan31989** [comment]
Hi,

I was looking into this and checked some online resources.
Here are the thought process.

- We cannot add color or any formatting information to CSV as it's just a pure textual content and this is more thoroughly mentioned in https://tools.ietf.org/html/rfc4180
- There are some libraries which help you generate `xlsx` from javascript, but that would mean a whole new way of doing the data manipulation and also.

Regards,
Nagaraj

**Comment by rkdmen** [comment]
hello,

I actually had to create whole new code using exceljs on backend. I think that was only way to customize the style way I want. It was time consuming to apply all the styles but I think it's the only way.

**Comment by tan31989** [comment]
@rkdmen Yes, perhaps very true. There has to be another approach.
@AllenFang Can go ahead and close this, as the feature to be requested would be to export as xlsx and not csv with color.

**Comment by AllenFang** [comment]
@tan31989 @rkdmen thanks you guys sharing 👍
