### ISSUE TITLE
Removed sizePerPage option, but the drop down button is still there

### ISSUE THREAD

**Issue by theGirrafish** [AllenFang/react-bootstrap-table#1377]
I'm trying to create a table that doesn't have a limit on how many rows it has per page, so I removed any options related to sizePerPage, but for some reason, the button is still there with the default sizes (10, 25, 30, 50).
How can I remove the button?

     render() {
        const options = {
            prePage: 'Prev',
            nextPage: 'Next',
            firstPage: 'First',
            lastPage: 'Last',
            paginationShowsTotal: renderShowsTotal,
            paginationPosition: 'bottom',
            onPageChange: this.onPageChange,
            page: this.state.page,
            onFilterChange: this.onFilterChange
        };

        return (
                        <BootstrapTable
                            height={700} scrollTop={'Top'}
                            data={this.state.logs}
                            options={options}
                            fetchInfo={{dataTotalSize: this.state.total}}
                            remote striped hover pagination
                            >
                            <TableHeaderColumn isKey hidden dataField='id'>id</TableHeaderColumn>
                            <TableHeaderColumn ref="details" width="900px" dataField="Details" filter={{type: 'TextFilter'}} headerAlign="center">Logging message</TableHeaderColumn>
                        </BootstrapTable>

**Comment by AllenFang** [comment]
hey, is that you want to hide or remove size per page dropdown?? if yes, please try `options.hideSizePerPage`

**Comment by chinu13Jain** [comment]
const options = {
      hideSizePerPage: false,
      onPageChange: this.onPageChange.bind(this),
      onSizePerPageList: this.sizePerPageListChange.bind(this),
      sizePerPage: this.state.targetList.size,
      
    };

 <BootstrapTable
            data={this.state.targetList.content}
            striped
            hover
            pagination
            options={ this.options }>
            <TableHeaderColumn dataField="organizationName" isKey dataSort>Organization Name</TableHeaderColumn>
            <TableHeaderColumn dataField="adminUserName" dataSort>Admin Name</TableHeaderColumn>
            <TableHeaderColumn dataField="adminEmail" dataSort>Email</TableHeaderColumn>
            <TableHeaderColumn dataField="phone" dataSort>Phone</TableHeaderColumn>
            <TableHeaderColumn dataField="userName" dataSort>User</TableHeaderColumn>
            <TableHeaderColumn dataField="status" width="5%" dataSort>Status</TableHeaderColumn>
            <TableHeaderColumn dataField="button" dataSort={false} className="actions" dataFormat={this.buttonFormatter} >Actions</TableHeaderColumn>
          </BootstrapTable>
