### ISSUE TITLE
Collapse expandable row on route change

### ISSUE THREAD

**Issue by JaxonDvl** [AllenFang/react-bootstrap-table#1378]
Hello, I have an issue with the expandableRow Component. When I change the route the previously expanded rows remain expanded. Is it possible to collapse all when I change the route ?
When expanded: 
![screen shot 2017-06-06 at 11 33 58](https://cloud.githubusercontent.com/assets/4042136/26820713/7a8acdca-4aac-11e7-8994-8256e875672f.png)
When changed route and come back to the table:
![screen shot 2017-06-06 at 11 34 25](https://cloud.githubusercontent.com/assets/4042136/26820731/8caab772-4aac-11e7-9029-29ce247447c8.png)

**Comment by JaxonDvl** [comment]
Ok I found the answer for my problem by using 
`this.refs.table.reset()`
#975 here

**Comment by ufukomer** [comment]
@JaxonDvl So when do you run this function? componentDidMount ?
