### ISSUE TITLE
Selection icons (checkbox, radio) do not show up 

### ISSUE THREAD

**Issue by runningcrane** [AllenFang/react-bootstrap-table#1383]
I've copy-pasted code from the examples on https://allenfang.github.io/react-bootstrap-table/example.html#selection and tried them out for myself; however, no selection icons show up at all.
<img width="629" alt="screen shot 2017-06-07 at 3 51 04 pm" src="https://user-images.githubusercontent.com/9300981/26904922-43818614-4b99-11e7-9f6f-9e0deee2d992.png">
<img width="1044" alt="screen shot 2017-06-07 at 3 51 25 pm" src="https://user-images.githubusercontent.com/9300981/26904921-437f5ba0-4b99-11e7-8ed3-2f1dfe654329.png">
^Selection icons were expected to show up on the left-hand side of the table. They are missing.

**Comment by AllenFang** [comment]
I think there's something wrong, but I can't reproduce it by your code, could you reproduce it with a small repo oi on the jsfiddle? thanks

**Comment by runningcrane** [comment]
Sorry Allen, turns out there was a conflicting scss that overrode it has hidden. No problems here!
