### ISSUE TITLE
Different structure of data to render the table

### ISSUE THREAD

**Issue by return007** [AllenFang/react-bootstrap-table#1385]
The BootstrapTable accepts data of form :
```
[
{
    id: 12,
    name: "xyz"
},
{
    id: 13,
    name: "abc"
}  
]
```

I need to construct table for data of the form like this:
```
[
{
    name:{
        first: "ab"
        last: "c"
    },
    id: 13
},
{
    name:{
        first: "xyz"
        last: "pqr"
    },
    id: 12
}
]
```

I tried to do all of the following but none worked.

```javascript
<BootstrapTable data={source} >
    <TableHeaderColumn dataField='name.first'></TableHeaderColumn>
</BootstrapTable>
```

```javascript
<BootstrapTable data={source} >
    <TableHeaderColumn dataField='first'></TableHeaderColumn>
</BootstrapTable>
```

```javascript
<BootstrapTable data={source} >
    <TableHeaderColumn dataField='source.name.first'></TableHeaderColumn>
</BootstrapTable>
```

Please let me know how to go about it.

**Comment by AllenFang** [comment]
@return007, sorry we dont support this feature currently, and it wont be implemented in near future, I suggest most of user to flatten their data first and feed into table. please let me know your concern.

**Comment by return007** [comment]
@AllenFang I was forced to do the same. However more flexibility can be achieved if this use case is taken care of.

**Comment by AllenFang** [comment]
yes, i know, but actually is a big change for current code base, I need sometime for me. thanks

**Comment by prajapati-parth** [comment]
@return007 You can do something like this
```jsx
<BootstrapTable data={source} >
    <TableHeaderColumn
        dataField='name'
        dataFormat={this.nameFormatter}
    >
    </TableHeaderColumn>
</BootstrapTable>

nameFormatter(cell, row, enumObject, index) {
    return `<span>${cell.first}</span>`
}
```
