### ISSUE TITLE
Validor updates table, removing cell classes and detaches "click to nav" from "editable"

### ISSUE THREAD

**Issue by IHeartReact** [AllenFang/react-bootstrap-table#1386]
Setting state "shakeEditor" causes an update of the table, and of the cell, which removes classes, unfocuses the cell, and detaches the "Navigation" from "editable".

Very annoying bug.

`ts.setState({ shakeEditor: false });`

To fix this I removed
`
//	          ts.setState({ shakeEditor: true, className: className });`

and 

`//	            ts.setState({ shakeEditor: false });`

**Comment by AllenFang** [comment]
I'm very sorry but I still doesn't know what error or bug happen, please make this issue clear, thanks
