### ISSUE TITLE
Keyboard navigation over expanding rows

### ISSUE THREAD

**Issue by Ninerian** [AllenFang/react-bootstrap-table#1389]
Hello,

thank you for this create script. It really makes table handling easy. 👍 

Currently I work on a table with subtables inside expanding rows.
It works great, but when I enable keyboard navigation, I could only navigate through the root table. For the tables in the expanded Row, I have to click again inside a cell.

Would it be possible to handle the navigation from row to row?
Also it would be great to expand/hide rows with the keyboard.

**Comment by AllenFang** [comment]
@Ninerian for the navigation into the subtable in expanded row, it's hard to implement I guess.

For expand/hide rows by keyboard is a good feature, I'll consider to implement in future, thanks 👍

**Comment by AllenFang** [comment]
@Ninerian, fixed on `v3.4.0` and check https://github.com/AllenFang/react-bootstrap-table/commit/6b6aa02d06545786e6e0d22d04fa2835dd6bbf25 for example.

you can configure `keyBoardNav.enterToExpand` as true, it will let user can press enter to expand/collapse the row.
