### ISSUE TITLE
Use modal in the columns to edit the respective column.

### ISSUE THREAD

**Issue by ajits731** [AllenFang/react-bootstrap-table#1390]
I'm trying to use modal to edit the row I clicked rather than cell edit. I doing the following. 
` constructor(props) {
      super(props);
      this.state = { showModal: false};
   }`
`<TableHeaderColumn width='120' dataField='_id' dataFormat={this.editCamp}>Edit</TableHeaderColumn>`

and editCamp function is: 
`editCamp(cell,row) {
  return <Link className="btn btn-warning" onClick={this.open.bind(this)} ><span className="fa fa-pencil-square-o"></span></Link>;
}`

But the modal isn't working more over the whole data disappears from the ReactBootStrap Table.

**Comment by AllenFang** [comment]
HI, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/cell-edit/custom-cell-edit-table.js#L187-L191

let me know if you have any questions, thanks
