### ISSUE TITLE
React Bootstrap Table doesn't update data on componentDidUpdate

### ISSUE THREAD

**Issue by holzfelix** [AllenFang/react-bootstrap-table#1392]
Hi,

I've got a table that's empty at the beginning and I want the user to insert data. This is my state:

```
this.state = {
            ...
            myArray: [],
	    ...
}
```

Within "myArray" is another array that holds the data to be displayed in the table:

```
 <BootstrapTable data={this.state.myArray[index].myInnerArray} striped hover condensed pagination options={{noDataText: "No data available"}}>
                            <TableHeaderColumn width='200' dataField="title" dataSort={true} isKey>Title</TableHeaderColumn>
                        </BootstrapTable>
```

I've got a button that opens a modal in which the user can choose from options that will be displayed in the table:

`<Button onClick={()=>{this.openModal(index)}}>+</Button>`

When you click on an option it triggers "componentDidUpdate":

```
componentDidUpdate(){
	const index = this.state.currentIndex;
        if(this.state.myArray[index].myInnerArray.length !== 0)
            return this.state.myArray[index].myInnerArray;
}
```

The update of state works perfectly fine. It does exactly what it's supposed to do, however the table doesn't update (re-render). If I were to add another table with the same array, it displays the data (because it's not empty anymore).
Does your table support data changes on-the-fly? I searched for this feature, but couldn't find it.

Is there generally a way to update "data" on componentDidUpdate (e.g. by using "setState()"), or do I have to customize your given "insertRow"-modal in order to change data on-the-fly? 
I've tried to do that, but that just a disproportionate effort for it's intended functionality, in my case.

Thanks for your work!

**Comment by AllenFang** [comment]
I think this is not a bug, in your `componentDidUpdate`, you are supposed to be called `setState`, do you did that?

**Comment by holzfelix** [comment]
I believe the source of the problem is the asynchronous setState or the point in time, in which the table re-renders. I already tried to do this (doesn't work either):

```
if(this.state.myArray[index].myInnerArray.length !== 0) {
            this.setState((prevState) => ({
                myArray: prevState.myArray.map((currentIndex, i) => {
                    if (i === this.state.currentIndex) {
                        return {
                            ...currentIndex,
                            myInnerArray: this.state.myArray[this.state.currentIndex].myInnerArray
                        }
                    }
                    return currentIndex
                })
            }), () => {
                console.log("New state in ASYNC callback:", this.state.myArray);
                //Even forced another componentDidUpdate like this:
                //this.componentDidUpdate();
            } );
        }
```

The callback function will be called whenever setState is finished and correctly displays the new data. However, the table doesn't adjust to the new data. Do you know when your table gets re-rendered? I think componentDidUpdate doesn't do the job, since I'm printing every step to the console.

**Comment by AllenFang** [comment]
ok, so could you please create a very simple and minimal example code for me to reproduce your case?  Just example code, without webpack, redux etc, let focus on the problems, thanks

**Comment by holzfelix** [comment]
It essentially breaks down to this: #1393. Could you provide an example on how to use "reset", please?

**Comment by AllenFang** [comment]
```js
handleReset() {
  this.ref.table.reset()
}

render() {
  return (
    <div>
        <button onClick={ this.handleReset.bind(this) }>RESET</button>
        <BootstrapTable ref='table' ...></BootstrapTable>
    </div>
  );
}

```

**Comment by holzfelix** [comment]
Hi Thanks,

I got this error:

Uncaught (in promise) Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded

**Comment by AllenFang** [comment]
could you please check if there's multi react loaded? and how did you add `react-bootstrap-table`? use `script` or commonJS and bundled by webpack?

**Comment by holzfelix** [comment]
React is only loaded once. 

I use this to import react-bootstrap-table

`// BootstrapTable
import {BootstrapTable, TableHeaderColumn} from "react-bootstrap-table";`

And yes I use webpack

**Comment by AllenFang** [comment]
@holzfelix, sorry I can't reproduce this issue and any simple and minimal repo to reproduce this issue?

**Comment by holzfelix** [comment]
@AllenFang I believe it's not actually related to your table. React doesn't render/pass prop types to the tags correctly because I store the html in a variable and display the variable like this:

```
render(){
  return(
    <div>
      ...
      {this.state.htmlArray}
      ...
    </div>
  )
}
```

I added an input field that should display the written value, but it doesn't work either. So the problem doesn't come from your table. Sorry to bother you, and thank you for your help :)

**Comment by AllenFang** [comment]
ok, but please let me know if you have any question or need some help, thanks :)

**Comment by tarim** [comment]
Hi @AllenFang,

I have a similar issue. After I update(with popup model) one row, the table doesn't show the updated status until I click the table. But, the redux store updated record correctly. 

Any idea, please?

Thanks,
