### ISSUE TITLE
Conflict between tabIndex

### ISSUE THREAD

**Issue by mvscosta** [AllenFang/react-bootstrap-table#1394]
Hi Allen,

I'm having a problem in a page that contains more than one react-bootstrap-table and others input fields, because the tab index in <td> always start with 1 and increment by 1 for next data and rows.
The tables are in separated divs with panel class.
Have any ideia to solve this problem, because when i try to navigate in the page with [tab] key doesn't work.

Thanks
MVSC

**Comment by stephanebarbey** [comment]
We are facing the same issue...

**Comment by AllenFang** [comment]
have you tried the keyboard navigation feature? https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/keyboard-nav

**Comment by mvscosta** [comment]
Hi Allen,

I tried to use the keyboard navigation, but at the rows of table continuous to writing the tabindex element.
I found a line in the component that create this element, my suggestion is change the line:
	                tabIndex: tabIndex++ + '',
to 
	                tabIndex: enableKeyBoardNav ? tabIndex++ + '' : '0',
Or something to don't create a element tabindex when dont enabled the keyboard nav.
Another stuff needed is a way to set the start value of tabindex.

What you think about?
Have another way to remove the tabindex? In my program actually i have dashboards with 8 - 10 tables.

Bests
Vinicius

**Comment by AllenFang** [comment]
How about give a props so that you can remote the `tableIndex`?

**Comment by mvscosta** [comment]
Hi Allen,

Is a good way to make better the control of tabindex, but what do you do with auto increment "tabIndex: tabIndex++" implementation?

Thanks

**Comment by AllenFang** [comment]
@mvscosta, if I provide a props to close the `tableIndex`, is that help to you? Sorry for lately reply lol

**Comment by mvscosta** [comment]
If this props remove the tabindex attribute for me is good. This implementation is so simple, don't solve anothers cases but for now is good.

**Comment by AllenFang** [comment]
ok, I'll support it, thanks your response 👍

**Comment by AllenFang** [comment]
@mvscosta this was fixed on `v3.4.5`, you can use `withoutTabIndex` on `BootstrapTable` to disable `tabIndex`, thanks

**Comment by shogan94** [comment]
@AllenFang I'm on `v4.0.0-beta.7` and `withoutTabIndex` doesn't seem to be doing anything for me. 

My table looks like 

```
 <BootstrapTable data={data} withoutTabIndex>
      <TableHeaderColumn isKey dataField="Id" hidden>Id</TableHeaderColumn>
      <TableHeaderColumn dataField="FirstName">First Name</TableHeaderColumn>
      <TableHeaderColumn dataField="LastName">LastName</TableHeaderColumn>
 </BootstrapTable>
```

Is there something else I need to do? Or another way to override and disable `tabindex`

**Comment by AllenFang** [comment]
@shogan94 , yes, I'm not bump `v4.0.0-beta.7` with `v3.4.5` yet, I'll bump v4.x` version in next few day, please wait, thanks :)

**Comment by AllenFang** [comment]
`v4.0.0` release.
