### ISSUE TITLE
Insert row validation

### ISSUE THREAD

**Issue by nguyenhose** [AllenFang/react-bootstrap-table#1395]
Hi, I'm using react bootstrap table and here is my workflow on a list users table:
1. Create an user
2. Check user information by calling an api
3. If response result is OK, then insert new row. If not OK, then show validate error

The problem is `afterInsertRow` or `onAddRow` will insert row immediately without waiting for asynchronous check, and in this case, a row will still insert if insert request is wrong . Any suggestion for this issue ?

**Comment by AllenFang** [comment]
hello, please check #1391 detail, I know you case and let me know your concern after you reading #1391, thanks

**Comment by AllenFang** [comment]
I'll reopen it if this issues is different with #1391, thanks

**Comment by nguyenhose** [comment]
yeah, the point is supporting asynchronous validate row data :-)

**Comment by AllenFang** [comment]
@nguyenhose, fixed on `v3.4.1`, you can check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/advance/insert-error-handle-table.js) to know how it work, thanks
