### ISSUE TITLE
Possible to add additional datafield per column?

### ISSUE THREAD

**Issue by DeeRebz** [AllenFang/react-bootstrap-table#1398]
I have a table where each row only has one column - the Item Name. I'd like to add (in a smaller font size) the item description directly under each item name and in the same row. The way I'm seeing it, it would need to be an additional dataField in the column. Is this possible?

**Comment by AllenFang** [comment]
The best solution is using the column group(`rowspan`), but currently, we only support column group on header. But actually, you can use `dataField` to split a td as two division.

For example:


```js
const data = [{
  name: '...', description: '...'
},{
  name: '...', description: '...'
}];


class Table extends React.Component {

  formatName(cell, row) {
      // get name by row.name
      // get description by row.description
      return (
          <div style={ { display: 'grid' } }>
              <div>{ row.name }</div>
              <div>{ row.description }</div>
          </div>
      );
  }

  render() {
    return (
      <BootstrapTable data={ data }>
          <TableHeaderColumn dataField='name' isKey={ true } dataFormat={ this.formatName }>Item Name</TableHeaderColumn>
      </BootstrapTable>
    );
  }
}

```

Let me know if you have any concern, thanks

**Comment by DeeRebz** [comment]
Perfect, thank you!

**Comment by PrashanthSuriyanarayanan** [comment]
I have the same scenario but I want both the field to be editable. Is there any way right now?

**Comment by PrashanthSuriyanarayanan** [comment]
I guess I can use "customEditorParameters" to display two inputs in the same field. I will try it and get back. 

Thanks

**Comment by AllenFang** [comment]
@PrashanthSuriyanarayanan sorry for lately reply, if your data field is nest or an object, it's impossible to edit I guess, if it's available please let me know :p

**Comment by RA344710** [comment]
My Json object is like this:
searchArray=[
    {
        "headers": {},
        "body": {
            "id": "5a55ebe3cb40f31d042d503a",
            "name": "java",
            "desc": "java desc",
            "categories": [
                "JEE Web Application",
                "NET Web Application"
            ],
            "assessmentCount": 0
        },
        "statusCode": "OK",
        "statusCodeValue": 200
    },
    {
        "headers": {},
        "body": {
            "id": "5a55f7dccb40f31d042d503b",
            "name": "ajax",
            "desc": "ajax desc",
            "categories": [
                "JEE Web Application"
            ],
            "assessmentCount": 0
        },
        "statusCode": "OK",
        "statusCodeValue": 200
    }
]
How can I print name, categories in dataField by using <BootstrapTable>?
plz share solution...
