### ISSUE TITLE
Default sorting

### ISSUE THREAD

**Issue by mfirry** [AllenFang/react-bootstrap-table#14]
How can I set a default sorting rule for the table?

**Comment by AllenFang** [comment]
hI @mfirry , there's no way to set sorting rules currently.

But I can add this feature.. in recently :)

**Comment by AllenFang** [comment]
I've release newest version v0.8.9 for this issue. Sorry a long time to fix it. :)

**Comment by AllenFang** [comment]
You can assign options prop on <code>&lt;BootstrapTable&gt;</code> and give two properties on that object, example as follow
<pre>
var options = {
  sortName: "name",  //default sort column name
  sortOrder: "desc"  //default sort order
}
&lt;BootstrapTable data={products} options={options}&gt;
//...
</pre>
