### ISSUE TITLE
about deleting rows

### ISSUE THREAD

**Issue by jcabrerazuniga** [AllenFang/react-bootstrap-table#1401]
Is there any command that after deleting a row or a set of rows will return me the list of all the deleted rows? not just their respective indexes?

**Comment by AllenFang** [comment]
Sorry, we only give the rowkeys only, does any case that you can't get the row with rowkey? I think this issues is very minor, I'll open it if there have any concern or critical issue, thanks

**Comment by jcabrerazuniga** [comment]
By having the content of the rows needed for deletion we can ensure that the data that is needed to be deleted will be deleted and no more, no less. Deleting is very critical but the use of the row keys is not and somehow it could be a great idea to be able to be independent of them as much as possible. In my case, I am using as a row key a column that doesn't exist in the DB so I could use the Boot Strap table. To solve this problem I had to create a state to contain all the selected rows. But, I had to trace all the transactions to destroy, add or delete elements from this set. I know, it looks minor, but given that the deletion of rows is very important topic then that capability to return the rows (including their content) could be paramount -as in my case-

**Comment by AllenFang** [comment]
ok, I'll try to add row for you, thanks

**Comment by XidongHuang** [comment]
Hi @AllenFang , 
I am using `Redux` with `react-bootstrap-table` now. It works fine for displaying data, but what if I want to delete data in database by deleting data in the table?

So base on examples, I am trying to get the key property of the data I am trying to delete, then send the request to back-end for deleting it in database. 
I expect we can do like this:
```
    /*
    Get deleting data's properties(at least the key - primary key in db) and send to back-end api
    */
    handleDeleteButtonClick = (onClick) => {

        //Could I get the properties of the data I want to delete? like this:
        console.log('delete', onClick.props.data.key);

        //then use action like this??
        this.props.deleteAction(data.key) 
    }

    //About delete
    deleteButton = (onBtnClick) => {
        return (
            <btn className="btn btn-danger" onClick={e => 
this.handleDeleteButtonClick(onBtnClick)}>Delete Account</btn>
        )
    }
    
    options = {
       ...
        deleteBtn: this.deleteButton, //About delete
        
    }

    selectRowProp = {
        mode: 'checkbox',
    }


    render() {
        const data = _.isEmpty(this.props.data)? []: this.props.data;
        return (
            
             <BootstrapTable id='mdm-table' containerStyle={{'marginTop': '1em'}}  
                       data={data} striped hover search  condensed pagination 
                       deleteRow options={this.options} selectRow={this.selectRowProp}>
                            
              <TableHeaderColumn isKey tdStyle={{whiteSpace: 'normal', 'wordWrap': 'break-word'}} 
                      thStyle={{whiteSpace: 'normal'}}  
                      dataField="email" dataSort>Email</TableHeaderColumn>
                          ....

             </BootstrapTable>
 
        
        );
    }
...
```


I also check the issue: [#1243](https://github.com/AllenFang/react-bootstrap-table/issues/1243), I think it is pretty similar with my purpose, but still don't understand the examples...

Please give some advises of it.

Thank you so much

**Comment by AllenFang** [comment]
Hi @XidongHuang, like I mention in https://github.com/AllenFang/react-bootstrap-table/issues/1243, 

You can try to use `remote` mode, `remote` mode will let you to handle your data , particular for async operation on data. 

so in the redux, you can:

`React Component :`
```js
handleDeleteRow(row) {
    this.props.deleteAction(row.id);
}

render() {
    return (
      <BootstrapTable data={ this.props.data }
                      remote={ true }   << important
                      deleteRow={ true }
                      selectRow={ { mode: 'radio' } }
                      options={ { onDeleteRow: this.handleDeleteRow} }>
        <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
        <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
        <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
```

`Redux Action :` I used `redux-thunk` as example
```js
export function deleteAction(row) {
  return dispatch => {
    // do your ajax call here to delete the row
    // then dispatch a Action to reducers if success
  }
}
```
`Reducer:`

```js
const initialState = {
  data: ....  // << this is the data for your table 
}

export default function(state = initialState, action) {
   switch(action.type) {
      case: "successful_delete":
         //   delete the row from current state and return it as new state
   }
}
```

**Note:** in `remote` mode, `react-bootstrap-table` just like a stateless table, you need to update table data in every action(delete, insert, update etc)

Let me know if you have any questions, thanks :)

**Comment by AllenFang** [comment]
@jcabrerazuniga, your requirement was fixed on `v3.4.2`, please have a look on it and let me know if the problem still remain. thanks

now, you can get whole rows on `onDeleteRow` and `afterDeleteRow` callback, they will be pass on last argument

**Comment by XidongHuang** [comment]
@AllenFang Thanks sir, I got the solution. Just found your example is very clear in the doc, I didn't think remote is the way get the deleting data.

And one more question here, how can I stop the `alert` when I click the delete button?
Thanks for your time!

**Comment by jcabrerazuniga** [comment]
Thanks a lot @AllenFang. So, you mean that for the call back:

onDeleteRow(rows) {
  // ...
}

there is another parameter like:

onDeleteRow(rows, fullrows) {
  // ...
}

?
