### ISSUE TITLE
Calling simple function from custom column?

### ISSUE THREAD

**Issue by dlucidone** [AllenFang/react-bootstrap-table#1405]
![screen shot 2017-06-15 at 2 55 43 pm](https://user-images.githubusercontent.com/9256365/27174775-dc794bc6-51da-11e7-8fb7-91c466af0afe.png)

I have tried way to achieve but no docs or simple solution is present. Help me out Thanks for amazing work

**Comment by AllenFang** [comment]
check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-format/react-column-format-table.js
or https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-format/html-column-format-table.js

Let me know if this is not your answer.

**Comment by dlucidone** [comment]
@AllenFang I tried as i have posted image above i'm able to create a button but how do i call functions from on click of button i have tried ways with onclick it worked but not able to pass data to it.

**Comment by AllenFang** [comment]
Hello, sorry for lately reply, what data you want to pass? and could you please show me your example code? but please keep it simple and minimal, thanks a lots 👍

**Comment by ohtanya** [comment]
@dlucidone were you able to fix this issue?
