### ISSUE TITLE
 Bug in TableStore.js: If a key is 0, it's regarded as invalid

### ISSUE THREAD

**Issue by freeboarder42** [AllenFang/react-bootstrap-table#1408]
In TableStore.js, row 241/242:
```
 isValidKey = key => {
    if (!key || key.toString() === '') {
```
Problem here is that `!key` will result in true for a key that stores the value 0. In my opinion, the value 0 is perfectly valid for a key. I changed this in my copy to
```
 isValidKey = key => {
    if (key == null || key.toString() === '') {
```

I also changed `addAtBegin`:
```
addAtBegin(newObj) {
   if (newObj[this.keyField] == null || newObj[this.keyField].toString() === '') {
```

**Comment by AllenFang** [comment]
@freeboarder42, fixed on `v3.4.1`, thanks 👍
