### ISSUE TITLE
Remove Expand Row Padding

### ISSUE THREAD

**Issue by ZephD** [AllenFang/react-bootstrap-table#1415]
How can I remove the expanded row padding?
Or add a class to the expanded row?
This is so that a nested table will align perfectly with the parent table columns

See the screenshot below.

![screenshot from 2017-06-22 13-23-10](https://user-images.githubusercontent.com/1461917/27433795-0ca9044e-574e-11e7-9eac-690feabdb264.png)

**Comment by PeterMerkert** [comment]
What a coincidence, but I also came across this just about 2 days ago. I have tried everything so far, but have not found a solution to inject a class to the subtable. Once we had a class option, we could modifiy it how we want.
Now, I thought that maybe we can still manipulate it, once we can access it with CSS selectors somehow. However, the only option I found it selecting the table as such (without background) with `td > .react-bs-table-container`.
It would be great, it we could supply a class to the subtable.

**Comment by ZephD** [comment]
Workaround:
Add
```<BootstrapTable
  headerStyle={{ display: 'none' }}
  tableStyle={{ margin: -8, borderRadius: 0, border: 0 }}
> ... </BootstrapTable>```
to the nested table (assuming it's react-bootstrap-table).

**Comment by AllenFang** [comment]
Hello forks, I'm wondering if [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/custom-expand-class.js) is helpful for your case, let me know your concern, and I'll support this feature if above solution is not good for you, thanks 👍

**Comment by PeterMerkert** [comment]
Thanks for your approach @ZephD :+1: . However, I need to modifiy :hover pseudo effects and others, which are not that easy with inline styles (if even possible). And anyway, we try to avoid the inline styling due to our reuse of the structures everywhere.
So, @AllenFang , I would be delighted if you could introduce `expandBodyClass` and `expandParentClass` l like in the example. It's more versatile. :thumbsup:

**Comment by AllenFang** [comment]
ok, let me mark it as `in progress`, I'll give a quick introduction for `expandBodyClass` and `expandParentClass` after my work off, thanks

**Comment by ZephD** [comment]
```
.expand-row-body {
  > td {
    padding: 0 !important;
  }
}
```

```
 const options = {
    expandBodyClass: 'expand-row-body',
  };
```

Sadly, `expandBodyClass` affects the `<tr>` not the `<td>` that has the padding, resulting in the need to affect the direct child.
Also, the default `padding: 8` for the `td`s is more specific and therefore overrides the `expand body class`, resulting in the need for `!important`.

However, this does fix the issue.

**Comment by AllenFang** [comment]
yes, `expandBodyClass ` will apply your custom class on the `tr`, but the `padding` was cause by `td` 👍 

I think @ZephD 's solution is good and @PeterMerkert you may take a look on it 👍 

and let me know if there's any concern, thanks

**Comment by PeterMerkert** [comment]
Yeah, the option should fix my issue, too. :+1:

**Comment by AllenFang** [comment]
ok, I'm going to close this ticket but feel free let me know if you want more support, thanks a lot 👍

**Comment by PeterMerkert** [comment]
Yes, I just double checked it, and @ZephD selector is working just fine. However, big thanks for the additional classes. They help a lot to customize @AllenFang  the table :-)

Simply great work!

**Comment by ShanikaEdiriweera** [comment]
@AllenFang Is there a way to align parent row and child row columns?
