### ISSUE TITLE
Cannot read property 'sortFunc' of undefined when conditionally rendering different tables

### ISSUE THREAD

**Issue by kylem038** [AllenFang/react-bootstrap-table#1418]
Currently in my app there's a select where a user can pick from a variety of different report types, each which renders an entirely new BootstrapTable component. Each column in each table has the 'dataSort' prop to allow for sorting. If the user sorts by a column which is shared by all the other tables, such as an id, everything works great. If the user sorts by a unique column to that table, and then selects a different table we get 'Cannot read property 'sortFunc' of undefined' at TableDataStore.js:735. I guess I'm confused as to why sorting in one BootstrapTable is being transferred to another component. Is there anything I need to do to deSelect a sorted column before rendering a new table in this scenario?

Thank you! Any help would be greatly appreciated 😄

**Comment by AllenFang** [comment]
@kylem038, it seems like a bug, I'll try to fix it ASAP, thanks 👍

**Comment by AllenFang** [comment]
After my quick survey, the problem is in the `componentWillRecieveProps` in `BootstraTable`, actually, I guess you replace the `react-bootstrap-table` by different report type. But in `componentWillRecieveProps`, I only consider to update table state by previous and current, but in you case, I replace the table maybe with different column, different data etc. so I would like to support another props call `replace`, if true assign, `react-bootstrap-table` will force render table without integrate previous state.

**Comment by AllenFang** [comment]
Fixed on `v3.4.2`, please have a look on it and let me know if the problem still remain. thanks

now, please add `replace` props on `BootstrapTable` then I think you shouldn't see this bug again.

**Comment by kylem038** [comment]
@AllenFang Works like a charm! Thanks for the quick response. 

Just a head's up, in one version of our app we default pagination to false. If the user clicks "Show Less" we set pagination to true. After adding in the replace prop we noticed that switching from false to true didn't show any data in the table, at least not until we switched from one report to another. 

Again - thanks so much for the quick turn around on this!

**Comment by AllenFang** [comment]
> If the user clicks "Show Less" we set pagination to true. After adding in the replace prop we noticed that switching from false to true didn't show any data in the table, at least not until we switched from one report to another.

I guess in this condition(Most of case), the `replace` should be `false` and maybe the problems will gone ?!

**Comment by yummyelin** [comment]
Hi Allen, I met the same error message. I have a guess which may help debug.

In my app. there are two Tabs(react-bootstrap), and each tab is rendering a BootstrapTable. Every BootstrapTable is given different data from selector. Every BootStrapTable is added cellEditProp.
The first BootStrapTable has four rows, second BootStrapTable has one row.
Clicking on 1st row of first BootStrapTable, afterSaveCell printed row object is the 1st row object of second BootStrapTable.
Clicking on 2nd or 3rd or 4th row of first BootStrapTable, it gives undefined error:

TableDataStore.js:250 Uncaught TypeError: Cannot set property 'status' of undefined
    at TableDataStore.edit (TableDataStore.js:250)
    at BootstrapTable.editCell (BootstrapTable.js:1033)
    at BootstrapTable.handleEditCell (BootstrapTable.js:1012)
    at TableBody.__handleCompleteEditCell__REACT_HOT_LOADER__ (TableBody.js:527)
    at Object.TableBody._this.handleCompleteEditCell [as completeEdit] (TableBody.js:106)
    at TableEditColumn.__handleBlur__REACT_HOT_LOADER__ (TableEditColumn.js:128)
    at TableEditColumn._this.handleBlur (TableEditColumn.js:58)
    at Object.ReactErrorUtils.invokeGuardedCallback (ReactErrorUtils.js:70)
    at executeDispatch (EventPluginUtils.js:85)
    at Object.executeDispatchesInOrder (EventPluginUtils.js:108)

My guess is afterSaveCell does not get the correct row object from correct BootStrapTable. replace prop doesn't help solve it. My react version is listed for your reference. "react": "15.4.1", "react-bootstrap-table": "^3.4.2"

**Comment by AllenFang** [comment]
@yummyelin, your table columns is all different?

**Comment by yummyelin** [comment]
a few columns are the same, others are not.

Thank you for your quick response. We found the problem. The two BootStrapTables are given the exactly same cellEditProp. If give two same cellEditProp with different name, they will work fine.

```
   const cellEditProp1 = {
      mode: 'click',
      blurToSave: true,
      afterSaveCell: (row) => {
        console.log(row);
      },
    };

   const cellEditProp2 = {
      mode: 'click',
      blurToSave: true,
      afterSaveCell: (row) => {
        console.log(row);
      },
    };
```

**Comment by AllenFang** [comment]
@yummyelin, I think you can still use same instance, but avoid to use same `afterSaveCell`. give a try
