### ISSUE TITLE
CSS not being applied

### ISSUE THREAD

**Issue by james-prado** [AllenFang/react-bootstrap-table#1422]
[Repo](https://github.com/james-prado/style-issues)
[Live Demo](https://styles-issue-vrvzzrpnni.now.sh/)

DataTable.jsx:
```
import React from 'react'
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table'
import 'react-bootstrap-table/dist/react-bootstrap-table-all.min.css'

export default class DataTable extends React.Component {
	constructor(props) {
		super(props)

		this.state = {}
	}

	componentWillMount() {
		this.state = [
			{
				id: 1,
				name: 'Item name 1',
				price: 100,
			},
			{
				id: 2,
				name: 'Item name 2',
				price: 100,
			},
		]
	}

	priceFormatter(cell, row) {
		return '<i class="glyphicon glyphicon-usd"></i> ' + cell
	}
	render() {
		return (
			<BootstrapTable data={this.state} striped={true} hover={true}>
				<TableHeaderColumn
					dataField="id"
					isKey={true}
					dataAlign="center"
					dataSort={true}>
					Product ID
				</TableHeaderColumn>
				<TableHeaderColumn dataField="name" dataSort={true}>
					Product Name
				</TableHeaderColumn>
				<TableHeaderColumn dataField="price" dataFormat={this.priceFormatter}>
					Product Price
				</TableHeaderColumn>
			</BootstrapTable>
		)
	}
}
```

I'm pretty sure that I've correctly imported the styles, however, the styles won't apply to the DataTable component

Steps to reproduce:
- create a project with [create-react-app](https://github.com/facebookincubator/create-react-app)
- `npm install --save react-bootstrap-table`
- create a data table component and import css using es6 syntax
- import the data table component into another component (in my case App.jsx)

**Comment by AllenFang** [comment]
Hello @james-prado, do you import bootstrap.css? `react-bootstrap-table` depend on bootstrap so that you are suppose to import `bootstrap.min.css`.  But `bootstrap.js` is not necessary.

**Comment by james-prado** [comment]
You are 100% correct, idk how i didn't realize I had to use bootstrap with this, it's even in the name.
