### ISSUE TITLE
noDataText colspan value is greater than the number of columns when the select column is hidden

### ISSUE THREAD

**Issue by luisega** [AllenFang/react-bootstrap-table#1424]
Hi!
In 4.0.0-beta.2 I am experiencing, an issue customizing the noDataText. 

I have several tables, but the simplest one only has one column and the hideSelectColumn property set to true. However, when displaying the noDataText, the colspan that I am obtaining is 2 (always, one more than the number of columns I have configured).

I have checked the Issue #1091 but I am still experiencing this problem.

Thanks!

**Comment by AllenFang** [comment]
@luisega, thanks, I'll check this

**Comment by AllenFang** [comment]
@luisega, if you upgrade to `v4.0.0.beta.6`, the problem still remain?

**Comment by AllenFang** [comment]
@luisega, this defect was fixed on `v4.0.0-beta.7` and `v3.4.4`, thanks

**Comment by luisega** [comment]
It works @AllenFang! Thank you very much! 😄
