### ISSUE TITLE
Multi type editor

### ISSUE THREAD

**Issue by ravihirani** [AllenFang/react-bootstrap-table#1425]
Hi

Is there a way I don't need to create a editor for each field and instead create 1 editor where I can provide cases which can serve up an edit input if dataField = active for example?

I have 10 fields and having 10 individual editors isn't the best solution as I would be repeating a lot of code.

Any suggestions would be appreciated.

**Comment by AllenFang** [comment]
@ravihirani, sorry for lately reply, what's editor you use? for cell editing or insert? thanks

**Comment by ravihirani** [comment]
No worries, for cell editing

**Comment by ravihirani** [comment]
@AllenFang any suggestions?

**Comment by AllenFang** [comment]
@ravihirani, sorry for lately reply, busy on my works...

For your case, if you use the cell editing, you can create a common React editor for your each field and reuse it on each `customEditor`.
