### ISSUE TITLE
Allow dynamic max table height, displaying scrollbar on overflow

### ISSUE THREAD

**Issue by TAGC** [AllenFang/react-bootstrap-table#1432]
I'm aware that you can set a [maxHeight](http://allenfang.github.io/react-bootstrap-table/docs.html#maxHeight) prop for the table, but this seems to only accept a fixed height value e.g. 200px.

I would like to be able to make the bootstrap table set its max-height to the height of its parent element and display a scrollbar if it exceeds that.

I've tried to do this manually by faffing about with rules targeting the react bootstrap table CSS classes, but I haven't managed to find a decent workaround.

**Comment by AllenFang** [comment]
@TAGC, yes, currently, we only support a fixed max height. I think the workaround is that you need to calculate the height of its parent element and config it on `BootstrapTable`.

if anything you feel it worth to enhance, PR is welcome, thanks
