### ISSUE TITLE
table layout : fixed causing text overlap

### ISSUE THREAD

**Issue by jivanshr** [AllenFang/react-bootstrap-table#1433]
Here I see two tables. one for table header and another for table body.  

Now the problem here is to manage equal width for td and th. which you guys have solved by using table layout :fixed.
And it is not good approach since long text are overlapped

<img width="897" alt="screen shot 2017-06-30 at 9 49 46 am" src="https://user-images.githubusercontent.com/4607569/27720506-868540ee-5d79-11e7-8814-6d4453fbe64b.png">

**Comment by konekoya** [comment]
Also encountered this issue the other day. My workaround is:

```css
td {
word-break: break-word;
}
```

And make sure that you don't have `white-space: nowrap` in these tds.

**Comment by AllenFang** [comment]
If only some columns will have this situation, you can fix it by `tdStyle`, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column/column-style-table.js#L27

You can configure the global `td` in your css, but there's a better way to solve it via https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/style/td-class-string-table.js

check [this](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/style) folder, `react-bootstrap-table` support a lots of way to configure the class and style, let me know if you have any concern or question, thanks 👍
