### ISSUE TITLE
Insert rows avoiding modals

### ISSUE THREAD

**Issue by gravitycode** [AllenFang/react-bootstrap-table#1434]
Hi All!. I have a question. Is possible to insert rows like cell edit method? i have few cells and i want to avoid the modals. It would be interesting to do it inline.

**Comment by AllenFang** [comment]
@gravitycode, sorry we only support the insert via modals, but actually, you can do any way to insert row by yourself, then update the state for table or calling [handleAddRow](https://allenfang.github.io/react-bootstrap-table/docs.html#handleAddRow) which is exposed by `BootstrapTable`. 

I want to say, you can insert new data through your custom component then add to table by updating state or API and i think it's very easy. But for your case, if you want to insert row like cell edit? how your perform this insert action? maybe you can share your thinking and maybe I can help you if it's possible. Thanks and sorry for lately reply.

**Comment by reactionic127** [comment]
I am having same issue with @gravitycode 
@AllenFang Could you kindly add this functionality for us?
Best regards.

**Comment by AllenFang** [comment]
@reactionic127, this feature is much minor too me, there's some high priority things I need to do. Like I mention above, you can still achieve this functionality via other custom ways.
