### ISSUE TITLE
Uncaught TypeError: dom.getFieldValue is not a function

### ISSUE THREAD

**Issue by wzup** [AllenFang/react-bootstrap-table#1436]
A custom field of `type="file"`  in an `InsertModal` throws an error. How to manage file uploads?

A field:

![file - google chrome 2017-07-02 21 31 56](https://user-images.githubusercontent.com/3880497/27770272-1616fcd4-5f6e-11e7-9f99-e460aa9a2ebb.png)

An error thrown by the plugin:

```
InsertModalBody.js:57 Uncaught TypeError: dom.getFieldValue is not a function
    at InsertModalBody.<anonymous> (InsertModalBody.js:57)
    at Array.forEach (<anonymous>)
    at InsertModalBody.getFieldValue (InsertModalBody.js:41)
    at InsertModal.__handleSave__REACT_HOT_LOADER__ (InsertModal.js:63)
    at InsertModal._this.handleSave (InsertModal.js:54)
    at InsertModalFooter.__handleSaveBtnClick__REACT_HOT_LOADER__ (InsertModalFooter.js:68)
    at InsertModalFooter._this.handleSaveBtnClick (InsertModalFooter.js:46)
    at Object.ReactErrorUtils.invokeGuardedCallback (ReactErrorUtils.js:69)
    at executeDispatch (EventPluginUtils.js:85)
    at Object.executeDispatchesInOrder (EventPluginUtils.js:105)
```

Real screenshot of component's code. 1) The method is never called. 2) It is never called whatsoever. Although the method exists in a component.

![google chrome 2017-07-03 05 48 03](https://user-images.githubusercontent.com/3880497/27773759-532bfe36-5fb3-11e7-8b93-47c7982e5df3.png)

Method in a component:

![google chrome 2017-07-03 05 55 22](https://user-images.githubusercontent.com/3880497/27773791-48ded592-5fb4-11e7-8093-813086c60c08.png)

**Comment by AllenFang** [comment]
@wzup, sorry for lately reply, busy on my job..

If you have any custom editor in insert modal, the component of custom editor should implement `getFieldValue` method and return the value if input, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/insert-modal/custom-insert-modal-field.js#L28-L30)

Let me know the problems is still remain, thanks

**Comment by DarMontou** [comment]
There's some likely unexpected behavior when using a [single custom insert modal field](http://allenfang.github.io/react-bootstrap-table/custom.html#insertmodalfield) if the value of the field is falsy, and the getFieldValue method is undefined.

```
inputVal = inputVal || dom.getFieldValue();
::=> "" || dom.getFieldValue();
::=> dom.getFieldValue()
::=> Uncaught TypeError: dom.getFieldValue is not a function
```

**Comment by AllenFang** [comment]
HI @DarMontou, you mean if you return `false` in `getFieldValue` function then got above error ?

**Comment by justbill2020** [comment]
i'm also having an issue with this. dom.getFieldValue() not a function

**Comment by Strateus** [comment]
same here

**Comment by Strateus** [comment]
It seems issue is related to redux connect, it works without it

**Comment by solace** [comment]
Using the example provided:
```
customSaleField = (column, attr, editorClass, ignoreEditable) => {
  /*
    In this case, you are suppose to be prodived a specific method name for
    react-bootstrap-table to get the value for this field.

    Notes:
    1. You are suppose to be implement getFieldValue function and return the value that user input
  */
  return (
    <SalesRadioField ref={ attr.ref } editorClass={ editorClass } ignoreEditable={ ignoreEditable }/>
  );
}
```
`attr.ref` is undefined which appears to be why this error occurs.

Any suggestions?

**Comment by AllenFang** [comment]
@solace, it work well for me,

**Comment by solace** [comment]
Well, it doesn't seem to according to the other people above. :)

**Comment by solace** [comment]
In any case, I was able to resolve by overriding the insert modal body. Copied the original and made modifications to the ref for custom fields.

https://gist.github.com/solace/b5f1fc3f1f632cb79bccc63ed7f49d1d
