### ISSUE TITLE
[customEditor] No documentation

### ISSUE THREAD

**Issue by wzup** [AllenFang/react-bootstrap-table#1439]
http://allenfang.github.io/react-bootstrap-table/docs.html#customEditor

![react bootstrap table - documents - google chrome 2017-07-02 21 55 26](https://user-images.githubusercontent.com/3880497/27770432-4bbef528-5f71-11e7-957e-1b3dfff49532.png)

**Comment by AllenFang** [comment]
I'll improve it if I have time, sorry it's busy for me, thanks
