### ISSUE TITLE
Sizing bugs in 1.2.11 tested in firefox

### ISSUE THREAD

**Issue by tbaeg** [AllenFang/react-bootstrap-table#144]
Line https://github.com/AllenFang/react-bootstrap-table/blob/f26449e97d6f71c8ea3f69902203d803a9332aba/src/TableColumn.js#L32 causes below error.

```
TypeError: this.props.width is undefined
Stack trace: [object Object]
```

Breaks when no width is specified. Should see if `this.props.width` is `falsey` instead of `!== null`.

Should also set `minWidth` for `TableColumnHeaders` at line https://github.com/AllenFang/react-bootstrap-table/blob/master/src/TableHeaderColumn.js#L27.

Height in `TableColumnHeader` is `42px` but each row is `46px`. Causes all columns to be incorrectly offset because of `input` element. Looking at fix.. going to start making fixes in my fork.

Looking into other issue as well... I hate `css`!

**Comment by tbaeg** [comment]
Sorry for all the bug report. :(

**Comment by AllenFang** [comment]
That's fine, you done a great job :)

**Comment by tbaeg** [comment]
Ah, I found a big one. A lot of the inline `style` objects are taking `widths` of type string, when it SHOULD be an `integer`. Fixed a lot of issues for me.

**Comment by AllenFang** [comment]
really? Is the body column width?

**Comment by tbaeg** [comment]
These are quick fixes I made to get some things working for my needed.

https://github.com/AllenFang/react-bootstrap-table/compare/master...tbaeg:master

`react` style object expects `integer` not `strings` for `width/maxWidth/minWidth`. :)

I passed int `width="200"` and now works as expected.

**Comment by AllenFang** [comment]
it's strange, because it's work in past on chrome(but I dont test it on firefox). so, style object excepts <code>integer</code> for width in all browser?

**Comment by tbaeg** [comment]
Yeah, looking at the docs seems that way!

https://facebook.github.io/react/tips/style-props-value-px.html

**Comment by AllenFang** [comment]
ok, I got you, but I dont know why it work in the past... ;(

**Comment by AllenFang** [comment]
Release in v1.2.13
