### ISSUE TITLE
How to use input type "date" instead of "datetime-local"

### ISSUE THREAD

**Issue by roslaneshellanoo** [AllenFang/react-bootstrap-table#1440]
**When choosing** 
editable={{ type: 'datetime' }}
**you have to add time too... e.g. Hours and minutes**

If you want to use only date?...it's a problem because if you choose only date in present datetime input, the value is empty. hence you have to choose minutes and hours also.

**How to create a date input without time?**

**Comment by AllenFang** [comment]
HI @roslaneshellanoo, sorry for lately reply, 

Although `react-bootstrap-table` document said that we support `datetime`, `checkbox`, `select` and `textarea` but you can still assign as `date`, we sill transfer any `editable.type` into input tag.  :)

`<TableHeaderColumn dataField='datetime' editable={ { type: 'date' } }>Date Time</TableHeaderColumn>`
