### ISSUE TITLE
iOS9 Safari

### ISSUE THREAD

**Issue by zeusbangayan** [AllenFang/react-bootstrap-table#1442]
Having issues on the following error.
TypeError: undefined is not an object (evaluating 'v.style.width')

<img width="677" alt="screen shot 2017-07-03 at 2 00 33 pm" src="https://user-images.githubusercontent.com/5523635/27779859-27c8c702-5ff8-11e7-82ab-de436e6b8bec.png">

**Comment by AllenFang** [comment]
@zeusbangayan, sorry for lately reply, please upgrade and try it again, feel free to discuss with me if the problems is still remains, thanks 👍
