### ISSUE TITLE
Please fix documentation on http://allenfang.github.io/react-bootstrap-table/start.html

### ISSUE THREAD

**Issue by MichalRemis** [AllenFang/react-bootstrap-table#1443]
If you follow steps on [http://allenfang.github.io/react-bootstrap-table/start.html ,](http://allenfang.github.io/react-bootstrap-table/start.html ) Table has misaligned header columns because of a typo on docs page:

```
#<link rel="stylesheet" **src**="https://npmcdn.com/react-bootstrap-table/dist/react-bootstrap-table-all.min.css">
</link>
```

src needs to be replaced with href

**Comment by AllenFang** [comment]
oh... it's my mistake, fixed it now 👍  thanks
