### ISSUE TITLE
Filter Options cant be changed?!

### ISSUE THREAD

**Issue by medianetic** [AllenFang/react-bootstrap-table#1445]
Hello,

i am trying to change the filter options depending on a state. I got the following code in my render method:

f(this.state.mode == "monthly") {
            var filter_options = {
                type: 'TextFilter', 
                defaultValue: myCurrentMonth,
            };
          } else {
            var filter_options = {
                type: 'TextFilter', 
                defaultValue: null,
            };
}

and in the return statement, i got my TableHeaderColumn defined like this:
`
<TableHeaderColumn headerAlign='center' row='0' rowSpan='2' width="0" dataField='monat' filter={filter_options} editable={ false } hidden>Monat</TableHeaderColumn>
`
The TableHeaderColumn always use the first defined value for defaultValue. This might be intended to be. but how can i change the filter options? Any Idea or workaround?

**Comment by AllenFang** [comment]
Sorry for lately reply and let me check this out, it might be a bug.

**Comment by AllenFang** [comment]
hello @medianetic, this bug was fixed on `v3.4.4`, please let me know if the problem still remain, thanks

**Comment by medianetic** [comment]
Hello @AllenFang 

unfortunately the problem still remain. For testing i've tried the following (in my render method):

         if(this.state.mode == "monthly") {
            var filter_options = {
                type: 'TextFilter', 
                defaultValue: myCurrentMonth,
            };
          } else {
            var filter_options = {
                type: 'TextFilter', 
                defaultValue: '09',
            };
          }

Now if the value of this.state.mode is not 'monthly' the table sets the filter to null (not as expected to '09')

**Comment by AllenFang** [comment]
@medianetic, could you please describe your reproduce step on UI?  I think this bug was fixed but maybe we're not in the same line for reproducing this issue, thanks
