### ISSUE TITLE
Custom insertRow in a modal 

### ISSUE THREAD

**Issue by kwekuboateng** [AllenFang/react-bootstrap-table#1447]
Please how do i add my own insertRow to the table from a custom modal. my new row will include text fields, numbe fields, upload image from pc

**Comment by AllenFang** [comment]
Sorry for lately reply @kwekuboateng, `react-bootstrap-table` support a lots of parts for customization on insert modal, check [here](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/custom/insert-modal)
But I think the custom field in insert modal will be best for you I guess, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/insert-modal/custom-insert-modal-field.js), feel free to discuss with me if you have any concern or questions, thanks 👍
