### ISSUE TITLE
Pagination resets to page 1 but data of another page shows after filter change

### ISSUE THREAD

**Issue by theGirrafish** [AllenFang/react-bootstrap-table#1449]
Whenever I change the filter, the data gets filtered and shows the proper data for the page that I am on, but the problem is that the pagination goes back to the first page. When I look at the page number, it says I am on page 4, yet the pagination shows 1.

![image](https://user-images.githubusercontent.com/16931654/27841612-03058e6c-60d1-11e7-8d03-d480a094371a.png)

**Comment by AllenFang** [comment]
how about show your example? **keep it simple and minimal**<<<<  it's very very important, I've no time to study your code but just focus on the problem. thanks

Some question, I want to know
1. is you enable `remote`?
2. how did you configure the `remote`, have you doing like [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-alternative.js#L9-L15)?
3. did you handle the pagination by yourself?

thanks
