### ISSUE TITLE
Can we control the data formatted to be called once for the first time?

### ISSUE THREAD

**Issue by sunnybogawat** [AllenFang/react-bootstrap-table#1454]
I am using dataFormat to format the table data. the format function has some external API call to get some value. When there is state change the component is re-render and my dateFormat is invoked again and again. is there any way that I can control the data format method so it would not call each time there is a state change

**Comment by AllenFang** [comment]
hey @sunnybogawat, we can control it but you can control it.

I think I have two solution for you
1. 
In you custom react component, you can only call the API in the `componentWillMount`

2.
Before render table, you can call the API and then feed into table.

Let me know if you have any concern, thanks
