### ISSUE TITLE
Find one bug for BootstrapTable.js.

### ISSUE THREAD

**Issue by athenaxing** [AllenFang/react-bootstrap-table#1456]
@AllenFang 
Hi, Allen
I have found one bug in componentWillReceiveProps function:

it will crash if the data is undefined here. Need to add condition code.
this.store.setData(nextProps.data.slice());

I have added this code in my projects.
 if (nextProps.data == undefined)    
        return;
      }
 this.store.setData(nextProps.data.slice());

**Comment by AllenFang** [comment]
@athenaxing, yes, but something you can avoid by following:
```js
<BootstrapTable data={ products || [] }
```
Thanks your PR, I'll check this out
