### ISSUE TITLE
selectrow properties previously working

### ISSUE THREAD

**Issue by laitang2000** [AllenFang/react-bootstrap-table#146]
Hi,

In version 1.2.7 the following code worked with the selectRowProp object. 

var Invoices = React.createClass({
    formatCurrency: function(cell, row){
        return '<i class="glyphicon glyphicon-gbp"></i> ' + cell.toFixed(2);
    },
    rowSelect: function(row, isSelected){
        // console.log(row);
        // console.log(isSelected);
    },
    render: function(){
        var products = [{
            id: 1,
            name: "Item name 1",
            price: 100
        },{
            id: 2,
            name: "Item name 2",
            price: 100
        }];
    var selectRowProp = {
                          mode: "checkbox",  //checkbox for multi select, radio for single select.
                          clickToSelect: false,   //click row will trigger a selection on that row.
                          bgColor: "rgb(238, 193, 213)",   //selected row background color
                          onSelect: this.rowSelect
                        };
    return (
        <BootstrapTable selectRow={selectRowProp} data={products} striped={true} hover={true}>
            <TableHeaderColumn dataField="id" isKey={true} dataAlign="center" dataSort={true}>Product ID</TableHeaderColumn>
            <TableHeaderColumn dataField="name" dataSort={true}>Product Name</TableHeaderColumn>
            <TableHeaderColumn dataField="price" >Product Price</TableHeaderColumn>
        </BootstrapTable>

    );
    }
});

But in version 1.2.11 I now get the following message "Uncaught TypeError: Cannot read property 'indexOf' of undefined"

**Comment by AllenFang** [comment]
Thanks, I'll spend some time to check it

**Comment by SunJang** [comment]
+1

**Comment by AllenFang** [comment]
Fix it on v1.2.12 :)

**Comment by laitang2000** [comment]
Awesome! :)))

**Comment by AllenFang** [comment]
Thanks for your finding and always keep this project on watching, feel free to report any problem :)

**Comment by laitang2000** [comment]
Thanks! Maybe when I get more experience with react I can help contribute to this great project ;)

**Comment by AllenFang** [comment]
That's great!

**Comment by SunJang** [comment]
Awesome!!
