### ISSUE TITLE
Is it possible to change format of csv column by csvFormatter

### ISSUE THREAD

**Issue by rashisinha** [AllenFang/react-bootstrap-table#1468]
Hi @AllenFang I have a table in which I am rendering an IPV6 hex address. These IP addresses are typically like :
20011100c00000000000000000000000
20011100000000000000000000000000
They are displayed correctly on browsers.
I have used exportCSV option in the table and csvFormat to download the data into csv. On downloading, the above ip addresses are converted to scientific notation in the csv. Excel formats the column as 'general' and displays as following:
20011100c00000000000000000000000 - it displays the whole data
20011100000000000000000000000000 - it displays in scientific notation as 2.00111E+31
I need to show the values as it is in the csv and NOT in scientific form
Is there any way by which we can explicitly set mime type or column type as string in csv through csvFormat or through any other property in table.
Thanks.

**Comment by AllenFang** [comment]
@rashisinha sorry for lately reply, I'll help to check this, thanks

**Comment by AllenFang** [comment]
@rashisinha sorry, I can not reproduce it, I use `20011100000000000000000000000000` as value and then export csv, but I still saw `20011100000000000000000000000000` in csv file

**Comment by AllenFang** [comment]
any update?
