### ISSUE TITLE
Deleted row still reflected in data

### ISSUE THREAD

**Issue by dinachewyp** [AllenFang/react-bootstrap-table#147]
I am creating an application where the user can edit the cell, add and delete row from the table and save the changes to DB. 
Editing the cell seem to update the state of data but deleting row does not seem to update the state of data. 
I tried to get the state of data using refs (this.refs.bootstrapTable.state.data) and somehow the rendered table and data do not match.

**Comment by AllenFang** [comment]
you can call <code>getTableData()</code> to get data if you dont enable pagination, if enable pagination , I can provide a method to get all table without page, becaue <code>getTableData()</code> just return the data which display on table

**Comment by dinachewyp** [comment]
I do not need pagination, so this is good enough.
Thanks!

**Comment by AllenFang** [comment]
gooood :)
