### ISSUE TITLE
Multicolumn search not working properly with formatted column data

### ISSUE THREAD

**Issue by carlosu4** [AllenFang/react-bootstrap-table#1471]
I have formatted some data into one of the columns of the table using format property following this mapping:

Source: Array of Objects
Destination: <span title={formattedData}>{formattedData}</span>

being the formattedData an string obtained using concat of one property of each object.

The problem is that _search function of TableDataStore is not able to look for complex items like that (neither the unformatted array nor the HTML span element). Any ideas on how to fix this problem?

**Comment by AllenFang** [comment]
> being the formattedData an string obtained using concat of one property of each object.

So seems like the final data displayed on table is a string which concat all the element in array, right?

so did you use the `dataFormat`?  if yes, please add `filterFormatted` on `TableHeaderColumn` which tell `react-bootstrap-table` to filter/search the formatted data instead of source data,

Following is an example, you can check it:
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/search-format-table.js

Thanks, let me know if I misunderstand your question 👍

**Comment by carlosu4** [comment]
Hi @AllenFang and thank you for fast response! It still not working since the output of `dataFormat` is not a string but an HTML element instead. In my case, what I have is `<span title={formattedData}>formattedData</span>`, so that a tooltip is displayed.

**Comment by AllenFang** [comment]
@carlosu4, sorry, could you explain your source data and show me the what data in the column and also  show me what actual text being display on table? thanks

**Comment by carlosu4** [comment]
@AllenFang i'm copying part of the code.

`formatCows(cows) {
    if (!cows) {
        return '';
    }

    const formattedCows = cows.map(cow => cow[COW_ID_COLUMN]).join(', ');

    return cows.length === 0 ? '' : <span title={formattedCows}>{formattedCows}</span>;
}`

Thank you very much for your time/help.

**Comment by carlosu4** [comment]
@AllenFang i'm copying part of the code.

`
formatCows(cows) {
    if (!cows) {
        return '';
    }

    const formattedCows = cows.map(cow => cow[COW_ID_COLUMN]).join(', ');

    return cows.length === 0 ? '' : <span title={formattedCows}>{formattedCows}</span>;
}
`

Thank you very much for your time/help.

**Comment by idoromm** [comment]
Is there any resolution for this?
Filtering by formatted does not work for me either.
