### ISSUE TITLE
Support for TSV

### ISSUE THREAD

**Issue by bryon-czoch** [AllenFang/react-bootstrap-table#1476]
I have been able to get the table to use the Tab separator instead of comma, but the file extension is still .csv  Is there any support (code example) of a TSV download?

**Comment by AllenFang** [comment]
@bryon-czoch, sorry we dont support the tsv file and I think no plan for this feature in near future, so PR is welcome. thanks

**Comment by bryon-czoch** [comment]
Some example code here:  https://gist.github.com/jogoodma/57e6297ff1fef0036f9afc0e76e595f7

Courtesy @jogoodma
