### ISSUE TITLE
search textbox width

### ISSUE THREAD

**Issue by choyalpramod** [AllenFang/react-bootstrap-table#1477]
Can you can define search width

**Comment by AllenFang** [comment]
You can custom it by yourself, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/search/default-custom-search-field.js#L29)

if you can custom it by class, is it ok for you? or do you want to configure it by `style` or some attribute?
Thanks

**Comment by choyalpramod** [comment]
Thanks

**Comment by AllenFang** [comment]
Let me know if you can achieve by attributes or class, thanks
