### ISSUE TITLE
pass column.attrs to  TableEditColumn

### ISSUE THREAD

**Issue by MekMed** [AllenFang/react-bootstrap-table#1478]
Actually, the column.attrs is not passed to the TableEditColumn class.
As consequence, when specifying 'colspan' for example, it is not add in the TableEditColumn.

Is it possible to add  column.attrs to the current TableEditColumn on's ?

Thx,

**Comment by AllenFang** [comment]
@MekMed, we have a PR is working on it https://github.com/AllenFang/react-bootstrap-table/pulls
But it only for `v4.0.0` but it still on beta.

**Comment by MekMed** [comment]
Ok, Good.
I'll wait for v4.0.0.
Thx for your work

Issue closed.

**Comment by AllenFang** [comment]
@MekMed this was fixed and released on [`v4.0.0-beta.8`](this PR was fixed and released on [`v4.0.0-beta.8](https://github.com/AllenFang/react-bootstrap-table/releases/tag/v4.0.0-beta.8), check [this commit](https://github.com/AllenFang/react-bootstrap-table/commit/a864f8241c6e3f6380d95f3d867e7e22822e42e5) to learn how to add your own attributes on editor, thanks

Let me know if you have any questions

**Comment by MekMed** [comment]
@AllenFang thanx for your fix. However, attributes are actually settled to the field inside the 'td' element. But, for the 'colspan', it must be settled to the 'td'. Is it possible to have an attribute 'tdAttr' like for the TableHeaderColumn ?

thx,

**Comment by AllenFang** [comment]
@MekMed sorry, I misunderstand your requirement, I will find some way to add attributes on `td`, thanks

**Comment by AllenFang** [comment]
@MekMed thi was fixed on `v4.0.0-beta.9`, use `editTdAttr` on `TableHeaderColumn` instead. Thanks

**Comment by MekMed** [comment]
@AllenFang It is working fine 👍 . Thx a lot for your work.

**Comment by AllenFang** [comment]
@MekMed thanks, BTW, `v4.0.0` has been released, you can check this 👍

**Comment by rajinikala** [comment]
Can some one post a usage of editTdAttr ? Much appreciated !!
