### ISSUE TITLE
Use 'isKey={true}' to specify a unique column. 

### ISSUE THREAD

**Issue by PavanRaj999** [AllenFang/react-bootstrap-table#1483]
I am using react-bootstrap-table table component. Event after having isKey in my My TableHeaderColumn am still getting error saying - "Uncaught (in promise) Error. No any key column defined in TableHeaderColumn. Use 'isKey={true}' to specify a unique column."

Below is my code

const TableComponent = (props) => {
  const { isKeyProp } = props
  const products = [
    {
      id: 1,
      name: 'Item name 1',
      price: 100,
    },
    {
      id: 2,
      name: 'Item name 2',
      price: 200,
    },
    {
      id: 3,
      name: 'Item name 3',
      price: 300,
    },
  ]
  return (
    <BootstrapTable data={products} keyField={uuidV4()} >
      <TableHeaderColumn dataField={products.id} isKey={isKeyProp} >Product Id</TableHeaderColumn>
      <TableHeaderColumn dataField={products.name} >Product Name</TableHeaderColumn>
      <TableHeaderColumn dataField={products.price} >Product Price</TableHeaderColumn>
    </BootstrapTable>
  )
}

TableComponent.propTypes = {
  isKeyProp: PropTypes.bool.isRequired,
}

TableComponent.defaultProps = {
  isKeyProp: true,
}
No clue why ..

**Comment by AllenFang** [comment]
use `keyField` on `BootstrapTable` will be recommendation, but you use it in wrong way, it should be the one of a `dataField` instead of a uuid value.

Also, please dont use `keyField` and `isKey` both, `react-bootstrap-table` does know which it should take it.
