### ISSUE TITLE
Apply NumberFilter to formatted data column

### ISSUE THREAD

**Issue by HamzaApache** [AllenFang/react-bootstrap-table#1485]
Hi,

I have a table with a filter on a column that contains not a float values ​​but a react component that displays the float values.
The filter does not work with this formatData.
I would like to know if there is a way to apply the filter to the value that is in the React component.

Attached an image of my table.
The column I'm talking about is "Sentiment"
![table](https://user-images.githubusercontent.com/20092544/28273734-604a9ab6-6b0f-11e7-8e42-56bd6e7089c9.PNG)

**Comment by AllenFang** [comment]
@HamzaApache try to use `filterFormatted` on `TableHeaderColumn`, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/search-format-table.js#L52) example


And please let me know if there's any question or it doesn't work, thanks
