### ISSUE TITLE
search

### ISSUE THREAD

**Issue by choyalpramod** [AllenFang/react-bootstrap-table#1489]
Hello Allen,

I have a local/non-remote json data which has many columns but i have defined few columns in header, when i tried searching data those fields i have not mentioned in headers such data is not searched. I want it to search from my whole data not just viewed data.

**Comment by AllenFang** [comment]
@choyalpramod two solution
First is just put all the columns on table but hide them. but it may have some,
Second is you do the search function by yourself then update the table.

I think theres no any magic :)
