### ISSUE TITLE
Server side rendering and filesaver.js

### ISSUE THREAD

**Issue by staminaloops** [AllenFang/react-bootstrap-table#149]
Hi @AllenFang 
I'm using SSR on my project, and had some problems with filesaver.js

I fixed it in my fork, it will only load filesaver on the browser bundle.
Check it here: https://github.com/staminaloops/react-bootstrap-table/commit/e4c134a9e20dd7ebeaefa82dc3292634c3816d88#diff-3602ea699cf9dc846a0e23263aecf3b0

If you agree, I can do a pull request.

Cheers :)

**Comment by AllenFang** [comment]
@staminaloops, you did a great job, thanks a lots. Feel free to make PR :)
