### ISSUE TITLE
ExpandRow Column width is not working... 

### ISSUE THREAD

**Issue by patelroshan27** [AllenFang/react-bootstrap-table#1491]
Hello,

ExpandRow Column width is not working... 
Parent Table Header and width are fine, but not nested table exapandRow width not working... i tried setting up width by %, but it does not work when i resize window. 
also add, react-bootstrap-table.min.css from react-bootstrap-table.

Please help..

**Comment by patelroshan27** [comment]
also how to set width exactly as parent table header/column width?

**Comment by patelroshan27** [comment]
/* eslint max-len: 0 */
import React from 'react';
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';
import {Link} from 'react-router-dom';


const products = [];

function addProducts(quantity) {
  const startId = products.length;
  for (let i = 0; i < quantity; i++) {
    const id = startId + i;
    if (i < 3) {
      products.push({
        id: id,
        name: 'sub' + id,
        price: 2100 + i,
        id1: id,
        name1: 'sub' + id,
        price1: 2100 + i,
        expand: [ {
          id: id,
          name: 'sub' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i
        }, {
          id: id,
          name: 'sub' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i
        }, {
          id: id,
          name: 'sub' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i
        }, {
          id: id,
          name: 'sub' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i
        } ]
      });
    } else {
      products.push(
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
        {
          id: id,
          name: 'data' + id,
          price: 2100 + i,
          id1: id,
          name1: 'sub' + id,
          price1: 2100 + i,
        },
      {
        id: id,
        name: 'data' + id,
        price: 2100 + i,
        id1: id,
        name1: 'sub' + id,
        price1: 2100 + i,
      }
    );
    }
  }
}
addProducts(5);

class BSTable extends React.Component {
  render() {

    if (this.props.data) {

      var height = this.props.data.length * 37;

      return (
        <BootstrapTable height={height} tableHeaderClass={"col-hidden"}   bordered hover  data={ this.props.data } >
          <TableHeaderColumn width='43.5px' ></TableHeaderColumn>
          <TableHeaderColumn width='16.32%'  dataSort dataField='id' isKey={ true }></TableHeaderColumn>
          <TableHeaderColumn width='16.4059%'  dataSort dataField='name'></TableHeaderColumn>
          <TableHeaderColumn width='16.32%'  dataSort dataField='price'></TableHeaderColumn>
          <TableHeaderColumn width='16.32%'  dataSort dataField='id1' ></TableHeaderColumn>
          <TableHeaderColumn width='16.28%'  dataSort dataField='name1'></TableHeaderColumn>
          <TableHeaderColumn width='16.32%'  dataSort export={ true } dataField='price1'></TableHeaderColumn>
        </BootstrapTable>);
    } else {
      return (<p>?</p>);
    }
  }
}

export default class ExpandRow extends React.Component {
  constructor(props) {
    super(props);
  }

  isExpandableRow(row) {
    if (row.expand) return true;
    else return false;
  }

  expandComponent(row) {
    return (
      <BSTable data={ row.expand } />
    );
  }

  expandColumnComponent({ isExpandableRow, isExpanded }) {
    var content;

    if (isExpandableRow) {
      content = (isExpanded ? <span  className='glyphicon glyphicon-minus-sign' ></span> : <span className='glyphicon glyphicon-plus-sign' ></span> );
    } else {
      content = ' ';
    }
    return (
      <div style={{textAlign:'center', paddingTop : '10px'}}> { content } </div>
    );
  }

  renderShowsTotal(start, to, total) {
      return (
        <p style={ { color: '#337ab7' } }>
          Showing { start } to { to } of { total } records
        </p>
      );
    }

    goToCustomerProfile = (cell, row) => {
        return (
          <Link to='/viewProfile'>
            {cell}
          </Link>
        )
      }

      goToOptions = (cell, row) => {
          return (
            <div  role="group" >

              <Link to='/report' width="100px"  className="btn btn-info " style={{width:'48%', marginRight: '5px'}}  role="button" >
                <span className='glyphicon glyphicon-list' />&nbsp;&nbsp;Report
              </Link>

              <Link to='/viewProfile' className="btn btn-info" style={{width:'48%'}} role="button">
                  <span className='glyphicon glyphicon-blackboard' />&nbsp;&nbsp;Monitor
              </Link>
            </div>
          )
        }


  render() {


    const options = {
            expandRowBgColor: 'white',
            page: 1,  // which page you want to show as default
            sizePerPageList: [ {
              text: '20', value: 20
            }, {
              text: '30', value: 30
            }, {
              text: 'All', value: products.length
            } ], // you can change the dropdown list for size per page
            sizePerPage: 20,  // which size per page you want to locate as default
            pageStartIndex: 1, // where to start counting the pages
            paginationSize: 20,  // the pagination bar size.
            prePage: 'Prev', // Previous page button text
            nextPage: 'Next', // Next page button text
            firstPage: 'First', // First page button text
            lastPage: 'Last', // Last page button text
            paginationShowsTotal: this.renderShowsTotal,  // Accept bool or function
            paginationPosition: 'bottom'  // default is bottom, top and both is all available
            // hideSizePerPage: true > You can hide the dropdown for sizePerPage
            // alwaysShowAllBtns: true // Always show next and previous button
            // withFirstAndLast: false > Hide the going to First and Last page button

    };
    return (
      <BootstrapTable id='parentTable' striped bordered condensed hover  data={ products } pagination
        headerStyle={ { paddingTop : '10px', paddingBottom : '10px', backgroundColor: '#337ab7', color : 'white' } }
        options={ options }
        expandableRow={ this.isExpandableRow }
        expandComponent={ this.expandComponent }
        expandColumnOptions={ {
          expandColumnVisible: true,
          expandColumnComponent: this.expandColumnComponent,
          columnWidth : '50px'

        } }>
        <TableHeaderColumn tdStyle={{paddingTop : '12px', paddingBottom : '12px'}} dataSort dataField='id' isKey={ true }>File ID</TableHeaderColumn>
        <TableHeaderColumn tdStyle={{paddingTop : '12px', paddingBottom : '12px'}} dataSort dataField='name' dataFormat={ this.goToCustomerProfile } >Customer Name</TableHeaderColumn>
        <TableHeaderColumn tdStyle={{paddingTop : '12px', paddingBottom : '12px'}} dataSort dataField='price'>Received</TableHeaderColumn>
        <TableHeaderColumn tdStyle={{paddingTop : '12px', paddingBottom : '12px'}} dataSort dataField='id1' >Status</TableHeaderColumn>
        <TableHeaderColumn tdStyle={{paddingTop : '12px', paddingBottom : '12px'}} dataSort dataField='name1'>File Name</TableHeaderColumn>
        <TableHeaderColumn dataSort dataField='price1' dataFormat={ this.goToOptions }>Options</TableHeaderColumn>

      </BootstrapTable>
    );
  }
}

**Comment by AllenFang** [comment]
sorry, could you review your example code and make it easy to check? it's too hard to saw your example...

**Comment by patelroshan27** [comment]
[index.zip](https://github.com/AllenFang/react-bootstrap-table/files/1181807/index.zip)

I have 2 questions,
How to set width for child table columns exactly as parent table columns?
how to set extra property like formatExtraData to below functions?
expandableRow={ this.isExpandableRow }
expandComponent={ this.expandComponent }

I am using the same data, products, to create Nested row tables as attached.  I want to create nested row dynamically, so based on json property name='expand', table should create sub table.  I want to pass that json property('expand') to isExpandableRow and expandComponent functions.  

NestedRowTable code is attached. Usage of attached custom component as below.

    const products = [];

    function addProducts(quantity) {
      const startId = products.length;
      for (let i = 0; i < quantity; i++) {
        const id = startId + i;
        if (i < 3) {
          products.push({
            id: id,
            customerName: 'sub' + id,
            received: 2100 + i,
            status: id,
            fileName: 'sub' + id,
            options: 2100 + i,
            expand: [ {
              id: id,
              customerName: 'sub' + id,
              received: 2100 + i,
              status: id,
              fileName: 'sub' + id,
              options: 2100 + i,
            }, {
              id: id,
              customerName: 'sub' + id,
              received: 2100 + i,
              status: id,
              fileName: 'sub' + id,
              options: 2100 + i,
            }]
          });
        } else {
          products.push(
            {
              id: id,
              customerName: 'sub' + id,
              received: 2100 + i,
              status: id,
              fileName: 'sub' + id,
              options: 2100 + i,
            },
            {
              id: id,
              customerName: 'sub' + id,
              received: 2100 + i,
              status: id,
              fileName: 'sub' + id,
              options: 2100 + i,
            }
        );
        }
      }
    }
    addProducts(10);

    var fields = [
        {id: 'id', name: 'ID', 'isKey': true},
        {id: 'customerName', name: 'Customer Name', 'dataLink' : '/viewProfile'},
        {id: 'received', name: 'Received'},
        {id: 'status', name: 'Status'},
        {id: 'fileName', name: 'File Name'},
        {id: 'options', name: 'Options', 'optionLinks' : ['/report','/monitor']}
    ]

`<NestedTable data={products} fields={fields}  />`

**Comment by patelroshan27** [comment]
![image](https://user-images.githubusercontent.com/30273229/28699846-04af26be-731a-11e7-9600-3bfcef9d9050.png)

Above is a screenshots for mismatched column width for parent and child tables.

**Comment by patelroshan27** [comment]
I found a way to pass extra param to functions.  Only problem now is setting width to child table.  

Please help.

**Comment by AllenFang** [comment]
@patelroshan27, `react-bootstrap-table` only can configure the `height` for table.
The workaround is in your `BSTable`, use a div to wrap `BootstrapTable` and configure the width on that `div`.
