### ISSUE TITLE
[question] Press enter to save cell value on textarea mode

### ISSUE THREAD

**Issue by hdl-helsinki** [AllenFang/react-bootstrap-table#1492]
Is it possible to save a cell value on textarea mode by pressing a key? 

I can't see any example on [the docs](https://allenfang.github.io/react-bootstrap-table/example.html#celledit).

Thank you.

**Comment by AllenFang** [comment]
@hdl-helsinki sorry, we dont support this feature, but PR is welcome.

BTW, there's a workaround for you if you really want to press `ENTER` to save the cell, the solution is you can custom the cell editor, I think it's easy to do, just custom a `textarea` and manage the event for `ENTER`

[This](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/cell-edit/custom-cell-edit-table.js) is example for learning custom cell editor, let me know if you need any support or questions, thanks

**Comment by hdl-helsinki** [comment]
Thank you @AllenFang
