### ISSUE TITLE
[Bundle size] Increase in size due to react-toaster

### ISSUE THREAD

**Issue by prajapati-parth** [AllenFang/react-bootstrap-table#1493]
Hi @AllenFang 
Recently I've been observing the production bundle of my app using webpack-bundle-analyzer.

I imported the css which didn't use react-toastr still I'm seeing react-toastr occupying quite a size of the bundle. Is there a way to skip importing react-toastr? 

Including screenshots for your reference:
1) zoomed-out view
![pasted image at 2017_07_19 05_29 pm](https://user-images.githubusercontent.com/17194534/28366217-67ce017e-6ca9-11e7-9735-9c3c929ce8f6.png)

2) zoomed-in view to react-toastr
![pasted image at 2017_07_19 05_29 pm 1](https://user-images.githubusercontent.com/17194534/28366191-434bbed6-6ca9-11e7-9c77-6ece82abf14a.png)

Thanks! :+1:

**Comment by AllenFang** [comment]
@prajapati-parth nice question, this is known issue lol
Check https://github.com/AllenFang/react-bootstrap-table/pull/1216#issuecomment-296675731

Anyway, for now, it's impossible to remove those dependencies, in `v3.x` we use `react-toastr`, in `v4.x` we use `react-s-alert`. Like I mention above, I should avoid to use those library directly in this repo, if it really necessary, we should use it like a plugin or HOC or let developer to control the third-party library.

I'm planing the `react-bootstrap-table2` for the refactoring the table structure and code base, but currently it is still in the plan and really need some time. 

it's very sorry that we can fix this issue in near future.

**Comment by prajapati-parth** [comment]
I'm sure @AllenFang v4.x would be great! One more thing here. 

I was using this library `react-burger-menu` that had external dependency on some svg thing that was occupying considerable size in my bundle and I just followed [this](https://github.com/negomi/react-burger-menu/issues/152#issuecomment-298148268) to reduce the size by 83KB. 

Basically if I would have done something like this
```jsx
import { push as Menu } from 'react-burger-menu'
```
all the default dependencies would have pulled in.

So I followed the above mentioned comment and got size reduced quite much. Would something like that be possible in my imports of react-bootstrap-table? 

Thanks!

**Comment by AllenFang** [comment]
@prajapati-parth thanks your sharing, I think we can't do it like that

**Comment by prajapati-parth** [comment]
@AllenFang All right.
Thanks for considering it as enhancement.

**Comment by AllenFang** [comment]
I will, but like I mention, I wont fix in `react-bootstrap-table`. In my plan, if `react-bootstrap-table2` is available for me, I will do this enhancement in 2. Because reduce the bundle size in this package is  too hard sometime.  Thanks 👍
