### ISSUE TITLE
[Footer] Help need to fix scrolling of footer

### ISSUE THREAD

**Issue by prajapati-parth** [AllenFang/react-bootstrap-table#1496]
Hi @AllenFang,
I'm trying to create my own footer for react-bootstrap-table. I see that the `<thead>` and `<tbody>` are created in two different table and have already gone through #738 .

I'm stuck at a place where I need to scroll the footer according to the `<thead>` and `<tbody>`. Can you please help me and point me in your code where this is done?

Note: I've tried implementing #554 and #1190 but none of them scroll along. 

Thanks again.

**Comment by AllenFang** [comment]
@prajapati-parth, I think it's hard to implement it now in the `react-bootstrap-table`, particular you need to fix the footer.

I think if you want to fix the footer in the end, check the html structure of `react-bootstrap-table`
you will see it is construct by two div, most like:

```html
<div>
   <div><table><thead>...</thead></table></div>   <!-- HEADER -->
   <div><table><tbody>...</tbody></table></div>   <!-- BODY   -->
</div>
```

you can add another  `div` in [here](https://github.com/AllenFang/react-bootstrap-table/blob/master/src/BootstrapTable.js#L464) and make the html like

```html
<div>
   <div><table><thead>...</thead></table></div>   <!-- HEADER -->
   <div><table><tbody>...</tbody></table></div>   <!-- BODY   -->
   <div><table><tfooter>...</tfooter></table></div>   <!-- FOOTER   -->
</div>
```
Let me know if you have any consideration or questions.

**Comment by prajapati-parth** [comment]
Thanks @AllenFang. In my efforts, I'm currently doing the same! 
I'll try it up, may be send a PR if my code matches the standards.

**Comment by prajapati-parth** [comment]
@AllenFang I created a structure just like you suggested, but still I'm unable to get a hold on the footer's scroll. It would be really great if you could guide me a little here.
