### ISSUE TITLE
Hi, I have a question regarding the delete button

### ISSUE THREAD

**Issue by swli5** [AllenFang/react-bootstrap-table#1498]
Hi, I have a question regarding the delete button of react-bootstrap-table. The delete function on the official document is to have one single delete button sitting somewhere on the page, and have users select the row they want to delete, and click the delete button, and delete one row at a time.

Is there a way to put the delete button by the end of each row, and have users click them to delete corresponding rows?

Thank you

**Comment by AllenFang** [comment]
> Is there a way to put the delete button by the end of each row, and have users click them to delete corresponding rows?

You can achieve it directly by `react-bootstrap-table` supporting, but you can custom it

1, add extra column and use `dataFormat`  to custom the cell for adding a delete button
2. when click the button, call the API or update the table state.

Let me know if you have any trouble on implementation :)
