### ISSUE TITLE
PropTypes Warning

### ISSUE THREAD

**Issue by wallena3** [AllenFang/react-bootstrap-table#1499]
We can notice this warning in console:  

Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

May should update the source code now .

Great project! Many thanks to the author.

**Comment by actraiser** [comment]
I see this warning again since upgrading to 4.0.0-beta.8. I am pretty sure this was no issue in 4.0.0-beta.6. 

-act

**Comment by AllenFang** [comment]
Yes, I'll fix it on `v4.0.0-beta.9`, sorry for inconvenience.
