### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by mfirry** [AllenFang/react-bootstrap-table#15]
Would it be possible to set css classes for particular `td`? Say I want amounts to always be bold or something

**Comment by AllenFang** [comment]
Hi @mfirry, you mean the <code>td</code> in header or body or both?

**Comment by mfirry** [comment]
I need it for the body right now. Thanks!

**Comment by AllenFang** [comment]
Hi @mfirry you can use the "cell format" for your purpose

**Comment by mfirry** [comment]
You're right! Completely missed that. Sorry! Thank you so much!

**Comment by AllenFang** [comment]
Sorry, maybe there are some misunderstanding. Cause of the "cell format" use the custom format and wrap that with <code>td</code>, So cell format can't apply the style on <code>td</code>, just only on the inner element that you provide.

**Comment by mfirry** [comment]
Yep, you're right. But luckily that was good enough for me. The ability to actually style the `td` would be an enhancement, I agree.

**Comment by AllenFang** [comment]
Great!, in the future, I'll add the ability for styling <code>td</code>. Thanks for your suggestion.

**Comment by markmus** [comment]
Hi @AllenFang how can I remove the inline style width in the table header for responsive and display the sorting icons (caret) by default?

```
<div class="table-header" data-reactid=".0.0.1.1.1.2.$0.0.1.0">
<table class="table table-hover table-bordered" data-reactid=".0.0.1.1.1.2.$0.0.1.0.0" style="width: 1842px;"></table>
</div>
```
I also try to use `'sortName'` and `'sortOrder'` but its not working. I currently using `"react-bootstrap-table": "^0.9.10"`

Thanks for help.

**Comment by AllenFang** [comment]
Hi @markmus , I open two issues for your problem, plz reference :)

about removing header width, cause of <code>react-bootstrap-table</code> will set a fix with by browser with after rendering, I'll try to remove this function for fixing your problem. But maybe it does not work.

another, could you give me the default sorting sample code? because I think there's no any problem. 

Thanks:)

**Comment by markmus** [comment]
@AllenFang 

Here is my code

Variables
```
    let listOperator = {
      "operators": [
        {
          "creator": "TEST_USER",
          "created": "2015-08-14T05:37:35",
          "modifier": "TEST_USER",
          "name": "dbm",
          "modified": "2015-08-14T05:37:35",
          "links": [
            {
              "method": "GET",
              "rel": "self",
              "href": "http://localhost:8080/api/operators/55da7bd03411511f7a0a6351"
            }
          ]
        },
        {
          "creator": "TEST_USER",
          "created": "2015-08-27T07:21:13",
          "modifier": "TEST_USER",
          "name": "ABCDEFG",
          "modified": "2015-08-27T07:21:13",
          "links": [
            {
              "method": "GET",
              "rel": "self",
              "href": "http://localhost:8080/api/operators/55deba6940faef1b3adf3203"
            }
          ]
        }
      ]
    }
```

Table
```
<BootstrapTable data={listOperator.operators} sortName={ 'name' } sortOrder={ 'asc' } striped={ true } bordered={ true } condensed={ true } hover={ true } styles={ tableStyle }>
    <TableHeaderColumn dataField="name" dataAlign="center" isKey={ true }  dataSort={true}> Operator </TableHeaderColumn>
    <TableHeaderColumn dataField="creator" dataAlign="center" dataSort={true}> Group/Owner </TableHeaderColumn>
    <TableHeaderColumn dataField="created" dataFormat={ this.dateFormatter } dataAlign="center" dataSort={true}> Date Added </TableHeaderColumn>
    <TableHeaderColumn dataField="modified" dataFormat={ this.dateFormatter } dataAlign="center" dataSort={true}> Date Modified </TableHeaderColumn>
    <TableHeaderColumn dataField="links.href" dataFormat={ this.actionFormatter } dataAlign="center" dataSort={true}> Actions </TableHeaderColumn>
</BootstrapTable>
```

I also try `sortName='name' sortOrder='asc'` and it doesnt work as well.

**Comment by kevinduffey** [comment]
Is there any way to set the color of an entire row (or even a single cell) based on some data matching criteria? I want to use striped still, but I also want it so that if a certain cell data is of a value, I highlight the cell, column or row, such that I may have several successive rows highlighted to the color I indicated.

**Comment by AllenFang** [comment]
HI @kevinduffey , your requirement is great but currently this component does not support these feature, maybe I'll implement in future. If you really want, you can customize self component base this component. :)

**Comment by kevinduffey** [comment]
So it turns out there IS a way to do it with your component right now.. although I am now moving away from bootstrap altogether. You basically just have the style= call a function that then checks the value of the cell/row... since the cell is the data of the cell, and the row is the entire object being iterated, its possible to check the row specific data against another value, and from that change the style applied tot he cell. The only downer is its on a per cell basis, instead of the full row.

**Comment by AllenFang** [comment]
yeah, you are right, I think it it not hard to add your requirement to this component, but in my opinion, the priority of this requirement is much lower than others, cause of this feature is a much customize function for me. So my answer is:

1. you can customize this component.

2. if you want to change column style, you can set class on <code>TableHeaderColumn</code>, the class you assign will be bring to each column in table body.

**Comment by markmus** [comment]
@AllenFang  is there any way to add a className on the table so i could style the `table`, `td` and `tr` ?

**Comment by AllenFang** [comment]
HI @markmus just give the <code>className</code> to <code>BootstrapTable</code> for <code>table</code> and <code>TableHeaderColumn</code> for <code>td</code>. But <code>tr</code> does not support currently.

**Comment by AllenFang** [comment]
Hi All, use <code>trClassName</code> on <code>&lt;BootstrapTable&gt;</code> to add your css class name on row(tr)

and use <code>columnClassName</code> on <code>&lt;TableHeaderColumn&gt;</code> to add your css calss name on column(td)

finally, use <code>classname</code> on <code>&lt;TableHeaderColumn&gt;</code> to add your css calss name on header

**Comment by M3lkior** [comment]
And what about ```<table>``` element class ?

**Comment by RickiWeb** [comment]
Hi @AllenFang , it's the first time that i use rect boostrap tabel and i have this problem :/ 

and i'm sure that i import the right css style :/ :/ can you help me please ?

![image](https://cloud.githubusercontent.com/assets/25333016/22268405/bd444f66-e287-11e6-89e9-a60490487b5a.png)

**Comment by AllenFang** [comment]
@RickiWeb, I thought you load the css of `react-bootstrap-table` fails absolutely, maybe you can check on the network panel in chrome dev tool.

**Comment by RickiWeb** [comment]
i load this script : 
"<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>"
Can you help me please !

**Comment by RickiWeb** [comment]
i load this scripts : 
"<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
 <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"/>"
Can you help me please !

**Comment by AllenFang** [comment]
@RickiWeb, is [this](https://github.com/AllenFang/react-bootstrap-table#cimport-css)

**Comment by RickiWeb** [comment]
Absolutely, i got this error exactly like you said, what should i do now please ?
![image](https://cloud.githubusercontent.com/assets/25333016/22353618/a9588ad0-e421-11e6-86b5-7151767aa54b.png)

**Comment by AllenFang** [comment]
I have no idea about that, it's means the css file does not exist on your server or a wrong path, just check it out.

**Comment by RickiWeb** [comment]
ok, thanx !

**Comment by KseniyaT** [comment]
Hello!
Maybe somebody had a problem with className for selectRow prop?

Code is like that:
```
    const selectRowProp = {
      mode: 'checkbox',
      clickToSelect: true,
      className: 'custom-select-class',
      onSelect: this.handleRowClick,
      onSelectAll: this.handleCheckboxAllClick
    };
<BootstrapTable data={sitesList} selectRow={selectRowProp}>...</BootstrapTable>
```
and I do not have 'custom-select-class' anywhere.

**Comment by AllenFang** [comment]
@KseniyaT, upgrade your version and try again, `custom-select-class` will only be added when row was selected.

**Comment by Eashwarswamy** [comment]
Hi AllenFang,
I was refering to above comments ('use trClassName on <BootstrapTable> to add your css class name on row(tr)') but 'trClassName' is not adding the class to <tr>

Below is sample code

<BootstrapTable  trClassName="ag-header">
</BootStrapTable>

 and Using the Version

"react-bootstrap-table": "^3.4.6" 

Is there any alternative, could you please help me on this
