### ISSUE TITLE
can not put dropdown properly.

### ISSUE THREAD

**Issue by parth2495** [AllenFang/react-bootstrap-table#1500]
Hi Allen,
I had a project in which i have to put dropdown in one whole column but it dropdown is not possible because of table.

And i also can not differentiate values of dropdown based on row.

**Comment by prajapati-parth** [comment]
@parth2495 Please consider using [this](http://allenfang.github.io/react-bootstrap-table/example.html#column-format) example. Note the second example here `Column Format with React`. You can pass dropdown jsx as required. 
Thanks.

**Comment by AllenFang** [comment]
Thanks @prajapati-parth 's answer 👍   @parth2495 let me know if you still have questions, thanks

**Comment by parth2495** [comment]
Hey,

I was talking about something else.

Can you please check screenshot.
![untitled](https://user-images.githubusercontent.com/11635474/28515034-cd30de8c-7079-11e7-877a-a6e7bf739751.png)

**Comment by AllenFang** [comment]
https://github.com/AllenFang/react-bootstrap-table/issues/530
