### ISSUE TITLE
Update button with own custom form

### ISSUE THREAD

**Issue by EmmaHansson** [AllenFang/react-bootstrap-table#1503]
I would like to add 'UPDATE' button with my own custom edit form. It should work for  all table (for example batch update).
And it could be very nice if it possible to locate next to exportToCsv or New or Delete buttons.

Is that possible?

**Comment by thundermiracle** [comment]
I think it can be done by customizing the search panel.
like this example:
https://gist.github.com/AllenFang/258cdfa92d6ce36a4d22ffd8b2aea17e#file-custom-search-panel-1-jsx
