### ISSUE TITLE
Unknown react install found

### ISSUE THREAD

**Issue by prajapati-parth** [AllenFang/react-bootstrap-table#1506]
@AllenFang I'm using a local fork of the great REACT-BOOTSTRAP-TABLE. :slightly_smiling_face:  From what I see in [webpack.umd.config.js](https://github.com/AllenFang/react-bootstrap-table/blob/master/webpack.umd.config.js), you have react and react-dom specified in externals still installing it locally in my another project it shows me **extraneous** dependency of react within my project. 

Using the command `npm ls react` shows output
![error](https://user-images.githubusercontent.com/17194534/28524767-7af0330e-709f-11e7-8b56-77894797502c.png)

This is showing duplicate react error in the browser console. 
I'm not sure what's causing the error here, but recently today I pulled upstream from your repo. Could this be related to react-bootstrap-table in any case? 
```
npm version: 5.3.0
react-version: 15.6.1
```

**Comment by prajapati-parth** [comment]
Well @AllenFang this seems to be an issue on my end and the library works as required :+1: . I learned that the **externals** config in webpack.umd.config.js prevents bundling react and moreover you've perfectly specified **react** as a peerDependency in package.json. 

Cheers to that :beers:. Closing this out.

**Comment by AllenFang** [comment]
:beers:
