### ISSUE TITLE
Two row headers

### ISSUE THREAD

**Issue by colino** [AllenFang/react-bootstrap-table#151]
Hi,
new version of rbt is very good but i found this problem: header row is duplicated 

![reactbootstraptable_twoheaders](https://cloud.githubusercontent.com/assets/4049806/11373656/7fd1d662-92d3-11e5-8de9-42e409f83052.png)

what's wrong?

**Comment by AllenFang** [comment]
You need re-import the css file :)

**Comment by colino** [comment]
great! thanks for your availability :D

**Comment by AllenFang** [comment]
:+1:

**Comment by Alfafc** [comment]
Sorry, but I dont get it or it is not working for me.

What do you mean with "re-import" your css file? 
I got this lines in my app.css and I am sure they are finally getting inside the app.css:

@import '../node_modules/react-bootstrap-table/css/react-bootstrap-table-all.min.css';
@import '../node_modules/react-bootstrap-table/css/toastr.css';

Any clue?

**Comment by AllenFang** [comment]
@Alfafc, if you upgrade <code>react-bootstrap-table</code>, remember to import newest css again.
If two header exist, means the css does not include to page. you can use chrome developer tools to check it(F12)

**Comment by Alfafc** [comment]
Thanks @AllenFang!!

I was messing it up with WebPack and the CSS classnames were redefined by it, so obviously, it wont work. Now I solve it. Thanks!

**Comment by AllenFang** [comment]
@Alfafc, good job :)
