### ISSUE TITLE
Paginator align issues v.3.4.6

### ISSUE THREAD

**Issue by olaputin** [AllenFang/react-bootstrap-table#1510]
I'm using react-bootstrap-table v.3.4.6 and bootstrap v.4.0.0-alpha.6. 
And when I trying to use pagination I have the following align issue: 

![image](https://user-images.githubusercontent.com/1963469/28584723-6bb2c91a-7176-11e7-9ef2-ba80628f7208.png)

CSS I've added in webpack config.

**Comment by naldorp** [comment]
hey, 
I'm having the same problem. I checked the source code and it seems like there's a "div" that breaking the layout. 

![image](https://user-images.githubusercontent.com/7239553/28585694-6d6c6650-7147-11e7-93e2-805b5a5b48a7.png)

I remove it from the source code and it worked, but someone need submit a PR with this fix.

**Comment by olaputin** [comment]
Thanks a lot, it solved my issue. You are the best :)

**Comment by AllenFang** [comment]
I'll fix it in near future, thanks for bug report.

**Comment by AllenFang** [comment]
Fixed on `v3.5.0`. thanks
