### ISSUE TITLE
Page count selector doesnt hide when out of focus

### ISSUE THREAD

**Issue by meghnaraok** [AllenFang/react-bootstrap-table#1521]
When the drop down that shows the page size is clicked it opens up a menu, when we click anywhere outside the menu doesnt hide and remains open.

**Comment by AllenFang** [comment]
what browser you used? can you check [this](https://allenfang.github.io/react-bootstrap-table/example.html#pagination) example ?! In addition, what version of bootstrap you used? Thanks

**Comment by meghnaraok** [comment]
Thanks, That got fixed by adding jquery. However I have one more issue. Say a user clicks on the count drop down a menu pops up and then user clicks else where on the page the menu disappears. When a user re clicks on the count drop down the drop down doesnt show up. Clicking another time brings up the menu. I see that this issue exists even on the examples page.
