### ISSUE TITLE
How do I make the server pagination to show less?

### ISSUE THREAD

**Issue by ttran94** [AllenFang/react-bootstrap-table#1522]
![screen shot 2017-07-31 at 6 31 37 pm](https://user-images.githubusercontent.com/16868949/28805390-81ea2fb4-761e-11e7-915a-406b0babf059.png)
My remote pagination is showing everything. How do I limit them like the default pagination does?
this is my options
`
`
options: {
   hideSizePerPage: true,
   page: 1,
   sizePerPage: 25,
   onSearchChange: this.searchChange.bind(this),
   onPageChange: this.pageChange.bind(this),
   paginationSize: 30
}
`
`

**Comment by AllenFang** [comment]
@ttran94 sorry for lately reply, try to use `options.paginationSize` and assign a quantity which you want to limit. Let me know if this configuration doesn't help you, thanks
