### ISSUE TITLE
Programmatically trigger search (from another element)

### ISSUE THREAD

**Issue by joshuaja** [AllenFang/react-bootstrap-table#1525]
Firstly, thanks so much for the great library!

I have multiple Tables in a view (each table contains a user's data) and would like to have a text input that is at the top of the page trigger a global search within all of the Tables.

Column filtering would not work in this case because they need the ability to search for anything across columns.

Is there a way to programmatically do this? I've been working with the API and through the examples but so far haven't found a way to do so.

Any thoughts you have would be greatly appreciated!

**Comment by AllenFang** [comment]
HI @joshuaja try following:

```js

// in some where
this.refs.table.handleSearch('hello');

render() {
  return(
    <BootstrapTable ref='table' data={ ...}>....</BootstrapTable>
  );
}

```

Let me know if you have another questions, thanks

**Comment by redhat-training** [comment]
@AllenFang this is much appreciated. Thanks!

**Comment by joshuaja** [comment]
@AllenFang this is much appreciated. Thanks!

**Comment by joshuaja** [comment]
@AllenFang - I'm getting `table.handleSearch is not a function` when calling it on each table ref (this.tables.push is there because the tables are being rendered dynamically in a loop)

Here's a snippet of my code:

`<Datatable
    data={panel}
    ref={ref => this.tables.push(ref)}
    exportCSV={false}
    search
>`

Any ideas?

**Comment by AllenFang** [comment]
@joshuaja, could you please print the `ref.table` for any tables?, I want to make sure the `ref` on the `BootstrapTable` is a real `BootstrapTable`. Thanks

**Comment by joshuaja** [comment]
@AllenFang - here's a screenshot of the console output for one of the tables:
![image](https://user-images.githubusercontent.com/9004029/28926917-32292d48-7837-11e7-9da9-905497b641b3.png)

**Comment by AllenFang** [comment]
so how you access to the reference of `react-bootstrap-table`? in you case, I guess you should use this.refs.table.refs.xxx.handleSearch('xxxx')

Sorry, I still can not understand your component structure, you may expand the `refs` object at above diagram and show me again, thanks
