### ISSUE TITLE
Issue of state mutation was detected between dispatches

### ISSUE THREAD

**Issue by imakou** [AllenFang/react-bootstrap-table#1527]
The errors drive me crazy for couple days....
My idea is to combine `react-bootstrap-table` with `Redux`.

The problem happens on when you have inserted new rows and edited cells(save) then add new rows.

According to the console log, it is `A state mutation was detected between dispatches
```
Uncaught Error: A state mutation was detected between dispatches, in the path `workBook.data_rows.3.$hourly rate`. This may cause incorrect behavior.
```

My data is settled to `this.state.rows`.
```
    constructor(props) {
        super(props);
        this.state  = {
            rows: this.props.workbook.data_rows||[],
        }
    }
```
I can add new rows to my `Redux's Store` successfully.

    handleAfterInsertRow(row) {

        this.setState({
            rows:[...this.state.rows, row]
        }, () => {
            this.props.pushDataRow(row);
     })

But I failed to update new rows to my `Store`

```
   afterSaveCell(data_rows, cellName, cellValue) {
      this.setState({
            rows: [...this.state.rows, rows_array]
        }, () => {
            this.props.updateDataRow(rows_array)
        }) 
   }
```
Does anyone have idea how to deal data with Redux?

Thanks,

**Comment by AllenFang** [comment]
@imakou sorry for lately reply, I think use `react-bootstrap-table` with `redux` is no problems. but I will suggest you to enable `remote` on `BootstrapTable`. Check [this](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/remote) to see all the remote example.

`remote` mode allow you to handle your data in your state management framework(flux-like) or server side, for example, insert/edit/delete row, pagination etc. But sometime, you may hope sort/search/filter doesn't pass to the redux, so actually, `react-bootstrap-table` have a way to let you to decide what functionality should be handle by `react-bootstrap-table` internally and what functionality should be handled by redux, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-alternative.js#L9-L15) to see how to configure it.

Let me know if you have any questions, thanks
