### ISSUE TITLE
Each child in an array or iterator should have a unique "key" prop. Check the render method of `PaginationList`

### ISSUE THREAD

**Issue by anujmv** [AllenFang/react-bootstrap-table#1528]
Hi, I am getting this error even after passing a key to <TableheaderColumn>.
check code below.
` <BootstrapTable data={this.state.invoices}
                            striped={true}
                            hover={true}
                            deleteRow={ false }
                            condensed={true}
                            pagination={true}
                            search={true}
                            exportCSV={ true }

            >
                <TableHeaderColumn dataField="invoiceNumber" isKey={true} dataAlign="center" dataSort={true}>ID</TableHeaderColumn>
                <TableHeaderColumn dataField="customerName" dataSort={true}>Customer Name</TableHeaderColumn>
                <TableHeaderColumn dataField="customerPhone" >Customer Number</TableHeaderColumn>
                <TableHeaderColumn dataField="TotalBeforeTax" >Total Cost</TableHeaderColumn>
                <TableHeaderColumn dataField="CGST" >CGST(9%)</TableHeaderColumn>
                <TableHeaderColumn dataField="SGST" >SGST(9%)</TableHeaderColumn>
                <TableHeaderColumn dataField="TotalGST" >Total GST(18%)</TableHeaderColumn>
                <TableHeaderColumn dataField="GrandTotal" >Grand Total</TableHeaderColumn>

            </BootstrapTable>`

**What am i doing wrong???**

**Comment by christso** [comment]
I get the same error. If I remove the pagination property then I don't get the error. Is this a bug?

**Comment by AllenFang** [comment]
https://github.com/AllenFang/react-bootstrap-table/issues/1518
Upgrade to `v3.5.1`, thanks

**Comment by anujmv** [comment]
This is fixed 💃
