### ISSUE TITLE
missing CSS

### ISSUE THREAD

**Issue by maulikdesai21** [AllenFang/react-bootstrap-table#1530]
This is the react component that I am trying to use react-bootstrap-table
```javascript
import React from 'react';

import {BootstrapTable, TableHeaderColumn} from 'react-bootstrap-table';
var products = [{
  id: 1,
  name: "Product1",
  price: 120
}, {
  id: 2,
  name: "Product2",
  price: 80
},{
  id: 1,
  name: "Product1",
  price: 120
}, {
  id: 2,
  name: "Product2",
  price: 80
}];
class AccessList extends React.Component{
  constructor(props) {
    super(props);

  }
  render() {
    return (
      <div>
        <BootstrapTable data={ products } striped hover condensed>
          <TableHeaderColumn dataField='id' isKey>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
        </BootstrapTable>
      </div>
    );
  }

}
module.exports = AccessList;
```

This is the main component that serves as a container for all my components, where I imported the CSS 
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import './css/style.css';
import './css/style.css';
import '../node_modules/react-bootstrap-table/dist/react-bootstrap-table.min.css';
import App from './components/App'

import  'adp-css-framework';

ReactDOM.render(<App />,document.getElementById('root'));
```

This does not work. I work only if I add **bootstrap.min.css** & **jquery** in my HTML as shown below  
`<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <script src="http://code.jquery.com/jquery-2.1.3.min.js"></script>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>

</head>
<body>
<div id='root'></div>
</body>
</html>`

Not sure if I am doing something wrong as I am still quite a rookie at REACT

**Comment by prajapati-parth** [comment]
@maulikdesai21 Can you please mention the version of react-bootstrap-table that you're using. Also when importing styles directly in js/jsx files, you'll need styles loader in your webpack config file, if you are using webpack, please post the contents of your webpack.config.js file. I made the same mistake few weeks back. 
Refer [this](https://github.com/prajapati-parth/react-bootstrap-table-demo/issues/1) and #883.

Thanks.

**Comment by maulikdesai21** [comment]
I am using  `v 3.5.1`, I have all the necessary loaders in my environment. There are other CSS that I have imported and then work. Here is my webpack config for reference  
```javascript 
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');



module.exports = {
  entry:['babel-polyfill','./src/index.js'],
  output:{
    path:path.resolve(__dirname,'dist'),
    filename:'index_bundle.js',
    publicPath:'/'
  },
  devtool: 'eval-source-map',
  module:{
    rules:[
      {
        test:/\.(js)$/,
        use:'babel-loader'
      },
      {
        test:/\.css$/,
        use:['style-loader','css-loader']
      },
      {
        test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
        use: 'file-loader'
      },
      {
        test: /\.(woff|woff2)$/,
        use: 'url-loader?prefix=font/&limit=5000'
      },
      {
        test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
        use: 'url-loader?limit=10000&mimetype=application/octet-stream'
      },
      {
        test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
        use: 'url-loader?limit=10000&mimetype=image/svg+xml'
      },
      {
        test: /\.(?:(?:pn|jpe?)g|gif)$/,
        use: 'url-loader?limit=8192'
      }
    ]
  },
  devServer:{
    historyApiFallback:true
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: 'src/index.html',
      inject: 'body'
    })
  ]
};

```

**Comment by AllenFang** [comment]
I'm not sure what's going on in your repo but I think it's not a bug about `react-bootstrap-table`, could I have a demo repo to reproduce this one? Please give me a repo, I will help you to check, thanks
