### ISSUE TITLE
Error with webpack and beta build

### ISSUE THREAD

**Issue by alexkgodwin** [AllenFang/react-bootstrap-table#1532]
When I use npm to install the beta build like this:
 `npm install "git://github.com/AllenFang/react-bootstrap-table.git#4.0.0-beta.9" --save`
 it installs just fine and ends up in the node_modules folder. 

However when I run webpack to package my files I get
 `Module not found: Error: Can't resolve 'react-bootstrap-table' in '/Users/akgodwin/Documents/server/project/client/src/components'`
 but if I delete the files and run `npm install react-bootstrap-table` webpack doesn't throw any errors and works fine. 

In my code nothing changes between versions, and I import like this `import {BootstrapTable, TableHeaderColumn} from 'react-bootstrap-table';`

**Comment by AllenFang** [comment]
give me your repo, I think it's not a bug for `react-bootstrap-table`.

**Comment by alexkgodwin** [comment]
With the 4.00 release it's not a problem anymore. Thanks!
