### ISSUE TITLE
command to unselect all selected rows

### ISSUE THREAD

**Issue by jcabrerazuniga** [AllenFang/react-bootstrap-table#1533]
Is there a command to unselect all selected rows?
Thanks

**Comment by AllenFang** [comment]
@jcabrerazuniga sorry for lately reply,

A quick ways is 

```js

this.refs.table.setState({
  selectedRowKeys: []
});

<BootstrapTable ref='table' />
```

**Comment by SahRckr** [comment]
ended up with this:=> https://reactjs.org/warnings/refs-must-have-owner.html
(Using React 16)

**Comment by rushubh** [comment]
I had an issue with pagination, my requirment is whenever page change happens I need to clear all selected rows. 
For this I tried using onPageChange(page, sizePerPage) method. In this method I wrote: 
this.refs.table.setState({
  selectedRowKeys: []
});
Now while testing I observed something wierd. Consider the following scenario
On page1 I selected 2 records, navigated to page2, here I selected 1 record, Now I used this.refs.table.state.selectedRowKeys and this gave me 3 ids, 2 from page1 and 1 from page2.
Ideally it should have given only 1 record from current page.

can you please explain why this is happening.

**Comment by rushubh** [comment]
There is one more scenario that occurred
If for a table I have a set of data X, in this data i select 2 rows, after selecting two rows I refresh the data in the grid. Now this grid shows a completely different set of data Y. In this Y set of data I select 3 rows.
Now for this table, this.refs.table.state.selectedRowKeys gives total of 5 records 2 from X set and 3 from Y set.
Is this an issue or this is how it works ?

**Comment by hafdon** [comment]
This seems to work (using 
    "bootstrap-vue": "^2.0.0-rc.16",
    "vue": "^2.6.6",
)
```
this.$refs.['table-ref'].clearSelected()
```
If you print the table to the console, it shows that it's a Vue Component, with a few functions, one of which is clearSelected(). What's annoying is this was not easy to find on a search of the Vue Component API.

**Comment by vijaychouhan-rails** [comment]
```
<BootstrapTable
      ref={bstable}
      keyField="id"
      hover
      data={cusData}
      columns={columns}
      selectRow={{
        mode: 'checkbox',
        clickToSelect: true,
        onSelectAll: (isSelect, rows, _e) => {
          selectCustomer({ isSelect, rows, selectAll: true });
        },

        onSelect: (row, isSelect, _rowIndex, e) => {
          selectCustomer({ isSelect, rows: row, selectAll: false });
        },

      }}
    />
```

and then API call done `bstable.current.selectionContext.selected = [];`

**Comment by DevTakao** [comment]
> ```
> <BootstrapTable
>       ref={bstable}
>       keyField="id"
>       hover
>       data={cusData}
>       columns={columns}
>       selectRow={{
>         mode: 'checkbox',
>         clickToSelect: true,
>         onSelectAll: (isSelect, rows, _e) => {
>           selectCustomer({ isSelect, rows, selectAll: true });
>         },
> 
>         onSelect: (row, isSelect, _rowIndex, e) => {
>           selectCustomer({ isSelect, rows: row, selectAll: false });
>         },
> 
>       }}
>     />
> ```
> 
> and then API call done `bstable.current.selectionContext.selected = [];`

this worked for me to unselect all checkboxes

**Comment by alexwing** [comment]
This is my solution

```
const ref: any = React.useRef();
....

  function cleanFilters() {
    //unselet table
    if (ref && typeof ref === "object") {
      if (ref.current !== undefined) {
        ref.current.selectionContext.selected = [];
      }
    }
  }
...

  return (
    <React.Fragment>
                <BootstrapTable
                  ref={ref}
....

```
