### ISSUE TITLE
Restrict Insert Modal not to ask for id field

### ISSUE THREAD

**Issue by TayyabAhmed** [AllenFang/react-bootstrap-table#1535]
I am using firebase as backend for my app , and  using push to save the data  in firebase which creates its own unique id while saving the data .
The problem is that  insert Modal contains the  id input field  which is required because it is the keyfield of my table and this **key is generated by firebase on runtime**, is there any way to restrict the modal not to ask for id .
I am using this key for deletion of data  so I can not remove isKey from that this column.

**Comment by AllenFang** [comment]
HI @TayyabAhmed, try to give `autoValue` on `TableHeaderColumn` for key column.
