### ISSUE TITLE
[Question] Bootstrap with dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by Paul6552** [AllenFang/react-bootstrap-table#1536]
I create my table dependent on values I receive over the network. Sometimes my table has 2 columns, sometimes it has 9 columns. (columns NOT rows).
Therefore I have written this code in my app:

`			  <BootstrapTable height={'300px'} 
				data={ this.state.tableData } 
				search={ false } 
				dangerouslySetInnerHTML={this.bewertungenTableHtml()} />  `

And in my function bewertungenTableHtml I have written:

`  bewertungenTableHtml() { 
//here I have some code, checking how much columns I have. Then I build my rows together .
//Only for simplicity I am returning now only ONE TableHeaderColumn row.
	return {__html: "<TableHeaderColumn dataField='firstField' searchable={ false }>First Value</TableHeaderColumn>"}; 
  };`

Sadly, it is not working. What I am doing wrong?

Error message:
BootstrapTable.js?e928:237 Uncaught TypeError: Cannot read property 'reduce' of undefined
    at BootstrapTable.initTable (BootstrapTable.js?e928:237)
    at new BootstrapTable (...

//ANOTHER TRY
`			  <BootstrapTable height={'600px'} data={ this.state.tableData } search={ true } multiColumnSearch={ true }>
				<TableHeaderColumn dataField='startnummer' isKey>Startnummer</TableHeaderColumn>
			{["land","anzahl","bs","email"].map((item, key) => {
			  return (<TableHeaderColumn 
						dataField={item} 
						searchable={ false }>{item}</TableHeaderColumn>)
			})}				
			  </BootstrapTable>`

Error message:
Uncaught TypeError: Cannot read property 'isKey' of undefined

**Comment by tomaszantas** [comment]
I've got similar error. If I use "search" on BootstrapTable and generate the TableHeaderColumns from array, I get:

Uncaught TypeError: Cannot read property 'isKey' of undefined

If I remove "search" prop or map generating columns, everythings works fine.

**Comment by Paul6552** [comment]
I got it almost working without dangerouslySetInnerHTML (Thanks for that question [https://github.com/AllenFang/react-bootstrap-table/issues/406](url) )

In the render()
`<BootstrapTable 
				data={ this.state.bewertungenTableData } 
				keyField={ this.state.bewertungenTableColumns[0] } 
				search={ false }>
					{this.state.bewertungenTableColumns.map(function(name, key){
					  return <TableHeaderColumn dataField={ name }>{ name }</TableHeaderColumn>
					})}		
			  </BootstrapTable>`

Only the error message "Each child in an array or iterator should have a unique "key" prop ..." left.
How do I add a key to TableHeaderColumn?

**Comment by Paul6552** [comment]
This is the right way to insert:
`					{this.state.bewertungenTableColumns.map((name) =>{
					  return <TableHeaderColumn dataField={ name } key={name.uniqueId}>{ name }</TableHeaderColumn>
					})}	`

thank you all guys for the work on react bootstrap table 👍
