### ISSUE TITLE
Error while deleting rows from second page in case of default pagination

### ISSUE THREAD

**Issue by shalinibajpai0310** [AllenFang/react-bootstrap-table#1539]
Hi,
I am trying to delete the rows from the second page in case of default pagination but getting the following error.

![localdeletion](https://user-images.githubusercontent.com/20796527/29110896-e38771da-7d05-11e7-8463-7310e10d9e35.PNG)

Here is my code :
  import React from 'react';
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';

const products = [];

function addProducts(quantity) {
  const startId = products.length;
  for (let i = 0; i < quantity; i++) {
    const id = startId + i;
    products.push({
      id: id,
      name: 'Item name ' + id,
      price: 2100 + i
    });
  }
}

addProducts(70);

export default class DefaultPaginationTable extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {

     const selectRowProp = {
  mode: 'checkbox'
}
    return (
      <div>
        <BootstrapTable
          data={ products }
          deleteRow={ true }
         selectRow={ selectRowProp }
          pagination>
          <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
        </BootstrapTable>
      </div>
    );
  }
}
Kindly assist asap.

**Comment by shalinibajpai0310** [comment]
![image](https://user-images.githubusercontent.com/20796527/29116031-332b3738-7d17-11e7-93e2-8c5542e6578e.png)

**Comment by shalinibajpai0310** [comment]
@Allen ... kindly update on the issue asap.

**Comment by AllenFang** [comment]
@shalinibajpai0310 sorry for lately reply, I'll fix it soon and I'm @AllenFang

**Comment by AllenFang** [comment]
Fixed on `v4.0.1`
