### ISSUE TITLE
hide single selection column.

### ISSUE THREAD

**Issue by shekharkul** [AllenFang/react-bootstrap-table#154]
Hello,
I am using react-bootstrap-table in my application and i want to hide radio button column. I did it by using Jquery but when i moving to another page some radio button id displaying.
Please suggest how to do the same scenario.

Also i want to apply scroll bar to only to grid data  and hide/disable pagination if no of records are less than page size.

Thanks,

**Comment by AllenFang** [comment]
@shekharkul, you can give <code>hideSelectColumn</code> in <code>selectRow</code> to true for hiding the selection column.

Second, I suggest you should avoid to use jquery to do some stuff in react.js world. About your second problem, if there's no data, you can set <code>pagination</code> to false, it will hide the pagination buttons.

**Comment by AllenFang** [comment]
Anyway, Thanks you find this component :)

**Comment by shekharkul** [comment]
Thanks for your help.
In second scenario Actually I want to hide/ disable pagination if no of rows is less than selected page size 
e.g 1. if no of row is 5 and page size is 10 then pagination should be disable/hide
2. If no of row is 15 and page size is 10 then pagination should be enable, but if user change page size to 20 then pagination should be disable/hide.

Also I want to add scroll bar only to data in table and pagination always visible to user like static column.

Thanks.

**Comment by AllenFang** [comment]
I got you, but I think <code>react-bootstrap-table</code> have no ability to reach your pagination requirement currently. Because I design this for a general condition. Maybe, you need to fork this and customize for your requirement. sorry :)
