### ISSUE TITLE
Switch order between expand component and checkboxes

### ISSUE THREAD

**Issue by eduAbreu** [AllenFang/react-bootstrap-table#1543]
Hi again @AllenFang is it possible to change the order between the expand component and the checkboxes. At this moment you are showing the expand component first and the checboxes after, but I wanted to show the checkboxes first.

Anyway to do this?

Regards

**Comment by AllenFang** [comment]
@eduAbreu sure, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/expand-row-with-selection.js#L85), assign `false` on `expandColumnOptions.expandColumnBeforeSelectColumn`
