### ISSUE TITLE
Editable type='select' problem on insert popup

### ISSUE THREAD

**Issue by BdDragos** [AllenFang/react-bootstrap-table#1547]
Hello. I am trying to insert an object which has a nested object as one of the fields. Since I only need some nested objects to select from, object I already have in my database, I have tried to get all the objects from there, and to set the resulted array as the values in my editable type='select' field from an insert popup. The problem is, the field isn't recognized, and it looks like this.
![untitled](https://user-images.githubusercontent.com/26300460/29274475-aeca7c76-8110-11e7-92f7-fa928f132c23.png)

The number of objects is correct though, since you can see there are 4 possibilities to select from. I have tried to print in the console my new object formed after I input everything, but if the other fields are correctly assigned, the category one stays empty, no matter if I selected something from the dropdown or not.

I have also tried to set the Category dropdown to the id's of the categories, but I receive the following error when I try to assign as values an array of integers.

props.dataFormat(...).replace is not a function
    at format (BootstrapTable.js:1532)
    
Here is how my tableheader looks 

<TableHeaderColumn dataSort={true} editable={{ type: 'select', options: { values: catId } }}

catId is the integers array.

What can I do to fix this problem and how could I assign to the dropdown either the entire object or its id? Thank you

**Comment by AllenFang** [comment]
Hello @BdDragos 

1. we dont support the raw data which have nested field, for example:
```js
data = [{
  id: 100,
  address: {
    postal: 2003981,
    city: 'New York'
  }
}]
```

so could you please show me your data? Thanks

**Comment by BdDragos** [comment]
Hello and thank you for your reply.

Here is how one object from an array looks

"ID": 1,
        "name": "AAAAAAA",
        "category": {
            "ID": 3,
            "categoryName": "PC"
        },
        "serialNo": "1111-1111-1111",
        "provider": "CCCCCC",
        "acquisitionDate": "2017-08-15T15:00:06.037",
        "warrantyEnd": "2017-08-15T15:00:06.037",
        "inventoryNo": 25,
        "allocationStatus": "GIVEN",
        "owner": "BBBBBBBB",
        "allocationDate": "2017-08-15T15:00:06.037",
        "serviceStatus": "GOOD",
        "serviceResolution": "FIXED"

What I want to do is to take either the "ID" or the "categoryName" from my "category" field, display it in my the select popup, and after selecting it put it in my newly created row (or object).

**Comment by AllenFang** [comment]
@BdDragos sorry for lately reply, as I mention above, `react-bootstrap-table` doesn't support the nested data field on each raw data. But in you case, I guess you still can use custom editor field to custom the dropdown with your nested data field.

You can learn how to custom a field for insert by [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/insert-modal/custom-insert-modal-field.js). I will not support the nested data in `react-bootstrap-table` but will implement this feature on [`react-bootstrap-table2`](https://github.com/react-bootstrap-table/react-bootstrap-table2)

Please let me know if you get any trouble on custom the dropdown, thanks
