### ISSUE TITLE
A bug of remote paging's example

### ISSUE THREAD

**Issue by thundermiracle** [AllenFang/react-bootstrap-table#1549]
I think I found a bug of remote paging, at least the bug of remote paging's example.
I implemented this feature into my project and found that **onPageChange** will be called before **onSizePerPageList**, so in the example, setState(data...) will be called twice if you select the sizePerPage.

![remotepaging_bug](https://user-images.githubusercontent.com/25689126/29306123-eb60960e-81d6-11e7-93bb-4aeeb601e817.gif)

**Comment by AllenFang** [comment]
@thundermiracle thanks, I'll check this out

**Comment by li164902697** [comment]
i have the same problem, how to fix it?@AllenFang

**Comment by prajapati-parth** [comment]
@li164902697 This is same as #1587. 1587 has a work around.
@AllenFang We can close either one of these as the other is duplicate.

Thanks.
