### ISSUE TITLE
clickToSelect: true + cellEditTableData mode: dbclick not working

### ISSUE THREAD

**Issue by Paul6552** [AllenFang/react-bootstrap-table#1551]
Hello,
First: I have configured my table with clickToSelect: true, In the function clickToSelect I give the row another color:

`const selectRowTableData = {
		mode: 'checkbox', //radio or checkbox
		clickToSelect: true,
bgColor: function(row, isSelect) {
		  if (isSelect) {
			return 'red';
		  }
		  return null;
		}		
	};`

OK, working great.
Now I add celledit with **DOUBLE CLICK**:

`	const cellEditTableData = {
		mode: 'dbclick' // click cell to edit
	};	`

What happens now:
If I double click on my table it is working, I can edit the table. If I click only once on the table row it should mark the row with the color red, but this isn't working. 

I checked the behaviour with the debugger and found out, that the function selectRow (in my case selectRowTableData) will entered, but in the function bgColor nothing is selected. The value is every time false.

I look in the issue tracker and found the same question already in 2015:
[https://github.com/AllenFang/react-bootstrap-table/issues/21](url)

There the last entry of the developer was
"Hi stephenrs, so you just only want the user click row for selection and dbclick for editing? If is, I misunderstand before and I'll fix it." 

So in my opinion this should work. Do I something wrong?

My full table:
`			  <BootstrapTable height={'600px'} 
					data={ this.state.tableData } 
					options={optionsTableData} 
					cellEdit={ cellEditTableData }
					selectRow={ selectRowTableData } 
					trClassName={ this.trClassFormat }					
					insertRow 
					deleteRow 				
					search={ true } 
					multiColumnSearch={ true } 
					hover={true} 
					condensed 
					>
				<TableHeaderColumn dataField='startnummer' isKey>Startnummer</TableHeaderColumn>
				<TableHeaderColumn dataField='vid'>VID</TableHeaderColumn>
				<TableHeaderColumn dataField='titel'>Titel</TableHeaderColumn>
				<TableHeaderColumn dataField='disziplin' searchable={ false }>Disziplin</TableHeaderColumn>
				<TableHeaderColumn dataField='altersklasse' searchable={ false }>Altersklasse</TableHeaderColumn>
				<TableHeaderColumn dataField='kategorie' searchable={ false }>Kategorie</TableHeaderColumn>
				<TableHeaderColumn dataField='wertungsklasse' searchable={ false }>Wertungsklasse</TableHeaderColumn>
				<TableHeaderColumn dataField='dauer' searchable={ false }>Dauer</TableHeaderColumn>
				<TableHeaderColumn dataField='tanzId' searchable={ false }>TanzID</TableHeaderColumn>
				<TableHeaderColumn dataField='anzahl' searchable={ false }>Anzahl</TableHeaderColumn>
				<TableHeaderColumn dataField='land' searchable={ false }>Land</TableHeaderColumn>
				<TableHeaderColumn dataField='schulname' searchable={ false }>Schulname</TableHeaderColumn>`

**For better reading**: [JSFiddle](https://jsfiddle.net/ydk41egL/)

**Comment by AllenFang** [comment]
@Paul6552 sorry for lately reply, please try following code, this is not a bug

```js
const cellEdit = {
  mode: 'dbclick'
};
const selectRow = {
  mode: 'checkbox',
  clickToSelectAndEditCell: true
};
```

**Comment by Paul6552** [comment]
@AllenFang 
No, it is not working. With double click I can edit the cell. With one click the row is never selected:

`	const selectRowTableData = {
		mode: 'checkbox',
		clickToSelectAndEditCell: true,
		bgColor: function(row, isSelect) {
		  if (isSelect) {
			return 'red';
		  }
		  return null;
		}		
	};	`

iSelect = never true, every time False!

**Comment by AllenFang** [comment]
1. It's work for me
2. please describe your problem clear, the problem is the `isSelect` argument is always false for `bgColor` function.... **NOT ROW SELECTION BROKEN**

Following is my example

```js
const selectRowProp = {
  mode: 'checkbox',
  clickToSelectAndEditCell: true,
  bgColor: function(row, isSelect) {
    if (isSelect) { return 'red'; }
    return null;
  }
};

const cellEdit = {
  mode: 'dbclick'
};

export default class ClickToSelectTable extends React.Component {
  render() {
    return (
      <BootstrapTable data={ products } cellEdit={ cellEdit } selectRow={ selectRowProp }>
          <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
}
```

**Comment by Paul6552** [comment]
@AllenFang  Thank you for your reply.

I found my error with your provided example. Sadly, I have no idea how to fix this. :-/ 
`isSelect` and double click is working if I don't use `setState` in the function `onRowClick`.

In my JSFiddle example below, you will find an expanded example of your example above.
Bootstraptable with `cellEdit: dbclick`, `selectRowProp` AND NEW `options`.

In `options` I set the function `onRowClick: this.onClickDoSomething`.
`isSelect` is working (selected Row is true) as long as I don't use `setState` in the `onClickDoSomething` function.

So why is `isSelect` every time `false` if I use `setState` in the function `onClickDoSomething`?

Please open my JSFiddle for better understanding.
Thank you very much
https://jsfiddle.net/qbh9o7px/1/

**Comment by AllenFang** [comment]
> double click is working if I don't use setState in the function onRowClick.

I think you should point it at begin, this discussion is wasting my time lol

Actually, `onRowClick` must faster than row selection, os if you call `setState` in  `onRowClick` , the table will get rerender so the actually, the selection event is no trigger... I do suggest you not to change state in `onRowClick` or the other hook events.

**Comment by Paul6552** [comment]
Thank you for your time.
Finished
