### ISSUE TITLE
Browser Compatibility Issue

### ISSUE THREAD

**Issue by jiujianxian** [AllenFang/react-bootstrap-table#1553]
The datetime format does not work on Safari or Firefox. Like the first example on this page does not work: http://allenfang.github.io/react-bootstrap-table/example.html#advance. 

Could anyone help me resolve this issue?

**Comment by Suman-Plivo** [comment]
Hi @jiujianxian , 
If you are talking about the the datetimepicker that pops up when you click on the datetime in chrome browser then it is because it is a inbuilt feature of chrome browser, while safari and mozilla don't support the datetimepicker yet. So you won't be able to access them.

**Comment by mosane** [comment]
is there a work around?

**Comment by shellophobia** [comment]
Hi @mosane,
You could try to create a custom components with some other good datepicker plugins like ["react-dates".](https://github.com/airbnb/react-dates) It worked out for me. Just ensure that those components return an input field where the final value would be shown after you select a date.

**Comment by AllenFang** [comment]
yes, the workaround is you can use thrid party library to have your own datetime picker

For this issue, I'll take care more on [react-bootstrap-table2](https://github.com/react-bootstrap-table/react-bootstrap-table2), thanks

**Comment by mosane** [comment]
Hmm... I think a better work around would be using a polyfill for `input type=date`. Might be worth considering making this a part of the library.

**Comment by AllenFang** [comment]
@mosane great 👍

**Comment by AllenFang** [comment]
@mosane any suggestion polyfill for input date ?
