### ISSUE TITLE
CustomFilter documentation not clear for actually filtering cell values

### ISSUE THREAD

**Issue by charlieanstey** [AllenFang/react-bootstrap-table#1554]
Hi Allen,

Firstly thanks for the awesome package, it works a treat in a project I've been working on for many months.

Just getting into custom filtering, trying to filter a column holding a date value with a from/to date range. Having looked at #601 and the various examples, I know DateFilter only supports a single date and comparator.

So having gone through https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js and tried mocking up a basic solution, I can't see how/where I would filter the `cell` value? This example doesn't appear to actually filter - it just calls `this.props.filterHandler()` which when followed in debugging, goes into `handleFilter` and further into the internal `Filter` class etc.

How do I specify a custom function which is given the column value for each row and applies the filtering itself? I don't want to start using `remote` in any serious way as the table does the job just fine otherwise. And the `handleFilterData` API method seems to only support the built-in filters.

Look forward to hearing back,
Charlie

**Comment by AllenFang** [comment]
Hello @charlieanstey sorry for lately reply.

https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js  call the `handleFilter` and pass the value you want to filter will trigger filtering.

BTW, if you want filter data programmatically, you can try following, `handleFilterData` is not restricted for any built-in filter :)

```js
this.refs.table.handleFilterData({ name: 'Item name 3' });
or
this.refs.nameCol.applyFilter('Item name 3');

<BootstrapTable ref='table' data={ products }>
          <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn ref='nameCol' dataField='name' filter={ { type: 'TextFilter', delay: 1000 } }>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
        </BootstrapTable>
```

Feel free to let me know if you still have any questions :)

**Comment by charlieanstey** [comment]
Hi Allen. Sorry for my similarly late response!

Okay so I don't think this answers my question. Calling `handleFilter` lets me pass a value to your pre-defined filter function and 

> trigger filtering

as you say. But that actual filtering isn't customisable - I can't for example filter the value where it is outside a range of 2 values or dates. As stated, I want to handle the filtering myself. So I want to filter a date column between 2 dates which I define.

In the programmatic examples you've given, again that doesn't appear to let me filter between 2 dates or indeed anything else custom.

I get the feeling what I'm asking for isn't possible in `react-bootstrap-table` at the moment, essentially I'm saying the filter function should be exposed as a prop to pass in. Your custom filter feature doesn't appear to allow me to do what I expect: provide a custom function as a prop which accepts the column value and returns true/false to indicate whether or not the column value/row passed should be filtered. To me at least, the custom filter feature doesn't actually let me do custom filtering on the column - it just lets me customise when the filtering is triggered, but the filtering itself is just one of the predefined types you've implemented.

Again, I'm hoping this is just my lack of understanding of the documented examples and that I'm wrong. Hopefully you can shed some light on it.

**Comment by AllenFang** [comment]
HI @charlieanstey sorry for lately reply and some misunderstand on your question. now it's very clear 👍 


> again that doesn't appear to let me filter between 2 dates or indeed anything else custom.
Yes, it's the restriction in `react-bootstrap-table` currently.


> provide a custom function as a prop which accepts the column value and returns true/false to indicate whether or not the column value/row passed should be filtered

yes, it's a good point that I can try to support it, I'll consider to add it, but actually I'm busy in recently, so may take some time. its very sorry

**Comment by charlieanstey** [comment]
Hi Allen, thanks for the reply. Glad it makes sense now. It might not be a huge amount of work, perhaps adding a `PropTypes.func` prop to `TableHeaderColumn` for overriding the filterHandler. It would just need to be passed the cell value for each row, then return true or false to indicate if it should be filtered or not.

I realised that using Remote might have been a better option for my use case. But instead I decided to filter in my data request outside of `react-bootstrap-table` for now.

**Comment by AllenFang** [comment]
HI @charlieanstey sorry for some misunderstand lol

for the custom filter example, you can see [here](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js#L39-L45)

Actually, I think this is what you want, this function will be call on [here](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js#L35). Let me explain how it work...

1. [filter function](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js#L30) will be trigger when custom filter change, for example: click/checked etc.

2. In above function, you should call `filterHandler` and give a `callback` props, [here](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js#L35)

3. The callback function will be called from `react-bootstrap-table` when filtering on this column.

4. The callback function accept a column value and you can do your own filtering logic then return true/false to tell `react-bootstrap-table` if this column value is valid.

**Comment by rikkirabz** [comment]
@charlieanstey I am running into the same issue that you had.  Were you able to come up with a solution?

**Comment by marcramser** [comment]
@AllenFang But if you return true/false in the callback, you will not be able to get the value in the afterColumnFilter().

```
  afterColumnFilter = (filterConds, result) => {
    for (const prop in filterConds) {
      if (filterConds[prop].type === 'CustomFilter') {
        console.log('Filter column= ' + prop + ', Filter value= ' + filterConds[prop].value.callback());
      } else {
       // normal way to get the value
        console.log('Filter column= ' + prop + ', Filter value= ' + filterConds[prop].value);
      }
    }
  };
```
