### ISSUE TITLE
Uncaught TypeError: Cannot read property 'refs' of undefined on selecting tab

### ISSUE THREAD

**Issue by davecarlson** [AllenFang/react-bootstrap-table#156]
In Google Chrome (mac), when I select a tab of another page , then go back to the tab with the table on, i get multiple instances of this.

Uncaught TypeError: Cannot read property 'refs' of undefined_adjustHeaderWidth @ BootstrapTable.js:609

**Comment by AllenFang** [comment]
@davecarlson , I cant reproduce this problem but did you got another problem or bugs when this error printed?

**Comment by staminaloops** [comment]
I'm having this error too. Try to resize the window and see if you can reproduce it too.

**Comment by davecarlson** [comment]
@staminaloops  - yes, resizing the window gets the same error.

**Comment by AllenFang** [comment]
wow, that‘s strange, I cant reproduce again ;(  Anyway, there's any header unalign problem after window resizing?

**Comment by staminaloops** [comment]
no everything works, just Uncaught TypeError: Cannot read property 'refs' of undefined

**Comment by AllenFang** [comment]
@staminaloops, thanks, I'll keep an eye on this problem and try to reproduce it !

**Comment by staminaloops** [comment]
![error-table](https://cloud.githubusercontent.com/assets/11683210/11443585/2c148020-9516-11e5-9539-947c299fec37.png)

Everytime we resize the window, it add +1 error :) Thank you @AllenFang

**Comment by AllenFang** [comment]
:+1:

**Comment by AllenFang** [comment]
I find this problem, I should no bind <code>this</code> with <code>_adjustHeaderWidth</code> when remove window resizing event @BootstrapTable.js:122. Thanks for this bug report, I'll fix it on next version :)

**Comment by davecarlson** [comment]
Is this in v1.2.14 ?

**Comment by AllenFang** [comment]
@davecarlson, sorry for my promise. It's not fixed in v1.2.14, however, I'll fix it in these day :)

**Comment by AllenFang** [comment]
Fix it in v1.2.15

**Comment by davecarlson** [comment]
Confirmed. Thanks !

**Comment by kadariyp** [comment]
I am using ^4.0.0-beta.1 right now and i face the same issue. It fails on componentWillUnmount function, inside BootstrapTable.js.

**Comment by kadariyp** [comment]
this.refs.body.refs.container.removeEventListener('scroll', this._scrollHeader);

**Comment by AllenFang** [comment]
@kadariyp, only happen on `v4.0.0`?

**Comment by kadariyp** [comment]
@AllenFang I tried it with the latest non beta version and i still get the error. It happens on selecting the tab that mounts and unmounts the table. So I think the bug is similar to the one mentioned here.

**Comment by EmilAgren** [comment]
I'm also getting exactly the same error as @kadariyp is talking about (using react-bootstrap-table 3.3.5).

**Comment by AllenFang** [comment]
try to upgrade `v3.3.6`~

**Comment by EmilAgren** [comment]
Unfortunately still the same problem after upgrade to 3.3.6.
The problem started when I started using webpack. When using react-bootstrap-table just by importing the necessary script in index.html it works perfectly.

**Comment by AllenFang** [comment]
it's wired, could you post your error message?

**Comment by EmilAgren** [comment]
This is what I'm getting: 

![err2](https://cloud.githubusercontent.com/assets/4100810/26274614/dfe9b882-3d4d-11e7-85f0-0dc5b1f0ca70.PNG)

**Comment by AllenFang** [comment]
ok, I'll check this out, but not sure if I can fix it

**Comment by EmilAgren** [comment]
Solved it, and It was my mistake. I tried to reinstall all of my node modules which solved the problem.
My guess is that I must have had multiple copies of React loaded somehow.
Anyway, thanks for your time and a great component :)
