### ISSUE TITLE
Display custom text when hovered on a cell

### ISSUE THREAD

**Issue by narendravenkata** [AllenFang/react-bootstrap-table#1562]
Currently I am using headerText to display custom text when hovered on table header, in the same way is there anything I can use to display custom text when hovered on a particular cell.

**Comment by AllenFang** [comment]
HI @narendravenkata we can only use `columnTitle` to enable the title on cell and default value is cell value. I can support the custom title on specified cell, thanks

**Comment by narendravenkata** [comment]
![issue](https://user-images.githubusercontent.com/28738596/29488396-c922a8ce-84cf-11e7-9721-b48a1ca922ec.PNG)

Here I want to display error message when hovered on cell with red color and similarly for other colors

**Comment by AllenFang** [comment]
ok, got it, I will implement in this week, BTW, all the tooltip in `react-bootstrap-table` is [HTML title attribute](https://www.w3schools.com/tags/att_title.asp).

**Comment by AllenFang** [comment]
Fixed on `v4.0.2`, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column/column-title-table.js#L31) to see how to custom the title by `cell` or `row`. Thanks

**Comment by narendravenkata** [comment]
@AllenFang  Thanks Allen for your quick update on the issue, it is good if we can have rowIdx and columnIdx as well so we can know the exact cell number. is that possible?

**Comment by AllenFang** [comment]
> is that possible?

sure, I can fix it in next version

**Comment by welchn** [comment]
Hi Allen, is there any plan to support a richer variety of tooltip?  Perhaps allow styles on it, allow HTML or react components to be embedded, etc.?  We would definitely have use cases for this flexibility, and am curious if you think this may be supported in the future.  Thank you.

**Comment by AllenFang** [comment]
HI @welchn, as I mention in README, `react-bootstrap-table` already stop feature development and will implement next generation of `react-bootstrap-table`, but your idea is good, maybe you can go to https://github.com/react-bootstrap-table/react-bootstrap-table2 and discuss with us. Anyway, if you really want a richer tooltip, PR is welcome, thanks

**Comment by AllenFang** [comment]
@narendravenkata the row index and column was passed as third and fourth argument on `v4.0.3`
