### ISSUE TITLE
Can't access onClick function in the column's button formater  

### ISSUE THREAD

**Issue by ajits731** [AllenFang/react-bootstrap-table#1565]
open() {
  this.setState({showStatusModal: true});
}

actionsFormatter(cell,row) {
  return  <SplitButton bsStyle="warning" title="Actions" id="split-button-basic">
          <MenuItem eventKey="1"><Link to={"/edit_campaign/"+cell}><span className="fa fa-pencil"> </span> Edit Campaign</Link></MenuItem>
          <MenuItem eventKey="2"><Link to={"/internalReport/"+cell}><span className="fa fa-table"> </span> Internal Report</Link></MenuItem>
          <MenuItem eventKey="3"><Link to={"/clientReport/"+cell}><span className="fa fa-table"> </span> Client Report</Link></MenuItem>
          <MenuItem **onClick={() => this.open()}** eventKey="3"><Link ><span className="fa fa-clipboard"></span>Change Status</Link></MenuItem>
        </SplitButton>
}

**Comment by AllenFang** [comment]
HI it too hard for me to reproduce this issue, if ok, please give me a repo or full example but keep it simple and minimal. BTW, any event defined in `dataFormat` is work well for a long time, so I think it's not a bug, thanks

**Comment by prajapati-parth** [comment]
@ajits731 I've faced a similar kind of issue before. If you are using react-bootstrap library, it the issue of with MenuItem which is not being clickable. Please confirm if you are using react-bootstrap.
Thanks.

**Comment by AllenFang** [comment]
@prajapati-parth  👍

**Comment by ajits731** [comment]
Yes I'm using react-bootstrap but Never mind I used the modal as a component and bypassed the click event.
