### ISSUE TITLE
placeholder-selected in filters/Select.js is not handled correctly

### ISSUE THREAD

**Issue by CroniD** [AllenFang/react-bootstrap-table#1568]
Hi there,

the css class `placeholder-selected` is not removed from class names in filters/Select.js, when an option is selected not equal to the placeholder. The not-placeholder option is displayed in something like light grey if selected. Formatting in the menu is correct tho, but not in the field of the select element. There is no workaround for this. :(

Best regards

**Comment by AllenFang** [comment]
@CroniD thanks, I'll handle it :)

**Comment by AllenFang** [comment]
Fixed on `v4.0.3`

**Comment by CroniD** [comment]
@AllenFang & @rennerDa Thank you both. It works. :)
