### ISSUE TITLE
"none" as selectRow.mode

### ISSUE THREAD

**Issue by marcelalburg** [AllenFang/react-bootstrap-table#157]
Hello,

is it possible to allow "none" as selectRow.mode. I don't need a checkbox or radiobutton, i just need the click event and the clicked row, to show more information (as a slideover).

thanks for this nice lib

Marcel

**Comment by AllenFang** [comment]
you can give <code>radio</code> to <code>selectRow.mode</code> and set <code>selectRow.hideSelectColumn</code> for hiding selection column

**Comment by marcelalburg** [comment]
Uhh, now i see it in the docu. Thanks. it works perfectly.

Marcel
