### ISSUE TITLE
How to style active sort column?

### ISSUE THREAD

**Issue by VictorChen** [AllenFang/react-bootstrap-table#1571]
I've looked through the docs and examples but couldn't figure out how to style the current sorted column header. Basically, I want to change the color of the `<th>` that's being sorted, eg:

<img width="782" alt="screen shot 2017-08-24 at 10 21 08 am" src="https://user-images.githubusercontent.com/1408813/29670947-39a61434-88b6-11e7-8c05-441abcfe3eab.png">

There doesn't seem to be anything to indicate that the column is being sorted?

**Comment by prajapati-parth** [comment]
Hi @VictorChen, please consider #1458. This can even help you style entire column that is sorted. 
Thanks.

**Comment by VictorChen** [comment]
Hi @prajapati-parth, thanks for that. It still seems like a lot of work for something this simple though... Would be great if it added an `active` class to the `<th>` by default... or perhaps expose another table option like `activeSortColumnClassName`

**Comment by AllenFang** [comment]
Firslty, thanks @prajapati-parth 's answer 👍  
@VictorChen I'll consider to make it more simple, thanks

**Comment by AllenFang** [comment]
Fixed on `v4.0.4`, check [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/sort-style-table.js#L36-L37) and let me know if bug or any idea, thanks
