### ISSUE TITLE
data is saving but modal isn't closing on `handleAddRowWithASyncError`

### ISSUE THREAD

**Issue by avishaypelach** [AllenFang/react-bootstrap-table#1573]
Hi @AllenFang,

I'm using` react-bootstrap-table`  `insertRow` and I'm trying to close modal after pressing the save button.
I'm using `handleAddRowWithASyncError` to customize my error alerts and if every input is valid I'm saving data.

Problem is that data is saving but modal doesn't close when pressing save button.

add the function:

```
handleAddRowWithASyncError(row, colInfo, errorCallback) {
    setTimeout(() => {
      let rowTitleCapitalize = row.title.replace(/\b\w/g, function (l) {
        return l.toUpperCase()
      });
      let isTitleExists = this.state.books.find((book) => book.title === rowTitleCapitalize);
      let isIdExists = this.state.books.find((book) => book.id === parseInt(row.id));`

     ` if (isIdExists) {
        errorCallback('ID number is already exists, please change it');
      } else if (isNaN(row.id) !== false) {
        errorCallback('ID must be a number!');
      } else if (row.id.length === 0) {
        errorCallback('Must enter ID number!')
      } else if (row.author.length === 0) {
        errorCallback('Please enter an author name')
      } else if (row.title.length === 0) {
        errorCallback('Please enter a book name')
      } else if (isTitleExists) {
        errorCallback('Book name is already exists, please change it');
      } else if (typeof parseInt(row.date) !== 'number' || parseInt(row.date) > 2017) {
        errorCallback('Please enter a valid Publishing year')
      } else if (row.date.length === 0) {
        errorCallback('Please enter a publishing year')
      } else {
        this.state.books.push(row);
        this.setState({books: this.state.books});
      }
    }, 1);
    return false;
  }
```

Thanks in advance.

**Comment by AllenFang** [comment]
Hi @avishaypelach, very sorry for lately reply >>

```js
 else {
        errorCallback();    // when your validation all pass, please call callback without any argument
        this.state.books.push(row);
        this.setState({books: this.state.books});
      }
```

**Comment by avishaypelach** [comment]
Hi @AllenFang  thanks for your reply,

I was wondering, is there a way to create real time validation in the new row modal?
I mean once I insert a value to an input it can immediately alert me if there is a problem?

**Comment by AllenFang** [comment]
@avishaypelach we only have this kind feature for cell editing. it's sorry that we dont have this feature for insert modal. But it's a good idea that I can enhance on [react-bootstrap-table2](https://github.com/react-bootstrap-table/react-bootstrap-table2)

But there're still have a workaround but you may take some time...
is try to custom the each field and write a onblur event to checking the value.  [This](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/insert-modal/custom-insert-modal-field.js#L83-L85) is a good example you can take if necessary.

**Comment by avishaypelach** [comment]
@AllenFang  I can not thank you enough.
