### ISSUE TITLE
Expanded row class/styling

### ISSUE THREAD

**Issue by stackptr** [AllenFang/react-bootstrap-table#1575]
Objective is to conditionally style a row based on expanded state. There doesn't appear to be a straightforward way of doing this. Seems like the only way to do this is to select on `tr[width="100%"]` which is quite fragile/not semantic.

I suggest creating an `expandRowOptions` or similar that should deprecate the very specific `expandRowBgColor`. Instead of only being able to style a row's color, add the following options:

- `expandRowOptions.className(string | callback(row) => string)` -- applies `string` to every expanded row `tr`, or applies returned string of callback function which is passed the row data
- `expandRowOptions.style` -- could accept an arbitrary map of styles to apply on a row when expanded, in order to provide consistent API to style background color

**Comment by stackptr** [comment]
P.S., @AllenFang I'm aware of the feature freeze on this repo but it's unclear to me if the `react-bootstrap-table2` repo is in a usable state yet for me to submit a PR there or if I should do it here instead

**Comment by AllenFang** [comment]
@stackptr thanks your suggestion, I'll improve it ASAP.

Any PR or issues is welcome here, but if the feature request is too big, I won't do it. For `react-bootstrap-table2`, It still on progress, and it's need some time to make `react-bootstrap-table2` to have same feature/functionality with `react-bootstrap-table`. I hope  `react-bootstrap-table2` can achieve 80% functionality in the end of this year.

Anyway, I can promise that `react-bootstrap-table2` will have more functionality and less bug than `react-bootstrap-table`, thanks

**Comment by stackptr** [comment]
After poking around with the code I see an undocumented `BootstrapTable` `options` prop key, `expandBodyClass` which seems to apply a class to an expanded row, although it is not removed when the row is collapsed.

Anyways, I'll be working on a PR for this over the next few days...

**Comment by AllenFang** [comment]
ohhh... yes, we have `expandBodyClass`, and you can control it very easy:

```js
const options = {
      expandBodyClass: function(row, rowIndex, isExpanding) {
        if (!isExpanding) { //collapsed
          return null;
        } else {
          return YOUR_CUSTOM_CLASS
        }
      },
      expandParentClass: 'custom-expand-parent'  // expandParentClass also accept callback function
    };
```
