### ISSUE TITLE
Is it possible to display multiple datafields in one column?

### ISSUE THREAD

**Issue by uynap** [AllenFang/react-bootstrap-table#1577]
For example, the front end got JSON `{"firstName": "David", "lastName": "Jones"}`. I would like to display it like: "Full Name" with the combination of firstName and lastName. 

Is it possible to do? Or I have to change the backend API ?

**Comment by prajapati-parth** [comment]
@uynap Yes. Please consider the following example
```jsx
const data = [
  {
    empId: 1,
    name: {
      firstName: 'David',
      lastName: 'Jones'
    }
  },
  {
    empId: 2,
    name: {
      firstName: 'xyz',
      lastName: 'abc'
    }
  }
]

function nameFormatter(cell, row) {
    return `${cell.firstName} ${cell.lastName}`
}

class MyTable extends React.component {
  render() {
    return (
      <BootstrapTable data={ data }>
        <TableHeaderColumn dataField='empId'>Employee Id</TableHeaderColumn>
        <TableHeaderColumn dataField='name' dataFormat={ nameFormatter }>Full name</TableHeaderColumn>
      </BootstrapTable>
    )
  }
}
```

Refer [this page](https://allenfang.github.io/react-bootstrap-table/example.html#column-format)
Section: Column Format with HTML String

**Comment by uynap** [comment]
Thank you for the detail example. prajapati-parth . 
I was considering formatting the data at Redux's middleware level. Then it's one time for all.

**Comment by prajapati-parth** [comment]
@uynap All right. I wasn't aware that you were using Redux. Well that is at least better than changing the backend API. :+1:
