### ISSUE TITLE
How to clear select all checkbox by function ?

### ISSUE THREAD

**Issue by ahyanarizky** [AllenFang/react-bootstrap-table#1578]
Hi, i'm managed to ask question here because i haven't found myself an answer after spend hourly in documentation. is there any hook or something to clear select all checkbox by a function ? I already found way to clear single checkbox by function but not found any documentation about clear the select all checkbox by function. did I miss something ? 

the reference I used to clear my single checkbox is this ([337](https://github.com/AllenFang/react-bootstrap-table/issues/337)). But I couldn't find anymore of my issue in this. Can you help me? thanks.

**Comment by AllenFang** [comment]
Sorry for lately reply, you can take following hacky way:

```js
this.refs.table.setState({ selectedRowKeys: [] });

<BootstrapTable ref='table' ...>
```
