### ISSUE TITLE
count drop down doesnt open

### ISSUE THREAD

**Issue by meghnaraok** [AllenFang/react-bootstrap-table#1580]
Say a user clicks on the count drop down a menu pops up and then user clicks else where on the page the menu disappears. When a user re clicks on the count drop down the drop down doesnt show up. Clicking another time brings up the menu. I see that this issue exists even on the examples page.

**Comment by AllenFang** [comment]
@meghnaraok yes,  it's a known issue currently.

**Comment by ziaulrehman40** [comment]
Duplicate issues like this should be closed in favor of one which is most verbal and with most details. like #1570

**Comment by AllenFang** [comment]
Fixed on `v4.1.1`, now the sizePerPage dropdown work well. Thanks
