### ISSUE TITLE
Custom Filter on a complex object

### ISSUE THREAD

**Issue by cedmalherbe8** [AllenFang/react-bootstrap-table#1584]
Hello,
I would like to filter data on a "complex object JSON".

My data is like this : 
users (Array object JSON):
- id
- firstName
- lastName
- roles (Array object JSON)
** id
** name
** code

I display roles column via  dataFormat but how to apply filter in a complex object ?

Thanks for your answer.

**Comment by AllenFang** [comment]
@cedmalherbe8 sorry for lately reply.

https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/search-format-table.js#L51-L52

There're two way to do it

1. Enable `filterFormatted` on `TableHeaderColumn`, which will allow `react-bootstrap-table` to filter the data by the result of `dataFormat`, but if your `dataFormat` contain some HTML tag, this ways is not good

2. Use `filterValue` to assign which field or data you wanna to be filtering

Let me know if you have any concern, thanks :)
