### ISSUE TITLE
Trouble with table width

### ISSUE THREAD

**Issue by foreveRush** [AllenFang/react-bootstrap-table#1585]
I use react-bootstrap-table and need the vertical scroll. My code:
```
<BootstrapTable data={products} hover>
      <TableHeaderColumn isKey dataField='id' width='10%'>
          Product ID
      </TableHeaderColumn>
      <TableHeaderColumn dataField='name'>
          Product Name
      </TableHeaderColumn>
      <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
</BootstrapTable>
```
This code works fine and I get the auto width resizable table. After that, I added next key:
`<BootstrapTable data={products} hover height='200px'>`
and got the problem with 100% width, instead of resizing table width I got one more scroll like in the picture below:
![peek 2017-09-01 18-07](https://user-images.githubusercontent.com/19690587/30022646-d63557ee-9174-11e7-9538-f73ba7520ff2.gif)

How can I fix this?

**Comment by AllenFang** [comment]
ah.. it's a known issue before for fixing some unalign issue.. Because `react-bootstrap-table` will adjust column width when vertical scroll bar existing, but there's a tricy way to avoid this dynamic adjust, you can add `printable` on `BootstrapTable`

**Comment by foreveRush** [comment]
Thanks, adding `printable` on `BootstrapTable` helped me.
