### ISSUE TITLE
Auto collapse expanded rows on sorting/filtering

### ISSUE THREAD

**Issue by elmoro666** [AllenFang/react-bootstrap-table#1586]
Hi

I tried to search previous issues, but couldn't find the answer there. 
Case: A user clicks on a row and it expands. The user then sorts the columns or chooses a different filter for one of the columns. Is it possible to have the expanded row auto-collapse in this case? It stays expanded with the default options (that I could find).

**Comment by AllenFang** [comment]
> I tried to search previous issues, but couldn't find the answer there.

Good behavior, thanks 👍 

About your case, I can design a prop to collapse all the expand rows after search/filter/sorting.

**Comment by nordicbondpricing** [comment]
That would be awesome!

**Comment by elmoro666** [comment]
That would be awesome!

**Comment by AllenFang** [comment]
HI @elmoro666 this feature is support on `v4.0.5`, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/auto-collapse.js) example, thanks

**Comment by elmoro666** [comment]
Brilliant! You're the man Allen

**Comment by constance-gb** [comment]
Hi Allen, is there a way, with autoCollapse or anything else, to automatically collapse open row(s) whenever the user expand a new one?

(I put parenthesis around the -s, because with such functionality, it should not be possible to have more than one row open at the time)

**Comment by constance-gb** [comment]
Nevermind, I succeed with onlyOneExpanding: true, much simpler solution!
