### ISSUE TITLE
I can't generate a dynamic TableHeaderColumns

### ISSUE THREAD

**Issue by carlosgg93** [AllenFang/react-bootstrap-table#1588]
I want generate 'x' bootstrap table with all its dynamics headers and when I try it, appear this errror:

> Warning: Each child in an array or iterator should have a unique "key" prop.

This is my code. How i can generate all dynamic headers with his correct key? Thanks!

```js
{ channelList.map ((channels, i) =>
                                    <BootstrapTable data={channels.data} maxHeight={200} scrollTop={ 'Bottom' } selectRow={ selectRowMeasures } options={ optionsSort } striped hover>
                                        {channels.header.map((headerLabel,x) => {
                                            return <TableHeaderColumn key={x} dataField={headerLabel.id} dataSort={ true }>{headerLabel.label}</TableHeaderColumn>
                                        })}
                                    </BootstrapTable>
                                )}
```

**Comment by AllenFang** [comment]
@carlosgg93 you forgot to assign `keyField` on `BootstrapTable`. It is tell `react-bootstrap-table` which column is unique. :)

**Comment by AllenFang** [comment]
are you sure that row have a `SINGAL` field?

**Comment by carlosgg93** [comment]
Yes, i think..

this is the header array:
 `{"id":"SIGNAL","label":"DVB-T","units":""},{"id":"POWER","label":"Power","units":"dBµV"},{"id":"CN","label":"C/N","units":"dB"},{"id":"STATUS","label":"STATUS","units":""},{"id":"MER","label":"MER","units":"dB"},{"id":"LM","label":"LM","units":"dB"},{"id":"CBER","label":"CBER","units":""},{"id":"VBER","label":"VBER","units":""}`

And this is the data array:
`{"DVB-T":"33","POWER":56.695156,"CN":42.012447,"MER":34,"CBER":0.000084,"VBER":1e-7,"LM":16.4,"STATUS":"LOCKED","SIGNAL":"33"}`

And this is the code:
`{ channelList.map ((channels, i) =>
                                    <BootstrapTable  data={channels.data} keyField='SIGNAL' maxHeight={200} scrollTop={ 'Bottom' } selectRow={ selectRowMeasures } options={ optionsSort } striped hover>
                                        {/*<TableHeaderColumn isKey dataField='id' width='1' dataSort={ true }></TableHeaderColumn>*/}
                                        {channels.header.map((headerLabel,x) => {
                                            return <TableHeaderColumn  dataField={headerLabel.id} dataSort={ true }>{headerLabel.label} {headerLabel.units}</TableHeaderColumn>
                                        })}
                                    </BootstrapTable>
                                )}`

**Comment by AllenFang** [comment]
HI @carlosgg93 your `keyFIeld` should be `id`.

**Comment by carlosgg93** [comment]
Hi @AllenFang ,I can not fix it, I have put keyField = "id" and the error still appears

And this is the code:
`{ channelList.map ((channels, i) =>
                                    <BootstrapTable data={channels.data} keyField="id" maxHeight={200} scrollTop={ 'Bottom' } selectRow={ selectRowMeasures } options={ optionsSort } striped hover>
                                        {channels.header.map((headerLabel) => {
                                            return <TableHeaderColumn  dataField={headerLabel.id} dataSort={ true }>{headerLabel.label} {headerLabel.units}</TableHeaderColumn>
                                        })}
                                    </BootstrapTable>
                                )}`

**Comment by AllenFang** [comment]
sorry I'm also confuse about your header array and data array. maybe a quick repo for me to reproduce will be good. and please make sure you understand your data. thanks

**Comment by carlosgg93** [comment]
Ok, The first I want to generate as many bootstrap tables as positions have in array channel list

This is the array channelList, in this case it has 2 positions,  channelList[0] contains a header and a data and the position 1 also :

`[{"header":[{"id":"SIGNAL","label":"DVB-T","units":""},{"id":"POWER","label":"Power","units":"dBµV"},{"id":"CN","label":"C/N","units":"dB"},{"id":"STATUS","label":"STATUS","units":""},{"id":"MER","label":"MER","units":"dB"},{"id":"LM","label":"LM","units":"dB"},{"id":"CBER","label":"CBER","units":""},{"id":"VBER","label":"VBER","units":""}],"data":[{"DVB-T":"33","POWER":56.695156,"CN":42.012447,"MER":34,"CBER":0.000084,"VBER":1e-7,"LM":16.4,"STATUS":"LOCKED","SIGNAL":"33"}]},{"header":[{"id":"SIGNAL","label":"DVB-T2","units":""},{"id":"POWER","label":"Power","units":"dBµV"},{"id":"CN","label":"C/N","units":"dB"},{"id":"STATUS","label":"STATUS","units":""},{"id":"MER","label":"MER","units":"dB"},{"id":"LM","label":"LM","units":"dB"},{"id":"CBER","label":"CBER","units":""},{"id":"LBER","label":"LBER","units":""}],"data":[{"DVB-T2":"53","DVBT2_PROFILE":"BASE","PLP":100,"POWER":52.102112,"CN":31.292336,"MER":35.599998,"CBER":0.000001,"LBER":0.000001,"LM":33.400002,"STATUS":"LOCKED","SIGNAL":"53,PROFILE=BASE,PLP=100"}]}]`

Then in render method I make a map that runs this array and creates "X" bootstrap tables (in this case 2)

this is the code: 
`{ channelList.map ((channels, i) => <BootstrapTable data={channels.data} keyField="id" maxHeight={200} scrollTop={ 'Bottom' } selectRow={ selectRowMeasures } options={ optionsSort } striped hover> {channels.header.map((headerLabel) => { return <TableHeaderColumn dataField={headerLabel.id} dataSort={ true }>{headerLabel.label} {headerLabel.units}</TableHeaderColumn> })} </BootstrapTable> )}`

**Comment by AllenFang** [comment]
oh, I see,  sorry for some wrong instruction, I think the `keyField` should be `SIGNAL` if it is unique. But you said even you set `keyField` as `SIGNAL` abut the problem still remain?  

I'll try again on my local, thanks

**Comment by carlosgg93** [comment]
Yes @AllenFang, when I set keyField to "SIGNAL" this error appears : 

> Warning:Each child in an array or iterator should have a unique "key" prop.

And I think that the field "SIGNAL" is unique, you can check it in the array channelList that I sent you in the previous message.

I wait your answer, Thanks!! :)

**Comment by AllenFang** [comment]
Sorry, I still can't reproduce this issue....
Following is my example code:


```js
const tables = [ {
  header: [ { id: 'SINGAL', label: 'singal' }, { id: 'POWER', label: 'power' } ],
  data: [ { SINGAL: 'tester1', POWER: 'power1' }, { SINGAL: 'tester3', POWER: 'example' }, { SINGAL: 'tester7', POWER: 'power1' } ]
}, {
  header: [ { id: 'SINGAL', label: 'singal' }, { id: 'POWER', label: 'power' } ],
  data: [ { SINGAL: 'tester1', POWER: 'power1' } ]
}, {
  header: [ { id: 'SINGAL', label: 'singal' }, { id: 'POWER', label: 'power' } ],
  data: [ { SINGAL: 'singal_1', POWER: 'power1' }, { SINGAL: 'tester3', POWER: 'example' }, { SINGAL: 'singal_3', POWER: 'power123' } ]
} ];

export default class BasicTable extends React.Component {
  render() {
    return (
      <div>
        {
          tables.map((table, i) => {
            return (
              <BootstrapTable key={ i } data={ table.data } keyField='SINGAL'>
                {
                  table.header.map(column => <TableHeaderColumn dataField={ column.id }>{ column.label }</TableHeaderColumn>)
                }
              </BootstrapTable>
            );
          })
        }
      </div>
    );
  }
}
```

Give me a simple repo or fully and minimal example for me to reproduce this problem, thanks
