### ISSUE TITLE
Trouble with onUpdate function in some cases

### ISSUE THREAD

**Issue by Charlie91** [AllenFang/react-bootstrap-table#1589]
I have some troubles with understanding of this example 
/examples/js/cell-edit/custom-cell-edit-table.js

I found this example very useful for me, but i can't understand this line
`const createNameEditor = (onUpdate, props) => (<NameEditor onUpdate={ onUpdate } {...props}/>);
`
I can't understand what occurs with the onUpdate function and where is its native code;
When i tried to console.log it, i discovered something like that:
```
ƒ () {
      return _this.__handleCustomUpdate__REACT_HOT_LOADER__.apply(_this, arguments);
 }
```

So, i can apply new data only with this function, but i can't edit it or change it.

I would be glad if somebody could help me either how to apply data with self-writed function or with how to edit onUpdate function.
Thank you.

**Comment by AllenFang** [comment]
> I can't understand what occurs with the onUpdate function

`onUpdate` function will do the cell editing immediately when you call it. so after call it, the cell value will be changed





> So, i can apply new data only with this function, but i can't edit it or change it.

yes, but user should change the data then you call this `onUpdate` function

Hope I answer you question, feel free to discuss with me if necessary :)
