### ISSUE TITLE
Date filter without comparators (one one comparator, i.e '=') 

### ISSUE THREAD

**Issue by mustafawm** [AllenFang/react-bootstrap-table#1591]
Hi,

Is there a way to remove comparators list from filters? I want to make `=` the only option.

I tried to provide a comparators array and limit it to `['=']` as you shown in this [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/number-filter-without-empty-option.js#L32#L35) but it doesn't seem to work! 

> "react-bootstrap-table": "^3.4.2"

Thanks in advance

**Comment by AllenFang** [comment]
sorry, it should be
`filter={ { type: 'DateFilter', dateComparators: [ '=' ] } }`

use `dateComparators` instead :)
