### ISSUE TITLE
Row with colspan?

### ISSUE THREAD

**Issue by VictorChen** [AllenFang/react-bootstrap-table#1592]
Is there anyway to render a row with a colspan? eg `Group row 1` and `Group row 2`:

<img width="776" alt="screen shot 2017-09-05 at 9 01 54 pm" src="https://user-images.githubusercontent.com/1408813/30089870-8ab8206c-927d-11e7-8d2e-e3736c6253ac.png">

**Comment by AllenFang** [comment]
This feature will be implement on `react-bootstrap-table2`, PR is welcome to version 1. thanks

Close it due to duplicated issues
