### ISSUE TITLE
Add row at index when sorting is active

### ISSUE THREAD

**Issue by Grinzzekatze** [AllenFang/react-bootstrap-table#1595]
Hi!
How is it possible to add an row at a specific index when sorting is active?
I get the correct index, but when I want to add the row, the row appears somewhere else.

Whats wrong with my code?
Thanks

```
Parent:
  addRowSorted(index) {
    let resources = this.state.resources.slice();
    var emptyLine = { id: _.random(-100000000000, 0) }
    resources.splice(index, 0, emptyLine);
    this.setState({ resources }, this.refs.table.added);
  }

  onSortChange(sortName, sortOrder) {
    let resources = this.state.resources.slice();
    this.setState({ resources }, this.refs.table.added);
}



Child:
    this.options = {
            sizePerPageList: [15, 25],
            sizePerPage: 15,    
            defaultSortName: this.state.sortName,
            defaultSortOrder: ['asc', 'asc'],      
            onSortChange: () => this.onSortChange
        };

onSortChange(sortName, sortOrder) {
        this.props.onSortChange;
    }

```

**Comment by Grinzzekatze** [comment]
Hi again! 
I found out that my code works, but the table renders it wrong. Could that be?

**Comment by AllenFang** [comment]
where's wrong when table rendering?

**Comment by Grinzzekatze** [comment]
For example: I have a Table with my products:

Ordering Number | Product | Price | Add Row
-- | -- | -- | --
1 | Milk | 1€ | +
2 | Coffee | 3€ | +
3 | Chocolate | 2,5€ | +
4 | Tea | 0,5€ | +
5 | Cake | 2€ | +

When I want to insert an empty row between Milk an Coffee after sorting by ordering number,  the table looks for example like this : 


Ordering Number | Product | Price | Add Row
-- | -- | -- | --
1 | Milk | 1€ | +
2 | Coffee | 3€ | +
3 | Chocolate | 2,5€ | +
4 | Tea | 0,5€ | +
  |   |   | +
5 | Cake | 2€ | +


but it should look like this:

Ordering Number | Product | Price | Add Row
-- | -- | -- | --
1 | Milk | 1€ | +
2 | Coffee | 3€ | +
  |   |   | +
3 | Chocolate | 2,5€ | +
4 | Tea | 0,5€ | +
5 | Cake | 2€ | +


The empty line appears somewhere else but my data-array is correct ( E.g  Milk, Coffee, “Empty with random id”, Chocolate, Tea, Cake).

**Comment by AllenFang** [comment]
so......  how do you insert a new row after sorting... or it's your feature request for adding an empty row after each sorting?

BTW, sorry for lately reply.

**Comment by Grinzzekatze** [comment]
I have buttons in each row in my table. I click at my button e.g in row 3 and then a empty row should appear in row 4. 

My function is : 

  addRowSorted(index, row) {
    debugger;
    let products = this.state.products.slice();
    var emptyLine = { id: _.random(-100000000000, 0) }
    products.splice(index + 1, 0, emptyLine);
    this.setState({
      products: products,
    })
  }

No it´s not a request. I simply want sort my table and after that I need to insert a row at a specific position. 
Adding the row without sorting works fine, but after sorting, the empty row appears somewhere else in the table ,though the empty row is at the correct position in my sorted array - only the table shows it somewhere else.

No problem - thank´s for the awesome component :)

**Comment by AllenFang** [comment]
ok, I see, some question I still want to confirm

1. how you handle the sorting? by yourself or `react-bootstrap-table` itself?
2. how do you know the sorted array?
3. could you please share some example value for `_.random(-100000000000, 0)`?
4. what column you sort? `Ordering Number`?

Thanks 👍

**Comment by Grinzzekatze** [comment]
Hey. 
I found my problem.  My problem was, that I filled my table with random entries (and so with random orderingnumbers) and somehow this causes problems when I want to add a new empty row. 
It works fine when I have my static entries :)

**Comment by AllenFang** [comment]
OK, let me know if you have any other question, thanks 👍
