### ISSUE TITLE
Expand component gets called MANY times

### ISSUE THREAD

**Issue by VictorChen** [AllenFang/react-bootstrap-table#1596]
I have a table with expandable rows and I'd like to fetch stuff when a row is expanded. However, it seems like ALL the expandable rows get rendered even before you expand a row. What would be the best way to have the expand component fetch data and display it?

Here's an example of what I mean:
https://jsfiddle.net/1s8reLw1/4/

I'd expect the expanded row to be called ONLY when it's visible

**Comment by VictorChen** [comment]
Actually I found a workaround by using `onExpand` callback and keeping track of which rows are expanded myself.

eg:
https://jsfiddle.net/1s8reLw1/5/

or is there a better way?

**Comment by AllenFang** [comment]
> I have a table with expandable rows and I'd like to fetch stuff when a row is expanded. However, it seems like ALL the expandable rows get rendered even before you expand a row

yes

> What would be the best way to have the expand component fetch data and display it?

Someone ask same question, but something need big change, so I plan to implement this feature on [`react-bootstrap-table2`](https://github.com/react-bootstrap-table/react-bootstrap-table2)



> Actually I found a workaround by using onExpand callback and keeping track of which rows are expanded myself.

yes, it's actually a workaround, it's only way to do it

thanks

**Comment by snootyCapri** [comment]
But the problem with this is the custom(...) does not work with selectRow.
