### ISSUE TITLE
Expanding a row causes the horizontal scrollbar to show up(Chrome Version 61.0.3163.79)

### ISSUE THREAD

**Issue by VictorChen** [AllenFang/react-bootstrap-table#1597]
When you expand a row, it causes the horizontal scrollbar on the table. eg:

<img width="1212" alt="screen shot 2017-09-07 at 2 29 35 pm" src="https://user-images.githubusercontent.com/1408813/30179077-239df3d6-93d9-11e7-808c-f2588bef74a3.png">

You can actually see this in the example page:
https://allenfang.github.io/react-bootstrap-table/example.html#expand

**Comment by AllenFang** [comment]
it's wired... I cant reproduce this issue.. anyone have the same problem here?

**Comment by prajapati-parth** [comment]
@AllenFang I checked with multiple resolution and multiple browsers, didn't see the scrollbar.

**Comment by VictorChen** [comment]
It shows up on the latest Chrome Version 61.0.3163.79 (Official Build) (64-bit)

**Comment by AllenFang** [comment]
thanks you guys feedback, I can reproduce it now, I will try to fix it. 👍

**Comment by prajapati-parth** [comment]
Sorry about that @AllenFang. My chrome was at 60.0.3112.101 version.

**Comment by wtellis** [comment]
Any luck with tracking down the cause?

**Comment by AllenFang** [comment]
I know the root cause,,, but it's hard to fix, I'm still try to find the best solution to patch this bug.

**Comment by wtellis** [comment]
FYI, looks like Chrome v62.0.3202.62 fixes the issue.

**Comment by VictorChen** [comment]
ah yep, can confirm it's fixed in `62.0.3202.62`

**Comment by AllenFang** [comment]
It's awesome :)
