### ISSUE TITLE
Way to configure encoding for CSV?

### ISSUE THREAD

**Issue by CoralSilver** [AllenFang/react-bootstrap-table#1599]
Is there a way to set encoding to ISO/IEC 8859-1 for example as latin characters, accents are not displaying correctly?

**Comment by AllenFang** [comment]
HI @CoralSilver sorry for lately reply, could you please give a simple text for me to have a expertiment?

I'm not sure if it is available, need more check, so please give me some raw data, thanks

**Comment by CoralSilver** [comment]
```
[
{
activity: "Reading Comprehension",
date: "04/01/17",
firstName: "José",
lastName:"Rodriguez",
score: "100%",
type: "lesson on demand",
}
]
```
See for example how "José" appears.

**Comment by AllenFang** [comment]
But actually I use UTF-8 encoding currently, after I test it, I still got the "José" in the CSV file. but I just open CSV file via VSCode instead of a excel or something like that. So see the "José" is correct for you? or you didn't see the "José" in your CSV file lol

**Comment by CoralSilver** [comment]
If I open it up in exel, José looks like this: JosÃ©

**Comment by AllenFang** [comment]
ok, got it, I'll try to fix it, thanks

**Comment by AllenFang** [comment]
@CoralSilver upgrade to `v4.0.4` and check again, I'm not sure if this patch can fix it because I dont have excel to test it lol.

**Comment by CoralSilver** [comment]
Are you going to release new version? Or do you want me to try updating local package with your change first?

**Comment by AllenFang** [comment]
I did something on `v4.0.0`, please use it but just not sure if fix your issue. I dont have excel to test.. lol
