### ISSUE TITLE
JSX instead of string in data field?

### ISSUE THREAD

**Issue by crowdwave** [AllenFang/react-bootstrap-table#1603]
Hi Allen,

Thanks again for your most excellent work!

I want to put JSX into my datafield instead of a string.

Can this be done?
thanks

**Comment by AllenFang** [comment]
Hi @crowdwave sorry for lately reply, I think you can use `dataFormat` to custom your cell
https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/column-format

Let me know if you have any question, thanks
