### ISSUE TITLE
Columns change width when i select or unselect a row

### ISSUE THREAD

**Issue by ofirgeller** [AllenFang/react-bootstrap-table#1606]
The change is bigger the first time a row is selected or un-selected but there is still a small change.

Anything I can do to understand this better and maybe fix it?

This is happening both when the select column is hidden and when it is not.

I am not using any custom styles or classes on the table.

Edit:

Seems like not specifying units in the columns width param had something to do with it. when i specify the change in the width in minimal. I was following the examples and there no units are given.

**Comment by AllenFang** [comment]
Actually, as I know, if the unit missing, I'll handle it, and there's no any issue about this I encounter before. anyway, please give the unit for your case, thanks
