### ISSUE TITLE
Do we have the difference of "onSelect" -> onUnselect?

### ISSUE THREAD

**Issue by Paul6552** [AllenFang/react-bootstrap-table#1607]
I couldn't find the function `onUnselect` in the documentation. I have to react on the behaviour if the user unselects the row.

(Table Radio button) Or is there a possibility that the user can`t unselect the row, so that the table has just one selected row every time.

Thanks

**Comment by AllenFang** [comment]
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/select-hook-table.js#L25

check the second argument, we dont have `onUnselect`, we use same callback but use a argument to tell you if it is select or not
