### ISSUE TITLE
Search result is reset when a rerender occur in the application with search and remote enabled.

### ISSUE THREAD

**Issue by widdde** [AllenFang/react-bootstrap-table#1608]
I'm using BootstrapTable with "search" option (search field in top right corner that search in every field in the table) enabled and remote enabled for cellEdit (remote(remoteObj) {remoteObj.cellEdit=true;}. As soon as a rerender occur in the application the table resets the search and all items will be shown again. The search textfield still contains the search string that was written.
I don't think this is the expected behavior. Shouldn't the table keep the filter even if a re-render, caused by calling setState, occur in the application? I have tracked it down to the remote method, as soon as I enabled "remote" in the table this behavior occurs, but not when it is disabled. 

Any suggestions?

EDIT: I am using the latest (4.0.0) version of React Bootstrap Table.

**Comment by AllenFang** [comment]
HI @widdde, what's situation cause the rerender?  after you saving the result of the cell editing?

**Comment by widdde** [comment]
Hi @AllenFang !
No, actually this happens when something in the view where the BootstrapTable is placed causing a state update, not really in the table itself.

To reproduce the "feature":
<BootstrapTable data={this.state.data} search remote={ this.remote } options={ {
                        onCellEdit: this.onCellEdit,} }><TableHeaderColumns...></BootstrapTable>

remote(remoteObj) {
remoteObj.cellEdit = true;
return remoteObj;
}

onCellEdit() {
Do something.. 
}

Create, for example, a div or a button or something that is updating the state on something on the page where you have the table..
<div onClick={() => this.onClick}>Click this</div>

onClick() {
this.setState({message: "Changing the state in the component",})
}

If you have searched something in the search field in the table, this will reset the search and show all data in this.state.data again.. As soon as i put the pointer in the searchfield again, the search result is back and when pressing the div, or button and changing another state the search is reset again and so on..

Hope you understand :)

**Comment by AllenFang** [comment]
sure, I can reproduce it now, i think it's a critical bug, I will fix ASAP, thanks

**Comment by widdde** [comment]
Thanks for fast responsen!
I found a workaround for this, by not enable remote but keep the onCellEdit: this.onCellEdit. This will still call the this.onCellEdit method even if remote is set to false. This doesnt reset the search but will still call the onCellEdit when edit a cell. Two separate things but now it works for me att the moment :)

**Comment by AllenFang** [comment]
@widdde bug fixed on `v4.0.4` please check it again, thank you 👍

**Comment by widdde** [comment]
Thank you very much for fast response to this bug! :)
One more question:
I Found a workaround for this, this workaround was to not set
remote={true}, but I could still use onCellEdit in options and the table
will call the onCellEdit. I thought this was bound to that remote was set
to true?

Kind regards,
Fredrik

**Comment by AllenFang** [comment]
hmm. actually, it's a bug anyway. but `remote` do effect on a lots of functionality.

**Comment by widdde** [comment]
Ok, thank you for your answer!
When will npm get the latest version (4.0.4)

Kind regards
Fredrik

Den 18 sep. 2017 3:19 em skrev "Allen" <notifications@github.com>:

**Comment by canvural** [comment]
This still happens to me at v`4.0.5`

Search input is resetted when `size per page` list is changed.
