### ISSUE TITLE
Cell height

### ISSUE THREAD

**Issue by vivekmago** [AllenFang/react-bootstrap-table#1610]
I am trying to use word wraping but have been unsuccesful at achieving it using the table. I have tried using the td classname and adjust row height but nothing seems to work. Could you advise the best way to achieve this in the component.

**Comment by VictorChen** [comment]
Add `white-space: normal;` css to the `td` ?

**Comment by vivekmago** [comment]
That worked perfect thanks


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Victor <notifications@github.com> Date: 9/13/17  10:46 AM  (GMT-05:00) To: AllenFang/react-bootstrap-table <react-bootstrap-table@noreply.github.com> Cc: vivekmago <vivekmago@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [AllenFang/react-bootstrap-table] Cell height (#1610) 
Add white-space: normal; css to the td ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AllenFang/react-bootstrap-table","title":"AllenFang/react-bootstrap-table","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AllenFang/react-bootstrap-table"}},"updates":{"snippets":[{"icon":"PERSON","message":"@VictorChen in #1610: Add `white-space: normal;` css to the `td` ?"}],"action":{"name":"View Issue","url":"https://github.com/AllenFang/react-bootstrap-table/issues/1610#issuecomment-329191165"}}}

**Comment by AllenFang** [comment]
@VictorChen thanks 👍
