### ISSUE TITLE
"columnClassName" method gets rendered as a class in colgroup?

### ISSUE THREAD

**Issue by VictorChen** [AllenFang/react-bootstrap-table#1611]
When you use `columnClassName`, eg:

```
function columnClassNameFormat(fieldValue, row, rowIdx, colIdx) {
  // fieldValue is column value
  // row is whole row object
  // rowIdx is index of row
  // colIdx is index of column
  return rowIdx % 2 === 0 ? 'td-column-function-even-example' : 'td-column-function-odd-example';
}

<TableHeaderColumn dataField='price' columnClassName={ columnClassNameFormat }>
```

The table will render the entire method as the class name of the `col`, eg:

```
<colgroup>
  <col class="">
  <col class="">
  <col class="function columnClassNameFormat(fieldValue, row, rowIdx, colIdx) {
    // fieldValue is column value
    // row is whole row object
    // rowIdx is index of row
    // colIdx is index of column
    return rowIdx % 2 === 0 ? 'td-column-function-even-example' : 'td-column-function-odd-example';
  }">
</colgroup>
```

You can see this from one of the examples here:
https://allenfang.github.io/react-bootstrap-table/example.html#style

is this expected?

**Comment by AllenFang** [comment]
lol,  thanks your mention, it's not a expected behavior, I'll fix it soon. thanks a lots

**Comment by AllenFang** [comment]
@VictorChen fixed on `v4.0.4`, and I'll update the docs, thanks

**Comment by kiftio** [comment]
Hi, when doing columnClassName="some-classname", the classname is no longer appearing on the <col> tag, is that intended?

**Comment by AllenFang** [comment]
@kiftio yes, any issues there?

**Comment by gyerzh** [comment]
@AllenFang, I have an issue that columnClassName property doesn't applied to `<col>` tag in a table.
What the goal of columnClassName if it doesn't add any class to `<col>` tag?? or I missed something and this property is used for other purposes?
