### ISSUE TITLE
between dates filter

### ISSUE THREAD

**Issue by mstruensee** [AllenFang/react-bootstrap-table#1612]
filter option for DateBetween to prompt for 2 dates? >= Date1 and <= Date2

if this does not exist ...
there should be no need to prompt for comparators unless you want >= vs > and <= vs <. default to both and allow to override to just use 1 of the option?

if it does exist ...
please send me in the right direction :)

thanks

**Comment by AllenFang** [comment]
@mstruensee , I see. I'll implement it on `react-bootstrap-table2`. thanks, but for now, there's only way for `react-bootstrap-table` is custom the column filter..  but it's will be a additional effort lol

**Comment by mstruensee** [comment]
Yes that was my work around.  It will be a nice to have OOB in v2, that seems to be a top requirement lately from my work experience.
