### ISSUE TITLE
Export value as integer. 

### ISSUE THREAD

**Issue by olaputin** [AllenFang/react-bootstrap-table#1613]
Now I have table with 3 columns with types:
string, integer, integer, (example of values:  Pre-Test | 3 | 100)

And after export I have the following values in .csv file:
"Pre-Test:","3","100"

Are there any way to get something like this: 
"Pre-Test:",3,100

Thanks in advance.

**Comment by AllenFang** [comment]
I will support this enhancement, thanks

**Comment by AllenFang** [comment]
HI @olaputin this fixed on `v4.0.5` and you can add `csvFieldType='number'` on `TableHeaderColumn` to specify the type of column when exporting csv. thanks

**Comment by olaputin** [comment]
Thanks a lot. I appreciate your efforts and this library well.

**Comment by AllenFang** [comment]
BTW, [`react-bootstrap-table2`](https://github.com/react-bootstrap-table/react-bootstrap-table2) already in development, feel free to ask any useful feature :)  I hope most of user can switch to `react-bootstrap-table` finally.  But we still have a long road need to walk.
