### ISSUE TITLE
Sorting on empty fields is wonky and unpredictable

### ISSUE THREAD

**Issue by stevelacerda7** [AllenFang/react-bootstrap-table#1618]
I took a screen capture of what's going on. I click on sort on columns with empty fields and the sort is really unpredictable. I can't really tell what it's doing.

[https://drive.google.com/file/d/0B0jVs-9rYRN8Y3c0eTFDUGU0eUE/view?usp=sharing](url)

```
<BootstrapTable 
   printable
   bodyStyle={{overflow: 'overlay', maxHeight: height}}
   ref='table' 
   data={ this.state.rows } 
   striped={ true } 
   hover={ true } 
   search={ true }
   searchPlaceholder="Search..."
   scrollTop={ 'Top' }
   keyField='timestamp'
   options={ options }
   exportCSV={ true }
   csvFileName="alerts"
>
   { headers }
</BootstrapTable>
```

And this is my headers code:

```
return columns.map((header, id) => {
   if (header === "__health") {
      return (
         <TableHeaderColumn key={ id } dataField={ header } hidden={ true }>{ header.toUpperCase() }</TableHeaderColumn>
      )
   } else if (header.toLowerCase() === "timestamp") {
      return (
         <TableHeaderColumn key={ id } dataField={ header } dataSort={ true } dataFormat={ this._dateFormatter }>{ header.toUpperCase() }</TableHeaderColumn>
      )
   } else {
      return (
         <TableHeaderColumn key={ id } dataField={ header } dataSort={ true } dataFormat={ this._statusStyler }>{ header.toUpperCase() }</TableHeaderColumn>
      )
   }
});
```

Any ideas? I would think empty td's would sort to one end of my table on ASC sort, then the other end on DESC sort.

**Comment by AllenFang** [comment]
the empty field means empty string?

**Comment by stevelacerda7** [comment]
Yes, exactly. So the DOM ends up looking like:

`<td tabindex="5" class="" style="text-align: left;"><div></div></td>`

Each time I sort, the sorting is different. Not exactly sure what it's doing. 

I would like to commend you for this project by the way, I love it.

**Comment by AllenFang** [comment]
I'll going to check this problems, but need some time, thanks 👍

**Comment by stevelacerda7** [comment]
Okay, so I messed around a bit, and found _sort in react-bootstrap-table.js and it looks like that's the culprit. It checks for null, but not undefined values. I changed the code and it seems to work without any adverse consequences: 

```
if (a[sortDetails.sortField] === null || a[sortDetails.sortField] === undefined) {
   var valueA = '';
} else {
   var valueA = a[sortDetails.sortField];
}
```

What do you think?

**Comment by stevelacerda7** [comment]
Now, my problem is that our code base rebuilds the library by pulling it from npm everytime. So, I can't make any local changes and have it persist? Any ideas?

**Comment by prajapati-parth** [comment]
@stevelacerda7 
1) Fork react-bootstrap-table and clone it locally
2) make required modifications
3) build react-bootstrap-table by `gulp prod`
4) install it from local rather than npm
   eg. if your directory structure is something like this
```
  ├── your project
     /src
     /dist
     package.json
  ├── react-bootstrap-table
     /src
     /dist
     /css
     package.json
```
from the root of your project directory run `npm install ../react-bootstrap-table`
5) When new features are pushed to react-bootstrap-table, you can pull upstream, build, uninstall and reinstall from local.

**Comment by stevelacerda7** [comment]
Unfortunately, our build process automatically pulls directly from npm, so anything in the package.json file will be pulled from remote repo. Instead, I just imported react-bootstrap-table.js.min into my component, not great, but works for now.

**Comment by AllenFang** [comment]
HI @stevelacerda7 is https://github.com/AllenFang/react-bootstrap-table/pull/1640 trying to fix this issue?

**Comment by AllenFang** [comment]
https://github.com/AllenFang/react-bootstrap-table/pull/1644
