### ISSUE TITLE
how to install the module from source

### ISSUE THREAD

**Issue by venkat-vs-id** [AllenFang/react-bootstrap-table#1620]
Hi All,

can someone help me how to install this module from source? I'm making little changes to the source and I want to use that install of the original 

1) I cloned this git-repo
2) I did npm install <path-to-my-local-repo>
3) I can see the react-bootstrap-table (link) folder in my node_modules folder
4) but when i use webpack to build my code, it says 

Module not found: Error: Can't resolve 'react-bootstrap-table' in

**Comment by prajapati-parth** [comment]
Did you build the source? As per [package.json](https://github.com/AllenFang/react-bootstrap-table/blob/master/package.json#L5) `index.js` within `lib` dir is accessed. 

Please try running `glup prod` to build the source.
Thanks.

**Comment by venkat-vs-id** [comment]
Thanks Parth. I resolved that issue and stuck with a new one

Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. This is issue only comes when Im building the module from my local source and not when I do a npam install react-bootstrap-table

my npm verson: 5.4.2
react-bootstrap-table version:4.0.3

**Comment by prajapati-parth** [comment]
@venkat-vs-id this is there are two copies of React at your end. I faced the same issue quite a while ago when I used npm-link, and solved it by tweaking the `externals` part of my webpack config. You may refer either (this)[https://stackoverflow.com/a/32444088], [this](https://github.com/callemall/material-ui/issues/6345#issuecomment-286929703) or [this](https://facebook.github.io/react/warnings/refs-must-have-owner.html).
Out of which the second one is more better.

@AllenFang This is not an issue related to installing from source, and can be closed.
Thanks.

**Comment by AllenFang** [comment]
> this is there are two copies of React at your end. I faced the same issue quite a while ago when I used npm-link, and solved it by tweaking the externals part of my webpack config. You may refer either this, this or this.

👍 👍 👍
