### ISSUE TITLE
Tab to move to next field Issue on Custom Cell Editor

### ISSUE THREAD

**Issue by RejinR** [AllenFang/react-bootstrap-table#1621]
Hi.. I was trying to use custom cell editors and was having an issue with TAB to move to the next cell and edit like how it works in the in built cell editors.. 

I could not get focus on the next cell when pressing TAB from my custom editor..

[](http://allenfang.github.io/react-bootstrap-table/example.html#celledit)
In the example page also I don't get the TAB to work..

Also is there any reason why SHIFT+TAB isn't working on cell edits, to move to previous cell?? Shift+Tab doesn't work in the example page as well..

**Comment by AllenFang** [comment]
HI @RejinR sorry for lately reply,

1. For the custom cell editor, please implement `focus` method, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/cell-edit/custom-cell-edit-table.js#L45-L47), because we dont know your DOM structure.
2. we dont support SHIFT+TAB, PR is welcome.

**Comment by chris-allnutt** [comment]
This is still an issue:
`    return (
      <select
        ref="selectRef"
        className="col-md-12"
        value={ this.state.year }
        onChange={ this.updateData } >
          {yearOptions.map(year => (<option key={ year.value } value={ year.value }>{ year.name }</option>))}
      </select>
    );`

Is my dom, focus is implemented.  I'm using this for 2 cells in the same row.  Hitting tab from this one does not focus on the next editor.

**Comment by Moggieggwp** [comment]
I have the same problem

**Comment by glennlosentes** [comment]
Hi any updates on hitting TAB to focus on the next editor?

**Comment by vademyanchik** [comment]
The same problem

**Comment by glennlosentes** [comment]
I have a custom editor (autocomplete input) and made it work by setting the cellEditProp only mode:'click' nothing else and I set beforeSaveCell function in my case.
