### ISSUE TITLE
How to reach data in insertRow?

### ISSUE THREAD

**Issue by widdde** [AllenFang/react-bootstrap-table#1625]
I'm implementing a function to insert a row to the table and to actually save this data it will be sent to our server.
But I can not find a way to reach the inserted data in one of the methods?

I am using <InsertModalFooter> and have set insertModalFooter to this.createCustomModalFooter.

`createCustomModalFooter = (closeModal, save) => {

}`

My question is: 
Where can I reach the data inserted in the textfields? 
The provided parameters are only the closeModal and a save-function? 
I'm sure I have missed something, I', sure there is a way to reach the data.. I need to send this to the server to actually store it in the database.. 
Or do I need to totally custom the insert modal ? 

Thanks in advance
Fredrik

**Comment by AllenFang** [comment]
> Or do I need to totally custom the insert modal ?

Probably no, if you want custom modal, you can use it.

if you want the new data, you can try https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/insert-row-table.js#L34

Let me know if you have any question, thanks

**Comment by stevenqzhang** [comment]
@AllenFang I'm having a similar situation- trying to save the entire table state to server after row additions and subtractions are done. It seems like the `data` prop for the `BootstrapTable` is NOT updated whenever we add a row or delete a row, so you recommend we do that manually in `onAfterInsertRow` and `onAfterDeleteRow`?

**Comment by PedroVillacrecesCiudad** [comment]
Hi guys,

Related to this. How to delete the row if something is wrong storing data into your server... I mean... having this `const options = {
  afterInsertRow: onAfterInsertRow   // A hook for after insert rows
};` and then in my onAfterInsertRow and calling to my API in terms of saving this data. If my server would fail for some reason... How can I delete the row inserted?

Thanks guys!

**Comment by passionInfinite** [comment]
@AllenFang If we have the event of `onBeforeInsertRow` so that we can send the request to the server and if successful we can proceed further otherwise we will not.
