### ISSUE TITLE
sizePerPage title

### ISSUE THREAD

**Issue by holzfelix** [AllenFang/react-bootstrap-table#1627]
Hi there,

is it possible to add a label / title to the sizePerPage dropdown?

Thanks

**Comment by prajapati-parth** [comment]
@holzfelix One way that I know is to create a custom sizePerPage dropdown. You can find it [here](https://allenfang.github.io/react-bootstrap-table/example.html#custom) (section: `Default Custom SizePerPage DropDown` and `Fully Custom SizePerPage DropDown` ).
This will be like more coding for a minor feature.

Tell me if this is useful.
Thanks.

**Comment by AllenFang** [comment]
@holzfelix like @prajapati-parth mention above, you need to custom it. thanks
