### ISSUE TITLE
RemoteStoreSorting inside remote-store-all.js

### ISSUE THREAD

**Issue by asciicode** [AllenFang/react-bootstrap-table#1629]
class typo error

**Comment by prajapati-parth** [comment]
@asciicode The class name needs to be `RemoteStoreAll` instead of `RemoteStoreSorting`, is that what you are indicating?

**Comment by asciicode** [comment]
yup

**Comment by prajapati-parth** [comment]
Pull requested #1635

Thanks @asciicode :+1:
