### ISSUE TITLE
Cell Edit on filtered column, changes all rows 

### ISSUE THREAD

**Issue by masoudmanson** [AllenFang/react-bootstrap-table#1630]
When there are no filters on table columns, cell editing works just fine.
But when I set a filter on a column (Assume there is a weekday column on table, and you select filter on Saturdays), if you edit a single cell from any column now, the whole column values update. This is strange :0

**Comment by AllenFang** [comment]
any example code to reproduce this issue? please keep it simple and minimal, dont mixing too many thing, that's focus on problems, thanks

**Comment by masoudmanson** [comment]
Wow :|
Everything is just fine , My Bad
the table id field was null, so rows were not unique. SRY BTW

`<TableHeaderColumn hidden isKey dataField='id'>#</TableHeaderColumn>`

Never Trust the data back-end guys send you :)))
