### ISSUE TITLE
Dynamic Column headers 

### ISSUE THREAD

**Issue by narendravenkata** [AllenFang/react-bootstrap-table#1634]
Hi @AllenFang  Your table was very much useful to me. I am trying to display the following data in Bootstrap table.

data=[{totalCount:1243},{letterCodes:{01:898,01INT:345}}]

The table should look like as follows 
![capture](https://user-images.githubusercontent.com/28738596/30674458-ddfbd73c-9e3f-11e7-8096-569430156af2.PNG)

The sub object letterCodes is dynamic and we should generate columns based on that object ,I tried using map, with help of previous issues raised regarding same thing ,but I was not able to get it . Your help is appreciated

**Comment by prajapati-parth** [comment]
@narendravenkata If you can format your data to something like this you can use the below mentioned approach
```json
[
    {
        totalCount:1243,
        letterCodes:{
            01: 898,
            01INT: 345
        }
    }
]
```

For 2nd and 3rd column both, use `dataField` as `letterCodes` and then use `dataFormat` to return value against key `01` and `01INT` for 2nd and 3rd column respectively. 

```jsx
const products = [
  {
    totalCount: 1243,
    letterCodes: {
      '01': 898,
      '01INT': 345
    }
  }
];

export default class BSTable extends React.Component {
  render() {
    const thc = [];

    for (const item in products[0].letterCodes) {
      if (item) {
        thc.push(
          <TableHeaderColumn key={ item } dataField='letterCodes' dataFormat={ cell => cell[item] }>{ item }</TableHeaderColumn>
        );
      }
    }

    return (
      <div>
        <BootstrapTable data={ products }>
          <TableHeaderColumn isKey={ true } dataField='totalCount'>Total Count</TableHeaderColumn>
          {
            thc
          }
        </BootstrapTable>
      </div>
    );
  }
}
```

**Comment by narendravenkata** [comment]
@prajapati-parth Thanks for your help, It works good with the formatting of data but when I am using options like exportCSV={true} , i am having an error 

```
<BootstrapTable data={ products } exportCSV={true}>
                                    <TableHeaderColumn isKey={ true } dataField='totalCount'>Total Count</TableHeaderColumn>
                                    {
                                      thc
                                    }
                                  </BootstrapTable>
```

TypeError: Cannot read property 'isKey' of undefined

I tried many options but not able to find the cause of the error

**Comment by narendravenkata** [comment]
@prajapati-parth  I have solved the issue by generating all columns and using keyField 
`<BootstrapTable data={ jobLetterCodeCountReportData } keyField='totalCount' striped hover pagination={true} search options={options} csvFileName={this.getFilename} exportCSV={true} >
{
                                      thc
                                    }
                                  </BootstrapTable>`

But here with multiple objects in the products data like below

```
 const products = [
            {
              totalCount: 1243,
              letterCodes: {
                '01': 898,
                '01INT': 345
              }
            },
            {
                totalCount: 1000,
                letterCodes: {
                  '01': 450,
                  '01INT': 350,
                  '51CC':200
                }

            },
            {
                totalCount: 750,
                letterCodes: {
                  '50A': 400,
                  '41HV': 200,
                  '50CC':150
                }

            }
          ];
```
the table should look like this 
![whatsapp image 2017-09-21 at 2 54 44 pm](https://user-images.githubusercontent.com/28738596/30715720-f75e572a-9edc-11e7-8ecb-17a8370927b2.jpeg)

**Comment by prajapati-parth** [comment]
@narendravenkata At the line where we do `thc.push()` you can do like this
```jsx
for (const item in products[0].letterCodes) {
    thc.push(
        <TableHeaderColumn key={ item } dataField='letterCodes' dataFormat={ cell => cell[item] ? cell[item] : '0' }>{ item }</TableHeaderColumn>
    );
}
```
And according to the API design principles, response should contain keys with `null` values when the value against them is not available(or similar objects should be contained in the array). So your products array should look something like this
```
const products = [
    {
        totalCount: 1243,
        letterCodes: {
            '01': 898,
            '01INT': 345,
            '50A': null,
            '51CC':null,
            '41HV': null,
            '50CC':null
        }
    },
    {
        totalCount: 1000,
        letterCodes: {
            '01': 450,
            '01INT': 350,
            '50A': null,
            '51CC':200,
            '41HV': null,
            '50CC':null
        }

    },
    {
        totalCount: 750,
        letterCodes: {
            '01': null,
            '01INT': null,
            '50A': 400,
            '51CC':null
            '41HV': 200,
            '50CC':150
        }

    }
];
``` 
Else you'll have to make major modifications in your front-end code due to the kind of data that you mentioned.

Thanks.

**Comment by narendravenkata** [comment]
@prajapati-parth  Thanks for the help, the letter codes are dynamic and are generated based on various other reports , so every object doesnt contain all lettercodes, I have created data as follows


```javascript
        var thc = [];
        var finalcolumns=[];
        var columns=[];
        thc.push(<TableHeaderColumn dataField='totalCount'>Total Count</TableHeaderColumn>,
            <TableHeaderColumn dataField='cycleDate'>Cycle Date</TableHeaderColumn>,
            <TableHeaderColumn dataField='cycleComments'>Cycle Comments</TableHeaderColumn>
        );
        for(var i=0;i<products.length;i++){
            var l=Object.keys(products[i].letterCodes).length;
            for(var j=0;j<l;j++){
                columns.push(Object.keys(products[i].letterCodes)[j])
            }            
        }
        finalcolumns=Array.from(new Set(columns));
        console.log(finalcolumns);
        for(var i=0;i<finalcolumns.length;i++){
            thc.push(
                <TableHeaderColumn dataField={finalcolumns[i]} >{finalcolumns[i]}</TableHeaderColumn>
            );
        }
        for(var i=0;i<products.length;i++){
            _.merge(products[i],products[i].letterCodes);
            console.log(products[i]);
        } 
```

and then used thc in my bootstrap table output as
![capture](https://user-images.githubusercontent.com/28738596/30729817-e971b332-9f27-11e7-9081-88c0d0566500.PNG)

**Comment by prajapati-parth** [comment]
@narendravenkata Nice approach :+1:. But this code might get a little hard to maintain, debug and will be hard to implement some new modifications here.
How about the approach to modify the products array after a receiving response? That way you can even separate out a function that modifies your response.

**Comment by AllenFang** [comment]
thanks your help @prajapati-parth 👍

**Comment by ZameerAhmed** [comment]
I used same procedure to create dynamic data but i am getting this error " Each child in an array or iterator should have a unique "key" prop." @narendravenkata can you help how you used key here

**Comment by narendravenkata** [comment]
@ZameerAhmed you need to provide a unique key for each child ,so that it helps rendering the component  to distinguish. please add key={} some unique value for each TableheaderColumn
```javascript
for (var i = 0; i < finalcolumns.length; i++) {
                if (columns[i]) {
                    thc.push(
                        <TableHeaderColumn width='100' dataField={finalcolumns[i]} csvHeader={finalcolumns[i] + ' Count'} key={i + 5} >{finalcolumns[i]}</TableHeaderColumn>
                    );
                }
            }
```

**Comment by zubairpaizer** [comment]
```js
<BootstrapTable data={categories}
                search={true}
                scrollTop={ 'Bottom' }
                pagination={true}
                multiColumnSearch={ true } >
{
  categories.map((category, index) => {
    if(index == 0){
      return <TableHeaderColumn key={category.name} isKey dataField='name'>{ category.name }</TableHeaderColumn>
    }else{
      return <TableHeaderColumn key={category.name} dataField='name'>{ category.name }</TableHeaderColumn>
    }
  })
}
</BootstrapTable>
