### ISSUE TITLE
expandColumnOptions does not work

### ISSUE THREAD

**Issue by susannakosic** [AllenFang/react-bootstrap-table#1636]
Hi :)
I was trying expandColumnOptions to pass into BootstrapTable a callback for expandColumnComponent, as described [here](https://allenfang.github.io/react-bootstrap-table/docs.html#expandColumnOptions) literally:
```javascript
<BootstrapTable //... data, options, tableHeaderClass and tableBodyClass passed into and working				
  expandableRow={() => {return true;}}
  expandComponent={this.getExpandableContent.bind(this)}
  expandColumnOptions={{
      expandColumnVisible: true,
      expandColumnComponent: expandColumnComponent,
      columnWidth: 100
  }}>
   {/* ... */}
</BootstrapTable>
```
having:
```javascript
const expandColumnComponent = ({isExpandableRow, isExpanded}) => {
   debugger;
   let content = '';
   if (isExpandableRow) {
      //as in docs
   }
};
```

This option is not having any effect on the rendered table. No errors in the console, and debugger is never reached.
Any idea on this? Thanks a lot!

**Comment by AllenFang** [comment]
@susannakosic sorry for lately reply, is it solved?

**Comment by susannakosic** [comment]
Upgrading to last stable sorted it.
