### ISSUE TITLE
Persistent filter state

### ISSUE THREAD

**Issue by JcBernack** [AllenFang/react-bootstrap-table#1637]
I'm building a small wrapper to connect the table to our redux-store and persist sort and filter state. This way the state of the table will remain even if navigating somewhere else and then coming back to the table.

For sorting this was really easy:

- Add a handler to `onSortChange` which persists `sortName` and `sortOrder` to the store.
- Add `sortName` and `sortOrder` from the redux-store to the options of the table.

Now I wanted to add filtering in the same way, but it seems that is not possible, because the options object does not allow setting the filters, correct? The only way I see to set the filters from outside the table is using a `ref` on each column and calling `applyFilter`, but I really would like a generic approach, without having to touch each column.

Any suggestions how this could be done?

**Comment by JcBernack** [comment]
I just found out that I can set all filters at once by calling `handleFilterData(filterState)` on a ref to the table, but this has two problems:

- The filters are applied correctly, but the input fields are not set. They remain empty.
- And it seems that I can not call `handleFilterData` immediately on render:

      setFilterState(tableRef) {
          tableRef.handleFilterData(filterState); // does not work, filters are cleared
          setTimeout(() => tableRef.handleFilterData(filterState), 2000); // works...
      }
      <BootstrapTable ref={tableRef => this.setFilterState(tableRef)} .... />

**Comment by JcBernack** [comment]
The input fields not getting set can be reproduced using the example here:
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/text-filter-programmatically.js#L29

`applyFilter` on the column ref works, while `handleFilterData´ on the table ref does not.

**Comment by AllenFang** [comment]
@JcBernack sorry for lately reply. Firstly, `applyFilter` is only way to do it now, `handleFilterData` is also work but it's legacy way before. I usually suggest to use `applyFilter`.

The other solution is use `filter.defaultValue`, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/text-filter-with-default-value.js) example for text filter. Let me know if you have any question :)  thanks

**Comment by JcBernack** [comment]
Both methods you suggest would need changes on the columns, but I would really like to get/set the filter state at the table and not touch the columns.

Here is my redux connected table, which works perfectly for sorting. It can be used as a direct replacement for the `BootstrapTable` as it will pass through all props. This component does not know about the columns actually used, it will just catch any changes to sorting and fire a redux action.

```
import React, { Component, PropTypes } from 'react';
import { BootstrapTable } from 'react-bootstrap-table';
import { connect } from 'react-redux';
import { setOrderBy } from '../../../redux/actions/reduxBootstrapTable';

@connect((state, props) => ({
  tableState: state.reduxBootstrapTable[props.tableKey],
}), {
  setOrderBy,
})
export default class ReduxBootstrapTable extends Component {
  static propTypes = {
    tableKey: PropTypes.string.isRequired,
    tableState: PropTypes.object,
    children: PropTypes.node,
    setOrderBy: PropTypes.func,
  };

  handleSortChange = (sortName, sortOrder) => {
    this.props.setOrderBy(this.props.tableKey, sortName, sortOrder);
  };

  render() {
    const { tableState, options, children, ...rest } = this.props;
    // prevent passthrough to BootstrapTable
    delete rest.tableKey;
    delete rest.setOrderBy;
    return (
      <BootstrapTable
        options={{
          ...tableState,
          onSortChange: this.handleSortChange,
          ...options,
        }}
        {...rest}
      >
        {children}
      </BootstrapTable>
    );
  }
}
```

I don't see a way to do the same with filtering with you suggestions.

**Comment by AllenFang** [comment]
The only two solutions are mentioned above, if you use `props.children`, i think you can still use `React.Children` API to operate on them, but sometime, it's not a good practice, but anyway, it depends
