### ISSUE TITLE
Adding bootstrap styles to rows dynamically

### ISSUE THREAD

**Issue by jsaddiction** [AllenFang/react-bootstrap-table#1643]
How is the most effective way to format a row based on a cells contents?

If I had a row with a date before today it should be styled with "className='danger'"
A row with a date within a week is should be styled with "className='warning'"
A row with a date more than a week but less than a month should be styled with "className='info'"

I only see "selecting a row" but its not really what I am trying to do, nor do I understand its implementation or how I could use it with multiple styles.

Thanks in advance!!  Love the table!!

**Comment by prajapati-parth** [comment]
@jsaddiction You can use `trClassName` prop. You can use it as follows 
```jsx
class MyTable extends React.Component {
  render() {
    return (
      <BootstrapTable data={ products } trClassName={this.rowClassNameFormat}>
          <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }

  rowClassNameFormat(row, rowIdx) {
    if (row.date < todayDate) {
      return 'danger'
    } else if () {
    } else {
    }
    // adjust as needed here
  }
}
```
Apparently, the documentation has a mismatch here so I couldn't point you to the link.

@AllenFang Section `Use trClassName as Function on <BootstrapTable>` of [this page](https://allenfang.github.io/react-bootstrap-table/example.html#style) has a gist mismatch. I've updated the gist [here](https://gist.github.com/prajapati-parth/cad382dd876183c2507a161397e515cb) to better match the section example. However I'm not sure if more parameters are returned for function `rowClassNameFormat `.

**Comment by AllenFang** [comment]
@jsaddiction `trClassName` will be your answer.
@prajapati-parth thanks for quick response, and the gist already updated 👍

**Comment by jakedurell** [comment]
I am trying something similar on the code below, and rowClassNameFormat is not getting called as the console.log is not printing.

`import React, { Component } from 'react'
import { BootstrapTable, TableHeaderColumn }
    from 'react-bootstrap-table'
import 'Table.css'
import '../node_modules/react-bootstrap-table/dist/react-bootstrap-table-all.min.css'
import 'react-bootstrap-table-next/dist/react-bootstrap-table2.min.css';



class Table3 extends Component {
    render() {
        return (
            <div>
                <BootstrapTable data={this.props.data} trClassName={this.rowClassNameFormat}>
                    <TableHeaderColumn isKey dataField='id'>
                        ID
                    </TableHeaderColumn>
                    <TableHeaderColumn dataField='name'>
                        Name
                    </TableHeaderColumn>
                    <TableHeaderColumn dataField='value'>
                        Value
                    </TableHeaderColumn>
                </BootstrapTable>
            </div>
        )
    }
}

function rowClassNameFormat(row, rowIdx) {
    // row is whole row object
    // rowIdx is index of row
    console.log("Row is " + row)
    return row['name'] === 'George Michael' ?
        'GeorgeMichael-Row' : 'Other-Row';
}


export default Table3`
