### ISSUE TITLE
Button for Printing table

### ISSUE THREAD

**Issue by josefheld** [AllenFang/react-bootstrap-table#1645]
Hi, 
maybe my researches for that were not thorough enough...
I need a button to print a table. 
Some of my tables are displayed in a modal window. The normal browser print is not sufficient.
Any idea or suggestions if that is possible?

**Comment by prajapati-parth** [comment]
@josefheld Will exporting your table to CSV and then print serve the purpose? If so please find it [here](https://allenfang.github.io/react-bootstrap-table/example.html#custom), section: `Default Custom Export CSV Button`.

**Comment by AllenFang** [comment]
@josefheld I think we haven't this kind of feature.. sorry. let me know if you have any concern or idea, thanks
