### ISSUE TITLE
Build Custom Filter outside the React Bootstrap Table

### ISSUE THREAD

**Issue by eduAbreu** [AllenFang/react-bootstrap-table#1647]
Hi @AllenFang, for start let me congratulate you for this amazing project, this really is a life saving, and I would like to know if it's possible to create some filter components, for example build a text input, outside the table and have access to the trigger events that filter the table.

Let me know if you have any doubt about the question.

Best Regards and great work on this ;)

**Comment by AllenFang** [comment]
@eduAbreu thanks :) and your requirement is totally available in `react-bootstrap-table`. but something I need to confirm, when you filtering the data, do you need to specify a column? or maybe actually, you need a search on the data?

**Comment by eduAbreu** [comment]
@AllenFang thanks for the quick response.
I don't really need on the specific column, so you suggest instead of trying to trigger the filter method I do a search on table?

**Comment by AllenFang** [comment]
@eduAbreu sorry for lately reply, and yes, you should using `search`, `BootstrapTable` have a exposed API: `handleSearch` can help you. call with with the search text. ;)
