### ISSUE TITLE
Pull select option values from row

### ISSUE THREAD

**Issue by 5tormTrooper** [AllenFang/react-bootstrap-table#1651]
Is there a way to populate the options of a select based the values of a row?
```
<TableHeaderColumn
  dataField={name}
  editable={{
    type: 'select',
    options: { values: this.createOptions() }
  }}>
	{name}
</TableHeaderColumn>
```
In the example above, `this.createOptions()` would need to have access to the row, as each row has a different set of options. So something like `this.createOptions(row)`. I could then use that method to output the options stored in that row.
I can see how to edit the value of the field using the `dataFormat` attr, but not how to edit the options associated with the cells in that column.

Appreciate the help.

**Comment by AllenFang** [comment]
@5tormTrooper sorry for lately reply, and I think your requirement is very common and necessary, I'll implement it ASAP, thanks 👍

**Comment by AllenFang** [comment]
@5tormTrooper actually, this feature was implement in two month ago..

For example:

```js
function createOptions(row) {
  // must return an array, for example: ['dog', 'cat']
}

<TableHeaderColumn
  dataField={name}
  editable={{
    type: 'select',
    options: { values: this.createOptions }
  }}>
	{name}
</TableHeaderColumn>
```

But if you want to control the the text and the value of each option, you can:

```js
function createOptions(row) {
  // must return an array, for example: [{
    text: 'DOG',
    value: 'dog_code'
  }, {
    text: 'CAT',
    value: 'cat_code'
  }]
}

<TableHeaderColumn
  dataField={name}
  editable={{
    type: 'select',
    options: { values: this.createOptions, textKey: 'text , valueKey: 'value' }
  }}>
	{name}
</TableHeaderColumn>
```


Let me know if you have any questions, thanks

**Comment by 5tormTrooper** [comment]
@AllenFang in your example, `this.createOptions` doesn't fire on its own. I need to add `this.createOptions()` for it to call the method. When I console log the row in `createOptions(row)`, it returns `undefined`. Are you certain the row is implicitly passed as an argument? Logging `arguments` in the return method doesn't show anything for me.

**Comment by AllenFang** [comment]
I think it's work well
```js
class EditTypeTable extends React.Component {
  // ....

  jobTypes(row) {
    if (row.id > 2) {
      return [ 'A', 'B' ];
    } else {
      return [ 'B', 'C', 'D', 'E' ];
    }
  }

  render() {
    // custom attributes on editor
    const attrs = {
      rows: 10,
      onKeyDown: function() {
        console.log('keydown event trigger');
      }
    };
    return (
      <BootstrapTable data={ jobs } cellEdit={ cellEditProp }>
        <TableHeaderColumn dataField='id' isKey={ true }>Job ID</TableHeaderColumn>
        <TableHeaderColumn dataField='name' editable={ { type: 'textarea', attrs: attrs } }>Job Name</TableHeaderColumn>
        <TableHeaderColumn dataField='type2' editable={ { type: 'select', options: { values: this.jobTypes } } }>Job Type2</TableHeaderColumn>
        <TableHeaderColumn dataField='active' editable={ { type: 'checkbox', options: { values: 'Y:N' } } }>Active</TableHeaderColumn>
        <TableHeaderColumn dataField='datetime' editable={ { type: 'datetime' } }>Date Time</TableHeaderColumn>
      </BootstrapTable>
    );
  }
```

**Comment by jaeho-kim** [comment]
I have a question about the select-options.
when it has [{'value': '1', 'text': 'AAA'}, {'value': '2', 'text': 'BBB'}]

I tried to change column using cellEdit() (AAA to BBB)
The data has updated correctly but the displayed value was '2' not 'BBB'.
How can I handle this? I want to display by text value.

**Comment by whittlem** [comment]
Any update on the issue by @jaeho-kim? I am having the same issue. Values are displaying not text before editing.

**Comment by whittlem** [comment]
@jaeho-kim, I got this working with a bit of a hack. I didn't use the "value" and "text" object and options. I just created an array where my id is the key and the text is the value. I then used a dataFormat to display the text based on the value passed.
