### ISSUE TITLE
Click outside of data table is not observed

### ISSUE THREAD

**Issue by pramodZipGo** [AllenFang/react-bootstrap-table#1652]
In React Bootstrap Table when I enable a enable to field to be editable. When I want to cancel the edition I press can ESC button it goes back earlier phase, but when a user clicks on data table or press enter its saves, but when I click outside of data table it remains in edit phase. I want the same thing to happen outside of data table.

In the below example, if I click outside of data table, the product price edit must go away, but currently, it remains there which is weird.

![screen shot 2017-09-28 at 1 25 52 pm](https://user-images.githubusercontent.com/29728910/30955254-a39a85ea-a450-11e7-9fef-cbc3780026c1.png)

**Comment by AllenFang** [comment]
I can try to support a `cellEdit.blurToLeave` props to support this feature, thanks

**Comment by pramodZipGo** [comment]
Thank You

**Comment by AllenFang** [comment]
@pramodZipGo fixed on `v4.0.6`, please check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/cell-edit/blur-to-escape-table.js#L24) example, thanks
