### ISSUE TITLE
Clicking on cell in a borderless table causes scrollbars to appear

### ISSUE THREAD

**Issue by wtellis** [AllenFang/react-bootstrap-table#1653]
If you're using Chrome  61 and click on a cell in a borderless table you will get horizontal and vertical scrollbars

See screenshot from borderless table example:

![capture](https://user-images.githubusercontent.com/821340/30999154-2f99b606-a488-11e7-90f1-5d804658d67c.PNG)

**Comment by AllenFang** [comment]
Duplicated with https://github.com/AllenFang/react-bootstrap-table/issues/1597
