### ISSUE TITLE
Uncaught TypeError: this.refs.innerDiv.setAttribute is not a function

### ISSUE THREAD

**Issue by patelhs** [AllenFang/react-bootstrap-table#166]
When I tried to use this component in my existing ES6 react app after following installation instructions, it displays data correctly but breaks whole application by throwing Uncaught TypeError: this.refs.innerDiv.setAttribute is not a function. Any idea? 

I looked at the browser debugger and found that TableColumnHeader class is having this issue. 

 _createClass(TableHeaderColumn, [{
    key: 'handleColumnClick',
    value: function handleColumnClick(e) {
      if (!this.props.dataSort) return;
      var dom = this.refs.innerDiv;
      this.order = this.order == _Const2['default'].SORT_DESC ? _Const2['default'].SORT_ASC : _Const2['default'].SORT_DESC;
      this.props.clearSortCaret(this.order, this.props.dataField);
      dom.appendChild(_util2['default'].renderSortCaret(this.order));
    }
  }, {
    key: 'componentDidMount',
    value: function componentDidMount() {
      this.refs.innerDiv.setAttribute("data-field", this.props.dataField);
    }

**Comment by AllenFang** [comment]
@patelhs, I haven't seen this problem, would you give me your code? Thanks :)

**Comment by patelhs** [comment]
Allen,
Thanks for coming back quickly. I am sure I am missing something very basic somewhere. You can view code at https://github.com/patelhs/HealthVu.git
I am trying to use it at home.jsx

**Comment by AllenFang** [comment]
@patelhs I trace the code and find the <code>Home_appointments_table.jsx</code>, but I dont see any render for BootstrapTable

**Comment by patelhs** [comment]
My apology. I just checked it in.

**Comment by AllenFang** [comment]
wow, It's strange, if you just run <code>react-bootstrap-table</code> examples codes, could you see this error again?

**Comment by patelhs** [comment]
I don't see this issue with examples. but when I tried to integrate it as per instructions in my app, I see this problem. it's been past couple of days I have been trying to troubleshoot but landing no where. are we experiencing any compatibility issue with react version?

**Comment by AllenFang** [comment]
which react version you used ?

**Comment by AllenFang** [comment]
Maybe you can upgrade <code>react-bootstrap-table</code> to the newest version and try again

**Comment by patelhs** [comment]
I did upgrade react-bootstrap-table to the latest. i am using react 0.14.2 at this time. Again, It is most likely my existing code creating some short of conflicts with react-bootstrap-table. First I thought It may be reference issue since I am using ES6 but then I read your documentation and examples to find out that you component is up to date with ES6 compatibility. My code is very simple, you may want to take a look at packages to see if you can point out something that may have been causing this issue.

**Comment by AllenFang** [comment]
@patelhs, I try to run your repo, but I cant run it successful, the server (localhost:8080) is started but I got some error in browser console:
GET http://localhost:8080/js/build.js 

and the command line  show this message:

Browserify Error { [Error: Cannot find module 'react/lib/warning' from '/Users/allen/Node/HealthVu/node_modules/react-bootstrap/lib']

so, how did you run your product?

**Comment by patelhs** [comment]
Yes, there is a link for server example that can be used to set it up. Browserify error for warning in react lib is new to me. I can check my code and see what is different?

On Dec 3, 2015, at 10:03 AM, AllenFang <notifications@github.com<mailto:notifications@github.com>> wrote:


@patelhs<https://github.com/patelhs>, I try to run your repo, but I cant run it successful, the server (localhost:8080) is started but I got some error in browser console:
GET http://localhost:8080/js/build.js

and the command line show this message:

Browserify Error { [Error: Cannot find module 'react/lib/warning' from '/Users/allen/Node/HealthVu/node_modules/react-bootstrap/lib']

so, how did you run your product?

-

**Comment by AllenFang** [comment]
@patelhs, because the react-bootstrap problem for doing browserify, I just uninstall react-bootstrap and modify the index.jsx in the following:
<pre>
import React from 'react';

import {BootstrapTable, TableHeaderColumn} from 'react-bootstrap-table';

var products = [];

function addProducts(quantity) {
  var startId = products.length;
  for (var i = 0; i < quantity; i++) {
    var id = startId + i;
    products.push({
      id: id,
      name: "Item name " + id,
      price: 2100 + i
    });
  }
}

addProducts(10);

React.render(
&lt;BootstrapTable data={products} height="120"&gt;
  &lt;TableHeaderColumn dataField="id" isKey={true}&gt;Product ID&lt;/TableHeaderColumn&gt;
  &lt;TableHeaderColumn dataField="name"&gt;Product Name&lt;/TableHeaderColumn&gt;
  &lt;TableHeaderColumn dataField="price"&gt;Product Price&lt;/TableHeaderColumn&gt;
&lt;/BootstrapTable&gt;, document.getElementById('content'));
</pre>

And it's work, so I think you should solve the problem that I said before so that I can help you to find the root cause

**Comment by patelhs** [comment]
that was it! I reinstalled react-bootstrap and react both and problem got resolved. Show stopper error is gone. 
Thank you so much!

happy coding!

**Comment by AllenFang** [comment]
Great!
