### ISSUE TITLE
Issues with preselected rows

### ISSUE THREAD

**Issue by swapnildubal** [AllenFang/react-bootstrap-table#1660]
Hi Allen,

Here is my selectRowWrap : selectRowProp = {
    mode: "checkbox",
    clickToSelect: true,
    onSelect: this.onRowSelect,
    bgColor: "#f5f5f5",
    selected: this.selectedRowIds
  };

When I don't use 'selected' flag everything works fine, however, once I have this flag, the checkbox is not getting checked on click. When I click the checkbox, close the modal and reopen it, previously clicked row gets selected. But then I am not able to do any further selection/de-selection.

Could you please help

**Comment by AllenFang** [comment]
if you use `selectRow.selected` props which mean you wanna control the selection by your react state or something, [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/externally-managed-selection.js) is an example to show how it work, please make sure you used it correctly, thanks

**Comment by swapnildubal** [comment]
This worked, thanks for the correction :)
