### ISSUE TITLE
React 16 unique key warning when expandColumnVisible = true

### ISSUE THREAD

**Issue by elmoro666** [AllenFang/react-bootstrap-table#1661]
Hi

When creating at table with expandable rows, React 16 issues av warning about unique keys when you add the property expandColumnVisible = true. If you need a fiddle I will create one, but you can see the warning in the console in:

http://allenfang.github.io/react-bootstrap-table/example.html#expand

**Comment by elmoro666** [comment]
By the way, this is not very important to me, so you can wait til version 2 if you want to. I have found ways around the problem.

**Comment by AllenFang** [comment]
@elmoro666 oh,,, that's ok. but what's your work around :)

**Comment by elmoro666** [comment]
Nothing fancy. I just added my own (+) sign to the key column, instead of using expandColumnVisible = true.

![image](https://user-images.githubusercontent.com/15340253/31376332-df4363fc-ada4-11e7-9a7f-611eeb827037.png)
