### ISSUE TITLE
Cannot read property 'getHeaderColGrouop' of undefined

### ISSUE THREAD

**Issue by frossigneux** [AllenFang/react-bootstrap-table#1662]
In my package.json: "react-bootstrap-table": "^4.0.6"
I have this issue using react-bootstrap-table in Electron app with react "react": "^15.5.4".
I get this error with the basic example:
```
TypeError: Cannot read property 'getHeaderColGrouop' of undefined
    at BootstrapTable._adjustHeaderWidth
```
Is there a mistake getHeaderColGrouop => getHeaderColGroup ?

**Comment by AllenFang** [comment]
hmm... it's a wrong naming issue, but even with wrong naming, it still work well because the caller also call `getHeaderColGrouop`.  can you make sure you dont have different react were installed in your `node_modules`? thanks

**Comment by sameerasaad** [comment]
i am getting the same issue and i have only one react version installed

**Comment by ZuzooVn** [comment]
I have the same problems, any solution here?

**Comment by philipp-sorin** [comment]
Any solution here? I have the same issue

**Comment by Magneticmagnum** [comment]
I also have been running into this issue

**Comment by AllenFang** [comment]
hello there, give a a simple and minimal repo for reproducing this issue, thanks!
