### ISSUE TITLE
Element ref was specified as a string (table) but no owner was set.

### ISSUE THREAD

**Issue by bradrisse** [AllenFang/react-bootstrap-table#1663]
After upgrading to React 16 I received this message, Element ref was specified as a string (table) but no owner was set. Downgrading back to 15.6.1 for both react and react-dom, it went back to normal. I'm assuming this will require all string refs in the library to be converted for this to work with version 16.

https://reactjs.org/warnings/refs-must-have-owner.html

**Comment by AllenFang** [comment]
I'll have investigation on it, btw, do you have any example for reproduce this one.  thanks :)

**Comment by jaywcjlove** [comment]
@AllenFang   https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs

Legacy API: String Refs

**Comment by AllenFang** [comment]
oh, yes, I'll handle this, thanks you @jaywcjlove

**Comment by AllenFang** [comment]
Fixed on `v4.2.0` and let me know if this problem still remain, thanks
