### ISSUE TITLE
Select top 10 rows in React bootstrap table

### ISSUE THREAD

**Issue by vpb88** [AllenFang/react-bootstrap-table#1664]
Hi Allen,

I have a use case to select top 10 rows from the React bootstrap Table Data Grid. I want to trigger the top 10 rows by using a button which outside of Bootstrap Data Grid. I used Rowkeys to select the Selected rows but I am unable to get the row data of selected rows. I used Select all to select all the rows.  I need both selectAll and selectTop10 functionality. If you have a valid use case to demonstrate with an example let me know.

**Comment by AllenFang** [comment]
You can control the select rows via `selectRow.selected` props,

```js
class ExternallyManagedSelection extends React.Component {
  constructor(props) {
    super(props);
    this.onSelectAll = this.onSelectAll.bind(this);
    this.onRowSelect = this.onRowSelect.bind(this);
    this.state = {
      selected: [],
      currPage: 1
    };
  }

  onRowSelect({ id }, isSelected) {
    if (isSelected && this.state.selected.length !== 2) {
      this.setState({
        selected: [ ...this.state.selected, id ].sort(),
        currPage: this.refs.table.state.currPage
      });
    } else {
      this.setState({ selected: this.state.selected.filter(it => it !== id) });
    }
    return false;
  }

  onSelectAll(isSelected) {
    if (!isSelected) {
      this.setState({ selected: [] });
    }
    return false;
  }

  selectTopTen() {
    const top_ten_row_keys = get_top_ten_row_keys() // get the rowkeys of top ten rows
    this.setState({ selected: top_ten_row_keys });
  }

  render() {
    const {
      currPage
    } = this.state;

    const selectRowProp = {
      mode: 'checkbox',
      clickToSelect: true,
      onSelect: this.onRowSelect,
      onSelectAll: this.onSelectAll,
      selected: this.state.selected
    };

    const options = {
      sizePerPageList: [ 5, 10, 15, 20 ],
      sizePerPage: 10,
      page: currPage,
      sortName: 'id',
      sortOrder: 'desc'
    };

    return (
      <div>
        <button onClick={ this.selectTopTen.bind(this) }>select top 10</button>
        <BootstrapTable ref='table' data={ products } selectRow={ selectRowProp } pagination={ true } options={ options }>
          <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
        </BootstrapTable>
      </div>
   );
  }
}
```

**Comment by vpb88** [comment]
Thanks Allen for your immediate response. I have one more question on this issue after selecting the top 10 rows I want to access row data of the top 10 rows. can you let me know how to achieve it.

**Comment by AllenFang** [comment]
HI use `this.refs.table.state.selectedRowKeys`

**Comment by vpb88** [comment]
Allen,

I want to get row data of first 10 rows not the row keys how we get for an onSelect method. This onSelect method will automatically be triggered when we select a row and gives us the selected row data like this I am able to select all 10 rows by using code which you provided above but I am not able to fetch the data of all 10 rows. I want to know whether it can be achievable or not

**Comment by AllenFang** [comment]
> I want to get row data of first 10 rows

you can get the first 10 rows by your state I think....
