### ISSUE TITLE
Highlighting changing field

### ISSUE THREAD

**Issue by vinaySaxo** [AllenFang/react-bootstrap-table#1665]
Hi AllenFang,

In my project, the table is fed with dynamic data which is continuously being updated over websocket. Please tell me if it is possible to highlight changing fields in the table by blinking or change in color or something for a short duration(maybe for just 2 seconds and then it comes back to normal state) which tells the user about change in data.

**Comment by AllenFang** [comment]
I think the only way is use `dataFormat` to render the custom cell. But `react-bootstrap-table` doesn't tell you if this field was changed or not, you need to handle it by yourself...

Following is example for custom cell
https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/column-format

Let me know if you have any questions, thanks
