### ISSUE TITLE
Bind exportCSV to custom react button

### ISSUE THREAD

**Issue by Soverne** [AllenFang/react-bootstrap-table#1667]
Hey Allen,

I'm wondering if there's a way to bind the exportCSV action to some other component in a webpage? I know you provide the custom button example but is there any way it could be taken further? I'm thinking a button separate from the BootstrapTable entirely that can trigger actions within the table, think a button separated by a < br > before the actual table is rendered.

Thanks!

**Comment by mrijke** [comment]
Hey @Soverne, coincidentally I was thinking about this two days ago myself. I ended up doing the following:
  * Saving the BootstrapTable as a ref on my parent Table component:
`<BootstrapTable ref={node => this.table = node} />`
  * Then, in an `onClick` handler of a custom Export CSV button, you just call `this.table.handleCSVExport()`, and the CSV is downloaded!

See also #1104

**Comment by AllenFang** [comment]
@mrijke nice answer !!! 👍

**Comment by Soverne** [comment]
Yup this solves my problem.

Through some testing of my solution I found this to work as well:

<Button onClick={() => this.refes.mainTable.handleExportCSV()} />
<BootstrapTable ref="mainTable">
    ..
</BootstrapTable>

Thanks @mrijke for the inspiration and the solution!
