### ISSUE TITLE
User changeable columns

### ISSUE THREAD

**Issue by Gilks** [AllenFang/react-bootstrap-table#1669]
I'd like to give my users the ability to change viewable columns to customize the data they are viewing. 

For example, say there are 5 columns of data available: Position, Value, Status, Date, Time.  The user can only see 2 columns due to screen space, so they chose "Name" and "Status". Eventually the user decides they want to change the "Status" column to "Date". 

Are there any options available that allows this to take place? Ideally I'd be able to have a "Change Columns" button that would give a modal where I could let them select a new column from a drop down. For example:

**The user clicks "Change Columns"**
![main](https://user-images.githubusercontent.com/11075149/31322493-856fb84c-ac66-11e7-8b6f-d4c50e92015f.PNG)

**The user is presented with the modal that lets them switch columns**
![modal](https://user-images.githubusercontent.com/11075149/31322497-a451df74-ac66-11e7-8066-93dd7a8e13f5.PNG)

**Comment by prajapati-parth** [comment]
@Gilks Please use the `hidden` property as shown [here](https://allenfang.github.io/react-bootstrap-table/example.html#column), section: `Hide Column`.
You can change `hidden` to true/false depending upon user selection.

Thanks.

**Comment by AllenFang** [comment]
@Gilks we dont support the column toggle feature, but like @prajapati-parth mentioned above, `hidden` is a good solution. thanks
