### ISSUE TITLE
Error with react 16.0.0

### ISSUE THREAD

**Issue by marcosguti** [AllenFang/react-bootstrap-table#1670]
i'm upgrading my app to react 16.0.0 and i getting this error related with react-modal inside in react-bootstrap-table

check the screenshot

https://prnt.sc/gv6586

i'm using create-react-app with:
 "react": "^16.0.0",
"react-dom": "^16.0.0 ",
 "react-bootstrap-table": "^4.0.6",
"react-scripts": "1.0.14"

**Comment by AllenFang** [comment]
https://github.com/reactjs/react-modal/issues/498

I'll upgrade `react-modal`, thanks 👍

**Comment by AllenFang** [comment]
Fixed on `v4.1.0`, thanks
