### ISSUE TITLE
Weird bug with table columns / filter

### ISSUE THREAD

**Issue by VictorChen** [AllenFang/react-bootstrap-table#1675]
Hi, I upgraded to the latest version `4.0.6` and things broke 😢. I had to downgrade it back to `4.0.3`. I made a reproducer since it's hard to explain:

https://codesandbox.io/s/7zoq39wp06

The table gets rendered initially with no data, and then later the data gets populated (when you click on the button) and then it breaks...

**Comment by VictorChen** [comment]
I believe this is the change that causes the bug:

https://github.com/AllenFang/react-bootstrap-table/commit/84cc76c7d92b4aa2eb3f1a3c8fddabd5b20f9647

**Comment by AllenFang** [comment]
@VictorChen thanks for bug report, I'll check this out ASAP, thanks

**Comment by AllenFang** [comment]
@VictorChen please confirm it again on `v4.1.0`, thanks

**Comment by VictorChen** [comment]
Perfect, issue is fixed, thanks!
