### ISSUE TITLE
How to set cursor at end of input

### ISSUE THREAD

**Issue by yummyelin** [AllenFang/react-bootstrap-table#1677]
Hello,

Click on a cell to edit, cursor will by default at the beginning of input if cell has value. I want to move it to the end for easier input.

If adding props `editable={ { type: 'textarea' } }`, cursor is moved to the end. But is there a better way?

Thanks!

**Comment by AllenFang** [comment]
I will try to do this enhancement, thanks

**Comment by AllenFang** [comment]
@yummyelin sorry, this feature will only be implemented on `react-bootstrap-table2`, actually, it's implemented on version 2. Sorry about that.
