### ISSUE TITLE
Use regular button to call exportCSV. 

### ISSUE THREAD

**Issue by bconrad1** [AllenFang/react-bootstrap-table#1678]
I have a custom toolbar with a button which I want if possible to call the exportCSV button. The table header looks like 

`<BootstrapTable data={this.props.data} 
        options={options}
        hover 
        condensed 
        exportCSV ={true} 
        striped 
        >`

I have options declared 

`const options = {
      
      toolBar : this.createCustomToolBar,
      
    };`

And then my call to create the toolbar. `  createCustomToolBar = props => {
    return (
      <div className='table-toolbar' style={style.toolbarBG}>
   
            <RaisedButton 
              backgroundColor = '#D1121F'
              labelColor ='white'
              label={'Export'} 
              
            /> 
      </div>
   );

  }`

I was hoping for that raised button to export to CSV similiar to the ExportCSVButton. I'd prefer my own custom button to do that and was wondering if there is a way to still call the export functionality. If not is is possible to insert that ExportCSVButton into the toolbar. Most examples I've seen seem to just return the button as options rather then embedded.

**Comment by prajapati-parth** [comment]
@bconrad1 Please refer #1667
Thanks.

**Comment by bconrad1** [comment]
@prajapati-parth  Ahh perfect that worked just as needed. Thanks!

**Comment by AllenFang** [comment]
thanks @prajapati-parth
