### ISSUE TITLE
Filter and customized columns headers conflicts

### ISSUE THREAD

**Issue by Rclass93** [AllenFang/react-bootstrap-table#1680]
Hey, i came across this problem today. I have icons in the columns headers and if i set up the filter, it shows this message:

Warning: Failed prop type: Invalid prop `columnName` of type `array` supplied to `TextFilter`, expected `string`.
    in TextFilter (created by TableHeaderColumn)
    in TableHeaderColumn (created by ListaChamadas)
    in tr (created by TableHeader)
    in thead (created by TableHeader)
    in table (created by TableHeader)
    in div (created by TableHeader)
    in TableHeader (created by BootstrapTable)
    in div (created by BootstrapTable)
    in div (created by BootstrapTable)
    in BootstrapTable (created by ListaChamadas)
    in div (created by Panel)
    in div (created by Panel)
    in Panel (created by ListaChamadas)
    in ListaChamadas (created by displayChamadas)
    in div (created by displayChamadas)
    in div (created by displayChamadas)
    in displayChamadas
    in App
    in div
    in div

If i delete the filter, it doesn't show anymore.
Here's the code:

<TableHeaderColumn dataField='selected_option' dataSort dataAlign="center" 
                columnClassName={ this.columnClassNameFormat } 
                filter={{ type: 'TextFilter', delay: 500, placeholder:"Procure"}} 
                width='16%'><i className="fa fa-crosshairs"/>&nbsp;Ação
</TableHeaderColumn>

Thank you

**Comment by AllenFang** [comment]
@Rclass93 this issue was fixed on `v4.1.0`, thanks :)

**Comment by crazyUI** [comment]
Hi,

I have a custom column header component. When I add textFilter to it, column disappears.. I am using version 4.3.1. 
There is no error or warning in console.  If I remove the header component and directly use text, it works fine. Please advise.

Thank you
Lalitha
