### ISSUE TITLE
onSelect and onSelectAll seem to be broken with React16

### ISSUE THREAD

**Issue by crowdwave** [AllenFang/react-bootstrap-table#1689]
I'm not entirely sure but it appears that with React16, onSelect and onSelectAll strangely seem to not be scoped to the object that the function is defined in, even though they are defined as arrow functions.

This means that onSelect and onSelectAll don't work anymore.

To make it work I need to change the functions from arrow functions to ordinary functions and then bind this to them.  

    var selectRowProp = {
      mode: "checkbox",
      clickToSelect: false,
      onSelect: this.onRowSelect.bind(this),
      onSelectAll: this.onSelectAll.bind(this),
      selected: this.state.selected,
    }

Update, it seems to be only onSelect, not onSelectAll.  This works:

    var selectRowProp = {
      mode: "checkbox",
      clickToSelect: false,
      onSelect: this.onRowSelect.bind(this),
      onSelectAll: this.onSelectAll,
      selected: this.state.selected,
    }

**Comment by AllenFang** [comment]
@crowdwave I think this is not about react 16, it's work well on react 16, please upgrade to `v4.1.0` and confirm again, thank you
