### ISSUE TITLE
Table header rendered twice.

### ISSUE THREAD

**Issue by risonsimon** [AllenFang/react-bootstrap-table#169]
I'm using the basic table code in my react component.
```javascript
<BootstrapTable data={this.props.admins}>
  <TableHeaderColumn dataField="id" isKey={true}> ID</TableHeaderColumn>
  <TableHeaderColumn dataField="first_name">Name</TableHeaderColumn>
  <TableHeaderColumn dataField="email">Email</TableHeaderColumn>
</BootstrapTable>
```

However, the header row is rendered twice.
![image](https://cloud.githubusercontent.com/assets/871227/11594672/17341124-9a8a-11e5-961d-0a61811f6fdb.png)

Here is the markup. There are two `thead`.
![image](https://cloud.githubusercontent.com/assets/871227/11594766/93aaa27c-9a8a-11e5-933a-f8559bc8b6c1.png)

**Comment by AllenFang** [comment]
@risonsimon, check [this](https://github.com/AllenFang/react-bootstrap-table/issues/135)
