### ISSUE TITLE
table loaded data, but not showing it, and row which had data are too narrow.

### ISSUE THREAD

**Issue by StevenZhangLC** [AllenFang/react-bootstrap-table#1690]
![image](https://user-images.githubusercontent.com/32248179/31606855-c38bcc04-b2c6-11e7-8ac8-35082cd0a817.png)
Hi Allen, 

Thanks for this awesome tool.
I just faced a tiny problem and make sure I did every thing on README and installation right, imported css and all the stuff, but still no luck.
The problem is , my table loaded data, has 4 results, I can see it when mouse hover through it. But its all blank, and the rows with data inside is so narrow.

Any possible reason?

Here is the file.
[App.txt](https://github.com/AllenFang/react-bootstrap-table/files/1387031/App.txt)

**Comment by prajapati-parth** [comment]
@StevenZhangLC Probably you are looking for https://github.com/react-tools/react-table

**Comment by StevenZhangLC** [comment]
@prajapati-parth ah, yes, sorry I misunderstand this two table libraries. Thank you for the advice!
