### ISSUE TITLE
Pagination drop down requires double click

### ISSUE THREAD

**Issue by li164902697** [AllenFang/react-bootstrap-table#1691]
![image](https://user-images.githubusercontent.com/11850782/31610722-c160ccb0-b2ab-11e7-98b6-3cf9b324b3a3.png)

@AllenFang  everytime needs double click

**Comment by li164902697** [comment]
Pagination drop down every time requires double click

**Comment by ziaulrehman40** [comment]
This issue is visible on demo/examples page too.

**Comment by AllenFang** [comment]
Fixed on `v4.1.1`, now the sizePerPage dropdown work well. Thanks
