### ISSUE TITLE
more than two level row expand support

### ISSUE THREAD

**Issue by MYSHLIFE** [AllenFang/react-bootstrap-table#1692]
Does it support three level row expand for now? For example, when I open an row, and then I would like to click the second level row to open another table.

**Comment by AllenFang** [comment]
We don't explicit that we support this feature, but maybe you can try it 👍

**Comment by AllenFang** [comment]
Let me know if you need more help, thanks

**Comment by MYSHLIFE** [comment]
@AllenFang  Got it. Thanks, will try add it.

**Comment by karan-chauhan** [comment]
Hi @MYSHLIFE ,
Did you try two level row expand? I need this functionality too.
