### ISSUE TITLE
Getting the displayed data in the table

### ISSUE THREAD

**Issue by thekhenzie** [AllenFang/react-bootstrap-table#1693]
Hi @AllenFang ! Is there any way to get the processed data (the filtered data by column, formatted, etc.)? I'm going to create an export pdf/excel and share it with you here. Can you help me? Thanks! 👍

**Comment by AllenFang** [comment]
we can only get the raw data only.  There's only one way is you try to print the page by chrome brower and then chose to saving as PDF.
