### ISSUE TITLE
SizePerPage is not respected when remote paging is used

### ISSUE THREAD

**Issue by hc1skalyanasundaram** [AllenFang/react-bootstrap-table#1697]
I use remote paging. When I do this, sizePerPage is not respected. i have set sizePerPage to 10, but it always shows all the rows returned by the API.

<BootstrapTable
                headerStyle={ {background: '#ddd'} }
                selectRow={{mode: 'checkbox'}}
                data={ this.state.data }
                fetchInfo={{dataTotalSize: this.state.total}}
                striped={ true } hover={ true } condensed={ true } pagination
                tableContainerClass='custom'
                version='4'
                remote
                options={{
                    paginationPanel: this.renderPaginationPanel,
                    sizePerPage : this.state.sizePerPage,
                    sizePerPageList : [10,25,50,100],
                    onSizePerPageList: this.state.onSizePerPageList
                }}>

**Comment by AllenFang** [comment]
I think it's not a bug, maybe you have something wrong, make sure the `sizePerPageList` array contain  `this.state.sizePerPage`

**Comment by hc1skalyanasundaram** [comment]
I do have it to 10. Also when I remove the 'remote' option it works just fine.
