### ISSUE TITLE
Is there any way to show all the values instead of "ta..." when table width being smaller?

### ISSUE THREAD

**Issue by tsmvision** [AllenFang/react-bootstrap-table#1699]
I tested vanilla bootstrap3 and react-bootstrap. Both of them shows all the table values even when table being smaller but I noticed that react-bootstrap-table express value as "ab..." rather than showing all the values. I am wondering if there's any way to show all the values.

**Comment by AllenFang** [comment]
Yes, that's the default behavior, but you can still show whole the text:
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column/column-style-table.js#L32
