### ISSUE TITLE
Feature request: notification when a BootstrapTable has been updated

### ISSUE THREAD

**Issue by stephenrs** [AllenFang/react-bootstrap-table#17]
I'm using BootstrapTable as a child component of a larger component, and I'm using the TableDataSet feature to manage the list of items displayed in the table. My parent component needs to know when the BootstrapTable component has finished updating after a new list of items has been passed (after a myTableDataSet.setData(newData)), in order to perform some additional actions.

So, I'm wondering if you would consider adding this feature(?)

One way to do this would be to pass a callback prop (something like "handleUpdate") that can be called from BootstrapTable's componentDidUpdate method...but maybe there's a better way...

Thanks!

**Comment by AllenFang** [comment]
Hi @stephenrs, your request is an important feature for frontend development. We actually need a hook on before or after of some methods and I will consider your request for react-bootstrap-table. But need some time, I'm little busy :'(

**Comment by stephenrs** [comment]
Sounds great @AllenFang, thanks! And yes, there are definitely a few other hooks that would be useful.

I did find a temporary way to hack this though. It's pretty ugly, and I think it goes against the React way of doing things, but it's working for now. My componentDidMount method looks something like this:

```
componentDidMount: function() {
    var self = this;    
    self.refs.bsTable.originalFunc = self.refs.bsTable.componentDidUpdate;
    self.refs.bsTable.componentDidUpdate = function(prevProps, prevState) {
        self.refs.bsTable.originalFunc(prevProps, prevState);
        self.doExtraStuff();
    };
}
```

**Comment by AllenFang** [comment]
That's a good idea for current condition, you just give a function on react-bootstrap-table component and I think your solution is fine. Anyway, I'll provide a better solution for a more common usage. Thanks for your contribution!!

**Comment by AllenFang** [comment]
Hi @stephenrs, I've resolve this request

give BootstrapTable a <code>options</code> prop 

and assign a <code>afterTableComplete</code> property which accept an callback function, as follow: 

<pre>
function onAfterTableComplete(){
  console.log('Table render complete.');
}
var options = {
  afterTableComplete: onAfterTableComplete // A hook for after table render complete.
};

&lt;BootstrapTable data={products} options={options} ...
</pre>
