### ISSUE TITLE
When trying to edit a column that has no data IE 11 fails with error code 800a025e

### ISSUE THREAD

**Issue by widdde** [AllenFang/react-bootstrap-table#1701]
When trying to edit a row in a column that has no data, IE 11 fails with error code 800a025e. I have not seen this error in Chrome but fails every time in IE11.
Looks like the error is on line 125 in TableColumn.js
`sel.removeAllRanges();`

I have seen this issue in both v. 4.0.5 and v 4.06.

**Comment by AllenFang** [comment]
@widdde could you please check it again on `v4.1.1`  thanks :)
