### ISSUE TITLE
Prevent "data is undefined" error during React's lifecycle methods  

### ISSUE THREAD

**Issue by lennartj** [AllenFang/react-bootstrap-table#1704]
Hello there,

I have been struck by the "TypeError: data is undefined" state quite a lot by the react-bootstrap-table, despite being rather careful to handle null input data into the react-bootstrap-table. Apparently, in React's lifecycle the update events do sometimes create states where the data is deemed "undefined" in the RBT codebase despite distinctly not being undefined in the surrounding class.

Could we add a catch so as not to yield an exception within the RBT codebase here? 
This is a rather pesky state to handle, as it throws an exception during Reacts render() method implying that the application breaks/gets stuck in an infinite loop.

      168 | var tableColumns = this.props.columns.filter(function (_) {
      169 |   return _ != null;
      170 | }).map(function (column, i) {
      > 171 |   var fieldValue = data[column.name];
      172 |   var isFocusCell = r === y && i === x;
      173 |   if (column.name !== this.props.keyField && // Key field can't be edit
      174 |   column.editable && // column is editable? default is true, user can set it false

**Comment by lennartj** [comment]
This is caused by the data array being set to 10 undefined elements, where (alas) the this.props.data is pointing to an array, but all its elements are set to undefined. This is not coming from application code - which makes it somewhat difficult to track.

**Comment by lennartj** [comment]
The code below:

            const dataArray = this.state.food_data;
            console.log(prefix + "dataArray: ", dataArray);

            foodContent = (<BootstrapTable data={dataArray}

... yields the following entry on the console (after upgrading to release 4.1.1 of the RBT, the line number is changed from the version used above, but the same error message occurs).
Hence, the data array contains 95 (non-undefined) elements, but the RBT complains that its data is undefined. 

      [SettingsAllergies::render]: dataArray:  Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 95 till… ]  SettingsAllergies.:439
      TypeError: data is undefined[Läs mer]  TableBody.j:244
            render/tableRows</tableColumns< TableBody.js:244

**Comment by AllenFang** [comment]
HI @lennartj sorry for lately reply. I think before you give an undefined raw data array to `react-bootstrap-table`, you are suppose to handle those undefined row data, just skip them I think. it's wired that your row data is undefined.
