### ISSUE TITLE
can  achieve such a jump effect

### ISSUE THREAD

**Issue by li164902697** [AllenFang/react-bootstrap-table#1709]
![image](https://user-images.githubusercontent.com/11850782/31887754-1ca04d1e-b82c-11e7-96c5-9ef50d5351a8.png)

@AllenFang  can  achieve such a jump effect

**Comment by AllenFang** [comment]
HI @li164902697 As I mention on README.md, `react-bootstrap-table` already stop implement new feature and start move to [react-bootstrap-table2](https://github.com/react-bootstrap-table/react-bootstrap-table2).  So it's sorry that I'm not going to implement this feature but you can still custom the pagination bar to achieve your requirements.

Check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/pagination/custom-pagination-panel.js) you can learn how to custom the pagination panel, actually, it's not very hard you just add some button and input I think.
