### ISSUE TITLE
Cannot use cleanSelected any more in React16, looks like a scoping issue?

### ISSUE THREAD

**Issue by dukedougal** [AllenFang/react-bootstrap-table#1710]
I don't seem to be able to use this.refs.table any more in React16.

Seems to be a scoping issue maybe?  The function does not seem to be on the ref object.

Any ideas?

thanks

**Comment by AllenFang** [comment]
I dont think so, you still can use `refs` but you need to use it as a callback
https://reactjs.org/docs/refs-and-the-dom.html

**Comment by dukedougal** [comment]
Hi Allen

All the react-bootstrap-table documentation shows refs as a string.  Can you give an example of the correct way to use a callback please for react-boostrap-table refs?

thanks

**Comment by enkaradura** [comment]
Hi dukedougal,

How did you solve the problem? Even with using a callback, I get 'cleanSelected is not a function. The same with reset.

**Comment by enkaradura** [comment]
I has to do something like 
```
this.tableRef = React.createRef(); // in the constructor
this.tableRef.current.reset()
```
I was missing the _current_, just in case this is useful for somebody
