### ISSUE TITLE
Cell highlighting and post validation

### ISSUE THREAD

**Issue by gayanis** [AllenFang/react-bootstrap-table#1712]
Hello,

I'm working on using react-bootstrap-table with row insertion and deletion to create a dataset with validation. i also would like to have the capabilities to import a csv file into the table. i would like to conduct cell validations after getting the data. 

1. can i perform cell validation at any time, other than during cell edit or row insertion?
2. how can i highlight the cells that fail the validation tests?

Thanks a bunch!

**Comment by AllenFang** [comment]
@gayanis sorry for lately reply,

> can i perform cell validation at any time, other than during cell edit or row insertion?

Yes, you can. please check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/advance/validator-table.js

> how can i highlight the cells that fail the validation tests?

Our error alert is via a toastr, it'll popup when fail.

For your requirement, you want to import a csv data into table and check each cell value by your validator, right?

I think there's still a workaround, you can just use `data` prop on `BootstrapTable` to set your csv data into table. and use `dataFormat` to do your validator, if validation fails, you can have a custom cell to highlight this cell is invalid.

Let me know if you want any help, thanks
