### ISSUE TITLE
Is there a possibility to make a horizontal oriented table?

### ISSUE THREAD

**Issue by Charlie91** [AllenFang/react-bootstrap-table#1713]
I have an array of data with structure like this:
`[ {date:1,val:2}, {date:2,val:3}, {date:2,val:3} ]` and etc.
I want to make a horizontal table where the "date" property would be a table column header and the "val" property would be a cell. how can i do this?
In other words, i need something like this:
![gkgye](https://user-images.githubusercontent.com/13438795/32047754-b60c1fc6-ba4f-11e7-8dd2-1d8f7a60bb13.png)

**Comment by AllenFang** [comment]
I think it's possible but you need to transfer your data firstly, because `react-bootstrap-table` doesn't support to display this kind of table natively.
