### ISSUE TITLE
table height makes the table unresponsive

### ISSUE THREAD

**Issue by Kirbypnc** [AllenFang/react-bootstrap-table#1714]
When I set my table's height to be 300 the table becomes unresponsive, but if I set it to 700 the table becomes responsive.

<BootstrapTable 
                    data = { data } 
                    height = { 300 } 
                    search = { true } 
                    pagination = { true } 
                    striped hover 
                     className="table-padding">

Is there a fix for this issue?

**Comment by AllenFang** [comment]
it's a known issue for a long time, it's hard to explain. Actually, we fix some unalign column issue but make table unreponsive when you config the `height`.
