### ISSUE TITLE
PaginationShowsTotal on the left of the pagesize dropdown?

### ISSUE THREAD

**Issue by MagnumDopus** [AllenFang/react-bootstrap-table#1716]
It seems really odd that when enabling paginations shows total, or providing a custom display for pagination, it defaults to place it to the left of the page size drop down, thus dynamically moving the dropdown selection.

Wouldn't it make more sense if paginationshowstotal displayed the pagination information to the right of the dropwdown, thus inside the element and not offsetting the control?

![screen shot 2017-10-26 at 1 12 06 pm](https://user-images.githubusercontent.com/10997753/32074769-51d32de2-ba4f-11e7-84f7-28e385855da2.png)

**Comment by AllenFang** [comment]
HI @MagnumDopus, it's sorry for you to feel odd but this is current circumstances. Only you can do is custom it. https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/pagination/custom-pagination-panel.js
