### ISSUE TITLE
Selected Page/ Jump to certain page 

### ISSUE THREAD

**Issue by yh070809** [AllenFang/react-bootstrap-table#1717]
HI Allen 
I am using your react-bootstrap-table 
for pagination , now its can only go to prev and next 

is there any way , I give user a input and let user decide which page to go ?

![image](https://user-images.githubusercontent.com/15305663/32092007-4eef4fd6-bb29-11e7-81b4-eed84f2d7a41.png)

**Comment by prajapati-parth** [comment]
Please check #1709.
