### ISSUE TITLE
Is there a way to add button in each row and the button could open a simple modal

### ISSUE THREAD

**Issue by kliu4** [AllenFang/react-bootstrap-table#1720]
I can not find such example:

There is a button column in table, each row has a button. When user click one of the button, a simple modal will be created.

**Comment by prajapati-parth** [comment]
Yes. Please check here https://allenfang.github.io/react-bootstrap-table/example.html#column-format

**Comment by zeeshansafdar48** [comment]
Please anybody can tell me where is it? 
I also not find this example. not on the above given url
