### ISSUE TITLE
[Help] Hidden column during Add modal

### ISSUE THREAD

**Issue by dbalutsel** [AllenFang/react-bootstrap-table#1722]
Hello,
I have a hidden column: 
`<TableHeaderColumn hidden={true} dataField='id' isKey={true}>Id</TableHeaderColumn>`, 
but when `+New` button is pressed id `dataField` is visible.
<img width="297" alt="screen shot 2017-10-28 at 7 50 35 pm" src="https://user-images.githubusercontent.com/18720927/32136613-6573405a-bc19-11e7-941b-294b1c7b4f97.png">

Is there a way to hide it?

**Comment by AllenFang** [comment]
@dbalutsel use `hiddenOnInsert` on `TableHeaderColumn`, thanks
