### ISSUE TITLE
[Help] - dropdown-menu don't hidden after choise size per pages

### ISSUE THREAD

**Issue by vandungbk92** [AllenFang/react-bootstrap-table#1723]
- I added jQuery v3.2.1, Bootstrap v3.3.6 and used react-bootstrap-table v4.1.1 but when change size per pages dropdown-menu not hidden.
![screenshot_11](https://user-images.githubusercontent.com/11436154/32152617-ad8fc2f2-bd57-11e7-9ebe-4612ff4903b9.png)

**Comment by CEmocca** [comment]
I also have this problem as well.

**Comment by AllenFang** [comment]
sorry for lately reply, you guys have custom size per page dropdown?

**Comment by AllenFang** [comment]
Try to add `open={ props.open }` when rendering `SizePerPageDropDown`

**Comment by CEmocca** [comment]
Hey @AllenFang, 
Sorry to late reply. No i don't use custom sizePerPageDropdown but i use sizePerPageList.

**Comment by prajapati-parth** [comment]
Also @vandungbk92 jQuery is not required.
