### ISSUE TITLE
validator without showing the alert?

### ISSUE THREAD

**Issue by bathpp** [AllenFang/react-bootstrap-table#1727]
Hello, wonder if the validator can work without an alert pop up?
Below is my code, I want to use invalidEditColumnClassName and CSS to show the invalid cell.
However there is always an alert pop up when `nameValidator` returns `false`.
```
nameValidator = value => {
    if (!value) {
      return false;
    } else {
      return true;
    }
  };
```
then in the `TableHeaderColumn`
```
<TableHeaderColumn
    dataField="fieldName"
    editable={{ validator: this.nameValidator }}
    invalidEditColumnClassName={this.invalidEdit}
>
```
Is it possible to not show the alert?

**Comment by AllenFang** [comment]
Sorry for lately reply, please check following:
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/advance/disable-toastr-table.js#L72-L73
