### ISSUE TITLE
Problems with onFilterChange

### ISSUE THREAD

**Issue by silver17** [AllenFang/react-bootstrap-table#1729]
I my table, I have added filters to my columns and also set onFilterChange: `this.onFilterChange,` .
In this function, I make an ajax request to backend to fetch data. Now this gives me a loop, the data is fetched and previewed in the table, but the `onFilterChange` fuction is called in a loop. Why is that so? I know, that I can set the `filter: true` under `remote` and this stops this kind of behaviour but it also stops the default table filters from working ("TextFilter" for example). 

This happens, when props change during `onFilterChange` and the table takes its data from props. (Same happens if table would take its data from state and state is changed during onFilterChange)

Any ideas?

**Comment by AllenFang** [comment]
It can be a improvement here. Currently, when table re-render, we will do the filter again when any columns got filtering in the previous state.

However, what kind of data you fetch in `onFilterChange`, I don't suggest people to do `setState` or other action which will cause re-render  when filtering

**Comment by mustafawm** [comment]
>Currently, when table re-render, we will do the filter again when any columns got filtering in the previous state.

Can we hijack/prevent this?

**Comment by mustafawm** [comment]
because, when re-rendering,  it is calling the onFilterChange with one filter only (when multiple were set) which in turn causes unnecessary ajaxs 

if it calls onFilterChange with all the filters that were set, it'll be ok cause passed filters will == previously set filters, so no ajax will be performed

PS: filters are stored in redux

**Comment by AllenFang** [comment]
I think it just like @silver17, if you handle the filtering in the store, I will highly recommend to use `remote`

**Comment by mustafawm** [comment]
Hi Allen

I am.... for the most part. only the sort func is not remote. Could that be the reason?

`remote={this.remoteFncs}`

```
cosnt TABLE_LOCAL_FUNCS = ['sort'];

remoteFncs = remoteFnObj => {
  for (let fnc in remoteFnObj) {
    if ( !TABLE_LOCAL_FUNCS.includes(fnc) ) {
      remoteFnObj[fnc] = true;
    }
  }
  return remoteFnObj;
};
```

I have implemented a hacky workaround to cancel onFilterChange on re-rendering

**Comment by AllenFang** [comment]
@mustafawm sorry for lately reply

Most of people only enable remote on pagination, insert, delete, cell edit and leave sort, filter/search as not remote.

For your case, you need to handle all the data changes by your application except the sorting. I can't tell you if it's good, but if you dont enable insert, delete or something and I feel it's good

Please kindly let me know if you have any question or issue, thanks
