### ISSUE TITLE
Column width broken when resize window

### ISSUE THREAD

**Issue by SunJang** [AllenFang/react-bootstrap-table#173]
If the table has selectRow property, it breaks column layout when trying to resize window.

```javascript
<BootstrapTable data={advertisersList} striped={true} hover={true} condensed={true} selectRow={selectRowProp} search={true} pagination={true} exportCSV={true} >
            <TableHeaderColumn dataField="ID" isKey={true} dataAlign="center" dataSort={true}>ID</TableHeaderColumn>
            <TableHeaderColumn dataField="Name" dataSort={true}>Name</TableHeaderColumn>
            <TableHeaderColumn dataField="Email" >Email</TableHeaderColumn>
          </BootstrapTable>
```
![2015-12-08 5 17 46](https://cloud.githubusercontent.com/assets/1294162/11650862/d09a2368-9dcf-11e5-9133-aa3b38a8aec2.png)

**Comment by AllenFang** [comment]
@SunJang, which version of <code>react-bootstrap-table</code> did you used?

**Comment by SunJang** [comment]
@AllenFang 1.3.0

**Comment by AllenFang** [comment]
@SunJang, did you re-import the css files? because I can't reproduce this problem on v1.3.0

**Comment by SunJang** [comment]
@AllenFang Yes, I re-imported css files. And there is no log message appears on console related this issue. I think you can find similar problem on http://allenfang.github.io/react-bootstrap-table/example.html

if you increase width of the browser window, you can find broken column layout. 

![2015-12-09 11 08 30](https://cloud.githubusercontent.com/assets/1294162/11674541/46d9a1bc-9e65-11e5-8390-c394ebf5b1b8.png)
![2015-12-09 11 08 37](https://cloud.githubusercontent.com/assets/1294162/11674543/495708ee-9e65-11e5-93f2-9cb23d5aac3b.png)

I tested on Chrome(46.0.2490.86) and Safari 9.0.1(11601.2.7.2) . 
It happened on both browser. any hints?

**Comment by AllenFang** [comment]
@SunJang, probably like you said, the scenario is 
1. open a smaller windows
2. render table
3. increase the size of windows
4. got this problem

I'll spend some time to fix this issues

**Comment by AllenFang** [comment]
@SunJang, fix it on v1.3.1 :)

**Comment by SunJang** [comment]
@AllenFang Awesome!! Thank you!

**Comment by robwise** [comment]
I am still observing this issue, the cells are different sizes if I use a zoom other than 100% (either zooming in or zooming out):

<img width="942" alt="screen shot 2015-12-26 at 12 37 00 pm" src="https://cloud.githubusercontent.com/assets/6173488/12007329/72c4ad1a-abcd-11e5-99db-72dc57527374.png">

This is Chrome (latest) on OSX using 1.3.3 and as you can see, this happens whether or not the component needs to have a horizontal scroll. 

It seems playing around with the size of the header fonts versus the td fonts affects how bad this gets. Does this library require using certain sizes of fonts, styling of fonts (px vs. ems), etc. or should it be able to handle this?

**Comment by AllenFang** [comment]
@robwise, your problem is different with this issue, because you use zoom in&out instead of sizing windows. Anyway, it seem like a bugs that we can improve
