### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sortFunc' of undefined

### ISSUE THREAD

**Issue by adc17** [AllenFang/react-bootstrap-table#1731]
React says this is an issue with the `<BootstrapTable />` component. 
It was introduced in version 4.1.1—4.1.0 works fine.
I'm not sure what additional info to provide, but send me any extra details you need and I'll get back to you.

**Comment by AllenFang** [comment]
HI @adc17 could you please give me a small and simple example code for reproducing it? thanks

**Comment by adc17** [comment]
Hi @AllenFang, don't worry about it—the latest release appears to have fixed the issue.

**Comment by AllenFang** [comment]
@adc17 yes, there's some mistake I made before lol
