### ISSUE TITLE
Get Selected Rows Data on Custom Button click 

### ISSUE THREAD

**Issue by v1pothapu** [AllenFang/react-bootstrap-table#1733]
Hi,

  I have a custom button for example "edit" and onClick of this button how I can I get the selected row data not just keys.

Thanks
Vinoth

**Comment by v1pothapu** [comment]
I was able to get the selected row data using this.refs.table.state.data. Closing the issue

**Comment by AllenFang** [comment]
Sorry for lately reply and you got it :)
