### ISSUE TITLE
Missing Data values when adding static headers on multiple rows.

### ISSUE THREAD

**Issue by dyennam** [AllenFang/react-bootstrap-table#1735]
@AllenFang 
Hello Allen, (Thanks for the awesome library.)
The below screenshot is my output of table with related data that shows up correctly when I removed the extra TableHeaders i used as static rows.. But i want my table to look like the 2nd image.

![screen shot 2017-11-05 at 5 24 51 pm](https://user-images.githubusercontent.com/4074631/32420841-5d6d7e30-c24e-11e7-9ed5-7d9229660e39.png)

![screen shot 2017-11-05 at 5 25 04 pm](https://user-images.githubusercontent.com/4074631/32420846-7a70b4ca-c24e-11e7-9c66-33ea8c4ed6a1.png)

Once i add the extra table headers to generate the a/b/c/d headers, the data doesn't display. I want the empty rows to appear after the a/b/c/d text cells.
Not sure how i should go about resolving this issue. The sample data i used just contained numbers to print thats all.
Any help would be greatly appreciated. 
Thanks for your time.

I have attached my code snippet.
`		<BootstrapTable data={testData} version={'4'} striped={true} hover={true}   >
						<TableHeaderColumn row='0' rowSpan='3' colSpan='6'  headerAlign='center'>Test Table</TableHeaderColumn>

						<TableHeaderColumn row='0' colSpan='20' headerAlign='center' thStyle={ { background: 'Gainsboro' } }> 1</TableHeaderColumn>
						<TableHeaderColumn row='0' colSpan='20' headerAlign='center'  >2</TableHeaderColumn>

						<TableHeaderColumn row='1' colSpan='10' headerAlign='center' dataField='check' > 1</TableHeaderColumn>
						<TableHeaderColumn row='1' colSpan='10' headerAlign='center'> 2</TableHeaderColumn>

						<TableHeaderColumn row='1' colSpan='10' headerAlign='center'> 3</TableHeaderColumn>
						<TableHeaderColumn row='1' colSpan='10' headerAlign='center'> 4</TableHeaderColumn>

						<TableHeaderColumn row='2' colSpan='2' headerAlign='center' >11/1</TableHeaderColumn>
						<TableHeaderColumn row='2' colSpan='2' headerAlign='center'>11/2</TableHeaderColumn>
						<TableHeaderColumn row='2' colSpan='2' headerAlign='center' dataField='id' isKey={ true } dataAlign='center'>11/3</TableHeaderColumn>
						<TableHeaderColumn row='2' colSpan='2' headerAlign='center'>11/4</TableHeaderColumn>
						<TableHeaderColumn row='2' colSpan='2' headerAlign='center'>11/5</TableHeaderColumn>

						<TableHeaderColumn row='2' colSpan='2' headerAlign='center'>11/6</TableHeaderColumn>
						<TableHeaderColumn row='2' colSpan='2' headerAlign='center'>11/7</TableHeaderColumn>
						<TableHeaderColumn row='2' colSpan='2' headerAlign='center'>11/8</TableHeaderColumn>
						<TableHeaderColumn row='2' colSpan='2' headerAlign='center'>11/9</TableHeaderColumn>
						<TableHeaderColumn row='2' colSpan='2' headerAlign='center'>11/10</TableHeaderColumn>

						<TableHeaderColumn row='2' colSpan='2' headerAlign='center'>11/11</TableHeaderColumn>
						<TableHeaderColumn row='2' colSpan='2' headerAlign='center'>11/12</TableHeaderColumn>
						<TableHeaderColumn row='2' colSpan='2' headerAlign='center'>11/13</TableHeaderColumn>
						<TableHeaderColumn row='2' colSpan='2' headerAlign='center'>11/14</TableHeaderColumn>
						<TableHeaderColumn row='2' colSpan='2' headerAlign='center'>11/15</TableHeaderColumn>

						<TableHeaderColumn row='2' colSpan='2' headerAlign='center'>11/16</TableHeaderColumn>
						<TableHeaderColumn row='2' colSpan='2' headerAlign='center'>11/17</TableHeaderColumn>
						<TableHeaderColumn row='2' colSpan='2' headerAlign='center'>11/18</TableHeaderColumn>
						<TableHeaderColumn row='2' colSpan='2' headerAlign='center'>11/19</TableHeaderColumn>
						<TableHeaderColumn row='2' colSpan='2' headerAlign='center'>11/20</TableHeaderColumn>

						<TableHeaderColumn row='3' colSpan='3' headerAlign='center'>A</TableHeaderColumn>
						<TableHeaderColumn row='3' colSpan='3' headerAlign='center'>B</TableHeaderColumn>
						<TableHeaderColumn row='4' colSpan='3' headerAlign='center'>c</TableHeaderColumn>
						<TableHeaderColumn row='4' colSpan='3' headerAlign='center'>d</TableHeaderColumn>

					</BootstrapTable>`

**Comment by AllenFang** [comment]
@dyennam how you generate new header column(a/b/c/d) ?!

BTW, currently, if you wanna the column/row span, I recommend you not to use `react-bootstrap-table`. Actually, there's still have some unalign column bugs, as you can see like your screenshot. Anyway, we are focusing on the development for [`react-bootstrap-table`](https://github.com/react-bootstrap-table/react-bootstrap-table2) and we will fixing those issues. Currently, I suggest you can use other react table component.  it's very sorry.

**Comment by AllenFang** [comment]
Anyway, feel free to ask any question :)

**Comment by dyennam** [comment]
@AllenFang I appreciate all the help, and your prompt response. As your question regarding the a/b/c/d columns, I used the following code snipped:

`<TableHeaderColumn row='3' colSpan='3' headerAlign='center'>A</TableHeaderColumn>
					<TableHeaderColumn row='3' colSpan='3' headerAlign='center'>B</TableHeaderColumn>
					<TableHeaderColumn row='4' colSpan='3' headerAlign='center'>c</TableHeaderColumn>
					<TableHeaderColumn row='4' colSpan='3' headerAlign='center'>d</TableHeaderColumn>`  I attached the full code for the table in the original issue.

**Comment by AllenFang** [comment]
oh~  sorry that I miss understand your question lol   About your requirement, `react-bootstrap-table2` not support yet, currently we only support span on header. But `react-bootstrap-table2` will support it as well, but need some time :)

**Comment by arunmmanoharan** [comment]
@AllenFang Does the table support colspan now? Like to have a row that spans across 4 columns?

**Comment by shorif2000** [comment]
i need this for http://allenfang.github.io/react-bootstrap-table/ to dynamically add `colspan` to cells depending on data/cell/row value

**Comment by Mikeez** [comment]
> oh~ sorry that I miss understand your question lol About your requirement, `react-bootstrap-table2` not support yet, currently we only support span on header. But `react-bootstrap-table2` will support it as well, but need some time :)
 
Does it support it now :P
