### ISSUE TITLE
Flash background color of individual rows when certain conditions have been met

### ISSUE THREAD

**Issue by charlesjhlee** [AllenFang/react-bootstrap-table#1736]
I can't find a way to change style of each row in the table based on cell contents, for example something similar to the color flashing inside the "ORDER BOOK" and "MARKET HISTORY" tables on this page: https://www.bittrex.com/Market/Index?MarketName=BTC-ETH

Would it be possible to add a functionality in react-bootstrap-table to achieve the above?

I can think of something like this but not sure whether the capability exists in react-bootstrap-table:

var dataArray = [
{}, {}, ...
{... , highlight_ind: 1 , ...}
... {}, {} ...
];

this.dataArray.map((item, index) => {
    <tr className: {item.highlight_ind === 1 ? highlight : null}
})

and in css:
.highlight {
   // some sort of timed background-color trigger/change
}

**Comment by AllenFang** [comment]
HI @charlesjhlee sorry for lately reply, please check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/style/tr-style-table.js#L26-L28 and let me know if you still have any question, thanks
