### ISSUE TITLE
Data get sorted locally even with remote sorting

### ISSUE THREAD

**Issue by jfremy** [AllenFang/react-bootstrap-table#1737]
https://github.com/AllenFang/react-bootstrap-table/blob/97171e1c0d7ad7291746ff594fc6c97e03348919/src/BootstrapTable.js#L281

When using a remote data source and remote sorting, react bootstrap table still sorts the data locally even though it should not.
I think the bug is located in BootstrapTable.js line 281 (in componentWillReceiveProps) and should probably be something like this:

```javascript
if (!this.allowRemote(Const.REMOTE_SORT)){
  data = this.store.sort().get();
}
newState.data = data;
```

I'm not completely familiar with that part of the code so the fix proposal might not be the right one.

I think the previous condition block (the `if (this.store.isOnFilter) { ... }`) probably need the same kind of logic checking for support of Const.REMOTE_FILTER.

**Comment by AllenFang** [comment]
@jfremy I'll check it soon

**Comment by AllenFang** [comment]
However, in the block of `if (this.store.isOnFilter) { ... }`, it will call the handleXXX function, in those function, we already check is remote or not.

**Comment by HomelessSamurai** [comment]
I've also been stuck on this issue for the past two days and only after reading this post have finally fixed it. 
The proposed solution by @jfremy has fixed the bug for me and now local sorting doesn't occur. 
Can you please add this in and release an update

**Comment by AllenFang** [comment]
sure, this will be fixed on next release.

**Comment by HomelessSamurai** [comment]
Thank you. When will the next release occur?

**Comment by meet-asite** [comment]
We are also stuck on this and waiting for the next release.

**Comment by AllenFang** [comment]
11/10, I promise it, sorry about this mistake.

**Comment by AllenFang** [comment]
Released on `v4.1.2`. Let me know if the problem still remain.

**Comment by meet-asite** [comment]
@AllenFang I have updated to v4.1.2. Now I am getting blank table with message: "There is no data to display" even though I have got data from the server. Could you please check?

**Comment by jfremy** [comment]
Yes, I'm seeing the same.
@AllenFang the `newState.data = data;` part should not be inside the `if (!this.allowRemote(Const.REMOTE_SORT)){ ... }` block.
It must be run with or without remote sort.

**Comment by harryxu** [comment]
@meet-asite @AllenFang I am getting blank table too, after updated to v4.1.2 just now. 😅

**Comment by AllenFang** [comment]
I'm shame on this mistake, fixed it again and released on `v4.1.3`. :(

**Comment by prajapati-parth** [comment]
@AllenFang To avoid such situations in future for react-bootstrap-table2, do you think we can have e2e tests that runs after every merge to master?

**Comment by AllenFang** [comment]
Something we can done for unit test, e2e test I will consider, but if we have more stronger unit tests in `react-bootstrap-table2`, this bug will be easy to tested.  So in current development for `react-bootstrap-table2`, I claim that we need to write tests more detail in particular.

**Comment by dawnmist** [comment]
I think something went wrong with the 4.1.3 release - looking at the compiled code in lib in the released package, it doesn't contain the fix you added and on the page the table still shows only the "no data" message in the table.

**Comment by meet-asite** [comment]
I am still getting blank table with V4.1.3

**Comment by AllenFang** [comment]
try again on `v4.1.4` and let me know if the problem still remain, thanks

**Comment by dawnmist** [comment]
Tables are displaying data properly now. :)

**Comment by meet-asite** [comment]
Thank you @AllenFang remote sorting is working properly now.

**Comment by AllenFang** [comment]
Thanks you guys. it's sorry that I make some mistake when released. :P
