### ISSUE TITLE
set all column width problem if enable multiple selection

### ISSUE THREAD

**Issue by xiril** [AllenFang/react-bootstrap-table#174]
There is a problem with fixed column width, when multiple selection is used.
If I check it on and off, the column width change, despite of fixed width (with different colum width).
The problem is the hardFixHeaderWidth() method in Tablebody.js.

**Comment by AllenFang** [comment]
@xiril, thanks for this report, did you set fixed width on each columns?

**Comment by xiril** [comment]
yes, all of columns have fixed width:

          <TableHeaderColumn dataField="id" isKey={true} hidden={true} width="0">ID</TableHeaderColumn>
          <TableHeaderColumn width="260" dataFormat={this.column1Formatter.bind(this)}>...</TableHeaderColumn>
          <TableHeaderColumn width="150" dataFormat={this.column2Formatter.bind(this)}>...</TableHeaderColumn>
          <TableHeaderColumn width="150" dataFormat={this.column3Formatter.bind(this)}>...</TableHeaderColumn>

**Comment by AllenFang** [comment]
@xiril, yes, I found your problem only happened if all column width been given, and it's a sticky problem on Bootstrap table, I mean the 'column width on Bootstrap table'. In the past several months, I've fix a lot of problem about column width, resizing, horizontal scroll.. but I've no idea for fixing this issues currently, so the workaround for now is dont set widths on each column to avoid this bug and I need a lots of time to solve these issues totally

**Comment by xiril** [comment]
ok, thanks for your suggestion

**Comment by xiril** [comment]
Hi,

The workaround doesn't work. I've tried all of possible combinations.
Only one thing is working, if I comment out this 2 lines in TableHeader.js:
React.cloneElement(this.props.children[i], {width: headerProps[i+startPosition].width+"px"});
React.cloneElement(this.props.children, {width: headerProps[0].width+"px"});

**Comment by AllenFang** [comment]
this 2 lines code is for window resizing, so it's maybe a workaround if your window doesn't change. would you show me your code? Because I can't reproduce this isssues :)

**Comment by xiril** [comment]
There is a full example code:


```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import { Button } from 'react-bootstrap';
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';

class Main extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      selected: []
    };
    this.componentWillReceiveProps = this.componentWillReceiveProps.bind(this);
  }

  componentWillReceiveProps(nextProps) {
    this.setState({  groups: nextProps.groups });
  }

  onRowSelect(row, isSelected){
    if (isSelected) {
      this.state.selected.push(row);
    } else {
      let index = this.state.selected.indexOf(row);
      if (index !== -1) this.state.selected.splice(index, 1);
    }
  }

  cellFormatter(cell, row) {
    return <span>{row.name}</span>;
  }

  infoFormatter(cell, row) {
    return <Button bsStyle="info" className="listButton"><i className="glyphicon glyphicon-pencil"></i></Button>;
  }

  memberFormatter(cell, row) {
    return <Button bsStyle="primary" className="listButton"><i className="glyphicon glyphicon-user"></i></Button>;
  }

  render() {
    var groups = [
      { id: 1, name: "Group001" },
      { id: 2, name: "Group002" },
      { id: 3, name: "Group003" },
      { id: 4, name: "Group004" },
      { id: 5, name: "Group005" }
    ];

    var selectRowProp = {
      mode: "checkbox",
      width: "40px",
      bgColor: "rgb(206, 206, 206)",
      onSelect: this.onRowSelect.bind(this)
    };
    return (
      <div className="groupList">
        <BootstrapTable data={groups} height="560" bordered={false} striped={true} hover={true} trClassName="reactTable groupListTable" selectRow={selectRowProp}>
          <TableHeaderColumn dataField="id" isKey={true} hidden={true}>ID</TableHeaderColumn>
          <TableHeaderColumn className="reactTableHeader groupListHeader" columnClassName="reactTableCell groupListCell" dataFormat={this.cellFormatter.bind(this)}>Group name</TableHeaderColumn>
          <TableHeaderColumn width="50" className="reactTableHeader groupListHeader" columnClassName="reactTableCell groupListCell" dataFormat={this.infoFormatter.bind(this)}></TableHeaderColumn>
          <TableHeaderColumn width="50" className="reactTableHeader groupListHeader" columnClassName="reactTableCell groupListCell" dataFormat={this.memberFormatter.bind(this)}></TableHeaderColumn>
        </BootstrapTable>
      </div>
    );
  }
}

ReactDOM.render(<Main/>, document.getElementById('content'));

```

**Comment by AllenFang** [comment]
ok, I'll test it :)

**Comment by AllenFang** [comment]
@xiril, I've tested your code, but If I check it on and off on selection column, the column width doesn't change. And in your example, the third and fourth column without content text, is that correct? Thanks :)

**Comment by xiril** [comment]
Yes, only buttons are in third and fourth column.
It seems there was an error in html file, I didn't have doctype in it.
It's solved my problem.

Thx for help

**Comment by AllenFang** [comment]
great :+1:
