### ISSUE TITLE
How to set dropdown uneditable

### ISSUE THREAD

**Issue by Grinzzekatze** [AllenFang/react-bootstrap-table#1740]
Hi!

How is it possible to set a cell of type "select" uneditable?

E.g:
For a normal cell it works like this: 
`  <TableHeaderColumn row="1" dataField="description" width={colSizes.description} dataSort={sortdata} editable={editTable}>Beschreibung</TableHeaderColumn>` 
where my editTable is true or false.

But how does it work when I use a dropdown? This doesn´t work for me:
` <TableHeaderColumn row="1" dataField="methode" width={colSizes.method} editable={{ editTable, type: 'select', options: { values: this.method } }}>Methode</TableHeaderColumn>`

Thanks!

**Comment by AllenFang** [comment]
HI @Grinzzekatze sorry for lately reply. 
```js
const attrs = { disabled: true };

<TableHeaderColumn row="1" dataField="methode" width={colSizes.method} editable={{ type: 'select', attrs: { attrs }, options: { values: this.method } }}>Methode</TableHeaderColumn>
```
