### ISSUE TITLE
Caret sort icon doesn't reset

### ISSUE THREAD

**Issue by HomelessSamurai** [AllenFang/react-bootstrap-table#1743]
The caret won't reset back to the original state when you've done another search, so the results table will have the sorted icon from the previous search rather than the default one.

**Comment by AllenFang** [comment]
yes, currently we dont support reset sorted table. This feature will be implement on [`react-bootstrap-table2`](https://github.com/react-bootstrap-table/react-bootstrap-table2), closed it due to duplicated issue.
