### ISSUE TITLE
Change cell or row color afterCellSave

### ISSUE THREAD

**Issue by dhananjayd232** [AllenFang/react-bootstrap-table#1744]
Is it possible to change color of all edited cells or rows containing edited cell

**Comment by prajapati-parth** [comment]
@dhananjayd232 if you have data indicating that a cell has been edited, you may use `Use classname & columnClassName` from here: https://allenfang.github.io/react-bootstrap-table/example.html#style

Thanks.

**Comment by dhananjayd232** [comment]
@prajapati-parth 
Thank a lot Prajapati for immediate reply.
Solved my problem.

**Comment by AllenFang** [comment]
Thanks @prajapati-parth
