### ISSUE TITLE
Cell text is not showing completely

### ISSUE THREAD

**Issue by dhananjayd232** [AllenFang/react-bootstrap-table#1745]
When I specify width to the column, it is not showing whole text of cell
![image](https://user-images.githubusercontent.com/17920326/32598744-85b90c00-c560-11e7-9331-89bc48003f2c.png)
Find screen for the same.

**Comment by prajapati-parth** [comment]
@dhananjayd232 In your case, can it work without specifying width?
Thanks.

**Comment by AllenFang** [comment]
HI @dhananjayd232  try this example: https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column/column-style-table.js#L32
