### ISSUE TITLE
Is CustomFilter with Remote filtering possible?

### ISSUE THREAD

**Issue by dawnmist** [AllenFang/react-bootstrap-table#1746]
We'd like to be able to use a regex filter with an 'includes regex' or 'does not include regex' checkbox toggle (because a regex for returning lines that do not match is awful for the end user to write - much nicer to be able to simply invert the regex test result). So I thought the best way to do this would be with a CustomFilter component that provides the checkbox & text field.

However, looking at the examples for CustomFilter it looks like the filter is expected to always be applied within the table, and I wasn't sure if the filter object values would be passed out of the table to use with remote filtering. Is the combination of CustomFilter + Remote Filtering currently possible?

**Comment by CEmocca** [comment]
As far as i understand your question, i think yes you can use both of that by implement CustomFilter and parse onFilterChange as an option to table.
In my opinion, if you want to custom filter only one column you can use on standard filter and implement CustomFilter which provides functionality as you want

You can see my example here: [sandbox](https://codesandbox.io/s/4zkx7m6q34)

Take a look at filter function which accept targetValue and parameter, in your case you can custom parameter to true or false based on your check box and implement logic to filter value by using regex or not.

Hope this help

**Comment by AllenFang** [comment]
Agree with @CEmocca. 
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-filtering.js and https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-filtering.js is a quick example for use a embed filter with remote mode. But it's ok to custom your filter with above example.

And also just remind, `remote` props on `BootstrapTable` accept a bool value or an abject, if a object give, you will have a ability to choose what functionality you want to handle on remote server, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-alternative.js#L9-L15

Most of people use `remote` for data fetching, pagination, delete/edit/insert, but keep sort, filtering and search on locally.
