### ISSUE TITLE
call BootstrapTable.exportCSV as a function?

### ISSUE THREAD

**Issue by monkeysuffrage** [AllenFang/react-bootstrap-table#1747]
Thanks for the great component.
Is there any way to call exportCSV as a function so that I can layout my buttons the way I want instead of having that green button alone above my table?
It looked like maybe handleExportCSV() would do it but then it got convoluted with _possibleConstructorReturn and I got lost.
Thanks in advance.

**Comment by prajapati-parth** [comment]
@monkeysuffrage Please refer #1667 
Thanks.

**Comment by monkeysuffrage** [comment]
Thanks @prajapati-parth, I think this is what I'm looking for, however, I was using:
onRef={ref => (this.table = ref)}
instead of:
ref={node => this.table = node}
I think maybe one of these is a more modern syntax but I'm not sure which, it moves so fast. Switching to `ref=` breaks other things for me.

**Comment by AllenFang** [comment]
@prajapati-parth thanks :)

**Comment by AllenFang** [comment]
HI @monkeysuffrage what's kind of problem you encounter? please describe, thanks

**Comment by monkeysuffrage** [comment]
It says  this.table.handleExportCSV is not a function

**Comment by AllenFang** [comment]
are you sure `this.table` is the instance of `BootstrapTable`?

**Comment by monkeysuffrage** [comment]
No, it's the DefaultSortTable component from the example.
I guess that explains the error. Thanks.
