### ISSUE TITLE
Keyboard Nav and selection row

### ISSUE THREAD

**Issue by andrisundae** [AllenFang/react-bootstrap-table#1750]
Btw thanks for your powerfull library...
I want to ask, how can i custom keyboard nav with selection row if i press pageUp or pageDown ?
so i can select row with press pageUp or pageDown in row like onclik in row.
Or maybe how can i customize onEnter to selection row if i navigate table ?

**Comment by ArthurBugan** [comment]
Up!

**Comment by AllenFang** [comment]
Currently, it's impossible in `react-bootstrap-table`. However, I can support a hooks and it will be called when navigate happen then you can do some work on it.

**Comment by AllenFang** [comment]
hey all, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/keyboard-nav/enter-to-select-row-with-nav-table.js) example and remember to upgrade to `v4.1.5`   thanks
