### ISSUE TITLE
Provides "index" parameter in "beforeSaveCell" and "afterSaveCell" callbacks

### ISSUE THREAD

**Issue by pcmnac** [AllenFang/react-bootstrap-table#1751]
I'm using react-bootstrap-table with redux and would be great if it provides "index" parameter in "beforeSaveCell" and "afterSaveCell" callbacks for cell editing. To workaround it, I had to put a aditional "index" field in my data, but requires me to do a map() always data is inserted or removed from my collection.

**Comment by AllenFang** [comment]
@pcmnac sorry for lately reply, what kind of index you need? row index or cell index? thanks

**Comment by pcmnac** [comment]
@AllenFang Thanks for reply. For my specific case, I need row index (just like you can get it in custom column render). When a cell is edited I dispatch an action to my reducer and I need to inform which row was modified. You can consider add other params (like "extra" or "columnIndex", or even a "meta" object grouping all this additional info)

**Comment by AllenFang** [comment]
@pcmnac cool, I will support this in next version, thanks

**Comment by AllenFang** [comment]
@pcmnac fixed on `v4.1.5`, 
there a props object will be passed as fifth argument for `beforeSaveCell` and fourth argument for `afterSaveCell`.  thanks

**Comment by jpjpjp** [comment]
Thank you @AllenFang!   Was able to programmatically discover that this prop looks like this:
