### ISSUE TITLE
Sorting field and order is not taken from props when using remote datasource

### ISSUE THREAD

**Issue by aalbul** [AllenFang/react-bootstrap-table#1752]
I found that when i use remote datasource, there is no way to reset / change sortName or sortOrder.
My use case is pretty easy. I store table data, pagination data + sorting data in redux. When i change sorting field in Redux (and not by clicking on header), this change is not reflected in the table.

This is happening because this data is not synchronised back into store inside of BootstrapTable.componentWillReceiveProps method.

**Comment by aalbul** [comment]
I created pull request to fix it. Please review it here: https://github.com/AllenFang/react-bootstrap-table/pull/1753

**Comment by AllenFang** [comment]
@aalbul I'll check this out, thanks

**Comment by AllenFang** [comment]
@aalbul I've some feedbacks on PR

**Comment by aalbul** [comment]
Thanks, please see my answer in PR :)

**Comment by AllenFang** [comment]
@aalbul released on `v4.1.5`. thanks your contributions

**Comment by dawnmist** [comment]
Prior to this change, clearing a sort used to work by:
* Using Table.cleanSort(), and
* Setting `SortOrder = undefined`, `SortName = ''` in the table options.

Doing this with 4.2.0 (I would assume in 4.1.5 - I just tried upgrading from 4.1.4) results in BootstrapTable throwing the error: `"The type of sort field and order should be both with String or Array"`.

The changes made for this issue do not take into account/provide any way to reset the current sort without triggering the above error check. i.e. `TableDataStore.setSortInfo(sortOrder, options.sortName)` enforces that sortOrder must never be undefined.
