### ISSUE TITLE
Exporting multilevel header react botstrap table

### ISSUE THREAD

**Issue by snehak-xor** [AllenFang/react-bootstrap-table#1757]
While exporting react bootstrap table having multi-leveled header .. gives excel warning.. 
"File format and extension of spreadsheet mismatch..File corrupted or unsafe."
Also the header is shifted to different level.
What might have gone wrong in my code :(

**Comment by snehak-xor** [comment]
![image](https://user-images.githubusercontent.com/22785615/32888449-4d5ef7ce-caed-11e7-9d02-33e1c65fee66.png)


![image](https://user-images.githubusercontent.com/22785615/32888477-6301b576-caed-11e7-9b98-bfa28af1a84f.png)


![image](https://user-images.githubusercontent.com/22785615/32888543-959def54-caed-11e7-8d8f-41497b1ad718.png)

**Comment by AllenFang** [comment]
hmm..  not very sure, becuase some span column will be perform as nothing in the CSV file. actually,  the CSV file is not support the span column as well and i guess the error you saw is just an invalid csv file when you import to EXCEL

https://stackoverflow.com/questions/43449236/export-html-table-with-rowspan-and-colspan-to-csv-or-xls

**Comment by snehak-xor** [comment]
Thanks got it. It was row span issue. :)
