### ISSUE TITLE
Custom Filter Multiple Filter

### ISSUE THREAD

**Issue by jiayingw703** [AllenFang/react-bootstrap-table#1758]
Hi, I am just wondering how can we have multiple filters based on the existing 'yes' or 'no' when.
For example, how can we filter a row is both 'yes' and 'unknown'? like a multi filtering in a same row.

<img width="379" alt="wx20171117-001956 2x" src="https://user-images.githubusercontent.com/22546775/32930516-26884d40-cb2d-11e7-8bcf-89f0b336228d.png">

**Comment by AllenFang** [comment]
HI @jiayingw703 sure, just check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js example

**Comment by jiayingw703** [comment]
Hi Allen, thank you for your replying.
I think I didny say it  in the right way. I already checked your example and added a new filter option call 'unknown'. 
Lets say if the first row, is both yes and no(I know its not gonna happen, but just for example..), how can I add it? And will the filter still apply? 
<img width="379" alt="32930516-26884d40-cb2d-11e7-8bcf-89f0b336228d" src="https://user-images.githubusercontent.com/22546775/32977805-dd7bb7f0-cc02-11e7-93a8-1c5b6cc2d9e7.png">
(since the others are not both yes and no, they will be filtered out..

thank you in advance!

**Comment by AllenFang** [comment]
hmm... I'm still not very clear...  you mean when use checked the "yes" and "no" checkboxs then you hope to filter the table which the column's value is contain "yes no" ?

am I right? so the column is only simple "yes", it will be filtered out?!

**Comment by jiayingw703** [comment]
Yes! thats exactly what I meant!
Thank you so much for your quick replying.

**Comment by AllenFang** [comment]
I see, column filter only work on column level not the row level. But you still can use the https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js example to custom your filter but you need to use filter in **remote mode**, it'll be some complicated, which mean

1. You need to define `options.onFilterChange` 
2. When filtering trigger, you filter the data by your special logic
3. update data to table.

https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-filtering.js
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-filtering.js

Above is example to show you how to use remote filter. Let me know if you have any questions

However, I don't suggest to do that but if you have no choice, remember to only enable filter as remote mode:

```js
remote(remoteObj) {
    // Only column filter will be handled by remote
    remoteObj.filter = true
  }
<BootstrapTable remote={ this.remote } .... >
```
