### ISSUE TITLE
event of pagination dropdown

### ISSUE THREAD

**Issue by ssjogus** [AllenFang/react-bootstrap-table#176]
i want to call a function on pagination dropdown. when i make 10 records to 20 records, some function needs to be executed. how can i call that? can you give some hints?

**Comment by AllenFang** [comment]
@ssjogus, there's no any hook for that, but I can provide it in next version :) The next version will release in these day

**Comment by AllenFang** [comment]
Fix it on v1.3.1, check example from [8f4d57b](https://github.com/AllenFang/react-bootstrap-table/commit/8f4d57b048e0063819cef185549fa1f8514e4941)
