### ISSUE TITLE
Retain all values of the table and show the checked as well in the previous page

### ISSUE THREAD

**Issue by repapa** [AllenFang/react-bootstrap-table#1760]
Hi,

My application is like this:
1. I have filters like name and country. I don't show the table first.
2. Upon selecting the input for filters and clicking the Filter Button, that's the time I will display the table with the data.
3. I will check rows that I want to process and by clicking next it will go to the next page and will display the checked rows.

I would like to ask for your assistance regarding on how I can retain all the values of the table and showing the checked one's as well in the previous page when I click the Back button.

Kind Regards,
Rey-An

**Comment by AllenFang** [comment]
@repapa 

if you use `selectRow` props, there's a quick way you can collect the selected row keys

```js

this.node.state.selectedRowKeys  // it will get all the rowkeys which selected

<BootstrapTable ref={ node => { this.table = node; }}
```

let me know if you still have any questions, thanks

**Comment by repapa** [comment]
Hi @AllenFang ,

Thanks for the reply but my issue is still not resolved.

I am able to get all the selected row keys and pass it to the next page using props. Now when I go to previous page, I pass it again using props. Now, how can I show it again in the table the selected row keys including the unselected row keys.

Kind Regards,
Rey-An

**Comment by AllenFang** [comment]
> I pass it again using props. Now, how can I show it again in the table the selected row keys including the unselected row keys.

You mean when you go back previous page, you wanna restore the before selected row?

If yes, there're some options:

1. `selectRow.selected`  // accept an rowkeys array
2. call table.setState({ selectedRowKeys })   // selectedRowKeys is an rowkeys array

First one will be prefer. Let me know if any problems.

**Comment by repapa** [comment]
Hi @AllenFang,

It works! Thank you very much for the assistance.

Kind Regards,
Rey-An
