### ISSUE TITLE
Nothing happens in table

### ISSUE THREAD

**Issue by ReboPH** [AllenFang/react-bootstrap-table#1763]
I have a component like this:

```
import React from 'react';
import ReactDom from 'react-dom';
import PropTypes from 'prop-types';
import TableHeaderColumn from 'react-bootstrap-table/lib/TableHeaderColumn';
import BootstrapTable from 'react-bootstrap-table/lib/BootstrapTable';
import 'react-bootstrap-table/dist/react-bootstrap-table.js';
import 'react-bootstrap-table/css/react-bootstrap-table.css';
```

In the view when I want order fields or filter by search input, nothing happens. No error console..no error precompile with webpack....nothing!! I see just the table with fields and data. 

I don't know what can I do. Any help?

Before in my aplication I had bootstrap-table without React and I love it! And I wish migrate to React :)

Thanks a lot.

**Comment by AllenFang** [comment]
hmm... it's very wired, would you have a repo for reproducing this issue?!  

However, I think you only need to import `BootstrapTable` and `TableHeaderColumn`:
`import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';`

Dont import 'react-bootstrap-table/dist/react-bootstrap-table.js' and make sure your import is same as above
