### ISSUE TITLE
Handling null in filterText

### ISSUE THREAD

**Issue by Velua** [AllenFang/react-bootstrap-table#1765]
I've got a column I'd like a text filter on however each row won't always have data in it and be undefined.. so given it uses this bit code...

`

    value: function filterText(targetVal, filterVal) {
      var cond = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : _Const2.default.FILTER_COND_LIKE;

      targetVal = targetVal.toString();
      filterVal = filterVal.toString();
      if (cond === _Const2.default.FILTER_COND_EQ) {
        return targetVal === filterVal;
      } else {
        targetVal = targetVal.toLowerCase();
        filterVal = filterVal.toLowerCase();
        return !(targetVal.indexOf(filterVal) === -1);
      }
    `

On line 
`targetVal = targetVal.toString();`

I'll get a targetVal is undefined error, if I make a pull request can we change this to..
`targetVal = targetVal ? targetVal.toString() : '';` instead?

**Comment by AllenFang** [comment]
@Velua I'll handle this in next version, thanks

**Comment by AllenFang** [comment]
Fixed on `v4.2.0`
