### ISSUE TITLE
Add event object to all props related to "click"

### ISSUE THREAD

**Issue by Robertmw** [AllenFang/react-bootstrap-table#1766]
Hello @AllenFang,

Related to https://github.com/AllenFang/react-bootstrap-table/issues/1524, I suggest to at least add the event object to **props.onRowClick** and **props.onExpandRow**. This should allow propagation handling.

I have a similar corner case where I'm expanding a row from an "inside" icon and my workaround is to check if the **cellIndex** is **NaN** (that means the target is the icon) and return immediately the function that handle the click event.

I can work on this in the weekend, if you're accepting this.

**Comment by Robertmw** [comment]
![image](https://user-images.githubusercontent.com/7315642/33019253-38be0a04-ce02-11e7-8a10-652712dc7a88.png)

Markdown of an expandable row

**Comment by AllenFang** [comment]
@Robertmw sure PR is welcome, let me know if any problems, I can help on it. thanks

**Comment by AllenFang** [comment]
Fixed  on `4.2.0`, thanks @Robertmw your PR 👍
