### ISSUE TITLE
hi, i am using react-bootstrap-table only problem i am facing is in filter functionality,  can you please answer whats wrong with my below code

### ISSUE THREAD

**Issue by skjadeja54** [AllenFang/react-bootstrap-table#1769]
![screenshot 37](https://user-images.githubusercontent.com/33864224/33069170-a2df7238-ced9-11e7-94b1-01354eb68e81.png)

**Comment by skjadeja54** [comment]
const qualityType = {
      "N": "N",
      "P": "P",
      "C": "C"
    };

function enumFormatter(cell, row, enumObject) {
  return enumObject[cell];
}



<BootstrapTable
data={this.props.uccrecordeddata}
deleteRow={true}
options={{ handleConfirmDeleteRow: this.customConfirm }}
remote={true}
selectRow={{ mode: 'checkbox' }}
striped hover condensed
 >
<TableHeaderColumn dataField='uniqueid' width='8%' columnClassName='my-class' isKey={true} >Id</TableHeaderColumn>
<TableHeaderColumn dataField='name' >Username</TableHeaderColumn>
<TableHeaderColumn dataField='panno'>Pancard No.</TableHeaderColumn>
 <TableHeaderColumn dataField='aadharno' >Aadhar No.</TableHeaderColumn>
<TableHeaderColumn width='8%' dataField='status'
  filterFormatted dataFormat={enumFormatter}
 formatExtraData={qualityType} filter={{ type: 'SelectFilter', options: qualityType, defaultValue: 1 }}>
 ><center>Status</center></TableHeaderColumn>
 <TableHeaderColumn width='6%' dataField='edit' dataFormat={this.editButton}><center>Edit</center></TableHeaderColumn>
<TableHeaderColumn width='9%' dataField='Next-Step' dataFormat={this.stepButton}><center>Next-Step</center></TableHeaderColumn>
</BootstrapTable>

**Comment by widdde** [comment]
Looks like the data you are trying to filter on is undefined. Try using a formatter in your status field that is returning an empty string if it has no value. Worth a try. :)

**Comment by AllenFang** [comment]
Duplicated with #1765
