### ISSUE TITLE
Search improvements

### ISSUE THREAD

**Issue by frontsideair** [AllenFang/react-bootstrap-table#177]
I think search should work on data after it's formatted, not before. I have a table with a timestamp right now and entering a number in search field brings a lot of rows that user may not need to see. 

Also, search is slow with a lot of data. I think it might help to have a debounce function for search.

I'll go on and implement these once I have some spare time, do you think it'll be useful?

**Comment by AllenFang** [comment]
@frontsideair, ok, I understand your problem, but about **search should work on data after it's formatted**, I think you can pre format it and render it or anther way to do it.Anyway, feel free to make a PR but I hope the feature should be general as possible :)  

And thanks your feedback and contributions :)

**Comment by frontsideair** [comment]
Thanks for quick reply. :+1: 

I thought about preformatting it, but then sorting doesn't work as I expect. In my specific case, there is a column with a lengthy timestamp and if I localize it before I pass to the component, sorting does not work correctly. If I do, then any numerical search brings more results than it should. Anyway, I think I can provide a convincing use case after I'm done implementing it. :smile:

**Comment by AllenFang** [comment]
Thanks :+1: , expect your :ship:

**Comment by AllenFang** [comment]
@frontsideair, try give a ```filterFormatted={true}``` on ```TableHeaderColumn```. But only support fully compare currently. so if you want to filter formatted data, please just return value without html or something else in ```dataFormat```.
