### ISSUE TITLE
onClick event not re-rendering the table when adding a new row and changing state

### ISSUE THREAD

**Issue by anbe6083** [AllenFang/react-bootstrap-table#1770]
I have three components:

* App: Parent component. Holds the state (balance) and changeBalance() function to increment the balance

* AccountHistoryTable: Uses [react-bootstrap-table](https://github.com/AllenFang/react-bootstrap-table). Meant to add a new row for the transaction when a user confirms and update the balance. 
* Balance: Simply displays the balance

My problem is this line on AccountHistoryTable (line 76):

    <button className='btn btn-success' onClick={ () => {this.handleSaveBtnClick(columns, onSave); this.props.changeBalance(); } }>Confirm</button>

 the onClick event handler has two functions: 

* this.handleSaveBtnClick(columns, onSave) (Line 23 in AccountHistoryTable)

        handleSaveBtnClick = () => {
          const { columns, onSave } = this.props;
          const newRow = {};
          columns.forEach((column, i) => {
            newRow[column.field] = this.refs[column.field].value;
          }, this);
          // You should call onSave function and give the new row
          onSave(newRow);
        }
* this.props.changeBalance() (Line 14 on App)

        changeBalance = () => {
            this.setState((prevState, props) => ({
              balance: prevState.balance + 1
            }));
            console.log(this.state.balance);
          }

When I click on the confirm button, the balance is being incremented, but a new row with the new transaction isn't being inserted. My first thought is because setState is asynchronous, it's the new row isn't being rendered, but I'm not too sure. Any help is appreciated. 

**App.js**

    import React, { Component } from 'react';
    import Balance from '../containers/balance';
    import AccountHistoryTable from './account_history_table';
    
    
    export default class App extends Component {
      constructor(props) {
          //assign an initial state of 1000
          super(props);
          this.state = { balance: 1000 };
          this.changeBalance = this.changeBalance.bind(this);
      }
    
      changeBalance = () => {
        this.setState((prevState, props) => ({
          balance: prevState.balance + 1
        }));
        console.log(this.state.balance);
      }
    
      render() {
        return (
          <div>
            <Balance balance={this.state.balance} />
            <AccountHistoryTable balance={this.state.balance} changeBalance={this.changeBalance}/>
          </div>
        );
      }
    }

**AccountHistoryTable.js**

    /* eslint max-len: 0 */
    /* eslint no-alert: 0 */
    /* eslint guard-for-in: 0 */
    import React from 'react';
    import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';
    
    
    const products = [];
    
    
    
    function onAfterInsertRow(row) {
      let newRowStr = '';
      for (const prop in row) {
        newRowStr += prop + ': ' + row[prop] + ' \n';
      }
    }
    
    
    
    class CustomInsertModal extends React.Component {
      
        handleSaveBtnClick = () => {
          const { columns, onSave } = this.props;
          const newRow = {};
          columns.forEach((column, i) => {
            newRow[column.field] = this.refs[column.field].value;
          }, this);
          // You should call onSave function and give the new row
          onSave(newRow);
        }
      
        render() {
          const {
            onModalClose,
            onSave,
            columns,
            validateState,
            ignoreEditable
          } = this.props;
          
          return (
            <div style={ { backgroundColor: '#eeeeee' } } className='modal-content'>
              <h2 style={ { color: 'red' } }>Enter Your Transaction</h2>
              <div>
                {
                  columns.map((column, i) => {
                    const {
                      editable,
                      format,
                      field,
                      name,
                      hiddenOnInsert
                    } = column;
      
                    if (hiddenOnInsert) {
                      // when you want same auto generate value
                      // and not allow edit, for example ID field
                      return null;
                    }
                    const error = validateState[field] ?
                      (<span className='help-block bg-danger'>{ validateState[field] }</span>) :
                      null;
                    return (
                      <div className='form-group' key={ field }>
                        <label>{ name } : </label>
                        <input ref={ field } type='text' defaultValue={ '' } />
                        { error }
                      </div>
                    );
                  })
                }
              </div>
              <div>
                <button className='btn btn-danger' onClick={ onModalClose }>Leave</button>
                <button className='btn btn-success' onClick={ () => {this.handleSaveBtnClick(columns, onSave); this.props.changeBalance(); } }>Confirm</button>
              </div>
            </div>
          );
        }
      }
      
    
    export default class AccountHistoryTable extends React.Component {
      
      createCustomModal = (onModalClose, onSave, columns, validateState, ignoreEditable) => {
        const attr = {
          onModalClose, onSave, columns, validateState, ignoreEditable
        };
        return (
          <CustomInsertModal { ... attr } changeBalance={this.props.changeBalance} />
        );
      }
    
    
      constructor(props) {
        super(props);
      }
      render() {
        const options = {
          afterInsertRow: onAfterInsertRow,   // A hook for after insert rows
          insertModal: this.createCustomModal
        };
        return (
          <BootstrapTable data={ products } insertRow={ true } options={ options }>
              <TableHeaderColumn dataField='payee' isKey={ true }>Payee</TableHeaderColumn>
              <TableHeaderColumn dataField='date'>Date</TableHeaderColumn>
              <TableHeaderColumn dataField='category'>Category</TableHeaderColumn>
              <TableHeaderColumn dataField='amount'>Amount</TableHeaderColumn>
          </BootstrapTable>
        );
      }
    }
**Balance.js**

    
    import React, { Component } from 'react';
    /*
    * Description: Render a component that includes the balance of the account
    * The state of the balance changes, so this will be a container
    */
    
    
    export default class Balance extends Component {
    
        render() {
            return (
                <div>
                    <h1 >Balance: {this.props.balance}</h1>
                    <h2 >Transaction</h2>
                </div>
    
            );
        }
    }

**Comment by AllenFang** [comment]
HI @anbe6083 sorry for lately reply, I have some question want to confirm:

1. Is there any error in the console.log?
2. if you remove to call `this.props.changeBalance()`, the new transaction will be available?
3. I suggest to call `this.props.changeBalance()` after new transaction inserted. However, I saw you defined the `options.onAfterInsertRow`, its a good place you can call the `changeBalance` here.

Let me know if you have any questions, thanks
