### ISSUE TITLE
When using react-s-alert in project, double alerts are shown when react-bootstrap-table are mounted.

### ISSUE THREAD

**Issue by widdde** [AllenFang/react-bootstrap-table#1771]
Hello!
We have some trouble with React-bootstrap-table in our project. We're using react-s-alert-component internally in our project and in all views that we are using react-bootstrap-table, we get 2 alerts when calling Alert.info (for example).
I think react-bootstrap-table use react-s-alert internally and somewhere define an  global < Alert > and because of this, we get alerts twice.
Can you provide a boolean in options or something, where you then can disable the global < Alert > internally in react-bootstrap table and then depend that it is defined in the parent project?

I think this is also an issue when you have 2 react-bootstrap-tables mounted at the same time.. 
We're not using tables in all our views, so we can not depend that we always have a react-bootstrap-table present where < Alert > is defined, so we need a way to not mount the < Alert > in react-bootstrap-table.

Thanks in advance.
PS. The version of react-s-alert you are using in react-bootstrap-table does use Object.Assign() which is not supported in IE11. When trying to show an alert in IE11 the application fails. Just a hint to also update react-s-alert in your project to a newer version.We have polyfilled this in our project at the moment and are using a newer version of react-s-alert where this is fixed, but it is not fixed in the version that react-bootstrap-table are using.

**Comment by AllenFang** [comment]
@widdde yes, I know this issue, if we have more than one table, will popup multiple alerts. That's why I create [`react-bootstrap-table2`](https://github.com/react-bootstrap-table/react-bootstrap-table2) and remove the alert dependency from `react-bootstrap-table2`.

However, I already stop to implement the new feature on `react-bootstrap-table`, but your suggestions is good, I'll give a props to not render the `Alert` inside the `react-bootstrap-table` and also update

Thanks

**Comment by widdde** [comment]
Thanks for the reply and fix :)
We will migrate to React Bootstrap table2 when it is available :)

**Comment by AllenFang** [comment]
@widdde sure, but it still need the time to develop ;)

**Comment by AllenFang** [comment]
@widdde fixed on `v4.2.0` add `renderAlert={ false }` on `BootstrapTable`. Also update the version of `react-s-alert`. thanks

**Comment by widdde** [comment]
Thank you @AllenFang !
Will test 4.2.0 asap! :)
