### ISSUE TITLE
how to pass event on onrowclick in react bootstrap table 4.0.1

### ISSUE THREAD

**Issue by patelroshan27** [AllenFang/react-bootstrap-table#1772]
@AllenFang, I am using react bootstrap table "^4.0.1" and would like to pass event object on    onRowClick : this.onRowClick in table options.

I also do have dataFormat in TableHeaderColumn and have 3 links in 2 different columns.  When i click on these links, it also called  onrowclick callback function.

**Somehow, i need to to stop event propagation in onrowclick callback function when clicking on anchor links from dataformatter functions.**  

FYI, dataformatter links will nagivates to another page and click on row without data links, will load expanded rows.

**# How to pass event object or stop event propagation in onrowclick callback function?**
Below are callback functions,

onrowclick callback function
  ***************
onRowClick(row, columnIndex)
  {
      if(row.multiSubmissionList != null && row.multiSubmissionList.length > 0 )
      {
        row.multiSubmissionList = [];
      } else {
        this.callService(row.fileID);
      }
  }

dataformat functions
*********************
function dataFormatterFunction(cell, row, field) {
  if(field.dataLink)
      return renderDataLink(cell, row, field);
  else if(field.optionLinks)
      return renderOptions(cell, row, field);
  else {
      return cell;
  }
}

function renderDataLink(cell, row, field) {
      return (
      <Link to={field.dataLink}>
        {cell}
      </Link>
    )
  }

function renderOptions(cell, row, field) {
  return (
    <div>
      <Grid fluid>
        <Row >
          <Col lg='6' >
            <Link to={field.optionLinks[0]}  className="btn btn-info" role="button" >
              <span className='glyphicon glyphicon-list' />&nbsp;&nbsp;Report
            </Link>
          </Col>
          <Col lg='6' >
            <Link to={field.optionLinks[1]}  className="btn btn-info" role="button">
              <span className='glyphicon glyphicon-blackboard' />&nbsp;&nbsp;Monitor
            </Link>
          </Col>
        </Row>
      </Grid>
    </div>
  )
}

Please let me know as soon as you can.
Full program as attached.

[index.zip](https://github.com/AllenFang/react-bootstrap-table/files/1497598/index.zip)

**Comment by Robertmw** [comment]
Hey, I already propsed a solution for this: https://github.com/AllenFang/react-bootstrap-table/issues/1766

I'm going to create a PR for this in weekend.
