### ISSUE TITLE
Additional Row for every page

### ISSUE THREAD

**Issue by repapa** [AllenFang/react-bootstrap-table#1773]
Hi @AllenFang,

I would like to ask if there's a feature that can add an additional row when navigating pages in Table.

In my case I want to add a "Grant Total" row for every page.

FYR. Please see images below:
![image](https://user-images.githubusercontent.com/19182530/33165574-4de6845c-d072-11e7-86d6-bdec74649ad2.png)

![image](https://user-images.githubusercontent.com/19182530/33165616-675d4290-d072-11e7-8d2f-51f74cd5f694.png)

Kind Regards,
Rey-An

**Comment by AllenFang** [comment]
@repapa the table footer(summary row) is not support but we will support on [`react-bootstrap-table2`](https://github.com/react-bootstrap-table/react-bootstrap-table2/tree/develop), but it's still work in progress.
