### ISSUE TITLE
expandParentClass option concat classNames

### ISSUE THREAD

**Issue by Robertmw** [AllenFang/react-bootstrap-table#1774]
Found a little bug.

Applying "expandParentClass"  will add the value to className, but without space. At least if you pass assign a string to "expandParentClass".

Example:
**Collapsed row:** 
```HTML
<tr class="tr-even">
```

**Expanded row:**
```HTML
<tr class="tr-evencustom-expand-parent">
```

I'll create a PR for it in a while.

**Comment by AllenFang** [comment]
Fixed  on `4.2.0`, thanks @Robertmw your PR 👍
