### ISSUE TITLE
Sort issue when using remote pagination

### ISSUE THREAD

**Issue by mrbeen351** [AllenFang/react-bootstrap-table#1775]
Hi @AllenFang , I have a problem when using sorting with remote pagination. When I added remote={ true } to react-bootstrap-table and click to the header then it didn't sort. Did anyone face this problem?

**Comment by AllenFang** [comment]
This is not a bug, actually, if you enable `remote` mode, all the data changing(sort, edit, insert, delete, search etc) will not being handled by `react-bootstrap-table` internally. 

But most of people only use `remote` on insert, pagination and they hope they can still sort/filter/search table internally, so `react-bootstrap-table` also have options to control:
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-alternative.js#L9-L15

Above example, `remoteObj` default set all the functionality as false which mean all the data change will not be handled in remote.

i suggest you to enable the function only that you really need to handle on remote(like: pagination or insert etc)

Let me know if you have any question and sorry for lately reply.

**Comment by mrbeen351** [comment]
Thank you  :))
