### ISSUE TITLE
SizePerPageDropDown doesn't dropdown in bootstrap@4.0.0-beta.2

### ISSUE THREAD

**Issue by darrenmerrett** [AllenFang/react-bootstrap-table#1779]
Need to add ${openClass} to class on dropdown-menu so it opens using bootstrap@4.0.0-beta.2

`<ul  className={${openClass} dropdown-menu} role='menu' aria-labelledby='pageDropDown'>`

https://github.com/AllenFang/react-bootstrap-table/blob/fed36faab76abf12c5dad5589910df7bb81dd908/src/pagination/SizePerPageDropDown.js#L37

**Comment by AllenFang** [comment]
@darrenmerrett do you add `version="4"` on `BootstrapTable` when you use bootstrap@4?

**Comment by DitoRaharjo** [comment]
I found some problem with the dropdown :
- The clickable area in dropdown is only the number itself not the whole cell
- Dropdown cannot be closed after I choose one of the option
- The dropdown option shown up above the element.

I'm using v4.2.0 and bootstrap 4.0.0-beta.2

![react-bootstrap-table bug](https://user-images.githubusercontent.com/21091663/33438270-eeef4366-d61c-11e7-9a80-4076629e2c30.gif)

**Comment by darrenmerrett** [comment]
@AllenFang Yes I add version="4". It worked fine when Bootstrap was in Alpha, but they made the change when they went to Beta.

**Comment by AllenFang** [comment]
@darrenmerrett yes, I trust it's about bootstrap beta, please forward to https://github.com/AllenFang/react-bootstrap-table/issues/1783, I'll collect these issues there. thanks

**Comment by AllenFang** [comment]
Fixed on v4.3.1
