### ISSUE TITLE
Checkbox not works on search - Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by damikael** [AllenFang/react-bootstrap-table#1784]
I'm using the follow implementation:

```
const selectRowProp = {
   mode: 'checkbox',
   clickToSelect: true,
   onSelect: (row, isSelected)=> {this.onRowSelect(row, isSelected)},
   onSelectAll: (isSelected, rows)=> {this.onSelectAll(isSelected, rows)}
};

<BootstrapTable 
   data={this.state.list}  
   options={options} 
   selectRow={selectRowProp} 
   search pagination
   striped hover>
      ...



onSelectAll(isSelected, rows) {		
   if(isSelected) {
      this.setState({ selected: rows })
   } else {
      this.setState({ selected: [] })
   }
   return false;
}

```

Checkbox selection works well if i don't use search field, but if I filter rows using search field, selection does not work anymore and I get the error "Uncaught TypeError: Cannot read property 'id' of undefined" both for onSelectAll and onSelect

**Comment by AllenFang** [comment]
@damikael are you trying to manage the selection by yourself instead of `react-bootstrap-table` internally?  If yes, You are suppose to add your `state.selected` to `selectRowProp.selected`

I think this is not a bug, maybe some code wrong,
