### ISSUE TITLE
Avoid state mutation

### ISSUE THREAD

**Issue by risonsimon** [AllenFang/react-bootstrap-table#179]
Hi,

I'm having trouble with adding data as mentioned in #168 without mutating state.

```javascript
handleInsertSubmit (newRow) {
    let result = this.refs.table.handleAddRow(newRow);
    console.log(result);
    this.props.actions.addUserData(newRow);
  }
```

When I do this, `handleAddRow` direclty updates my state and add the row. I do not want this as I'm using Redux and I want the state mutations to only happen through reducers.

Another problem is that when the reducer updates my state with the new row item. This change in state is not reflected in the table when I do this.

```javascript
handleInsertSubmit (newRow) {
    // let result = this.refs.table.handleAddRow(newRow);
    // console.log(result);
    this.props.actions.addUserData(newRow); // reducer updates the state
  }
```
This state is mapped to a prop and provided to the table.
```javascript
<BootstrapTable data={this.props.users} ref="table">
```
But this does not update unless I do `this.refs.table.handleAddRow`. But this method mutates the state.

**Comment by AllenFang** [comment]
@risonsimon, I am not familiar with redux, but I think to avoid state mutation is best practice in these flux implement redux, alt, or something like that. So just focus your second case, I think there should be no problem on <code>react-bootstrap-table</code>, because I have <code>componentWillReceiveProps</code> and will take the new <code>data</code> to render table again. so could you make sure <code>this.props.users</code> already have the new row? 
And I'll try to find whether there's some bug or not :)

**Comment by staminaloops** [comment]
Hello,
The state is not being mutated.
The thing is, if you are using redux, you dont need to use this api.

Tested and working

React component:
```
import { connect } from 'react-redux';
import { addRow } from 'reduxModules/tasks/insert-task';
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';

class DemoTable extends React.Component{

  handleInsertBtnClick(){
    var fakeRow = {
      id: 10,
      name: "Product one ",
      price: 240
    };
    // insert a fake row
    const { dispatch } = this.props;
    dispatch(addRow(fakeRow));
  }

  render(){
    return (
      <div>
      <button onClick={this.handleInsertBtnClick.bind(this)}>insert an row</button>
      <BootstrapTable ref="table" data={this.props.dataSet}>
          <TableHeaderColumn dataField="id" isKey={true}>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField="name">Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField="price">Product Price</TableHeaderColumn>
      </BootstrapTable>
      </div>
    );
  }
};

export default connect(
  state => ({
    dataSet: state.dataSet
  })
)(DemoTable); 
```
Redux
```
const ADD_ROW = 'task/insert-row';

export default function reducer(state = [], action) {
  switch (action.type) {
  case ADD_ROW:
// HERE, return the previous state with the new row
    return [
      ...state,
      action.row
    ]
  default:
    return state;
  }
}

// action
export function addRow(row) {
  return {
    type: ADD_ROW,
    row: row
  };
}
```

Root reducer

```
const rootReducer = combineReducers({
  // all the other reducers here,
  dataSet
});
```

**Comment by staminaloops** [comment]
![image](https://cloud.githubusercontent.com/assets/11683210/11761533/7e06146c-a0be-11e5-90a7-82a0fa970869.png)

**Comment by risonsimon** [comment]
@staminaloops brilliant. :)

Thank you, that worked beautifully. Thanks for taking time to make an example.

**Comment by AllenFang** [comment]
Thanks @staminaloops :+1:
