### ISSUE TITLE
maxLength text, mask

### ISSUE THREAD

**Issue by pedrophalves** [AllenFang/react-bootstrap-table#1790]
Is there any easy way to put maxLength in a column in edit and insertion?

Also, same question to include masks, such as phone numbers, dates, etc.

**Comment by AllenFang** [comment]
@pedrophalves you can custom it >
For cell editor > https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/cell-edit/custom-cell-edit-table.js

For the insert > https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/insert-modal/custom-insert-modal-field.js

You can learn how to custom your own input field, let me know if you got any question, thanks :)
