### ISSUE TITLE
Expand All and Collapse All records

### ISSUE THREAD

**Issue by knnemade99** [AllenFang/react-bootstrap-table#1791]
Hi,
I used the 2-level nested table, I want to expand all records and collapse all records feature in the table.
I tried passing expanding array in the options, but with that i need to send all the keys to this expanding array.
Is there any other solution i can prefer??

Thanks in advance.

**Comment by AllenFang** [comment]
@knnemade99 only this solution that you mentioned above. is there any problem that hard to get all rowkeys?

**Comment by knnemade99** [comment]
No, that worked for me, thanks
