### ISSUE TITLE
sizePerpage droddown issue

### ISSUE THREAD

**Issue by JyotiRani** [AllenFang/react-bootstrap-table#1793]
I am using "react-bootstrap-table": "^4.2.0" but when i click on the size per page drodown it doesn't work, rather causes the whole page refresh. What's going wrong?

**Comment by JyotiRani** [comment]
I solved it by adding the bootstrap.js but is it still required?

**Comment by AllenFang** [comment]
did you use bootstrap 4 beta ?

**Comment by 9005** [comment]
@JyotiRani : What do you mean by adding bootstrap.js? Where did you inject it ?

**Comment by JyotiRani** [comment]
I added the following in my application:
<script src="http://code.jquery.com/jquery-2.1.3.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.js"></script>

**Comment by 9005** [comment]
In which file did you add these changes?

**Comment by AllenFang** [comment]
@JyotiRani As I know, if you use bootstrap 4 beta, the dropdown will broken, I'll fix it ASAP.

But actually, `bootstrap.js` is not necessary for `react-boostrap-table`

**Comment by 9005** [comment]
I have not used bootstrap.js. The table is working for me except size per
page drop down. Need help??

**Comment by 9005** [comment]
This issue is fixed for me
