### ISSUE TITLE
How to Get Selected Column?

### ISSUE THREAD

**Issue by nikolay-kovalenko91** [AllenFang/react-bootstrap-table#1797]
Hi,
I have faced with unusual task: if I click on some row I can get all data from this row by using selectRow property. But what if I need to get associated column name too? For example, I clicked on some cell in column 'Price', how can I get its name('Price') as I clicked?
Thanks!

**Comment by AllenFang** [comment]
@nikolay-kovalenko91 sorry for lately reply, you can use `dataFormat` add add `onClick` event, we dont support the on cell click, but it will support on [`react-bootstrap-table2`](https://github.com/react-bootstrap-table/react-bootstrap-table2/tree/develop), however, it is still work in progress.

Let me know if you still have any question.

**Comment by nikolay-kovalenko91** [comment]
Ok, got it, thanks!
