### ISSUE TITLE
Clear button (e.g. X) inside input field (e.g. search)

### ISSUE THREAD

**Issue by RyanThomas95** [AllenFang/react-bootstrap-table#1803]
Hello!
I was wondering if there is any easy way to put an clear button (e.g. X) inside of an input field. I want to do so for searching and noticed there is a clear button available, but I want something that appears in the input box on the right side when I type. Is this possible given the existing framework or do I have to attach a custom component myself. Thanks!

**Comment by AllenFang** [comment]
@RyanThomas95 I think it's possible, but not sure if it's easy to you. The only way is to custom the search input field, you can check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/search/fully-custom-search-field.js)

But I'll not enable `options.clearSearch` in your case, instead, I will try to add a custom button inside the input field and handle the click event.

[There](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/custom/search) are some search component customization examples.

Hope this will help you and let me know if you have any problems, thanks
