### ISSUE TITLE
Ability to sort column either by number or letter

### ISSUE THREAD

**Issue by rikkirabz** [AllenFang/react-bootstrap-table#1805]
Hi!  Is there any way to add 2 options to the header of a column (which has alpha numeric data) which allows the user to either sort by number or by letter?  Thank you for a job well done! 
![screen shot 2017-12-12 at 9 19 18 am](https://user-images.githubusercontent.com/19497989/33889273-95d2206e-df1d-11e7-884e-794be349ed16.png)

**Comment by AllenFang** [comment]
@rikkirabz sorry for lately reply. Currently, it's hard to achieve your requirement in the `react-bootstrap-table`. But I'll consider to enhance it on [`react-bootstrap-table2`](https://github.com/react-bootstrap-table/react-bootstrap-table2/tree/develop) when I have time, 

Thank you :)
