### ISSUE TITLE
How to send Extra data to onFilterChange() 

### ISSUE THREAD

**Issue by dhananjayd232** [AllenFang/react-bootstrap-table#1808]
As we can send extra data to dataFormat by **formatExtraData** .
I want send some extra data to onFilterChange().

**Comment by AllenFang** [comment]
HI @dhananjayd232 sorry for lately reply, actually, I think I cant agree to add extra data to `onFilterChange`, it's a infinite requirement, you can use higher order function or some class/global variable to solve your issue.
