### ISSUE TITLE
Row swap feature (reorder rows with drag and drop)

### ISSUE THREAD

**Issue by ashishd751** [AllenFang/react-bootstrap-table#1810]
Hey @AllenFang,

Does the react-bootstrap-table include a row swap feature [where the user can long click on one row and reorder it, to place it above or below any of the other existing rows - a simple swap (preferably with drag-drop animations)]?

If no, do you plan on bringing it soon?

Regards,
Ashish

**Comment by AllenFang** [comment]
@ashishd751 hi sorry for lately reply, we dont support this feature, and like https://github.com/AllenFang/react-bootstrap-table/blob/master/CONTRIBUTING.md said, I already stop implement new feature and start develop new [`react-bootstrap-table2`](https://github.com/react-bootstrap-table/react-bootstrap-table2/tree/develop). 

PR is welcome, thank you :)
