### ISSUE TITLE
Tooltip UI design

### ISSUE THREAD

**Issue by RunCmd** [AllenFang/react-bootstrap-table#1811]
The issue I am having is table layout header is fixed with overflow hidden, and is there a chance to make UI tooltip design outside the overflow of the table ?  

By the way nice work on everything, and thank you in advance! :D .

**Comment by AllenFang** [comment]
HI @RunCmd what's the mean for tooltip, we dont support this kinda feature, do you mean the `title` attribute on cell?

Thanks
