### ISSUE TITLE
exportCSV causing "cannot read property 'isKey' of undefined

### ISSUE THREAD

**Issue by Slind14** [AllenFang/react-bootstrap-table#1814]
Hi there,
when I generate the table columns using "map", the export feature isn't working because it can't find the appropriate props.

e.g. 

```javscript
BootstrapTable data={boostrapTableData2} striped hover version='4' exportCSV={ true }>
                        <TableHeaderColumn key={-1} isKey dataField='group' dataSort>Product ID</TableHeaderColumn>
                        {data.types.map((key, i) => {
                            return <TableHeaderColumn key={i} dataField={key}>asdfasdf</TableHeaderColumn>;
                        })}
                    </BootstrapTable>
```

**Comment by AllenFang** [comment]
@Slind14 try to add `keyField='group' on the `BootstrapTable` instead of `isKey`

Thanks

**Comment by choi2k** [comment]
It seems the issue still exist even using `keyField` instead of `isKey`
```javascript
       if (Array.isArray(children)) {
          columns = children.filter(function (_) {
            return _ != null;
          }).map(function (column, r) {
            if (!column) return;
            var props = column.props;

            var isKey = props.isKey || keyField === props.dataField;
```
`column` would be an array if `TableHeaderColumn` is generated by array.map and thus `props` in undefined in this case.

**Comment by robrwx** [comment]
This is still a bug. You absolutely cannot create TableHeaderColumns using a map. Hard to believe you can only use hardcoded static column names. 

UPDATE:

This was my fault. I had one statically declared TableHeaderColumns and then a map to create the rest. When I changed the code to generate ALL columns with a map it worked fine.
