### ISSUE TITLE
Unable to access component state in onAddRow and beforeSaveCall

### ISSUE THREAD

**Issue by mahendratkg** [AllenFang/react-bootstrap-table#1815]
Hello,
I am using react-bootstrap-table@4.2.0 for creating a table and I need to make remote calls for add and edit on my table. I am unable to access **_this_** and in turn **_state_** of my component from **_onAddRow_** and **_beforeSaveCall_** in which I am creating this table. I wanted to refresh my table with the changes through adding new row or editing the cell value in my component's state. Please help me to achieve this behavior. 

Thanks,
Mahendra

My code snippet:

onAddRow(row) {

      request
        .post(this.url)                  //this is not defined here
        .send(data)
        .set('Accept', 'application/json')
        .set('Content-Type', 'application/json')
        .end((err, res) => {
          if (!err && res.ok) {
               // this.setState()     this not defined here
          } else {
            const body = err.response && err.response.body;
            const dataErrorMsg = body ? body.message : `Failed to add row: ${err}`;
          }
        });
}

**Comment by AllenFang** [comment]
@mahendratkg I dont think this is a bug, do you bind `onAddRow` to `this` or just write it as arrow function?

Thanks

**Comment by mahendratkg** [comment]
Thanks @AllenFang . I did not bind onAddRow to this. Now its working fine.
