### ISSUE TITLE
Cannot read property 'type' of null Error in TableHeaderColumns when having dynamic columns

### ISSUE THREAD

**Issue by rrameshkumar76** [AllenFang/react-bootstrap-table#1816]
I get the following error in latest version of react bootstrap table. We use remote mode.

```
TypeError: Cannot read property 'type' of null
    at TableHeaderColumn.getFilters
    at TableHeaderColumn.componentWillReceiveProps 
```
The error is in line number:
https://github.com/AllenFang/react-bootstrap-table/blob/master/src/TableHeaderColumn.js#L55
The filter property in this.props comes up as null.

This error occurs when we dynamically change the columns based on a column chooser we have in our UI. We have a dynamic column chooser like in image below. 

<img width="822" alt="screen shot 2017-12-15 at 6 44 23 pm" src="https://user-images.githubusercontent.com/13610968/34065510-ffac6d26-e1c7-11e7-8afe-20f67703375c.png">

This issue probably arose after https://github.com/AllenFang/react-bootstrap-table/commit/84cc76c7d92b4aa2eb3f1a3c8fddabd5b20f9647#diff-8f8b33ee4d9574a41f23bcf7dcd7440c

Everything works fine if all columns have filters, but i get above error when some fields do not have filters.

We were using version 3.3.7 and this functionality was working fine there.  The issue starts to happen after 4.0.5 release and worked fine until 4.0.3.

Adding && this.props.filter 
in line https://github.com/AllenFang/react-bootstrap-table/blob/master/src/TableHeaderColumn.js#L27 fixes the issue for me.

**Comment by AllenFang** [comment]
@rrameshkumar76 sorry for lately, I'll try to fix it on next version. thanks

**Comment by rrameshkumar76** [comment]
Thanks for the response @AllenFang

**Comment by AllenFang** [comment]
HI @rrameshkumar76 check `v4.3.1` and let me know if the problem still remain, thanks

**Comment by rrameshkumar76** [comment]
Looks like it works fine. Thanks @AllenFang
