### ISSUE TITLE
is there any way to change the react-bootstrap responsive view to Collapse by rows

### ISSUE THREAD

**Issue by Erandakuruneru** [AllenFang/react-bootstrap-table#1817]
is there any way to change the react-bootstrap responsive view to **Collapse by rows.**
rather than using the horizontal scrolling.

**Comment by prajapati-parth** [comment]
@Erandakuruneru Currently there's no such feature. And react-bootstrap-table has stopped developing new features, you can request new features to [react-bootstrap-table2](https://github.com/react-bootstrap-table/react-bootstrap-table2)

Thanks.
