### ISSUE TITLE
SizePerPage dropdown reserves space even if not present

### ISSUE THREAD

**Issue by waynebrantley** [AllenFang/react-bootstrap-table#1818]
When the sizePerPage dropdwon is not shown on the pager, it sets the visibility of itself to hidden.

https://github.com/AllenFang/react-bootstrap-table/blob/281db991c08f1d4cad2c522b13875a97d2e27e0f/src/pagination/SizePerPageDropDown.js#L21

This should be ```display:none```.   When using visibility, the element is not shown but the screen real-estate for that control is still reserved which results in a pager that is a good bit larger than it needs to be.

However, I also question why this control does not just ```return null``` if the drop down is hidden and not render anything at all.

**Comment by AllenFang** [comment]
@waynebrantley `v4.3.1` fixed this issue, if  `options.hideSizePerPage`  is true, we will not render the sizePerPage dropdown anymore.

Thanks 👍
