### ISSUE TITLE
Unable to create thin wrapper

### ISSUE THREAD

**Issue by im1dermike** [AllenFang/react-bootstrap-table#1820]
I'm trying to encapsulate react-bootstrap-table and create a thin wrapper component in React.  [Here](https://codesandbox.io/s/57py8w75p) is a CodeSandbox of what I have.  You can see that my `CustomTableHeader` component fails to render properly, but if it is replaced with the same `TableHeaderColumn` code above, it works without issue.

I'm wondering if the problem is that when `BootstrapTable` renders initially, it only looks for children of type `TableHeaderColumn` and it's not resolving my `CustomTableHeader` wrapper successfully.  That said, it is displaying the title correctly so something is working.

What would I need to do to make a wrapper?

**Comment by AllenFang** [comment]
> I'm wondering if the problem is that when BootstrapTable renders initially, it only looks for children of type TableHeaderColumn

No, I use `each` or `map`. The root cause is `react-bootstrap-table` recognize the props by `dataField`, `dataSort` etc when looping the children of `BootstrapTable`. When you doing a wrapper, you should giving the same props name like `TableHeaderColumn`.

Thanks
