### ISSUE TITLE
'Replace' property brakes checkbox row selection

### ISSUE THREAD

**Issue by stilllife00** [AllenFang/react-bootstrap-table#1822]
I hide certain columns on demand (via a filter button) and this was causing https://github.com/AllenFang/react-bootstrap-table/issues/1418 

To fix that I use the property `replace={true}` on `BootstrapTable` which worked very well.

I found out then, that it breaks the checkbox row selection. The selection happens (the callback is fired) but the checkbox remains unchecked. After a second click, the checkbox checks properly. Also worth to mention that the "Check all" checkbox does not check at all (even at second click)

Is this a bug or there is something I need to be aware of while using `replace` ?

**Comment by AllenFang** [comment]
@stilllife00, sorry for lately reply and `replace` always not a good solution, it's just workaround sometime. could you please give an a short and workable example to reproduce your issue(with `replace`)?  thanks

**Comment by stilllife00** [comment]
This bin (https://www.webpackbin.com/bins/-L1NI8yeZgTz73kF_t5E) shows that a clean usage of replace does not actually break the row selection.

I suspect I was messing with the `hidden` property. Instead of hiding certain columns I was not rendering them entirely and that somehow was messing up the behavior. 

The proper code was:

````
headers.map((header) => {
if (<conditions to hide the column>) {
    header.hidden = false
} else {
    header.hidden = true
}
return (
     <TableHeaderColumn ....
)
````

Closing the issue
