### ISSUE TITLE
Export to excel ( need to export data on different sheets of same excel file) in React bootstrap table

### ISSUE THREAD

**Issue by shalinibajpai0310** [AllenFang/react-bootstrap-table#1823]
Hi Allen,

I an having a set of records( suppose Set A and Set B) which i want to export to excel file but i want that SetA records should get exported to Sheet1 and SetB records should get exported to Sheet2.
Attached sample excel file for reference:

Kindly help asap
[SampleFile.xlsx](https://github.com/AllenFang/react-bootstrap-table/files/1574430/SampleFile.xlsx)
![image](https://user-images.githubusercontent.com/20796527/34194059-d78c02c6-e57c-11e7-865e-9185edb2bfbf.png)

**Comment by AllenFang** [comment]
@shalinibajpai0310 sorry for lately reply, I dont know if it's available to do in `react-bootstrap-table`, we only help user to down a CSV, so i think it's hard to control the sheets in the excel. However, PR is welcome, thanks
