### ISSUE TITLE
Custom Search Field's search is not working if we place it in custom tool bar

### ISSUE THREAD

**Issue by bhanuchandarch** [AllenFang/react-bootstrap-table#1824]
I have a created custom search field as per 'https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/search/fully-custom-search-field.js'. This is totally working.

`class SolutionSearchField extends Component {

    getValue() {
      return ReactDOM.findDOMNode(this).value;
    }
    setValue(value) {
      ReactDOM.findDOMNode(this).value = value;
    }
    render() {
      return (
        <input
          className={ 'form-control' }
          type='text'
          placeholder={ "Search" }
          onKeyUp={ this.props.search }/>
      );
    }
  }`

But if we place this in custom tool bar, the search functionality is not working.

```js
const createCustomToolBar = ( props ) => {
            return (
              <div>
                <div className='col-xs-4 col-sm-4 col-md-4 col-lg-4'>
                  <SolutionSearchField/>
                </div>
                <div className='col-xs-6 col-sm-6 col-md-6 col-lg-6'>
                    <button style={{border:'none',backgroundColor:'Transparent'}}>
                        <i className="fa fa-search" aria-hidden="true" style={{fontSize:'23px'}}></i>
		</button>
                </div>
                <div className='col-xs-2 col-sm-2 col-md-2 col-lg-2'>
                    { props.components.btnGroup }
                </div>
              </div>
            );
          }
        const options = {
            paginationShowsTotal: true, 
            toolBar: createCustomToolBar            
        };
```

**Comment by AllenFang** [comment]
@bhanuchandarch sorry for lately reply, about your question: dont render `SolutionSearchField` directly, you are supposed to rendering custom search panel via `options.searchField` and in the `options.toolBar`, render the search panel by `props.components.searchPanel`, like


```js
const createCustomToolBar = ( props ) => {
            return (
              <div>
                <div className='col-xs-4 col-sm-4 col-md-4 col-lg-4'>
                  { props.components.searchPanel }
                </div>
                <div className='col-xs-6 col-sm-6 col-md-6 col-lg-6'>
                    <button style={{border:'none',backgroundColor:'Transparent'}}>
                        <i className="fa fa-search" aria-hidden="true" style={{fontSize:'23px'}}></i>
		</button>
                </div>
                <div className='col-xs-2 col-sm-2 col-md-2 col-lg-2'>
                    { props.components.btnGroup }
                </div>
              </div>
            );
          }
```

Let me know if the problem still remain, thanks
