### ISSUE TITLE
no column is a key

### ISSUE THREAD

**Issue by runslow917** [AllenFang/react-bootstrap-table#1825]
the situation exactly similar to issue #402. Is the feature multiple columns as key is added now? @AllenFang  has commented a workaround for #402. But still i am not quite get it. Can you please illustrate with code?

**Comment by AllenFang** [comment]
@runslow917 sorry for lately reply, each rows in  `react-bootstrap-table` must have an unique key, for example:

```js
data = [{
  id: 1,
  name: 'test'
}, {
  id: 2,
  name: 'test'
}]
```

`id` is the unique value in the above example, if your data doesn't have any unique field, I will suggest you to generate a unique key via a sequence number to UUID and then feed into the `react-bootstrap-table`.

Thanks
