### ISSUE TITLE
body column widths don't match header column widths

### ISSUE THREAD

**Issue by kurt-o-sys** [AllenFang/react-bootstrap-table#1829]
Using react-bootstrap-table for making a table, the widths of the headers are not the same as the widths of the body-columns (see screenshot). I must be missing something...

![image](https://user-images.githubusercontent.com/2430465/34350966-f77d4c56-ea19-11e7-82c3-df10758eaf79.png)

**Comment by AllenFang** [comment]
@kurt-o-sys sorry for lately reply, you forgot to import the css of `react-bootstrap-table` 

https://github.com/AllenFang/react-bootstrap-table#cimport-css

**Comment by kurt-o-sys** [comment]
right. Thx!
