### ISSUE TITLE
Wrap Text in Cell (text overflow)

### ISSUE THREAD

**Issue by ryanh1** [AllenFang/react-bootstrap-table#1830]
Hi AllenFang,

Thank you for this awesome library.  You did a great job with it, and it is really helpful.

Currently, if the text exceeds the length of the cell, there is an ellipses, and it is truncated.  I would like to wrap the text inside of the cell so that the cell gets larger (vertically) to fit all of the text in.  Is this possible?

I am currently trying your messageFormatter function - but I am not getting the desired result.  This is the code:

  messageFormatter(cell, row) { 
    return (
      <p className='wrapText'>{cell}</p>
    )
  }

  render() {
    return (
      <div>
        <div className="container w-75 mt-5">
          <h3 className="text-center">Tweets</h3>
          <p className="text-secondary text-center" id="date"></p>
        </div>

        <link rel="stylesheet" href="https://npmcdn.com/react-bootstrap-table/dist/react-bootstrap-table-all.min.css" />

        <BootstrapTable
          data={this.props.tweets}
          options={ {noDataText: 'Please add a tweet to get started.'} }
          id="tweets"
          className="table table-bordered container w-75 mt-2"
        >
          <TableHeaderColumn dataField='author' width='20%'>Author</TableHeaderColumn>
          <TableHeaderColumn dataField='time' width='20%'>Time</TableHeaderColumn>
          <TableHeaderColumn isKey dataField='message' width='60%' dataFormat={ this.messageFormatter}>Tweet</TableHeaderColumn>
        </BootstrapTable>
      </div>
    )
  }
}

... and in a separate file:

.wrapText {
  word-break: break-all;
}

This code eliminates the ellipses but does not cause the cell to become larger.

Thank you for your help.

**Comment by bhanuchandarch** [comment]
use attribute 'tdStyle={ { whiteSpace: 'normal' } }' in <TableHeaderColumn/> to wrap the text in a cell.

`<TableHeaderColumn searchable={ false } dataField='testColumn' tdStyle={ { whiteSpace: 'normal' } } thStyle={ { whiteSpace: 'normal' } }>Test Column</TableHeaderColumn>`

which will solve your issue.

**Comment by ryanh1** [comment]
Thank you!  That's it.  Much appreciated.

**Comment by anubhavj19** [comment]
@bhanuchandarch I'm using tdStyle={ { whiteSpace: 'normal' } } but my text still doesn't wrap.
<BootstrapTable data={this.state.employeeList} tableStyle = {{ border: 'black 2.5px solid' }}>
        <TableHeaderColumn className = 'th' isKey dataField='Title' tdStyle={{ whiteSpace: 'normal' }} width='30%'>Mission</TableHeaderColumn>
        <TableHeaderColumn dataField='Accountabilities' tdStyle={{ whiteSpace: 'normal' }} width='70%'>Accountabilities</TableHeaderColumn>
        </BootstrapTable>

![image](https://user-images.githubusercontent.com/28684224/117799423-b607a380-b26f-11eb-9ca9-9fa5e8e44081.png)

Suggestions?

**Comment by aashiqahmed98** [comment]
> use attribute 'tdStyle={ { whiteSpace: 'normal' } }' in to wrap the text in a cell.
> 
> `<TableHeaderColumn searchable={ false } dataField='testColumn' tdStyle={ { whiteSpace: 'normal' } } thStyle={ { whiteSpace: 'normal' } }>Test Column</TableHeaderColumn>`
> 
> which will solve your issue.

This worked for me thanks , my style was , i used seperate css file which is:
```
.custom-table td{
    white-space: normal !important;
}
```

`custom-table` is a wrapper class for `table`
