### ISSUE TITLE
nesting TableHeaderColumn not working for dataFormat

### ISSUE THREAD

**Issue by waynebrantley** [AllenFang/react-bootstrap-table#1831]
Trying to create a custom wrapper around TableHeaderColumn and I cannot seem to override dataFormat.
The code below renders the ``job name`` field unmodified and ``renderField`` is never called

Maybe related to #1504 ?

```
const jobs = []

function addProducts(quantity) {
  const startId = jobs.length
  for (let i = 0; i < quantity; i++) {
    const id = startId + i
    jobs.push({
      id,
      name: "Application_Name_ " + id,
    })
  }
}

addProducts(5)

class ReactColumnFormatTable extends React.Component {
  public render() {
    return (
      <BootstrapTable data={ jobs }>
          <TableHeaderColumn dataField="id" isKey={ true }>Job ID</TableHeaderColumn>
          <TableHeaderHeaderColumnField dataField="name">Job Name</TableHeaderHeaderColumnField>
      </BootstrapTable>
    )
  }
}

class TableHeaderHeaderColumnField extends React.PureComponent {
    public render() {
      return (
      <TableHeaderColumn
            {...this.props}
        dataFormat={this.renderField}
         />
      )
    }

    public renderField = (value, row, formatExtraData, rowIdx) => {
      return (
        "Pre-" + value + "Post"
      )
    }
  }
```

**Comment by AllenFang** [comment]
@waynebrantley, firstly sorry for lately reply.
it's a restriction currently on `react-bootstrap-table`, we only recognize the first level children in `BootstrapTable` and populate the props form it. in your case `dataFormat` should be defined on `TableHeaderHeaderColumnField`

That will be a case we can improvement, however, we are not decide to do too much feature or enhancement on `react-bootstrap-table` and start to forward to [`react-bootstrap-table2`](https://github.com/react-bootstrap-table/react-bootstrap-table2/tree/develop), so PR is welcome.
