### ISSUE TITLE
React Bootstrap table 4.0.2

### ISSUE THREAD

**Issue by dileepmiahra** [AllenFang/react-bootstrap-table#1834]
Hi,

I am using "react-bootstrap-table": "^4.0.2" for pagination. The component is good.
I am facing the issue on dataSort on a column having date(date time data,createdOn:"21-12-2017 17:25:45").

It's not able to do the sorting on datewise. please suggest how to do it.

**Comment by dileepmiahra** [comment]
I dint receive any response...It's very urgent otherwise I have to go with other way to do it.

**Comment by waynebrantley** [comment]
Is this server side or client side sorting?
If client side, just create a custom sort function (https://allenfang.github.io/react-bootstrap-table/example.html#sort) 
In that use javascript 'dates' not text to sort.

**Comment by dileepmiahra** [comment]
client side sorting

**Comment by dileepmiahra** [comment]
I am clicking on header for sorting and my column has date coming from the server.

**Comment by dileepmiahra** [comment]
Thanks for ur response.Can you give example on Date(with time) sorting? I have done as you said but not getting the expected result.

**Comment by waynebrantley** [comment]
What exactly is coming from the server?
Is it a string like "01-05-2018 11:52:00"
If it is a string like that, then your sort function would be
```
function datesort(a, b, order) {   // order is desc or asc
  if (order === 'desc') {
    return new Date(a.someDate) > new Date(b.someDate)
  } else {
    return new Date(a.someDate) <= new Date(b.someDate)
  }
}
```

**Comment by dileepmiahra** [comment]
thanks for your reply. date is coming like "05-01-2018 14:37:03". I have tried as you said, but still not able to get the expected results.

below is my code
======
sortDateColumn(a, b, order) {   // order is desc or asc
      if (order === 'desc') {
        //console.log("Date"+a.createdOn)
        return new Date(a.createdOn) > new Date(b.createdOn);
        //return new Date(a.createdOn) - new Date(b.createdOn);
      } else {
        return new Date(a.createdOn) <= new Date(b.createdOn)
        //return new Date(b.createdOn) - new Date(a.createdOn);
      }
  }

and my rendering table is:

renderMyTableTable(breakFixData){
    if(breakFixData.length==0 || breakFixData.length==undefined){
      return(
          <div><font color="green" ><b>There is no matching data available</b></font></div>
      );
    }else{

      // console.log(breakFixData[0]);
      //alert("M1234")
    this.props.getBreakFixDetails(breakFixData[0].breakfixId,breakFixData[0].breakfixNumber,
      breakFixData[0].description,breakFixData[0].additionalInfo,breakFixData[0].createdOn,
      breakFixData[0].serviceName,breakFixData[0].serviceCriticality,
      breakFixData[0].spGroupname,breakFixData[0].spUsername,
      breakFixData[0].requestNumber);
    //this.props.getItemDetails(breakFixData[0].breakfixId);
      //alert(breakFixData[0].breakfixNumber)
    //console.log('breakfixobj'+breakFixObj.breakfixId)
    const options = {
      page: 1,  // which page you want to show as default
      sizePerPageList: [ {
        text: '10', value: 10
      }, {
        text: '15', value: 15
      }, {
        text: '25', value: 25
      },{
        text: 'All', value: breakFixData.length
      } ], // you can change the dropdown list for size per page
      sizePerPage: 10,  // which size per page you want to locate as default
      pageStartIndex: 1, // where to start counting the pages
      paginationSize: 6,  // the pagination bar size.

      //prePage: 'Prev', // Previous page button text
      //nextPage: 'Next', // Next page button text
      //firstPage: 'First', // First page button text
      //lastPage: 'Last', // Last page button text
      //paginationShowsTotal: this.renderShowsTotal,  // Accept bool or function
      paginationPosition: 'top',  // default is bottom, top and both is all available
      //paginationHAlign
      //hideSizePerPage: true > You can hide the dropdown for sizePerPage
      //alwaysShowAllBtns: true // Always show next and previous button
      // withFirstAndLast: false > Hide the going to First and Last page button,
      sortName:'breakfixId',
      sortOrder:'desc',
      //paginationShowsTotal: true
    };
    //console.log("this.props.quickViewDetails")
    //console.log(this.props.quickViewDetails)
    var selectRowProp = {
      mode: "radio",
      clickToSelect: true,
      bgColor: "#ADD8E6",
      //componentClass:"select",
      onSelect: this.onRowSelect,
      selected: [this.props.quickViewDetails[breakFixData.length-1].breakfixId]
    };

    return(
        <BootstrapTable
            bordered condensed hover responsive className="tableView"
            data={ breakFixData }
            pagination={true} options={ options }
            selectRow={selectRowProp}
            multiColumnSearch={true}
            search={true}
            >
              <TableHeaderColumn dataField='breakfixId' isKey={true} hidden>breakfixId</TableHeaderColumn>
              <TableHeaderColumn dataField='requestNumber' hidden>requestNumber</TableHeaderColumn>
              <TableHeaderColumn dataField='breakfixNumber' dataSort>Work Item ID</TableHeaderColumn>
              <TableHeaderColumn dataField='serviceName' dataSort>Service</TableHeaderColumn>
              <TableHeaderColumn dataField='consumerCompanyName' dataSort columnTitle>Company</TableHeaderColumn>
              <TableHeaderColumn width="10%" dataField='status' dataSort>Status</TableHeaderColumn>
              <TableHeaderColumn width="8%" dataField='priorityId' >Priority</TableHeaderColumn>
              <TableHeaderColumn dataField='impactedUsername' columnTitle>Requested by</TableHeaderColumn>
              <TableHeaderColumn dataField='createdOn' columnTitle sortFunc={ this.sortDateColumn }  dataSort>Reported On</TableHeaderColumn>
          </BootstrapTable>
        );
      }
  }

**Comment by waynebrantley** [comment]
``sortDateColumn`` is external sort assigned to the grid in options, not the column.  See the example External sorting I linked earlier.  Also, would help greatly if you just setup a simply example with fake data in codesandbox.io or something.  Would save everyone lots of time here!

**Comment by dileepmiahra** [comment]
Hi, i am not using sortDateColumn in option and it is not on external data. it is applied on data available in data={ breakFixData }.

**Comment by dileepmiahra** [comment]
I used like this
my function
sortColumnData(a,b,order,field,dataObject){// order is desc or asc
    //var d = new Date(a.createdOn)
    //console.log(d);
    //console.log(dataObject);
    if (order === 'desc') {
      return dataObject[new Date(a[field])] > dataObject[new Date(b[field])];
    }else{
      return dataObject[new Date(a[field])] < dataObject[new Date(b[field])];
    }
  }

and my grid
<TableHeaderColumn dataField='createdOn' sortFunc={this.sortColumnData} sortFuncExtraData={ breakFixData } columnTitle dataSort>Reported On</TableHeaderColumn>

but I am still not able to get the expected result

**Comment by dileepmiahra** [comment]
my grid
<TableHeaderColumn dataField='createdOn' sortFunc={this.sortColumnData} sortFuncExtraData={ breakFixData } columnTitle dataSort>Reported On</TableHeaderColumn>

**Comment by dileepmiahra** [comment]
in grid used like this
dataField='createdOn' sortFunc={this.sortColumnData} sortFuncExtraData={ breakFixData } columnTitle dataSort

**Comment by dileepmiahra** [comment]
but still not able to get expected data....is it possible to call a function(serverside) only once upon clicking in sort arrow.

**Comment by waynebrantley** [comment]
I was telling you that you need the sort in options...and you are not.  See examples.
Yes, you can do server sort.  See sort example :  https://allenfang.github.io/react-bootstrap-table/example.html#remote

**Comment by dileepmiahra** [comment]
I did exactly what you told, but it is not working on data field.

onSortChange(sortName, sortOrder) {
    if (sortOrder === 'asc') {
      this.props.quickViewDetails.sort(function(a, b) {
        if (a[sortName] > b[sortName]) {
          return 1;
        } else if (b[sortName] > a[sortName]) {
          return -1;
        }
        return 0;
      });
    } else {
      this.props.quickViewDetails.sort(function(a, b) {
        if (a[sortName] > b[sortName]) {
          return -1;
        } else if (b[sortName] > a[sortName]) {
          return 1;
        }
        return 0;
      });
    }
  }

and use this function in option

**Comment by dileepmiahra** [comment]
it is not working on date data

**Comment by dileepmiahra** [comment]
i mean not working on date column.

**Comment by dileepmiahra** [comment]
I am doing server sorting also and data is coming right but on page data is loading on date basis(on the basic of first digit) so not loading as expected. not able to find a solution from myside and still trying

**Comment by dileepmiahra** [comment]
is there any way to include below tag with reactbootstrap table in same row as searchField

<div className="inlineFields">
          <ControlLabel>Sort By:</ControlLabel>
          <FormControl componentClass="select" onChange={(event) => { this.onSortChange(event.target.value);}}>
            <option value="0">Ascending</option>
            <option value="1">Descending</option>
          </FormControl>
          <span className="orderAz controls"></span>
        </div>

**Comment by dileepmiahra** [comment]
a option tag

**Comment by dileepmiahra** [comment]
anyhow I am able to do this like below:
<TableHeaderColumn dataField='createdOn' columnTitle >Submitted Date<span>&nbsp;<a onClick={this.onSortAsc} className="black" title="Ascending"><b><i className={this.state.faCustomAsc}></i></b></a>&nbsp;<a onClick={this.onSortDesc} className="black" title="Descending"><i className={this.state.faCustomDesc}></i></a></span><span className="float-r margin-r-10"></span></TableHeaderColumn>

**Comment by dileepmiahra** [comment]
and calling server to update data but this is not right solution as I think. Once we have data available then why to fetch data again.

**Comment by dileepmiahra** [comment]
Submitted Date<span>&nbsp;<a onClick={this.onSortAsc} className="black" title="Ascending"><b><i className={this.state.faCustomAsc}></i></b></a>&nbsp;<a onClick={this.onSortDesc} className="black" title="Descending"><i className={this.state.faCustomDesc}></i></a></span><span className="float-r margin-r-10"></span>

**Comment by dileepmiahra** [comment]
I am closing this now.

**Comment by dileepmiahra** [comment]
how to export data to pdf format

**Comment by dileepmiahra** [comment]
is there any library to use for this?

**Comment by AllenFang** [comment]
@dileepmiahra we dont support this feature, thanks

**Comment by dileepmiahra** [comment]
Not able to make search on 'In stock' in react-boot-strap table. Or In a reserved keywork in react-boot-strap table. Is there any way to do search for In stock.
