### ISSUE TITLE
button onClick() function is calling while page loading without even clicking on button

### ISSUE THREAD

**Issue by bhanuchandarch** [AllenFang/react-bootstrap-table#1835]
I have customised the tool bar and placed a search button on it.

`const customToolBar = ( props ) => {
            return (
              <div>
                <div className='col-xs-4 col-sm-4 col-md-4 col-lg-4'>
                  {props.components.searchPanel}
                </div>
                <div className='col-xs-6 col-sm-6 col-md-6 col-lg-6'>
                    <button style={{border:'none',backgroundColor:'Transparent'}} onClick={ this.searchButtonHandler(this.state.searchFieldValue) }>
                        <i className="fa fa-search" aria-hidden="true" style={{fontSize:'23px'}}></i>
					</button>
                </div>
                <div className='col-xs-2 col-sm-2 col-md-2 col-lg-2'>
                    { props.components.btnGroup }
                </div>
              </div>
            );
          }`

if I load this page, this button's searchHanlder is calling without even clicking on it.

`searchButtonHandler (searchFieldValue, e) {
        console.log("Hello " + searchFieldValue);
        );}`

How to stop this. Any help on why this is happening would be appreciated. Thanks.

**Comment by AllenFang** [comment]
@bhanuchandarch could you please help to make your code clear? However, I think this is not a bug in `react-bootstrap-table`.
