### ISSUE TITLE
Sort and Update Issues

### ISSUE THREAD

**Issue by ricoxor** [AllenFang/react-bootstrap-table#1836]
Hello,
I have two issues with react-bootstrap-table.

The first issue is that the sort function doesn't work, when I change the order desc/asc the numbers are not ordered correctly.
As you can see on the screenshot there is a problem with the first column.

![Image](https://puu.sh/ySLrs/d52751350e.png)

I already try the change the type of the numbers as : float, numbers, int but nothing work.

    revertSortFunc = (a, b, order) => {
        if (order === 'desc') {
            return Number(a) - Number(b);
        } else {
            return Number(b) - Number(a);
        }
    }

My second problem is that the table don't update when I change the state.
When I check the state with the react extention, I can see the changes but the table stay the same.
Is there a function the refresh/update the table after my setState update?

Thank's a lot

**Comment by waynebrantley** [comment]
Can you provide a code example?
Suggest using something like codesandbox.io or equivalent.
here is a possible starting point https://codesandbox.io/s/4zkx7m6q34

**Comment by AllenFang** [comment]
Like @waynebrantley a simple and minimal example will be good to address your problems, thank you

**Comment by juanmafont** [comment]
Because the parameters 'a' and 'b' that you receive into revertSortFunc are not then content of the cell, they are the full line of data.

 So if you data is:
 { 
   pos: 1,
   symbol: 'btc',
   name: 'bitcoin',
  24hVol: 18800
   ....  
}

Try:
`revertSortFunc = (a, b, order) => {
    if (order === 'desc') {
        return a.pos - b.pos;
    } else {
        return b.pos - a.pos;
    }
}`
