### ISSUE TITLE
How to set any one row expanded while other's remained collapsed.

### ISSUE THREAD

**Issue by cloud-github** [AllenFang/react-bootstrap-table#1840]
![isssue](https://user-images.githubusercontent.com/6135944/34674709-0bac8a1c-f4af-11e7-91e8-6ee5b4d91183.png)

How to set row expanded when i click any one of the row while other rows should automatically collapse. At any time, only one row should expand. 
 How can i able to achieve this ?

**Comment by rikkirabz** [comment]
In your options assign assign onlyOneExpanding to true.  Default is false. 

```
 const options = {
     onlyOneExpanding: true,
}
```

**Comment by cloud-github** [comment]
Thank you so much @rikkirabz .

**Comment by AllenFang** [comment]
thank @rikkirabz 👍

**Comment by hingu167** [comment]
> In your options assign onlyOneExpanding to true. Default is false.
> 
> ```
>  const options = {
>      onlyOneExpanding: true,
> }
> ```

if it is not working then
?
