### ISSUE TITLE
How to set the theme color for whole website background?

### ISSUE THREAD

**Issue by JohnHour89** [AllenFang/react-bootstrap-table#1845]
Hi, Allen Fang, may I know it is available to set the background color of the website like set the theme color for it like this example can set Theme1, Theme2 or Theme3 and change the color of it?
Thank you.

---https://sm-react.github.io/storybook-boilerplate/?theme-ind=0&theme-sidebar=false&theme-full=false&knob-Title=Welcome%20to%20React-Theming&knob-Subtitle=Storybook%20Boilerplate%20Project&selectedKind=Theme%20Switcher&selectedStory=Component&full=1&down=1&left=1&panelRight=0&downPanel=sm%2Fstorybook-addon-material-ui%2Fmaterial-panel

**Comment by AllenFang** [comment]
@JohnHour89  I think this issue is irrelevant with `react-bootstrap-table`
