### ISSUE TITLE
custom search field position and size in bootstrap table

### ISSUE THREAD

**Issue by florentcuret** [AllenFang/react-bootstrap-table#1846]
following the instructions http://allenfang.github.io/react-bootstrap-table/custom.html#searchfield
I could not find a way to set the position and size of the search field.
It looks like its size is 1/3 of the table width aligned on the right.
Is there a way to set it on the left and make it 100% table width?
![screen shot 2018-01-11 at 10 57 26](https://user-images.githubusercontent.com/1671431/34819633-93f9a772-f6be-11e7-88a4-3b491dec7ddd.png)
![screen shot 2018-01-11 at 11 00 28-2](https://user-images.githubusercontent.com/1671431/34820897-3dd6a6ac-f6c2-11e7-93f2-2f101e3f436c.jpg)

**Comment by chillyistkult** [comment]
You can use your own input wherever you like and trigger this.table.handleSearch(searchText) on the BootstrapTable instance in the onChange event of your input.

**Comment by florentcuret** [comment]
I found a way better suiting my requirements:
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/toolbar/left-search-panel.js
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/toolbar/custom-toolbar-1.js

**Comment by AllenFang** [comment]
@chillyistkult solution is good and also @florentcuret you already found the answer

Let me know if you have any questions, thanks. BTW, `react-bootstrap-table2` had launch
https://github.com/react-bootstrap-table/react-bootstrap-table2
https://react-bootstrap-table.github.io/react-bootstrap-table2/

**Comment by chandanv03** [comment]
@AllenFang Hi I'm a newbie to react js, I'm looking for a fully loaded data table which will load data remotely (from an API call) /  JSON file 
i) should have an export to CSV button
ii) should have an external search field 
iii) pagination 
iv) page limit
v) a button/ icon in one of the columns, on click of it should display the modal popup to view the details of the row 
vi) multiple select of the rows and check all rows of the page 
the one shown in the screenshot but I couldn't find in your repos or examples 

PS: I couldn't find the full code for the below screenshot shown, please help me out.

![](https://react-bootstrap-table.github.io/react-bootstrap-table2/img/react-bootstrap-table2-sample.png)
ref: I tried this [link: https://appdividend.com/2018/05/04/react-bootstrap-table2-example/ ]
