### ISSUE TITLE
onSave on axios request calling axios request again

### ISSUE THREAD

**Issue by albertogaldames** [AllenFang/react-bootstrap-table#1847]
Hi I've made a custom modal where i make an axios post when i click on save button. I call the 'onSave' method when the response is done and valid but it looks like onSave function is calling the axios post again (Without onSave method it's just one call). It's weird because i've achieve this functionality in another component and this is almost a copy paste from the other.

`
handleSaveBtnClick = () => {
    const { onSave } = this.props;
    const newRow = {
        ...
    };
    axios.post('/api/newRow/', newRow)
        .then((response) => {
            onSave(response.data);
        })
        .catch((error) => {
            console.log(error.response);
        });
    }
render() {
    const { onModalClose } = this.props;
    return (
        ...........
        <ModalFooter>
            <Button className="modal-button modal-button__save" onClick={() => this.handleSaveBtnClick()}>Guardar</Button>
            <Button className="modal-button modal-button__cancel" onClick={onModalClose}>Cancelar</Button>
        </ModalFooter>
    );
}`

Am I doing something wrong?

Ps: I don't know how to write the issue to show the code formatted sorry :S

**Comment by crissdev** [comment]
@albertogaldames Wrap your code with ```js <newline> ...code.... <newline>```

See the link at the bottom of this comment box (https://guides.github.com/features/mastering-markdown/)

**Comment by AllenFang** [comment]
@albertogaldames if you want to sync up the new row into your database, I will not suggest you to doing like this, please enable the `remote` mode.

```js
remote(remoteObj) {
    // Only insert row will be handled by remote store
    remoteObj.insertRow = true;
    return remoteObj;
  }
 // ...
 <BootstrapTable data={ this.props.data }
                      selectRow={ selectRow }
                      remote={ this.remote }
```

and call your redux action or axios in the options.onAddRow`,
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-alternative.js#L34
