### ISSUE TITLE
When click on formatted data onRowClick columnIndex shows Nan

### ISSUE THREAD

**Issue by Skeetfly** [AllenFang/react-bootstrap-table#1850]
I'm trying to get columnIndex and row when i click on cell. But when i click on formatted data columnIndex value shows as Nan. 
Is there any other way to get cell columnIndex or Header and row or rowIndex?

**Comment by AllenFang** [comment]
@Skeetfly yup, that's a known bug, there's workaround is you add the `onClick` event on your formatted data field. It's hard to fix in `react-bootstrap-table` but I will make sure it's no problem for [`react-bootstrap-table2`](https://github.com/react-bootstrap-table/react-bootstrap-table2/tree/develop), anyway, it's still work in progress.


Let me know if you still have any questions,
Thank your :)
