### ISSUE TITLE
Two down carets appearing in pagination dropdown

### ISSUE THREAD

**Issue by abhishek84** [AllenFang/react-bootstrap-table#1851]
<img width="833" alt="screen shot 2018-01-16 at 3 00 15 pm" src="https://user-images.githubusercontent.com/6415265/34983183-b826a3c6-fad2-11e7-9123-77c48c0dffee.png">

**Comment by AllenFang** [comment]
@abhishek84 can you give me more information? thanks

**Comment by urirahimi** [comment]
How was this fixed?
