### ISSUE TITLE
table-layout: auto not working with react-bs-table css?

### ISSUE THREAD

**Issue by minamesephy** [AllenFang/react-bootstrap-table#1852]
Hi this is followup to the email:

I'm trying to use table-layout: auto in my CSS to get the table columns to resize based on their content. However, it seems like when I do this, the columns in the table get formatted, but the column headers do not get formatted with them. 

Is there a suggested workaround to do this?

**Comment by AllenFang** [comment]
@minamesephy it's because the `react-bootstrap-table` have two `table` actually, so you may need to apply `table-layout` into the header one.

header is a table and body is also another table.

Allen
