### ISSUE TITLE
hover selector on table rows

### ISSUE THREAD

**Issue by Anushka3174** [AllenFang/react-bootstrap-table#1853]
How can the user know if the row is clickable? Do we have the feature of something like hover selector in the data field to let the user know that some action is performed by clicking the row?

**Comment by Anushka3174** [comment]
> tooltip

**Comment by AllenFang** [comment]
@Anushka3174 currently, you can add a custom style on row: https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/style/tr-style-table.js#L33

For the clickable, useually apply `cursor` property.
