### ISSUE TITLE
[help wanted] Call from dataFormat function to a class' (component) function

### ISSUE THREAD

**Issue by dlplenin** [AllenFang/react-bootstrap-table#1854]
Hi Allen,
First, I have to say that your component is really great and I really apreciate your effort in this!, we are using this table in our project a lot.

I need to know if my implementation is ok, everithing is working, but I'm wondering if there is a better way to do this:

**One of my TableHeaderColumn:**
I'm calling a function wich belongs to the class where BootstrapTable is too, I use formatExtraData to pass (**this**) to the class/component instance.
`<TableHeaderColumn dataField="_id" dataAlign="center" dataFormat={this.alocationTool} formatExtraData={this} width="90"/>Selection</TableHeaderColumn>`

**The dataFormat function:**
Here I user extraData to access the props of the class/component and call another function on the **onChange** event.
```  javascript
alocationTool(id, rowData, extraData) {
    let alreadySelected = (extraData.props.course.students || []).includes(id); 
    rowData.isSelected = alreadySelected; 
    return (
      <label className="pos-rel">
        <input 
          type="checkbox" 
          checked={alreadySelected}
          onChange = {extraData.onChange.bind(extraData, id)}
        />
      </label>
    );
  }
```

**The Class' function:**
Here I need to acces to props.dispatch due to Redux.
```  javascript
onChange(id, event) {
    let updatedCurrentStudents = Object.assign([], this.props.course.students);

    if (event.target.checked) {
      updatedCurrentStudents.push(id);
    }
    
    if (!event.target.checked) {
      updatedCurrentStudents = updatedCurrentStudents.filter(student => student !== id);
    }

    this.props.dispatch(formActions.change('course.data.students', updatedCurrentStudents));
  }
```
**The result**
![image](https://user-images.githubusercontent.com/2582026/35110619-365a1410-fc47-11e7-88d0-f3f578ece8e3.png)

Thanks.

**Comment by AllenFang** [comment]
HI @dlplenin sorry for lately reply,

I think your code is ok for me. if the `onChange` and  `alocationTool` function is in the same function, maybe you dont doing like that.  You can still use extra data but don't keep a callback function inside it.

Let me know if you have any questions, thank you
