### ISSUE TITLE
Outside filters + search text

### ISSUE THREAD

**Issue by dlplenin** [AllenFang/react-bootstrap-table#1855]
Hi Allen,

It me again.

Is there any way to have filters outside the table that work together with the search entry (also the sorting functionality), like this:
![image](https://user-images.githubusercontent.com/2582026/35114630-64e79ddc-fc53-11e7-94dc-d6e6cdc626ed.png)

I have to work with filters that handle info that is showing (gender) and also that is not showing in the table (Programs in a select element, allergies in a radio button element, and others...).

Thanks.

**Comment by AllenFang** [comment]
For the search https://allenfang.github.io/react-bootstrap-table/docs.html#handleSearch
For the sort https://allenfang.github.io/react-bootstrap-table/docs.html#handleSort
For the https://allenfang.github.io/react-bootstrap-table/docs.html#handleFilterData

A quick example for filter
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/text-filter-programmatically.js#L23-L31

A quick example for sort
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/sort-table.js#L40
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/manage-sort-external-table.js#L44-L45
