### ISSUE TITLE
Column filter Header : how to put the text input zone on the right of column title

### ISSUE THREAD

**Issue by lilucanalplus** [AllenFang/react-bootstrap-table#1859]
Now the text input zone is under the title, can I put it just next to the title (on the same line) ?
![image](https://user-images.githubusercontent.com/28622563/35159303-0f249c96-fd3a-11e7-83ef-cdf3ca83814e.png)

Thanks in advance.

**Comment by AllenFang** [comment]
@lilucanalplus it's probably hard in `react-bootstrap-table` but it's possible in `react-bootstrap-table2`

BTW,  `react-bootstrap-table2` already launch yesterday:
https://github.com/react-bootstrap-table/react-bootstrap-table2
https://react-bootstrap-table.github.io/react-bootstrap-table2/

**Comment by lilucanalplus** [comment]
Ok thanks a lot !!! ;)
