### ISSUE TITLE
cellEdit: Does not save being edited if setState used.

### ISSUE THREAD

**Issue by amrutharamesh** [AllenFang/react-bootstrap-table#1860]
Hi, I am working with editable cells in react bootstrap table. When I am using this function `beforeSaveCell` to do some custom logic using `this.setState`, it does not save the cell being edited. I am returning `true` after the logic and it still doesnt save. Is `this.setState` not possible inside this function?

Thanks!

**Comment by AllenFang** [comment]
@amrutharamesh yes, we really don't suggest you to call `setState` in `beforeSaveCell` function, thanks!
