### ISSUE TITLE
Row Borders

### ISSUE THREAD

**Issue by gfleetwood** [AllenFang/react-bootstrap-table#1861]
Hi, 

The default borders aren't working for me even if I put `bordered={true}` explicitly. (Other commands like `striped` or `hover` aren't working either.) I have borders for the table and header by using this code from the documentation:

```        
             <BootstrapTable
              data = {data }
              tableStyle={ { border: 'black 1px solid' } }
              containerStyle={ { border: 'black 1px solid' } }
              headerStyle={ { border: 'black 1px solid' } }
              bodyStyle={ { border: 'black 1px solid' } }
          >
```
But I still have no borders separating the rows. How can I do that manually?

Secondly, when I change the width of the `TableHeaderColumn` I don't see the width of the table changing. How can I make it wider?

**Comment by AllenFang** [comment]
@gfleetwood I think you forget to import bootstrap css ?!  the issue still remain?  Sorry for lately reply.
