### ISSUE TITLE
How to display modal on clicking a row, with the row data in the modal?

### ISSUE THREAD

**Issue by aditya1950** [AllenFang/react-bootstrap-table#1864]
I am trying open a modal with the row data displayed in that modal on click event of any row. 
Please help.

**Comment by AllenFang** [comment]
We dont support thise feature but I think it's not too hard to implement, use [`onRowClick`](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/row-click-table.js#L25) and in the callback function, open your custom modal
