### ISSUE TITLE
Filter checkboxes outside of the table

### ISSUE THREAD

**Issue by klapouchy** [AllenFang/react-bootstrap-table#1865]
Is it possible to have the checkboxes that can filter columns be outside of the table?

Here is an example with the checkboxes within the column header. 
https://gist.github.com/AllenFang/f33003f64f0f3ce5239f82e5a97de94d

**Comment by dlplenin** [comment]
Take a look at this draft in [codepen](https://codepen.io/dlplenin/pen/GQRXBb)

**Comment by klapouchy** [comment]
@dlplenin thank you for the example. However, all filters require double click and the filter for name doesn't seem to work.

**Comment by dlplenin** [comment]
@klapouchy ... I'm not sure why is neccesary double click in codepen, but it works (only one click or in onChange event in radiobuttons or checkboxs) in my real project. 
Name filter is working, the filter action only shows the exact match "Zapato", pls open the console in codepen and you wll see the object to be passed to handleFilterData.

Let me know if it works.

![image](https://user-images.githubusercontent.com/2582026/35697985-c257371e-0759-11e8-9777-163c0ef746c2.png)

In my project I have radiobutton, checkbox, select...

**Comment by AllenFang** [comment]
@dlplenin thanks your response, great job, let me know @klapouchy if your question is not answered, sorry for lately reply.
