### ISSUE TITLE
Regarding showOnlySelected on Row Selection

### ISSUE THREAD

**Issue by yanamandra09** [AllenFang/react-bootstrap-table#1868]
Hi Allen, the showOnlySelected  (even though true on selectRow) by default it shows all and only after button click it shows selected rows. Is it possible to do otherwise or is there a way to overwrite 'showSelected' prop here https://allenfang.github.io/react-bootstrap-table/custom.html#selectOnly

**Comment by AllenFang** [comment]
@yanamandra09 sorry for lately reply, I think it's possible to overwrite to do it by the other ways, but this request is minor to me, so PR is welcome, thanks
