### ISSUE TITLE
handleFilterData + regex

### ISSUE THREAD

**Issue by dlplenin** [AllenFang/react-bootstrap-table#1869]
Hi Allen, 
How can I apply this:
`this.refs.table.handleFilterData({gender: /^Male$/});`?

I need to implement a filter to gender info (male, female), but due to "male" is into "female" string both values are returned, so I try to use a regex.

PD: Im goin to join some datafields (gender, grade, etc..) values and pass it object to handleFilterData because client dont want to use column's  filters.

**Comment by dlplenin** [comment]
If it helps someone:

https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/array-filter-programmatically.js

https://github.com/AllenFang/react-bootstrap-table/blob/359c324bb3bb89195e0ade784f2e6be935aa5f4c/src/Const.js#L43

So this works for me:
```
    this.refs.table.handleFilterData.handleFilterData({
      gender: {type: 'RegexFilter', value: '^Male$'}
    });
```

**Comment by carlosloaiza21** [comment]
Hi, how can i do the same but whit dateFilter? i mean:
gender: {type: 'DateFilter', value: '___Date condition___'}

**Comment by dlplenin** [comment]
Maybe:

  handleBtnClickDate = () => {
    var filter = {date: new Date(2015, 1, 31)};
    this.refs.table.handleFilterData(filter);
  };

**Comment by carlosloaiza21** [comment]
hi, thanks but if i understand the problem is the same i don't have a range date?
