### ISSUE TITLE
Need Freeze Column Functionality

### ISSUE THREAD

**Issue by karan-chauhan** [AllenFang/react-bootstrap-table#1870]
I want to freeze my some columns in grid. I want that columns freeze while horizontal scroll only, not with vertical scroll.
Can you please explain, how can i achieve that functionality?

**Comment by AllenFang** [comment]
we will try to implement this feature in [`react-bootstrap-table2`](https://react-bootstrap-table.github.io/react-bootstrap-table2/) when the beginning of the Q2, thanks

**Comment by 9005** [comment]
@AllenFang :  Hi Allen. Is Frozen Columns functionality is implemented in react bootstrap table. Please let me know.. Thanks

**Comment by nadezhda-serafimova** [comment]
Any updates on this issue?

**Comment by karan-chauhan** [comment]
@nadezhda-devlabs I think this functionality is still not available in react-bootstrap-table2, as i didn't find any doc from following link;
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/table-props.html
I switch my code from react-bootstrap-table to Paramquery grid few months ago, because didn't found this functionality.
You can use paramquery, its easy to use and has lot of options, customisations, formatting and freeze column functionality. You can ask me if you need any help.

**Comment by 9005** [comment]
hey guys, I dont think for freezing columns and scrolling horizontally you
will get help from react bootstrap table. But you can fix table header and
scroll vertically only data in table . Just give some height for table
content .

**Comment by NorbertSzabo** [comment]
you can apply: position: sticky for any of the columns
e.g.
.react-bs-container-body > table > tbody > tr > td:nth-child(1),
.react-bs-container-header > table > thead > tr:nth-child(1) > th:nth-child(1) {
  background-color: $background-color;
  position: sticky;
  position: -webkit-sticky;
  left:0;
  z-index:2;
}
