### ISSUE TITLE
getData from bootstrap table into a variable (Array of objects)

### ISSUE THREAD

**Issue by srikanthsailesh** [AllenFang/react-bootstrap-table#1871]
Hi, currently I am working on a task that requires me to load all the data i display in a bootstrap table into a single variable. Basically, I am doing this because i need the table data with values for an extra column which i am gonna add from a different source. I am trying to use getData feature in bootstrap to populate the variable but it does not seem to work. Could someone help me with the right syntax or any other suggestions? Thank you!

**Comment by AllenFang** [comment]
@srikanthsailesh  sorry for lately reply, take following solution:


```js
this.refs.tabe.state.data  // << current table data

<BootstrapTable ref="table" data={ ... }/>
```
