### ISSUE TITLE
render array items in newline

### ISSUE THREAD

**Issue by cheersalam** [AllenFang/react-bootstrap-table#1872]
I have a data which is like:
```
var products = [{
      id: 1,
      name: "Item name 1",
      price: 100,
      location: ["Address 1", "Address 2", "Address 3"]
  },{
      id: 2,
      name: "Item name 2",
      price: 100,
      location: []
  }];
```
Is there a way to print each `location` in newline in a row or new row within a row?

**Comment by cheersalam** [comment]
it is not possible with `react-bootstrap-table` as it expects flat structure. Workaround I found was manually adding `<br/>` after each array element. That worked for me. Closing.

**Comment by minamesephy** [comment]
Would you mind posting how you did this? I try to map the values as such for the array:
(qualifiers is an Array of Strings) 

                qualifiers: x.qualifiers.join("<br/>"), 

but then it literally prints the <br/> between elements instead of a newline
