### ISSUE TITLE
Possible to use the delete button functionality on another custom button.

### ISSUE THREAD

**Issue by bconrad1** [AllenFang/react-bootstrap-table#1873]
I'm currently using Semantic-UI react for my application, and I have a custom form group which includes my toolbar buttons. I was wondering if its possible to call the same functionality as the default deleteBtn component when I click my custom button. So basically onClick -> do the same thing as the table default delete button. 

I have it working with filtering where when I hit the filter button I use this.refs.table.handleFilterData({}). I'm curious if there is an equivalent for deleting rows.

**Comment by AllenFang** [comment]
@bconrad1 sorry for lately reply, I think my answer is yes, you can do any functionality on your custom component :)
