### ISSUE TITLE
Access 'columns' information outside options.insertModal

### ISSUE THREAD

**Issue by AlpacaGoesCrazy** [AllenFang/react-bootstrap-table#1874]
I would like to implement my own row insert without react-bootstrap-table's modal and I want to get some information on columns in my table. Is there any way to access 'columns' object without calling 'options.insertModal' and opening modal window, or completely prevent modal window from opening?
[custom insertmodal reference](https://allenfang.github.io/react-bootstrap-table/custom.html#insertmodal)

**Comment by AllenFang** [comment]
@AlpacaGoesCrazy I think if you dont use the `options.insertModal` to custom the insert modal, for `react-bootstrap-table` we can't pass something to you.  You can have your fully custom component to trigger the modal, but you need to control the anything you want.

There'a way you can have a columns information which wrapped up by `react-bootstrap-table`:


```js

this.ref.table.store.colInfos

<BootstrapTable ref="table" data={ ... } >
...
</BootstrapTable>
```

Let me know if you have any other questions, thank you.
