### ISSUE TITLE
Custom insertRow modal not working when using react-autosuggest as input

### ISSUE THREAD

**Issue by sebasvelasco353** [AllenFang/react-bootstrap-table#1875]
Hello Allen and other fellow developers, im trying to make a custom modal for inserting rows which its actually only and input with autosuggest (using the react-autosuggest module) and it works when put it outside of the modal, the problem is that i need it to be inside of the insert row modal, in fact i need it to be the only thing on the modal other than the confirm button.

i've been trying to get it right using your example and documentation but it just doesn't recognize the custom modal and brings me the default body.

i was wondering if i could get any help on it.

Thank you so much.

**Comment by AllenFang** [comment]
HI @sebasvelasco353 sorry for lately reply, how you custom the input or whole the model body or event modal? there are some [example](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/custom/insert-modal) you can check :)

Or maybe you can share your code, thanks
