### ISSUE TITLE
react-bootstrap-table transpose

### ISSUE THREAD

**Issue by mahendratkg** [AllenFang/react-bootstrap-table#1876]
Hello,
Is there a way to display a bootstrap table vertically. I have a table with single row and lots of columns and would prefer to show it vertically i.e. Column names at left vertically and the values corresponding to its right like a key value pairs. Please let me know if this feature is already available or possible to implement. Thanks.

**Comment by AllenFang** [comment]
@mahendratkg sorry for lately reply, currently, we don't have this kind of feature.

**Comment by mahendratkg** [comment]
Thanks for your reply. It will be very nice to have it. Please consider this for react-bootstrap-table-2.

**Comment by AllenFang** [comment]
@mahendratkg sure, I think already some people ask for it https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/79
