### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by patrick-kelly-eigen** [AllenFang/react-bootstrap-table#1879]
Hi there, 

I have loaded in bootstrap css and react-bootstrap-table css files with require.
However, when this screen is loaded I get white text (you can only see the text when you click to edit)
Also, the table line spacing is messed up and there is no styling on the delete and new buttons.
Could you please offer some guidance?

Thank you.

require('../../../../node_modules/react-bootstrap-table/dist/react-bootstrap-table.min.css');
require('bootstrap/dist/css/bootstrap.css');
import React from 'react';
import PropTypes from 'prop-types';
import {connect} from 'react-redux';
import {
  fetchUsers,
//  editUser,
//  deleteUser
} from 'Actions/users_actions';
import {BootstrapTable, TableHeaderColumn} from 'react-bootstrap-table';
//import Bootstrap from 'bootstrap';
//import Jquery from 'jquery'

class UserManagementConsole extends React.Component {

    constructor(props){
        super(props);
    }

    componentWillMount() {
        this.props.fetchUsers();
    }

    render() {
        //const user_obj = this.props.users.allIds.map(id => this.props.users.byId[id]);
        const title = 'User Management'

        return (
          <div>
            <Header title={title}/>

          </div>
        )
    }
}

class Header extends React.Component {
    render(){
        return (
          <div className="ui-header">
            <div className="centered">
              <h2>{this.props.title}</h2>
              <div>
                <EditableTable/>
              </div>
            </div>
          </div>
        );
    }
}

class EditableTable extends React.Component {
    render() {
        
      const user_obj = [{
        id: 1,
        username: 'PatrickKelly1',
        email: 'patrick.kelly@eigentech.com'
      },
      {
        id: 2,
        username: 'Sinan1',
        email: 'sinan@eigentech.com'
      }]

      const dataStyle = {
        fontWeight: 'bold',
        fontSize: 'large',
        textAlign: 'center',
        backgroundColor: '#A9A9A9'
      };

      const cellEditProp = {
        mode: 'click',
      };
      const selectRow = {
        mode: 'radio' //radio or checkbox
      };
      return (
        <BootstrapTable version='4' data={user_obj} options={{noDataText: 'Add some users!'}} cellEdit={ cellEditProp }  selectRow={ selectRow } deleteRow insertRow >
          <TableHeaderColumn dataField="id" hidden={ true } isKey></TableHeaderColumn>
          <TableHeaderColumn dataField="username" editable={ true } >User Name</TableHeaderColumn>
          <TableHeaderColumn dataField="email" editable={ true } > Email</TableHeaderColumn>
        </BootstrapTable>
      );
    }
  } 
  //

const mapDispatchToProps = dispatch => ({
    fetchUsers: () => dispatch(fetchUsers()), 
//    editUser: () => dispatch(editUser(this.state.uid)),
//    deleteUser: () => dispatch(deleteUser(this.state.uid))
});  
const mapStateToProps = state => ({
    users: state.users,
}); 

export default connect(
    mapStateToProps, 
    mapDispatchToProps
)(UserManagementConsole);

**Comment by Cvladianu** [comment]
I think you may have written the css import with the wrong path.
import 'react-bootstrap-table/dist/react-bootstrap-table-all.min.css';
just write it like this <module_name>/<additional_path>, npm should be able to figure the correct path properly

Also, have this in the component where you display your EditableTable. Had this issue, and properly providing the path to this css file solved it :)
