### ISSUE TITLE
Table search + Cell Editing

### ISSUE THREAD

**Issue by laitang2000** [AllenFang/react-bootstrap-table#188]
When search is enabled and the rows filtered, if cell editing is enabled for a column I get an error message in the console "Uncaught TypeError: Cannot assign to read only property 'xxx' when I attempt to edit the cell.

It all works fine if no search value is entered.

Thanks

**Comment by AllenFang** [comment]
Thanks your bug reports, I'll solve it in the recent.

**Comment by AllenFang** [comment]
@laitang2000, fix it in newest version :)

**Comment by laitang2000** [comment]
Awesome! Thanks :)
