### ISSUE TITLE
Render array of objects vertically in a react bootstrap table

### ISSUE THREAD

**Issue by vpb88** [AllenFang/react-bootstrap-table#1883]
Hi Allen,

I have array of objects if I want to render it vertically like as below

my array is[
{
"month": "Jan",
"amount":"10.00"
},
{
"month": "Feb",
"amount":"20.00"
},
{
"month": "mar",
"amount":"30.00"
},
{
"month": "apr",
"amount":"30.00"
},
{
"month": "may",
"amount":"60.00"
},
]
I want as table like below month comes as  headers and amount comes as row

jan feb mar apr may 
10   20  30   30   60

**Comment by AllenFang** [comment]
`react-bootstrap-table` already stop implement new feature, and start to forward to [`react-bootstrap-table2`](https://react-bootstrap-table.github.io/react-bootstrap-table2/), we will consider to implement this feature on `react-bootstrap-able2` > https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/79
