### ISSUE TITLE
Saving pagination, how many rows, and search value with redux

### ISSUE THREAD

**Issue by raevangregson** [AllenFang/react-bootstrap-table#1884]
I am trying to save the pagination, how many rows showing selected, search value and any column sorting thats been set by the user so I can save to state using redux, this way when the user navigates off and back to the page with the table there settings are still there. Do you have a suggestion for the best way to do this?

**Comment by AllenFang** [comment]
sure, `react-bootstrap-table` have some hooks/listener so that you can collect page/sort/filter change's information.

**Comment by AllenFang** [comment]
we got a lots of examples: https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js . let me know if you have any qurstions, thanks

**Comment by raevangregson** [comment]
Thanks I ended up finding The callbacks I needed after doing some digging, thanks!
