### ISSUE TITLE
SelectFilter doesn't work properly; returns nothing or shows empty table 

### ISSUE THREAD

**Issue by VladimZaguzin** [AllenFang/react-bootstrap-table#1885]
Hello, I need some help
I have a table populated with data from DB. I need to make a filter on user side (amount of data is less then 200 rows, so not a big problem). For My task I need to make a select filtration based on values that we have in one column 

that's how I tried to make it 

    const AccessGroup =[];
            this.state.usersInfo.map(usersInfo => {
                if (AccessGroup.indexOf(usersInfo.AccessGroup) === -1) {
                    AccessGroup.push(usersInfo.AccessGroup)
                }
            });
    
    const AccessGroupArr = Object.assign({}, AccessGroup)
    console.log(AccessGroupArr) // just to see what's inside that array 

 
     //got it from examples and I think that this function  
     function enumFormatter(cell, row, enumObject){ 
            return enumObject[cell];
     }

     return (
                <div>
                    <BootstrapTable data = {this.state.usersInfo}                  
                                    striped hover 
                                    selectRow={ selectRow }
                                    remote={ this.remote }
                                    insertRow deleteRow search pagination
                                    cellEdit={ cellEditProp }
                                    options={ {
                                        onCellEdit: this.props.onCellEdit,
                                        onDeleteRow: this.props.onDeleteRow,
                                        onAddRow: this.props.onAddRow
                                    }}
                                    >
                        <TableHeaderColumn width="150" dataField='UserId' isKey={true} dataSort={true}>User ID</TableHeaderColumn>
                        <TableHeaderColumn width="250" dataField='UserName' dataSort={true}>User Name</TableHeaderColumn>
                        <TableHeaderColumn dataField='AccessGroup' 
                        editable={{ type: 'select', options: { values: AccessGroup }}} 
                        dataSort={true} 
    
                        filterFormatted dataFormat={enumFormatter}
                        formatExtraData={AccessGroupArr}
    
                        filter={{type:'SelectFilter', options: AccessGroupArr}}
                        >Access Group</TableHeaderColumn>
    
                        
                    </BootstrapTable>
                </div>

as for now it's works like this -
when i open a page a got 2 arrays instead of one [![enter image description here][1]][1]

next I have all the date when there is no filter applied AND I remove `filterFormatted dataFormat={enumFormatter}` line from column settings 

and it looks like this 
[![enter image description here][2]][2] 
but as soon as I add `filterFormatted dataFormat={enumFormatter}` the result looks like this 
[![enter image description here][3]][3]

in any case with or without `filterFormatted dataFormat={enumFormatter}` when i apply filter a final result looks like this 
[![enter image description here][4]][4]

dropdown for filter is populated correctly but it still doesn't work properly.

What am I doing wrong ?  

  [1]: https://i.stack.imgur.com/AlY1q.png
  [2]: https://i.stack.imgur.com/bwxee.jpg
  [3]: https://i.stack.imgur.com/Fb8Wc.jpg
  [4]: https://i.stack.imgur.com/lSLbO.jpg

**Comment by jonathanbroderick** [comment]
@VladimZaguzin I'm having the same problem. Does anyone know if this repo is still being maintained? I see the most recent commit was 20 days ago as of today so that doesn't seem promising. I guess I need to look elsewhere for a good React table component.

**Comment by AllenFang** [comment]
`filterFormatted` will filter the each data base on the result of `dataFormat`, I think your code have some bug, maybe you can post a simple code and raw data that I can help you, thanks

**Comment by jaytiBansal** [comment]
@VladimZaguzin , How did you solve this? I am having same problem plus i dont get any data in select filter.
