### ISSUE TITLE
Override dataField and apply name attr to TableHeaderColumn

### ISSUE THREAD

**Issue by iredmedia** [AllenFang/react-bootstrap-table#1888]
Is it possible to apply a name to "TableHeaderColumn", potentially overriding dataField? I'd like to pass it an object to be rendered via dataFormat, and allow filter requests to use a different name than the object passed (dataField)

I'm using filtering (text input) and it's throwing it off, by giving it the dataField name instead of what I want it to say.

Any help is greatly appreciated!

**Comment by AllenFang** [comment]
@iredmedia sorry for lately reply, actually you can pass an object and use `dataFormat` to display the actual value on table, but in this case, you will lost the functionality on sorting and cellediting.

in you case, you may need to custom the filter,  how about add placeholder on text filter?

`filter={ { type: 'TextFilter', delay: 1000, placeholder: 'my name' } }`

**Comment by iredmedia** [comment]
In my case all I needed was to use the "row" data, to display something different than I was searching for (which in this case is status)

```
<TableHeaderColumn
  dataField="status"
  filter={ { type: 'TextFilter' } }
  dataFormat={(cell,row) => _statusFormatter(cell, row)}
  width={"100px"}>
  Status
</TableHeaderColumn>
```
