### ISSUE TITLE
Change position where modal is displayed during insert Row

### ISSUE THREAD

**Issue by narendravenkata** [AllenFang/react-bootstrap-table#1889]
I am using the table and trying to insert a row ,but the top portion of the table is not visible. I am trying to display it below the header in my application.

**Comment by AllenFang** [comment]
@narendravenkata sorry for lately, I think you can do something on the CSS, actually, `react-bootstrap-table` can't choose the position.  The insert modal in `react-bootstrap-table` is based on `react-modal` https://github.com/reactjs/react-modal
