### ISSUE TITLE
Does plugin support fully custom row markup?

### ISSUE THREAD

**Issue by wzup** [AllenFang/react-bootstrap-table#189]
It is a question, not an issue. Couldn't find where to ask, so ask here.

I need to customize a row markup. I need to preserve a row as a line, but I don't need columns in it, only custom markup. Something like the following, no columns, only `div`s inside the row, arbitrary styled and markup-ed:
```
-----------------------------------------------------------------------------------------
|   1   |   name: John    surname: Doe   age: 25    likes: JS       flag: green 
|       |            date: 20-12-2015       IP: 123.12.123.0        new: 1                          
----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
|   2   |   name: John    surname: Doe   age: 25    likes: JS       flag: green 
|       |            date: 20-12-2015       IP: 123.12.123.0        new: 1                          
----------------------------------------------------------------------------------------

```

Does the plugin provide this functionality?

**Comment by AllenFang** [comment]
@wzup, <code>react-bootstrap-table</code> doesn't support row customization, but your requirement is interesting, I think you can just give only two column(key and the other one), and use column format to design the second column by your expectation :)

**Comment by staminaloops** [comment]
Hello, this question is old, but yes, I've been doing like that and works great.

Just use the column with the key and another column with 

```
dataFormat
```
To customize the column. This callback function should return a String or a React Component.
In addition, this function taking two argument: cell and row.

If you need to search the formated unique column, use `filterFormatted` prop set to true **or** include the other columns `hidden`

I think we can close this :+1:

**Comment by AllenFang** [comment]
thanks @staminaloops
