### ISSUE TITLE
Rendering table columns as a single variable yields warning "Each child in an array or iterator should have a unique "key" prop"

### ISSUE THREAD

**Issue by Cvladianu** [AllenFang/react-bootstrap-table#1890]
I am writing a table component for an application which interacts with an API. Consequently, I decided to declare the columns display name and data fields like this :
![image](https://user-images.githubusercontent.com/25775252/35915452-df05cd72-0bfe-11e8-99da-d9445a244974.png)
 so that if the api changes, the changes to the component will be minimal.

I have 2 functions that create pieces of the table, one of which is the one returning the id column
![image](https://user-images.githubusercontent.com/25775252/35915497-0c333e60-0bff-11e8-8423-bec165e0b671.png)
However, if I return the columns as an array and simply display that, I get the warning in the title, that each child needs a unique key.
![image](https://user-images.githubusercontent.com/25775252/35915547-3521ef88-0bff-11e8-936f-541abbee7cf3.png)

This however does not appear if I declare all columns in render
e.g.
<BootstrapTable data={this.props.achievements}>
<TableHeaderColumn dataField='title' editable>Title </TableHeaderColumn>
<TableHeaderColumn isKey datafield='id" > ID </TableHeaderColumn>
</BootstrapTable> 
//just an example

Am I doing this the wrong way?

**Comment by Cvladianu** [comment]
Just to add something
If in function getTableIdCol, I add the parameter key={generic-react-key}, the warning disappears.

**Comment by AllenFang** [comment]
> If in function getTableIdCol, I add the parameter key={generic-react-key}, the warning disappears.
sure, because an return component of array need a key. but actually, I think `react-bootstrap-table` can just add a key on each element when rendering.
