### ISSUE TITLE
Using SelectRow Checkbox and ExpandableRow does not work together. 

### ISSUE THREAD

**Issue by Kawirider636** [AllenFang/react-bootstrap-table#1891]
I have the code below, selecting a checkbox works correctly, but clicking the + to expand the row does nothing. Am I doing something wrong or is this a bug? Thanks. 

If I remove selectRow={ selectRowProp }, the expand feature works fine. Looks like there might be some conflict? Checking a checkbox actually calls expandComponent(), but doesn't actually expand the component. 

```

const selectRowProp = {
        mode: 'checkbox',
        onSelect: this.selectOne.bind(this),
        onSelectAll: this.selectAll.bind(this)
};

const options = {
	expandRowBgColor: 'rgb(215, 244, 245)',
	expandBy: 'column'
};

<BootstrapTable  
	data={this.state.routes}
	height={ 500 }
	options={ options }
	expandableRow={this.expandableRow.bind(this)}
	expandComponent={this.expandComponent.bind(this)}
	expandColumnOptions={{
		expandColumnVisible: true,
		expandColumnComponent: this.expandColumnComponent.bind(this),
		columnWidth: 50
		}}
	selectRow={ selectRowProp }
>
```

**Comment by LuanSena** [comment]
do you have found some solution?

@AllenFang can you help me with this? I've the same issue.

**Comment by fabriciopirini** [comment]
I'm having the same issue using SelectRow Checkbox and/or CellEdit DBClick ... Did you guys find any solution for it? When I have both functionality, it works normally.
