### ISSUE TITLE
Is it possible to for row click to only trigger if non-text part of row is clicked?

### ISSUE THREAD

**Issue by minamesephy** [AllenFang/react-bootstrap-table#1897]
I'm using the react-bootstrap-table's expandComponent and isExpandableRow. 

Every row is expandable, but I would like the row only to expand if a non-text element of the row is clicked. For example, sometimes a user might want to select and copy the text in the row without expanding the row and unexpanding it when it is clicked. 

Is there any known solution for this?

**Comment by AllenFang** [comment]
@minamesephy good question here, it's hard to prevent actually, I'll suggest you to enable the expand indicator: https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/expand-indicator.js

Let me know your feedback, thanks

**Comment by minamesephy** [comment]
Can I see an example of what this should actually look like? For me I don't see any performance difference? I get an empty column but no behavioral differences? Also the extra column is just blank and doesn't have any kind of illustrations or anything.

**Comment by AllenFang** [comment]
https://allenfang.github.io/react-bootstrap-table/example.html#expand

**Comment by AlpacaGoesCrazy** [comment]
you should probably have a onClick function on your text elements:
```
(event) => {
  event.stopPropagation()
  /* do other stuff */
}
```
