### ISSUE TITLE
cannot able to check or uncheck the row dynamically 

### ISSUE THREAD

**Issue by sridharAJ** [AllenFang/react-bootstrap-table#19]
Hi i have an case, where i need to uncheck or check the row without doing it by click event. 

Means, there should be a function which can accept rowIndex and isSelected(boolean) as parameter and perform the above uncheck or check based on isSelected. 

please provide some function.

**Comment by AllenFang** [comment]
I've commit a newest code to <code>master</code> and you can clone to your local and run qsample as this gist : https://gist.github.com/AllenFang/e6440666329ac5b27a60.

Just like what tell you on hangout. It's hard for me to provide a instance or static function for user to call for set the row select or unselect.

So I use <code>componentWillReceiveProps</code> in <code>TableBody</code> and in these component which render <code>BootstrapTable</code> can change the selected rows on table through re-render by <code>selectRow</code> prop.

A simple explain is if you want to select some rows, you just set the <code>selected</code>attribute in <code>selectRow</code> prop and trigger render.

**Comment by AllenFang** [comment]
About the dynamic select or unselect feature, I've released on v0.9.5
