### ISSUE TITLE
UNMET DEPENDENCY and UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by wzup** [AllenFang/react-bootstrap-table#190]
Installing the package in a newly created app with empty `/node_modules` I have these warnings thrown:

```
$ npm install react-bootstrap-table --save
app@0.0.0 c:\Users\user\sbox\node\app
├── UNMET DEPENDENCY react@^0.14.3
└─┬ react-bootstrap-table@1.3.3
  ├── classnames@2.2.1
  ├── UNMET PEER DEPENDENCY fbjs@^0.3.1
  ├── UNMET PEER DEPENDENCY react@^0.14.0
  └─┬ react-toastr@2.2.4
    ├── UNMET PEER DEPENDENCY react@^0.14.3
    ├── react-addons-update@0.14.3
    └── react-dom@0.14.3

npm WARN EPEERINVALID react-bootstrap-table@1.3.3 requires a peer of react@^0.14.0 but none was installed.
npm WARN EPEERINVALID react-toastr@2.2.4 requires a peer of fbjs@^0.3.1 but none was installed.
npm WARN EPEERINVALID react-toastr@2.2.4 requires a peer of react@^0.14.0 but none was installed.
npm WARN EPEERINVALID react-dom@0.14.3 requires a peer of react@^0.14.3 but none was installed.
npm WARN EPEERINVALID react-addons-update@0.14.3 requires a peer of react@^0.14.3 but none was installed.
```

I understand that it means that there is no React and fbjs packages. 
*My first question is*: is there a way to force your package to install its dependencies automatically?

My second question.
I removed `react-bootstrap-table` and installed React and `fbjs` packages beforehand. `fbjs` was installed with this version:
```
"version": "0.5.1"
```
The warning says that `react-bootstrap-table` needs `fbjs@^0.3.1`. After re-installation of `react-bootstrap-table` it says that `fbjs@0.5.1` is not welcomed, it needs only `fbjs@^0.3.1`:
```
$ npm install react-bootstrap-table --save
app@0.0.0 c:\Users\user\sbox\node\app
└─┬ react-bootstrap-table@1.3.3
  └── UNMET PEER DEPENDENCY fbjs@^0.3.1

npm WARN EPEERINVALID react-toastr@2.2.4 requires a peer of fbjs@^0.3.1 but none was installed.
```
*So my second question is*: Will your package work with `fbjs@0.5.1`?

I installed `fbjs@^0.3.1` and eventually there were no any warnings. But what if my other packages will require `fbjs@0.5.1`? How may I install both versions of `fbjs`, one for your and one for others?

**Comment by staminaloops** [comment]
Hello, what node and npm version do you have?

**Comment by AllenFang** [comment]
maybe your npm version is too old. If not, try to 
```bash
$ rm -rf node_modules/
$ npm cache clean
```
and install again

**Comment by robwise** [comment]
I can confirm that it will complain unless you lock the version of `fbjs` down to `^0.3`

**Comment by staminaloops** [comment]
https://github.com/AllenFang/react-bootstrap-table/pull/194

**Comment by AllenFang** [comment]
thanks @staminaloops, check the newest version of <code>react-bootstrap-table</code>

**Comment by sranjithk** [comment]
@AllenFang Its worked for me, thank you.
