### ISSUE TITLE
weird space between header and body

### ISSUE THREAD

**Issue by ridonkz** [AllenFang/react-bootstrap-table#1901]
Hi @AllenFang , thanks for the library. This is very similar to this issue https://github.com/AllenFang/react-bootstrap-table/issues/883 so I believe the issue is with css.

I am using create-react-app so do not have my webpack.config.js to add use: [ 'style-loader', 'css-loader' ].

I am currently importing the css as follows:
import '../node_modules/react-bootstrap-table/dist/react-bootstrap-table.min.css'

Could you please help me with this?

**Comment by AllenFang** [comment]
@ridonkz I think it's not a bug and the css of `react-bootstrap-table` must not loaded successfully. Please check your code or webpack config. thanks

if the problem still there, please let me know. Actually, I also use `react-bootstrap-table` via `create-react-app` and it work fine.
