### ISSUE TITLE
Re-render React-Bootstrap Table Add/ Remove Column

### ISSUE THREAD

**Issue by paul-phillips-ark** [AllenFang/react-bootstrap-table#1910]
On my site there are 5 columns in my table. There is a function to hide and show columns. Let's say I hide two columns. The table looks fine. As soon as I show these columns again the table pushes these columns off the page. I want the table to refresh/ re-render when this happens so the user can clearly see all the columns. I cannot use JQuery for this purpose.

**Comment by juanpasolano** [comment]
What are you using to hide/show your columns? are you using the `hidden` prop?

**Comment by paul-phillips-ark** [comment]
This is solved now.  There is a prop hidden in the docs https://github.com/AllenFang/react-bootstrap-table/blob/master/src/BootstrapTable.js
That prop is printable. Simply putting in printable into my BootstrapTable component fixes issue. As far as I know, by default, it re-renders when I remove columns but will not re-render when they are added until printable is set to true. This should be in docs or be amended.
