### ISSUE TITLE
First Row Padding with condensed={true}

### ISSUE THREAD

**Issue by robwise** [AllenFang/react-bootstrap-table#192]
I have noticed an issue with the padding of the first row (after the header row, that is) of a table that has `condensed={true}`:

<img width="1280" alt="screen shot 2015-12-26 at 12 32 08 pm" src="https://cloud.githubusercontent.com/assets/6173488/12007321/d738d1c8-abcc-11e5-99d5-9a7c1e62fcff.png">

See how the `1` row has slightly less padding than the others? I think this is because its padding is overlapping with the header row (notice how the green padding goes above the header row bottom border):

<img width="361" alt="screen shot 2015-12-26 at 12 34 42 pm" src="https://cloud.githubusercontent.com/assets/6173488/12007323/1accfff4-abcd-11e5-818d-153d00c0e1fd.png">

**Comment by AllenFang** [comment]
Thanks for bug report, I've fixed this styling issue and will release it on next version.

**Comment by robwise** [comment]
@AllenFang :+1:   :+1:   :+1:

**Comment by AllenFang** [comment]
Released on <code>v1.4.0</code>
