### ISSUE TITLE
How to get columnIndex ?  

### ISSUE THREAD

**Issue by rullymartanto** [AllenFang/react-bootstrap-table#1932]
here my Child code...
How to get columnIndex ? so I can get correct record when click my button?
It wouldn't work when I move to page 2 (pagination)

Thanks

cellButton(cell, row, enumObject, rowIndex) {
   
        return (
            <div>
                <button type="button"  name="update" className="btn btn-success fas fa-edit" 
                    onClick={(e) => this.props.onClick(rowIndex, e)}> 
                </button>
                &nbsp;
                <button type="button" name="delete" className="btn btn-danger far fa-trash-alt"  
                onClick={e => this.props.onClick(rowIndex, e)}> <div className="ripple-container" ></div>
                </button>
            </div>
        )
    }

    render() {
        const options = {
            paginationPosition: 'top'
        };
        return (
            
            <div className="table-responsive">
                <BootstrapTable data={this.props.data} pagination options={options} table striped={true} hover={true} tableStyle={{ overflowY: 'scroll' }} height={String(Math.min([MAX_HEIGHT, (this.props.data.length + 1) * ROW_HEIGHT]))} >
                    <TableHeaderColumn width='25%' dataField='RoleName' ClassName="text-primary" isKey>Role Name</TableHeaderColumn>
                    <TableHeaderColumn width='60%' dataField='ListMenu' ClassName="text-primary">Akses Menu</TableHeaderColumn>
                    <TableHeaderColumn width='15%' dataField="button" columnClassName='td-actions text-right'  dataFormat={this.cellButton.bind(this)}></TableHeaderColumn>
                </BootstrapTable>
            </div>
        );
    }

**Comment by juanpasolano** [comment]
If you want a hold of the correct record, why don't you use the `row` attribute?
