### ISSUE TITLE
Peer react-bootstrap-table@1.3.3 wants react@^0.14.0

### ISSUE THREAD

**Issue by alfredoreduarte** [AllenFang/react-bootstrap-table#196]
The react-rails gem already uses react 0.14.3, so I can't use react-bootstrap-table along with it. https://github.com/reactjs/react-rails

Seems like we need a version bump for react here.

**Comment by AllenFang** [comment]
I will upgrade react.js to <code>0.14.3</code>, Thanks

**Comment by AllenFang** [comment]
Released on <code>v1.4.0</code>
