### ISSUE TITLE
Support images in table cell

### ISSUE THREAD

**Issue by reuvenf** [AllenFang/react-bootstrap-table#198]
Currently there is no way to insert an image into the cell.
Please add this functionality.
Thank you.

**Comment by reuvenf** [comment]
I found the way to do it by using dataFormat.

**Comment by nodox** [comment]
Can you elaborate for the rest of the community. I'm trying to do the same.

**Comment by jgtoriginal** [comment]
@nodox here you got an example on how to insert an image into a cell.

```
function imageFormatter(cell, row){
  return "<img src='"+cell+"'/>" ;
}
 
React.render(
  <BootstrapTable data={products} striped={true} hover={true}>
      <TableHeaderColumn dataField="name" dataSort={true}>Product Name</TableHeaderColumn>
      <TableHeaderColumn dataField="description" dataSort={true}>Product Description</TableHeaderColumn>
      <TableHeaderColumn dataField="image" dataFormat={imageFormatter}>Product Price</TableHeaderColumn>
  </BootstrapTable>,
    document.getElementById("app")
);
```

**Comment by foodaka** [comment]
```
    function imageFormatter(cell, row){
      return (<img style={{width:50}} src={cell}/>)
    }
```

**Comment by nikhilbhawsinka** [comment]
Hi, how to pass the src? unable to do <img style={{width: 12, height=12 }} src={row.logo}/>

The url to my image is in the "logo" datafield  of my table

**Comment by hwbell** [comment]
Echoing nikhilbhawsinka  - how to pass the src??? Please assist!

**Comment by reuvenf** [comment]
The information is in the code provided by @nodox. To clarify it more:
Object "products" should contain a field "image".
Field "image" is the image URL.

Then you specify 
`<BootstrapTable data={products} striped={true} hover={true}>`
That means populate each raw from the object "products".
Object "products should contain all the fields one per cell something like

`
var products = [
    {name: 'XYZ', description: "My image", image: "http://mydomain.com/a.jpg"}
];
`
In the following line
`<TableHeaderColumn dataField="image" dataFormat={imageFormatter}>Product Image</TableHeaderColumn>`

the cell will be populated from the specified field (dataField="image")  and passed to the "imageFormatter" function as a first parameter and raw will be passed as a second parameter.

Hope this helps.

**Comment by AllenFang** [comment]
thanks @reuvenf 👍

**Comment by kwekuboateng** [comment]
how do convert the image to base64 to be able to save in the database

**Comment by pgksunilkumar** [comment]
function imageFormatter(cell, row){
      return `<img src= ${cell} />`;
    }

**Comment by JohnVLinton** [comment]
Is there a way to pass in an onClick event to the img that changes State back in the parent table?

**Comment by venkatvenkataraman** [comment]
Does the imageFormatter function and procedure described above work with the new version, react-bootstrap-table-next? Understand that "TableHeaderColumn" is not supported in that version and it needs to be replaced by passing column data using the "columns" field inside the "BootstrapTable" tag.  I have the following snippet in my column data const definition:    
...
}, {
  dataField:'conditionsURL',
  text: "Conditions URL",
  formatter: imageFormatter
}];
However, what I see in the rendering of the table is the html text command - e.g., 

> <img src="http://icons...." alt="image"/> > 

 and not the image itself. Wondering if I am missing a trick here. Thanks for any help or pointers.

**Comment by jvlinton** [comment]
Working from memory so this will be rough, but you should be able to do something like this:

function imageFormatter(cell, row, rowIndex) {
return (<span><img src='pic.png'></span>)
}

-- or something LIKE that (my syntax might be a little off)

**Comment by venkatvenkataraman** [comment]
Thanks for your prompt reply, @jvlinton!  Currently my imageFormatter code looks like below (added "rowindex" as a parameter, based on your recommendation), but still  no luck - it displays the html text (which seems to be in the correct format without any extra quotes) but not the image.

function imageFormatter(cell, row, rowindex){
    const imageStmtForRender= '<img src="'+cell+'" alt="image"/>';
    return imageStmtForRender;
}

**Comment by venkatvenkataraman** [comment]
No idea why my "img" code statements in this post are getting converted to an image icon and if there is a way to get around that.

**Comment by jvlinton** [comment]
See this link:

https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Columns&selectedStory=Column%20Formatter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by venkatvenkataraman** [comment]
@jvlinton, Thanks for your patience. Is there an Image URL display example similar to the priceFormatter example?  I tried to structure the code similar to the example you sent (with a few extra lines to fit in the react environment I'm running in). The text from your example are in comments and my code snippets are right below.  It compiles fine but all I see is html text in the table, not an image.
import React, { Component } from "react";
import BootstrapTable from 'react-bootstrap-table-next';

// function priceFormatter(cell, row) {
//   if (row.onSale) {
//     return (
//       <span>
//         <strong style={ { color: 'red' } }>$ { cell } NTD(Sales!!)</strong>
//       </span>
//     );
//   }
// return (
//     <span>$ { cell } NTD</span>
//   );
// }

  function imageFormatter(cell, row){
    const imageStmtForRender= '<img src="'+cell+'" alt="image"/>';
    console.log("Image statement for rendering: ", imageStmtForRender);
    return imageStmtForRender;
  }

// const columns = [
// // omit...
// {
//   dataField: 'price',
//   text: 'Product Price',
//   formatter: priceFormatter
// }];

const columns = [{
    dataField:'conditionsURL',
    text: "Conditions URL",
    formatter: imageFormatter
  }];

const data = [{
    id: 1523404800,
    conditionsURL: "http://icons.wxug.com/i/c/k/clear.gif"
 }, {
    id: 1523664000,
    conditionsURL: "http://icons.wxug.com/i/c/k/chancetstorms.gif"
 }
]

class Weather extends Component {
        render() {
            return (

                    // <BootstrapTable
                    //   keyField="id"
                    //   data={ products }
                    //   columns={ columns }
                    // />

                    <BootstrapTable
                        keyField="id"
                        data={ data }
                        columns={ columns } 
                    />
            );
        }
  }

  export default Weather;

**Comment by venkatvenkataraman** [comment]
where you see the image icon in the code above, please replace by the html open and close tags.  

const imageStmtForRender= ' _html open tag_ img src="'+cell+'" alt="image"  _html close tag_'

**Comment by JohnVLinton** [comment]
I am not sure but would try to return a simple empty <span></span> then
build up from there.

My guess is your const is not supported by the formatter.

Nix that and try returning a return(<span></span) first.

Or if you need a variable input, test overloading the arguments with the
last one being whatever variable url you need.

John

**Comment by JohnVLinton** [comment]
don't use const

something like:

return (<span><img src={cell}></span>)

**Comment by JohnVLinton** [comment]
return (<span><img src={'yourlink'}></span>)

**Comment by venkatvenkataraman** [comment]
It turns out that I didn't need the span. The following does the trick for me. Thanks again for your pointers and patience, John!
  
function imageFormatter(cell, row){
    return (
       _html open tag_ img src={""+cell+""} alt=" " _html close tag_
    );
   }

   <BootstrapTable
   keyField="id"
   data={ data }
   columns={ columns } 
   />
