### ISSUE TITLE
Blur To Save- Tab key

### ISSUE THREAD

**Issue by arif25169** [AllenFang/react-bootstrap-table#1981]
Hi , when i enable `  blurToSave: true` , the tab key doesn't move to next cell.
But It works perfectly at   https://allenfang.github.io/react-bootstrap-table/example.html#celledit.

What am  I doing wrong there?

**Comment by vademyanchik** [comment]
Hi @arif25169!  Did you find a solution? I have the same problem

**Comment by nurhanna** [comment]
Hi @arif25169 ! I'm also facing the same issue, do you manage to solve it? Thanks

**Comment by KoGaYoung** [comment]
Maybe That problem caused by react-bootstrap-table key. change key to another value! i solve this problem this way.
