### ISSUE TITLE
extra wrapper div for tbl-header will help

### ISSUE THREAD

**Issue by ssjogus** [AllenFang/react-bootstrap-table#201]
Hi,

i am using your plugin, and have updated to the latest. My design requires a colored background (gradient) for header. The new new release of react-bootstrap-table, tbl-header is getting margin-right beautifully adjusted. But it also reducing the area of colored-backgroud, Please check attached screenshot.

![screen](https://cloud.githubusercontent.com/assets/8896732/12136003/570be7ce-b469-11e5-8591-371bdaf03755.png)

1. Can you wrap a tbl-header in other react-bs-header, so that background of the header can spread to 100 %.

2. another thing is about pagination holder div.  it will help if the last div has some class. if any style needs to be updated we need to do as '.react-bs-container > div:last-child'. so if this div has some class as 'footer' it will help.

3. one more question: Do column accept width in percentage? when i set column width in percentage, and select one row, the width is getting adjusted, so it seems there is some flickering issue..

thanks for all your help and this plugin

shruti.

**Comment by AllenFang** [comment]
@ssjogus, thanks your feedback

1. it's seems like a bug, I'll fix it.
2. I can add it
3. No, there's some problem that I can't solve it currently, the width of bootstrap table is a big hell

Hope the answer is you wanted

if any question, welcome to join the [gitter](https://gitter.im/AllenFang/react-bootstrap-table) to discuss with us.

**Comment by AllenFang** [comment]
@ssjogus, another question, how did you change the header style?

**Comment by ssjogus** [comment]
@AllenFang , i just gave some styling to this class '.tbl-header'..

i think .tbl-header is getting margin-right adjusted according to scrollbar. may be it will help (just a suggestion) if we wrap it in some other div '.bs-header-container', which will get no margin, but is 100% width, to which we can give the background, it can solve the problem..

thanks..

**Comment by AllenFang** [comment]
@ssjogus, yes you are right, the div of ```.table-header``` apply ```margin-right: 15px``` for the case which scrollbar exists. so you means use another div wrap ```.table-header```?

**Comment by ssjogus** [comment]
@AllenFang ,

yes, right.. may be something like:
```
<div class='table-header-holder'><div class='table-header'>...</div></div>
```
so it should background styles to .table.header-holder and apply margin-right to the .table-header

**Comment by AllenFang** [comment]
@ssjogus, good, that's what I consider, I'll try it after work. Thanks!

**Comment by AllenFang** [comment]
@ssjogus, Fix this issue.
First, I add ```.table-header-wrapper``` to wrap ```.table-header```
Second, apply ```.table-footer-pagination``` class name on div of pagination.

check the newest version

**Comment by ssjogus** [comment]
thanks..
