### ISSUE TITLE
Get all selected rows while using pagination

### ISSUE THREAD

**Issue by TonyVeigel** [AllenFang/react-bootstrap-table#203]
Is there a way to get all the selected rows while using pagination. I see there is a getTableData() but that is all that I see and doesn't work with pagination. I would like to get all the selected rows and send them off to the server. 

Thanks

**Comment by TonyVeigel** [comment]
I will just use this.refs.state.data.selectedRowKeys, does the job.

**Comment by AllenFang** [comment]
:+1:
