### ISSUE TITLE
Filter by custom field.

### ISSUE THREAD

**Issue by code-artisan** [AllenFang/react-bootstrap-table#204]
How can I filter the data by custom field, eg:

```js
// ...
<BootstrapTable data={ products } search={ true } striped={ true }>
        <TableHeaderColumn dataField="id" dataSort={ true } isKey={true}>Product ID</TableHeaderColumn>
        <TableHeaderColumn dataField="name" dataSort={ true } dataFormat={ nameFormatter }>Product Name</TableHeaderColumn>
        <TableHeaderColumn dataField="price" dataSort={ true } dataFormat={priceFormatter}>Product Price</TableHeaderColumn>
</BootstrapTable>
```

When I type the keywords, I want to filter by `name` field, How can I do this ? thanks...

**Comment by AllenFang** [comment]
@code-artisan, you means you want filter name field after formatting?

**Comment by code-artisan** [comment]
yes

**Comment by AllenFang** [comment]
@code-artisan, ok, it's certainly a enhancement for <code>react-bootstrap-table</code>, someone has been report this issues, I'll add this feature in the near future. But for now, the workaround is dont use <code>dataFormat</code>, just pre format by youself on your source data and then give source into table.

**Comment by AllenFang** [comment]
@code-artisan, if any questions, welcome to join the [gitter](https://gitter.im/AllenFang/react-bootstrap-table) to discuss with us :)

**Comment by code-artisan** [comment]
:100: And here:

![image](https://cloud.githubusercontent.com/assets/5195218/12164604/ea17dc9c-b551-11e5-8af0-5e52fc5973f4.png)

![image](https://cloud.githubusercontent.com/assets/5195218/12164610/f7974b96-b551-11e5-985d-02188cf5aad5.png)

can not find any data.

Trim the white space :smile:

**Comment by AllenFang** [comment]
yep, for now, I only match the condition with whole text

**Comment by code-artisan** [comment]
A ha, this is good product. Good job. :100:

**Comment by AllenFang** [comment]
Thanks @code-artisan :)

**Comment by AllenFang** [comment]
@code-artisan, released on newest version,

if you want to filter or search data after cell formatted, just give a ```filterFormatted={true}``` on ```TableHeaderColumn```.
