### ISSUE TITLE
Help with Build. No files being created in dist folder

### ISSUE THREAD

**Issue by Agilesolutionspk** [AllenFang/react-bootstrap-table#208]
I followed  this 
   $ git clone https://github.com/AllenFang/react-bootstrap-table.git
   $ cd react-bootstrap-table
   $ npm install
and then 
   $ gulp prod #for production

There was no error but no file was created in build. To be sure i deleted in precompiled file available in dist.  To troubleshoot further i tried to run webpack from command line. Here is what i got

c:\react-bootstrap-table>webpack --config webpack.production.config
Hash: 69a76034c360bd3f923a
Version: webpack 1.12.10
Time: 47ms
    + 1 hidden modules

ERROR in ./src/index.js
Module parse failed: c:\React\node_modules\react-bootstrap-table\src\index.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import BootstrapTable from './BootstrapTable';
| import TableHeaderColumn from './TableHeaderColumn';
| import {TableDataSet} from './store/TableDataStore';

I want to make some change to code but i cannot build it. I am new to js/node environment.  Any hint would be great help.  May be i am doing it wrong.

**Comment by AllenFang** [comment]
@Agilesolutionspk, if no error when run ```gulp prod``` for profuction, it's hard to find the root cause. I will try it on my windows env, and what's your node.js version?

**Comment by Agilesolutionspk** [comment]
Thank you for the quick reply.  I am using node 5.4.0

**Comment by AllenFang** [comment]
@Agilesolutionspk, I've tested on windows but got no error. your ```gulp``` is installed on global?

**Comment by AllenFang** [comment]
@Agilesolutionspk, I guess it's a ```gulp``` issues,

you can install gulp global then tun ```$ gulp prod``` again
or 
<pre>
$ cd node_modules\gulp\completion
$ bash
$ > gulp prod
</pre>

if any question, welcome to join the [gitter](https://gitter.im/AllenFang/react-bootstrap-table) to discuss with us.

**Comment by Agilesolutionspk** [comment]
@AllenFang I am using windows 10. Installed gulp local as well as global. Also tried via gulp\completion.  Somehow bash does not work at all.  Dist folder remains empty.  I guess it is better to switch to ubuntu for node related work.  Its nice working with you. Thank you.

**Comment by Agilesolutionspk** [comment]
@AllenFang    SOLVED:    Deleted everything node etc and then reinstalled.  Under node_modules\gulp\completion  i used powershell as bash does not work on windows. It is Great to be back on track :)

**Comment by AllenFang** [comment]
good :P
