### ISSUE TITLE
dataSort sorts data provided in data in-place rather than using a copy or some other heuristic

### ISSUE THREAD

**Issue by finkelm** [AllenFang/react-bootstrap-table#210]
As stated `dataSort=true` literally sorts the data provided in `data`. While this can be desirable sometimes, it seems this would break with desired component behaviour wherein daughter components do not tamper implicitly with data being provided by a parent. I would think that data passed into `data` should stay the same after a sort.

**Comment by AllenFang** [comment]
@finkelm, sorry for my pool english..., did you think I should not change the sorting order on data source? if a good example will be better to undestand :)

**Comment by finkelm** [comment]
For example, I provide a data array with: [{id: 4}, {id: 3}, {id: 2}, {id: 1}, {id: 0}] and provide it as an input to the table component. When I click to sort, the component actually changes the array to [{id: 0}, {id: 1}, {id: 2}, {id: 3}, {id: 4}]. The parent component's version of data has been changed!

**Comment by AllenFang** [comment]
@finkelm, ok I understand. Thanks :)

**Comment by AllenFang** [comment]
@finkelm, fixed it on ```v1.4.5```. check this out
