### ISSUE TITLE
Select All checkbox customization (Display any other icon instead of checkbox)

### ISSUE THREAD

**Issue by chiragmansata** [AllenFang/react-bootstrap-table#2125]
Hello,
Firstly to say its a great library to work with.
However I need help on displaying any other icon in pace of select all check box. (As shown in picture)
My requirement states that user shall be able to select the table rows, however there is max limitation of 8 rows only.  So basically I need the select feature of the table but don't need the SelectAll feature.

I am aware that using 'react-bs-select-all' class I can hide the SelectAll checkbox but doing this makes the table look incomplete as the Heading of one column shall remain blank then.

Therefore seeking your help. Thanks in advance.
![Issue](https://user-images.githubusercontent.com/57209879/95582816-cbf28300-0a58-11eb-814c-c9e823b9713e.PNG)

**Comment by julienmouraddotcom** [comment]
@chiragmansata you're probably looking for: `selectionHeaderRenderer`

Reference:
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowselectionheaderrenderer-function

Storybook:
https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Custom%20Selection&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by chiragmansata** [comment]
@julienmouraddotcom Yes, exactly looking for the same.
Thanks a lot for the reference.
