### ISSUE TITLE
import data from CSV file

### ISSUE THREAD

**Issue by liqili** [AllenFang/react-bootstrap-table#214]
Hi,
The functionality of exporting to CSV  is working fine,it's better if it can import data from CSV file.

**Comment by AllenFang** [comment]
thanks for feedback, I prefer to support remote data than import csv to table. there are a lots of things to do, so any PRs are welcome!

**Comment by liqili** [comment]
Hi AllenFang,
I find a problem when  exporting to CSV.The row end with a superfluous comma.

**Comment by AllenFang** [comment]
@liqili, thanks your bug report :) I've fixed it and will release in next version on thess days

**Comment by AllenFang** [comment]
@liqili, I've fix the bug for the row end with a superfluous comma in csv file, check the newest version. Thanks

**Comment by liqili** [comment]
Thanks AllenFang .The functionality works fine now.By the way,it's inefficient to record the item which is selected，especially in big data set.So I don't know whetcher it can give the index of the data set which is selected.

**Comment by AllenFang** [comment]
Thanks, btw
> it's inefficient to record the item which is selected

what's mean? you mean I record all row data which selected in internal?

**Comment by liqili** [comment]
Yes.I have to record the index by additionaI storage if I can't get the internal index when submitting to back-end.

**Comment by liqili** [comment]
I have found some issues about Table Search functionality.
1.The search key will match the hidden column.
2.I meet problems following the below steps.
a.SelectAll records
b.Search by some condition.Some records are filtered.
c.I still get all records including filtered records when submitting to backend .

**Comment by AllenFang** [comment]
@liqili, thanks issues report, could you please open another issues so that I can solved issues by each issues number

**Comment by dannysindra** [comment]
I also would like the 'import from csv' feature to be added, please

**Comment by dmk255** [comment]
I also second the import from csv feature request :)

**Comment by sinamics** [comment]
+1 for CSV import
