### ISSUE TITLE
Sorting not re-rendering data when dataFormat is being used

### ISSUE THREAD

**Issue by flipjs** [AllenFang/react-bootstrap-table#215]
When I add dataFormat on a specific column, lets say for example a date column to convert it to ISOstring. When I sort the data, the date column stays static. If I change the page using pagination, its still the same. If I remove the dataFormat, then everything works fine again.

Work around is to transform the data and not use dataFormat. But doing so, I lose the functionality of adding an event handler like onClick on the column. If I dont use dataFormat, is there any other way to attach an event handler on the column? Thanks.

**Comment by AllenFang** [comment]
@flipjs, <code>react-bootstrap-table</code> just sort data from source data, if you want to sort a column which formatted, I can add this feature in near future. so I thinks the support for sorting on formatted column is which you want?

**Comment by flipjs** [comment]
@AllenFang thanks for the quick reply. Actually sorting doesnt work when using dataFormat. The old data is still present on screen, but the real data behind it doesnt move at all when sorting. The issue here is, clicking on a column will get the wrong data/object.

Actually, sorting works on first click. Second, third and succeeding clicks on header, sorting stops working. Heres an example,  I have 30 items, with ID 1 to 30. Initial screen show 1 to 10. When I click on ID header, it will sort all the data correctly, and will show records from ID30 down to ID21. If I click on the ID header again, it will still sort, but columns with dataFormat get stuck on screen, and the real data behind it get stuck as well. See the 2 tablesbelow:

![table1](https://cloud.githubusercontent.com/assets/8011958/12392805/a7f649ca-bde9-11e5-9ba7-62d5d7794c62.png)

![table2](https://cloud.githubusercontent.com/assets/8011958/12392809/b1af4a48-bde9-11e5-8efd-00481eeeaa93.png)

On Table 1, it still show the correct rows and clicking on ip address with ID30, will console log the ID30 object.

On Table 2, sorting didnt work correctly. The topmost is now ID1, but the IP address column didnt move. Clicking on IP address with ID1 row, will still console.log the ID30 object.

**Comment by flipjs** [comment]
I think its the dataFormat that is causing the issue. I removed datasort on all columns, which I thought would solve my problem. But now, with pagination, its still the same. If I go to different page number, the one with dataFormat will not change at all.

So I guess I cannot use dataFormat for now. But I dont know how to add onClick anymore on a column without dataFormat. Is there any other way to add onClick functionality on column without using dataFormat?

**Comment by AllenFang** [comment]
@flipjs, for workaround, you can use row selection, 

```javascript

function onRowSelect(row, isSelected){
  // get your cell from row!!
}

var selectRowProp = {
  mode: "radio",
  hideSelectColumn: true,  // hide selection column.
  clickToSelect: true,  // you should enable clickToSelect, otherwise, you can't select column.
  onSelect: onRowSelect
};

export default class HideSelectionColumnTable extends React.Component{
  render(){
    return (
      <BootstrapTable data={products} selectRow={selectRowProp}>
          <TableHeaderColumn dataField="id" isKey={true}>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField="name">Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField="price">Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
};
```

**Comment by AllenFang** [comment]
Anyway, I'll spend some time to trace this problem :) Thanks your helping. 
If any questions, welcome to join the [gitter](https://gitter.im/AllenFang/react-bootstrap-table) to discuss with us :)

**Comment by AllenFang** [comment]
@flipjs, I thinks there are some case I need to confirm, so could you please give me some example codes(on gist)

About the add onClick, you want to click some columns and using the column which clicked to do some stuffs? if yes, your workaround is ```row selection```

```js
function onRowSelect(row, isSelected){
  // click row will trigger this callback function
  // you can get whole columns from row 
}

var selectRowProp = {
  mode: "radio",
  onSelect: onRowSelect,
  hideSelectColumn: true,  // hide selection column.
  clickToSelect: true  // you should enable clickToSelect, otherwise, you can't select column.
};

export default class DemoTable extends React.Component{
  render(){
    return (
      <BootstrapTable data={products} selectRow={selectRowProp}>
          <TableHeaderColumn dataField="id" isKey={true}>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField="name">Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField="price">Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
};
```

**Comment by AllenFang** [comment]
@flipjs, I just write a simple example with sort and dataformat as following, 
```js

function priceFormatter(cell, row){
  return '<i class="glyphicon glyphicon-usd"></i> ' + cell;
}

export default class SortTable extends React.Component{
  render(){
    return (
      <div>
        <BootstrapTable ref="table" data={products}>
            <TableHeaderColumn dataField="id" isKey={true} dataSort={true}>Product ID</TableHeaderColumn>
            <TableHeaderColumn dataField="name" dataSort={true}>Product Name</TableHeaderColumn>
            <TableHeaderColumn dataField="price" dataFormat={priceFormatter}>Product Price</TableHeaderColumn>
        </BootstrapTable>
      </div>
    );
  }
};
```
But I sort on all column with multiple times clicked, there's no any problem like your conditions.
so colud please give me your example code(on gist) or there's something I miss?

**Comment by flipjs** [comment]
Hi Allen, Thanks for your prompt action on this. Actually I have the code in my repo. Here it is:

https://github.com/flipjs/react-bootstrap-table

What I want is, even If I cannot format the data, is have some way to click on column, and get the cell (not row) data. Then I can add onClick event on that, send the cell as parameter. With onSelectRow, I dont know which cell was clicked.

Thanks.

**Comment by AllenFang** [comment]
@flipjs, thanks your examples, I'll check it out tomorrow, it's time to sleep :)

**Comment by flipjs** [comment]
No worries. Stay healthy. Thanks.

**Comment by AllenFang** [comment]
@flipjs, there are a lots of bug to fix, so maybe need more time ;( sorry

**Comment by flipjs** [comment]
No worries. Take your time. Thanks for looking into this.

**Comment by AllenFang** [comment]
@flipjs, I've find the problem and will fix in these days, thanks:)

**Comment by flipjs** [comment]
Cool! Thanks!

**Comment by tikotzky** [comment]
Hi, I'm experiencing this issue as well.
The issue seems to be triggered when you use `dataFormat` to return a custom component.

It seems like [`shouldComponentUpdate`](https://github.com/AllenFang/react-bootstrap-table/blob/ba9adabc848ceb0e1d9ce3833ee8ba8781c137e0/src/TableColumn.js#L10])in `TableColumn` is always returning false even when children of the custom component has been updated.

perhaps the `shouldUpdateComponent` method should be updated to always return true if the `dataFormat` prop is returning a custom component. This way the custom component can choose to implement their own `shouldUpdateComponent` if they choose.

**Comment by AllenFang** [comment]
@tikotzky, exactly. because on v1.4.2, I did some performance tuning on ```shouldComponentUpdate``` in ```TableColumn``` so that caused this bug. btw, if always return true, when user use ```dataFormat``` will reduce performance on a long table. But I've no idea to solve this problem so the workaround is just return true to fix this issue ;(

**Comment by flipjs** [comment]
I downgraded to 1.4.1 for now. Thank you both!

**Comment by tikotzky** [comment]
The custom component has the option to implement shouldUpdateCoponeny itself if it's worried about performance. 

Perhaps it should just be documented that if you use dataFormat you should make sure the component returned implements shouldUpdateComponent.

**Comment by AllenFang** [comment]
@tikotzky, cool, good idea!!, thanks a lots :)

**Comment by AllenFang** [comment]
release on ```v1.4.3``` :)

**Comment by flipjs** [comment]
Brilliant! Thanks @AllenFang @tikotzky !

**Comment by andest01** [comment]
when using `dataFormat`that returns a `select` element with `options` inside of it, sorting doesn't sort, and changes to state don't get reflected in the column.  Make sure that your `select` element also has a `defaultValue`, e.g. `<select defaultValue={myStatus} >`

Here's a video reproducing the problem.
https://www.dropbox.com/s/qndf7rxngo4pu64/SortAndStateUpdatesDontWork.mov?dl=0

I attempted to change the `shouldComponentUpdate` to always force returning `true`. This DID NOT fix the problem. I tried downgrading to 1.4.1 and that did not work.

This appears to still be an issue. I'm sorry that I can't be of much use right now due to a demo tomorrow - I love the stuff you've made and it's helped my team out a ton!

**Comment by AllenFang** [comment]
@andest01, thanks for issue reporting, could you please give your example code for me to debug?
Thanks :)

**Comment by MicroRAsus** [comment]
@AllenFang Have you implemented the sort on formatted data yet? Is there a way to trigger dataFormat handler function after sorting was triggered? I'm using dataFormat to convert epoch time column to readable format, and I also want to be able to sort the epoch time. Currently, I'm using bootstrap table 4.3.1, when the table renders, it does trigger the formatting, but when I click on sorting, the sorted table does not trigger the formatting.

**Comment by AdnanBoota** [comment]
Any possible solution for "react-bootstrap-table": "4.3.1", i'm using dataFormat, but unable to do dataSort???
![image](https://user-images.githubusercontent.com/14972616/54444966-2116c780-4744-11e9-9b74-40a31053a967.png)


Thanks.
