### ISSUE TITLE
Debug the original React files

### ISSUE THREAD

**Issue by dana2208** [AllenFang/react-bootstrap-table#217]
Hi,

Is there a way I can debug the original react files when developing my application that uses your grid?

Thansk

**Comment by AllenFang** [comment]
@dana2208, ok, I'll add this feature, but  I'm busy in recent, so need sometime to do it. If any PR is welcome :)

**Comment by AllenFang** [comment]
@dana2208, use webpack ```dev-tool: 'eval-source-map'``` to provide the source map, please check this out on newest version

**Comment by dana2208** [comment]
hello,
Thanks a lot for this! I am finally able to debug with the web developer tool.
However there is a weird behavior:
In the web developer tooI I set a breackpoint in the generated BootstrapTable.js but it doesn't get hit until I also set a breackpoint in my own jsx file, the one that renders BootstrapTable.
According to this [stackoverflow answer](http://stackoverflow.com/a/34247061/2334891), maybe you should add:
```
debug: true,
devtool: "#eval-source-map",
```
I guess you don't want to put this in your webpack for production so maybe you could write another webpack for development use only.

Thanks

**Comment by AllenFang** [comment]
> so maybe you could write another webpack for development use only

Just a little question,
you mean I can add ```debug:  true``` in my dev webpack for only development?
Thanks :)

**Comment by jochenberger** [comment]
If I understand https://webpack.github.io/docs/configuration.html#devtool correctly, the `*eval*` devtools should not be used for production. In any case, they cause issues if the resulting files are passed through a minifier. For example, I get: "RequireJS error: define: exports is not defined, modules react-bootstrap-table"
