### ISSUE TITLE
Setting default sort and then sorting first time always sort descending

### ISSUE THREAD

**Issue by dana2208** [AllenFang/react-bootstrap-table#219]
Hi,

I am setting a default sorting for my column this way:
`<BootstrapTable data={dataSet} striped={true} hover={true} condensed={true} options={sortName: "dispName", sortOrder: Const.SORT_DESC}>`
Then, first time I click on the column header of dispName, then the sorting is not changed to ascending but rather is still in descending order. I need to click again in order to get the table sorted ascendingly.
This is due to the fact that TableHeaderColumn uses a local variable (this.order) that is undefined at the beginning and only after the first click it is updated with the current sort order. Instead it should already be aware of the default sorting order.

Thanks

**Comment by AllenFang** [comment]
@dana2208, it seems like a bug after v1.4.2, because I fixed some sorting problem on this release, I'll check it out :) thanks your feedback

**Comment by AllenFang** [comment]
@dana2208, I've fixed this issues and will release on next version in these day :) 
Thanks :+1:

**Comment by AllenFang** [comment]
@dana2208, I've fixed this issues on ```v1.4.3``` :)
