### ISSUE TITLE
Column hidden problem

### ISSUE THREAD

**Issue by eric379990** [AllenFang/react-bootstrap-table#221]
Hi Allen, I have set one TableHeaderColumn to hidden with "hidden={true}", but when I use dataSet to add a new row to this table, the TableHeaderColumn is hidden, but the td area is still shown, can you help for this? thanks.

**Comment by AllenFang** [comment]
@eric379990, dataSet will no longer to support, I prefer users change to ```state``` for the data changing :) if problem still remain, please tell me, I will solve it
