### ISSUE TITLE
cellEdit in redux not working

### ISSUE THREAD

**Issue by WangFenjin** [AllenFang/react-bootstrap-table#222]
Hi,

I can't integrate react-bootstrap-table with redux when using cellEdit feature. The cell always turn to normal status after I click to edit the cell.

Could anyone help me? Thanks.

**Comment by AllenFang** [comment]
@WangFenjin, I'm not familiar with redux, but I guess cell edit and redux do not have any relation. so could you please show me you sample code?
Thanks :)

**Comment by WangFenjin** [comment]
Thanks Allen, I will close this issue for now, need to learn more about redux.

Sorry to bother.
