### ISSUE TITLE
Server-side pagination

### ISSUE THREAD

**Issue by Lightheaded** [AllenFang/react-bootstrap-table#224]
Hey! I was wondering if server-side pagination would be possible with react-bootstrap-table and how would one approach it?

I have potentialy tens of thousands of rows and several megabytes of data which results in unacceptable load times when pulling a single JSON.

**Comment by AllenFang** [comment]
@Lightheaded, you mean when page changing will fetch data from server?

**Comment by Lightheaded** [comment]
Yes, exactly that. So if I have 10,000 results, the server would return something like
```json
{
  "total": 10000,
  "offset": "30",
  "data" : [
    {...},
    {...}
  ]
}
```
or something along the lines. It's just that currently I have a really large JSON which causes slow loading times and also typing in the search box crashes when searching for such a large dataset.

**Comment by AllenFang** [comment]
@Lightheaded, sorry for late reply. it's seems like you need a remote data fetch provided in react-bootstrap-table. there's same [issues](https://github.com/AllenFang/react-bootstrap-table/issues/73) for this, but in my opion, I don't want to do this in near future.

But maybe you just need a custom function for pagination when user click page, you can fetch data at time, and this issues has been posted before [#76](https://github.com/AllenFang/react-bootstrap-table/issues/76)

So i prefer to provide the second one, but need some time, however, any PR is welcome :)

**Comment by Lightheaded** [comment]
Sorry but I will have to ditch this plugin in that case. I will see if I have time in the near future to help out here, but currently it doesn't fit a feasible use case in my opinion. The whole point of an interactive data table is to search something from a large dataset. If it cannot handle a large dataset, it kind of makes it a moot point.

Sorry about not being able to help at the moment, hope to see you still developing and hoping someone will volunteer :)

**Comment by AllenFang** [comment]
@Lightheaded, that ok, actually, there still some performance issue need to be improved, like search. Anyway, thanks your feedback :+1:

**Comment by AllenFang** [comment]
Support on ```remote``` data, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-paging.js)

**Comment by vijaykotha** [comment]
Hi AllenFang

So Cant we achieve server side pagination in this React Bootstrap Table?? and also I need to make some custom changes to the Export to CSV functionality. How i can achieve this. Please help me out

**Comment by AllenFang** [comment]
> So Cant we achieve server side pagination in this React Bootstrap Table??

sure, like I mention above

> I need to make some custom changes to the Export to CSV functionality.

what kind of customization?

**Comment by vijaykotha** [comment]
Like on ExportToCSV, the downloaded file contains some improper data(For huge numbers) and also I need to color the rows as per some conditions.

So is it possible or not possible to achieve server side pagination??

**Comment by AllenFang** [comment]
> So is it possible or not possible to achieve server side pagination??

it's possible, use `remote` mode on `BootstrapTable`

> Like on ExportToCSV, the downloaded file contains some improper data(For huge numbers) and also I need to color the rows as per some conditions.

for the customization, we only support you to skip some column for format some column. so i guess your requirement is little bit hard to achieve currently.
