### ISSUE TITLE
Duplicated header

### ISSUE THREAD

**Issue by ckiss** [AllenFang/react-bootstrap-table#225]
Hi guys. I have an issue here. I can see the header names twice followed by the actual rows. I'm running your example with Product Id, name and price. Did this happened to somebody else too? Thanks

**Comment by AllenFang** [comment]
@ckiss, remember to include the css of ```react-bootstrap-table```

**Comment by ckiss** [comment]
thanks @AllenFang that fixed it. sorry about this :)

**Comment by AllenFang** [comment]
welcome :+1:
