### ISSUE TITLE
Content column lines didn't align with the title column lines in IE

### ISSUE THREAD

**Issue by liqili** [AllenFang/react-bootstrap-table#227]
Hi,
I found that content column lines didn't align with the title column lines in IE11.

**Comment by NullDivision** [comment]
Also reproduced on Chrome with v1.4.3

**Comment by AllenFang** [comment]
@liqili and @NullDivision, did you assign width on any columns?

**Comment by NullDivision** [comment]
Tried that. No dice.

**Comment by AllenFang** [comment]
@NullDivision, can you help to dont set the width and test it again? and what version did you used?

**Comment by liqili** [comment]
Hi AllenFang,
I didn't set any width.

**Comment by AllenFang** [comment]
any horizontal bar in your table? I test it on IE 11.09600, it's fine

**Comment by anthonypaparella** [comment]
@AllenFang +1 was able to reproduce

on Chrome Version 47.0.2526.106 (64-bit)
using react-bootstrap-table.css

<BootstrapTable data={this.props.list} pagination={true} search={true}>
        <TableHeaderColumn isKey={true} dataSort={true} dataFormat={buildLink} dataField="po_id">PO ID</TableHeaderColumn>
        <TableHeaderColumn dataSort={true} dataField="po_number" hidden={true}>PO Number</TableHeaderColumn>
        <TableHeaderColumn dataSort={true} dataField="created_at">created_at</TableHeaderColumn>
        <TableHeaderColumn dataSort={true} dataField="fulfillment_status">fulfillment_status</TableHeaderColumn>
        <TableHeaderColumn dataSort={true} dataField="po_date">po_date</TableHeaderColumn>
        <TableHeaderColumn dataSort={true} dataField="vendor_name">vendor_name</TableHeaderColumn>
        <TableHeaderColumn dataSort={true} dataField="warehouse">warehouse</TableHeaderColumn
</BootstrapTable>

Width attribute seems to have no effect on column size for me either. Any Ideas?

**Comment by AllenFang** [comment]
I've planed to design a new bootstrap table to solve the width and align problem. need some time.

**Comment by jochenberger** [comment]
I've created a Fiddle to demonstrate the issue:https://jsfiddle.net/8huu795c/

**Comment by jochenberger** [comment]
I updated the fiddle so it works with Chrome. https://jsfiddle.net/8huu795c/1/
Btw, the column widths are fine in Chromium, but they are off in Firefox.

**Comment by jochenberger** [comment]
If I set `min-width` on the `th`s as well as `width` and `max-width`, the rows are aligned properly in Firefox.

**Comment by AllenFang** [comment]
@jochenberger, thanks your exmaple, I'll take care about this on my new plan :+1:

**Comment by AllenFang** [comment]
Dear all, ```v2.0.0``` has been released, you can check #331 for more detail explanation and I'll close this issues, if problem still remain, please tell me on #331 or open an issue
