### ISSUE TITLE
Please help about table row delete.

### ISSUE THREAD

**Issue by eric379990** [AllenFang/react-bootstrap-table#229]
Hi Allen,

I have create a table and there is a cell with a button in each row, I want to delete the whole row when I click the button. currently I splice the row from the table data array, and setState with the new data array to the table. The table's rows are updated, but the buttons seems not deleted correctly. e.g.
Before:
row1    del_button1
row2    del_button2
row3    del_button3

after pressing del_button1 the result is
row2    del_button1
row3    del_button2

btw: the button is added to each row by dataFormat={this._editButtonFormatter} in TableHeaderColumn

do you have some good suggestions to handle this?  thanks.

BR/Eric

**Comment by staminaloops** [comment]
Hello,
Can you give us some code example?

**Comment by AllenFang** [comment]
@eric379990, please upgrade to newest version to try again, if problem still remain, give error message or show me your codes
Thanks :)

**Comment by mrzou** [comment]
@eric379990 Hi, do you fix this problem? I encountered this problem now.

**Comment by AllenFang** [comment]
@mrzou, any example code and simple data for me to reproduce it?

**Comment by mrzou** [comment]
@AllenFang Thanks for your reply. This is my problem. I return input label to TableHeaderColumn component attributes dataFormat. And when i delete one row not last one, the table only delete last one. At the same time, the row deleted with input label value not change.now i fix it.
sorry my english is poor,but my original code is:
```
  return (
        <input
          className="form-control"
          onChange={(function(event){changeField(event, row, field)})}
          defaultValue={row[field]}
        />
   );
```
when i change defaultValue in input label attributes to value. It works.
Thanks again for your reply.

**Comment by AllenFang** [comment]
@mrzou, goood job :+1:
