### ISSUE TITLE
Sort order is reversed when passing 'options'

### ISSUE THREAD

**Issue by stephenrs** [AllenFang/react-bootstrap-table#23]
When passing sortName and sortOrder to set the initial sorting of a table, 'asc' sorts the table in descending order and 'desc' sorts in ascending order :)

I hope I'm not bothering you too much!

**Comment by AllenFang** [comment]
It's a mistake for me, I will fix it when I get off work today :)

**Comment by AllenFang** [comment]
This bug has been closed on v0.9.3
