### ISSUE TITLE
How to show select column BUT hide selectAll

### ISSUE THREAD

**Issue by vgoklani** [AllenFang/react-bootstrap-table#230]
Hi, is there a way to show the select column (with the checkboxes) but hide the selectAll button at the top?

Thanks!

**Comment by AllenFang** [comment]
@vgoklani, there's no way to do it. but I can add a class on selectAll checkbox for you to hide, how about that? 
Thanks:)

**Comment by vgoklani** [comment]
that should be perfect, thank you so much!

**Comment by eric379990** [comment]
@AllenFang  Hi Allen, also a question for the row edit, if enable the deleteRow={true}, is it possible to call my custom function when the delete button is clicked?

**Comment by AllenFang** [comment]
@eric379990, what's means for your custom function? you want a row deletion hook?

**Comment by eric379990** [comment]
@AllenFang I have 2 tables, user can select some items in the first table and add to the 2nd table, and also can delete some items in the 2nd table, the items needs to back to the 1st table. so I want to handle the item back actions in the onDelete function.

**Comment by AllenFang** [comment]
```js
function afterRowDelete(rowKeys) {
    // rowKeys is the rowkeys which you delete
}

var options = {
    afterDeleteRow: afterDeleteRow
}
//....
ReactDOM.render(
 <BootstrapTable data={products} options={options}>
.....
);

```

**Comment by eric379990** [comment]
Thanks Allen, this helped a lot!

**Comment by AllenFang** [comment]
@vgoklani, I've add the class ```react-bs-select-all``` on select all checkbox. please check this out
Thanks :)

**Comment by vgoklani** [comment]
Thanks @AllenFang for adding the react-bs-select-all class. Quick question - is there a way to dynamically set the "display: none" via React? I would prefer not to touch the .css/.less files if possible

**Comment by AllenFang** [comment]
@vgoklani, sure, just give it a ```style```

**Comment by vgoklani** [comment]
not following, how would I pass in the style to set display:none for the react-bs-select-all class from React? Thanks!

**Comment by AllenFang** [comment]
@vgoklani, I got the wrong consideration. sorry for that. In this situation, the only way is modify the css file

**Comment by vgoklani** [comment]
ok, thanks!

**Comment by yasaiki** [comment]
I am having a difficult time hiding all select with react-bs-select-all class. Anyone can help me on how to accomplish that in css? The selector is not picking up the css.

**Comment by chiragmansata** [comment]
Firstly a big shout out to the owners and maintainers of this library, it is indeed a great one.
**Secondly to answer @vgoklani :**   I too am having the same use case for conditional show hide of select all and below code works for me:
if (typeof (document.getElementsByClassName("react-bs-select-all")) !== 'undefined' && document.getElementsByClassName("react-bs-select-all").length > 0) {
            document.getElementsByClassName("react-bs-select-all")[0].setAttribute('style', `display:none`);
}
You can place it in your componentDidUpdate() method and based on the condition modify the display value to show ('') or Hide ('none')

@yasaiki : Below code shall work, just place it in your css (in case still not working then can try the above way aswell)
.react-bs-select-all{
    display: none;
}

Thanks.
