### ISSUE TITLE
Table sort and selectedRowKeys

### ISSUE THREAD

**Issue by TonyVeigel** [AllenFang/react-bootstrap-table#235]
When you sort the table it would be nice to have state.selectedRowKeys sorted just like the state of the table is.

**Comment by AllenFang** [comment]
@TonyVeigel, any consideration for this proposal?

**Comment by TonyVeigel** [comment]
I could certainly work on something if you think this should be the intended behavior.

**Comment by AllenFang** [comment]
I thinks this is not a main feature for this component currently, but if you really want this, the workaround is

you can add a ```onSortChange``` in ```options``` props, if sorting triggered, get the selectedRowKey from  state and sort it on your component. Maybe you can show me your scenario which I can help you :)

**Comment by TonyVeigel** [comment]
Thanks, I will try that out, or I can come up with another solution. My scenario is that I am not using the export that comes with the table and I am just exporting the keys. So if the user sorts the table and I grab state.selectedRowKeys and send them to the server, I would expect  state.selectedRowKey to be sorted just like state.data.

**Comment by AllenFang** [comment]
I understand, I think the solution in the previous is work for you. If any questions, we can discuss more or join [gitter](https://gitter.im/AllenFang/react-bootstrap-table) to discuss. So close this discussion :)

Cheers
