### ISSUE TITLE
React Bootstrap NavDropdown throwing error on click.

### ISSUE THREAD

**Issue by ArchanaKalidoss** [AllenFang/react-bootstrap-table#236]
Hi, 
I am using below versions of react and react-bootstrap but on click of "NavDropdown" I an getting the error "TypeError: _reactDom2.default is undefined" on the console. From the file react-bootstrap.inc.js from the below code

Dropdown.prototype.componentWillUpdate = function componentWillUpdate(nextProps) {
	    if (!nextProps.open && this.props.open) {
	      this._focusInDropdown = _domHelpersQueryContains2['default'](_reactDom2['default'].findDOMNode(this.refs.menu), _domHelpersActiveElement2['default'](document));
	    }
	  };

Versions I am using : react.inc.js - v0.13.3, react-bootstrap.inc.js - 0.27.3-0, 
react-dom.inc.js - v0.14.0. 

Kindly inform what is the issue.

**Comment by AllenFang** [comment]
@ArchanaKalidoss, is it belong to ```react-bootstrap```?, I think you posted this in wrong place, here is ```react-bootstrap-table```.

**Comment by ArchanaKalidoss** [comment]
Yes it belongs to react-bootstrap.
