### ISSUE TITLE
Customer sort function make data shift in Chrome 

### ISSUE THREAD

**Issue by MalumRuby** [AllenFang/react-bootstrap-table#238]
I used the Customer sort function to get sorted data from DB server.
The table is doing well in Firefox, but in Chrome the data will shift.
When I click the column to sort table, No.2, No.8 and No.14 row shift the data.
  No.2 > No.8 > No.14

Table 在排序過後第2筆資料會跳到第8筆, 第8筆會跳到第14筆, 第14筆會跳到第2筆
從第2筆之後每加6的row會跳動
而且在排序的狀況下按下Check也會造成資料跳動
只有在Chrome上遇到Firefox表現正常

範例CODE
[code.txt](https://github.com/AllenFang/react-bootstrap-table/files/106327/code.txt)

如果需要聯絡我: malum0929@hotmail.com

**Comment by AllenFang** [comment]
I'll check this out. Thanks issue report :+1:

**Comment by AllenFang** [comment]
@MalumRuby, I think your custom sort function is wrong. please make sure how to sort your data in javascript, this component follow the basic sorting method, take this [reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort)

Thanks, if any problems, feel free to discuss.

**Comment by MalumRuby** [comment]
Uh.. I just put the empty function, the data still shift in Chrome.
```
<TableHeaderColumn dataField="name" dataSort={true} sortFunc={()=>{}}>
    {"Name"}
</TableHeaderColumn>
```

**Comment by AllenFang** [comment]
which version of ```react-bootstrap-table``` and chrome you used

**Comment by AllenFang** [comment]
Anyway, I'll test the case of empty function.

**Comment by MalumRuby** [comment]
version 1.4.5

**Comment by MalumRuby** [comment]
BTW I'm using redux.

**Comment by AllenFang** [comment]
@MalumRuby, this component have no any relation with redux, however, I tried a empty sort function in chrome, but it's fine. so could you please give me a example code which can reproduce this issue. And what's the version of your chrome?

**Comment by MalumRuby** [comment]
Well, I fixed the problem.

I rewrote the handleSort function.
[code.txt](https://github.com/AllenFang/react-bootstrap-table/files/113392/code.txt)

My Chrome version: 48.0
