### ISSUE TITLE
Add button on search bar to clear input?

### ISSUE THREAD

**Issue by flipjs** [AllenFang/react-bootstrap-table#239]
Hi Allen,

Is it possible to clear the search bar like sending a callback when pressing a button? See image below:

![searchbar](https://cloud.githubusercontent.com/assets/8011958/12617158/47d0fa80-c506-11e5-911b-64c23fd90e4c.png)

You see, I have a global search on top, on my page view I actually have plenty of tables with local search on each table acting as filter. Is it possible to add a button on the searchbar (same with my global search on top), then pass a callback on the button to clear the search string? How do I do it?

Thanks.

**Comment by AllenFang** [comment]
@flipjs, I thinks I can support this feature or some solutions for you, but just a little question,
if clear the text in search bar, do you want the table search again(means clear the search condition)

**Comment by flipjs** [comment]
Yes Allen, thats correct. When I click clear, it will reset the search and show all data again. Thanks for the quick reply. You're a star!

**Comment by AllenFang** [comment]
Thanks, I'll find a best solution for you or add a feature in these day

**Comment by flipjs** [comment]
Cool! Probably an option like searchClear={true} on the BootstrapTable, which will add a bootstrap button group on the search input.

Looking forward to this. Many thanks!

**Comment by AllenFang** [comment]
it's idea for this case, but just another question, if I add this clear button with search input field, which means your user need click that button by themself, am I right?

**Comment by flipjs** [comment]
Hi Allen. That's correct. User has to click on the clear button. When the clear button was click, it will empty/clear the search input, and shows all data again on the table.

**Comment by AllenFang** [comment]
Great, I'll support this feature. Thanks

**Comment by flipjs** [comment]
Great! Thank you Allen!

**Comment by AllenFang** [comment]
check example [6eb548e](https://github.com/AllenFang/react-bootstrap-table/commit/6eb548e59d8b791dcbdd23e431f764b74d9f815b)
Supported on v1.4.6

**Comment by flipjs** [comment]
Excellent! Thank you @AllenFang !

**Comment by L5eoneill** [comment]
Should have clearSearchText option to support languages/i18n, or use of "X" instead of the word "Clear"
