### ISSUE TITLE
After insert row, the screen is still dimmed.  

### ISSUE THREAD

**Issue by eric379990** [AllenFang/react-bootstrap-table#240]
Hello, I am using "react-bootstrap-table": "1.4.1", I have enabled the insertRow, but I found when I finish the new row input and click the save button of the pop up modal, the row has been added, but the screen is still in dimmed state. I need to click the screen again to exit the dim state. I am using Chrome 47.0.2526.106 (64-bit). 

I found it is OK in your Demo web page, I don't know what should be the problem.
here is my code:

`
require('react-bootstrap-table-all.min.css');
var React = require('react');
var BS = require('react-bootstrap');
var Row = BS.Row;
var Col = BS.Col;
var Panel = require('react-bootstrap').Panel;
var Modal = require('react-bootstrap').Modal;
var Button = require('react-bootstrap').Button;
var BootstrapTable = require('react-bootstrap-table').BootstrapTable;
var TableHeaderColumn = require('react-bootstrap-table').TableHeaderColumn;
var api = require('task/api');

var defaultSettings = {};
var changedSettings = {};

var SettingPanel = React.createClass({
    getInitialState: function () {
        return {
            open: false,
            buttonLabel:'Extend',
            buttonStyle:'danger',
            data: []
        };
    },
    
    componentDidMount: function() {
        this._getSettings();
    },

    _getSettings(){
        api.getTestTypeData(this.props.testType, function(result) {
            if (result!=null) {
                this.setState({
                    data: result.testConfig
                });
                for(var i=0;i<result.testConfig.length;i++){
                    defaultSettings[result.testConfig[i].name] = result.testConfig[i].value;
                }
            }
        }.bind(this));
    },

    _settingExpend(){
        if(this.state.open){
            this.setState({
                open:false,
                buttonStyle:'danger',
                buttonLabel:'Extend'
            });
        }else{
            this.setState({
                open:true,
                buttonStyle:'success',
                buttonLabel:'Collapse'
            });
        }
    },

    _onAfterSaveCell(row, cellName, cellValue){
        if(defaultSettings[row.name]!=row.value){
            changedSettings[row.name] = row.value;
        }else{
            delete changedSettings[row.name];
        }
    },

    _afterInsertSetting(rowKeys){
        console.log(rowKeys);
    },

    render: function() {
        return (
        <div>
            <Col md={6}>
                <Panel header={this.props.name} collapsible expanded={this.state.open}>
                    <BootstrapTable data={this.state.data} insertRow={true} deleteRow={true} 
                            selectRow={{mode: "radio", clickToSelect: true}} options={{afterInsertRow:this._afterInsertSetting}} 
                            cellEdit={{mode: "click", blurToSave: true, afterSaveCell: this._onAfterSaveCell}}>
                        <TableHeaderColumn dataField="name" dataAlign='center' isKey={true} >Key</TableHeaderColumn>
                        <TableHeaderColumn dataField="value" dataAlign='center' >Value</TableHeaderColumn>
                    </BootstrapTable>
                </Panel>
            </Col>
            <Col md={3}>
                <Button style={{marginTop: '5px'}} bsSize="small" bsStyle={this.state.buttonStyle} onClick={this._settingExpend}>{this.state.buttonLabel}</Button>
            </Col>
        </div>
        );
    }

});
module.exports = SettingPanel;
`

**Comment by AllenFang** [comment]
@eric379990, thanks issues report, I'll check this out

**Comment by matthewpolkiewiczsc** [comment]
I'm also seeing this problem when using bootstrap 3.3.6 Javascript + CSS. I don't see it when I used version 3.3.2 (like your examples).

**Comment by AllenFang** [comment]
ok, @eric379990, what's version of bootstrap you used?

**Comment by Dodeo** [comment]
Same for me with 3.3.6 bootstrap version.

**Comment by eric379990** [comment]
Hi Allen, I am using Bootstrap v3.3.5, sorry for late reply due to in Spring festival holiday. @AllenFang

**Comment by AllenFang** [comment]
@eric379990 ok

**Comment by AllenFang** [comment]
@eric379990, sorry for a long time to fix it, I've fixed and released on v1.5.3

**Comment by eric379990** [comment]
@AllenFang Thanks a lot Allen!
