### ISSUE TITLE
Search Bootstrap classes

### ISSUE THREAD

**Issue by informa** [AllenFang/react-bootstrap-table#241]
If you add search <BootstrapTable search> how do you change the markup or bootstrap column classes around the search input ie col-sm-6.

Is this possible?

**Comment by AllenFang** [comment]
could you explain this more detail? if user enable search, I just render a div on toolbar, and all the styles is fixed, I dont do any changing on markup, you can see the ```src/TableBody.js```.

Anyway, do you have any customization issues?

**Comment by informa** [comment]
Just a styling query really.
Yeah I just wanted to know if it is possible to change the markup on the toobar. Specifically the bootstrap grid classes around the search input. No big deal -- I can just override styles.  Thanks for replying.

```html
<div class="tool-bar" data-reactid=".0.0.0.0.0.1.4.0">
        <div class="row" data-reactid=".0.0.0.0.0.1.4.0.0">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-8" data-reactid=".0.0.0.0.0.1.4.0.0.0">
            <div class="btn-group btn-group-sm" role="group" data-reactid=".0.0.0.0.0.1.4.0.0.0.0">
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4" data-reactid=".0.0.0.0.0.1.4.0.0.1">
            <div class="form-group form-group-sm" data-reactid=".0.0.0.0.0.1.4.0.0.1.0">
              <input class="form-control" type="text" placeholder="Type here to filter the list" data-reactid=".0.0.0.0.0.1.4.0.0.1.0.0">
            </div>
          </div>
          <div id="toast-container" class="toast-top-right" aria-live="polite" role="alert" data-reactid=".0.0.0.0.0.1.4.0.0.2">
          </div>
        </div>
      </div>
```

**Comment by AllenFang** [comment]
ok, if you think there are some bad css class on markdown or anything you think it can be tuned, feel free to open PR :)
