### ISSUE TITLE
Warnings when using this component

### ISSUE THREAD

**Issue by urahonky** [AllenFang/react-bootstrap-table#25]
Hello!

This component has saved me a ton of time. I just wanted to let you know that I'm getting two new warnings since importing your latest code:

Warning: Failed propType: Invalid prop `data` of type `object` supplied to `BootstrapTable`, expected `array`. Check the render method of `app`.

and

Warning: Don't set .props.clearSortCaret of the React component. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. The element was created by app.

The first one occurred when I switched to using data sets (to be reactive with the data changes) from an Array of data.

Not a big deal just wanted to make sure you were aware! Thanks again!

**Comment by AllenFang** [comment]
Hi @urahonky , I known these warning and I will use some time to improve it. Anyway, I'm glad that you use <code>react-bootstrap-table</code> and give me some suggestion :)

**Comment by AllenFang** [comment]
fix it on v0.9.13 :)

**Comment by Ajitprakash** [comment]
I am facing Same issue v ^4.3.1. any clue.
