### ISSUE TITLE
Doubleclick event handler support

### ISSUE THREAD

**Issue by bbodi** [AllenFang/react-bootstrap-table#250]
First, thanks for your work and for this library!

The default "insert new row" feature is nice, but in many situations, it is better to allow the programmer to handle this in a specific way. For this, it would be useful if the programmer could provide an event handler for double clicking on a row.

**Comment by AllenFang** [comment]
@bbodi, I thinks there are two issues, 


> The default "insert new row" feature is nice, but in many situations, it is better to allow the programmer to handle this in a specific way

there are some way to insert new row data, first is just add new row into your state of table data, second is you can call the ```handleAddRow``` which exposed by ```BootstrapTable```, you can check the [docs](http://allenfang.github.io/react-bootstrap-table/docs.html#the-attributes-in-tableheadercolumn)

> For this, it would be useful if the programmer could provide an event handler for double clicking on a row.

there's no way to handle double click on row, maybe I'll add it in near future :)

**Comment by willdevelops** [comment]
+1  - Was looking for a way to attach an onDoubleClick to the table row element so that I can invoke another function off of it when a user double clicks.   Are there any plans to add this functionality?

**Comment by AllenFang** [comment]
I'll try to survey how to implement it. Sorry for lately fixing

**Comment by AllenFang** [comment]
Released on ```v2.5.6```. Thanks :0
