### ISSUE TITLE
scroll bars

### ISSUE THREAD

**Issue by jmc420** [AllenFang/react-bootstrap-table#254]
Hi

I noticed an issue with the scroll bars.

The markup generated by react-bootstrap-table looks like this:

<div class="react-bs-container">
 <div class="react-bs-table-container" style="height:100%">
  <div class="table-header-wrapper">
 <div class="table-container" style="height:100%">

the css rule table-container has overflow:auto which should switch on the scroll bars when the table overflows. 

However this does not work because there is no height defined for react-bs-container:

http://stackoverflow.com/questions/17295219/overflow-scroll-css-is-not-working-in-the-div

The scroll bar does appear if one defines a css rule for react-bs-container like this:

.react-bs-container {
  height:100%;
}

However the height of the scroll bar is wrong because table-container has a height of 100% - if it is reduced to 90% then it is about correct.

Can you add a height to react-bs-container and adjust the height of table-container?

James

**Comment by AllenFang** [comment]
@jmc420, thanks this issue report, it's a enhancement got height of table, however, I've planed to design the new DOM structure of ```react-bootstrap-table```, so I think this issue will be solved in that patch :+1:

**Comment by AllenFang** [comment]
@DexterHaslem, sorry for a long time to wait, I've solve all the issues about unalign and table in tabs problem. Currently, I'm test the capability on different browser currently, I am sure it will be released in these day.  sorry

**Comment by AllenFang** [comment]
Dear all, ```v2.0.0``` has been released, you can check #331 for more detail explanation and I'll close this issues, if problem still remain, please tell me on #331 or open an issue

**Comment by jmc420** [comment]
I recently upgraded from version 1.4.6 to version 2.5.6 and I cannot get vertical scroll bars added.

In version 1.4.6 the DOM structure was

<div class="react-bs-container">
 <div class="react-bs-table-container" style="height:100%;">
  <div class="table-header-wrapper">
  <div class="table-header">
  <div class="table-container" style="height:100%;">

 I added these css rules to make scrolling work:

.react-bs-table-container {
  height:100% !important;
}

.react-bs-table-container .table-container {
  height:90% !important;
}

In version 2.5.6 the DOM structure has changed to:

<div class="react-bs-table-container">
 <div class="react-bs-table" style="height: 100%;">
  <div class="react-bs-container-header table-header-wrapper">
  <div class="react-bs-container-body" style="height: 100%;">
   <table>
    <thead>
    <tbody>

I have not been able to get scrolling to work. Is there something else I need to do to get it to work?

James

**Comment by dk4210** [comment]
This solved it for me

.react-bs-table-container {
    height:100%;
    }
    
.react-bs-container-body {
    max-height: 230px;
    overflow-y: scroll;
}
