### ISSUE TITLE
Pagination doesn't work in IE9

### ISSUE THREAD

**Issue by kolyabokov** [AllenFang/react-bootstrap-table#255]
In IE9 (emulated via Dev tollbar of IE11) if you click any pagination link - all available page numbers will disapear and the table will show "There is no data to display" message. 
This can be reproduced at example page http://allenfang.github.io/react-bootstrap-table/

**Comment by AllenFang** [comment]
@kolyabokov, I'll check this out. And what's version did you used?

**Comment by kolyabokov** [comment]
@AllenFang, the latest version, 1.4.6

**Comment by AllenFang** [comment]
ok, thanks :)

**Comment by kolyabokov** [comment]
@AllenFang, hi. Any chance that it would be fixed soon?

**Comment by AllenFang** [comment]
@kolyabokov, wow, sorry, I almost forgot this issue and I will solve it in these day. SORRY again!

**Comment by AllenFang** [comment]
@kolyabokov, I found the problem and fixed it,  will release in this week. sorry

**Comment by kolyabokov** [comment]
@AllenFang, great, thanks!

**Comment by AllenFang** [comment]
@kolyabokov, I've fixed it and released on v1.6.2. You can try it :)

**Comment by kolyabokov** [comment]
@AllenFang it works now, thanks!)
