### ISSUE TITLE
How to style the delete button?

### ISSUE THREAD

**Issue by vgoklani** [AllenFang/react-bootstrap-table#257]
I need to change both the location and the color of the delete button, is there a simple way of doing that? 

Thanks!

**Comment by AllenFang** [comment]
@vgoklani, if I give some class or id on delete button is helpful to you? if ok, I can add it after my vacation :)

**Comment by AllenFang** [comment]
@vgoklani, I've add a classname on delete button, so I think you can customize it. but change location is hard to do, so if you want to another style delete button, I suggest you dont enable ```deleteRow``` and customize one by yourself and call exposed function: ```handleDropRow``` to delete row
