### ISSUE TITLE
Any ideas on performance optimization please?

### ISSUE THREAD

**Issue by opensourcegeek** [AllenFang/react-bootstrap-table#258]
I'm testing with 5000 items in the table, I can show it fine when I enable pagination however searching makes the browser hang. Do you have any ideas on how to optimize please? I'm already using redux for maintaining state by the way and I'm not sure if I can use immutable js with react-bootstrap-table.

**Comment by vgoklani** [comment]
same issue here :)

**Comment by opensourcegeek** [comment]
I'm wondering if I could just use keys in search(possibly making it quicker?). In my implementation my keys are already unique referring to an object passed into table. All my fields are combined with a separator to create this key. If I can just search the keys field, it will be enough I think(?). 

So for example if my key is ABC$DEF$GHI$1.2.3.4$00:01:02:03, and if the user is searching for "GHI ABC" which is a mult column search, I just need to get all the keys (5000 of them in my data set) and check if GHI or ABC is in the key, if it does then I can use the key to pick data from store. Not sure if this will be any quicker but I'd probably give this logic a go later on and see how it works out.

**Comment by AllenFang** [comment]
For a quick response, 
there are some absolutely performance issue on there, I'll spend some time to solve it after my vacation, but need some time, there are a lot of things to do..  sorry

and ```react-bootstrap-table``` can't just search key only, it's a fully text searching.
if you encounter a performance issues of search, I suggest you don't use embedded search.
because search will be trigger when ```keyup```, so it's a big problem in there if you have a huge data.

Feel free to discuss :)

**Comment by pirate** [comment]
You might already have tried this, but one trick to prevent lag when typing in the search field is to add a 500ms delay from last `keyUp` before actually executing the search.

<img width="331" alt="screen shot 2016-02-10 at 12 45 58 am" src="https://cloud.githubusercontent.com/assets/511499/12939640/ace01ca6-cf8f-11e5-888e-76f47053ad27.PNG">
```javascript
$('#myform .search input').on('keyup', function() {
    $('#myform .fa-spin').show();  // show loading spinner

    // wait 500ms sec after last keyup before searching 
    if (window.keyup_timeout) clearTimeout(window.keyup_timeout);
    window.keyup_timeout = setTimeout(performSearch, 500);
});
```
(please excuse me using jQuery, I copied this from an old project)

The spinner icon is a nice touch so the user doesn't think the form is just laggy in accepting search input.

**Comment by staminaloops** [comment]
Yes @pirate something like debounce https://github.com/lodash/lodash/blob/4.3.0/lodash.js#L8577 will improv performance I think.

**Comment by opensourcegeek** [comment]
@pirate @staminaloops I don't think the search worked any better after debouncing too. It still hangs after few the debounce timeout. I think 5000 items is too much for the table to handle. But I think I could probably customize search for my use case and see if that works any better.

**Comment by opensourcegeek** [comment]
Wow - just changing the inner loop in search function from using `for (var key in row)` to using `Object.keys()` has significantly improved performance. I'll do some more tests tomorrow. If it works fine I can send a PR?

**Comment by AllenFang** [comment]
Feel free to open it. btw, the most important tuning point is on ```shouldComponentUpdate```. hope your solution can improve some performance

**Comment by opensourcegeek** [comment]
I really haven't looked into shouldComponentUpdate, it seems like even having 5000 items in a paginated table loads fine even on mobile. That's probably because not all 5000 items are not added to DOM in a paginated table at the same time. The only issue I had was with search function which is essential for me, and that seems to spend a lot of time just in that inner loop I was referring to. I'm only fixing that for the moment.

**Comment by AllenFang** [comment]
Actually, there're some performance issue like row selection, cell editing, filtering in big table. I think the root cause is on the ```shouldComponentUpdate``` of ```src/TableRow.js``` and ```src/TableColumn.js```. After I finished my new plan for tuning table structure, I'll start to tackle this issue:)
Thanks

**Comment by opensourcegeek** [comment]
I don't do editing at the minute so I don't have any issues. I would like to do similar thing with lists/table using material-ui components if I get some time...!
