### ISSUE TITLE
Global Table Search doesn't work properly in presence of null

### ISSUE THREAD

**Issue by psibi** [AllenFang/react-bootstrap-table#259]
Throws the following error in console:

```js
TypeError: children is null
	

var trCss = {
```

**Comment by AllenFang** [comment]
could you please give me a correct example, thanks. I'll check it out after my vacation

**Comment by AllenFang** [comment]
this condition is seems like #260. will be solved in these day

**Comment by psibi** [comment]
Sorry, been quite busy. I will give you an example tomorrow. But I think issue 260 is different. In my example, some of the data in the table had `null` in it and that caused the problem. Replacing `null` value with an empty string solved the issue temporarily for me.

And yes, enjoy the vacation!

**Comment by psibi** [comment]
CC: @AllenFang 

This slightly modified demo code reproduces the problem:

``` javascript
var products = [{
      id: 1,
      name: "Item name 1",
      price: 100
  },{
      id: 2,
      name: "Item name 2",
      price: null
  }];

React.render(
  <BootstrapTable data={products} striped={true} hover={true} search={true}>
      <TableHeaderColumn dataField="id" isKey={true} dataAlign="center" dataSort={true}>Product ID</TableHeaderColumn>
      <TableHeaderColumn dataField="name" dataSort={true}>Product Name</TableHeaderColumn>
      <TableHeaderColumn dataField="price" dataFormat={priceFormatter}>Product Price</TableHeaderColumn>
  </BootstrapTable>,
    document.getElementById("app")
);
```

Note that one of the `price` value is `null` and I have enabled searching using `search={true}`.

**Comment by AllenFang** [comment]
@psibi, great!!!

**Comment by AllenFang** [comment]
btw, what version of ```react-bootstrap-table``` did you used?

**Comment by psibi** [comment]
Version: 1.5.0
By the way, I'm able to repeat this even without search={true} parameter. Just having `null` value triggers this for me.

**Comment by AllenFang** [comment]
```react``` version is ? because I cant reproduce this issues by your case on ```1.5.0``` and ```react@0.14.6```

**Comment by psibi** [comment]
I have the same react version `0.14.6`. Not sure why then it is happening to me. Probably, will update it to `0.14.7` and see.

**Comment by AllenFang** [comment]
so the ```TypeError: children is null``` is the error message ?

**Comment by AllenFang** [comment]
@psibi, could you try again with ```v1.5.1```?

**Comment by psibi** [comment]
Thanks this is fixed in `v1.5.2`. Was there anything specific you did ?

**Comment by AllenFang** [comment]
@psibi, the reason of problem is same as #260, so just follow up the fixing of #260

**Comment by psibi** [comment]
Thanks!
