### ISSUE TITLE
On state change: Uncaught TypeError: Cannot read property 'props' of null

### ISSUE THREAD

**Issue by pirate** [AllenFang/react-bootstrap-table#260]
Whenever I search my table (or update its state in any way), I get this error, and the table breaks.

`Uncaught TypeError: Cannot read property 'props' of null` on line `48` on on `TableColumn`'s `children`.

<img width="655" alt="screen shot 2016-02-09 at 2 29 15 pm" src="https://cloud.githubusercontent.com/assets/511499/12928100/a50bbac2-cf39-11e5-9512-08b6ef70d9f6.PNG">
Chrome dev console breakpoint set on line 48, showing the value of `children` immediately before the error.
<img width="668" alt="screen shot 2016-02-09 at 2 28 50 pm" src="https://cloud.githubusercontent.com/assets/511499/12928097/a0cd42fa-cf39-11e5-842b-d53c453336d8.PNG">

Fo some reason the if statement on line `47` seems to think `typeof "251" === "object"`, and it immediately errors on the next line when it tries to call `"251".props`, which of course doesn't exist since `"251"` is a string.  I've tried checking the type in console as well `typeof children >> "string"`, I'm stumped.  Any ideas?

----

**Code to reproduce:**
```javascript

export class CustomSortTable extends React.Component {
    render() {
        var {items, fields} = this.props;
        return <BootstrapTable data={items} search={true}>
            {fields.map((field, idx) => 
                <TableHeaderColumn
                    dataField={field.id}
                    dataSort={true}
                    key={field.id}
                    isKey={field.isKey || false}>
                    {field.name}
                </TableHeaderColumn>)}
        </BootstrapTable>
    }
};

var fields = [
    {id: 'id', name: 'ID', 'isKey': true},
    {id: 'my_value', name: 'My Value'},
]

var items = [{
     'id': '251',
     'my_value': true,
}, ...]

<CustomSortTable items={items} fields={fields}/>
```

**Comment by AllenFang** [comment]
Thanks for bug report, I'll check this out after my vacation, need some time :)

**Comment by pirate** [comment]
新年快乐！Enjoy your vacation  :), no rush.

**Comment by AllenFang** [comment]
happy new year :)

**Comment by AllenFang** [comment]
@pirate, which version of ```react-bootstrap-table``` did you used? and are you sure the code will produce the error? because I can't reproduce this followed by your example code

**Comment by pirate** [comment]
react-bootstrap-table `1.5.0`, react `0.14.6`.  I'll try a few things, and if they don't work I'll see if I can write some more reproducible code than this snippet.

**Comment by AllenFang** [comment]
@pirate, I've published ```v1.5.1``` and you can try it again :)

**Comment by pirate** [comment]
Appears to be fixed, thanks!

**Comment by AllenFang** [comment]
@pirate, Thank you. I am very grateful. I've no idea about accepting any donations:) Actually, I need more contributor to help this project become better :)
Thanks :+1:
