### ISSUE TITLE
Custom header cells

### ISSUE THREAD

**Issue by jochenberger** [AllenFang/react-bootstrap-table#266]
I'd like to be able to customize the `th` elements, for example, I'd like to render custom data attributes depending on the column and the sorting state, e.g. 
```html
<th data-property-name="name" data-column-sort="ascending">
  <a href="#" onClick={this.sortByName.bind(this)}>
    Name
  </a>
</th>
```

**Comment by staminaloops** [comment]
Hello,

This works for me, although I dont know if its meant to be used like this (never have thought about until now):

```javascript
import React from 'react';
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';


var products = [];

function addProducts(quantity) {
  var startId = products.length;
  for (var i = 0; i < quantity; i++) {
    var id = startId + i;
    products.push({
      id: id,
      name: "Item name " + id,
      price: 2100 + i
    });
  }
}

addProducts(5);

export default class Example extends React.Component{
  renderCustomHeader() {
    return(
      <p onClick={() => console.log('clicked!')}>Custom header</p>
    );
  }

  render(){
    return (
      <div>
        <BootstrapTable data={products}>
            <TableHeaderColumn dataField="id" isKey={true}>
              {this.renderCustomHeader()}
            </TableHeaderColumn>
            <TableHeaderColumn dataField="name">Product Name</TableHeaderColumn>
            <TableHeaderColumn dataField="price">Product Price</TableHeaderColumn>
        </BootstrapTable>
      </div>
    );
  }
};
```

**Comment by jochenberger** [comment]
Thanks, that will help me customize the content of the `th` element, but not its attributes. And I don't know the column's sorting state - I'd like to render `data-column-sort="sortable|ascending|descending"`.

**Comment by AllenFang** [comment]
@jochenberger, the solution as following, use ```react-dom``` to find the ```ref``` which you defined
```js
export default class TrClassStringTable extends React.Component{

  componentDidMount() {
    ReactDOM.findDOMNode(this.refs.name).setAttribute('data-attr-custom', 'its_my_infomation');
  }

  render(){
    return (
      <BootstrapTable ref="table" data={products}>
          <TableHeaderColumn dataField="id" isKey={true}>Product ID</TableHeaderColumn>
          <TableHeaderColumn ref="name" dataField="name" className="td-header-string-example">Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField="price" columnClassName="td-column-string-example">Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
};
```

**Comment by AllenFang** [comment]
another things is about how to get the sort state, you can set ```onSortChange``` hook at ```options``` prop. check this [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/sort-hook-table.js)

**Comment by jochenberger** [comment]
Yes, that'll do it, thanks!

**Comment by jochenberger** [comment]
Unfortunately I also have to remove the `span.order` element that is created since https://github.com/AllenFang/react-bootstrap-table/commit/55ac719981bfd30708059f218b33431e4650bc2a. Maybe that could be made optional.

**Comment by AllenFang** [comment]
your goal is add some custom attribute on ```th```, why to remove the ```span.order``` elm  in the content of ```th```?

**Comment by staminaloops** [comment]
I surely cant understand what you are trying to do, or why do you want to use data-attributes or messing directly with the DOM with React. Maybe you should consider changing your approach :)

**Comment by jochenberger** [comment]
I want to render custom sort icons. The CSS that I use does that by setting different background images on the `th` elements depending on the `data-column-sort` attribute. Now, if I set those attributes, I get the sort icons from the CSS as well as the default sorting icons from the `span.order`. 
That's why I wrote that I wanted to customize the whole `th` in the first place. ;-)

**Comment by AllenFang** [comment]
@jochenberger, if I make the [55ac719](https://github.com/AllenFang/react-bootstrap-table/commit/55ac719981bfd30708059f218b33431e4650bc2a) as an optional, can this help you solve all issues?

btw, if I don't want to make the [55ac719](https://github.com/AllenFang/react-bootstrap-table/commit/55ac719981bfd30708059f218b33431e4650bc2a) as an optional, instead, I provide a props to let you to set the classname on span to replace the ```order``` & ```dropup```, how about this?

**Comment by jochenberger** [comment]
I can hide the span by setting display:none in my CSS. That seems imperfect to me but I can live with it. ;-) Option 2 would not help me though.

**Comment by AllenFang** [comment]
@jochenberger, great!
