### ISSUE TITLE
Column widths don't match headers, and change when selection checkbox is clicked

### ISSUE THREAD

**Issue by dukedougal** [AllenFang/react-bootstrap-table#268]
I've seen a few other issues here saying that column widths do not match header widths but I'm not sure if this issue is fixed.

Also each time I click on the select checkbox, the column contained the select checkboxes gets a little bit wider.

**Comment by staminaloops** [comment]
Hello,

@AllenFang is on vacations (well deserved!), but please follow this https://github.com/AllenFang/react-bootstrap-table/issues/227

AllenFang commented 15 days ago
I've planed to design a new bootstrap table to solve the width and align problem. need some time.

**Comment by AllenFang** [comment]
thanks @staminaloops, I thinks these all width issues will be fixed in near future, if problem still remain, feel free to open another issue

**Comment by AllenFang** [comment]
@dukedougal, ```v2.0.0``` has been released, you can check #331 for more detail explanation, if problem still remain, please tell me on #331 or open an issue
