### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getDOMNode' of undefined

### ISSUE THREAD

**Issue by urahonky** [AllenFang/react-bootstrap-table#27]
Hi there Mr. Fang,

I have run into an issue and I suspect that it's pretty unique but it's causing me some problems. I'm getting the following error message:

```
Uncaught TypeError: Cannot read property 'getDOMNode' of undefined
```

And this occurs here:

```
_adjustHeaderWidth: {
      value: function _adjustHeaderWidth() {
        this.refs.table.getDOMNode().childNodes[0].childNodes[0].style.width = this.refs.table.getDOMNode().childNodes[1].childNodes[0].offsetWidth - 1 + "px";
      }
    },
```

It seems to occur when I draw the Table on the page and then remove it. In my application they have something similar to tabs. On the third tab it shows this table. When they click off of the tab the table stops being rendered. After that if they resize their window the console gets filled with that error message.

I'm not quite sure how to handle this on your end. I'd maybe look to see how other react components are unmounting or something. Do you need me to write up a quick and dirty example?

**Comment by AllenFang** [comment]
Hi @urahonky, maybe give me a quick sample, I can debug it. :))

**Comment by urahonky** [comment]
Sorry Mr. Fang... Work has been crazy today. Hopefully I get a break tomorrow for me to write up a quick example.

**Comment by AllenFang** [comment]
that's ok,  take your time :)

**Comment by chuchengcao** [comment]
BootstrapTable.js:294 Uncaught TypeError: Cannot read property 'getDOMNode' of undefined
Can this help? version 0.9.7

**Comment by AllenFang** [comment]
Hi @chuchengcao 
I probably know the problem is just the <code>this.ref.table</code> does not exist, and add a <code>if</code> condition maybe a quickly solve way. But I want to know what condition and why caused it :)

Anyway, so can you tried out this issue also?

**Comment by chuchengcao** [comment]
Hi, @AllenFang , thank you for reply. I think I found the method to repeat the problem.
1. Transition to a page which render the React-bootstrap-table;
2. Transition to another page which does not contain the React-bootstrap-table;
3. Change the view port height (alter the brower height for example)
4. Got the error
5. Even though we transition to the page which render the React-bootstrap-table again, the problem still exist;
Source code is a bit too many, do you need the source code?

**Comment by AllenFang** [comment]
OK, I got it. I'll check it out, thanks very much :)

**Comment by LeeChSien** [comment]
I got same problem when I resize the browser window.
<img width="984" alt="2015-08-23 1 44 34" src="https://cloud.githubusercontent.com/assets/1298784/9427114/73f0eb32-499d-11e5-8f1e-4986d8f0e449.png">

**Comment by AllenFang** [comment]
Hi @chuchengcao, I follow your instruction but I can't get this problem. how you change the page or can give some certainly example ?

**Comment by AllenFang** [comment]
I've fixed this problem by avoiding this error happened for a temporary solution, if any bug appear, plz report. However, update to v0.9.11 and check it out :)

**Comment by chuchengcao** [comment]
No such errors anymore :)
