### ISSUE TITLE
Provide unminified production distribution

### ISSUE THREAD

**Issue by jochenberger** [AllenFang/react-bootstrap-table#273]
I'd like to propose adding an unminified aggregated build (e.g. `dist/react-bootstrap-table.js`). This will make debugging much easier for users.

**Comment by AllenFang** [comment]
HI @jochenberger, As I know, only one main entry point I can assign on npm package. Any idea?

**Comment by jochenberger** [comment]
Sorry, I don't have much experience with node and npm. But, if I understand the question correctly, the minified version could still be the default and the unminified one could be an additional option. Or can you set it up so that the file is chosen depending on the `NODE_ENV` of the application?

**Comment by AllenFang** [comment]
me too, i'm not sure about this issues, 

> Or can you set it up so that the file is chosen depending on the NODE_ENV of the application?

I think it's impossible, i'll spend some time to find the solution, but the priority is lower, sorry

**Comment by AllenFang** [comment]
if you find any case like you said, please let me know or PR is welcome :)

**Comment by jochenberger** [comment]
Closed in favor or #277

**Comment by dana2208** [comment]
Hi,

While running the project (either with gulp prod or gulp example-server) in chrome you can see in the developer tool in the source tab the folders "webpack://" > "." > "src". In the "src" you can see all the sources and debug there.
Isn't it what you wanted?
![image](https://cloud.githubusercontent.com/assets/10193337/13081556/ed2382b2-d4d5-11e5-994d-44783821b449.png)

**Comment by jochenberger** [comment]
@dana2208 no, I want to be able to use my Java web framework's minification/aggregation capabilities.

**Comment by AllenFang** [comment]
@jochenberger, you used Java web framework to minify javascript code? what tool you used?

**Comment by jochenberger** [comment]
I'm using [Apache Tapestry](http://tapestry.apache.org/) together with https://github.com/eddyson-de/tapestry-react. The minification is done via [Google Closure Compiler](https://developers.google.com/closure/compiler/).
