### ISSUE TITLE
Customization of the "no data to display" cell

### ISSUE THREAD

**Issue by jochenberger** [AllenFang/react-bootstrap-table#274]
I'd like to be able to customize what is displayed if there is no data available. Currently, my use case is that I'd like to remove the `text-align: center` style.

**Comment by AllenFang** [comment]
@jochenberger, how about I add a class name on the ```tr``` so that you can override it by css on your site?

**Comment by jochenberger** [comment]
Yes, that would help me for my current project. I wonder if I might need more flexibility someday, but I can always open another issue then. Thanks!

**Comment by AllenFang** [comment]
ok, I'll add it on next version, thanks

**Comment by AllenFang** [comment]
@jochenberger, I've added a classname on "no data to display" ```td``` on newest version.

**Comment by jochenberger** [comment]
Could you add the `text-align: center` to the CSS class instead of to the element itself? That would make it easier to override.

**Comment by AllenFang** [comment]
@jochenberger, I've did this improvement on v1.5.3

**Comment by jochenberger** [comment]
Great, thanks!
