### ISSUE TITLE
Combination of Edit cell and Filter

### ISSUE THREAD

**Issue by dana2208** [AllenFang/react-bootstrap-table#279]
Hello,

When table is filtered on a specific value, let's say names that contain "A" and I edit a row and change the name to "BBB" then I expect the row not to be displayed after the row is saved since it does not fit the result set.
I guess we can achieve that behavior using the prop `afterSaveCell` but I think it should be built in and now it looks like a bug.

What do you think?

**Comment by AllenFang** [comment]
You are right, I thinks this is easy to fix.

**Comment by AllenFang** [comment]
Released on v1.5.2
