### ISSUE TITLE
Selecting all (row selection) + Pagination does not return all data

### ISSUE THREAD

**Issue by annelorraineuy** [AllenFang/react-bootstrap-table#280]
Hi there. Great module!! Props to you for creating this, I love it! :+1: 

However, I think it's quite inconsistent that selecting all rows _(when pagination = true)_ only returns the rows on 1 page when all other rows on the rest of pages are actually selected! Is there a way to make the behaviour consistent? 

Either `currentSelectedAndDisplayData` returns all the selected rows, or only the rows on that one page is selected.

**Comment by AllenFang** [comment]
@annelorraineuy, did you want to get the all selected rows?

**Comment by annelorraineuy** [comment]
Yes. Either behaviour is fine as long as it is consistent. Get all selected rows or have only the rows on 1 page be selected.

**Comment by AllenFang** [comment]
```js
export default class SelectHookTable extends React.Component{
  getSelectedRowKeys() {
   // I think this answers your questions
    console.log(this.refs.table.state.selectedRowKeys)
  }

  render(){
    return (
      <div>
        <button onClick={this.getSelectedRowKeys.bind(this)}>Get selected row keys</button>
        <BootstrapTable data={products} selectRow={selectRowProp} ref='table'>
            <TableHeaderColumn dataField="id" isKey={true}>Product ID</TableHeaderColumn>
            <TableHeaderColumn dataField="name">Product Name</TableHeaderColumn>
            <TableHeaderColumn dataField="price">Product Price</TableHeaderColumn>
        </BootstrapTable>
      </div>
    );
  }
};
```
reference from #261 
Thanks!
