### ISSUE TITLE
Sorting not behave properly 

### ISSUE THREAD

**Issue by Dhaval8087** [AllenFang/react-bootstrap-table#281]
Hello Allen,

I have implemented one column in table in that column my data like 

Col A           Col B
 1                 abc
 2                 ABC
 3                 bcd

so when I sort  col B data should like 

abc
ABC
bcd

but in my component it's look like 
abc
bcd
ABC

basically in sorting it will count upper case and lowercase can you please let me know how we can avoid upper and lower case while sorting

**Comment by AllenFang** [comment]
@Dhaval8087, It seems like a bug for now, so I need to trace to know why I use upper case or lower case when sorting, if I found the reason, I will tell you and implement a mechanism to avoid case, 
Thanks :)

**Comment by AllenFang** [comment]
@Dhaval8087, I've tested but I could not reproduce this issues, could you please give me your example code?
that's my scenario

abc
ABC
bcd

order by desc
bcd
abc
ABC

order by asc
ABC
abc
bcd

Thanks

**Comment by markortiz** [comment]
@AllenFang, on my end I do have also problem with sorting.

```
abc
Abc
bcd
Bcd
```

It should be
Desc:
```
Bcd
bcd
Abc
abc
```

Actual result is:
Desc:

```
bcd
abc
Bcd
Abc
```
Asc:
```
Abc
Bcd
abc
bcd
```

In my case if the hierarchy of sorting is like
1. 0-9
2. A-Z
3. a-z
4. Chinese Characters 

another thing is if there are `null` items in between, for example

```
Abc
null
Bcd
Cde
Def
```
expected result is 
Desc:
```
Def
Cde
Bcd
Abc
null
```
Asc:
```
null
Abc
Bcd
Cde
Def
```

Actual result:
Desc:
```
Abc
null
Bcd
Def
Cde
```

my temporary fix for that if I have a `dataFormater` that will convert all `null` to a empty string `' '` then it will work fine.

**Comment by AllenFang** [comment]
@Dhaval8087, @markortiz, I can reprodce this issue and figured out why this bug happened. I thinks I need to use ```localeCompare``` for a correctly compare on sorting. I'll do more survey and release at next version :)

Sorry for a long time to fix ;(

**Comment by markortiz** [comment]
Thanks @AllenFang :)
