### ISSUE TITLE
Issues of table search

### ISSUE THREAD

**Issue by liqili** [AllenFang/react-bootstrap-table#282]
I have found some issues about Table Search functionality.
1.The search key matched the hidden column.
2.I met problems following the below steps.
a.SelectAll records
b.Search by some condition.Some records are filtered.
c.I still get all records including filtered records when submitting to backend .

**Comment by AllenFang** [comment]
@liqili, I'll check this out. Thanks :)

**Comment by liqili** [comment]
@AllenFang Thanks very much.Regarding issue 2,I think it's not a problem if I can get the record sets displayed in the screen.

**Comment by AllenFang** [comment]
@liqili, for issue 2, you can try this:
```js
var options  = {
  //...
  afterSearch: function(searchText, result) {
      //result is the data which filtered
  }
}

//...

<BootstrapTable options={options}>
```

**Comment by liqili** [comment]
@AllenFang Fine.Thank you!

**Comment by AllenFang** [comment]
@liqili, if work, please let me know :)

**Comment by liqili** [comment]
@AllenFang Thanks,It's satisfied my requirements.

**Comment by AllenFang** [comment]
Great, I will fix issues 1

**Comment by AllenFang** [comment]
For issues 1, I've fixed it and released on v1.5.2

**Comment by chriscostello9** [comment]
Maybe list a good example for those using ES6 linting, in your docs:

```
options={{sortName: 'name',
  sortOrder: 'asc',
  afterSearch: (searchText, result) => {
    this.afterSearch(result);
  }
}}
```

Then, the afterSearch function to do whatever it is you want:

```
afterSearch(result) {
  const filtered = new Set(result.map(item => item.myPropName));

  this.setState({
    filtered: selected,
  });
}
```

**Comment by AllenFang** [comment]
@chriscostello9, thanks your feedback. I'll improve my document in near future :)

**Comment by waiter** [comment]
@AllenFang 
Since the search can't search text in object, so can't you add a switch to enable the search key matched the hidden column? Or other better ways??

I've read the source code, the `targetVal.toString()` makes the object to `[Object object]` ...

**Comment by AllenFang** [comment]
@waiter, I think it's hard to search on an object. But if I make the searching on hidden column configurable, is that helpful for you?

**Comment by AllenFang** [comment]
@waiter, btw, your case is common, if you really need a object can be searched, A customization search can achieve your requirement. I mean just handle search and state outside the ```react-bootstrap-table```.

**Comment by waiter** [comment]
@AllenFang 
Make the searching on hidden column configurable is what I want. So could you add this feature.
Handle search and state outside the `react-bootstrap-table` means I should reset the `BootstrapTable `'s prop `data` every time?

**Comment by AllenFang** [comment]
@waiter, I think I can add this feature in near future. 

> Handle search and state outside the react-bootstrap-table means I should reset the BootstrapTable's prop data every time?

yes, after searching, just render new props data on table

**Comment by waiter** [comment]
@AllenFang 
OK, thank you~

**Comment by AllenFang** [comment]
@waiter, @liqili  I've released the newest version v1.6.0
**Currently, hidden column can be searched by default, if you want some hidden cant be searched, add ```searchable={false}``` on ```<TableHeaderColumn>```**

Sorry for this functionality changed, feel free to discuss with me

**Comment by waiter** [comment]
@AllenFang 
Great to hear that! Thank you~
But, it doesn't work. Did you write the wrong logical operator??
**you write  `!hidden && searchable` to check wheather it can be searched, 
but I think it should be `!hidden || searchable` since when column is hidden, then `hidden={true}`.**
Pleace check it ...

**Comment by AllenFang** [comment]
I made a big mistake, I will solve this issue quickly. Thanks

**Comment by waiter** [comment]
@AllenFang 
Great~

**Comment by AllenFang** [comment]
@liqili @waiter, sorry for my mistake, ```v1.6.1``` is the newest version, hidden column can be searched by default. you can set ```searchable={false}``` to disable. Feel free to ask anything

**Comment by waiter** [comment]
@AllenFang 
Thank you, it works now~~

**Comment by nguyenchanhnghia** [comment]
hi all. I have a issue of search table. search is not working when data of cell is object. How to search realizable?
Thank!

**Comment by AllenFang** [comment]
@nguyenchanhnghia, sorry for lately reply, I've opened #569 and have a plane to deal with it.
