### ISSUE TITLE
change the column filter position 

### ISSUE THREAD

**Issue by priyanka1-webonise** [AllenFang/react-bootstrap-table#284]
Is there any option to change the position of column filter position?
currently it is at bottom of the table I want to it at after the table header

**Comment by liqili** [comment]
In v1.5.1,you can set the TableHeaderColumn parameters like below.
` <TableHeaderColumn dataField="name" filter={{type: "TextFilter", placeholder: "Please enter a value"}}>Product Name</TableHeaderColumn>`

**Comment by AllenFang** [comment]
@priyanka1-webonise, check [examples](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/column-filter), this feature release on v1.5.1, it will apply filter on header

**Comment by priyanka1-webonise** [comment]
Thanks for quick reply.
Can I replace this text filter with another custom react component.
I want to replace it with slider.

**Comment by AllenFang** [comment]
check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js)

**Comment by priyanka1-webonise** [comment]
Hey thank you so much.
awesome product as lot of customization possible.

**Comment by AllenFang** [comment]
Thanks, I am very grateful. btw, this feature implemented by another contributor @dana2208, he give this awesome feature :+1:
