### ISSUE TITLE
How set filter column at above

### ISSUE THREAD

**Issue by Dhaval8087** [AllenFang/react-bootstrap-table#286]
Hello Guys,

I want to set filter row column at above currently it's available at bottom. can you please let me know how we can set at above I mean below the column header

**Comment by AllenFang** [comment]
is [column-filter](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/column-filter) ?

**Comment by AllenFang** [comment]
I will open if you have any feedback or response

**Comment by Dhaval8087** [comment]
Please check the URL
[https://www.dropbox.com/s/pcvp1nrreqxkw40/Reactdatagrid.PNG?dl=0](url)

I want to add the filter col in at above means below the headers

**Comment by AllenFang** [comment]
Hi @Dhaval8087, your link is broken. btw, I think your hope is make the filter still in the header but    above the column text, right? if yes, I'll make this feature configurable.

**Comment by Dhaval8087** [comment]
Hello Allen,

Can you please check this link 
https://www.dropbox.com/s/pcvp1nrreqxkw40/Reactdatagrid.PNG?dl=0
yes I want to set the filter col just below the header.

**Comment by dana2208** [comment]
Hello @Dhaval8087 ,

Do you mean like that?
http://allenfang.github.io/react-bootstrap-table/example.html#header-filter

**Comment by Dhaval8087** [comment]
@dana2208 Yes exactly Thanks I will use filter on each TableHeaderColumn that I think it resolve my prob.

**Comment by AllenFang** [comment]
Thanks @dana2208
