### ISSUE TITLE
selectRow needs a class property

### ISSUE THREAD

**Issue by L5eoneill** [AllenFang/react-bootstrap-table#287]
Since you can't set a width with a table header, selectRow should have a property to assign a class to the column.

**Comment by AllenFang** [comment]
You can assign ```columnClassName``` on ```TableHeaderColumn```, check [these](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/style) all example

**Comment by L5eoneill** [comment]
selectRow isn't entered into the table as a separate TableHeaderColumn, though, so you can't set a classname on it.

**Comment by AllenFang** [comment]
why need ```selectRow```?

**Comment by L5eoneill** [comment]
To have checkboxes for selecting a row for an action. That's what it's for, right?

**Comment by AllenFang** [comment]
yes, but if you want to set column class on table, just assign ```columnClassName``` on ```TableHeaderColumn```, check [these](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/style) all example. It's not a matter with ```selectRow```.

Your goal is give your custom class on column, am I right?

**Comment by L5eoneill** [comment]
Someone here is very confused. selectRow creates a column of checkboxes which are not created using TableHeaderColumn. I'd like that column to have a class as one of its properties.

`    const selectRowProp = {
      mode: 'checkbox',
      onSelect: this.onRowSelect.bind(this),
      onSelectAll: this.onSelectAll.bind(this)
    };`

Oh blah... that's from an example in your docs, but I just looked at the full docs, and it lists className as an allowed property for the selectRow object.

But to clarify: selectRow is not created by the component having TableHeaderColumn for the select checkbox column. The other columns are created that way, just not the select column. That's what I was trying to say.

So anyway, thanks for responding so quickly, and sorry I didn't find the part of the docs earlier where className can be a property for the selectRow settings object.

**Comment by AllenFang** [comment]
Thaht's ok, dont mind :)

**Comment by pastinepolenta** [comment]
@AllenFang I am still confused on this one.

Goal: custom CSS class on the FIRST column, the one with the checkboxes

- `columnClassName` can be used on `TableHeaderColumn` but `TableHeaderColumn` is not responsible of rendering the first column
- `className` on `selectRow` is the class of the selected row, so nothing to do with the first column

What is the solution?

**Comment by L5eoneill** [comment]
@stilllife00 It's been a while, but iirc putting a className in the selectRow object worked for me.
