### ISSUE TITLE
React warning: Don't set .props.clearSortCaret

### ISSUE THREAD

**Issue by chuchengcao** [AllenFang/react-bootstrap-table#29]
I got this warning:Don't set .props.clearSortCaret of the React component. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props.

vesion0.9.7, TableHeader.js:110.

I think React does not suggest modify props directly, maybe we can use React.cloneElement instead?

**Comment by AllenFang** [comment]
Thanks for your remind, And in <a href='https://github.com/AllenFang/react-bootstrap-table/issues/25'>#25</a> issues also talk about the all warning in this component, Anyway I'll spend some time to fix it, thanks :)
