### ISSUE TITLE
Possible to change the no data text?

### ISSUE THREAD

**Issue by eric379990** [AllenFang/react-bootstrap-table#290]
Hi Allen,

Since there are lots of data in my table, when the remote data has not been sent back, the table is showing "There is no data to display", sometimes it is confusing the user. Is it possible to dynamic change it to "Loading" when the data has not been sent back?

Thanks.
BR/Eric

**Comment by AllenFang** [comment]
check following example
```js
var options = {
    noDataText: 'Your_custom_text'
};

<BootstrapTable
                data={products}
                options={options}
>...
```

**Comment by eric379990** [comment]
Thanks Allen！

**Comment by tuananh19961** [comment]
Thank you Allen!

**Comment by titoxix** [comment]
Thanks Allen
