### ISSUE TITLE
Need min-width to work with safari for wide table

### ISSUE THREAD

**Issue by daiwhea** [AllenFang/react-bootstrap-table#300]
Hi.

I have a large table with many columns. react-bootstrap-table works well in chrome. But in safari, table header doesn't align to tbody.

![table](https://cloud.githubusercontent.com/assets/163152/13319078/0fb9c0cc-dbfa-11e5-8deb-fd67d26406b8.png)

I modified your react-bootstrap-table.min.js to add minWidth:width, Then it works for safari now.

Thanks!

**Comment by AllenFang** [comment]
@daiwhea, sorry for lately reply. I've started to re-design the dom of ```react-bootstrap-table``` for fixing width and unalign problem. It will coming soon.

**Comment by daiwhea** [comment]
Thanks.

**Comment by AllenFang** [comment]
HI @daiwhea, ```v2.0.0``` has been released, you can check #331 for more detail explanation and I'll close this issues, if problem still remain, please tell me on #331 or open an issue.
