### ISSUE TITLE
Options value for current page and size per page are not respected

### ISSUE THREAD

**Issue by xabikos** [AllenFang/react-bootstrap-table#304]
We are using the component with server side pagination. This means that we only retrieve the data for the current page from the page and in every page change or when the size of the page changes a new request is happening. This requires to maintain the current page and the current size per page internally and pass it to react-bootstrap-table through the options object. This worked quite good but currently is broken. I suspect this happened in this [commit](https://github.com/AllenFang/react-bootstrap-table/commit/add9ff611b0ed3e0945723d45379e3379681bc0f) as I noticed this behavior in version 1.5.3. If the description is not clear enough I can provide also a small example demonstrate that.

**Comment by AllenFang** [comment]
@xabikos, I thinks a example is good. btw,

**Comment by xabikos** [comment]
@AllenFang Here you can find an example gist I created which demonstrates the problem
https://gist.github.com/xabikos/fcd6e709f8ae0c11e33b
This works perfectly in version 1.5.2 but not in later versions. Paging and size per page are not changed in a correct way. Please let me know if I need to provide some more info.

**Comment by AllenFang** [comment]
Thank your! I'll check this out

**Comment by xabikos** [comment]
Please keep in mind my first comment and which changes are probably related to the problem. Thanks in advance for the help. I will also try to explore the code.

**Comment by AllenFang** [comment]
@xabikos, a question, the problem which you encounter is that the page button and sizePerPage dropdown is not changed correctly, ex: click page 2, but I see page one still clicked but data has changed correctly

**Comment by xabikos** [comment]
Exactly this one. And if you try to change the size per page e.g. to 25 then you will see 25 rows but the corresponding dropdown still shows 10

**Comment by AllenFang** [comment]
ok, Thanks your example!

**Comment by AllenFang** [comment]
@xabikos, fixed on v1.6.2. You can check it out :)

**Comment by xabikos** [comment]
Yes it is fixed. Thanks once again!
