### ISSUE TITLE
Prepend New Row to Table Manually

### ISSUE THREAD

**Issue by annelorraineuy** [AllenFang/react-bootstrap-table#307]
Hi there! Thanks again for the awesome work :) This is more of a question than anything. Is there a way for me to define a custom method that would prepend (new data as first row) manually? I have an external way of adding data to the table (it's more complex than what the built-in Add row can do) so instead of calling the server to reload the data, I want to just show the user that the data was added to the table.

**Comment by AllenFang** [comment]
Thanks. I've some idea for this and I can test it after going off work. If my idea is not work, maybe i will give a expose function on ```BootstrapTable``` for this issue. btw, how did you add a new row to table currently? by state?

**Comment by annelorraineuy** [comment]
I wasnt able to add a new row! Was just asking if its possible and if so, how? Hehehe

Anne Lorraine Uy
www.anneuy.com

**Comment by AllenFang** [comment]
Following is able to add new row externally, but the new row will be appended at last
```js
var fakeRow = {
      id: 10,
      name: "Product one ",
      price: 240
};
// insert a new row
var result = this.refs.table.handleAddRow(fakeRow);
if(result){  //some error happen, ex: doesn't assign row key or row key duplicated
      console.log(result);
}
```
for your requirement(the new row at first), there's no way to do this, but I think it's easy to do in next version.

**Comment by annelorraineuy** [comment]
Okay, thank you so much Allen! Looking forward to the next version. :)

**Comment by AllenFang** [comment]
@annelorraineuy , fixed and released on v1.6.0. Thanks :)

```js

handleBtnClick = () => {
   this.refs.table.handleAddRowAtBegin({
     id: fake_id, 
     name: 'product 1', .....
   });
}

render() {
  return (
    <div>
      <button onClick={this.handleBtnClick}>Prepend</button>
      <BootstrapTable ref='table'>
          ....
      </BootstrapTable>
    </div>
  );
 
}
```

**Comment by SwethaMK** [comment]
Say the json data is held in a javascript array called myList at index 0 & you are inserting into table name 'myTable', use the 'insertRow' option for bootstrap table to insert as the last row at the end of the table, as below:

var rowId = $("#myTable >tbody >tr").length;
$(myTable).bootstrapTable('insertRow',{
            index: rowId,
            row: myList[0]
         });

**Comment by ghost** [comment]
@SwethaMK I dont understand? Why use jQuery when you are already using React? Isn't React supposed to replace other UI libraries ?
