### ISSUE TITLE
Server side pagination 

### ISSUE THREAD

**Issue by smondal** [AllenFang/react-bootstrap-table#308]
How server side pagination will work with react-bootstrap-table? As I see **bootstrap table** supports server side pagination using sidePagination but **react-bootstrap-table** is not supporting this.

Below are the link for supporting server side pagination on **bootstrap table** 
http://bootstrap-table.wenzhixin.net.cn/documentation/
https://github.com/wenzhixin/bootstrap-table-examples/blob/master/options/server-side-pagination.html#L22

**Comment by AllenFang** [comment]
@smondal, this component does not support server side pagination and remote data fetching. I think this feature will not be implemented in near future. But PR is welcome

**Comment by yybear** [comment]
@AllenFang, 
can just add a prop 'dataTotalSize' which is total size of data from remote server in BootstrapTable component? 
then component can use the 'dataTotalSize' not the size of 'data' prop.

**Comment by AllenFang** [comment]
HI @yybear, what's your purpose, or any trouble you encountered?

**Comment by yybear** [comment]
Hi @AllenFang 
now react-bootstrap-table is not support for server side pagination, i think it can add  a prop 'dataTotalSize' which is the total size of data got from server side.

<BootstrapTable **dataTotalSize={this.state.total}** data={this.state.items} selectRow={this.selectRowProp} pagination>

the reponse from server side is not only returning data items but also the total size of data. for example:
{'total':100, "items":[item1, item2, item3]}

now u must use the size of 'data' prop to paginate in client side. if add the 'dataTotalSize' prop, u can use it to paginate in client side.  when page changed we can use the of 'sizePerPageListChange' or 'onPageChange' to get the new data items from server side.

i think it's a way to support server side pagination for react-bootstrap-table.

**Comment by AllenFang** [comment]
@yybear, ```react-bootstrap-table``` has been supported remote pagination from ```v2.3.0```, but not yet update document, you can check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-paging.js) example. Hope this feature can help you :)

**Comment by yybear** [comment]
@AllenFang good job! i will try it, thks.

**Comment by VuongTran21** [comment]
Hello @AllenFang, thanks for your great package on React, I'm using React Bootstrap Table and I have small problem. When using pagination, how can I show all page depend on totalSizeData without get all data. It's because if I have about more thousands records and I have to get all for the first request, it will be take a long time, could you please help me?

**Comment by prajapati-parth** [comment]
@VuongTran21 Please refer [this comment above](https://github.com/AllenFang/react-bootstrap-table/issues/308#issuecomment-219713836). This is a similar issue.
Thanks.

**Comment by VuongTran21** [comment]
Thanks @prajapati-parth , I'm fresher with React and I really don't understand exactly how to apply it to pagination in server side, could you please help me?

**Comment by prajapati-parth** [comment]
@VuongTran21 With all humbleness, it would be really great for this question to be asked on StackOverflow. The issues tab of the repo is more focused to solve repo specific bugs and request for new features.

Thanks.

**Comment by sanjibansealnavsoft** [comment]
For everybody who will face this problem, **how to pass total datasize as number**, just go here 
[https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-paging.js](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-paging.js).
You will find something like this : 
fetchInfo={ { dataTotalSize: this.props.totalDataSize } }
