### ISSUE TITLE
Pagination question

### ISSUE THREAD

**Issue by zoilorys** [AllenFang/react-bootstrap-table#31]
I will need to work with a lot of data from server, so i wanted to ask is it possible, if i'll get first 10 items from server and just the number of pages, to set number of pages for pagination? I did not found any kind of property, that would let me to do this. I just dont want to mess myself with your src.
And is there way to make table to not resize, when there is less items, like when you switch from page with 10 items to 3 items, so it fills the rest with blanks?

**Comment by AllenFang** [comment]
1. So you just want to set the number of a page? If yes, there's actually no way to do this currently, but I can add it in the future.

2. A way to make table to not resize when there is less items. I think it's a particular case for bootstrap table and perhaps you can use css to control the table. I dont want to solve this question probably.

**Comment by zoilorys** [comment]
1. To set the overall number of pages, so it is possible to bind click handler to button to request new data from server depending on chosen number of page. It is important, cause application will need to work with thousands of entries, and its not really good to fetch all of them at once. 
2. What i meant, is that it would be nice if when next page is less than prev, the diff is filled with empty rows to keep the size of table, counting elements per page.

**Comment by AllenFang** [comment]
1. I thinks it's possible. But this advance feature which I need to do more plan and maybe take many times.

2. ok, I understand what you mean. If I have a lots of free time, I will do this feature :)

**Comment by zoilorys** [comment]
@AllenFang , nice to hear :) You've done great job so far, so thank you for that)

**Comment by joshhornby** [comment]
+1 on this. Any timescale?

**Comment by AllenFang** [comment]
HI @joshhornby, I've no any schedule for this currently, there's some stuff I need to do. But I will keep it in my mind :)

**Comment by smartameer** [comment]
By giving ```height="auto"``` worked for me for removing the blank. :)
