### ISSUE TITLE
Feature for single cell click?

### ISSUE THREAD

**Issue by bbesase** [AllenFang/react-bootstrap-table#318]
I may be missing something, but is there a feature that handles single cell clicking rather than just whole row clicking?

**Comment by AllenFang** [comment]
@bbesase, sorry for we dont support this feature, btw, let me know what's your consideration or requirement, maybe I can help you :)

**Comment by bbesase** [comment]
I figured it out! I used the data format to return a React Component with
the HTML string and from there I was able to register onClick to it and
pass cell and row as props 😀

**Comment by AllenFang** [comment]
@bbesase, cool solution! I will close this issue. Feel free to discuss with me. Thanks :+1:
