### ISSUE TITLE
Use React.Children to iterate/mutate children

### ISSUE THREAD

**Issue by bbodi** [AllenFang/react-bootstrap-table#319]
[According to](https://facebook.github.io/react/tips/children-props-type.html) React, 

> when there is only a single child, this.props.children will be the single child component itself without the array wrapper. This saves an array allocation.

In my application, an error occurred [at this line](https://github.com/AllenFang/react-bootstrap-table/blob/43cebf33faf22aa16efb75ecd67280da81b1aef6/src/BootstrapTable.js#L119
), because of one of my **one-column table**.
```
Uncaught TypeError: children.map is not a function
```

My suggestion is to use [React.Children.map](https://facebook.github.io/react/docs/top-level-api.html#react.children).

Sorry for not implementing and testing it myself, but currently I haven't got the infrastructure to do that.

**Comment by AllenFang** [comment]
@bbodi, I'll check this out!

**Comment by AllenFang** [comment]
@bbodi, I've fixed it and release on v1.6.1
