### ISSUE TITLE
Sort feature doesn't work in Chrome last version 

### ISSUE THREAD

**Issue by garciasa** [AllenFang/react-bootstrap-table#320]
Hi guys,
I'm using Chrome (last version) and IE11, to render some data with this component, but when i include sort feature in one of the columns, in chrome, when i click in that column to sort data, i lose all the columns, except the first one. In IE11 is working properly.

`        <Grid>
            <Row>
                <Col xs={10} sm={10} md={10} >
                    <span>Inputting Surface </span>
                </Col>
            </Row>
            <Row style={style.row}>
                <Col xs={11} sm={11} md={11} >
                    <BootstrapTable data={data.inputsurface} striped={true}>
                        <TableHeaderColumn dataField="code" isKey={true}>Code</TableHeaderColumn>
                        <TableHeaderColumn dataField="name" dataSort={true}>Name</TableHeaderColumn>
                        <TableHeaderColumn dataField="type" dataSort={true}>Type</TableHeaderColumn>
                        <TableHeaderColumn dataField="lateststatus">Latest Status</TableHeaderColumn>
                    </BootstrapTable>
                </Col>
            </Row>
        </Grid>`

I'm using other react component react-bootstrap, could that the issue??

**Comment by AllenFang** [comment]
I've no idea, could you try [this](http://allenfang.github.io/react-bootstrap-table/example.html#column-sort) on your chrome first?

**Comment by garciasa** [comment]
Yes, that is working, is something incompatible between react-bootstraps and react-bootstrap-table, I'm gonna try to figure it out...

Thanks anyway
