### ISSUE TITLE
Sort and width column feature doesn't work when it's in a hidden div in Chrome (49)

### ISSUE THREAD

**Issue by garciasa** [AllenFang/react-bootstrap-table#321]
Hi,
now i now what it's wrong, if you put a table, as part of bootstrap Tab, and that Tab it's not a default Tab (it's hidden at the beginning), when you click on that tab, and try to order one of the column, all of them disappears, except the first one...

It's working properly when the table is in the default tab and it's the first you see when you load the component.

This behavior is in Chrome (last version), in IE11 works properly.

Any suggestion??

**Comment by AllenFang** [comment]
@garciasa, ok I understand, could you please me a example code and tell me the react-bootstrap version. It's helpful for me to debug, because I'm not familiar with ```react-bootstrap```, so a repo is better :)

**Comment by garciasa** [comment]
Sure, this is my test component, by default the tab is the second one defaultActiveKey={2}, in that way is not working, if you change to {1}, in which the table is then works.



`
import React from 'react';
import {Tabs, Tab} from 'react-bootstrap';


const products = [
    {
        id: '1',
        name: 'asdfasf',
        price: '123'
    },
    {
        id: '2',
        name: 'ddddd',
        price: '23'
    }
];

const Test = () => {
    return(
        <Tabs defaultActiveKey={2}>
            <Tab eventKey={1} title="Tab 1">
                <BootstrapTable data={products}>
                    <TableHeaderColumn dataField="id" isKey={true} dataSort={true}>Product ID</TableHeaderColumn>
                    <TableHeaderColumn dataField="name" dataSort={true}>Product Name</TableHeaderColumn>
                    <TableHeaderColumn dataField="price">Product Price</TableHeaderColumn>
                </BootstrapTable>
            </Tab>
            <Tab eventKey={2} title="Tab 2">Tab 3 content</Tab>
            <Tab eventKey={3} title="Tab 3">Tab 3 content</Tab>
        </Tabs>
    );
}

export default Test;
`

**Comment by AllenFang** [comment]
great :+1:  I'll check this out

**Comment by garciasa** [comment]
Perfect! Thank you.....

**Comment by garciasa** [comment]
Hi,
i updated it, because I've the same issue with the width property... when you render a component, if it is in a hidden div, it doesn't works properly...

Cheers.

**Comment by AllenFang** [comment]
HI @garciasa, ```v2.0.0``` has been released, you can check #331 for more detail explanation and I'll close this issues, if problem still remain, please tell me on #331 or open an issue
