### ISSUE TITLE
Table header displayed twice

### ISSUE THREAD

**Issue by Antonhansel** [AllenFang/react-bootstrap-table#322]
<img width="1190" alt="screen shot 2016-03-08 at 14 26 11" src="https://cloud.githubusercontent.com/assets/4123811/13618582/c98bdfba-e539-11e5-9bd4-fac54daaa34a.png">

The table column names are displayed twice, yet I don't think I'm doing anything weird in my code:
I have a container component with the following render function

```
render() {
     <div className="container">
      {data && !res &&
        data.map(function mapData(places, index) {
          return <PlaceTable key={index} places={places}/>;
        })}
     </div>
}
```

And here is my render function of the PlaceTable element:

```
    return (
      <div className="container">
        <h2>{name}</h2>
        <BootstrapTable data={places} striped={true} hover={true} pagination={true} search={true} exportCSV={true} selectRow={selectRowProp} ref={name}>
          <TableHeaderColumn dataField="name">Name</TableHeaderColumn>
          <TableHeaderColumn dataField="address" isKey={true} dataAlign="center" >Address</TableHeaderColumn>
        </BootstrapTable>
      </div>
    );
```

Am I missing something?

**Comment by AllenFang** [comment]
Include ```css/react-bootstrap-table-all.min.css``` will solve this issue :)

**Comment by Antonhansel** [comment]
Thank you for helping out, indeed my CSS inclusion wasn't working, see this issue explaining why and how to make it work.
https://github.com/erikras/react-redux-universal-hot-example/issues/750

**Comment by AllenFang** [comment]
I'll check this out. Thanks

**Comment by Antonhansel** [comment]
I'm pretty sure react-bootstrap-table had nothing to do with the issue, just the way css are included in this boilerplate can be a bit confusing ;)

**Comment by AllenFang** [comment]
ok, I'm not familiar with that repo, but this is a issue first time that I see, so how did you solve it? follow this [thread](https://github.com/erikras/react-redux-universal-hot-example/issues/750#issuecomment-169936916)?

**Comment by Antonhansel** [comment]
Yeah, I tried [this solution](https://github.com/erikras/react-redux-universal-hot-example/issues/750#issuecomment-168012321) and it works too.

Thank you for your time :)

**Comment by AllenFang** [comment]
Great :)  Thanks for these feedback :+1:
