### ISSUE TITLE
"There is no data to display" is not centered anymore

### ISSUE THREAD

**Issue by flipjs** [AllenFang/react-bootstrap-table#323]
I was using 1.4.6 for a while, and the text "There is no data to display" was centered on the table. I upgraded to the latest version now which is 1.6.0 I believe. The text is now displaying on the leftmost of the screen. Its not centered anymore.

I went back to 1.4.6, and its displaying on the center correctly.

**Comment by AllenFang** [comment]
@flipjs, update you upgrade to higher version, did you import new css file(```css/react-bootstrap-table-all.min.css```)?

Because I remove the inline style for center text to css file, so I guess your env does not catch the correct css file

**Comment by flipjs** [comment]
Thanks for clearing that up.
