### ISSUE TITLE
Sorting caret on header indicator

### ISSUE THREAD

**Issue by flipjs** [AllenFang/react-bootstrap-table#324]
In 1.5.0, you added an enhancement that shows the up/down caret on header if column is sortable.

Is it possible to turn this off? I prefer the older behaviour where it shows nothing on header, but when clicked, it will show the up or down caret when sorting. For me, it looks cleaner without the caret by default. But when clicked, it will show the caret on the column clicked, just like the previous versions before 1.5.0.

In general, the ui enhancement is a welcome addition to the table, but it would be nice if we could also turn this off. Thanks.

**Comment by AllenFang** [comment]
ok, I'll spend some time to make this configurable. Thanks your feedback!

**Comment by AllenFang** [comment]
@flipjs, released on v1.6.2, you can check the [example](https://github.com/AllenFang/react-bootstrap-table/commit/a58493e11647f61776def1413301c2f4c4f0a68f). 
Thanks

**Comment by flipjs** [comment]
Cool! Will try it out now. Thanks @AllenFang You are a :star: !

**Comment by flipjs** [comment]
:tada: It works! Thank you so much @AllenFang ! :smiley_cat:
