### ISSUE TITLE
Question about devtool: '#eval-source-map'

### ISSUE THREAD

**Issue by TonyVeigel** [AllenFang/react-bootstrap-table#325]
Why is this in production?

**Comment by AllenFang** [comment]
@TonyVeigel, follow #217. btw, any consideration for ```eval-source-map```?

**Comment by TonyVeigel** [comment]
Thanks. I just know like #217  that the *eval* devtools should not be used for production only for development. I see now even on the newest build it is production.

**Comment by AllenFang** [comment]
Just a discussion, like the problem of #217, how to solve it in your opinion

**Comment by TonyVeigel** [comment]
I will think of a solution, in the meantime though, I would say it should be pulled out of production because it causes issues with minifying, performance, etc..

**Comment by TonyVeigel** [comment]
Is this going to be pulled out of production? Before : 95.9 KB, after: 521 KB now: 611 KB For a table.

**Comment by staminaloops** [comment]
So for production, we can use cheap-source-map or cheap-module-source-map. all we have to do is change the Webpack production configuration of the repo.

**Comment by TonyVeigel** [comment]
There doesn't need to be a solution right now.  eval-source-map is not supposed to be in production for various reason but yet it is and people continue to download this library. I can do a PR with it removed but @AllenFang  seems like he needs a solution first.

**Comment by staminaloops** [comment]
@TonyVeigel as I said, cheap-module-source-map can be used in production. I'm doing a PR and try to improve other things on the build system.

**Comment by AllenFang** [comment]
I'll merge #347(Provided by @staminaloops ) and release quickly.  Sorry for make this issue still remain.

**Comment by AllenFang** [comment]
Released on v2.0.3, the size reduce to about ~110 KB. @TonyVeigel, sorry for this issues that I dont fixed activity, I thinks there's something wrong actually but thanks @staminaloops fixed.  I'll close this issues, feel free to ask any question :)
