### ISSUE TITLE
how to access this.state from within onSelect

### ISSUE THREAD

**Issue by mikedevita** [AllenFang/react-bootstrap-table#326]
what is the *proper* way to handle a scenario like this?

I have a table of data, and i need to be able to select one or more and all and then click a button.

That button needs to then be able to get a list of all those selected items and do other actions using those selected items data.

I have a state like so
```
this.state = {
  selected: []
}
```
I was trying to access `this.state` from within the `onSelect: ()` but it doesn't like that. My thought was to check if `isSelected === true` and if it does, push/concat `row` into `this.state.selected` and do a splice/slice as needed to remove that given item from the selected array.

Then when the button is clicked I can just read from `this.state.selected`.

**Comment by AllenFang** [comment]
yes, your solution is ok, and the other is like this [tutorial](http://allenfang.github.io/react-bootstrap-table/advance.html#how-to-get-select). 

Feel free to discuss with me.
Thanks !

**Comment by mikedevita** [comment]
@AllenFang my solution doesn't fully work as I can't access this.state from within `onSelect()`. Would you be able to provide a working example of this?

**Comment by AllenFang** [comment]
@mikedevita, the following is my example
```js
export default class ExternallyManagedSelection extends React.Component{
  constructor(props){
    super(props);
    this.state = {
      selected: []
    };
  }

  handleClickBtn = () => {
    console.log(this.state.selected);
  }

  onRowSelect = ({id}, isSelected) => {
    if (isSelected) {
      this.setState({ selected: [...this.state.selected, id] });
    } else {
      this.setState({ selected: this.state.selected.filter(it => it !== id) });
    }
  }

  render(){
    var selectRowProp = {
      mode: "checkbox",
      clickToSelect: true,
      onSelect: this.onRowSelect,
      selected: this.state.selected
    };

    return (
      <div>
      <button onClick={this.handleClickBtn}>clickToShowSelectedRows</button>
      <BootstrapTable data={products} selectRow={selectRowProp} pagination={true}>
        <TableHeaderColumn dataField="id" isKey={true}>Product ID</TableHeaderColumn>
        <TableHeaderColumn dataField="name">Product Name</TableHeaderColumn>
        <TableHeaderColumn dataField="price">Product Price</TableHeaderColumn>
      </BootstrapTable>
      </div>
   );
  }
};
```

**Comment by AllenFang** [comment]
@mikedevita, btw, I know your problem, if you want to change ```state``` in ```react.js```, dont reference origin state and change value and set, it's a invalid way

**Comment by mikedevita** [comment]
@AllenFang how are you `bind(this)` to `this.onRowSelect`.. when I use your example, `this.state` is undefined as onRowSelect hasn't been bound to the component's `this`

adding a `console.log(this)` inside of `onRowSelect` you'll see that `this` is a reference to the row object, and not the component `this`.

![image](https://cloud.githubusercontent.com/assets/2991640/13677458/50c804ea-e6a7-11e5-8197-dac553c0f750.png)

**Comment by AllenFang** [comment]
it's strange, because ```onRowSelect``` is a arrow function, ```this``` should be the instance of ExternallyManagedSelection, 
you can try
```js
var selectRowProp = {
      mode: "checkbox",
      clickToSelect: true,
      onSelect: this.onRowSelect.bind(this)
    };
```

**Comment by mikedevita** [comment]
@AllenFang i've tried both :(

**Comment by AllenFang** [comment]
ok, just dont use arrow function, 
```
onRowSelect (row, isSelected) {
var id = row.id;
 if (isSelected) {
      this.setState({ selected: [...this.state.selected, id] });
    } else {
      this.setState({ selected: this.state.selected.filter(it => it !== id) });
    }
}
```

**Comment by AllenFang** [comment]
@mikedevita, I'm going to sleep, I think it's not a big problem, maybe something stuck, just leave message to tell me the result

Thanks you :)

**Comment by mikedevita** [comment]
ill continue this on gitter, i sent a message on there and mentioned you.

**Comment by AllenFang** [comment]
check gitter, if does not worked, give your full example and let me debug it.

**Comment by leandermelms** [comment]
I'm experiencing the same issue. @mikedevita @AllenFang , did you find the solution how to bind this to `onRowSelect`?

**Comment by AllenFang** [comment]
@leandermelms, try to bind this in constructor

**Comment by chisom5** [comment]
hi, i just enter this same isssue what should i do?

**Comment by GodAlmighty990** [comment]
I'm also having an issue accessing the state in onSelect. I will post my solution once found
