### ISSUE TITLE
How to make table wrap text automatically 

### ISSUE THREAD

**Issue by liqili** [AllenFang/react-bootstrap-table#327]
Hi,
How to make table wrap text automatically?

**Comment by markortiz** [comment]
maybe you can try to add css.

**Comment by liqili** [comment]
@markortiz due to the css below,add css to td didn't work.
`.react-bs-container .table-header > table > thead > tr > th .table-header-column{
  line-height: 25px;
  vertical-align: top;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
`

**Comment by markortiz** [comment]
you can overwrite / change it to your `react-bootstrap-table-all.css`
i think you can find it on `line:30`

**Comment by AllenFang** [comment]
@liqili, is it work by @markortiz 's solution?

**Comment by yenhsiac** [comment]
@AllenFang It works. But I saw some other issues. In my case, I have many columns. 
When I add more columns, some column header texts are gone.

<img width="1003" alt="screen shot 2016-03-11 at 9 04 04 am" src="https://cloud.githubusercontent.com/assets/679023/13709347/47fb0274-e768-11e5-8b86-1741ca72a277.png">

When I add more columns and the horizontal scrollbar appears, the columns headers are mis-aligned. I know there is another thread that you are addressing alignment problem. Will it fix this issue too?

<img width="1020" alt="screen shot 2016-03-11 at 8 55 45 am" src="https://cloud.githubusercontent.com/assets/679023/13709189/6c258508-e767-11e5-9d1a-2f485b1f742e.png">

Thank you!

**Comment by yenhsiac** [comment]
If I keep write-space:nowrap as it is, I encounter another mis-alignment issue:

<img width="1227" alt="screen shot 2016-03-11 at 9 10 52 am" src="https://cloud.githubusercontent.com/assets/679023/13709532/585f2900-e769-11e5-8fc6-b650c2593f0d.png">

**Comment by AllenFang** [comment]
@yenhsiac , try v2.0.0, and check #331

**Comment by liqili** [comment]
It's working fine at v2.0.0,thank you!
