### ISSUE TITLE
delay for the search feature

### ISSUE THREAD

**Issue by dana2208** [AllenFang/react-bootstrap-table#330]
Hi,

I think there should be a "searchDelay" property (500ms for default) for the search feature so that not each new "key down" triggers a search.
This will improve the search feature performance.
Of course this delay could be overwritten.

What do you think?

**Comment by AllenFang** [comment]
@dana2208, agree, it's a good suggestion, but I think the default is zero is better for the user who has been use search functionality.

**Comment by AllenFang** [comment]
@dana2208, we've support a delay on search, I thinks it a workaround for this issue. Check [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/debounce-search-table.js)
