### ISSUE TITLE
Screen remains dark after inserting row

### ISSUE THREAD

**Issue by Robinnnnn** [AllenFang/react-bootstrap-table#334]
First off let me begin by saying how awesome this library is!

For some reason when I insert a new row, **the screen remains dark after the modal closes**. A similar issue looks to be outlined here: #240. 

Here are a couple before-and-after [screenshots](http://imgur.com/a/ZF2oM). In order to make the screen normal I must click one more time.

Versions:
* react-bootstrap-table v2.0.0
* bootstrap CSS v3.3.6
* bootstrap JS v3.3.6
* jQuery v1.12.0

**Comment by AllenFang** [comment]
Thanks, I'll check this out, btw, what's the browser did you used? and the table is in the modal? or just in a panel or div?

**Comment by Robinnnnn** [comment]
Browser is Google Chrome.

I'm not sure what you mean by table being in the modal -- do you mind clarifying your last question?

**Comment by AllenFang** [comment]
sorry for a unclear description, I means the table is in a dialog([bootstrap modal](http://www.w3schools.com/bootstrap/bootstrap_modal.asp))?. Basically, I want to know your dom structure, because I think there's somthing wrong with dom but I can't figure out currently :)

**Comment by ahmedprohic** [comment]
I had this issue and that was because I had more than one table (in tabs) and they were using insert modal. Solution was to loop over modals using document.querySelectorAll("." + "moda-backdrop") and .click() on each of them in ToolBar.js -  handleSaveBtnClick function. Hope this helps.

**Comment by AllenFang** [comment]
hi all, I've solve this issue and will release in these day, btw, @ahmedprohic, what's the version of bootstrap did you used?

**Comment by ahmedprohic** [comment]
Bootstrap v3.3.6. Great, thank you very much @AllenFang for this awesome work.

**Comment by AllenFang** [comment]
Fixed on ```v2.0.1```, check it out :)
