### ISSUE TITLE
interacting with filters toggles column sort

### ISSUE THREAD

**Issue by DexterHaslem** [AllenFang/react-bootstrap-table#336]
If you have a column header setup with dataSort and a filter, messing with the filter continually toggles sort. for example:

    <TableHeaderColumn dataField="num" dataSort={true} filter={{ type: 'NumberFilter'}}>

I tried to fix by putting a check [here](https://github.com/AllenFang/react-bootstrap-table/blob/master/src/TableHeaderColumn.js#L19)

I tried checking if the target was this.refs["header-col"], however that is too restrictive, and clicking on span with column label would not sort. Any ideas on how to make filter + sort more usable?

**Comment by dana2208** [comment]
Maybe make sure that `event.target` (or a parent of `event.target`) has no class `filter`.

**Comment by DexterHaslem** [comment]
that is a good idea. do you know off top of your head if custom filter will have all children classed correctly?

**Comment by dana2208** [comment]
Hi @DexterHaslem ,
I didn't understand your question...
A custom filter is by definition a any react class that any programmer can add and that will render in the header. So the programmer is the one responsible for setting the appropriate classes in the render method.
I hope this answer your question, if no let me know.

**Comment by AllenFang** [comment]
@dana2208, I thinks just check the ```e.target.tagName```. only TD or SPAN will trigger sorting

**Comment by DexterHaslem** [comment]
I ended up using e.target.tagName and it works OK for now. I will submit pull request

**Comment by dana2208** [comment]
what if someone uses these tags in the custom filter?? I think this solution is not good enough...

**Comment by DexterHaslem** [comment]
yea of course, I agree it will especially come up with clicking on spans that im sure people will use in custom filters. maybe TH and SPAN with class name of filter too would make it tolerable?

**Comment by dana2208** [comment]
the solution that will always work is to check that no parent of the event target has a class "filter". Because all the filters have this class. For custom filters, programmers will have to know that they have to put a class filter on the most external div of their filter.
But it is weird because on my grid clicking on filter does not fire the sort event... Maybe this happens now with the bootstrap new version (v.2.0.0), @AllenFang ?

**Comment by DexterHaslem** [comment]
is that on custom filter? I still have it on built in filters on 2.0

**Comment by AllenFang** [comment]
@dana2208, yes right, but for the parent, I'm scare that user use more than one div or something like that to wrap the input field or selection etc this will make problem need to find parent to make sure "filter" class exist in parent. so how to make this solution more intuitive to solve?

btw, how about ```event.stopPropagation()```?
maybe I can use a div to wrap all filter and bind a click event on that div, when click in any element in that div, just call ```event.stopPropagation()``` to stop it

**Comment by AllenFang** [comment]
In addition, this issue only happened on v2.0.0, because [this](https://github.com/AllenFang/react-bootstrap-table/blob/v1.6.2/src/TableHeaderColumn.js#L77)
Filter is outside the div which only wrap header text and sort caret

**Comment by AllenFang** [comment]
Fixed on ```v2.0.2```.
