### ISSUE TITLE
Radio selection still remains

### ISSUE THREAD

**Issue by anilapu** [AllenFang/react-bootstrap-table#337]
Hi,

I am using RowSelection(single). I selected a row from search result then I cleared my search data again I did search, now I can able to see previously selected row. 
How can I unselect the selected row on clear?

**Comment by AllenFang** [comment]
@anilapu, I think this is not a issue, because selection is one of states in ```react-bootstrap-table```, no matter what's you did(search, page changed, filtering or sorting), the selection state is still remain. 
so for your question, how to unselect after cleaning search, you can try following examples:

```js

handleAfterSearch = (searchText, result) => {
  if (searchText === '') {
    this.refs.table.cleanSelected();
  }
}

render() {
  const options = {
     afterSearch: this.handleAfterSearch
  };

  const selectRow = {
     mode: 'radio'
  };
  
  return (
    <BootstrapTable ref='table' data={data} options={options} selectRow={selectRow}>
    ........
  );

}


```

**Comment by anilapu** [comment]
Thanks for response. Still same even though I followed your reference. **handleAfterSearch** is not firing.

`
constructor(props) {
    super(props);
    const { sectionsearch, dispatch } = this.props;
    this.state = sectionsearch;
    this.actions = bindActionCreators(SectionSearchActions, dispatch);
    this.onRowSelect = this.onRowSelect.bind(this);
    this.handleAfterSearch = this.handleAfterSearch.bind(this);
    this.selectRowProp = {
      mode: 'radio',
      clickToSelect: true,
      onSelect: this.onRowSelect
    };
  }

handleAfterSearch = (searchText, result) => {
    if (searchText === '') {
      this.refs.table.cleanSelected();
    }
  }


render() {
    const options = {
      afterSearch: this.handleAfterSearch
    };
    
    return (
           <BootstrapTable ref='table' data={this.props.sectionsearch.searchdata}
            options={options} selectRow={this.selectRowProp}>
                  <TableHeaderColumn dataField="attributeSectionId" isKey width="30%" dataSort>    Section ID</TableHeaderColumn>
                  <TableHeaderColumn dataField="AttributeSectionNames" width="60%" 
dataFormat=   {this._attributeSectionNameFormat} dataSort>Name</TableHeaderColumn>
             </BootstrapTable>
         }
  );
}
`

**Comment by AllenFang** [comment]
@anilapu, 1.0.0 is too old,  you can use 2.0.0. btw, in you code, you forgot add ```search={true}``` on ```<BootstrapTable>```

**Comment by AllenFang** [comment]
@anilapu, a question, did you handle search functionality by yourself? or you use internal search(provided by ```react-bootstrap-table```)?

**Comment by anilapu** [comment]
sure @AllenFang I will use updated one. I am handling search functionality.

**Comment by AllenFang** [comment]
@anilapu, ok, I understand, if you hand search by yourself, just use ```this.refs.table.cleanSelected();``` to clean selection states on table.

**Comment by sureshvarman** [comment]
@anilapu 
 this.refs.table.setState({selectedRowKeys: []});

**Comment by anilapu** [comment]
Thanks @AllenFang @sureshvarman for your suggestions. Now I can able to clear. I am using old version(1.0.0) so I have used `this.refs.table.setState({selectedRowKeys: []});`.

**Comment by AllenFang** [comment]
Good job and thanks @sureshvarman

**Comment by amitsetty** [comment]
cleanSelected seems not to be a function 
<img width="961" alt="Screen Shot 2020-03-27 at 11 46 26 AM" src="https://user-images.githubusercontent.com/32575407/77773944-af44af80-7020-11ea-8232-30e7d2ce46a9.png">
