### ISSUE TITLE
Pagination dropdown (results per page) won't work

### ISSUE THREAD

**Issue by nirhadassi** [AllenFang/react-bootstrap-table#338]
Hi,
Set `pagination={true}`.
The dropdown shows 10 and appears clickable but when clicked nothing happens.

Any solution?

**Comment by AllenFang** [comment]
@nirhadassi, any error on browser console? and what's version did you used and which browser?
btw, I think the problem is you forget to import bootstrap js in your application

**Comment by nirhadassi** [comment]
Hey @AllenFang, thanks for your quick replay.

That's what I'm using:
react-bootstrap-table 2.0.0
Google Chrome Version 49.0.2623.87

On my component page I imported:
`import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';`

On my html page I have:
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="..." crossorigin="anonymous">
<link rel="stylesheet" href="../style/react-bootstrap-table-all.min.css">

No console errors.
Am I missing anything?

**Comment by AllenFang** [comment]
I think you really missing the bootstrap js file

**Comment by nirhadassi** [comment]
Thanks,
Had to add  `<script src="//code.jquery.com/jquery-1.12.0.min.js"></script>` to my index.html.
Hoped I wouldn't have to include jQuery but I guess there's no escape! :)

**Comment by sgentile** [comment]
using jQuery shouldn't be needed for this component - we are having the same issue.

**Comment by sgentile** [comment]
(oh, and we are using react-bootstrap)

**Comment by juan0087** [comment]
having the same issue here. Did you guys find a solution yet?

The results per page dropdown does't do anything on click. The page buttons to the right do work.

![nkcfl](https://cloud.githubusercontent.com/assets/13401194/15005647/99b819ee-1184-11e6-99b2-f83a997d5b2b.png)

**Comment by AllenFang** [comment]
@juan0087, currently, you need to import bootstap.js and css. could you please confirm that :)

**Comment by juan0087** [comment]
Thanks for the reply @AllenFang! I think I have imported all the necessary files:

  <link rel="stylesheet" type="text/css" media="screen" href="/style/css/react-bootstrap-table-all.min.css">
  <link rel="stylesheet" type="text/css" media="screen" href="/style/css/bootstrap.min.css">
  <script src="/js/libs/jquery-2.1.1.min.js"></script>
  <script src="/js/react-bootstrap-table.min.js"></script>

Am I missing anything else?

**Comment by AllenFang** [comment]
if you're sure that you've import these files, so any repo for reproducing it? Thanks

**Comment by dariobanfi** [comment]
Same happening here!

**Comment by AllenFang** [comment]
@dariobanfi, give me a repo for me to reproduce this issue. BTW, ```v3.0.0``` is on developing, and we wont include bootstrap.min.js anymore in future.

**Comment by mad10341** [comment]
Hi,

Any date on when this pagination issue will be fixed. 
We are very fond of this component and we are looking to deploy it in a production site. But pagination is a funcamental requirement.
Also we noticed that performance (e.g. select one row) is not good when the number of items is greater than 1500. 
Any comments on this? is there a configuration option to tackle this?

keep up the good work

**Comment by AllenFang** [comment]
@mad10341, 

> Any date on when this pagination issue will be fixed.

did you have the same issue about the dropdown doesn't work?


> Also we noticed that performance (e.g. select one row) is not good when the number of items is greater than 1500.

it's a known issues, but I really have no time to fix it. sorry... so PR is welcome.

**Comment by jordanblink** [comment]
Still hitting the same issue with React-Bootstrap-Tablev4.0.
Using Create-React-App with Webpack and no easy way to import bootstrap.js into the project as we are not using jQuery.
Real bummer cz everything else works so well and I am using it on multiple projects.
Any workaround without needing me to import jQuery into my project?

**Comment by AllenFang** [comment]
now, `react-bootstrap-table` no need the `jQuery` and `bootstrap.js` anymore, if you still have this issue, please give a simple repo to reproduce it, thanks.

BTW, I also use `react-bootstrap-table` with `create-react-app` in my private project, the pagination is work well until now
