### ISSUE TITLE
Search field placeholder text

### ISSUE THREAD

**Issue by davebream** [AllenFang/react-bootstrap-table#34]
It would be really nice to be able to change the placeholder text in the search field (localization).

**Comment by AllenFang** [comment]
Hi @davebream , thanks your suggestion for this component, I'll spend some time on it. :)

**Comment by AllenFang** [comment]
HI @davebream , sorry for a long waiting, I've add this feature on <code>react-bootstrap-table</code>. You can change the placeholder text in search field as follow
<pre>
&lt;BootstrapTable data={products} search={true} searchPlaceholder={YOUR_TEXT} &gt;
...
&lt;/BootstrapTable&gt;
</pre>
