### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by arrb** [AllenFang/react-bootstrap-table#340]
Hello, 

Seems like the CSS doesn't work for pagination. I have imported <link rel="stylesheet" href="./css/react-bootstrap-table-all.min.css"> but I don't get the default buttons for pagination.

**Comment by AllenFang** [comment]
what's thing did you import, could you please give more detail information :)

**Comment by arrb** [comment]
yes sorry, I imported the CSS (react-bootstrap-table-all.min.css) the scroll bar works and it only shows me the 10 first values; however, the buttons that I am supposed to get at the bottom are missing, I don't get buttons I only get a list.

**Comment by AllenFang** [comment]
did you enable ```search={true}```? and any error on browser console?

**Comment by arrb** [comment]
no errors on console. 
`<BootstrapTable data={this.state.data} pagination={true} search={true}>
      <TableHeaderColumn dataField="name" isKey={true}>Name</TableHeaderColumn>
      <TableHeaderColumn dataField="name">Name</TableHeaderColumn>
      </BootstrapTable>
`

Everything works fine, the only thing is the CSS for the pagination buttons. Do you know what am I missing? Do I have to import something else?

**Comment by arrb** [comment]
I do not want to search it's just the default pagination sample. Sorry for any misunderstandings

**Comment by AllenFang** [comment]
@arrb, so you means you did not see any the pagination list or page button? it's wired, what's bootstrap version and ```react-bootstrap-table``` did you used?

**Comment by arrb** [comment]
https://cloud.githubusercontent.com/assets/9982963/10610837/e00a8c68-7749-11e5-92da-0bd443989903.png
I can't see that (click on click above) I downloaded react-bootstrap-table today. I have these versions: 

    "react-bootstrap": "^0.28.3",
    "react-bootstrap-table": "^2.0.0",

I know it seems odd to me too, I really can't see where my error is.

**Comment by AllenFang** [comment]
@arrb, did you have any repo or fully example which can reproduce this issue? btw, ```react-bootstrap-table``` have no any dependency on ```react-bootstrap``` :)

**Comment by arrb** [comment]
Okay I am just trying to think of every single possibility. 
I don't have the repo right now, but everything works perfectly. I get all the data from a server, even sort works it's just the styling for pagination... Well it's okay thanks for helping anyways

**Comment by AllenFang** [comment]
@arrb, really? I think there must some thing stuck and maybe is a bug. however please tell me how did you solve. If you can't solve it, feel free to give your repo or examples. so I will close this issues until this issue could be confirm.

Thanks, feel free to ask anything :+1:

**Comment by arrb** [comment]
Hi, 

I "fixed it" just by adding my own css, but I still would like to know what's wrong. Here is a link to my repo: https://github.com/arrb/reduxSample

**Comment by AllenFang** [comment]
> by adding my own css

is [this](https://github.com/arrb/reduxSample/blob/master/src/components/employeeUI/employeeCSS.css)?

**Comment by arrb** [comment]
yes, my question is just if you know why the default css doesn't work for pagination? is there something I did wrong?

**Comment by AllenFang** [comment]
ok, I will spend some time to figure out :) Thanks your feedbacks

**Comment by LudiLi** [comment]
Same here, default css doesn't work in pagination part. I also import css and version I use is React-bootstrap-table 4.0.2

**Comment by idoromm** [comment]
Same issue here pagination CSS looks weird and does not work properly.
