### ISSUE TITLE
Is that possible to restrict the user input when edit the cell?

### ISSUE THREAD

**Issue by eric379990** [AllenFang/react-bootstrap-table#342]
Hi Allen,

Is that possible to restrict the user input when edit the cell? for example, restrict the user only can input numbers when edit the Age column.

thanks a lot.
BR/Eric

**Comment by AllenFang** [comment]
@eric379990, sorry, there are only ```select```, ```checkbox``` and ```textarea``` on cell edit. Maybe provide a beforeSaveCell function for you to valid?  is that helpful to you? or any ideas? :)

**Comment by eric379990** [comment]
@AllenFang beforeSaveCell helps, I can check the value by myself, wish you can add that if you have time:)

thanks!

**Comment by AllenFang** [comment]
@eric379990, sure, I'll support it in near future :)

**Comment by AllenFang** [comment]
@eric379990, Released on ```v2.0.2```. check [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/cell-edit/cell-edit-hook-table.js)
