### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by ernestocr** [AllenFang/react-bootstrap-table#343]
Thanks for the great work, I was wondering if there is a way (or will be) for making the buttons, filter and modal have a different language?

**Comment by AllenFang** [comment]
#85 is same as this issue, currently, I've no any plan for support language, because the next step for me is tuning the performance in large table. After it, i will consider hardly for supporting language. Sorry and close this issue due to duplicate. Btw, PR is welcome :+1:
