### ISSUE TITLE
Determining row from cell context

### ISSUE THREAD

**Issue by jeffdh5** [AllenFang/react-bootstrap-table#344]
I am using react-bootstrap-table and heavily customizing the formatter to support my web app needs. So far, this has been a breeze to get started in!

Below, I have some cells with buttons, and when the user clicks the button, it will open up a modal that allows the user to make edits. Once the user makes those edits, I need to go back into the correct and propogate the update. What's the best way to do this? I have a screenshot below to help explain my needs.

<img width="955" alt="screen shot 2016-03-20 at 10 54 17 pm" src="https://cloud.githubusercontent.com/assets/3132718/13911496/c368ac62-eeee-11e5-97af-ccd6c50f8187.png">

**Comment by AllenFang** [comment]
> I need to go back into the correct and propogate the update

What's that means? You means what's the best practices for how to update cell data programmatically?

**Comment by jeffdh5** [comment]
Sorry unclear wording! I am indeed asking for best practices behind updating cell data programmatically.

Let's say a user clicked "Edit Product Settings", and changed "Note Setting" to "Edited Note Setting." I need to find the correct row/cell associated with those edits.

**Comment by AllenFang** [comment]
@jeffdh5, if you used column format, ```react-bootstrap-table``` will pass the ```cell``` and ```row``` for you to customize. I think you can use row id to find the row which user edited.

**Comment by jeffdh5** [comment]
Got it, that helps.

I also was wondering - are key's modifiable? If I change the keys on the parent state what will happen to the table?

**Comment by AllenFang** [comment]
in client side(inside your compoent), I think you can do anything on your data(include key filed), if you change key, just means an change on id, there's no another new row show on the table.
