### ISSUE TITLE
How to implement clear table, without getting rid of headers?

### ISSUE THREAD

**Issue by jeffdh5** [AllenFang/react-bootstrap-table#345]
In my current approach, I have a reference to my table from a parent React class, via the "refs" tag. When I need to clear my list, I am calling this:

this.refs.table.setState({data: []}). 

This seems to also end up deleting the headers. Am I doing something wrong? Is there built in method that allows me to do this clearing? 

Not sure if related, but I find that after using this hack to clear my table, and I add in another row, it gives me all the entries that were ever added to the table (even previously cleared ones).

**Comment by AllenFang** [comment]
The best way is use ```data={this.props.data}``` in ```<BootstrapTable>```, ```this.refs.table.setState({data: []})``` is good also. 
btw, you should hold your table data in parent component, and pass as a ```prop``` to table, I think it's more better.

> Not sure if related, but I find that after using this hack to clear my table, and I add in another row, it gives me all the entries that were ever added to the table (even previously cleared ones).

Maybe it's a bug, I can try it out. however, It maybe caused by a wrong states control or something like that. Could you please give a simple example for me to reproduce?

**Comment by jeffdh5** [comment]
Here's an example: http://pastebin.com/WtrfF7aR

Note that I'm calling your method, handleAddRowAtBegin, rather than modifying the parent state directly. Is this possibly what's causing the problem?

**Comment by AllenFang** [comment]
@jeffdh5, I'll try it out after I get off work. Thanks !!

**Comment by jeffdh5** [comment]
Hey Allen, I have figured it out. Thanks for the advice!

I stopped using your method, handleAddRowAtBegin, which operates on the table's state which was copied from the original parent state. Instead, I just managed the data myself which worked out much better (and is also more intuitive).

**Comment by AllenFang** [comment]
@jeffdh5, good job. BTW, i don't suggest to set state of table directly, but the header disappear when give empty data is a bug, I'll fix it. Thanks :)
