### ISSUE TITLE
Unresponsive page when searching large tables

### ISSUE THREAD

**Issue by JeremyFossTemple** [AllenFang/react-bootstrap-table#349]
If the table is large then the page becomes unresponsive during search.  Maybe consider offloading search to a webworker, or searching for a set amount of time, then window.setTimeout(continueSearch)

**Comment by AllenFang** [comment]
@JeremyFossTemple, yes, its a performance issue on table search, #330 have asked a delay when user  want to search, I'll done this tuning in next version. About the performance issues, I'll try to solve in near future. Thanks :)

**Comment by AllenFang** [comment]
@JeremyFossTemple, we've support a delay on search, I thinks it a workaround for this issue. Check [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/debounce-search-table.js)
