### ISSUE TITLE
Filtering Options

### ISSUE THREAD

**Issue by raybooysen** [AllenFang/react-bootstrap-table#35]
Hi there

If you have selection enabled, and then you filter, there doesn't seem to be a hook to either:
1) De-select the items that are not part of the filtered set
2) Retrieve the current set of selected items.

This is useful when, for example, you filter and want to act on the filtered set.  Also, if you've select n items, filter that set down to n-5 (for example), then n items are still selected.  How do we determine what the user is seeing on screen?

Thanks for a good product!

**Comment by AllenFang** [comment]
Hi @raybooysen, I probably understand your question, sorry for my poor english ;( 
My answer for your question as follow one by one : 

1) Currently, maybe it's hard to de-select the items which not show in the table after filtered on this component and I will not implement such feature currently, maybe in future. :)

2) Retrieve the current selected item, this component can provide some callback for you and if item selected, you can get selected item and keep it in your client program. 

Anyway, I'm glad that you give these idea for me. Thanks :)
