### ISSUE TITLE
column header and body width out of align

### ISSUE THREAD

**Issue by lebeier** [AllenFang/react-bootstrap-table#351]
I read that in v2.0.0 this issue should have been fixed.
However, I am still seeing the width of column header is not aligned to the body.

**Comment by AllenFang** [comment]
@lebeier, could you please give more information? browser? example code? any horizontal bar? did you set column width? Did you replace ```react-bootstrap-table-all.css``` when upgrade?  if you give these information, I think I can help you, maybe it's a bug

Thanks :)

**Comment by lebeier** [comment]
I have just updated the css according to what you have mentioned. Still the alignment issue exist.
The browser used is chrome/firefox(doesnt work in both)


                 <Tabs defaultActionKey={1} className='mana-tab-container'>
                      <Tab eventKey={1} title='Virtual Devices'>
                          <div id='virtual_devices_dt'>
                              <BootstrapTable data={this.state.virtualDevicesDataSet} striped={true} hover={true} search={true} pagination={true} exportCSV={true}>
                                  <TableHeaderColumn isKey={true} dataField='device_id' width={'60'} >ID</TableHeaderColumn>
                                  <TableHeaderColumn dataField='mac_address'>MAC</TableHeaderColumn>
                                  <TableHeaderColumn dataField='device_name'>Device Name</TableHeaderColumn>
                                  <TableHeaderColumn dataField='user_name'>User</TableHeaderColumn>
                              </BootstrapTable>
                          </div>
                      </Tab>
                      <Tab eventKey={2} title='Physical Devices'>
                          <div id='physical_devices_dt'>
                             <BootstrapTable data={this.state.physicalDevicesDataSet} striped={true} hover={true} search={true} pagination={true} exportCSV={true}>
                                 <TableHeaderColumn isKey={true} dataField='device_id' width={'60'}>ID</TableHeaderColumn>
                                 <TableHeaderColumn dataField='mac_address'>MAC</TableHeaderColumn>
                                 <TableHeaderColumn dataField='name'>Device Name</TableHeaderColumn>
                                 <TableHeaderColumn dataField='type'>Type</TableHeaderColumn>
                                 <TableHeaderColumn dataField='mode_type'>Mode</TableHeaderColumn>
                                 <TableHeaderColumn dataField='status_type'>Status</TableHeaderColumn>
                                 <TableHeaderColumn dataField='action'>Action</TableHeaderColumn>
                             </BootstrapTable>
                         </div>
                     </Tab>

**Comment by AllenFang** [comment]
@lebeier, did you read #331 according to the README.md ? your table is in the tab(```react-bootstrap```). So did you call ```forceupdate``` if tab changing at first time? The reason and explanation is all in the #331 :)

**Comment by lebeier** [comment]
Ok I have just did what is mentioned too. the alignment only corrects after selecting the tab on the 2nd try. The first forceUpdate did not make it align.

**Comment by AllenFang** [comment]
@lebeier, did you enable ```animation``` on ```tab```, I remember default is true, so if you have animation on tab, remember to call ```forceupdate``` on async way(ex: settimeout). In this [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/others/table-in-tabs.js), I've gave some description on it. Try it !  :)

**Comment by AllenFang** [comment]
Like I said in #331, it's a workaround, because I can't calculate the actual width in hidden tab ;(

**Comment by lebeier** [comment]
ok now it is working. Thanks for the help. But I think the workaround is really hackish. xD

**Comment by AllenFang** [comment]
@lebeier, ya~~ but if you disable animation, you can drop the async call, it will be more intuitive :)  btw, welcome any solution on it :+1:
