### ISSUE TITLE
handleConfirmDeleteRow needs rowId param

### ISSUE THREAD

**Issue by invalidred** [AllenFang/react-bootstrap-table#355]
Hi Allen,

Thanks for the amazing component.

I am having a small issue when deleting a row. I need to first delete a row by calling the API and if the operation is successful, I then need to delete it in the react-bootstrap-table.

Currently there are 2 callbacks available around deleting a row
1. afterRowDelete: callback after row is deleted in UI
2. handleConfirmDeleteRow: callback before row is deleted in UI

I would like to make the API call in handleConfirmDeleteRow to delete the data and if that happens successfully then the store will get updated which will render the UI with correct data.

The problem is, handleConfirmDeleteRow currently does not provide rowID which is required to make API call.

I could call afterRowDelete method and then make API call, but the issue with that is, if the API call fails, the state still has that row, however in the UI the row deleted.

**Comment by AllenFang** [comment]
@invalidred, ok, I can give you the rowKey as param on handleConfirmDeleteRow callback function at next version:)

btw, I can give you another solution on this condition, maybe it's more intuitive. That's said, 

1. Dont use embedded deletion(Just disable by```deleteRow={false}```)
2. Add a custom button for row deletion
3. When user click that button, use ```this.refs.table.state.selectedRowKeys``` to get all selected row for deletion
4. call your API to delete these data and refresh your store(flux)
5. No matter wha't happend, just render table again based on your store.

Thanks:)

**Comment by invalidred** [comment]
Yes that solution works. Thank you very much Allen.

**Comment by AllenFang** [comment]
@invalidred, nice. anyway, I'll pass the rowKey as param in next version :)

**Comment by AllenFang** [comment]
Released on ```v2.1.0```. Thanks :)  Check [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/del-row-custom-confirm.js)
