### ISSUE TITLE
The checkbox next to ID should be empty if there is no data in table.

### ISSUE THREAD

**Issue by geekbosszhang** [AllenFang/react-bootstrap-table#359]
Hi, @AllenFang the default behavior of checkbox next to the ID is checked when there is no data.
![image](https://cloud.githubusercontent.com/assets/7484001/14038838/d867d02a-f290-11e5-863a-9af6ca6a939b.png)
In the src/BootstrapTable.js file, I saw the code below
![image](https://cloud.githubusercontent.com/assets/7484001/14038885/35e0ba96-f291-11e5-8dfe-efddb25c892b.png)
I think maybe we could modify the code to make the checkbox  empty if there is no data in table.
Thanks a lot.

**Comment by madeinfree** [comment]
Hi, @geekbosszhang this is my solution, I think it can improved your problem, but it will waiting for the @AllenFang to review the code.

**Comment by AllenFang** [comment]
@geekbosszhang, this issue has been fixed on ```v2.1.0```.  Check it out
