### ISSUE TITLE
Warning rendering TableHeader

### ISSUE THREAD

**Issue by raybooysen** [AllenFang/react-bootstrap-table#36]
When I render the grid, I get the following warning:

 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of TableHeader. It was passed a child from Grid. See https://fb.me/react-warning-keys for more information.

**Comment by raybooysen** [comment]
Using version 0.9.10

**Comment by AllenFang** [comment]
Hi @raybooysen , I know these warning message, and somebody also raise these <a href="https://github.com/AllenFang/react-bootstrap-table/issues/25">issues</a>. However, I'll solve it. Thank you for reminding me.

**Comment by raybooysen** [comment]
np
