### ISSUE TITLE
table search doesn't work sometimes

### ISSUE THREAD

**Issue by edwardwang0302** [AllenFang/react-bootstrap-table#363]
Hi,allen
For example, I want to search "abc", and I type "abc"  in search input it works. But when I type "abcd" and press backspace it can be matched any more

**Comment by AllenFang** [comment]
@edwardwang0302, if you type something separated with a space string(ex: abc de), this pattern will trigger a multi search functionality. in your case 'abcd ', the last backspace will be a search pattern for us.

**Comment by edwardwang0302** [comment]
@AllenFang Thanks for ur answer, but u may misunderstood. I want to match 'abc' but  type wrong string 'abcd' and then delete the last letter 'd',  then it can't match 'abc' any more.

**Comment by AllenFang** [comment]
@edwardwang0302, sorry, my fault. I take backspace as whitespace. lol.  I'll check this out again

**Comment by edwardwang0302** [comment]
@AllenFang Thanks again, sorry for my poor English by the way.

**Comment by AllenFang** [comment]
@edwardwang0302, I figure out. because the table search is depend on current data which display on table, but I thinks it's not very intuitive for user. Maybe I'll improve it in near future.

**Comment by AllenFang** [comment]
BTW, for your case, if you type wrong text for searching, you need to cancel it and type again

**Comment by AllenFang** [comment]
Released on ```v2.1.0```. Thanks :)

**Comment by edwardwang0302** [comment]
@AllenFang Thank u
