### ISSUE TITLE
Big amount of data

### ISSUE THREAD

**Issue by valinol** [AllenFang/react-bootstrap-table#37]
I need tables with bit amoun of data(50 colums or more) i try to make add bootstrap table and the result is this, my question is that if this table is prepared to bit amount of columns or not.

![screenshot - 270815 - 13 01 40](https://cloud.githubusercontent.com/assets/12271588/9518962/4353744c-4cbb-11e5-8868-5ad539d7d04d.png)

Here you can see my code:
![sin nombre](https://cloud.githubusercontent.com/assets/12271588/9519089/0a755a22-4cbc-11e5-8786-ce5bb0ad7f83.png)

**Comment by AllenFang** [comment]
Hi @valinol, this problem I doesn't have any idea currently. Maybe in the future.
