### ISSUE TITLE
Can not add new record when setting insertRow=true

### ISSUE THREAD

**Issue by simozhan** [AllenFang/react-bootstrap-table#370]
Hi, I am running into an issue when using insertRow={true}. when i add this property, i can see the blue "New" button, but after i click the button, there is no pop up to add a new record and it seems no error and warning.

Using:
"jquery": "~2.1.4"
"react": ">=0.13.3"
"react-bootstrap": ">=0.23.5"
"react-bootstrap-table": "^2.1.0"

By the way, the deleteRow is ok for me.

the snippet is: 
```
ReactDOM.render(
<BootstrapTable data={contacts} insertRow={true} deleteRow={true} options={tableOptions}>
<TableHeaderColumn dataField="component" dataAlign="center" isKey={true} editable={false}>Component</TableHeaderColumn>
<TableHeaderColumn dataField="release" dataAlign="center" editable={false}>Release</TableHeaderColumn>
<TableHeaderColumn dataField="email" dataAlign="center">Email</TableHeaderColumn>
<TableHeaderColumn dataField="role" dataAlign="center">Contact Role</TableHeaderColumn>
</BootstrapTable>, 
document.getElementById('app') );
```

Would appreciate any help on the issue!

**Comment by madeinfree** [comment]
Hi @simozhan 
1. may I have other information ? The pop up work in this simple test repo, you can try it.
https://github.com/madeinfree/bootstrap-table-test-repo,

2. you setting the component `editable={false}` and set `iskey={true}` , I think you would get error by empty value.

**Comment by AllenFang** [comment]
@simozhan, did you import ```bootstrap.js``` or ```bootstrap.min.js```?

**Comment by simozhan** [comment]
Thanks @madeinfree and @AllenFang I imported bootstrap.min.css. this is my html file.

`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Contact Browser</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="css/react-bootstrap-table.min.css">
    <link rel="stylesheet" href="css/spinner.css">
    <link rel="stylesheet" href="css/app.css">
  </head>
  <body>
    <div id="app"></div>
    <script type="text/javascript" src="build/bundle.js">
    </script>
  </body>
</html>
`

**Comment by AllenFang** [comment]
@simozhan, I think you still forgot ```bootstrap.js``` or ```bootstrap.min.js``` (javascript file) :)

**Comment by simozhan** [comment]
Ah. yes @AllenFang . i add bootstrap.min.js and it works now. Many many thanks

**Comment by AllenFang** [comment]
Great!
