### ISSUE TITLE
[ Table Sort ] Table is sorted to default options when table is updated

### ISSUE THREAD

**Issue by markortiz** [AllenFang/react-bootstrap-table#372]
Hi @AllenFang,

I just saw this now. By default my table was sorted by `name` in `ascending order` and when I sort it by `code` or other columns it will sort properly. 

But when the `table` is been `updated` it will sort again by the default column `name`. 

![kc0onr8yt2](https://cloud.githubusercontent.com/assets/1829168/14131169/54e87a9a-f66b-11e5-822d-e3232b6993e1.gif)

By default i have an options inside my render:
```
render() {
    let options = {
      sortName: 'name',
      sortOrder: 'asc'
    }
    return (
      <BootstrapTable data={ items} options={ options } striped={true} hover={true} ref='rbsTable'>
      ...
      </BootstrapTable>
    )
```

What happen when I click on the `gear icon` is I'll fetch the `sub menus` of each `item` from the `server`.

**Comment by AllenFang** [comment]
@markortiz, it's wired, when you sort the ```Code```, the ```Actions``` also been sorted, so could you give your ```<TableHeaderColumn>``` setting?  I guess the ```Code``` and ```Action``` share the same ```dataField```

**Comment by markortiz** [comment]
@AllenFang yes, the `code` and `actions` columns are sharing the same `dataField` but this issue is also occur when I sort different `columns` that have different `dataField`.

**Comment by AllenFang** [comment]
ok, could your please give me a simple examples? I want to reprdouce this issue on my site. Thanks :)

**Comment by markortiz** [comment]
I think it has something to do with `render()`.
I guest every time there is a `componentDidUpdate()` it will call again the `render()` then display table to it's default sorted column.

```
 getActionLink( data) {
   // fetch something to 
    Actions.fetchSomeData()
  }

actionsFormat ( id, data) {
    return <a className='gameroundsLink' onClick={ this.getActionLink.bind( null, data) }>link</a>
  }
render() {
    let options = {
      sortName: 'name',
      sortOrder: 'asc'
    }
    return (
      <BootstrapTable data={ items} options={ options } striped={true} hover={true} ref='rbsTable'>
         <TableHeaderColumn dataField='name' isKey={ true }  dataSort={true} >Name</TableHeaderColumn>
         <TableHeaderColumn dataField='id' dataSort={true}>Code</TableHeaderColumn>
         <TableHeaderColumn dataFormat={ this.actionsFormat }  dataField='id'>Actions</TableHeaderColumn>
      </BootstrapTable>
    )
}
```

**Comment by AllenFang** [comment]
> I guest every time there is a componentDidUpdate() it will call again the render() then display table to it's default sorted column.

Exactly right

I'll check this out when I get off work, Thanks :)

**Comment by AllenFang** [comment]
@markortiz, I've solved the same field name sorting problem(*I'll release on next version*). But you said the problem also occur sort when different columns that have different dataField, I can't reproduce it, so maybe you can provide a actually example for me to debug :)

Second, because you give a default sort information on ```render``` method, so if any state change, will get the default sort again, there are two way to avoid it

1. You can handle sort by yourself(In your component). Please check this [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/sort-hook-table.js) to see how to handle sort on your component

2. Use a flag to avoid the default sort on each render, Through ```onSortChange```, you can get sort info. So  if you got the first sort on table, just set a flag and avoid to use default sort on table.

For both solution, the first is best. So I thinks you can improve your code.

Feel free to ask any question :)
Thanks!

**Comment by markortiz** [comment]
Cool! Thanks for this @AllenFang  :)

**Comment by AllenFang** [comment]
@markortiz, release on ```v2.1.1```. Check it out :)

If the problems still remain, please tell me, thanks

**Comment by markortiz** [comment]
@AllenFang how can I set a default sorted column on first load?

**Comment by markortiz** [comment]
@AllenFang never mind this. It was fix on `v2.1.1`. 
Thank you so much! :+1:

**Comment by markortiz** [comment]
@AllenFang is there any way can I set a default sorted column on first load?

**Comment by AllenFang** [comment]
@markortiz, sorry for lately reply....  too many things need to do.

Following examples does not work for you?
```js
export default class SortHookTable extends React.Component {
  constructor(props) {
    super(props);

    this.state = {   //default sort
      sortName: 'name',
      sortOrder: 'asc'
    };

    this.options = {
      onSortChange: this.onSortChange.bind(this)
    };
  }

  onSortChange(sortName, sortOrder) {
    console.info('onSortChange', arguments);
    this.setState({
      sortName,
      sortOrder
    });
  }

  render() {
    return (
      <div>
        <p style={ { color: 'red' } }>sort: sortName={ this.state.sortName }, sortOrder={ this.state.sortOrder }</p>
        <BootstrapTable data={ products } options={ this.options }>
          <TableHeaderColumn dataField='id' isKey={ true } dataSort={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name' dataSort={ true }>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
        </BootstrapTable>
      </div>
    );
  }
}
```

**Comment by AllenFang** [comment]
BTW, I've plan to design a new mechanism to set default sort, I'll implement i in the recent. Check [this](https://github.com/AllenFang/react-bootstrap-table/pull/385)

**Comment by markortiz** [comment]
@AllenFang yes, it does not work for me. Even I set it on the constructor.

**Comment by AllenFang** [comment]
it's wired..  I'll try it later. what's version did you used?

**Comment by markortiz** [comment]
@AllenFang  `v2.1.1` :)

**Comment by AllenFang** [comment]
@markortiz, sorry it's a bug but I need to trace to find when this feature broken. Anyway, I'll fix it in these day. Sorry again ;(

**Comment by markortiz** [comment]
Alright, thanks again @AllenFang :)

**Comment by AllenFang** [comment]
@markortiz, sorry for a wrong direction, I'm so tired...

try follow code
```js
export default class SortHookTable extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      sortName: 'name',
      sortOrder: 'desc'
    };
  }

  onSortChange(sortName, sortOrder) {
    console.info('onSortChange', arguments);
    this.setState({
      sortName,
      sortOrder
    });
  }

  render() {
    const options = {
      sortName: this.state.sortName,
      sortOrder: this.state.sortOrder,
      onSortChange: this.onSortChange.bind(this)
    };
    return (
      <div>
        <p style={ { color: 'red' } }>sort: sortName={ this.state.sortName }, sortOrder={ this.state.sortOrder }</p>
        <BootstrapTable data={ products } options={ options }>
          <TableHeaderColumn dataField='id' isKey={ true } dataSort={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name' dataSort={ true }>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
        </BootstrapTable>
      </div>
    );
  }
}
```

Anyway, I'll change the default sort mechanism in near future.

**Comment by AllenFang** [comment]
@markortiz, but after new mechanism released, I promise the legacy way will be compatible

**Comment by AllenFang** [comment]
@markortiz, sorry for lately reply. In ```v2.1.3```, you can handle default sort more intutive.

check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/default-sort-table.js) to learn how to set default sort

**Comment by markortiz** [comment]
@AllenFang cool! Thanks for this! I'll try to implement this next week.

**Comment by Nandiniyadavraj** [comment]
hey! I want to display cost of table in desc order but isn't working while when applying same code for other column working properly. 

           defaultSort: [{
                dataField: 'value',
                order: 'desc'
            }]

I'm not getting why, If anybody have solution for this plz tell soon. Thank you.
