### ISSUE TITLE
"There is no data to display" - can this message be turn off or displayed on a timer?

### ISSUE THREAD

**Issue by dukedougal** [AllenFang/react-bootstrap-table#374]
The problem is that this message is immediately displayed and of course it takes a second or two for the ajax to complete and the data to display so it is a little jarring to always see that "there is no data to display" when actually it's coming.

What do you think?

thanks!

**Comment by AllenFang** [comment]
@dukedougal, yes you r right. But how about start to render the table after component receive the data?

**Comment by dukedougal** [comment]
Yes, rendering the table after I have the data seems like a good idea although I'm happy with the way it works right now.

One thing to note as well is that if I set the options like this:

    var options = {
      noDataText: ''
    };

Then  the default noDataText displays because it must be doing a "null or value" somewhere when it decides what to display.

**Comment by AllenFang** [comment]
@dukedougal, the warning is cause of ```noDataText``` accept string only. Anyway, I thinks ```noDataText``` should be work well. But  because you assign a empty string to it and I valid the display text like following:
```{ this.props.noDataText || Const.NO_DATA_TEXT }```

so maybe you can assign with a string with a space, like ' ', not ''

**Comment by dukedougal** [comment]
Hi Allen
Would you mind allowing values other than text & clearing the warning please so I can use the spinner code shown above without warnings?

thanks

**Comment by AllenFang** [comment]
@dukedougal, sure, I can make ```noDataText``` accept a text or a JSX.  I'll support this feature in neat future :)

Thanks

**Comment by dukedougal** [comment]
Thanks!

**Comment by AllenFang** [comment]
@dukedougal, on newest ```v2.1.1```, you can try following setting without any warning
```
var options = {
  noDataText: (<i className="fa fa-circle-o-notch fa-spin" style={{'fontSize': '24px'}}></i>)
};
```

**Comment by dukedougal** [comment]
thanks!
