### ISSUE TITLE
Column header title shows "[object Object]" instead of header text

### ISSUE THREAD

**Issue by kolyabokov** [AllenFang/react-bootstrap-table#376]
Hi,
After adding title to column header in 2.0.1 (https://github.com/AllenFang/react-bootstrap-table/commit/68efb4334cd6ad601f3de3e4c7bf149fb06f6261),  when I mouse over table header it shows "[object Object]".
It happens when `<TableHeaderColumn>` has nested elements, not plain text, e.g.
`<TableHeaderColumn><FormattedMessage id="my.header.text" /></TableHeaderColumn>` or `<TableHeaderColumn><span>Col Title</span></TableHeaderColumn>`.
Pls fix

**Comment by AllenFang** [comment]
> It happens when has nested elements, not plain text, e.g.

could you please show me an example? Thanks :)

**Comment by kolyabokov** [comment]
@AllenFang, sorry, it the site ate my code in the comment text, fixed now

**Comment by AllenFang** [comment]
@kolyabokov, I thinks this issues is hard to fixed, because I never know what's element or text or something inside the ```TableHeaderColumn```. So I dont want to fixed it, but I can support a ```title``` props on ```TableHeaderColumn``` to let you control the title on header column. How about that?

**Comment by kolyabokov** [comment]
@AllenFang, I don't need title on header column at all :) I just don't want it to show [object Object] on hover. Maybe you can add a simple check of the type of `this.props.children`, and do not show the title if it is not a string?

**Comment by AllenFang** [comment]
@kolyabokov, surely, I can add a validation on it at next version :+1:

**Comment by AllenFang** [comment]
@kolyabokov, release on ```v2.1.1```. Check it out :+1:

**Comment by kolyabokov** [comment]
@AllenFang, great. Thank you for quick fix!
