### ISSUE TITLE
Date filter with comparators

### ISSUE THREAD

**Issue by 0riesok** [AllenFang/react-bootstrap-table#377]
Is there way to implement date filter using comparators (>, =, >=, <, <=)?

**Comment by AllenFang** [comment]
@0riesok, I think we can try to support this in near future.

**Comment by 0riesok** [comment]
It would be perfect. Thanks

**Comment by AllenFang** [comment]
@0riesok, I'll close it after this issues be fixed :) Thanks

**Comment by AllenFang** [comment]
@0riesok, fixed on ```v2.1.3``` :)

**Comment by 0riesok** [comment]
I'm now working on my diploma thesis so I can't try it now :( But I'll look on it in the end of this month.
And really thank you. :)
