### ISSUE TITLE
columnFilter at top

### ISSUE THREAD

**Issue by mikeerickson** [AllenFang/react-bootstrap-table#378]
As per documentation:

```
columnFilter : Bool
Enable column filter by setting columnFilter to true, default is false.
If enabled, there're input text field per column under the table, user can input your filter condition by each column.
```

Is there an option for placing the filter bar at top of table (say between header and first row of data?

**Comment by gvikei** [comment]
@mikeerickson Could you please point me to where "Advanced Filter" is? I searched through the repo but couldn't find it. Thanks!
