### ISSUE TITLE
Table Search

### ISSUE THREAD

**Issue by valinol** [AllenFang/react-bootstrap-table#38]
When you try to search a value in a table, if this table have null values in field, the search doesnt works. The problem that i found is  in the file tabledatastore.js:
    search: {
      value: function search(searchText) {
        if (searchText.trim() === "") {
          this.filteredData = null;
          this.isOnFilter = false;
          this.searchText = null;
        } else {
          this.searchText = searchText;
          this.filteredData = this.data.filter(function (row) {
            var valid = false;
            for (var key in row) {
              if (row[key].toString().toLowerCase().indexOf(searchText.toLowerCase()) !== -1) {
                valid = true;
                break;
              }
            }
            return valid;
          });
          this.isOnFilter = true;
        }
      }
    },

And it can be solved just checking that the value is not null before the toString.

**Comment by AllenFang** [comment]
Hi @valinol , thanks your contributions, I've fixed this issues on newest version.
