### ISSUE TITLE
Can not set item in "+New" when setting the column attribute editable={false}

### ISSUE THREAD

**Issue by simozhan** [AllenFang/react-bootstrap-table#380]
Hi,

When i set a TableHeaderColumn's attribute editable={false}, i can not set the value in new item.
My expectation is i can not edit the column in the table, but when i want to add a new record, i can input value for the column.

Much appreciation for any help.

**Comment by simozhan** [comment]
It seems my issue is the same with this one [](https://github.com/AllenFang/react-bootstrap-table/issues/226). So do we have any plan for this feature in near future?

**Comment by AllenFang** [comment]
@simozhan, I know this condition, This rule I follow the ```jqgrid``` and ```DataTables``` which are both familiar jQuery table component.  But I think I can do some improvement like setting a ```prop``` to make you to choose the ```editable``` condition when adding row.

**Comment by simozhan** [comment]
@AllenFang ok. i got the point. Many thanks. Yes, if it can be supported natively, that's really awesome, but no hurry, i am just trying to add a New Modal as you suggested in (https://github.com/AllenFang/react-bootstrap-table/issues/226)

**Comment by AllenFang** [comment]
@simozhan, actually, most of user of ```react-bootstrap-table``` does not use ```insertRow```, they custom a modal for adding a new rows by themself, so if you can custom it is best condition, because you can control everything.

**Comment by AllenFang** [comment]
@simozhan, on newest ```v2.1.1```, you can use following config to ignore editable on insert
```js
const options = {
   ignoreEditable: true
};

return (
      <BootstrapTable data={ products } 
          cellEdit={ cellEditProp } 
          insertRow={ true } 
          options={ options }>
          //.....
    );
```

**Comment by simozhan** [comment]
@AllenFang Many many thanks for quickly fix! Awesome!!!
