### ISSUE TITLE
dataFormat function calling other function

### ISSUE THREAD

**Issue by dougdelabrida** [AllenFang/react-bootstrap-table#382]
Hi everybody, first i'd like to thank for this awesome react component which has helped me a lot. 
I've been trying to add some actions in my Table 

```
function actionsFormatter(cell, row){
      var html = '<div class="acoes"><button onClick="viewClient()"><span class="fa fa-eye"></span></button></div>';
      return html;
}

export default class ClientsList extends React.Component{
```
But i receive the following error: viewClient is not defined.

What could it be? is this the right way to do that?

**Comment by AllenFang** [comment]
@dougdelabrida, the dataFormat accept a string or JSX or a React Component, so you can handle this issue like following: 
```js
function actionsFormatter(cell, row) {
  return (
    <button onClick={ handleBtnClick }>clickme</button>
  );
}
```
