### ISSUE TITLE
Preserving row number while sorting

### ISSUE THREAD

**Issue by Meera613** [AllenFang/react-bootstrap-table#383]
Hi,
Is there some way I could preserve the row numbers even after some column is sorted? The row numbers usually get shuffled.
Eg: 
If the table contains the following,
<img width="203" alt="screen shot 2016-04-04 at 12 28 22 pm" src="https://cloud.githubusercontent.com/assets/6396294/14240224/c822d25a-fa60-11e5-898f-93b66f291234.png">
And if I sort in on column1 in ascending, it becomes this
<img width="204" alt="screen shot 2016-04-04 at 12 30 15 pm" src="https://cloud.githubusercontent.com/assets/6396294/14240270/18948670-fa61-11e5-9eca-575f7a56ff22.png">

But I would like to keep the row numbers as 1,2,3

Thanks

**Comment by AllenFang** [comment]
@Meera613 sorry, there's no way to do it and I didn't see this feature ever. So I should not support this feature, but PR is welcome. Thanks
