### ISSUE TITLE
table header columns and body columns aren't aligning properly to each other

### ISSUE THREAD

**Issue by pramodrhegde** [AllenFang/react-bootstrap-table#386]
I am facing this weird issue, when I load table data  as mentioned columns are not in line with each other 
basically my th style is
 `text-align: left;
    width: 0px;
    max-width: 0px;`
which is not aligning with tr's in tbody
when I resize window it aligns properly! now my th style is like this
`text-align: left;
    width: 212px;
    max-width: 212px;`
I am not giving any overriding css.please someone help me out.

**Comment by AllenFang** [comment]
@pramodrhegde, could you please show your code and what's browser did you use?

**Comment by pramodrhegde** [comment]
`<BootstrapTable exportCSV={true} csvFileName={csvName} data={investorsList} striped={true} hover={true} condensed= {true} search={true}>
				      <TableHeaderColumn dataField="email" dataSort={true} isKey={true}>Email</TableHeaderColumn>
				      <TableHeaderColumn dataField="name" dataSort={true}>Name</TableHeaderColumn>
				      <TableHeaderColumn dataField="investmentCapacity" dataSort={true}>Type</TableHeaderColumn>
				      <TableHeaderColumn dataField="roundType" dataSort={true}>Round</TableHeaderColumn>
				      <TableHeaderColumn dataField="participationDiv" dataSort={true}>Participation</TableHeaderColumn>
				      <TableHeaderColumn dataField="commitmentDiv" dataSort={true}>Commitment</TableHeaderColumn>
				      <TableHeaderColumn dataField="isFollowing" width="50" dataSort={true}>Following?</TableHeaderColumn>
				      <TableHeaderColumn dataField="isConnected" width="50" dataSort={true}>Introduced?</TableHeaderColumn>
				      <TableHeaderColumn dataField="editBlock" >Actions</TableHeaderColumn>
</BootstrapTable>`

I have checked in chrome and firefox

**Comment by AllenFang** [comment]
@pramodrhegde, which columns width are 0px ?

**Comment by pramodrhegde** [comment]
All columns have zero width even the once hard coded with 50 and one more thing i noticed now was that there were 2 tables!! one table under div with classes `react-bs-container-header table-header-wrapper` and one more table inside div with classes `react-bs-container-body`
once the data loaded from back end (and when I resize the window!!) header table columns are adjusting the widths according to the data in body table.

**Comment by AllenFang** [comment]
@pramodrhegde, there are two table absolutely. BTW, your table is in tab? and what version of firefox and chrome did you used?

**Comment by pramodrhegde** [comment]
Yes! i am using it inside a tab.
Chrome : Version 48.0.2564.103 (64-bit)
Firefox : 44.0.2

**Comment by AllenFang** [comment]
check this [discussion](https://github.com/AllenFang/react-bootstrap-table/issues/331) and this [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/others/table-in-tabs.js)

**Comment by pramodrhegde** [comment]
Hi I have tried the component forceUpdate but its the same :( 
should i use both css files `react-bootstrap-table.min.css` and `react-bootstrap-table-all.min.css` ?

**Comment by AllenFang** [comment]
Any sample or repo could let me reproduce it?  Use one of css files.  The ```react-bootstrap-table-all.min.css``` include toastr css, the other one is not :)

**Comment by obiwarn** [comment]
The problem occurs when rows are empty (so the header title of the row is wider than the row).

**Comment by obiwarn** [comment]
<img width="961" alt="screen shot 2016-09-09 at 13 03 21" src="https://cloud.githubusercontent.com/assets/9539797/18384956/f191398e-768d-11e6-8d0a-596c3818f842.png">

**Comment by AllenFang** [comment]
@obiwarn, great!  I'll try to reproduce it

**Comment by AllenFang** [comment]
, sorry for lately fixing, check `react-bootstrap-table@2.10.0-beta.1` by
```npm install react-bootstrap-table@2.10.0-beta.1``` and I thought this beta release already fixed couples unalign problem, if it work and stability, I'll consider to forward to production as soon as possible.

Let me know if the problems still there. thanks

**Comment by wujiang1900** [comment]
@AllenFang I tried "npm install react-bootstrap-table@2.10.0-beta.1", but failed. I got "└─┬ react-bootstrap-table@2.10.0-beta.1  invalid". Is version 2.10.0-beta.1 a valid version?

**Comment by AllenFang** [comment]
@wujiang1900, this beta is a valid version, in https://github.com/AllenFang/react-bootstrap-table/issues/965, there're some people test it and the column align is work well.

**Comment by wujiang1900** [comment]
@AllenFang I was able to figure out my installation issue, and checked out 2.10.0-beta.1 version. I did see that some issues with our table header are now fixed, however,  issue #386 "table header columns and body columns aren't aligning properly to each other"  is still not fixed (please see below screenshot). #965 is fixed and tested, but it is a different issue from this  issue (#386).
![image](https://cloud.githubusercontent.com/assets/11969043/22300147/2daee964-e2ec-11e6-9210-2e0decc3ed60.png)

**Comment by AllenFang** [comment]
@wujiang1900, you forgot to include the css, check https://github.com/AllenFang/react-bootstrap-table#cimport-css and test it again.

**Comment by wujiang1900** [comment]
I added css. It looks a little better, but the header still not aligning well with the body. (see below)

![image](https://cloud.githubusercontent.com/assets/11969043/22401519/f05ccdc6-e59b-11e6-8166-f661f25cea1c.png)

**Comment by wujiang1900** [comment]
I think this problem might happen only inside the tab.

**Comment by AllenFang** [comment]
@wujiang1900, sorry for lately reply, check https://github.com/AllenFang/react-bootstrap-table/issues/331#issuecomment-196358155

**Comment by ksiranjeevi92** [comment]
i am also facing same issue in HTML table , i was use nested table the child table hasn't proper align in parent table

**Comment by PavanKumarRao** [comment]
@AllenFang Im facing the same issue.Please revert back

**Comment by sadakmed** [comment]
use `width` and assign to it (100/ the number of column)% 

exampli gratia, i have 5 columns: 
```
<BootstrapTable version='4' data={ jobs } cellEdit={ cellEditProp } insertRow={ true }>
          <TableHeaderColumn dataField='id' width='20%' isKey={ true }>Job ID</TableHeaderColumn>
          <TableHeaderColumn dataField='status' width='20%' >Job Status</TableHeaderColumn>
          <TableHeaderColumn dataField='name' width='20%' >Job Name</TableHeaderColumn>
          <TableHeaderColumn dataField='type' width='20%' >Job Type</TableHeaderColumn>
          <TableHeaderColumn dataField='active' width='20%' >Active</TableHeaderColumn>
      </BootstrapTable>

```
