### ISSUE TITLE
Updating row data

### ISSUE THREAD

**Issue by Julusian** [AllenFang/react-bootstrap-table#389]
Is it possible to update the data for a row in the table?
I do not see a method in the api to do so, and I have tried to use the add method but it fails due to duplicate key.

I have a hacky workaround by deleting the row, whilst skipping showing a confirmation dialog, and then readding the data.

**Comment by AllenFang** [comment]
@Julusian, there're only two way you can update row
1. cell edit
2. manage by yourself

Maybe u can tell me your scenario and then make a choice
Thanks

**Comment by amitkumarsingh** [comment]
Can i handle the data save on particular row using external button save ?

**Comment by AllenFang** [comment]
@amitkumarsingh, you can just update table state after save button click. Feel free to discuss with me. Thanks
