### ISSUE TITLE
Event Object passed to onRowSelect callback

### ISSUE THREAD

**Issue by humblepig** [AllenFang/react-bootstrap-table#392]
Would it be possible to pass the event object as the third parameter to the onRowSelect callback?  This would allow user to check to see if there was a key pressed when the row was clicked.  There may be other use cases for this.

**Comment by AllenFang** [comment]
@humblepig, I'll add it

**Comment by madeinfree** [comment]
I try to add the event for OnRowSelect, see the #399

**Comment by AllenFang** [comment]
@humblepig, fixed on ```v2.1.3```, the event object will be passed as third argument.
