### ISSUE TITLE
React 15 Support

### ISSUE THREAD

**Issue by staskorz** [AllenFang/react-bootstrap-table#397]

**Comment by madeinfree** [comment]
Hi @staskorz,

I think it not easily to change the version now, because some of dependencies have to upgrade or change it ... and React changed the version 0.14.x jump to 15.0.0 this time, so we must be solve the dependencies issue now ~

I think it could support React 15 quickly !!

cc @AllenFang

**Comment by staskorz** [comment]
Hi @madeinfree,

Thanks for the "quickly" comment, I've change the title :-)

Re the dependencies: this package only depends on `classnames` and `react-toastr`. The later depends on React 0.14, I've just opened an issue in its repository (tomchentw/react-toastr#47).

Technically it's possible to depend on multiple `react `and `react-dom` versions like so:

`"react": "^0.14.3 || ^15.0.0"`

As till now both packages were running without React warnings, they should keep working with React 15, at least according to the Release Notes.

**Comment by AllenFang** [comment]
Released on ```v2.0.0```
