### ISSUE TITLE
Editable property input box can't copy value

### ISSUE THREAD

**Issue by rbalicante882012** [AllenFang/react-bootstrap-table#398]
When I click the cell the editable input box did not copy the value. But, when I used textarea, it works.

**Comment by madeinfree** [comment]
could you more detail description your problem or have some example for me to reproduce it ?
it work well in my example.

**Comment by rbalicante882012** [comment]
Hello @madeinfree. 
I add validator property for editable and I made handler but I won't copy the value of input box only. Only if I put type property.

**Comment by AllenFang** [comment]
@rbalicante882012, it's a bug, I'll fix it quickly

**Comment by rbalicante882012** [comment]
@AllenFang thanks :+1:

**Comment by madeinfree** [comment]
Hi, @rbalicante882012 @AllenFang I push the PR above #401, you can review it.

**Comment by rbalicante882012** [comment]
Thanks @madeinfree  :+1:

**Comment by rbalicante882012** [comment]
@madeinfree can I ask? 

What time @AllenFang will check it @madeinfree ?

**Comment by AllenFang** [comment]
@rbalicante882012, I'll do it in these day, before thursday ;)

**Comment by madeinfree** [comment]
@rbalicante882012 sure, feel free to discuss

**Comment by rbalicante882012** [comment]
Hi @madeinfree can I manipulate checkbox in the table header ? I want it checked = false.

**Comment by AllenFang** [comment]
you want to set the checkbox on header programmatically?

**Comment by rbalicante882012** [comment]
Yes @AllenFang.

**Comment by AllenFang** [comment]
@rbalicante882012, what version did you used?  I try to call ```cleanSelected``` and it works(all checked box will uncheck, include the header one).  BTW, could you show me your code?

Thanks :)

**Comment by rbalicante882012** [comment]
@AllenFang I want header to checked to false. Can I manipulate it?

**Comment by AllenFang** [comment]
No, the header checkbox depend on user operation.

**Comment by rbalicante882012** [comment]
@AllenFang I want it to clear after I click the delete button.

**Comment by AllenFang** [comment]
let me guess your scenario, 
1. user select some column, so header column checked
2. user click delete button to drop selected row
3. header column checkbox remain checked?

some question I want to ask

1. the delete button is means you enable ```deleteRow```? or you implement a delete button by yourself and also delete row by yourself?
2. I've test and it work when I enable ```deleteRow```.

**Comment by rbalicante882012** [comment]
@AllenFang, 
I created my own delete function and I want to uncheck the header check box. :)

**Comment by AllenFang** [comment]
@rbalicante882012, that what I want to know. how you delete data?

**Comment by rbalicante882012** [comment]
@AllenFang I created custom delete function.

**Comment by AllenFang** [comment]
you update your state in React or call ```handleDropRow```?  I thinks a example will be better

**Comment by rbalicante882012** [comment]
Here's the scenario @AllenFang. 

1. First I select list of products 
2 I click the delete button and show Modal
3 Delete the products I selected and unchecked the header check box.

**Comment by AllenFang** [comment]
@rbalicante882012,yes, I know, my question is how did you delete table data?  remove selected row and update state?  or call ```handleDropRow``` exposed by ```BootstrapTable```?

**Comment by rbalicante882012** [comment]
@AllenFang update state.

**Comment by AllenFang** [comment]
@rbalicante882012, thanks, that's exactly what I want......

**Comment by AllenFang** [comment]
@rbalicante882012, I open #403 for improve this situtaion

**Comment by AllenFang** [comment]
Hi, @rbalicante882012, fixed on ```v2.1.4```
