### ISSUE TITLE
Key based on multiple column information

### ISSUE THREAD

**Issue by Wind4Greg** [AllenFang/react-bootstrap-table#402]
My data doesn't have a single column that can act as a key, but a combination of columns.
Can react-bootstrap-table be used in this situation?

Cheers
Greg B.

**Comment by AllenFang** [comment]
HI, @Wind4Greg, ```react-bootstrap-table``` need a column presented as a key column. But a workaround is you can generate a new column for key by a time serial or a combination column, then you can hide it will be perfect.  How about that?

Thanks:)

**Comment by Wind4Greg** [comment]
Thanks for the quick response. That works great!
Cheers
