### ISSUE TITLE
select state still remain when update state on table

### ISSUE THREAD

**Issue by AllenFang** [AllenFang/react-bootstrap-table#403]
1. a table which enable multi select 
2. click some row for selection
3. remove selection row on source data and update table state
4. the checkbox on header is still remain

**Comment by rbalicante882012** [comment]
Thanks @AllenFang :+1:

**Comment by AllenFang** [comment]
Hi @rbalicante882012, fixed on ```v2.1.4```

**Comment by annelorraineuy** [comment]
OMG I was figuring out a workaround for this for a few days now. How timely! You're awesome @AllenFang !
