### ISSUE TITLE
TableDataSet, or migration from 2.0.x to 2.1.x 

### ISSUE THREAD

**Issue by jbilcke** [AllenFang/react-bootstrap-table#408]
Hi Allen,

My app uses `TableDataSet` to update the table with data from other parts of my application (forms, database sync etc) using `.setData(..)` but I've noticed it has been removed in 2.1.x

What is the new, recommended way of achieving the same kind of update? 

Actually (not sure this is the right thing to do) I've tried to directly use `TableDataStore`:
```
import {TableDataStore} from 'react-bootstrap-table';
```

But it doesn't seem to work (`TableDataStore` is not exported on the package level), so I guess this is on purpose, because we are not supposed to play with TableDataStore directly?

EDIT: I will wait for your feedback to have an official answser, but after some digging around, it looks like there is something in progress that I could use for my table updates: https://github.com/AllenFang/react-bootstrap-table/pull/369  :)

Thanks!

**Comment by AllenFang** [comment]
@jbilcke, sorry for removing```TableDataSet``` since ```v2.1.0```. Because some reason and really few people use it. BTW, without ```TableDataSet```, you still can update data just by updating react state. Following is a simple example:

```js
 class BasicTable extends React.Component {

  constructor(props) {
     super(props);
     this.state = {
        products: YOUR_DATA
     };
  }

  handleFetchDataBtnClick = () => {
      //get your data and set data to state...
      this.setState({
          products: DATA_FROM_FETCH
      });
  }

 handleAddDataBtnClick= () => {
      //here just create a fake data and update state...
      const product = { .... };
      this.setState({
          products: [ ...this.state.products, product  ]
      });
  } 

  render() {
    return (
      <div>
          <button onClick={ this.handleFetchDataBtnClick }>Fetch data</button>
          <button onClick={ this.handleAddDataBtnClick}>Add data</button>
          <BootstrapTable data={ this.state.products }>
              <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
              <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
              <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
          </BootstrapTable>
      </div>
    );
  }
}
```

Anyway, #369 is just a remote example(meteor-like), but without this PR, you still can table data by state.

Thanks and feel free to discuss with me.
Sorry for this API change
