### ISSUE TITLE
remove the inline style width in the table header

### ISSUE THREAD

**Issue by AllenFang** [AllenFang/react-bootstrap-table#41]
reference from <a href='https://github.com/AllenFang/react-bootstrap-table/issues/15#issuecomment-136660677'>#15</a> by @markmus

**Comment by markmus** [comment]
My problem that I encounter with this is I have `react-bootstrap-table` with a collapsible side panel. when I collapse the side panel, the table headers is being dis aligned because of the fix with. but it works fine with `width: 100%`

```
container
==================
| side  |  table |
| panel |        |
==================
```

**Comment by AllenFang** [comment]
HI @markmus, I'll try to find this problem :)

**Comment by AllenFang** [comment]
HI @markmus, I've solve the fix width in header problem in newest version (v0.9.13)

**Comment by markmus** [comment]
Thank you so much @AllenFang :)
