### ISSUE TITLE
Dynamic table columns

### ISSUE THREAD

**Issue by adamtay82** [AllenFang/react-bootstrap-table#410]
Possible that I'm being slow (react newbie), but I'm having an issue creating dynamic columns (from other posts, it looks like it's possible!):

My code is as follows:
`

       <BootstrapTable data={this.state.tableData}>

      <TableHeaderColumn dataField="location" dataSort={true}
                  isKey={true}>Location</TableHeaderColumn>
       {
                 this.state.tableColumns.map(function (elem, index) {
                 return <TableHeaderColumn dataField={period} key={index} dataSort={true}>{periodtxt}        
       </TableHeaderColumn>
         })
     }

     </BootstrapTable>
`
However, this gives me a "Cannot read property 'dataField' of undefined" - it appears the child doesn't have any props.  

Any ideas what I'm doing wrong?

Thanks!

**Comment by rpastorelle** [comment]
@adamtay82 What is your default value for `this.state.tableData`?

**Comment by adamtay82** [comment]
@rpastorelle Thanks for the quick response.   

I'm setting both tableData and tableColumns to [] in the constructor.  (Note: making it an object not an array doesn't appear to help...)

tableData has also been populated by the first time the component is rendered...

**Comment by rpastorelle** [comment]
@adamtay82 It is probably having issues rendering inside that `map` function where you have `dataField={period}` ... Should probably quote that : `dataField={"period"}`

**Comment by adamtay82** [comment]
@rpastorelle , That was me just trying to simplify my code poorly :/  Here's it with the period string calculated...
```
<BootstrapTable data={this.state.tableData} striped={true} hover={true} search={true}
                pagination={true}>
    
        <TableHeaderColumn dataField="location" dataSort={true} isKey={true}>Location</TableHeaderColumn>
    
         {
            this.state.tableColumns.map(function (elem, index) {
                var period_str = "period_" + (index)
                console.log("period_str: " + period_str + "  elem: " + elem)
                return <TableHeaderColumn dataField={period_str} key={index} dataSort={true}>{elem}</TableHeaderColumn>
            })
         }
    </BootstrapTable>
```

**Comment by rpastorelle** [comment]
@adamtay82 Lost me. Are you trying to access `this.state.tableColumns[ix]` by setting `dataField={"period_"+ix}` ... I wasn't aware that worked. Sorry I couldn't be more helpful

**Comment by adamtay82** [comment]
@rpastorelle No worries - appreciate you jumping in regardless.  Bit more detail on the off chance it helps...

I just have an array of column headers = ["period_1", "period_2", ..., "period_n"]

Then in tandem I have data that looks like this:

```
tableData = [ { "location": "locationname", 
                     "period_1": 1000, 
                     "period_n": 2000}, 
                     { ... next row}]
```

If that makes any sense? Then I'm trying to show periods as columns....

**Comment by AllenFang** [comment]
thanks your repsponse @rpastorelle, and @adamtay82 you can check this [issue](https://github.com/AllenFang/react-bootstrap-table/issues/406), it's absolutely same as yours

**Comment by adamtay82** [comment]
That did the trick - thanks @AllenFang  and @rpastorelle !
