### ISSUE TITLE
Help - table inside wordpress

### ISSUE THREAD

**Issue by garciasa** [AllenFang/react-bootstrap-table#413]
Hi guys,
I'm trying to render react-bootstrap-table inside a wordpress (default installation), but I'm getting this issue in the table.
![image](https://cloud.githubusercontent.com/assets/1852069/14677072/eb09476e-0707-11e6-8813-da04bba76d27.png)

when i remove the height, in Chrome DEV tool, 
![image](https://cloud.githubusercontent.com/assets/1852069/14677145/461cee9e-0708-11e6-9513-d0749d18bd55.png)
 works, but it's like all the time it's  getting a fixed height, bigger than the content.
If a try to override those heights properties, the component doesn't works properly, since those properties are there when i render the table outside wordpress, so it's part of the component.
If a render a normal table the height of this div it's correct (the size of the content), but if i render react-bootstrap-table doesn't.

Outside the wordpress works properly, and i don't have any style that could part of the problem, at least i think so.

It was working 2 days ago, but now after upgrade the library to the last version, i get this, did you do any change in the way you get the height of the parent div???
To increase the  mystery, same code in a IIS instance of wordpress works, but same code in NGINX  (linux) instance doesn't, and in my local (Wamp server) dev neither.... it's fucking weird...

**Comment by AllenFang** [comment]
@garciasa, maybe it's a weird thing, I haven't seen that.. and I'm sure that there's no any styling change in recently patch. anyway, if this problem still remain, you can defined your css styling to override the ```react-bs-table``` and ```react-bs-container-body```.  Hop this can help you, feel free to discuss with me. Thanks

**Comment by garciasa** [comment]
I have no idea!!! I´ve just tested at home, different setup, osx, mamp (apache), clean wordpress (4.5) and a component with react-bootstrap-table and it´s working, I´m gonna drive me crazy with that, I´m fucking lost hahaha...

**Comment by AllenFang** [comment]
@garciasa, take it easy... Just one more question, what's the only condition this issue will happened?

**Comment by garciasa** [comment]
I have no idea, now in my NGINX instance, if I remove my child theme and put the files into the parent theme it's working... it's fucking weird...
Anyway you can close this issue, I think it has nothing to do with react-bootstrap-table...

Thanks anyway...

**Comment by AllenFang** [comment]
@garciasa, sorry for no any helping ;(
