### ISSUE TITLE
Remove margin on react-bs-table

### ISSUE THREAD

**Issue by johannessjoberg** [AllenFang/react-bootstrap-table#414]
Hi,

I have a problem with the margin on react-bs-table class. I can't find any attribute in the docs to alter it. It would be nice to be able to alter the styling on the main component(BootstrapTable) without having to override that specific class.

Thanks for an awesome repo!
Cheers Johannes

**Comment by AllenFang** [comment]
Thanks @johannessjoberg, there's no way to define some style on ```react-bs-table``` through react(Maybe I can support it), but you can override the styling by your css.  Feel free to discuss with me :)

**Comment by johannessjoberg** [comment]
All right, good to know :) 

I'm going pretty heavy on the inline-styling with this project, i.e. not using classNames, and want to avoid external css as much as possible(death to globals ;) ).

Maybe the possibility to be able to set a `style` attribute on the BootstrapTable component which would only effect the styling on the wrapping div would be a solution?

**Comment by AllenFang** [comment]
> I'm going pretty heavy on the inline-styling with this project, i.e. not using classNames, and want to avoid external css as much as possible(death to globals ;)

that's a right thing on development a react application.



> Maybe the possibility to be able to set a style attribute on the BootstrapTable component which would only effect the styling on the wrapping div would be a solution?

I'll try to make a custom inline-styling on ```react-bs-table``` and apply a props on ```BootstrapTable```

**Comment by johannessjoberg** [comment]
Sweet! 
Perhaps it would be nice to implement it on other components like `TableHeaderColumn` as well?

Btw, thanks for the fast response!

**Comment by AllenFang** [comment]
Nice suggestion, btw, TableHeaderColumn apply ```classname``` for user to customize there column, [there](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/style) are some useful example.  But it's not a inline-style way.

**Comment by AllenFang** [comment]
@johannessjoberg, you can check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/style/inline-style-table.js) example to see how to apply inline styling. I support four type of inline style(```containerStyle```, ```tableStyle```, ```headerStyle```, ```bodyStyle```), it's corresponding to the class of  ```react-bs-table-container```, ```react-bs-table```, ```react-bs-container-header``` and ```react-bs-container-body```.

**Comment by johannessjoberg** [comment]
@AllenFang Nice! Thank you for the fast response and also the quick implementation. Awesome job, awesome repository!
