### ISSUE TITLE
column head jumps when sort

### ISSUE THREAD

**Issue by geekbosszhang** [AllenFang/react-bootstrap-table#420]
Hi, @AllenFang I noticed sortable column headers move down out of alignment when clicked, the version is 2.1.0, but in the old version, like 1.5.4, there isn't such problem.So is there any solution to solve this? Thanks a lot.

**Comment by geekbosszhang** [comment]
Hi, @AllenFang , we changed` <span className="caret" style={{margin: '0px 5px'}}></span>` to `  <span className="caret" style={{margin: '10px 5px'}}></span>`, it works. We found you changed the file
![image](https://cloud.githubusercontent.com/assets/7484001/14845955/e0c5edb6-0c93-11e6-8e82-3a580b9475ec.png)

**Comment by AllenFang** [comment]
@geekbosszhang, thanks your finding, I'll check this out :)

**Comment by AllenFang** [comment]
@geekbosszhang, released on ```v2.2.0```. Thanks
