### ISSUE TITLE
property title for each column

### ISSUE THREAD

**Issue by sarzijan** [AllenFang/react-bootstrap-table#422]
Hi @AllenFang ,

Is it possible to add new props e.g. "columnTitle" for component TableHeaderColumn, which will set html property title for each column?

I am using your awesome component and if I use it without dataFormat, the css style with ellipses are applied, then I want to see the whole text in title when I hover over the column.

Yes, I can use dataFormat and wrap it to the span with the title property, but then I have to call the formatter for each column, where the title should be sown. and also the default css style is not used and I have to create my own for that...

Thanks a lot

**Comment by AllenFang** [comment]
@sarzijan, I can support ```columnTitle``` for this requirement :)

**Comment by AllenFang** [comment]
@sarzijan, thanks your contribution, this patch has been released on ```v2.3.1```. Thanks 👍
