### ISSUE TITLE
New and Delete button custom text

### ISSUE THREAD

**Issue by ehelguero** [AllenFang/react-bootstrap-table#426]
I´m trying to change the text of the buttons new and delete, but the only way I found is editing react-bootstrap-table.js . Is there another way to do this?

Thanks

**Comment by AllenFang** [comment]
I can support a customize text on button for you.

**Comment by AllenFang** [comment]
Released on ```v2.2.0```, check [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/custom-btn-text-table.js)

**Comment by ehelguero** [comment]
Thank you very much.
