### ISSUE TITLE
The filters doesn't work when the column contains null values

### ISSUE THREAD

**Issue by Kurtas** [AllenFang/react-bootstrap-table#427]
Example of data 

`[
{
id: 1,
data: 'test'
},
{
id: 2,
data: null
},
{
id: 3,
data: 'test 2'
}
]`

**Comment by AllenFang** [comment]
I'll check this out. Thanks @Kurtas

**Comment by amitkumarsingh** [comment]
Hi Allen,

There are some objects where there are null values and this is the error i get on searchinh that particular field.
react-bootstrap-table.min.js:8 Uncaught TypeError: Cannot read property 'toString' of undefined.

**Comment by AllenFang** [comment]
@amitkumarsingh, ok could you please open another issues :)  Thanks!

**Comment by jfremy** [comment]
Hi guys, returning false for the filtering on null value might be too strong. It means you cannot filter in the values that are null.
What do you think about rather replacing null with the empty string, that way, there would still be way to write a filter that includes those lines (like the Regex filter)

**Comment by AllenFang** [comment]
#443, actually, I cant reproduce this issue. so just pending it.. BTW, thanks @jfremy
