### ISSUE TITLE
Using a custom function to sort the table

### ISSUE THREAD

**Issue by pola88** [AllenFang/react-bootstrap-table#43]
Hi guys,

I want to start use this package, but I was wondering if I can set a function to handle the sorting, is it possible?

Thanks in advance,

**Comment by AllenFang** [comment]
HI @pola88, you cant set a customize function for sorting, but it's good idea for this component. I'll consider to add this feature in future.(recently)

**Comment by AllenFang** [comment]
HI @pola88, I've add this feature in newest version (v0.9.13), you can customize your sort function as follow 

<pre>

var data = [
    {name: "test1", count: 1},
    {name: "test2", count: 6}, 
    {name: "test5", count: 0}
];
function mySortFunc(a, b, order){   //order is desc or asc
    return a.count - b.count;
}

&lt;BootstrapTable data={data} &gt;
      &lt;TableHeaderColumn dataField="name" isKey={true}&gt;Name&lt;/TableHeaderColumn&gt;
      &lt;TableHeaderColumn dataField="count" dataSort={true} sortFunc={mySortFunc}&gt;Count&lt;/TableHeaderColumn&gt;
&lt;/BootstrapTable&gt;
</pre>
