### ISSUE TITLE
Printing the table makes the header columns width different from the data

### ISSUE THREAD

**Issue by ehelguero** [AllenFang/react-bootstrap-table#430]
Hello! I´m am printing the table and it gets like this:

<img width="809" alt="captura de pantalla 2016-04-29 a las 6 20 46" src="https://cloud.githubusercontent.com/assets/1289195/14908685/4110f6d6-0dd2-11e6-9440-3b080d8cde97.png">

Is there a way to fix it? With the new version?

Thanks

**Comment by AllenFang** [comment]
> printing the table

what's that means?, because I feel the the table in the picture is not a react-bootstrap-table``` 

could you please give me the example? and what's browser and ```react-bootstrap-table``` you used?

Thanks :)

**Comment by ehelguero** [comment]
Hello, i am using window.print to print out the screen. Thats how it looks when i save the react-bootstrap-table to a PDF.

**Comment by AllenFang** [comment]
@ehelguero, ok, I see. I can't figure out what happen on window.print with react-bootstrap-table. I'll do some survey, but not sure I can solve it.

**Comment by ehelguero** [comment]
Ok, thank you very much in advance.

**Comment by ibilanchuk** [comment]
Hi, i have same problem 
Will be very glad if you'll fix it.
Thanks.

**Comment by AllenFang** [comment]
Try ```v2.5.6```.  Feel free to discuss with me if problem still there

**Comment by nathanpjones** [comment]
This resolves the issue _unless_ you set `width` for any column. If you set `width`, then the headers are misaligned in both screen and print.
