### ISSUE TITLE
Headers out of alignment with columns

### ISSUE THREAD

**Issue by dukedougal** [AllenFang/react-bootstrap-table#433]
Refer to the attached image thanks.

![image](https://cloud.githubusercontent.com/assets/691840/14953333/17b58f54-10ac-11e6-834c-b1975a758b50.png)

Any guesses as to why this would be happening?

thanks

**Comment by AllenFang** [comment]
@dukedougal, did you have any styling apply on ```react-bootstrap-table```? and which browser and version of the ```react-bootstrap-table``` you used?

**Comment by giulianojjk** [comment]
I have a similar problem in addition in may table there is a space between the headers and the cells.
Maybe there is a problem related to the margin-bottom of the .table class.
![senzanome](https://cloud.githubusercontent.com/assets/19168674/15016477/a1708f8a-1211-11e6-9953-797c7a2c15f8.png)

**Comment by AllenFang** [comment]
@giulianojjk, the ```margin-bottom: 20px;``` seems like from your styling?!, and ```react-bootstrap-table``` does not set the ```margin-bottom: 20px;```

make sure you have using the newest css file from ```react-bootstrap-table```. If problem still remain, I thinks you can give me a repo to reproduce it.

**Comment by AllenFang** [comment]
@giulianojjk, should be look like ![screen](http://imgur.com/2JYXP7Q.png)
```react-bootstrap-table``` will override ```margin-bottom``` to ```0px```. so I thinks you didn't load the css of ```react-bootstrap-table``` correctly

**Comment by giulianojjk** [comment]
You are absolutely right! I completely forgot the css include.
Also the headers problem has disappeared.
Sorry for the stupid question.

Thanks a lot!
Giuliano

**Comment by AllenFang** [comment]
@dukedougal, any feedback with this issue?

**Comment by AllenFang** [comment]
hi there, sorry for lately fixing, check `react-bootstrap-table@2.10.0-beta.1` by
```npm install react-bootstrap-table@2.10.0-beta.1``` and I thought this beta release already fixed couples unalign problem, if it work and stability, I'll consider to forward to production as soon as possible.

Let me know if the problems still there. thanks
