### ISSUE TITLE
Multiple lines string for cellEdit?

### ISSUE THREAD

**Issue by daiwhea** [AllenFang/react-bootstrap-table#435]
Hi.

Can we have a choice to use textarea tag with cellEdit? so we can keep the multiple lines string after cellEdit.

**Comment by AllenFang** [comment]
hi @daiwhea, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/advance/edit-type-table.js#L34

**Comment by daiwhea** [comment]
Sorry. Thank you, dear.
