### ISSUE TITLE
Row Level Edit

### ISSUE THREAD

**Issue by TWith2Sugars** [AllenFang/react-bootstrap-table#44]
The ability to handle all changes in a row in one go. This could be like the "new" row with a modal pop up that we can hook on the save event or some way in the cell edit to specify when a row loses focus etc.

Is this reasonable?

**Comment by AllenFang** [comment]
I think it's a reasonable feature for this component. But I wont implement this features, it may be spend a lot of time and it's a little unnecessary feature. It's a much customize function for this component. Anyway, you can folk it and implement this feature in your branch. :)
