### ISSUE TITLE
Make main entry point be index.js instead of dist build

### ISSUE THREAD

**Issue by ianks** [AllenFang/react-bootstrap-table#440]
Currently, we are using the dist build for this main entry point. This is problematical since bundlers like webpack cannot do things like sourcemaps easily. Also, the code is much harder to grok.

Do you think it would be reasonable to make the compiled index.js the main entry point instead?

ref: https://github.com/AllenFang/react-bootstrap-table/blob/master/package.json#L5

**Comment by AllenFang** [comment]
@ianks, sorry I can't got you. I've use ```./src/index.js``` as the main entry point in webpack building. 
https://github.com/AllenFang/react-bootstrap-table/blob/master/webpack.umd.config.js#L21

**Comment by ianks** [comment]
currently the minified version is used as the main entry in package.json. I am suggesting we don't do that.

**Comment by AllenFang** [comment]
@ianks, ok I understand. I'll do some survey. if have any solution, PR is welcome

**Comment by staminaloops** [comment]
Hey @AllenFang I've been out, a lot of work. On the PR that I did - improve build - I set the entry point to lib/index.js but I saw that someone changed it after that back to dist. If you see my comment on the gulpfile you can understand why I did it and why @ianks is telling you that. Cheers

**Comment by AllenFang** [comment]
@staminaloops, thanks, I'll figure out why the entry point been changed. :+1:

**Comment by AllenFang** [comment]
hi all, I found this problem is since ```v2.1.2``` released, there's a PR change it, but I doesn't review it carefully. Sorry about that. I'll fix it on next version.
Thanks :)

**Comment by AllenFang** [comment]
Released on ```v2.3.1```.  Thanks again!!
