### ISSUE TITLE
Problems with search, when using custom formatter.

### ISSUE THREAD

**Issue by mityushev** [AllenFang/react-bootstrap-table#442]
Hello!

In my case date format, that I get from server is timestamp (ex. '1440535599'). In order to convert it to human-date I use custom formatter:

```
 registered_onFormatter (cell, row) {
    var myDate = new Date( cell * 1000 );
    return "<span>"+(myDate.toLocaleDateString('en-GB')).split('/').join('.')+"</span>";
  }
```

So in my table cell it looks like 25.08.2015, not 1440535599

But when I try to use table search and input '2015' or '08.2015' => There is no data to display. It doesn't work.

If I search by timestamp everything works fine. But I need to search by human date, not timestamp.

Is it possible somehow to search by formatted data? If you have any ideas, how to overcome this problem, please share.

PS: Also this problem appears, when I use toString() method on array in custom formatter.

**Comment by mityushev** [comment]
Allen, sorry, I have found solution for my problem by reading documentation more thoroughly)

I will leave it here, just in case:

Add** filterFormatted={true}** attribute to <TableHeaderColumn> , in order to enable search or filter data on formatting. Default is false.

**Comment by AllenFang** [comment]
@mityushev, great!
