### ISSUE TITLE
The filters doesn't work when the column contains null values

### ISSUE THREAD

**Issue by amitkumarsingh** [AllenFang/react-bootstrap-table#443]
Hi Allen,

There are some objects where there are null values and this is the error i get on searching that particular field.
react-bootstrap-table.min.js:8 Uncaught TypeError: Cannot read property 'toString' of undefined.

Sample data:

[{
	"id": 17,
	"firstName": "Prof. Ashutosh Mani",
	"lastName": "Tiwari",
	"city": "Ghaziabad",
}, {
	"id": 287,
	"firstName": "Sourav",
	"lastName": "Kant",
	"city": null,
}, {
	"id": 8,
	"firstName": "Prof. Sudhir",
	"lastName": null,
	"city": "Delhi",
}]

**Comment by AllenFang** [comment]
@amitkumarsingh, when you doing the filter is using the column-filter or search?

**Comment by AllenFang** [comment]
@amitkumarsingh, make sure you use the newest ```react-bootstrap-table```

**Comment by amitkumarsingh** [comment]
I just installed the latest one from your repository.  do i need to update node version and npm version too ? because my project needs   **"node": ">=4.2.0",    "npm": "^3.0.0"** and its working fine.

**Comment by AllenFang** [comment]
HI @amitkumarsingh, I thinks it's doesn't matter with node version, but you don't tell me which function you used? ```column-filter``` or ```search```?

**Comment by amitkumarsingh** [comment]
I use columnFilter in the header.

**Comment by AllenFang** [comment]
@amitkumarsingh, any example code for me? or what type of filter did you used? because I cant reproduce it on my client :)

**Comment by amitkumarsingh** [comment]
import React from 'react';
import { Link } from 'react-router';
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';

export class ProfessorList extends React.Component {

  editFormatter(cell, row){
    return <Link className="mdl-navigation__link" to={`/professor/create/${row.id}`}><i className="material-icons" role="presentation">edit</i></Link>;
  }

  viewFormatter(cell, row){
    return <Link className="mdl-navigation__link" to={`/professor/create/${row.id}`}><i className="material-icons" role="presentation">view_list</i></Link>;
  }

  statusFormatter(cell, row){
    return row.status.publishStatus;
  }

  render() {
    const professors = this.props.professors;
    return (
        <BootstrapTable data={professors} striped={true}  pagination={true}  >
            <TableHeaderColumn dataField="id" isKey={true} dataAlign="left" dataSort={true}  filter={{type: "TextFilter", placeholder: "Id"}}>Id</TableHeaderColumn>
            <TableHeaderColumn dataField="firstName" dataAlign="left" dataSort={true} filter={{type: "TextFilter", placeholder: "Enter first name"}}>First Name</TableHeaderColumn>
            <TableHeaderColumn dataField="lastName" dataSort={true} filter={{type: "TextFilter", placeholder: "Enter last name"}}>Last Name</TableHeaderColumn>
            <TableHeaderColumn dataField="email" dataSort={true} filter={{type: "TextFilter", placeholder: "Enter email"}}>Email</TableHeaderColumn>
            <TableHeaderColumn dataField="city" filter={{type: "TextFilter", placeholder: "City"}}>City</TableHeaderColumn>
            <TableHeaderColumn dataField="Edit" dataFormat={this.statusFormatter.bind(this)}>Status</TableHeaderColumn>
            <TableHeaderColumn dataField="Edit" dataFormat={this.editFormatter.bind(this)}>Edit</TableHeaderColumn>
            <TableHeaderColumn dataField="View" dataFormat={this.viewFormatter.bind(this)}>View</TableHeaderColumn>
        </BootstrapTable>
    );
  }
}

export default ProfessorList;

professor data is for example

[{
"id": 17,
"firstName": "Prof. Ashutosh Mani",
"lastName": "Tiwari",
"city": "Ghaziabad",
}, {
"id": 287,
"firstName": "Sourav",
"lastName": "Kant",
"city": null,
}, {
"id": 8,
"firstName": "Prof. Sudhir",
"lastName": null,
"city": "Delhi",
}]

**Comment by amitkumarsingh** [comment]
You can try with the above sample data.

```
export class ProfessorList extends React.Component {

  editFormatter(cell, row){
    return <Link className="mdl-navigation__link" to={`/professor/create/${row.id}`}><i className="material-icons" role="presentation">edit</i></Link>;
  }

  viewFormatter(cell, row){
    return <Link className="mdl-navigation__link" to={`/professor/create/${row.id}`}><i className="material-icons" role="presentation">view_list</i></Link>;
  }

  statusFormatter(cell, row){
    return row.status.publishStatus;
  }

  render() {
    const professors = this.props.professors;
    return (
        <BootstrapTable data={professors} striped={true}  pagination={true}  >
            <TableHeaderColumn dataField="id" isKey={true} dataAlign="left" dataSort={true}  filter={{type: "TextFilter", placeholder: "Id"}}>Id</TableHeaderColumn>
            <TableHeaderColumn dataField="firstName" dataAlign="left" dataSort={true} filter={{type: "TextFilter", placeholder: "Enter first name"}}>First Name</TableHeaderColumn>
            <TableHeaderColumn dataField="lastName" dataSort={true} filter={{type: "TextFilter", placeholder: "Enter last name"}}>Last Name</TableHeaderColumn>
            <TableHeaderColumn dataField="email" dataSort={true} filter={{type: "TextFilter", placeholder: "Enter email"}}>Email</TableHeaderColumn>
            <TableHeaderColumn dataField="city" filter={{type: "TextFilter", placeholder: "City"}}>City</TableHeaderColumn>
            <TableHeaderColumn dataField="Edit" dataFormat={this.statusFormatter.bind(this)}>Status</TableHeaderColumn>
            <TableHeaderColumn dataField="Edit" dataFormat={this.editFormatter.bind(this)}>Edit</TableHeaderColumn>
            <TableHeaderColumn dataField="View" dataFormat={this.viewFormatter.bind(this)}>View</TableHeaderColumn>
        </BootstrapTable>
    );
  }
}
```

**Comment by AllenFang** [comment]
Thanks you!! I'll check this out:)

**Comment by AllenFang** [comment]
@amitkumarsingh, I cant reproduce by your example. BTW, because your table have some column which doesn't exist in source data, so I modify you code like following:
```js
export default class BasicTable extends React.Component {

  render() {
    const professors = [ {
      'id': 17,
      'firstName': 'Prof. Ashutosh Mani',
      'lastName': 'Tiwari',
      'city': 'Ghaziabad'
    }, {
      'id': 287,
      'firstName': 'Sourav',
      'lastName': 'Kant',
      'city': null
    }, {
      'id': 8,
      'firstName': 'Prof. Sudhir',
      'lastName': null,
      'city': 'Delhi'
    } ];
    return (
        <BootstrapTable data={ professors } striped={ true } pagination={ true }>
            <TableHeaderColumn dataField='id' isKey={ true } dataAlign='left' dataSort={ true } filter={ { type: 'TextFilter', placeholder: 'Id' } }>Id</TableHeaderColumn>
            <TableHeaderColumn dataField='firstName' dataAlign='left' dataSort={ true } filter={ { type: 'TextFilter', placeholder: 'Enter first name' } }>First Name</TableHeaderColumn>
            <TableHeaderColumn dataField='lastName' dataSort={ true } filter={ { type: 'TextFilter', placeholder: 'Enter last name' } }>Last Name</TableHeaderColumn>
            <TableHeaderColumn dataField='city' filter={ { type: 'TextFilter', placeholder: 'City' } }>City</TableHeaderColumn>
        </BootstrapTable>
    );
  }
}
```
So anything I miss?

**Comment by amitkumarsingh** [comment]
@AllenFang Yea this is wat it exactly looks like, and causing the error.

**Comment by AllenFang** [comment]
@amitkumarsingh, really?  but I couldn't get any error this code snippet.

**Comment by amitkumarsingh** [comment]
Just search with city field and try.

**Comment by AllenFang** [comment]
@amitkumarsingh, I've try [this](https://github.com/AllenFang/react-bootstrap-table/issues/443#issuecomment-218800007) code snippet and type some condition on city filter but got nothing.  could you please try the [this](https://github.com/AllenFang/react-bootstrap-table/issues/443#issuecomment-218800007) in your client and what's browser you used?

**Comment by AllenFang** [comment]
@amitkumarsingh, any feedback for this issues?

**Comment by amitkumarsingh** [comment]
@AllenFang See the screenshot i am still gettingg the same issue.
 
![screenshot from 2016-05-30 10 08 11](https://cloud.githubusercontent.com/assets/5790963/15639838/7775507a-264e-11e6-95b2-5b6239759fd1.png)

**Comment by AllenFang** [comment]
@amitkumarsingh, I really can't reproduce this issue follow [your example](https://github.com/AllenFang/react-bootstrap-table/issues/443#issuecomment-218757323)(because you missing something), so I wrote a [example](https://github.com/AllenFang/react-bootstrap-table/issues/443#issuecomment-218800007) and hope you can try it again...
