### ISSUE TITLE
Display data from nested objects

### ISSUE THREAD

**Issue by theWeird** [AllenFang/react-bootstrap-table#444]
I need to display data from hashes and arrays in the data objects coming out of a mongodb database.

The concrete email field I want to show looks like this:
```
emails: [
    {
        address: 'foo@bar.com', 
        verified: false
    }
]
```

In forms the field is expected to be named like this: emails.0.address
Is it possible to make nested data accessible like this?

**Comment by AllenFang** [comment]
@theWeird, sorry, it is impossible currently. The workaround is just flat the data before go into table. Hope I can support this feature in the future. Close it cause duplicated with #50
