### ISSUE TITLE
Adding a datepicker to inserting new rows

### ISSUE THREAD

**Issue by tofuboomboom** [AllenFang/react-bootstrap-table#449]
I'm looking to add a datepicker to the modal form, which would be a useful feature to have (different input types/components) but in the mean time, how would you recommend doing that without modifying your source code?

**Comment by AllenFang** [comment]
sorry @tofuboomboom, it's necessary to modify the source code. Because I'm busy on my work, so PR is welcome. if I've free time, I'll support it :)

**Comment by lbargery** [comment]
I've been using a date picker in my table using react-datepicker (https://github.com/Hacker0x01/react-datepicker). You can't set the date in the add dialog but you can then choose it afterwards in the cell. I just set the date on add to be today's date but you could choose anything sensible. You render the date picker in the dataFormat: (cell, row) method. Hope that helps for now!

**Comment by AllenFang** [comment]
@lbargery, Thanks for sharing :) hope I can support the datepicker on ```v3.0.0```

**Comment by AllenFang** [comment]
```v2.4.1``` enable to use date picker on row insert and cell editing, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/advance/edit-type-table.js#L38).  Feel free to ask me anything :)
