### ISSUE TITLE
Dynamically generated columns

### ISSUE THREAD

**Issue by tylerjryan** [AllenFang/react-bootstrap-table#450]
Do you know of a way to dynamically generate columns? I have something like this in mind (inside the `render` method):

```
const columns = ["name", "description", "age"];
return (
    <BootstrapTable data={someData}>
        <TableHeaderColumn isKey dataField="id">id</TableHeaderColumn>
        {columns.map(column => 
            <TableHeaderColumn dataField={column}>{column}</TableHeaderColumn>
        )}
    </BootstrapTable>
)
```

This seems like it would be a very efficient way of producing tables when you don't know the columns ahead of time. When I try to do this however, if receive this error:

```
react-bootstrap-table.min.js?3226:6 Uncaught TypeError: Cannot read property 'children' of undefined
```

This makes me think that react-bootstrap-table might not be implemented in such a way that it supports this. I just wanted to see your thoughts. 

Thanks for an awesome tool!

**Comment by AllenFang** [comment]
HI, try following way:
```js
return (
    <BootstrapTable data={someData} keyField='id'>
        {columns.map(column => 
            <TableHeaderColumn dataField={column}>{column}</TableHeaderColumn>
        )}
    </BootstrapTable>
)
```

**Comment by tylerjryan** [comment]
Ah I see. The problem is trying to create one column manually and the rest in the map. When all of them are created in the map, it works great. Thank you!

**Comment by leandrozapata** [comment]
Hellow, this this my code:

<BootstrapTable
        data={this.props.source} hover keyField={this.props.propertyKey} selectRow={selectRowProp} pagination={this.props.pagination} insertRow={true} columnFilter={true}>
        <TableHeaderColumn
          dataFormat={this.commandFormatter}
          width="70"
        />
        {this.props.columns.map(column => {
          return (
            <TableHeaderColumn
              key={index++}
              dataField={column.property}
              dataAlign="center"
              dataSort={column.sort}
              hidden={!column.visible}
            >
              {column.title}
            </TableHeaderColumn>);
        })
        }
      </BootstrapTable>

I need to create a first column for command actions like edit, delete, but i getting the same error, is not possible to me include all columns on map for dinamyc creation.

**Comment by AllenFang** [comment]
@leandrozapata, that's will throw some exception absolutely. But in my opinion, it should possible to make all columns dynamic creation.

**Comment by leandrozapata** [comment]
Thanks Allen, any suggerence for this case?

**Comment by leandrozapata** [comment]
Thanks Allan, I resolve the problem.

**Comment by rrameshkumar76** [comment]
This works fine to render the dynamically columns. The issue i have is that numeric datafilters do not work when built dynamically.

**Comment by kabala** [comment]
Thank you for the solutions. You all are awesome!

**Comment by Ketandadpe** [comment]
I am trying to generate dynamic columns according to date range selection. If i select date from 10 aug to 20 aug, then it should show 10 columns under month column ....likewise.I am getting no. of days after selecting date range then  how can i generate columns dynamically?

**Comment by smilingpigs** [comment]
Hi, I need to use some dataFormat for some of the columns, is there any hack so that we can squeeze it for these dynamic columns?

**Comment by smilingpigs** [comment]
Hi, this is my code
`<BootstrapTable data={ this.props.data.students } keyField='id' height='600' bordered={ false } striped hover condensed>
                <TableHeaderColumn dataField='firstName' dataFormat={this.linkFormatter}>Name</TableHeaderColumn>
                <TableHeaderColumn dataField='rollNo'>Roll Number</TableHeaderColumn>
                  {columns.map(column =>
                      <TableHeaderColumn dataField={column.obtained_marks}>{column.subjectName}</TableHeaderColumn>
                  )}
                  <TableHeaderColumn dataField='obtainedMarks' dataFormat={this.markFormatter}>Total Marks</TableHeaderColumn>
              </BootstrapTable>`

Inside map, datafield = {column.obtained_marks} doesnt fetch me any data. Apart from this all are working fine. Is this a correct way for the datafield?

**Comment by smilingpigs** [comment]
<BootstrapTable data={ this.props.data.students } keyField='id' height='600' bordered={ false } striped hover condensed>
                <TableHeaderColumn dataField='firstName' dataFormat={this.linkFormatter}>Name</TableHeaderColumn>
                <TableHeaderColumn dataField='rollNo'>Roll Number</TableHeaderColumn>
                  {columns.map(column =>
                <TableHeaderColumn dataField={column.obtained_marks}>{column.subjectName}</TableHeaderColumn>
                  )}
                  <TableHeaderColumn dataField='obtainedMarks' dataFormat={this.markFormatter}>Total Marks</TableHeaderColumn>
</BootstrapTable>

Inside map, datafield = {column.obtained_marks} doesnt fetch me any data. Apart from this all are working fine. Is this a correct way for the datafield?

**Comment by smilingpigs** [comment]
`<BootstrapTable data={ this.props.data.students } keyField='id' height='600' bordered={ false } striped hover condensed>

                <TableHeaderColumn dataField='firstName' dataFormat={this.linkFormatter}>Name</TableHeaderColumn>

                <TableHeaderColumn dataField='rollNo'>Roll Number</TableHeaderColumn>

                  {columns.map(column => 
                      <TableHeaderColumn dataField={column.obtained_marks}>{column.subjectName}</TableHeaderColumn>
                  )}

                  <TableHeaderColumn dataField='obtainedMarks' dataFormat={this.markFormatter}>Total Marks</TableHeaderColumn>

              </BootstrapTable>`

Hi, I got array of objects in my 'columns', everything works fine expect {column.obtained_marks} inside the map. Is this the correct way to write it? @AllenFang because it doesnt fetch me any data.

**Comment by AllenFang** [comment]
@smilingpigs is there any error when you use ` {column.obtained_marks}` inside the map?

**Comment by smilingpigs** [comment]
@AllenFang No, nothing on the console.

**Comment by AllenFang** [comment]
HI @smilingpigs so where's broken? I mean what's actual problem you have?

and i usually suggest to wrap all the `TableHeaderColumn` into `map` function 👍 
```js
<BootstrapTable data={someData} keyField='id'>
        {columns.map(column => 
            <TableHeaderColumn dataField={column}>{column}</TableHeaderColumn>
        )}
    </BootstrapTable>
```

**Comment by smilingpigs** [comment]
Yes mine too, wrapped into map function.
What I am doing is displaying the subject name as table headers and datafield to be respective marks for the subject.
But the marks are not getting fetched. Its blank.
@AllenFang

**Comment by NilapuAnusha** [comment]
When I use like how @AllenFang  mentioned
`return (
    <BootstrapTable data={someData} keyField='id'>
        {columns.map(column => 
            <TableHeaderColumn dataField={column}>{column}</TableHeaderColumn>
        )}
    </BootstrapTable>
)`

Got error

> **'columns' is not defined**

**Comment by smilingpigs** [comment]
So yeah did you define the columns?
For example: const columns = ["name", "description", "age"];

**Comment by NilapuAnusha** [comment]
@smilingpigs I don't know exactly which columns will be in response. How can I handle this case?

**Comment by smilingpigs** [comment]
Oh you fetching it from db? And the columns are dynamic?

**Comment by Rekha-B** [comment]
Please let me know how to render json columns and  data from response dynamically, As I am not aware of columns and data which I get as a response?

**Comment by NilapuAnusha** [comment]
You can try this way.


    `
      getColumns () {
          let list = []
          for (let i = 0; i <= this.props.companies.length; i++) {
              for (let key in this.props.companies[i]) {
                  if (list.indexOf(key) === -1) {
                     list.push(key)
                  }
              }
          }
          return list
      }
      <BootstrapTable data={this.props.companies} keyField='id' striped hover condensed 
                  trClassName='bootstrap-table-tr' options={{onRowClick: this.onRowSelect}}>
                      {this.getColumns().map((column, index) =>
                             <TableHeaderColumn dataField={column} dataAlign='center' width=
                              {this.getWidth(column)} key={index} dataFormat={this.rowFormatter} dataSort={true}>
                              {(column.substring(0, 1).toUpperCase() + column.substring(1)).split(/(?=[A-Z])/).join(' 
                              ')}</TableHeaderColumn>
                      )}
    </BootstrapTable>
`

**Comment by Rekha-B** [comment]
Thank you for the solution.

**Comment by Rekha-B** [comment]
May I know, how to identify which column is clicked ? 
I have a json with nested objects which I need to expand it and show them as a child table for parent column, similar to the example that is present in  

[https://allenfang.github.io/react-bootstrap-table/example.html#expand](url)

In the above specified link, I am able to get it for row, but not for column specific.

**Comment by NilapuAnusha** [comment]
@Rekha-B Could you refer [here](https://allenfang.github.io/react-bootstrap-table/example.html#celledit) once and let me know whether it is useful or not. Referer **Custom Cell Edit** section.

**Comment by lawreyios** [comment]
Help ~!!

 ```
 renderSoldiers() {
      return (
          <div>
            <BootstrapTable
                data={ this.state.soldiers }
                pagination= { true }
                search= { true }
                >
              <TableHeaderColumn
                  dataField='id'
                  isKey
                  width='200px'
                  >
                Name
              </TableHeaderColumn>
              {this.state.milestones.map(milestone =>
                   <TableHeaderColumn dataField={milestone.name}>{milestone.name}</TableHeaderColumn>
               )}
            </BootstrapTable>
          </div>
      );
  }
```
This gives me `TypeError: Cannot read property 'isKey' of undefined` error.

I am trying to list soldiers with first column to be id/name then dynamically load the rest as columns. from Milestones.

**Comment by NilapuAnusha** [comment]
@lawreyios Could you please specify the data in **this.state**?
I think data is missed when you are refering **dataField=id**
`<TableHeaderColumn
                 dataField='id'
                 isKey
                 width='200px'
                 >`
