### ISSUE TITLE
Doubt:: How can we show an attribute of a composed dataField ?

### ISSUE THREAD

**Issue by leandromoreira** [AllenFang/react-bootstrap-table#451]
Let's suppose I want to show a composed object attribute:
```jsx
          <TableHeaderColumn dataField="project.type_name">TIPO</TableHeaderColumn>
```

Is this possible?

**Comment by leandromoreira** [comment]
duplicated https://github.com/AllenFang/react-bootstrap-table/pull/418 https://github.com/AllenFang/react-bootstrap-table/issues/50 https://github.com/AllenFang/react-bootstrap-table/issues/444

**Comment by AllenFang** [comment]
@leandromoreira, yes, hope I can have free time to fix this feature :+1:   So PR welcome.
