### ISSUE TITLE
Typescript definitions and missing documentation

### ISSUE THREAD

**Issue by scharf** [AllenFang/react-bootstrap-table#452]
I created a[ PR to improve the typescript definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9285) -- hoping that someone merges it. 

I used the documentation to create the definitions (using some emacs macros), but I discovered, that some important features are not documented. If you look at this [diff](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9285/commits/0da9b192f14f224cf6db7f3988ed569fa90e5b54), you see the undocumented features.

I am not sure if I am missing some of the properties.

**Comment by AllenFang** [comment]
@scharf, thanks your contribution, but I'm not sure what's that means for *missing documentation*, anything I need to do?, I'm very pleasure to improve it :)

**Comment by scharf** [comment]
The following properties in the diff are not documented:


### The attributes in `<BootstrapTable>`

```
		remote?: boolean,

		fetchInfo?:FetchInfo;

		tableStyle?: any;
		containerStyle?: any;
		headerStyle?: any;
		bodyStyle?: any;
```

#### in the options the following attributes are not documented:

```
		     paginationShowsTotal?: boolean;
		
		     onSearchChange?: Function;
		     onAddRow?: Function;
		     onExportToCSV?: Function;
		
		     insertText?: string;
		     deleteText?: string;
		     saveText?: string;
		     closeText?: string;
```

### The attributes in `<TableHeaderColumn>`

 ```
		onSort?: Function;
		csvFormat?: Function;
		
		columnTitle?: boolean;
		sort?: SortOrder;
		formatExtraData?: any;
```

For me the most important missing property was `BootstrapTableProps.remote`.

**Comment by AllenFang** [comment]
@scharf, sorry for lately reply, I'll add these missing documents in near future.

**Comment by AllenFang** [comment]
@scharf,  I've updated the docs. Thanks you :)
