### ISSUE TITLE
there is nothing in react-bootstrap-table

### ISSUE THREAD

**Issue by PPHAC** [AllenFang/react-bootstrap-table#453]
class EcsInfo extends React.Component `{`
    constructor(){
        super();
        this.state = { ecsData:[] };
    }
    
    componentDidMount(){
        ajax.get('http://115.28.114.190:8080/ms-hospital/v1/dept/hospital/code?code=6101000003')
            .end((error,response) => {
                if(!error&&response){
                    this.setState({ ecsData:response.body.data });
                    debugger
                    console.log("Success fetching form ECS!");
                }else{
                    console.log("Error fetching form ECS!");
                }
            }
        );
    }
    
    render() {
        if(this.state.ecsData!= undefined && this.state.ecsData.length > 0) {
            return(
                <BootstrapTable data={ this.state.ecsData } >
                    <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
                    <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
                    <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
                    <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
                </BootstrapTable>
                );
        }
        else{
            return 
            <p> nodata </p>
        }
    }
}
I got a table there,and  i got the ecsData,but there's nothing in it
I want to know why,thinks.

**Comment by AllenFang** [comment]
@PPHAC, I have no idea about that, please confirm following question
1. make sure render go into ```if(this.state.ecsData!= undefined && this.state.ecsData.length > 0) {``` after receive data.

2. any error message in browser console?

**Comment by PPHAC** [comment]
@AllenFang ,I‘ sure that render go into if(),because there is a table in browser ,the table has head ,but there'nothing in cell.And  in browser console, it  just  show  "Success fetching form ECS!".
And I found there is a similar quertion on stack:
http://stackoverflow.com/questions/32020237/react-bootstrap-table-with-ajax-data
think you

**Comment by AllenFang** [comment]
@PPHAC, could you please try to fix like following:
```
constructor(props)  {
    super(props);
    this.state = { ecsData:[] };
}
```

I'm not sure if it work, I am going to write some example

**Comment by AllenFang** [comment]
@PPHAC, I try the following code, and it's work 
```js
require('../node_modules/react-bootstrap-table/css/react-bootstrap-table-all.min.css');
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import {BootstrapTable, TableHeaderColumn} from 'react-bootstrap-table';

var products = [];

function addProducts(quantity) {
  const startId = products.length;
  for (let i = 0; i < quantity; i++) {
    const id = startId + i;
    products.push({
      id: id,
      name: 'Item name ' + id,
      price: 2100 + i
    });
  }
}

addProducts(5);


class MyTable extends Component {

  constructor(props) {
    super(props);
    this.state = {
      ecsData: []
    };
  }

  componentDidMount() {
    setTimeout(() => {
      this.setState({
        ecsData: products
      });
    }, 5000);
  }

  render () {
    return (
      <BootstrapTable data={ this.state.ecsData }>
          <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
        </BootstrapTable>
    );
  }
}

ReactDOM.render(<MyTable />, document.getElementById("basic"));
```

**Comment by PPHAC** [comment]
Thank you for that.I have solved that problem.There was just no 'id' dataField in esdData.Then I want to insert a button on each row.But I can't find an API to insert an column or something like <Td>

**Comment by AllenFang** [comment]
@PPHAC, great job! For customize you columns, just use ```dataFormat```, check [this](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/column-format)

**Comment by VarunVaro** [comment]
> 
> 
> @PPHAC, I have no idea about that, please confirm following question
> Firstly, make sure render go into `if(this.state.ecsData!= undefined && this.state.ecsData.length > 0) {`
> Second, any error message in browser console?

Hi AllenFang, I am new to react-bootstrap-table. I need your input. I have data column named "email" , i am using radio as selection mode for Row. when selection of row new Modal will open with data of selected row, i do change email there in modal and save. the data which i modified in modal it's not change in Table, may i know what's the reason and how to update the table?
