### ISSUE TITLE
Control position of components (pagination, export button, ...)

### ISSUE THREAD

**Issue by fabarea** [AllenFang/react-bootstrap-table#456]
I didn't find the answer whether it is possible to define the position of components / widgets. For instance, I would like to place the export button at the bottom of the table (and not at the bottom as currently display). I don't see the config key in the [docs](http://allenfang.github.io/react-bootstrap-table/docs.html)

**Comment by AllenFang** [comment]
@fabarea, sorry for ```react--bootstrap-table``` does not support to define the position of these component, I know actually it should be, so hope I've free time to enhance this, however, PR is welcome. I'll close this issues because duplicated with #409. 

Feel free to discuss with me on #409.  Thanks your feedback.
