### ISSUE TITLE
insertRow doesn't work if bootstrap and jquery installed via npm

### ISSUE THREAD

**Issue by dp-huang** [AllenFang/react-bootstrap-table#458]
Instead of directly importing jquery and bootstrap library in html tag, I tried to install them via npm, in this case, the New button after turn on insertRow={true} won't pop up dialog somehow.

**Comment by AllenFang** [comment]
@dp-huang, could you please confirm your version of bootstrap via npm? Because I use this ```react-bootstrap-table``` on my other web project and also install bootstrap(integrated by ```bootstrap-loader```) and jquery via npm, that's all fine.

So I thinks it's not a real issue, feel free to discuss with me. Thanks
