### ISSUE TITLE
Grouping rows

### ISSUE THREAD

**Issue by lioralt** [AllenFang/react-bootstrap-table#460]
Hi,
Is it possible to dynamically group rows by a specific column ?
Also, is it possible to expand/collapse rows with react-bootstrap-table ?

thanks.

**Comment by AllenFang** [comment]
> Is it possible to dynamically group rows by a specific column ?

I'm not sure what's that, so any description or examples?

BTW, expand row has been wished on #362. Anyway, I'm busy on my work currently, so just can do some little fixing or patching, sorry about that I can't support these useful feature in near future. Maybe I'll do it if there has some free time, so PR is welcome :)

**Comment by AllenFang** [comment]
in ```v2.6.0```, we support expand row, check [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/expandRow.js). We will update document in these day
