### ISSUE TITLE
Question: Can we hide some fields in InsertRow modal?

### ISSUE THREAD

**Issue by ahmedprohic** [AllenFang/react-bootstrap-table#461]
I need to hide some fields like Action, ID in insert row. If I set _editable_ property to false field won't be editable but it's still shown. Thanks!

**Comment by AllenFang** [comment]
@ahmedprohic, sorry, for lately reply. Currently, there's no any configuration to hide these columns, But maybe I can add this feature in near future.

**Comment by AllenFang** [comment]
@ahmedprohic, support on ```v2.3.3```. Use ```hiddenOnInsert``` on ```<TableHeaderColumn>```

**Comment by ahmedprohic** [comment]
Thank you very much!

**Comment by mattslight** [comment]
awesome - I came here looking for this. Thank you.
