### ISSUE TITLE
paginationShowsTotal custom text

### ISSUE THREAD

**Issue by evilnemesis** [AllenFang/react-bootstrap-table#462]
Hi,
is it possible enter custom "paginationShowsTotal" text?
if not, it would be great to do it :)

**Comment by AllenFang** [comment]
> is it possible enter custom "paginationShowsTotal" text?

HI @evilnemesis, what's the means for ```paginationShowsTotal```? you means I need support to add a button which could display the total pages?

**Comment by evilnemesis** [comment]
Hi @AllenFang , I did't mean button for showing total rows text but possibility to enter custom text for "Showing rows 1 to 15 of 100" because of localization (language). I was not able to find this option in documentation. thx

**Comment by AllenFang** [comment]
HI @evilnemesis, sorry for my wrong understand, and there's no any configuration to change the text. Maybe I can support it in near future. But I'm busy on my work so that I'm not sure when I can support. 
Anyway, PR is welcome

**Comment by AllenFang** [comment]
@evilnemesis, supported on ```v2.3.3```, check [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/pagination/custom-pagination-table.js#L43).

Now, paginationShowsTotal accept a bool value or a function, if a function you need return your customize JSX.
