### ISSUE TITLE
Add ability to return unselected rows in `onSelectAll`

### ISSUE THREAD

**Issue by tylerjryan** [AllenFang/react-bootstrap-table#466]
In the `onSelectAll` handling, two arguments are passed: `isSelected` and `currentSelectedAndDisplayData`. In the case where the user is UN-selecting all, there is currently no way of knowing which rows of the table are being unselected because `currentSelectedAndDisplayData` is an empty array. This unfortunately makes it impossible to write a handler that is aware of the rows that are being unselected. I do understand that this could be inferred, but there is a particular reason why I need this. 

In the case of a single row being unselected, the `onSelect` callback does pass the row being unselected. Would it be possible to mirror this functionality in the `onSelectAll` by returning the unselected rows in the callback?

Let me know if this makes sense. Thanks!

**Comment by AllenFang** [comment]
HI @tylerjryan, sorry for lately reply. I'll thinks about that and maybe released in near future. Thanks :+1:

**Comment by tylerjryan** [comment]
Great, thank you very much! Nice work on this library!

**Comment by AllenFang** [comment]
Released on ```v2.3.3```, check [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/select-hook-table.js#L34). Thanks :)

**Comment by tylerjryan** [comment]
Awesome, very glad that you liked the idea, and thank you for implementing
this!
