### ISSUE TITLE
Add footer at the bottom of the table to show Total

### ISSUE THREAD

**Issue by ShrivastavAnurag** [AllenFang/react-bootstrap-table#467]
Is it possible to add a footer at the bottom of the table to show table of all the rows. And also it should be fixed and no sorting apply for it. Please help how can I achieve this.

**Comment by AllenFang** [comment]
hi @ShrivastavAnurag, sorry for lately reply. 

> Is it possible to add a footer at the bottom of the table to show table of all the rows

what's that meas? show the total row numbers?



> And also it should be fixed and no sorting apply for it

I can't got you, could you please describe it again more detail?

Thanks

**Comment by ShrivastavAnurag** [comment]
Hi Allen,

Thanks for the reply.

I have attached a snippet of the table and the thing which i want in the
footer of the table. It may help you to understand the problem.

I want the total row at the footer of the table which is showing in the
image attached. Can this be done in Watable plugin?





-- Regards
Anurag Shrivastav

**Comment by AllenFang** [comment]
I probably knowing your question, but where's the image attached?
BTW, I guess your expectation it's impossible to write a plugin to achieve it, need modify the source code

**Comment by ShrivastavAnurag** [comment]
Ok.

Thanks Allen. I will try to modify the source code to achieve this.

-- Regards
Anurag Shrivastav

**Comment by AllenFang** [comment]
Feel free to ask my anything, just close it.

**Comment by ShrivastavAnurag** [comment]
ya sure Allen,

Thanks.

-- Regards
Anurag Shrivastav

**Comment by Lilion12** [comment]
Hey Allan,

We're trying to achieve the same thing, ie. a fixed footer to the bottom of the table, i don't see why it wouldn't be possible as your component already splits the tbody and thead in two separate divs? 

Can you be more precise on why it's not possible?

Cheers,
Lilion12

**Comment by AllenFang** [comment]
In #497, I've plan to make customization more better. But @Lilion12, if you want to attach something in table footer, is upper than pagination?

**Comment by Lilion12** [comment]
hey @AllenFang , it would be just at the bottom of the table, before pagination, just like bootstrap table...
