### ISSUE TITLE
When you override the text of the Export CSV button it doesn't override the icon

### ISSUE THREAD

**Issue by snowzach** [AllenFang/react-bootstrap-table#469]
I use bootstrap in my project but not the glyphicons. When I override the text of the ExportCSV button, it still has a bad link to the icon. Can you make it so it overrides that also?

**Comment by AllenFang** [comment]
hi @snowzach, yes your are right, I just replace the button text only and I've no any plan to do this. But I'm not familiar with ```glyphicons```, because in my impression, ```glyphicons``` will be included into ```bootstrap```, so what's means for ```bad link to the icon```

**Comment by snowzach** [comment]
The glyphicons are the default icons included with bootstrap. A lot of people like to use other icons like font-awesome. I created a pull request that will override the icons as well when you set it.

Pull Request: https://github.com/AllenFang/react-bootstrap-table/pull/476

**Comment by harikrishna1213** [comment]
how to override the text of Export CSV Button

**Comment by ghost** [comment]
@harikrishna1213 Have a look at exportCSVText property on options field.
http://allenfang.github.io/react-bootstrap-table/docs.html#exportCSVText
