### ISSUE TITLE
How to clear filter text

### ISSUE THREAD

**Issue by yenhsiac** [AllenFang/react-bootstrap-table#470]
Hello Allen,

What is the best way to clear user entered filter text?

Thanks,
Claire

**Comment by AllenFang** [comment]
@yenhsiac, if clear the text in filter will cause a filtering again, so is that what you wants? if yes, maybe I can discuss with u to find a better solution

**Comment by yenhsiac** [comment]
Hi Allen,

Thanks for your response. In our use case, we have a reset button. Right now it clears all the user input from our forms, also data in the table, but not the filtered texts in the table. We want to be able to clear the filtered texts. Since we clear the data, it does not matter to us if the filtering is triggered again or not. Thanks!

Claire

**Comment by AllenFang** [comment]
@yenhsiac, if I expose an API from ```BootstrapTable``` and you can call this exposed function to clear text, how about that?

**Comment by yenhsiac** [comment]
Sounds good. Thank you very much!

**Comment by jfougere** [comment]
I'm interesting in this too. Any idea when this is planned ? ;)

**Comment by AllenFang** [comment]
hi @jfougere, I want to expose a function from ```<BootstrapTable>```, when you call this function will clear the condition on filter. Hope I've time to do this PR and released in near future

**Comment by AllenFang** [comment]
Sorry for waiting so long. This feature has been fixed and released on ```v2.4.0```.  Check this [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/all-filters.js#L62). Thanks :)
