### ISSUE TITLE
Datepicker in datatable?

### ISSUE THREAD

**Issue by AndroidDoctorr** [AllenFang/react-bootstrap-table#471]
Is there a way to make an editable date column in this datatable that uses a datepicker?
I'm trying to use the text input that shows up by default, and I can validate the date on saving, but I can't figure out how to format it for saving or for display in the text input. A datepicker would be easiest... is there maybe a way to override the onClick method with a custom method for that column?

**Comment by AllenFang** [comment]
HI @AndroidDoctorr, sorry for lately reply. I know it's a very important feature, but I'm busy on my work, hope I can support this feature in near future. So PR is welcome :)

I'll close this because duplicated with #449 

Feel free to discuss with me :)

**Comment by AllenFang** [comment]
```v2.4.1``` enable to use date picker on row insert and cell editing, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/advance/edit-type-table.js#L38)
