### ISSUE TITLE
Problem with dataFormat={enumFormatter}

### ISSUE THREAD

**Issue by dellasys** [AllenFang/react-bootstrap-table#474]
Hi,

I have a problem doing advanced column filtering. First, my table seems work but after adding `dataFormat={enumFormatter}` into the header, my column data become empty. Does anyone know which steps I am missing?
Below is my code:

`const statusType = {`
       `0: 'Absent',`
       `1: 'Attended'`
`};`

`function enumFormatter(cell, row, enumObject){`
        `return enumObject[cell];`
`}`

`export default class Registration extends TrackerReact(React.Component)  {`

`render(){`
		`return(`
			`<div>`
				`<BootstrapTable data={Users} striped={true} hover={true} pagination={true} search={true} exportCSV={true}>`
			      `<TableHeaderColumn dataField="status" dataFormat={enumFormatter} formatExtraData={statusType} filter={{type: "SelectFilter", options: statusType}}>Status</TableHeaderColumn>`
  				`</BootstrapTable>`
			`</div>`
		`)}}`

**Comment by dana2208** [comment]
I think you miss the formatExtraData where you pass the enum object.

**Comment by dana2208** [comment]
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-format/extra-data-column-format-table.js

**Comment by dellasys** [comment]
Hi Dana,

Thanks for your reply. But I do have the formatExtraData in table header column and I pass in the statusType variable as stated in code.

**Comment by dellasys** [comment]
Ok, so finally I figured it out. The problem is the value I filtered was not numeric id. So I change it to 

`var statusType = {`
	`"Absent": "Absent",`
	`"Attended": "Attended"`
`};`

in order to work for my situation.

**Comment by AllenFang** [comment]
@dellasys, that's good news, so any problem or question on this issue?

**Comment by Abhijeet1440** [comment]
not solve
