### ISSUE TITLE
HandleSearch using react-router

### ISSUE THREAD

**Issue by adamsaper** [AllenFang/react-bootstrap-table#475]
I apologize if this is the wrong place to ask this. 

I want to have a search bar in my application that is attached to the main navigation header.
What is the best way to access the table ref in order to call the HandleSearch function? 
I am using react-router to render the child components. 

Thanks for your help.

**Comment by AllenFang** [comment]
hi @adamsaper, sorry for lately reply, could you please show me your simple codes?
I almost knowing your problem, but just want to make sure.  Anyway, I've not gave a try for how to get the ```ref``` which wrapped inside the ```Router```, maybe you can find some solution in react-router community. In my opinion, you can handle the search by yourself, I means just get the search condition and do the filtering on your ```store``` or ```reducer```(if you use flux or redux) and pass the final result to the component which contain the ```react-bootstrap-table```.

Feel free to discuss with me :)
