### ISSUE TITLE
Display selectrow checkbox by condition

### ISSUE THREAD

**Issue by tarim** [AllenFang/react-bootstrap-table#477]
Hi There,

Is that possible to display selectrow checkbox dynamically by condition(status, value etc)??

Thank you,

**Comment by AllenFang** [comment]
Use default select, you need manage selection on externally, there're two examples,
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/externally-managed-selection.js
http://allenfang.github.io/react-bootstrap-table/advance.html#dynamic-select

Feel free to discuss with me :)

**Comment by tarim** [comment]
Hi Allen,

What I want to do is, display checkbox by condition, not for selected checkbox by condition.

Thanks,

**Comment by AllenFang** [comment]
@tarim, sorry, there's no way to do it. is that very important features for you?

**Comment by tarim** [comment]
Hi Allen,

I need batch update functionality. So, I need custom button and checkbox. I don't know how to add those. Need your help.

Thanks,
