### ISSUE TITLE
Is there a way to handle a cell click event without the cell being editable? 

### ISSUE THREAD

**Issue by alexwhb** [AllenFang/react-bootstrap-table#478]
I'm trying to figure out a way to get a click event from one of the table cells, but all I see is the onRowClick handler. Is there one I'm not seeing? or is this not currently a feature?

**Comment by AllenFang** [comment]
hi @alexwhb, you can use ```dataFormat```, ```dataFormat``` accept a string as HTML or a react component, therefore you can do anything on it, include event.

Thanks :)

**Comment by alexwhb** [comment]
@AllenFang Thank you so much! that's exactly what I needed.

**Comment by vigneshkvw** [comment]
hi @AllenFang, using dataformat i placed  an edit button to edit the row in  new page by passing unique id.but while routing i get same _id
