### ISSUE TITLE
Add bower support

### ISSUE THREAD

**Issue by Tjorriemorrie** [AllenFang/react-bootstrap-table#48]
Can you please make this front-end library work with a front-end manager...

How do I use this library without node.js? It doesn't even work with browserify: I'm including what your installation depicts:
```
var ReactBsTable = require("./node_modules/react-bootstrap-table");
var BootstrapTable = ReactBsTable.BootstrapTable;
var TableHeaderColumn = ReactBsTable.TableHeaderColumn;
```

But it gives the error:
> ReferenceError: ReactBsTable is not defined

**Comment by AllenFang** [comment]
It's impossible not work with browserify, and your import is wrong, the following is correct import:

<pre>
var ReactBsTable  = require('react-bootstrap-table');
</pre>
