### ISSUE TITLE
Row validation during Select All 

### ISSUE THREAD

**Issue by francisfai** [AllenFang/react-bootstrap-table#480]
Hi 

How do you use select all (checkbox) and at the same time validate and leave some of the rows that you don't want to be checked.'

Thanks

**Comment by AllenFang** [comment]
@francisfai, I think give an hook for you is maybe a good solution

**Comment by AllenFang** [comment]
Released on ```v2.3.3```. Check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/select-validation-table.js)

**Comment by francisfai** [comment]
kool thank you Allen
