### ISSUE TITLE
How to hide pagination when there is only one page?

### ISSUE THREAD

**Issue by Axighi** [AllenFang/react-bootstrap-table#484]

**Comment by AllenFang** [comment]
@Axighi, sorry there's no way. Maybe I can make this configurable, because you set ```pagination``` to true which means you want the pagination so I didn't think about this condition.

**Comment by AllenFang** [comment]
Use ```ignoreSinglePage``` on ```<BootstrapTable>```.  Update to newest version. Thank 👍

**Comment by ronaiza-cardoso** [comment]
how do I use this?
```
 <BootstrapTable
                    {...this.props}
                    keyField={'gridId'}
                    data={this.state.data}
                    columns={this.state.columns}
                    bordered={false}
                    loading={true}
                    selectRow={selectRow}
                    rowEvents={rowEvents}
                    onTableChange={this.handleTableChange}
                    remote={{ sort: true }}
                    ignoreSinglePage
                    pagination={paginationFactory(options)}
                />
```

**Comment by paulmerlyn** [comment]
I wasn't able to hide the page number on the first page when there is only one page using the ignoreSinglePage attribute of <BootstrapTable />. However, I did manage to apply this work around in case anyone else is looking for a solution:

**Step 1: Give the pagination attribute a dynamic value, derived from a class method:**
`    createDataTable = () => {
        return (
            <BootstrapTable
                pagination = { this.setPaginationOptions() }`

**Step 2: Declare your paginationOptions object:**
`    paginationOptions = {
        sizePerPage: 10,
        hidePageListOnlyOnePage: true,
        showTotal: false,
        hideSizePerPage: true,
        onPageChange: (page, sizePerPage) => {
            this.paginationOptions.page = page;
        },
    }`

**Step 3: Identify the number of items on your first page (e.g. store that count in state):**
`                this.setState({ accountCount: response.data.accounts.length });    // response.data.accounts is the result of an AJAX call in my example
`

**Step 4: Declare the setPaginationOptions() method in your React class:**
`    setPaginationOptions = () => {
        if (this.state.accountCount > this.paginationOptions.sizePerPage) {
            return paginationFactory(this.paginationOptions);
        } else {
            return null;
        }
    }`

P.S. thanks @AllenFang for creating this incredible utility!
