### ISSUE TITLE
Setting column header in csv file

### ISSUE THREAD

**Issue by simonhsu** [AllenFang/react-bootstrap-table#485]
Is there a way to set each column's header in the csv file ?

The default column header in csv file is using the value of **dataFiled** in `<TableHeaderColumn />`
But I want to customize it or just use the value between `<TableHeaderColumn>` and `</TableHeaderColumn>` 
( just like the concept of WYSIWYG - What You See Is What You Get )

Thanks in advanced.
Anybody help?

**Comment by AllenFang** [comment]
@simonhsu, It's a good idea, I'll add a prop on ```TableHeaderColumn``` for you to customize. Thanks

**Comment by AllenFang** [comment]
@simonhsu, released on ```v2.3.4```. Use ```csvHeader``` on ```<TableHeaderColumn>```
