### ISSUE TITLE
Hide pagination size selector dropdown

### ISSUE THREAD

**Issue by razagill** [AllenFang/react-bootstrap-table#487]
Hi, 
Great work @AllenFang. I was wondering if there was a way to hide the pagination size selector dropdown completely?

**Comment by AllenFang** [comment]
@razagill, I can support it in near future.

**Comment by razagill** [comment]
@AllenFang thanks. Any safe way to do it right now? Will removing it from the source would have any impact on anything else?

**Comment by AllenFang** [comment]
I need to confirm it, but you can give it a try.

**Comment by AllenFang** [comment]
```js
<BootstrapTable options={ { hideSizePerPage: true, ... } }>
```

Update to newest version

**Comment by razagill** [comment]
@AllenFang awesome!
