### ISSUE TITLE
error in selectRow className

### ISSUE THREAD

**Issue by itajaja** [AllenFang/react-bootstrap-table#488]
I believe this is a bug. Say I have my table with `trClassName="foo"` and `selectRow={{ className: "bar", ... }}` props. As it's clear from [this code](https://github.com/AllenFang/react-bootstrap-table/blob/master/src/TableRow.js#L56), when the row is selected, the class parameter will be `foobar`, instead of `foo bar` which is what I would expect. A workaround is to do `selectRow={{ className: "bar ", ... }}` but it feels kind of hacky. I can work on a fix if you agree

**Comment by itajaja** [comment]
I also suggest to use the [`classnames`](https://www.npmjs.com/package/classnames) package to handle class chaining

**Comment by AllenFang** [comment]
@itajaja, yes, it's a bug. ```react-bootstrap-table``` has been used ```classnames``` but some place did not used, it's also a improvement for handling class. Anyway, PR is welcome.
