### ISSUE TITLE
defaultSortName and SortName do not seem to work properly

### ISSUE THREAD

**Issue by joshadkins09** [AllenFang/react-bootstrap-table#489]
Hello,

I am new to developing with react and webpack and am porting an existing site I have to react and react-bootstrap-table is great. However, I want my table to be sorted by one of the fields by default the first time it loads and using the defaultSortName option does not seem to take care of this.  I'm able to feed it data and get a lot of the features to work, but can't get default sorting by a specified field.

My render function contains something like:

`
<BootstrapTable data={data}
	                    condensed={true}
	                    hover={true}
	                   options={{defaultSortName:'Status'}}>
    <TableHeaderColumn dataSort={true} dataField='Name'>name</TableHeaderColumn>
    <TableHeaderColumn isKey={true} dataSort={true}                dataField='Status'>status</TableHeaderColumn>
</BootstrapTable>
`

Has anyone actually got this working?

**Comment by AllenFang** [comment]
HI @joshadkins09  you need assign ```defaultSortOrder``` also.
