### ISSUE TITLE
Table with only 1 column that is the key, does not allow it to render

### ISSUE THREAD

**Issue by tmosleydermpath** [AllenFang/react-bootstrap-table#49]
Console log of error message:

Uncaught TypeError: this.props.children.forEach is not a function

            <BootstrapTable data={dataSet} striped hover>
                <TableHeaderColumn dataField="id" isKey={true} dataAlign="center">ID</TableHeaderColumn>
            </BootstrapTable>

As soon as another column is added, the error message goes away.

Version #: 0.9.12

**Comment by AllenFang** [comment]
Hi @tmosleydermpath , I've fix this bug in newest version :)
