### ISSUE TITLE
columnTitle error

### ISSUE THREAD

**Issue by francisfai** [AllenFang/react-bootstrap-table#493]
Hi 

When columnTitle is set to true for a column (example notes column or comments column/etc on a table) that is initially empty or null and this is assumed to be populated by the user manually later.

Table does not render. The console error is: 

react-bootstrap-table.min.js:7 Uncaught TypeError: Cannot read property 'toString' of null  

If I remove columnTitle  or set it to false then table is rendered as per normal.

**Comment by AllenFang** [comment]
@francisfai, I'll check this out. Thanks :)

**Comment by francisfai** [comment]
kool thank you

**Comment by AllenFang** [comment]
Fixed on ```v2.3.5```

**Comment by francisfai** [comment]
kool Thank you Allen :)
