### ISSUE TITLE
Feature Request: Add Total Page Number Option

### ISSUE THREAD

**Issue by jflayhart** [AllenFang/react-bootstrap-table#495]
See this example:

https://github.com/AdeleD/react-paginate#props

Basically your options object would allow a "totalPageNum" or something that would be user-defined. So If your server has 1,000 users, and you show 20 users per page, then you would set "totalPageNum" to 50. Yes your plugin does this automatically IF you get all 1,000 users, but for us using server limits and offsets, I can only get 20 users at a time. So Now I have a table with only 20 users in it, but I need to show the web viewer they have more users to see based on the number of pages available to select (then I use your custom page click callbacks to get users based on the page selected).

With all your features for custom function callbacks and onPageClick call backs, this should already be in your plugin but I can't find it. I can see if I can submit a PR, but not sure how much time I have. Am I missing something and this is already implemented? Just seems an obvious feature to have with this feature-rich library you have.

I think there is some misunderstandings of english terms too, because I see `paginationSize` but that turns out to REALLY be more of a range of pages to display, not that ACTUAL size of pages to display. I might suggest to change some of that wording around.

I guess I am requesting to be able to override the `totalDataSize` value, so I can just throw in "1000" and all pages will show according to the other options used (in my example, 50 pages should show up).

**Comment by jflayhart** [comment]
After delving into more of the source code and your remote examples, I noticed you do have this feature (I thought you would). Thanks!

**Comment by AllenFang** [comment]
@jflayhart, yes, that's what you want :+1:

**Comment by luisfuertes** [comment]
Im seing `remote-paging.js` example, but dont know how could implement it.

```
            <BootstrapTable
              data={rows}
              striped={true}
              remote={true}
              deleteRow={ true }
              selectRow={ selectRowProp }
              options={ this.getOptions() }
              pagination={true}>
              <TableHeaderColumn dataField="id" isKey={true} dataAlign="center" dataSort={true}>ID</TableHeaderColumn>
              <TableHeaderColumn dataField="date" dataSort={true}>date</TableHeaderColumn>
              <TableHeaderColumn dataField="name" dataFormat={ this.dateFormatter } dataSort={true}>Name</TableHeaderColumn>
            </BootstrapTable>
            <RemotePaging
              onPageChange={ this.onPageChange.bind(this) }
              onSizePerPageList={ this.onSizePerPageList.bind(this) }
              { ...this.state }
            />
``` 

With `import { BootstrapTable, TableHeaderColumn, RemotePaging } from 'react-bootstrap-table';`

It should works? Can you give me a working example? Thanks!

**Comment by AllenFang** [comment]
hello @luisfuertes, sorry for lately reply. could you please describe your question that will helpful to me to help you?

Anyway, enable the ```remote``` prop which means you want to handle the data manipulation(ex: sort, insert, search, filter, pagin  etc.) on your server or flux instead of ```react-bootstrap-table``` self. so the example mentioned before, is a simple example which we handle the paging  outside of ```react-bootstrap-table```.

You can check [react component](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-paging.js) and its [store](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-paging.js) to see how it work.

Let me know if you still have any question :)

**Comment by luisfuertes** [comment]
Thanks for answer.

Yesterday i try did it with this example: https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-paging.js

But after i found this other example ( https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-paging.js ) and i can do it works.

But i dont understand how can apply the first example in a real <BootstrapTable /> element.
Only see the < RemotePaging />  in example but dont know how can i use with <BootstrapTable />

**Comment by AllenFang** [comment]
> But i dont understand how can apply the first example in a real < BootstrapTable /> element.
> Only see the < RemotePaging /> in example but dont know how can i use with < BootstrapTable />

```RemotePaging``` is just only a wrapper for ```BootstrapTable```, so in the ```remote-store-paging.js``` we render ```RemotePaging```.

**Comment by luisfuertes** [comment]
Oh ok, thanks for answer @AllenFang
