### ISSUE TITLE
Raw select only works when click on check box or radio button.

### ISSUE THREAD

**Issue by nuwanprabhath** [AllenFang/react-bootstrap-table#499]
In the web page http://allenfang.github.io/react-bootstrap-table/example.html under Row Selection section it is able to select a row by clicking anywhere in the row. But when I run demo in master branch, row can be only selected by clicking on the check box. How do I change it to click anywhere in raw to do  row selection?

**Comment by AllenFang** [comment]
@nuwanprabhath, enable ```clickToSelect```, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/click-to-select-table.js#L24)
