### ISSUE TITLE
Hiding a unique data column

### ISSUE THREAD

**Issue by holmancts** [AllenFang/react-bootstrap-table#5]
I have a situation where I have data with a unique key, but I don't want that data to be displayed in the table since it is as meaningless ID number. None of the other data in the table is unique by itself. I am forced to set a key with the current version, and I can't specify a unique combination of key columns. Would it be an easy improvement to allow a column to be declared as a key, but hide it from the table? Or to allow for more than one key where the combination is unique?

**Comment by AllenFang** [comment]
Hi @holmancts 
I think the "hidden column on table" is better solution for your situation.

I will start to plan and implement in recent, but it need some time :)

**Comment by AllenFang** [comment]
Hi @holmancts 

I've release v0.8.2 for supporting hidden column, just use <code>hidden={true}</code> in <code>TableHeaderColumn</code> will hide that column.

Thanks your suggestion ;)
