### ISSUE TITLE
unable to turn off border-collapse

### ISSUE THREAD

**Issue by pbrianmackey** [AllenFang/react-bootstrap-table#500]
I have this:
```
      <BootstrapTable
          data={this.props.model}
          tableStyle={ { border: '0', 'borderCollapse':'none !important', 'borderRadius': '0' } }
          containerStyle={ { border: '0', 'borderCollapse':'none', 'borderRadius': '0' } }
          headerStyle={ { 'lineHeight': '23px', 'borderCollapse':'none', 'fontSize': '12px', 'fontFamily': 'Arial,Helvetica,sans-serif', 'border': '0', 'borderRadius': '0' } }
          bodyStyle={{ border: '0', 'borderRadius': '0', 'borderCollapse':'none' }}
          tableHeaderClass='myheaderclass'
          striped={true}
          hover={true}
          bordered={true}
        >
```
The resultant output still has .table-bordered with border-collapse: separate.

**Comment by AllenFang** [comment]
@pbrianmackey, what's your purpose? set bordered={false} is not your expectation?
BTW, ```.table-bordered``` is from ```bootstrap```, maybe you can try to override it on global?

**Comment by pbrianmackey** [comment]
The purpose is to keep the borders, but remove the rounding of the corners.  The client wants square edges.

**Comment by AllenFang** [comment]
@pbrianmackey, I thinks override ```. table-bordered``` will be better, it cant be controlled directly by ```react-bootstrap-table```

**Comment by pbrianmackey** [comment]
Ok, I understand thanks for the feedback!
