### ISSUE TITLE
Question: is there a way to disable select on a particular row or rows?

### ISSUE THREAD

**Issue by L5eoneill** [AllenFang/react-bootstrap-table#502]
We need select checkboxes for delete operations, but have a "default" item that cannot be deleted and wish to NOT show a checkbox for that row. Seems something that could be handy for other uses as well (user can only edit some rows depending on some value). Is there any current way to accomplish that?

**Comment by AllenFang** [comment]
@L5eoneill, sorry for lately reply and ```react-bootstrap-table``` doesn't support this feature currently. I thinks it's a particular feature or requirement. BTW, I think this requirement is not very hard to implement, maybe you can try it. Feel free to ask me anything if have question. 

BTW, this inspire me a idea for supporting a unselect row. however, i thinks I can support it in near future, if it done, and you can hide the disable checkbox through css(I can give this disbled checkbox a classname). Maybe its a perfect workaround.

**Comment by L5eoneill** [comment]
Sweet! Excellent work, Allen. It works great (other than the "select all" checkbox will never indicate "all" are selected.)

By the way, to hide the disabled one, you'll need css saying input[type="checkbox"][disabled] { display: none;}

**Comment by AllenFang** [comment]
@L5eoneill, oh I forgot the select all, I'll patch it on next version. BTW, I think I just make the checkbox disabled, I dont want to hide it. Anyway, it's a customizable case for user. I'm planing to make the ckeckbox columns more customizable in ```v3.0.0```. ckeck #497
Thanks.

**Comment by AllenFang** [comment]
@L5eoneill, the select all bug has been fixed on ```v2.3.7```.
