### ISSUE TITLE
To reset the previous filter, if I change the columns in the table?

### ISSUE THREAD

**Issue by vladSumy** [AllenFang/react-bootstrap-table#503]
Many thanks for the component!
There is a table with a certain set of columns, then I change the set of columns and I need to reset the previous filter?
how to clear or set obj Filter?

**Comment by vladSumy** [comment]
and this.refs.table.handleFilterData({}) do not clear objFilter

**Comment by AllenFang** [comment]
@vladSumy, I'm thinking solution for this feature, but there's some issues need to do firstly. so it's need some time and I just close this issues cause of duplicated on #470. Just follow #470 in future.

**Comment by AllenFang** [comment]
Released on ```v2.4.0```, check this [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/all-filters.js#L62) to see how to clear filter. Thanks
