### ISSUE TITLE
undefined ref in adjustHeaderWidth

### ISSUE THREAD

**Issue by vinnyoodles** [AllenFang/react-bootstrap-table#505]
Hi Allen, thank you for this wonderful library. 

I'm getting a `Uncaught TypeError: Cannot read property 'refs' of undefined` error when `adjustHeaderWidth()` is called, at line `823`

![screenshot from 2016-06-14 16-02-47](https://cloud.githubusercontent.com/assets/8698599/16057761/7bae075c-3249-11e6-9e7f-f4f5fe9bde77.png)

It seems like `this.refs.header` is null, but I'm not sure why.

**Comment by vinnyoodles** [comment]
I'm using es6 syntax. This is my source file [table.es6.js](https://gist.github.com/vinnyoodles/c6106f2ec2bec351fb658ab4efb92acd)

**Comment by AllenFang** [comment]
it's strangely, is it happened frequently? and what's condition will cause this issue?
BTW, what's your browser and version of ```react-bootstrap-table```?

**Comment by vinnyoodles** [comment]
I'm using google chrome with `react-bootstrap-table` 2.3.4. I tried version 2.3.5 and had the same error

**Comment by vinnyoodles** [comment]
These are my dependencies

```
{
  "dependencies": {
    "browserify": "^10.2.6",
    "browserify-incremental": "^3.0.1",
    "jquery": "^2.2.3",
    "jquery-ujs": "^1.2.1",
    "moment": "^2.10.6",
    "moment-range": "^2.1.0",
    "react": "^15.1.0",
    "react-bootstrap-table": "^2.3.4",
    "react-input-calendar": "^0.3.7",
    "react-textarea-autosize": "^4.0.2"
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.5.0",
    "babelify": "^7.3.0"
  },
  "peerDependencies": {
    "react": "^0.14.3 || ^15.0.0",
    "react-dom": "^0.14.3 || ^15.0.0"
  },
  "keywords": [
    "browserify",
    "react",
    "rails",
    "npm"
  ]
}
```

**Comment by AllenFang** [comment]
```
Only a ReactOwner can have refs. You might be adding a ref to a component that was not 
created inside a component's `render` method, or you have multiple copies of React loaded 
```
if you remove ```react-bootstrap-table``` and clean the code with it, is this message still remain?

**Comment by vinnyoodles** [comment]
That message will not show when I remove `react-bootstrap-table`. If I keep the `react-bootstrap-table` npm package, but just remove this from the `render()` method

```
 return (
      <BootstrapTable data={products} striped={true} hover={true} pagination>
        <TableHeaderColumn isKey={true} dataField="id">Product ID</TableHeaderColumn>
        <TableHeaderColumn dataField="name">Product Name</TableHeaderColumn>
        <TableHeaderColumn dataField="price">Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
```

Then, all the errors also go away.

**Comment by AllenFang** [comment]
ok, um... it's very weird. do you have any simple repo for me to reproduce it?

**Comment by vinnyoodles** [comment]
Uhh, give me a minute and I'll set up a public repo for it

**Comment by vinnyoodles** [comment]
Okay, the repo is here https://github.com/vinnyoodles/rails-react-app. I scraped out a bunch, but the main react components are still there as well as the same errors.

**Comment by AllenFang** [comment]
ok, I'll try this out. Thanks

**Comment by dp-huang** [comment]
I once got the exactly the same problem, but after npm was upgraded to the latest version, it's gone.

**Comment by Draccan** [comment]
I have this problem too!

**Comment by Draccan** [comment]
Ok, I have solved the problem.

The main problem was:

 I had React: "^15.2.3" as a dependency in my package.json, but my react-bootstrap-table: "^2.5.3" has in his package.json: "react": "^0.14.3 || ^15.0.0".
So node was downloading and including with webpack two versions of React. The first specified in my package.json and the React 15.0.0 because of React Bootstrap Table.

I have solved the problem specifying in my package.json the version of React 15.0.0 asking to have this specific version. So I have "react":"15.0.0" without "^".

**Comment by AllenFang** [comment]
@Draccan, that's a good feedback.

**Comment by longsangstan** [comment]
I had the same problem too for 3.0.0 beta.
I faced the issue when I used react router to render my table.
But I have no idea how to reproduce the bug - I re-install again and the bug is gone. Strange.

**Comment by AllenFang** [comment]
Check newest `v2.9.2` and `v3.0.0-beta.7`, it is supposed to be fixed correctly. thanks
