### ISSUE TITLE
question: Is there a way to use my customize dialog when I use insertRow?

### ISSUE THREAD

**Issue by stoneNo** [AllenFang/react-bootstrap-table#509]
Hi Allen,

Is there a way to use my own dialog instead of you given when i use insertRow to add Rows？
I want add Rows, and I use the props: insertRow,  but the dialog is not i wanted.
thanks!

**Comment by AllenFang** [comment]
@stoneNo, it's impossible, I suggest you customize one by yourself, include insert button. BTW, in #497, I've announced the support for customization component in ```v3.0.0```. But it really need some times.

**Comment by AllenFang** [comment]
Anyway, you can add new row from your dialog or something like that and then update the table state or calling ```handleAddRow``` which exposed by ```BootstrapTable```.

**Comment by AllenFang** [comment]
Fixed on `v3.0.0`, check https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/custom/insert-modal

Let me know if you got any questions

**Comment by EktaDevop** [comment]
while adding row, in the modal if we add empty value, toast message is shown, can we customize this
