### ISSUE TITLE
Editing without Modal

### ISSUE THREAD

**Issue by leandrozapata** [AllenFang/react-bootstrap-table#510]
Hi, Exists any way to edit a row without modal?

**Comment by AllenFang** [comment]
@leandrozapata, ```react-bootstrap-table``` only edit cell on each time, and its be triggered by inline edit instead modal. I thinks the **insert row** without modal is your question, right?

**Comment by leandrozapata** [comment]
Thanks Allen, in my application i need to have custom modal for edit and
delete. For this motive i put in your table a command colum with edit and
delete, and another button with add action.

Your component not expose customs methos por edit a row?

Regards.

**Comment by AllenFang** [comment]
@leandrozapata,  just only per cell. I thinks a state update after saving edited row is your best choice.
