### ISSUE TITLE
bootstrap.js and jquery.js dependency

### ISSUE THREAD

**Issue by daisycao111** [AllenFang/react-bootstrap-table#511]
Hi,

I noticed that we need bootstrap.js and jquery.js as a global runtime dependency as the pagination size dropdown functionality.

My application needs reproducibility to up to 5 years. Adding global runtime dependency is hard to manage and not reliable when we want to reproduce our app in the long past.

Could you please remove the global runtime dependency on top of bootstrap.js or jquery.js as soon as possible?

This issue was previously discussed in this ticket: https://github.com/AllenFang/react-bootstrap-table/issues/197, but I believe it has not fixed yet.

Thanks.

**Comment by AllenFang** [comment]
yes, its not yet finish. And I've planned tackle this issue in ```v3.0.0```, check #497. Close it due to duplicated
