### ISSUE TITLE
header and body unalign on recent Chrome version

### ISSUE THREAD

**Issue by maximmuss** [AllenFang/react-bootstrap-table#512]
I have a problem with width of header and body - columns, when I change manually the width of browser and in start. The width of column-header and column-body aren't equal.

**Comment by AllenFang** [comment]
@maximmuss, which browser and ```react-bootstrap-table``` you used?

**Comment by maximmuss** [comment]
I use chrome v51.0.2704.103 m and react-bootstrap-table: 2.3.5

**Comment by tkandr** [comment]
Have the same issue in chrome Version 51.0.2704. In firefox it's ok. It doesn't a problem until you try to customize header :( 
![image](https://cloud.githubusercontent.com/assets/5516660/16444653/c997415a-3de7-11e6-9497-c4e73113f1d7.png)
![image](https://cloud.githubusercontent.com/assets/5516660/16444763/60b13302-3de8-11e6-8661-5a1bfa4e705c.png)

**Comment by AllenFang** [comment]
HI @maximmuss 

> change width the last column

is that a examples or a scenario for me to reproduce it?

**Comment by maximmuss** [comment]
Hi @AllenFang! It is example, but when I start change width last column I have problem

**Comment by mistercrunch** [comment]
I'm running a recent chrome and the latest npm release and have alignment issues between header and body as well.
<img width="1060" alt="screen shot 2016-07-24 at 7 42 48 am" src="https://cloud.githubusercontent.com/assets/487433/17084432/47386ea2-5172-11e6-8b0f-a21e6040ef52.png">

**Comment by AllenFang** [comment]
sorry for lately reply, @mistercrunch, is this issue happened at before in different chrome? and did you set width on  ```CITY``` column?

**Comment by blitzd** [comment]
I'm also running into this. I'm not explicitly setting any widths on columns. The problems seems that the header width just isn't matching the table body width on the columns.

**Comment by AllenFang** [comment]
hi all, actually I found this issue is related with recent chrome probably, because I also ran into this issue on chrome 52.x.

I'll still focus on this issue.

**Comment by sgentile** [comment]
I am seeing this as well - it happens when I put width on a column

![image](https://cloud.githubusercontent.com/assets/132404/17944743/034d7510-6a0f-11e6-821a-13b9b46710a3.png)

**Comment by maximmuss** [comment]
also I have problem when I have change in table-layout fixed on auto. How can I set "auto" for table-layout?
 
![image](https://cloud.githubusercontent.com/assets/19345163/18503937/4676858e-7a68-11e6-9289-8055c1fa6a54.png)

**Comment by AllenFang** [comment]
@maximmuss, I dont suggest to change ```table-layout``` to ```auto```. You will lose the horizontal scrollbar

**Comment by maximmuss** [comment]
I understand you. Thank you.

**Comment by venkat-vs-id** [comment]
I worked out a solution for header and data column misalignment issue. call the below function after rending the table. The below function adjusts the header column width and data-table column width programmatically. 

Everytime you render the ReactBootstrapTable, call this function and this works like a treat.

You also need to set the below CSS. remeber this logic works only with STRIPED data-tables. 

Explained in details here - http://venkat-echo.blogspot.com.au/2016/10/react-bootstrap-table-header-column_11.html
---------------------------------------------------------------------------------
div.react-bs-table-container{
    overflow: auto;
}

.table>thead>tr>th {
    background-color: #616161;
    color: white;
}
.table-hover>tbody>tr:hover{
    background-color:#E3EEF5;
}
.table{
   margin-bottom:0px;
}
.table-striped{
   width: auto;
}
.h1class{
    text-align:center
}

td, th {
    padding: 0;
    white-space: nowrap;
}
---------------------------------------------------------------------------------

function myReactBootstrapTable_adj(){

    //---fix the data table based on the header if the header size is greater than the column width(datatable)
    var tables = document.getElementsByClassName("table");
    console.log( "total no of tables", tables.length )
    console.log( tables )

    var l_header_table = null;
    var l_row_table = null;
    var l_wd = null;
    for ( var i = 0; i < tables.length; i++){
        console.log( "---total no of tables", tables.length )
        console.log( "tables ----------------------------------", i)
        if (i%2 == 0){ //header
            console.log("header", i)
            l_header_table = tables[i]
        }else{ // row table
            console.log("row", i)
            l_row_table = tables[i]
            var first_row = l_row_table.getElementsByTagName("TR")[0];
            var tds = first_row.getElementsByTagName('TD');
            var larr_col_size = []
            for ( var j = 0; j < tds.length; j++){ // width of each cell
                console.log( tds[j].innerText, tds[j].style.width, tds[j].style.offsetWidth, tds[j].getBoundingClientRect().width)
                larr_col_size.push(tds[j].getBoundingClientRect().width)
            }

            console.log(l_row_table )
            console.log(larr_col_size)
            console.log(l_header_table)

            var first_row = l_header_table.getElementsByTagName("TR")[0];
            var h_tds = first_row.getElementsByTagName('TH');
            for ( var k = 0; k < h_tds.length; k++){ // each cell
                console.log( h_tds[k].innerText, larr_col_size[k])
                l_wd = h_tds[k].getBoundingClientRect().width
                console.log( l_wd, ' ...>... ', larr_col_size[k] )
                if (  l_wd > larr_col_size[k]){// if header width is greater than row width then apply that to row
                    tds[k].style.width = l_wd+'px'
                    tds[k].style.minWidth  = l_wd+'px'
                }else{
                    tds[k].style.width = larr_col_size[k]+'px'
                    tds[k].style.minWidth  = larr_col_size[k]+'px'
                }

            }

        }
    }

    //---fix the header table based on column width in the data table
    var tables = document.getElementsByClassName("table");
    console.log( tables )

    l_header_table = null;
    for ( var i = 0; i < tables.length; i++){
        console.log( "tables *******************************************-", i)
        if (i%2 == 0){ //header
            console.log("header", i)
            l_header_table = tables[i]
        }else{ // row table
            console.log("row", i)
            l_row_table = tables[i]
            var first_row = l_row_table.getElementsByTagName("TR")[0];
            var tds = first_row.getElementsByTagName('TD');
            var larr_col_size = []
            for ( var j = 0; j < tds.length; j++){ // width of each cell
                console.log( tds[j].innerText, tds[j].style.width, tds[j].style.offsetWidth, tds[j].getBoundingClientRect().width)
                larr_col_size.push(tds[j].getBoundingClientRect().width)
            }
            console.log(l_row_table )
            console.log(larr_col_size)
            console.log(l_header_table)
            var first_row = l_header_table.getElementsByTagName("TR")[0];
            var h_tds = first_row.getElementsByTagName('TH');

            for ( var k = 0; k < h_tds.length; k++){
                console.log( h_tds[k].innerText, larr_col_size[k])
                l_wd = h_tds[k].getBoundingClientRect().width
                console.log( l_wd, ' __>__ ', larr_col_size[k] )

                h_tds[k].style.width = larr_col_size[k]+'px'
                h_tds[k].style.minWidth  = larr_col_size[k]+'px'
            }

        }
    }
}

exports.myReactBootstrapTable_adj = myReactBootstrapTable_adj; //public function

**Comment by AllenFang** [comment]
hi there, sorry for lately fixing, check `react-bootstrap-table@2.10.0-beta.1` by
```npm install react-bootstrap-table@2.10.0-beta.1``` and I thought this beta release already fixed couples unalign problem, if it work and stability, I'll consider to forward to production as soon as possible.

Let me know if the problems still there. thanks
