### ISSUE TITLE
how to get current table data after search or filter?

### ISSUE THREAD

**Issue by WangLarry** [AllenFang/react-bootstrap-table#514]
I want to count,sum,average.. table data after user search or filter table.how to get current table data after search or filter?

**Comment by AllenFang** [comment]
@WangLarry, I can exposed a function on ```<BootstrapTable>``` for this requirement.

**Comment by AllenFang** [comment]
@WangLarry, BTW, there's a way you can get filtered or search data, on ```afterColumnFilter``` and ```afterSearch``` hooks will return the result, you can use it.

**Comment by AllenFang** [comment]
@WangLarry, update to ```v2.3.6``` and try the following snippet
```js
getFilteredResult() {
    this.refs.table. getTableDataIgnorePaging();  //That's the result
}

render() {
    return (
        <BootstrapTable ref='table'...>
        </BootstrapTable>
    );
}
```

**Comment by WangLarry** [comment]
@AllenFang Thank you!

**Comment by kadariyp** [comment]
@AllenFang I have a table with search bar. How do i get the number of result in the table after search? I have added ref to the Bootstrap table but the filtered data length needs to be somewhere on search bar right? like onChange of that input or somewhere. so my question is where do i call that **getFilteredResult**() function

**Comment by AllenFang** [comment]
@kadariyp, try to call ```getTableDataIgnorePaging``` which exposed on ```<BootstrapTable>```

**Comment by kadariyp** [comment]
@AllenFang Thanks for the quick reply. I can see **getTableDataIgnorePaging**  function returns the total number of row on the grid. But since search bar is inbuilt, how do i set onChange() to it or when the user types something on it, call this function so that when the grid gets updated, this **getTableDataIgnorePaging** gets called and updates my state or props wherever i want to store it?

**Comment by AllenFang** [comment]
@kadariyp, use ```onSearchChange``` 


```js

handleSearchChange = (searchText, colInfos, multiColumnSearch) => {
  //... your stuff on here
}

render() {
    const options = {
        onSearchChange: this.handleSearchChange
    };
    return (
        <Bootstrap data={...} options={ options }
    );
}
```
check [docs](http://allenfang.github.io/react-bootstrap-table/docs.html)

**Comment by kadariyp** [comment]
@AllenFang Thanks.

**Comment by victoria100** [comment]
I read all above and applied. but it doesn't work. 
Please have a look and tell me what I missing.


`handleSearchChange (searchText, colInfos, multiColumnSearch) {
	  this.refs.getTableDataIgnorePaging();	 //'this' is undefined and I have no idea, how do I get current cell values
	}


    render(){
		const options = {
	        onSearchChange: this.handleSearchChange.bind(this),
	        onFilterChange : this.handleSearchChange.bind(this)
	    };
        return (
        	<div>
        		<h2>Daily Report</h2>
        		<div className="data_table">
					<BootstrapTable data={this.state.data} striped={true} hover={true} trClassName="tr-string" search={true} ref='table' options={options}>
						<TableHeaderColumn isKey={true} dataField="id" className="no" hidden={true} >No.</TableHeaderColumn>
						<TableHeaderColumn dataField="Campaign Name" dataSort={true} className="campaign_header" columnClassName="campaign_col" filter={{type: "TextFilter"}}>Campaign Name</TableHeaderColumn>
						<TableHeaderColumn dataField="Delivery Name" dataSort={true} className="delivery_header" columnClassName="delivery_col" filter={{type: "TextFilter"}}>Delivery Name</TableHeaderColumn>
						<TableHeaderColumn dataField="Delivery Channel" dataSort={true} className="channel_header" columnClassName="channel_col" filter={{type: "TextFilter"}}>Channel</TableHeaderColumn>						
						<TableHeaderColumn dataField="Sent" className="sent" columnClassName="sent_col">Sent</TableHeaderColumn>
						<TableHeaderColumn dataField="Delivered" className="delivered" columnClassName="delivered_col">Delivered</TableHeaderColumn>
						<TableHeaderColumn dataField="Opened" className="opened" columnClassName="opened_col">Opened</TableHeaderColumn>
						<TableHeaderColumn dataField="% Opened of delivered" className="openedrate" columnClassName="openedrate_col">% Opened</TableHeaderColumn>
						<TableHeaderColumn dataField="Clicked" className="clicked" columnClassName="clicked_col">Clicked</TableHeaderColumn>
						<TableHeaderColumn dataField="% Clicked of opened" className="clickedrate" columnClassName="clickedrate_col">% Clicked</TableHeaderColumn>
						<TableHeaderColumn dataField="Total Leads Generated" className="leads" columnClassName="leads_col">Leads</TableHeaderColumn>
						<TableHeaderColumn dataField="Interested" className="interested" className="interested" columnClassName="interested_col">Interested</TableHeaderColumn>
						<TableHeaderColumn dataField="Fulfilled" className="fulfilled" columnClassName="fulfilled_col">Fulfilled</TableHeaderColumn>
					</BootstrapTable>
				</div>
				
				Total Sent : {this.state.sum}
			</div>`
