### ISSUE TITLE
how to get bootstrap "detail-view" feature?

### ISSUE THREAD

**Issue by adobeflex1** [AllenFang/react-bootstrap-table#515]
Hi Allen,

Normal bootstrap table has the feature to expand a row and display a "detail view" of that row.
Is there a way to get the feature here?  

Thanks.

**Comment by AllenFang** [comment]
@adobeflex1, sorry, we don't support this feature and hope I've time to do in in future. close it due to duplicated with #362

**Comment by AllenFang** [comment]
@adobeflex1, in ```v2.6.0```, we support expand row, check [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/expandRow.js). We will update document in these day
