### ISSUE TITLE
It is not possible to force set scrollTop parameter on scrollable table.

### ISSUE THREAD

**Issue by spetex** [AllenFang/react-bootstrap-table#516]
Hi,

I want to scroll my table to the top whenever I change filters for that table. In order to do that I need access to the scrollTop parameter of the scroll container. So I have tried to find that using refs to my table. Unfortunately, there is none scrollTop parameter because the ref is set to container which is not scrolling and the scroll container itself is encapsulated and not accessible from outside.

I know I can ReactDOM.findDOMNode that scrollable element and change it, but I wanted to make it more React and use refs.

My proposition is to add a handler function for triggering scroll to position into the table interface.

What do you think?

**Comment by AllenFang** [comment]
@spetex, it's a good idea, how about pass the event object in that handler function? But remember the event also triggered if there's a horizontal scroll

**Comment by hermanfenderson** [comment]
@spetex did you find a solution in the end? I am facing quite a similar problem and a hint could be great...

**Comment by spetex** [comment]
@hermanfenderson We decided to take a different direction in our company and since the customer wanted far more stuff in the table we decided to create our own implementation. Unfortunately we write software on contract and I cannot publish the source. :-(

**Comment by hermanfenderson** [comment]
@spetex ok! Thank you anyhow...

**Comment by AllenFang** [comment]
Fixed on ```v2.7.0```. check https://github.com/AllenFang/react-bootstrap-table/issues/860#issuecomment-267064087
