### ISSUE TITLE
Select filter - wrong filtering

### ISSUE THREAD

**Issue by Najdan** [AllenFang/react-bootstrap-table#517]
There's a weird issue with select filter when I select one value and getting wrong filter results in table.

I think that problem is related to "key" from _qualityType_ (it's showing data in table for 1, and 17 which contains 1 inside). For unknown "key" is 2 and it's not shown as result of filtering.
`const qualityType = {
  1: 'bad',
  2: 'unknown',
  17: 'good'
};`

Check this gist - [Select filter.js](https://gist.github.com/Najdan/8cd51506965f4fc4bf6b82aa820863ad) 
Check next images:
**1. Bad selected with key 1 - this is wrong**
![2016-06-20 16_15_49-react-bootstrap-table demo](https://cloud.githubusercontent.com/assets/4264802/16197517/abef3496-3702-11e6-8bb7-0c31176d626b.png)
**2. Unknown selected with key 2**
![2016-06-20 16_16_16-react-bootstrap-table demo](https://cloud.githubusercontent.com/assets/4264802/16197518/abefffca-3702-11e6-88c7-41a54b56de18.png)
**3. Good selected with key 17**
![2016-06-20 16_16_35-react-bootstrap-table demo](https://cloud.githubusercontent.com/assets/4264802/16197519/abf05ea2-3702-11e6-86e9-fb1c172140d1.png)

Code is just a small modification from example - [select-filter-with-default-value.js](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/select-filter-with-default-value.js)
Only changes made are qualityType and product.push method. 

Am I doing something wrong? 
Feel free to contact me if you need any other information.

Regards,
Najdan

**Comment by AllenFang** [comment]
@Najdan, actually it's not a bug, it's just a bad examples...because the value of field ```qualityType``` is number(ex: 1,2,3), but the select filter in  ```react-bootstrap-table``` is use ```string.indexOf()``` to filter data, so that's why you got this result. 

BTW, there's a enhancement need to do, ```react-bootstrap-table``` support ```filterFormatted``` props on ```<TableHeaderColumn>``` but it only format the data before filtering but I forgot to format the ```formatExtraData```.

Anyway, I'll do a patch for this issues and make examples more better. Thanks you

**Comment by AllenFang** [comment]
@Najdan, Fixed on ```v2.3.7```. Thanks
