### ISSUE TITLE
How can I give the checkbox of a row a class or id?

### ISSUE THREAD

**Issue by SimonDKnight** [AllenFang/react-bootstrap-table#518]
Cant figure this out, can you help?

**Comment by AllenFang** [comment]
@SimonDKnight, sorry for it cant be configurable. But I've planed to make the selection column more customizable on ```v3.0.0``` and talk about it in https://github.com/AllenFang/react-bootstrap-table/issues/502#issuecomment-227476845

check #487 for more detail for ```v3.0.0```. Thanks :)

**Comment by AllenFang** [comment]
check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/custom-multi-select-table.js
