### ISSUE TITLE
Add 2 layer header

### ISSUE THREAD

**Issue by christchron** [AllenFang/react-bootstrap-table#519]
I want to add 2 headers to my table but i don't know how to add new tr in this library. Can anyone help me to solve this? I can't use colspan or rowspan.
![image](https://cloud.githubusercontent.com/assets/12684064/16215415/3b05ebfa-378c-11e6-97a8-378f65e5949c.png)

**Comment by AllenFang** [comment]
@christchron, ```react-bootstrap-table``` cant get this requirement. Sorry for that. if you need a large customize on table, just forgot ```react-bootstrap-table```

**Comment by AllenFang** [comment]
Released on ```v2.8.0```, there're some [example](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/column-header-span) you can check it
