### ISSUE TITLE
Hide Column for Mobile

### ISSUE THREAD

**Issue by jzumbrun** [AllenFang/react-bootstrap-table#52]
I need to hide a column only for mobile.

When I apply a `className="hidden-xs"` to `TableHeaderColumn` ,which is the bootstrap way to hide elements based on media query, it only removes the column in the table and not its header.

I can not use `hidden={true}` which will hide both column and header because it needs to use media queries.

```
<TableHeaderColumn dataSort={true} className="hidden-xs" min-width="50px" dataField="req_number">Req #</TableHeaderColumn>
```
:point_up: will not hide column header.

**Comment by AllenFang** [comment]
Hi @jzumbrun , it seem a little bug and I will fix it in next version. Thanks for your feedback :)

**Comment by AllenFang** [comment]
This issue has been solved on newest version :)

**Comment by sgentile** [comment]
@AllenFang when I use className='hidden-xs' - it's hiding the header but not the column

```
<TableHeaderColumn dataField="state" className="hidden-xs" dataFormat={this.statusFormatter} dataSort={true}>Status</TableHeaderColumn>
```

**Comment by sgentile** [comment]
I found out I need to set both className and columnClassName - so no issue here!

Thanks
