### ISSUE TITLE
Question: Access component through refs (i.e. SearchInput) same as #134

### ISSUE THREAD

**Issue by mlsLino** [AllenFang/react-bootstrap-table#520]
Hi, good day!

First, thank you for this package. My issue is that I need to send onclick data from the table to the search textbox. I've tried accessing it through

this.refs.table.refs.seachInput
this.refs.seachInput

but to no avail. I'm fairly new to react and meteor so any help is greatly appreciated.
Thank you and regards.

**Comment by AllenFang** [comment]
@misLino, did you want to put the search text in search text field instead of user key in?

**Comment by mlsLino** [comment]
@AllenFang  yes. the text is actually binded to a table cell onclick.

**Comment by mlsLino** [comment]
I made it work by creating an input and binded it with handlesearch and the other functions. Thank you for your time.
