### ISSUE TITLE
Disable Displaying Page Numbers

### ISSUE THREAD

**Issue by jflayhart** [AllenFang/react-bootstrap-table#521]
Is there a way to completely disable showing page numbers? For example,

```
<BootstrapTable options={{ paginationSize: 0 }} />
```

Right now it only defaults to 5 no matter what, but I think our server-side changes are moving more towards not giving pagination options and just "load more" type data loading instead of using actual page numbers.

The Results of course would be:

"Prev Next" instead of "Prev 1 2 3 4 5 Next"

**Comment by AllenFang** [comment]
@jflayhart, sorry we cant do that in ```react-bootstrap-table```. Actually, I wont support this feature in near future.
