### ISSUE TITLE
Table for headers and columns

### ISSUE THREAD

**Issue by ZetsubouToshio** [AllenFang/react-bootstrap-table#523]
Hi!
Why have you selected structure with two tables: for headers and for columns? Haven't you tried single table for both? 
It's rather uncomfortable to change clomuns (and it headers) width depending 
their content now.

**Comment by AllenFang** [comment]
@ZetsubouToshio, yes, you r right. The reason why I separate the body and header is make vertical and horizontal scroll more compatible and comfortable on table. If any solution can solve scroll and width issues well, I can change it in ```v3.0.0```.
