### ISSUE TITLE
Add table index

### ISSUE THREAD

**Issue by ricogabunada** [AllenFang/react-bootstrap-table#524]
Hi! Is there any way I could add table/row index in react bootstrap table ?
Thanks! :D

**Comment by AllenFang** [comment]
you means the ```tabIndex```?

**Comment by ricogabunada** [comment]
@AllenFang Thank you so much for your response.
This is what I mean :D ( see the numbers at the left side ).

-------------------------------------------------------
-------------------------------------------------------
1 |        some text          |      some text        |
-------------------------------------------------------
2 |        some text          |      some text        |

I'm thinking you have an attribute or something to be added in the table that makes incremental values automatically based on the length of the data inserted in the table.

But I already had a solution to it, I just added the numbers in the data that was passed on the react-bootstrap-table.

If you have something like that could you please share it to me :D

Thank you very much!

**Comment by AllenFang** [comment]
> But I already had a solution to it, I just added the numbers in the data that was passed on the react-bootstrap-table.

That's the only way to do, ```react-bootstrap-table``` doesn't support the incremental values automatically on some column.

Thanks you 👍   You did a great job:)
