### ISSUE TITLE
Advance Column Filter dynamically fill drop down box

### ISSUE THREAD

**Issue by SimonDKnight** [AllenFang/react-bootstrap-table#525]
Hi, I am trying to add a drop down filter to my table, but I am having problems trying to set the dropdown box contents dynamically from the data. I tried giving the options a function but it does not seem to like it. Any ideas on how I can achieve this?

**Comment by SimonDKnight** [comment]
So I managed to get this working so that the drop down is populated using a function where I iterate over the different options from the objets I am sending to it. However I have run into a weird problem where it wont filter the items from the drop down. How is it doing the matching? It is just comparing strings?

**Comment by SimonDKnight** [comment]
Sorry was being dumb, the value was being set to an integer, where was it needed to be set to the string.   Got there in the end, phew. Thanks

**Comment by AllenFang** [comment]
@SimonDKnight, sorry for lately reply. Anyway I'm glad you can solve this issue well. :)
