### ISSUE TITLE
Current page not work correct from zero

### ISSUE THREAD

**Issue by inthedark122** [AllenFang/react-bootstrap-table#526]
I found some problem
https://github.com/AllenFang/react-bootstrap-table/blob/master/src/BootstrapTable.js#L42
When You use ||, you do not consider "0" property, You should use `if (typeof this.props.options.page !== "undefined")`.

**Comment by AllenFang** [comment]
@inthedark122, thanks your finding, I'll check this out :+1:

**Comment by inthedark122** [comment]
Thank you :+1:
