### ISSUE TITLE
Problem with dropdown

### ISSUE THREAD

**Issue by WhiteMiata** [AllenFang/react-bootstrap-table#530]
Hello, i'm trying to insert a dropdown button into a column.
I created the custom dataFormat function and the button correctly appear in the cell but if i click on it the appearing menu is visible only for the small part inside the cell, the rest is hidden "under" the table.
There's a way to make it work correctly?
Thanks

<img width="314" alt="dropdown button in table" src="https://cloud.githubusercontent.com/assets/20106002/16296332/040ab3fa-392c-11e6-8448-0241d1aa84ff.png">

**Comment by 9DigitNumber** [comment]
I have the same problem. Using a custom dataFormat function to return a dropdown makes it open UNDER the other rows.
Anyone can help?

**Comment by AllenFang** [comment]
hi all, I'll check this out.

**Comment by 9DigitNumber** [comment]
Thank you! I'll be eagerly waiting for an update on this matter. :)

**Comment by AllenFang** [comment]
Hi all, the problems is hard to fix, because the following styling applied on ```td```
```css
overflow: hidden;
white-space: nowrap;
text-overflow: ellipsis;
```
The root cause is from ```overflow: hidden```, but if I remove it will cause the content of ```td``` overlay to other cell if content it too large, so following is my workaround and I thinks it's much easy to solve this issue.

a)  apply ```columnClassName``` on you column which contain dropdown
```js
...
<TableHeaderColumn dataField='price' dataFormat={ activeFormatter } columnClassName='my-class'>Product Price</TableHeaderColumn>
...
```

b) Then override the ```overflow```
```css
.my-class {
    overflow: inherit !important;
}
```

Feel free to ask anything if you get confusing. Thanks.

**Comment by WhiteMiata** [comment]
Hi AllenFang, thanks for the reply.
Unfortunately part of the problem is still here. Your workaround worked to show the dropdown menu over the table cells but don't work over the table borders. If i open the dropdown in a table that have a height less than the one of the dropdown (as on a single row table or on the last item of a table) the menu is still hidden under the table margins and a height slider appear. I need to make it show over and outside the table itself. Can you suggest a way to make it work? Thanks.
Here a couple of screenshot:

<img width="329" alt="dropdown01" src="https://cloud.githubusercontent.com/assets/20106002/16385319/9845ac06-3c8c-11e6-9f6f-ca5ff9a2725a.png">
<img width="332" alt="dropdown02" src="https://cloud.githubusercontent.com/assets/20106002/16385325/9e9ed12c-3c8c-11e6-91ea-9a9c781eae31.png">

**Comment by AllenFang** [comment]
thanks @WhiteMiata, I'll keep to figure out it.

**Comment by AllenFang** [comment]
Sorry for lately reply, @WhiteMiata, did you set ```heigh``` on table? if not, you can overwrite the css:
```css
.react-bs-container-body{
    overflow: inherit !important;
}
```
Anyway, sorry These is all the workaround, Hope I can solve this issue correctly

**Comment by genau7** [comment]
Hi, unfortunately this workaround doesn't solve the dropdown issue when I try to put the dropdown in the column header. I tried to put a multiselect filter in one of my columns based on the custom filter example from your demo. This is how it looks before clicking on the dropdown:   

![image](https://user-images.githubusercontent.com/5731725/31279983-2f5a2e54-aaab-11e7-9230-d981101602fe.png)

And after clicking:   
![image](https://user-images.githubusercontent.com/5731725/31280083-74cabdd2-aaab-11e7-94d7-dadd10096343.png)


Now I tried different styles and none of them help me. Any suggestions?
```
.dropdown-menu {
     z-index: 2000;
}

.react-bs-container-header {
    z-index: 2000;
    overflow: inherit !important;
}

.my-class {
    overflow: inherit !important;
}

.react-bs-container-body{
    z-index: -1;
    overflow: inherit !important;
}
```
This is what I am using for the multiselect dropdown:   
https://github.com/skratchdot/react-bootstrap-multiselect

And these are its styles:   
https://raw.githubusercontent.com/davidstutz/bootstrap-multiselect/master/dist/css/bootstrap-multiselect.css

**Comment by MichalRemis** [comment]
I had similar problem, but with customEditor of a cell with dropdown. This workaround worked great, I just had to change `columnClassName` prop to `editColumnClassName` to make it work.

```
...
<TableHeaderColumn ... editColumnClassName='my-class'>Product Price</TableHeaderColumn>
...
```

**Comment by genau7** [comment]
@MichalRemis, thanks for you suggestion. Sadly it didn;t work :(

**Comment by bruno-sartori** [comment]
Didn't work for me as well, i'm trying to use react-select inside a row, any progress in this?

**Comment by namratha2403** [comment]
I am trying to use react select too.. but not achieving the solution

**Comment by ramkrishna757575** [comment]
I am using the react-select as well, but unable to fix it. Is there any solution for it?

**Comment by softwarefactory1** [comment]
I had the same problem with the react multiselect component I solved as follows:

in the css react-bootstrap-table.css file, change the style to line 20

.react-bs-table table td,
.react-bs-table table th {
   / * overflow: hidden;
   white-space: nowrap;
   text-overflow: ellipsis;
   * /
   overflow: inherit! important;
}

I hope this can help you.

**Comment by carlx** [comment]
I have created custom dropdown component that solves this issue in the responsive table.

https://github.com/carlx/ReactDropDown

**Comment by AdnanBoota** [comment]
I am also having this issue, but my react-select is outside the react-bootstrap-table. The options menu is hidden, i have tried to `overflow: inherit !important;` but still it's not visible, any idea???
![error-datatable](https://user-images.githubusercontent.com/14972616/53815325-befadd00-3f61-11e9-9a8b-0e0dc4d117b8.png)

**Comment by gitramro** [comment]
I'm getting this issue on version 6.10.0

**Comment by vtarelkin** [comment]
> I am also having this issue, but my react-select is outside the react-bootstrap-table. The options menu is hidden, i have tried to `overflow: inherit !important;` but still it's not visible, any idea???
> ![error-datatable](https://user-images.githubusercontent.com/14972616/53815325-befadd00-3f61-11e9-9a8b-0e0dc4d117b8.png)


@AdnanBoota @genau7 
I had the same issue in header. It helped me to set
`    mix-blend-mode: overlay;`
for the nearest column header.

**Comment by guilhermereisti** [comment]
Just set the container as 'root' on DropdownMenu.

` <DropdownMenu container='root'>`
