### ISSUE TITLE
Add and Remove React components on hover

### ISSUE THREAD

**Issue by Suzanna-Manoj-Williams** [AllenFang/react-bootstrap-table#531]
Hi,

How can we show and hide react components in a column on the hover of the corresponding row?

**Comment by AllenFang** [comment]
@Suzanna-Manoj-Williams, did you want to remove one cell only or column(Like remove a header column)?

**Comment by Suzanna-Manoj-Williams** [comment]
No... I want to show and hide a column in a table on hover on that row. The column should be visible in the hovered row and hidden elsewhere. When hovered out, the column should be completely hidden.
On 23-Jun-2016 23:01, Allen <notifications@github.com> wrote:@Suzanna-Manoj-Williams, did you want to remove one cell only or column(Like remove a header column)?

**Comment by AllenFang** [comment]
HI @Suzanna-Manoj-Williams, sorry for lately reply, ```react-bootstrap-table``` doesn't support this kind of feature and I thinks there's no any workaround for it.

**Comment by vtarelkin-comprehend** [comment]
@AllenFang no possibility to make cell visible on hover? Or maybe elements in cell (img) ? Default - unvisible, hover - visible
