### ISSUE TITLE
render components in cells

### ISSUE THREAD

**Issue by lcb** [AllenFang/react-bootstrap-table#533]
Hi there

I would like to render a button and links inside cells. Is this somehow possible? 

Thanks,
Lorenz

**Comment by gshakir** [comment]
I think 'dataFormat' is what you are looking for. See http://allenfang.github.io/react-bootstrap-table/example.html#column-format

**Comment by AllenFang** [comment]
@gshakir's answer is what you want, thanks :)

**Comment by lcb** [comment]
@gshakir Thanks, you are my hero!
@AllenFang it would be nice to highlight this feature better in your documentation. "Column Format" sounds more like how to format numbers in colums so I overlooked that. What about naming this example

## Embedded React Components
To show more than only text in your tables use dataFormat.

**Comment by AllenFang** [comment]
HI @lcb, thanks you :)  I'll consider it
