### ISSUE TITLE
Defining selected with radio button issue

### ISSUE THREAD

**Issue by popaulina** [AllenFang/react-bootstrap-table#535]
Using a table with radio button selection, I defined the 'selected' as the first row in the table. It highlights that row but then trying to change which row is selected does not work. Clicking on other rows still calls the onSelect function correctly but it does not update the row which is highlighted.

```
var selectRow = {
             mode: "radio",
             clickToSelect: true,
             bgColor: "rgb(238, 193, 213)",
             selected: [1],
             onSelect: this.onSelectRow
         }
```

This is the definition of my selectRow properties. Am I doing something wrong or is `selected` broken with radio button selection?

**Comment by AllenFang** [comment]
@popaulina, sorry for lately reply, could you please show your whole examples?

**Comment by popaulina** [comment]
@AllenFang 
This is the table definition: 
```
<div className="stacked">
    <BootstrapTable data={[{Id: 0, Value: "First"}, {Id: 1, Value: "Second"}]} 
        selectRow={selectTableRow} striped={true} hover={true} >
        <TableHeaderColumn dataField={"Value"} dataAlign="center" isKey={true}>
            Equity Allocation Method
        </TableHeaderColumn>
    </BootstrapTable>
</div>
```

The properties to go with it:
```
var selectTableRow = {
             mode: "radio",
             clickToSelect: true,
             bgColor: "rgb(238, 193, 213)",
             selected: ["First"],
             onSelect: this.onSelectTableRow
         }
```

and the function:
```
onSelectTableRow(row, isSelected) {
        if (isSelected) {
            this.setState({ Selection: row.Value });
        } else {
            this.setState({ Selection: null });
        }
    }
```

The "First" row highlights correctly and the state is set properly on selecting but the row that is highlighted never changes.

**Comment by AllenFang** [comment]
Hi @popaulina, following link is helpful to you.
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/externally-managed-selection.js

http://allenfang.github.io/react-bootstrap-table/advance.html#dynamic-select

Feel free to ask me anything 👍
