### ISSUE TITLE
Fixed Header

### ISSUE THREAD

**Issue by Suzanna-Manoj-Williams** [AllenFang/react-bootstrap-table#536]
Hi, 

Is there a way to keep the headers fixed?

**Comment by AllenFang** [comment]
@Suzanna-Manoj-Williams, sorry,  what's that means for **fixed** ?

**Comment by Suzanna-Manoj-Williams** [comment]
The header remains fixed in the top when table is scrollable.

**Comment by AllenFang** [comment]
@Suzanna-Manoj-Williams, check http://allenfang.github.io/react-bootstrap-table/example.html#basic-scroll, i think it's fixed header with scroll :)
