### ISSUE TITLE
Problem with Header width inside a Tab

### ISSUE THREAD

**Issue by WhiteMiata** [AllenFang/react-bootstrap-table#538]
Hello, i have this problem with the Table Header inside a Tab.
If I set a column width with a fixed value the table body work correctly but the header still work as all the columns have responsive width.
This problem happen inside a Tab only.
Result is shown in the attached screenshot.
Can help with this issue? Thanks.

<img width="1358" alt="header" src="https://cloud.githubusercontent.com/assets/20106002/16385976/475a7d32-3c8f-11e6-9273-4ba3aa7418c4.png">

**Comment by AllenFang** [comment]
@WhiteMiata, check #331. Feel free to ask any question :)
