### ISSUE TITLE
Pagintion problem

### ISSUE THREAD

**Issue by lewis617** [AllenFang/react-bootstrap-table#539]
![image](https://cloud.githubusercontent.com/assets/11524612/16403232/c0bde7e0-3d25-11e6-9a40-aae0cd4fdd23.png)
When I click the pagination,it doesn't display the list . Why?

I use the Universal render ,it is related to this ?

**Comment by pbromley** [comment]
This is happening for me too. With more that 10 results (11 in my test), clicking the drop down does nothing - version 2.2.0 but also tried in 2.3.6 with the same result

**Comment by gshakir** [comment]
There is dependency on Bootstrap JS. You need to add the following to index.html .

  <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

@AllenFang any chance you are working on removing this dependency and using react-bootstrap 'button' instead?

**Comment by pbromley** [comment]
cheers @gshakir adding this works - its also in the documentation which i missed

**Comment by lewis617** [comment]
@gshakir 
Thanks, I do not like jQuery, hope @AllenFang  can remove this dependency.

**Comment by AllenFang** [comment]
Hi all, sorry for lately reply and Thanks @gshakir's contribution :)
BTW, Hope I can remove these dependency in the future on ```v3.0.0``` #497
