### ISSUE TITLE
Pagination Button Disabled/Broken

### ISSUE THREAD

**Issue by aaronhayes** [AllenFang/react-bootstrap-table#54]
Hey Allen!

My pagination button isn't working. It seems to be disabled and clicking on it does nothing.

No warnings/errors appear in the console. Any idea on why this might be happening?

![image](https://cloud.githubusercontent.com/assets/4180720/9951728/c5bff1ea-5e0d-11e5-9819-4872357d3cd8.png)

**Comment by aaronhayes** [comment]
Actually looks like it might be some conflicting CSS - will keep you posted.

**Comment by aaronhayes** [comment]
Okay it's because your js requires bootstrap.js (which I'm not using).

Surely there is a way to make this React only? And not require the additional js files.

**Comment by aaronhayes** [comment]
maybe look at using something like https://github.com/AdeleD/react-paginate ?

**Comment by AllenFang** [comment]
You need to include your bootstrap js file into your html, bundle the bootstrap with this component is not a good idea :)
