### ISSUE TITLE
Support Default Search

### ISSUE THREAD

**Issue by mgiraud** [AllenFang/react-bootstrap-table#540]
Hello,

I'd really like to store the filters, sort and search data with Redux, so the filters can be set if found in the store.
Basically this not difficult to achieve, but i have two issuse : 

1. i can't find how to set a default value to the search input (value stored in redux or in URL for example)

2. Same to set default sorting

Any idea and advice for this ?

Thanks !

**Comment by AllenFang** [comment]
2. check [default sort](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/default-sort-table.js)

1. There's no way to set default value on search, But I can support it.

BTW, I wonder if you just keep the search text or sort field in redux and pass them as props to component to render the table with these search text or sort field?

**Comment by mgiraud** [comment]
Thx for the answer
1- Sorry I missed it 
2- That would be nice

And yes when modifying the search text or sort field, i dispatch an action which update my state with these values, and i update my url so i can have a direct access to a sorted/filtered table.

**Comment by AllenFang** [comment]
@mgiraud thanks.

**Comment by AllenFang** [comment]
Released on ```v2.4.1```, check [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/default-search-table.js).  Sorry for lately fixing. :)
