### ISSUE TITLE
Question: SelectRow only show  check on specific rows

### ISSUE THREAD

**Issue by bteepell** [AllenFang/react-bootstrap-table#541]
I would like to only allow certain rows to be select-able based on a value in a column. 
eg) if column allowEdit is set to true then the row shows checkbox else it does not .

Or should or can this be handled in the editable table column?

**Comment by AllenFang** [comment]
HI @bteepell, sorry for lately reply. check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/unselectable-table.js#L25.

duplicate with #502

**Comment by bteepell** [comment]
Great. That's awesome

**Comment by bteepell** [comment]
when I add and delete from the table the unseleted column list does not get updated.  For example the one I add is select-able but appears as unselectable because it was added into the table above one that was unselectable.  when I refresh the list it appears corretly?
