### ISSUE TITLE
Is it able to change pagination dropdown into dropup ?

### ISSUE THREAD

**Issue by nuwanprabhath** [AllenFang/react-bootstrap-table#542]
In the pagination dropdown, when user selects number of rows it appear as a dropdown. I would like to change it to dropup by changing its class of dropdown into dropup. I've done this by changing the source code in paginationList.js file. Is there any other way of doing this ?

**Comment by AllenFang** [comment]
@nuwanprabhath, sorry for lately reply. There's no way to do it. In #497 I've planned to make these components more customizable, so maybe this feature can be done on ```v3.0.0```. Thanks

**Comment by AllenFang** [comment]
Fixed on `v.3.0.`, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/pagination/custom-size-per-page.js#L39

Let me know if you got any questions
