### ISSUE TITLE
Multiple column sort

### ISSUE THREAD

**Issue by mahyarmobilab** [AllenFang/react-bootstrap-table#543]
Hi all,
first I want to say thanks for sharing this great component. Is there any plan to add multiple column sort to the component?

**Comment by AllenFang** [comment]
Thanks, @mahyarmobilab. Currently, I've no plan to support this feature so PR is welcome. BTW, How to implement the multi column sorting? No idea ;D

Feel free to discuss with me

**Comment by lynn** [comment]
[This example](http://tablesorter.com/docs/#Demo) demonstrates a nice multi-column sorting interface: click to sort, shift-click to add a secondary/tertiary/… column to sort on.

**Comment by AllenFang** [comment]
@lynn, thank you :)  I'll check this out. Anyway, in the recent, I prefer to finish ```v.3.0.0```, so the multi sort may not soon be done

**Comment by repocho** [comment]
👍

**Comment by AllenFang** [comment]
wow, I forgot this issue, actually, in ```v2.9.0```, we start to support the multi sort, following is few examples you can check it:

https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/multi-sort-table.js
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/manage-multi-sort-external-table.js

Let me know if you have any question or trouble on implement, thanks 👍
