### ISSUE TITLE
Add custom buttons to toolbar

### ISSUE THREAD

**Issue by tarim** [AllenFang/react-bootstrap-table#547]
Hi there,

Is that possible to add custom buttons to toolbar please? Such as "Save All" for multi row update etc.

Thank you,

NS

**Comment by AllenFang** [comment]
#497 for ```v3.0.0``` is ready to make component more customizable.

**Comment by tarim** [comment]
Hi Allen,

Thank you for quick reply, when v3.0.0 will be available?

Thanks,

NS

**Comment by AllenFang** [comment]
@tarim, No idea currently, sorry. There're a lots of thing to do, It really need some time. Hope I can complete before October. 

Thanks you :)

**Comment by gary-menzel** [comment]
I realise this is a couple of month old now, but I use some jQuery trickery to attach some buttons/dropdowns into the react-bootstrap-table (in `componentDidMount`) which works most of the time (95%).  In any case, the buttons/dropdowns are sitting directly above the table anyway  I have not tried it with any other components but expect it would be no different as it is happening when the DOM is rendered.  It also seems to play well with the ADD/DELETE buttons for rows in the table.

**Comment by AllenFang** [comment]
@gary-menzel, thanks :)  Hope after ```v3.0.0``` released, everyone can customize their component more easily.

**Comment by gary-menzel** [comment]
Looking forward to it Allen... I am still relatively new to GitHub and PR's (and how to keep the separation between branches I want to work on without getting it caught up in my own private code) but am also right in the middle of coding for a start-up (so not a lot of time to experiment).  Eventually, though, I'll be happy to work on some of the code and submit PR's (when I work out the best workflow for it).

**Comment by AllenFang** [comment]
Fixed on `v3.0.0`, check [examples](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/custom/toolbar) to learn how to customize toolbar

Let me know if you got any questions, thanks
