### ISSUE TITLE
How to set text value in TextFilter component?

### ISSUE THREAD

**Issue by WangLarry** [AllenFang/react-bootstrap-table#548]
I want to use TextFilter to filter data, using  params in URL as text value in TextFilter.
I notice there is a 'dafaultValue' in table options, but it works only initialize phase.
How to set text value in TextFilter component, so i can filter data dynamically.

**Comment by AllenFang** [comment]
@WangLarry, sorry for lately reply and we dont support this feature currently. This issues is same as #470. Like I said, I'll support it but I've no any schedule, so PR is welcome :)

**Comment by AllenFang** [comment]
Sorry for lately fix, check ```v2.4.2```, https://github.com/AllenFang/react-bootstrap-table/commit/7d6ded2d2467f8d3b5dbc303c7bc05b1977d471a is example. Thanks :)
