### ISSUE TITLE
[FEATURE] Keeping state of the table

### ISSUE THREAD

**Issue by fabarea** [AllenFang/react-bootstrap-table#549]
Is it a way to keep the state of the table? Use case: I reload the page and have the search / sorting applied as I left the table.

**Comment by AllenFang** [comment]
Hi @fabarea, sorry for lately reply.
> reload the page

You means you refresh the page in browser?

**Comment by fabarea** [comment]
Yes.

**Comment by AllenFang** [comment]
@fabarea, I think it is not a important feature for now and I think in react world, you should just keep the search text and sorting(field and order) and cache all in somewhere where should not be clear when reload. If reloading, just set the default sort the call ```handleSearch``` will restore the status.

BTW, #540 has asked a default search for this component and I'll implement it in recently. So, maybe in the future, you just set the default sort and default search when reload trigger!

**Comment by fabarea** [comment]
Thanks for your reply.

``handleSearch`` could do the trick but I am not sure how to use it. Could you give me a direction (like a snippet) how to proceed it or shall I wait #540 to have it implemented? Here is my use case for a user which is fairly common:

1. route ``/customers`` - list view of customers (bootstrap table). We are dealing with ~ 2000 entries. Let assume the user filters with term "foo". 
2. route ``customers/edit/xyz`` - edit view of a customer, the user has clicked on the edit icon in a row and is now editing the data.
3. route ``/customers`` - the user is back on the list view, data is refreshed - however the state of the table is "lost". => I wish to have search term "foo" re-applied against the list

Hope it shades some light about what I would like to achieve - which is a very ordinary / expected behaviour.

For instance, in the DataTables jQuery plugin (I know not to compare with in the approch!) they have [an option](https://datatables.net/examples/basic_init/state_save.html) `stateSave: true` which does the job.

**Comment by AllenFang** [comment]
@fabarea, sorry for lately reply, I thinks ```handleSearch``` is what you wanted. check [docs](http://allenfang.github.io/react-bootstrap-table/docs.html)

following is example:
```js
//in somewhere, you can do a dynamic search
this.refs.table. handleSearch('foo');
///

render() {
  return(
    <BootstrapTable ref='table'>
    </BootstrapTable>
  );
}


```

**Comment by AllenFang** [comment]
I'll open it if necessary, feel free to discuss with me.

**Comment by fabarea** [comment]
Thanks for the pointer. It **will** look quiet clumsy but I resolved the case as that for the time being:

```
	/**
	 * @return void
	 */
	componentDidUpdate() {
		const searchTerm = localStorage.getItem('react-bootstrap-table-search-term');
		if (this.refs.table && searchTerm) {
			
			// Trigger a search on the table
			this.refs.table.handleSearch(searchTerm);
			
			// Re-inject value into search text field. 
			$('.react-bs-table-search-form input').val(searchTerm);
		}
	}
```

And even more awful (I barely dare copy / paste here) to persist the search term value - I could not use `onSearchChange` as I don't do server side processing

``` 

	/**
	 * @return void
	 */
	componentWillMount() {
		$(document).on("keyup", ".react-bs-table-search-form input", e => {
			localStorage.setItem('react-bootstrap-table-search-term', $('.react-bs-table-search-form input').val());
		});
	}
```
