### ISSUE TITLE
unselectable list refresh issues

### ISSUE THREAD

**Issue by bteepell** [AllenFang/react-bootstrap-table#550]
I have a case where I set the 'unselectable' list to the key id's  When I first run the list it is fine.  I have 7 rows of data and row 3 and 4 are selectable. But if I delete one of those rows the 'unselectable' list shows incorrectly in the browser.  I have debugged the list and it is correct in console.log.  I deleted row 3 for example but the list shows the next row down is now selectable, even though the list in the output shows correctly?   If I refresh, the list shows correct select/unselectable.  This only seems to happen on add and delete. I retrieve the list each time I add or delete and recreate the 'unselectable' list.

**Comment by AllenFang** [comment]
@bteepell, I'll check it out!  Thanks you

**Comment by AllenFang** [comment]
@bteepell, sorry for lately fixed, it has been released on ``v`2.3.8```. Thanks :)
