### ISSUE TITLE
built-in show/hide columns popup?

### ISSUE THREAD

**Issue by lcb** [AllenFang/react-bootstrap-table#551]
Hello, me again

I saw that for showing/hiding columns there is the `hidden` property. I was hoping that there is some built-in functionality or an example on how to make a pop-up dialog to select which columns to show? I guess I am not the first one with this issue?

Cheers,
Lorenz

**Comment by wentaoxu415** [comment]
@lcb: I think this is a related issue 
https://github.com/AllenFang/react-bootstrap-table/issues/299

**Comment by lcb** [comment]
This is correct, thanks!
