### ISSUE TITLE
Unselect checkbox/rows

### ISSUE THREAD

**Issue by SimonDKnight** [AllenFang/react-bootstrap-table#552]
Hi, I want to unselect currently selected checkboxes/rows after a successful ajax request. Is there a function I can call to unselect all checkboxes? 

Thanks for your help.

**Comment by AllenFang** [comment]
@SimonDKnight, sorry for lately reply, there's a simple way, call ```cleanSelected``` which exposed by ```<BootstrapTable>```

**Comment by prabhath** [comment]
clean selection is not available to me. I tested on 2.3.4 and 2.3.9.
![jkl](https://cloud.githubusercontent.com/assets/711146/17244381/22ddd9ee-559f-11e6-8ba2-5b1054c79839.png)
