### ISSUE TITLE
The demo example does not suit the latest react any more?

### ISSUE THREAD

**Issue by chenatu** [AllenFang/react-bootstrap-table#555]
please correct `React.render` with `ReactDom.render`

**Comment by AllenFang** [comment]
Thanks :)

**Comment by madeinfree** [comment]
@chenatu I try to modify the React.render to ReactDOM.render :D

**Comment by AllenFang** [comment]
thanks @madeinfree :)

**Comment by AllenFang** [comment]
Released on ```v2.3.9```
