### ISSUE TITLE
npm install different version

### ISSUE THREAD

**Issue by itsbluething** [AllenFang/react-bootstrap-table#556]
Using `npm install react-bootstrap-table` seems to install an older version that is on ES5 instead of ES6. It also doesn't have a gulpfile. In addition, using `npm install git+[github here]` will install the current version of the repo, but then webpack/react has issues finding the module.

**Comment by AllenFang** [comment]
@itsbluething, sorry for lately reply. 

> Using npm install react-bootstrap-table seems to install an older version that is on ES5 instead of ES6

why?  ```react-bootstrap-table``` is still wrote by es6.

and what's the version?

**Comment by itsbluething** [comment]
2.3.7
