### ISSUE TITLE
Insert New Row Not working

### ISSUE THREAD

**Issue by nsdube** [AllenFang/react-bootstrap-table#562]
Hello Allen,

I tried to use react-bootstrap-table in my project but am not able to insert the new row, the modal doesn't pop up. I imported the javascript and css.

Error:
<img width="1391" alt="screen shot 2016-07-14 at 5 05 21 pm" src="https://cloud.githubusercontent.com/assets/5911954/16859585/f00ca5c4-49e4-11e6-92ae-2a96f9a118ff.png">

**Comment by daniel1943** [comment]
+1

**Comment by AllenFang** [comment]
@daniel1943 give a well answer.
