### ISSUE TITLE
How can I export the table with the selected rows

### ISSUE THREAD

**Issue by basketballislife** [AllenFang/react-bootstrap-table#567]
![image](https://cloud.githubusercontent.com/assets/20488904/16905378/a9d7289a-4cd7-11e6-80bd-311b14876eea.png)
1. The return value of the function which is "onExportToCSV" must "the rows which need to be exported",
but what is the struct of the return value?
2. Is my usage Effective? or what is the correct usage
Thank u

**Comment by basketballislife** [comment]
The attributes REMOTE must be true, then the table can be exported with the selected rows...means you must handle the data filtering, sorting, adding or removing etc on your own.

**Comment by AllenFang** [comment]
You need to return the rows in```onExportToCSV```, which the structure is same as the value of  ```data``` props on ```<BootstrapTable>```. 

I write a example without testing, maybe you can try it

```js
class ExportCSVTable extends React.Component {

  onExportToCSV() {
    const selectedRows = this.refs.table.state.selectedRowKeys;
    return products.filter(prod => {
      if (selectedRows.find(prod.id) > -1) {
        return prod;
      }
    });
  }

  render() {
    const selectRow = {
      mode: 'checkbox'
    };

    const options = {
      onExportToCSV: this.onExportToCSV
    };

    return (
      <BootstrapTable ref='table' data={ products } exportCSV={ true } options={ options } selectRow={ selectRow }>
          <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
}
```

**Comment by AllenFang** [comment]
Sorry, I thinks the snippet is not work. BTW, you are right,  I need to do some fixing for avoid ```onExportToCSV``` is only work on ```REMOTE``` condition.

**Comment by AllenFang** [comment]
@basketballislife, this issue fixed on ```v2.3.9```. Thanks :)

**Comment by asheshtuladhar** [comment]
test

**Comment by asheshtuladhar** [comment]
Is it possible to excel export using React Table ?
