### ISSUE TITLE
pass csvFileName as a function instead of a string

### ISSUE THREAD

**Issue by anvk** [AllenFang/react-bootstrap-table#568]
It would be great if we could pass into `csvFileName` not only a string but also a function which supposed to return a string. I would love to prefix fileNames with a timestamp if possible but right now `react-bootstrap-table` supports static names only.

**Comment by AllenFang** [comment]
@anvk, thanks your suggestion, it's worth to support it :)  I'll find some time to add this feature

**Comment by AllenFang** [comment]
@anvk, this enhancement has been patched on ```v2.4.1```. Sorry for lately fixing :)
