### ISSUE TITLE
Search on object

### ISSUE THREAD

**Issue by AllenFang** [AllenFang/react-bootstrap-table#569]
https://github.com/AllenFang/react-bootstrap-table/issues/282#issuecomment-190528716
https://github.com/AllenFang/react-bootstrap-table/issues/282#issuecomment-232918746

```react-bootstrap-table``` support the column filter and search on **formatted cell**, you can enable ```filterFormatted``` and give ```dataFormat``` a format function. But maybe your filtering condition is one of the property in object. In the light of this, I'll support a ```filterFormat``` function and let you decide what's actual value you want to be filtered or searched on ```react-bootstrap-table```

Feel free to discuss with me :)

**Comment by AllenFang** [comment]
@nguyenchanhnghia, I've support ```filterValue``` to let you to decide what value you want to be filtered. check [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/search-format-table.js#L51)

Remember to upgrade to ```v2.3.9```. Thanks

**Comment by Ethaan** [comment]
just wondering, its possible to search everything inside an object?

taking as an example i have this data

```
{
 username: someUsername,
 profile: {
  extraEmail: someExtraEmail,
  phone: somePhone
 }
}
```

its possible to search over the whole `profile` object?

**Comment by AllenFang** [comment]
@Ethaan, currently, we only handle the search on a property.
