### ISSUE TITLE
Option to Hide Radio Button Column for selection

### ISSUE THREAD

**Issue by mjrussell** [AllenFang/react-bootstrap-table#57]
Being able to click the row to select is great and makes the radio button column somewhat unnecessary (at least for single selection). 

Would be great to be able to pass an option to selectRow that hides the selection column.

Something like:

```
var selectSessionProp = {
            mode: 'radio',
            clickToSelect: true,
            hideColumn: true,
            bgColor: 'rgb(238, 193, 213)',
            onSelect: this.props.onSelect
        };
```

**Comment by AllenFang** [comment]
OK I'll add this feature in next version. Thanks your feedback :)

**Comment by AllenFang** [comment]
HI @mjrussell, you can hide selection column as follow: 
<pre>
var selectRowProp = {
  mode: "radio",
  clickToSelect: true,
  hideSelectColumn: true, //you can hide select column, if you enable clickToSelect
};
</pre>

**Comment by mjrussell** [comment]
:+1: Awesome!

**Comment by ssjogus** [comment]
thanks for this new feature, but somehow when i add this line in the code, it is disturbing table alignment. When a scrollbar appears in table-body, the most right column border  in the table-header and table-body does not match.. any idea, how to fix that?

**Comment by AllenFang** [comment]
@ssjogus, would you give me your code? because I can't reproduce this problem :)

**Comment by ssjogus** [comment]
hi @AllenFang ,  sorry the issue is not because of this new feature.. i think its over there even i don't use the hideSelectColumn. i am using 0.9.7 version.

![screenshot1](https://cloud.githubusercontent.com/assets/8896732/11738972/a4e3d4e0-a00d-11e5-81e5-c1126d0d2a39.png)

**Comment by AllenFang** [comment]
@ssjogus, upgrade to the newest version will solve your problem, and remember to re import the css file to your project.

**Comment by ssjogus** [comment]
when i update, it is asking for react 0.14, and our project uses 0.13. so i am not able to use it.

**Comment by AllenFang** [comment]
@ssjogus, upgrade is only one solution, I can't republish 0.9.7 for fixing this bug ;(

**Comment by vishalbsacet** [comment]
How to do disabled true for any particular radio button , for some condition e.g Count is more than 2.
