### ISSUE TITLE
onCellSelect functionality 

### ISSUE THREAD

**Issue by kaustav1992** [AllenFang/react-bootstrap-table#571]
There is a provision for onRowSelect for Bootstrap table to which I can attach an onClick listener and perform some activities. What if I want to attach the onClick listener to just some columns of the row and not all the columns. Is there a way to do that? Tried hard finding a way out, but couldn't. Or in other words, is there a way to perform anything like onCellSelect, similar to onRowSelect?

**Comment by AllenFang** [comment]
@kaustav1992, currently, ```react-bootstrap-table``` doesn't support ```onCellSelect``` or something like that. But there's a workaround, use ```dataFormat``` to attach any event.
```js
export default class ReactColumnFormatTable extends React.Component {

  handColumnClick = e => {
     alert('click event');
  }
  
  activeFormatter = (cell, row) => {
     return (
       <div onClick={ this.handColumnClick }>{ cell }</div>
     );
 }

 render() {
    return (
      <BootstrapTable data={ jobs }>
          <TableHeaderColumn dataField='id' isKey={ true }>Job ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Job Name</TableHeaderColumn>
          <TableHeaderColumn dataField='active' dataFormat={ activeFormatter }>Active</TableHeaderColumn>
      </BootstrapTable>
    );
  }
}
```

**Comment by email2vimalraj** [comment]
@AllenFang : I'm trying to do this, but not working for me. The following is the sample:

```javascript
handleCellClick(event) {
  console.log(event.innerHTML);
}

linkCellFormatter(cell, row) {
  return (
    <a href='#' onClick={this.handleCellClick}>{cell}</a>
  );
}

render() {
  return (
    <BootstrapTable data={jobs}>
      <TableHeaderColumn isKey dataField="id" dataFormat={this.linkCellFormatter}>Job Id</TableHeaderColumn>
      <TableHeaderColumn dataField="name">Job Name</TableHeaderColumn>
    </BootstrapTable>
  );
}
```

It doesn't logs the console which I was expecting.

**Comment by email2vimalraj** [comment]
So I'm able to solve this by binding the `linkCellFormatter`. I'm not deleting my previous comment for the sake of community use.

**Comment by AllenFang** [comment]
@email2vimalraj, good job

**Comment by msamorukov** [comment]
this solution does not work, if cell has empty data, or if clicked inside 5px padding.
