### ISSUE TITLE
csvFormat function doesn't seem to receive the row as an argument, only the cell

### ISSUE THREAD

**Issue by jbgarr** [AllenFang/react-bootstrap-table#573]
When trying to provide a csvFormat function to format the cell for csv export I am getting 'undefined' as the row. I am using the same function to format my data (passed as dataFormat) in the table and it works fine. It seems like the row just ins't being passed to the csvFormat function as described in the docs.

**Comment by AllenFang** [comment]
@jbgarr, thanks your remind, I'll fix it :)

**Comment by jbgarr** [comment]
Great, glad I could help. Looking forward to the fix. Thanks for the great work so far!

**Comment by AllenFang** [comment]
@jbgarr, fixed it on ```2.3.9```
