### ISSUE TITLE
Clear column search

### ISSUE THREAD

**Issue by Lilion12** [AllenFang/react-bootstrap-table#576]
Hello, 

Is there a way to programatically clear the search filter and result in the table? After a row click for instance? 
We managed to clear the field but the result stays filtered...

Cheers, 
Lilion12

**Comment by AllenFang** [comment]
@Lilion12, sorry for lately reply, Busy on job.

for the search, you can call ```handleSearch``` and give it emty string for clear search, ```handleSearch``` is an exposed api from ```<BootstrapTable>```

for the filter, there's no way to do it, #470 has asked this feature, but I'm busy on development for ```v3.0.0```

I'll try to fix the second requirement when I've free time

**Comment by AllenFang** [comment]
@Lilion12, upgrade to ```v2.4.0``` and check this [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/all-filters.js#L62) to see how to clear filter. Thanks
