### ISSUE TITLE
hook to "on Edit Cell" event

### ISSUE THREAD

**Issue by giko45** [AllenFang/react-bootstrap-table#581]
I want to catch the "edit event"  (click cell) to be able to handle the editing myself (in this case show a datepicker of my choice) and put back the result in the select cell.  I did som browsing through the docs and the code but i have not found how to do this.

**Comment by AllenFang** [comment]
@giko45, sorry for lately reply. we are not support this feature, I thinks this issue is "make cell edit customizable", I will thinks about to add this feature in ```v3.0.0```. Check #497

**Comment by AllenFang** [comment]
@giko45, check ```v2.4.0```, we announced the custom cell editing. [There](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/cell-edit/custom-cell-edit-table.js)'s a example. Try it out and feel free to discuss with me

**Comment by giko45** [comment]
Hi, 

checked this out but it seems that the custom editor is not called when inserting a new row.

regards

**Comment by AllenFang** [comment]
@giko45, yes.  we only support default edit types which apply to insert and cell editing. I'll make the the custom editor applied to both in ```v3.0.0```
