### ISSUE TITLE
Value returned by csvFormat function is not being used in created .csv file

### ISSUE THREAD

**Issue by jbgarr** [AllenFang/react-bootstrap-table#586]
It seems the value that is returned by the csvFormat function is not actually being used in the .csv file. I have a function that I'm using to format my column values for both my dataFormat and csvFormat functions. The value returned in the UI is formatted as expected (as a string), but in the .csv file the result is [object Object]. Here is my function:

    teamFormatter = (cell, row) => {
      const teams = row.engagements.map((engagement) => {
        return engagement.label;
      });
      const teamText = teams.join(", ");
      return (
        <span title={teamText}>{teamText}</span>
      );
    }

Here is the column that is using the function (for both dataFormat and csvFormat):

    <TableHeaderColumn
            dataField="engagements"
            dataSort={true}
            caretRender={TableUtils.caretFormatter}
            dataFormat={TableUtils.teamFormatter}
            csvFormat={TableUtils.teamFormatter}>Associated Team(s)</TableHeaderColumn>

Am I missing something here?

**Comment by jbgarr** [comment]
Ah, I see that the csvFormat function should return a string, not a jsx component. I've provided another function that returns a string and it works fine. I suggest updating the docs to explain that the csvFormat function needs to return a string.

**Comment by AllenFang** [comment]
@jbgarr, sorry for lately reply, busy on work. And I'll updating the docs, so just reopen it util the docs been  updated
