### ISSUE TITLE
pagination 

### ISSUE THREAD

**Issue by MaxwellZhou** [AllenFang/react-bootstrap-table#59]
how to set total count displaying in pagination?
how to set position about  seletions of page items?
thanks

**Comment by AllenFang** [comment]
My answer is all are unavailable on this component.Cause of these feature are not primary requirements for this components currently. But I can add these two feature in tuture :)

**Comment by AllenFang** [comment]
HI @MaxwellZhou, I add some pagination feature base your requirement and some idea in v1.0.0.

A quick example as follow, 

<pre>
   var options = {
      page: 2,  //which page you want to show as default
      sizePerPageList: [5,10], //you can change the dropdown list for size per page
      sizePerPage: 5,  //which size per page you want to locate as default
      paginationSize: 3,  //the pagination bar size.
    }

    <BootstrapTable data={products} pagination={true} options={options}>
    //....
</pre>

**Comment by MaxwellZhou** [comment]
Thanks a lot.



zhou2003737@qq.com
 
From: AllenFang
Date: 2015-10-04 15:56
To: AllenFang/react-bootstrap-table
CC: MaxwellZhou
Subject: Re: [react-bootstrap-table] pagination (#59)
HI @MaxwellZhou, I add some pagination feature base your requirement and some idea in v1.0.0.
A quick example as follow, 
   var options = {
      page: 2,  //which page you want to show as default
      sizePerPageList: [5,10], //you can change the dropdown list for size per page
      sizePerPage: 5,  //which size per page you want to locate as default
      paginationSize: 3,  //the pagination bar size.
    }
    
    //....

**Comment by fayejaye** [comment]
How do I add the overall total rows? Like 'Showing 1-10 of 134'
