### ISSUE TITLE
Latest React update causing "unknown props" warnings

### ISSUE THREAD

**Issue by tylerjryan** [AllenFang/react-bootstrap-table#590]
In the latest version of React, errors are being thrown for "unknown props". See here: https://facebook.github.io/react/warnings/unknown-prop.html

It seems that the BootstrapTable is currently throwing these (as of version 2.3.9):
![screen shot 2016-07-27 at 9 59 12 am](https://cloud.githubusercontent.com/assets/4932412/17184459/2eda8bee-53e1-11e6-8fa1-2f41699814c0.png)

This seems to have already been resolved by React-Bootstrap, see here: https://github.com/react-bootstrap/react-bootstrap/issues/1994

I just wanted to let you know about this in case you weren't aware. Thanks for the great work!

**Comment by madeinfree** [comment]
Hi, @tylerjryan, about React-Bootstrap version 0.30.0 was resolve this problem, I can help to change it.

**Comment by quantumreference** [comment]
Yeah, I'm on 0.30.0 and the latest of react-bootstrap-table as well, and I'm still seeing this issue. Thanks for checking!

**Comment by madeinfree** [comment]
Hi, @tylerjryan  @quantumreference I found this is issue from react-toastr module, I look at that issues and have someone to intent to fix it ! see [Here](https://github.com/tomchentw/react-toastr/issues/68).

**Comment by tylerjryan** [comment]
perfect, that makes sense. Thank you very much!

**Comment by AllenFang** [comment]
yes, the problem is from ```react-toastr```

**Comment by AllenFang** [comment]
Fixed on ```v2.4.4```. Thanks :)

**Comment by AllenFang** [comment]
there's one thing to notice, on v2.4.4 I move the css files from css to dist folder, remember to update the css path. I apologize for it.
