### ISSUE TITLE
Pagination PropType Invalid 

### ISSUE THREAD

**Issue by madeinfree** [AllenFang/react-bootstrap-table#592]
I found this weird issue with paginationShowsTotal, it happened when give this prop a function, but [here](https://github.com/AllenFang/react-bootstrap-table/blob/master/src/pagination/PaginationList.js#L210) validate expected type of 'boolean'.

![2016-07-28 9 39 55](https://cloud.githubusercontent.com/assets/4027049/17198389/6471cb52-54a7-11e6-9abf-5b4002518742.png)

**Comment by AllenFang** [comment]
um, I think I forgot to use ```oneOfType ``` when support ```paginationShowsTotal```  can be customize if a function given

**Comment by AllenFang** [comment]
Fixed on ```v2.4.3```. Thanks 👍
