### ISSUE TITLE
Problem with adding rows

### ISSUE THREAD

**Issue by alexbokii** [AllenFang/react-bootstrap-table#593]
Hi, Allen
I’m using the react-bootstrap-table in a simple MVC web page.  I have successfully been able to provide initial row data to the table, and enable editing so that the user can change the data.  However, I also need to add row creation and deletion functionality.  I have tried to enable these by setting insertRow and deleteRow to true.  The ‘new’ and ‘delete’ buttons render correctly, and the ‘delete’ button works properly.  However, the ‘new’ button does not seem to work.  Nothing happens when it is clicked.  Looking at the javascript code which has been generated, it seems to have no onclick method.  Please can you suggest what might be wrong?  The code I am using is attached below; is anything missing?

```
import * as React from "react";
import * as ReactDOM from "react-dom";
import {BootstrapTable, TableHeaderColumn, CellEditClickMode, SelectRowMode} from "react-bootstrap-table";
 
declare var electricalTTTs: any;
declare var electricalTTTsDataGrid: any;
 
var cellEditProp = {
    mode: "click" as CellEditClickMode,
    blurToSave: true
}
 
var selectRowProp = {
    mode: "checkbox" as SelectRowMode,
    bgColor: "#FFDDDD"
};
 
electricalTTTsDataGrid =
    <BootstrapTable
        data={electricalTTTs}
        striped={true}
        hover={true}
        cellEdit={cellEditProp}
        insertRow={true}
        deleteRow={true}
        selectRow={selectRowProp}
    >
        <TableHeaderColumn hidden={true} dataField="Id"></TableHeaderColumn>
        <TableHeaderColumn isKey={true} dataField="TapNumber">Tap No</TableHeaderColumn>
        <TableHeaderColumn dataField="TPIHL">Impedence HV-LV (%) </TableHeaderColumn>
        <TableHeaderColumn dataField="TPLHL">Load Loss HV-LV (kW) </TableHeaderColumn>
        <TableHeaderColumn dataField="TPIHT">Impedence HV-TV (%) </TableHeaderColumn>
        <TableHeaderColumn dataField="TPILT">Impedence LV-TV (%) </TableHeaderColumn>
        <TableHeaderColumn dataField="TPLHT">Load Loss HV-TV (kW) </TableHeaderColumn>
        <TableHeaderColumn dataField="TPLLT">Load Loss LV-TV (kW) </TableHeaderColumn>
    </BootstrapTable>;
 
ReactDOM.render(
    electricalTTTsDataGrid,
    document.getElementById("electricalDataGrid")
);
```

**Comment by AllenFang** [comment]
@alexbokii, ```react-bootstrap-table``` depends on ```bootstrap.js``` and ```jQuery```. check the documents and I use them to control the menu and modal behavior. Anyway, I've plan to remove these dependencies on ```v3.0.0```, you can check #497 

BTW, sorry for lately reply.. I'm busy on work and I'm glad that you find and use this component. Thanks and enjoy it.

**Comment by anandsutar** [comment]
I am having problem while next page click delete functionality is not working. but if i open the grid on first page all functionality working fine i wonder that why is not working properly when i go to the next page .
Can you please assist on this?

I have used Jquery and ajax for this.
