### ISSUE TITLE
cell parameter is null in dataFormat callback

### ISSUE THREAD

**Issue by lewfish** [AllenFang/react-bootstrap-table#596]
It seems that the `cell` parameter in the dataFormat callback is always set to `null`, but I expected it to be set to the value of the `dataField` field in the `row`. See example below.

```
function format(cell, row) {
    // cell is null, but I expected it to be row.x
    return row.x;
}

<BootstrapTable
    data={rows}
>
    <TableHeaderColumn
        dataField="x"
        dataFormat={format}
    >
        X
    ...
```

**Comment by AllenFang** [comment]
make sure your each object in ```rows``` array which all have the ```x``` field.
