### ISSUE TITLE
Unable to import the library; everything fails.

### ISSUE THREAD

**Issue by jchio001** [AllenFang/react-bootstrap-table#598]
I'm trying to import your library into my project, but nothing is working. I've downloaded the tar file and unzipped it into a local directory.

Trying to import through require gives me:
`ReferenceError: require is not defined`
And typing to import through 'import {BootstrapTable, TableHeaderColumn} from 'react-bootstrap-table' just straight up fails on me.

How I'm using react.js for my project is that I have a .html file and a .jsx file. In my .html file, I have some divs which are loaded by calling React.render(..., ...). My .jsx file is where the code for rendering the components is.

**Comment by AllenFang** [comment]
@jchio001, You dont even show me your example so I can't help you. BTW, I think you should learn how to setup a react project at first.
