### ISSUE TITLE
React Component for Column/Data Format

### ISSUE THREAD

**Issue by aaronhayes** [AllenFang/react-bootstrap-table#6]
It would be useful to be able to use React Elements in the `dataFormat` prop.

**Comment by AllenFang** [comment]
Hi @aaronhayes 
I dont understand what's problem about <code>dataFormat</code>, would you describe it detail or give some example? :)

**Comment by aaronhayes** [comment]
sorry about that, it was a pretty vague issue.

in your example you pass a function which returns a string to `dataFormat`. 
`function priceFormatter(cell, row){
  return '<i class="glyphicon glyphicon-usd"></i> ' + cell;
}`

Instead of returning a string I want to return a React Element.
`return <ReactElement randomProp={3} />` 
Currently the way it works is to DangerouslySet the return valued, which of course would output [object Object] in my example.


Cheers.

**Comment by AllenFang** [comment]
Hi @aaronhayes 
Ok! I understand, maybe I need to try it more, but need some time:)
Anyway, your idea is very good for react-bootstrap-table. :+1:

**Comment by aaronhayes** [comment]
awesome, thanks. I made a commit to my fork which has it working (~not fully tested). Still playing around with some things. 189860c8600178c0e8ab5e3d26cbafb5d448848e

**Comment by AllenFang** [comment]
Great! I will try your code in these days. I think your solution is ok, you can create a PR for this issue so that I can help to do more testing and debug. Anyway, thanks for your contribution :)

**Comment by AllenFang** [comment]
Hi @aaronhayes 
I have release the newest version v0.8.5 for this issue, plz update and run it again.

**Comment by aaronhayes** [comment]
@AllenFang 
Sorry about the late reply. Changes look great. Thanks for all your hard work!
Now using your latest changes in my project and it works beautifully.
