### ISSUE TITLE
How to Get Selected Row data from all row?

### ISSUE THREAD

**Issue by KristinaMatuleviciute** [AllenFang/react-bootstrap-table#600]
At the moment I am using your code (from here http://allenfang.github.io/react-bootstrap-table/advance.html#how-to-get-select ) and I am getting just data from product ID column, How to get data from all row , all columns : id, name , price as a json? would appreciate your answer. By the way very nice table :)

**Comment by AllenFang** [comment]
hi @KristinaMatuleviciute, if you got the ID and you can use it to find the whole columns from your data source, but there's a better solution is use ```onSelect``` hook, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/select-hook-table.js#L25)

Feel free to discuss with me. Thanks

**Comment by KristinaMatuleviciute** [comment]
Thank you, it was helpful.

**Comment by AllenFang** [comment]
Your first example is mean http://allenfang.github.io/react-bootstrap-table/advance.html#how-to-get-select ?

If yes, this example is only get the selected row keys, but I dont know why you cant see the console, maybe you can show me your example?
