### ISSUE TITLE
Tootip for data in BootstrapTable

### ISSUE THREAD

**Issue by Shraddhasv** [AllenFang/react-bootstrap-table#603]
Hi Team,

I am using react-bootstrap-table and following is code to show table

  BootstrapTable data={tableDataSet} pagination={true} condensed={true} search={true} keyField='Id' selectRow={selectRowProp} height='405' ref='rbsTable'>
                                           {columns.map(column => 
                                                  TableHeaderColumn dataField={column.Name} dataSort={true} sortFunc={nameSorter} hidden={column.isKey} dataFormat={textFormatter} dataAlign='left' headerAlign='left'>{column.Name}/TableHeaderColumn>
                                           )}
                                        /BootstrapTable>
										
How can I add tooltip for data in each column and also how can resize the columns?

**Comment by AllenFang** [comment]
@Shraddhasv, enable ```columnTitle``` on <TableHeaderColumn>```, and we dont support column resizing, so PR is welcome :)
