### ISSUE TITLE
Transferring clicked row information to a co-component.

### ISSUE THREAD

**Issue by cj285** [AllenFang/react-bootstrap-table#606]
I have a React component structured as follows:
Parent
  -- BootstrapTable
  -- Buttons
Based on the rows that are checked, I wish to be able to activate and deactivate buttons. The usual way of transferring this information is to set the parent state, which on rerender, sends the new props to the Buttons child. However, if I do this, the rows will automatically uncheck themselves (my guess is that the rows don't keep their old internal states when updating). How should I go about this problem, if it is even feasible to do? Thanks!

**Comment by AllenFang** [comment]
hi @cj285, If a row checked, you set state on parent to control Buttons, you should avoid BootstrapTable rerender again by ```componentWillReceiveProps```. Like #605.
