### ISSUE TITLE
Possible to filter like this?

### ISSUE THREAD

**Issue by daniel1943** [AllenFang/react-bootstrap-table#608]
I hate having two input "boxes" for number filters, would it be possible to remove the operators and have just single input box? Like text/status filter.

And if users wanted to filter something numerically they would just type something like:

    <3
    >= 5
    > 100

edit: and if it is possible to remove the annoying up/down arrows.

**Comment by AllenFang** [comment]
@daniel1943, if you really dont like this style, just customize one by your self. I'll change the number filter if there'r a lots of people said it very annoying.

Anyway, your requirement is not very hard to implement.
