### ISSUE TITLE
How to use sortFunc

### ISSUE THREAD

**Issue by thevangelist** [AllenFang/react-bootstrap-table#609]
I tried to follow this example to get custom sortFunc: https://allenfang.github.io/react-bootstrap-table/advance.html#customSort 

I am getting error: `error 'order' is defined but never used no-unused-vars "react-bootstrap-table"`

Whats wrong here?

**Comment by AllenFang** [comment]
@thevangelist, it's just a eslint error, you can turn off it. BTW,  https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/custom-sort-table.js is also a good example for you.
Thanks:)

**Comment by thevangelist** [comment]
Thanks! now it's working.
