### ISSUE TITLE
Last column header width not calculated correctly

### ISSUE THREAD

**Issue by vaskgjuri** [AllenFang/react-bootstrap-table#610]
At some width sizes the last column cuts the text in the header instead of adding the three dots...

http://prntscr.com/c1yrdh

http://prntscr.com/c1yrtf

Now, if I increase or reduce the width of the browser width, the listener kicks in and makes new calculations and it moves from correct behavior to the wring one

http://prntscr.com/c1ys49

http://prntscr.com/c1ys81

The reported screenshots are made with resizing the window of just 1 pixel. If I move it another pixel in the same direction it will be broken again, and another pixel, OK again.. etc...

BR

**Comment by AllenFang** [comment]
@vaskgjuri, I'll check this out.

**Comment by AllenFang** [comment]
@vaskgjuri, sorry for lately fixing, check `react-bootstrap-table@2.10.0-beta.1` by
```npm install react-bootstrap-table@2.10.0-beta.1``` and I thought this beta release already fixed couples unalign problem, if it work and stability, I'll consider to forward to production as soon as possible.

Let me know if the problems still there. thanks
