### ISSUE TITLE
selectRow 'selected' issue

### ISSUE THREAD

**Issue by sgentile** [AllenFang/react-bootstrap-table#611]
```
<BootstrapTable data={items} striped={false} hover={true} options={this.options} selectRow={this.selectRowProp}>

this.selectRowProp = {
        mode: 'checkbox',
        clickToSelect: true,
        selected: this.getSelectedSeries(),
        onSelect : this.onSelect,
        onSelectAll: this.onSelectAll
      };

```
I'm attempting to programmatically select the first row - however the data isn't populated yet on the first render.  The getSelectedSeries call I have fires the first time, but when the data ('items') comes in this isn't called again.  

I'm using redux and the prop 'items' is an empty array on first render and when the data is retrieved it re-renders the component with the items but the selected call isn't invoked again.

**Comment by AllenFang** [comment]
HI @sgentile, you means the second render happened, the ```this.getSelectedSeries()``` function doesn't been called?

**Comment by sgentile** [comment]
Yes, that is what is happening.  It's not 

```constructor(props) {
    super(props);

      ...

      this.getSelectedSeries = () => {

        const selected = props.collectionStats.items.reduce((selectedItems, item) => {
          if (item.selected) {
            selectedItems.push(item.seriesKey);
          }
          return selectedItems;
        }, []);

        console.log('getSelectedSeries', selected);
        return selected;
      };

      this.selectRowProp = {
        mode: 'checkbox',
        clickToSelect: true,
        selected: this.getSelectedSeries(),
        onSelect : this.onSelect,
        onSelectAll: this.onSelectAll
      };
  }

<BootstrapTable data={collectionStats.items} striped={false} hover={true} options={this.options} selectRow={this.selectRowProp}>

```

Additionally, when I select a row, it triggers the 'onSelect' call however, when the data re-renders it's not showing it as selected.

**Comment by sgentile** [comment]
I figured out what I was doing wrong.   Thanks
