### ISSUE TITLE
Feature Request: Cell information on row hover

### ISSUE THREAD

**Issue by RacheleMoresi** [AllenFang/react-bootstrap-table#615]
There doesn't appear to be a cell-specific hover function.  I am trying to retrieve the original cell value on hover over an edited cell for display in a popover.  Is there currently a way to get specifics about which column in the row I am hovered over or a potential for a columnMouseover function to be exposed?

**Comment by AllenFang** [comment]
> I am trying to retrieve the original cell value on hover over an edited cell for display in a popover

How about enabled the ```columnTitle``` on ```TableHeaderColumn```?

**Comment by RacheleMoresi** [comment]
That would get the job done. Thanks!






From: Allen
Sent: ‎Tuesday‎, ‎August‎ ‎9‎, ‎2016 ‎8‎:‎03‎ ‎PM
To: AllenFang/react-bootstrap-table
Cc: Rachele Moresi, Author






I am trying to retrieve the original cell value on hover over an edited cell for display in a popover

How about enabled the columnTitle on TableHeaderColumn?

**Comment by ZephD** [comment]
Hi @RacheleMoresi @AllenFang ,

I'm trying to do the same: Hover over cell to obtain full info for a popover.
I'm not sure how adding `columnTitle` helps? I see no difference in the arguments of onRowMouseOver.

Could you explain how you solved this?

Many thanks

**Comment by AllenFang** [comment]
hi @ZephD, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column/column-title-table.js :)

**Comment by ZephD** [comment]
That just shows the use of the flag, which I understand (though see no difference it being true or false, the heading is always visible...).
How does it help with the onRowMouseOver and getting the current column / cell?

**Comment by RacheleMoresi** [comment]
@ZephD I'm afraid I can't provide you a code sample for that.  I did get it working at one point. However, as the project evolved, I decided to anchor the popover with cell info to an icon in the cell. I passed the information I needed to the icon component using the dataFormat property, and then setting the popover content based on the info stored in the props of the icon.

**Comment by ZephD** [comment]
Anchoring the hover info to an object in the formatted cell... Could do the job. Thanks.

**Comment by Tulasi-Pilli** [comment]
I am looking to show a text on hover over a cell.
how can I hover over one particular cell?

**Comment by 9005** [comment]
@AllenFang : I need to obtain row,colIndex,rowIndex,cellvalue on hover. Is it possible?

**Comment by AllenFang** [comment]
it's impossible in `react-bootstrap-table` but may possible in `react-bootstrap-table2`

BTW,
`react-bootstrap-table2` already launch
https://github.com/react-bootstrap-table/react-bootstrap-table2
https://react-bootstrap-table.github.io/react-bootstrap-table2/

**Comment by 9005** [comment]
@AllenFang 
Is it possible to obtain ow,colIndex,rowIndex,cellvalue onRowMouseOver?

**Comment by 9005** [comment]
@AllenFang : 
Question: Is it possible to obtain colIndex and rowIndex for onRowDoubleClick?

**Comment by 9005** [comment]
@AllenFang : After searching by textFilter I want to have all table data .Is their way to get table data after search.Will afterSearch works.Please suggest me?
