### ISSUE TITLE
Sort indicator doesn't work when remote is on

### ISSUE THREAD

**Issue by sercanov** [AllenFang/react-bootstrap-table#616]
It fires the onSortChange but I think it doesn't update the state inside. It always fires 'desc' order

**Comment by sercanov** [comment]
When I renew the state in onSortChange it worked. Don't know if it's still a bug.

**Comment by AllenFang** [comment]
maybe you can show me an example, because I have no idea about this issue.

**Comment by sercanov** [comment]
```
<BootstrapTable
                        data={this.state.tableData}
                        remote
                        selectRow={{
                            mode: 'radio',
                            onSelect: self.props.onSelect,
                            clickToSelect: true
                        }}
                        striped hover
                        options={{ sizePerPage: 25, onSortChange: self.props.onSortChange}} >
<TableHeaderColumn width="150" isKey dataField='id' dataAlign="center">ID</TableHeaderColumn>
<TableHeaderColumn width="150" dataSort={ true } dataField='name' dataAlign="center">Name</TableHeaderColumn>
```

The code above generates the screen below. When I click the Name column, indicators doesn't change and it always fires the same sort order. ( I found this by logging in the onSortChange ) But when I set state in the onSortChange method, it works without a problem. I hope this helps. 

![ekran resmi 2016-08-10 10 26 37](https://cloud.githubusercontent.com/assets/10291644/17545284/f59eed66-5ee4-11e6-9172-8125af26e2a2.png)

**Comment by AllenFang** [comment]
I want to check ```self.props.onSortChange``` and you missing to import the ```react-bootstrap-table.min.css```

**Comment by sercanov** [comment]
@AllenFang yeah, imported the css now thanks. 

This is the onSortChange, with this block it works good, when the setState function deleted, indicators doesn't work. Anyway it's not a issue for me but I think it is because the page is not re-rendering, BootstrapTable should be rendered inside itself I guess.
```
	onSortChange(sortColumn, sortOrder) {
		var sortQuery = {};
		sortQuery[sortColumn] = sortOrder;

		this.setState({ sort: sortQuery, currentPage: 1 }, function () {
			this.init()
		})
	}
```

**Comment by AllenFang** [comment]
@sercanov, check this [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-sorting.js). You need apply thee result of sorting to state. Actually, ```remote``` is means you need to handle the state changing, for example, you should add/update/delete a row on you state manager(redux, mobx, flux...), ```react-bootstrap-table``` just receive the final result data and render it.
