### ISSUE TITLE
How could I delete the specific row when clicking the button in the dataFormat

### ISSUE THREAD

**Issue by charles90dc** [AllenFang/react-bootstrap-table#619]
`onItemDelete(){
        
    }

    operationFormatter(cell, row, enumObject, index){
        console.log(`The row index: ${index}`);
        return(
            <Button bsStyle="warning" bsSize="xsmall" onClick={this.onItemDelete}>删除</Button>
        );
    };

    render(){
        return (
            <div>
                <BootstrapTable data={this.props.requestedItemsData} striped={true} hover={true} condensed={true} search={false} deleteRow={false} pagination={false} remote={true} height="355">
                    <TableHeaderColumn dataField="id" editable={false} isKey={true} hidden={true}>ID</TableHeaderColumn>
                    <TableHeaderColumn dataField="addedItems" editable={true} dataAlign="center">已添加物品</TableHeaderColumn>
                    <TableHeaderColumn dataField="quantity" editable={true} dataAlign="center">数量</TableHeaderColumn>
                    <TableHeaderColumn dataField="operation" dataFormat={this.operationFormatter} dataAlign="center">操作</TableHeaderColumn>
                </BootstrapTable>
            </div>
        )
    }`

**Comment by AllenFang** [comment]
Feel free to ask me anything :) Thanks
```js
onItemDelete = (id) => {
    this.refs.table.handleDropRow([id]);
}

operationFormatter(cell, row, enumObject, index){
    console.log(`The row index: ${index}`);
    return(
        <Button bsStyle="warning" bsSize="xsmall" onClick={ e => this.onItemDelete(row.id)}>删除</Button>
    );
};

render(){
    return (
        <div>
            <BootstrapTable ref='table' data={this.props.requestedItemsData} striped={true} hover={true} condensed={true} search={false} deleteRow={false} pagination={false} remote={true} height="355">
                <TableHeaderColumn dataField="id" editable={false} isKey={true} hidden={true}>ID</TableHeaderColumn>
                <TableHeaderColumn dataField="addedItems" editable={true} dataAlign="center">已添加物品</TableHeaderColumn>
                <TableHeaderColumn dataField="quantity" editable={true} dataAlign="center">数量</TableHeaderColumn>
                <TableHeaderColumn dataField="operation" dataFormat={this.operationFormatter} dataAlign="center">操作</TableHeaderColumn>
            </BootstrapTable>
        </div>
    )
}
```

**Comment by charles90dc** [comment]
ERROR in ./js/operatingroomWebpage/addJobs.js
Module build failed: SyntaxError: D:/Perforce/taimirobot/Develop/taimi-robot/robot-web/src/main/webapp/js/operatingroomWebpage/addJobs.js: Missing class properties transform.
  113 |     }
  114 |
> 115 |     onItemDelete = (id) => {
      |     ^
  116 |         this.refs.table.handleDropRow([id]);
  117 |     }
  118 |

**Comment by AllenFang** [comment]
@charles90dc, please fixing by yourself, because I just write this down without any compile... BTW, I use es6, so watch out
