### ISSUE TITLE
Can the table be borderless?

### ISSUE THREAD

**Issue by ripitrust** [AllenFang/react-bootstrap-table#62]
Is it possible to remove the borders between each cells?

same as the bootstrap table?

**Comment by AllenFang** [comment]
@ripitrust I thinks is possible in v1.0.0, in that version, <code>react-bootstrap-table</code> can add <code>classname</code> on table column or row.

**Comment by ripitrust** [comment]
that should be cool

**Comment by pannj** [comment]
is it possible to edit  a row data by opening a window as  createing data

**Comment by AllenFang** [comment]
HI @ripitrust , in newest <code>react-bootstrap-table</code> you have more ability to customize your component. 
You can use <code>trClassName</code> on <BootstrapTable> to add your css class name on row(tr) and <code>columnClassName</code> on <TableHeaderColumn> to add your css calss name on column(td). Finally, use <code>classname</code> on <TableHeaderColumn> to add your css calss name on header.

HI @pannj, this component does not support this feature currently.
