### ISSUE TITLE
paginationShowsTotal is false by default

### ISSUE THREAD

**Issue by chriswhong** [AllenFang/react-bootstrap-table#620]
The docs say it is true by default, but I had to add `paginationShowsTotal: true` to options for it to show up.

**Comment by AllenFang** [comment]
@chriswhong, I found I wrote it as reverse..., sorry, the default value is false, I'll fix it. Thanks you :)

**Comment by AllenFang** [comment]
Fix it, https://github.com/AllenFang/react-bootstrap-table/commit/901bec058b359e6790f992049d1f2045d86a1a14
