### ISSUE TITLE
Set options for paging

### ISSUE THREAD

**Issue by jbgarr** [AllenFang/react-bootstrap-table#622]
Is there a way to set options for the paging portion of the BootstrapTable? I would like to control the options listed in the "results per page" dropdown and set the initial selected value for that dropdown as well. Right now the default value is 10, but I want to show more results than that when the table is rendered. Is this possible? If so how? Thank you.

**Comment by jbgarr** [comment]
Ah, sorry! I just found the paging options in the docs under the options section. Awesome work! Maybe one suggestion is to add something to the docs that points users to the options section for any feature that has options available. For example under the section that reads:

pagination : Bool
Enable pagination by setting pagination to true, default is false.

Add a line that lets users know that there are paging related options in the options section.

**Comment by AllenFang** [comment]
@jbgarr, thanks your suggestion, actually, I've planed to rewrite the docs again in the future. I'll keep your suggestion in mind :)
