### ISSUE TITLE
Header width issue when no data is available

### ISSUE THREAD

**Issue by wgorman** [AllenFang/react-bootstrap-table#623]
When I render a table with no data, the width attribute on the TableColumnHeader is ignored.  Looking at the code, it looks like width and min-width only get set if data exists in the table.  As a work-around, I've done something like this in my react component:

```
componentDidUpdate() {
    if (this.state.fields.length == 0) {
      $("th.t1").css({"width":"30", "min-width":"30"});
      $("th.t2").css({"width":"150", "min-width":"150"});
      $("th.t3").css({"width":"150", "min-width":"150"});
    }
}
```

<TableHeaderColumn className="t1" width="30"  ...
<TableHeaderColumn className="t2" width="150"  ...
<TableHeaderColumn className="t3" width="150"  ...

Here is the code that is causing the issue in _adjustHeaderWidth():

https://github.com/AllenFang/react-bootstrap-table/blob/master/src/BootstrapTable.js#L857

Thanks,

Will

**Comment by AllenFang** [comment]
@wgorman, this seems to be a good workaround, but I'll try to improve it. Thanks :)

**Comment by AllenFang** [comment]
Improved on ```v2.4.2```. Check it out :)
