### ISSUE TITLE
Disable checkbox for certain rows

### ISSUE THREAD

**Issue by anujemc** [AllenFang/react-bootstrap-table#624]
Is there any way by which we can disable checkboxes for certain rows. props by which we can handle enable/disable checkbox status .
Example -
for example in below mentioned table we just want to disable checkboxes where status is expired so how we can disable/remove checkbox from that particular row while other checkboxes should work as usual . 

![table](https://cloud.githubusercontent.com/assets/19282193/17581541/0d7d3174-5fc4-11e6-801d-6a2f6009a9ba.PNG)

**Comment by anujemc** [comment]
After reading more documentation I found a 'key' named unselectable in rowSelect which make certain row disable by passing key values as an array .

**Comment by AllenFang** [comment]
@anujemc, great :)
