### ISSUE TITLE
Is there a way to get the cell name when using columnClassName to set the cell class?

### ISSUE THREAD

**Issue by rrameshkumar76** [AllenFang/react-bootstrap-table#625]
Is there a way to get the "cell name" when using columnClassName?  It looks like we only get fieldValue,row,rowIdx,colIdx. Else Is there a way else to get the cellname for colIdx?

**Comment by AllenFang** [comment]
Any problem you encountered? Because I think pass the cell name is not necessary, if you can show me why you think it important, I'll try to pass it. 

BTW, I give the ```colIdx```, you can map the ```colIdx``` to cell name, it's fixed.

Close it first.
