### ISSUE TITLE
Delay with dynamic pagination and scroll switch

### ISSUE THREAD

**Issue by doshisunny** [AllenFang/react-bootstrap-table#626]
I am trying to do some dynamic scroll functionality for pagination. And I am having issue with slow performance with that. Switching from full scroll to pagination is quick but for pagination to scroll is really slow.

I attached PaginateIssue jsx file and sampleData.json.
For testing purpose If you hover on print data button it should switch between above two.

[PaginateIssue.txt](https://github.com/AllenFang/react-bootstrap-table/files/414301/PaginateIssue.txt)
[sampleData.txt](https://github.com/AllenFang/react-bootstrap-table/files/414302/sampleData.txt)

**Comment by AllenFang** [comment]
@doshisunny, actually, we still have the performance there with large data, I'll try to fix it, #566 is try to fix it, but I'm still review it. Close it because duplicated.

**Comment by doshisunny** [comment]
Thank you, @AllenFang
