### ISSUE TITLE
Column headers shifted when hidden column present

### ISSUE THREAD

**Issue by applebya** [AllenFang/react-bootstrap-table#628]
I'm encountering a problem with TableHeaderColumn headers (`<th>`) being improperly positioned when a hidden column is present in the table.

In the following example, I have a 3rd column set as `hidden: true`.

![screen shot 2016-08-11 at 5 33 32 pm](https://cloud.githubusercontent.com/assets/9222480/17609421/f518418e-5fe9-11e6-851e-4289793c9eb6.png)

Notice how "Definition" is shifted over to the right.

To reproduce:
- Add a new column to the end, set `hidden: true`

My recommendation to fix this would be to remove the hidden column DOM **entirely** rather than using `display: none`. I don't see any reason for keeping the DOM there anyway.

This would also fix a related CSS issue I have, where styling `td.last-child` still gets applied to a hidden last column - whereas I want it applied to the last visible one. I realize I can probably fix this  now by adding something like a 'visible' className to each visible column - but that makes my table logic pretty hairy.

Thoughts? Might submit a pull request with a fix...

**Comment by sgentile** [comment]
I'm seeing the same issue

**Comment by AllenFang** [comment]
@applebya, I'll check this out. PR is welcome, thanks :)

**Comment by kwent** [comment]
Same issue here.

**Comment by AllenFang** [comment]
hi there, sorry for lately fixing, check `react-bootstrap-table@2.10.0-beta.1` by
```npm install react-bootstrap-table@2.10.0-beta.1``` and I thought this beta release already fixed couples unalign problem, if it work and stability, I'll consider to forward to production as soon as possible.

Let me know if the problems still there. thanks
