### ISSUE TITLE
customEditor to have row as an argument

### ISSUE THREAD

**Issue by nasospsa** [AllenFang/react-bootstrap-table#629]
```
customEditor:
getElement(REQUIRED): Accept a function and take two arguments: onUpdate and props.
```

We need to have the whole row (record) as an argument in order to customize the editor. I checked on the source code and you seem to have rowIndex and columnIndex in the props although they don't pass as arguments in getElement callback.

Do you have any thoughts on if this could be solved?

**Comment by AllenFang** [comment]
@nasospsa, ok I'll support this in next version

**Comment by AllenFang** [comment]
Check ```v2.4.2```. The whole row data in the ```props``` as ```row```.
