### ISSUE TITLE
Editable converts zero (0) to empty string on first edit

### ISSUE THREAD

**Issue by bontibon** [AllenFang/react-bootstrap-table#630]
**Version:** 2.4.2

1. Have a table with a column that is editable
2. Have a cell in that column whose value is `0`
3. Click to edit that cell
4. A empty textbox is shown with (**expected**: textbox shown with value of `0`)
5. Set textbox to `0` and save
6. Click cell to edit again
7. Textbox is shown with value of `0`

**Comment by AllenFang** [comment]
@bontibon, I'll check this out. thanks your clear description.

**Comment by AllenFang** [comment]
Released on ```v2.4.3```. Check it out :)
