### ISSUE TITLE
Column width problem

### ISSUE THREAD

**Issue by ccjruemenapf** [AllenFang/react-bootstrap-table#632]
Hi folks,
first of all, thanks for this awesome component, but we have a little problem with it.

If we add items to _template.projection_ ({column}) and react rerender the table everything looks fine. 

But if we remove items of _template.projection_, the width of deleted column is splitting to each remaining column and ignore the width information on other _TableHeaderColumn_.

```
 <BootstrapTable height="250" data={data} striped={true} hover={true} condensed={true}>
    <TableHeaderColumn dataField="articleNumber" width="60" dataFormat={this.excludedFormatter}>       
        {labels.new_action}</TableHeaderColumn>
    <TableHeaderColumn dataField="articleNumber" width="115" isKey={true}
        filter={{type: "TextFilter", placeholder: labels.new_articleNumber}}/>
    <TableHeaderColumn dataField="description"
        filter={{type: "TextFilter", placeholder: labels.new_description}}/>
    {column}
</BootstrapTable>
```

column = 

```
        let column = filter.concat(template.projection).map(headline => {
            return (
                <TableHeaderColumn dataField={headline} width="80">{headline}</TableHeaderColumn>
            );
        });
```

**Comment by AllenFang** [comment]
@ccjruemenapf, I haven't see this issue, could you please show me an complete example(A js or a repo for me to reproduce this issue easily)?
Thanks you :)

**Comment by ccjruemenapf** [comment]
Hi, 
thank you for your very fast response. 
I'm created a separate project with only the functionality to add and delete columns. 

And i realize that the issue only occurs if a horizontal scrollbar appears on table component, otherwise it works fine.

So it would be nice if you checkout my repository and take a look at the problem.

Add columns (all) using the left component until a horizontal scrollbar appears on the table component. Then delete columns using the x on the left component. 
[https://github.com/ccjruemenapf/react-bootstrap-table-column-example]

![image](https://cloud.githubusercontent.com/assets/11871051/17704987/13765c74-63d7-11e6-9c5d-bbcc6291e720.png)


I hope the project is easy enough and thank you very much for your time.

**Comment by AllenFang** [comment]
Thanks !!  I'll check this out :+1:

**Comment by markortiz** [comment]
@AllenFang I have the same issue just like this even before.
The problem here is if on the `componentDidMount` and the table is rendered without scrollbar, then when I add new data upon `componentWillReceiveProps`  or `update` the `table` columns is being misaligned because of the added scroll bar.

I solved mine by creating a complicated `eventListener ` and some css configuration.

but now I think this can be resolved now by simply putting `react-bs-container-body` inside of a custom scroll like this one [react-custom-scrollbars](http://malte-wessel.github.io/react-custom-scrollbars) in that way, we can avoid adding of extra `scoll-width ` on the table body that cause column misalignment.

**Comment by AllenFang** [comment]
@markortiz, thanks, I'll try it out, sorry for lately fixing, busy on work ;(

**Comment by AllenFang** [comment]
hi there, sorry for lately fixing, check `react-bootstrap-table@2.10.0-beta.1` by
```npm install react-bootstrap-table@2.10.0-beta.1``` and I thought this beta release already fixed couples unalign problem, if it work and stability, I'll consider to forward to production as soon as possible.

Let me know if the problems still there. thanks
