### ISSUE TITLE
Sort wont be applied after search

### ISSUE THREAD

**Issue by simonberger** [AllenFang/react-bootstrap-table#634]
If you sort by a column and then do a search the result isn't sorted anymore.

**Comment by AllenFang** [comment]
@simonberger, sorry I can't reproduce it, any example for me to reproduce this?

**Comment by simonberger** [comment]
First of all sorry for the bad description before.
Some problems also came because of application side effects.

Anyway there are issues that can be easily reproduced. In short it seems to be that all column sortings done while a search is active will be discarded after  the search box is empty again. But the indicator still shows the sorting.

Way to reproduce the issue:

1. I use the first demo table on page http://allenfang.github.io/react-bootstrap-table/ to describe
2. Type "name 5" in the search box
3. Sort by Product Name
4. empty the search box
5. Result is sorted most likely by the column before the search (in this demo table there are only two possible sort cases)

**Comment by AllenFang** [comment]
Fixed on ```v2.4.3```. Check it out :)
