### ISSUE TITLE
Size Per Page List doesn't seem to work

### ISSUE THREAD

**Issue by tusharkhatiwada** [AllenFang/react-bootstrap-table#636]
Hi there,
I'm trying to use the `sizePerPageList` option on my table but it doesn't seem to work. I used it as below:

```
options={{
            sizePerPageList: [5,10,15,20],
            sizePerPage: 10,
            paginationShowsTotal: true
          }}
```
It just displays the default 10.

<img width="1250" alt="screen shot 2016-08-17 at 12 15 04 pm" src="https://cloud.githubusercontent.com/assets/5126590/17726684/4926e062-6474-11e6-855e-bcf0f2af2d06.png">

**Comment by AllenFang** [comment]
I think the sizePerPage in dropdown should be 5 10 15 20. But you give the ```sizePerPage``` with 10, which mean the default selected size per page. that's why you always see ```10``` is shown by default.

**Comment by tusharkhatiwada** [comment]
From your docs page, **sizePerPage** takes **Number** as argument. When I use it as array:
```
options={{
            sizePerPage: [5,10,15,20],
            paginationShowsTotal: true
          }} 
```
I get something like this:
<img width="1244" alt="screen shot 2016-08-18 at 9 01 32 am" src="https://cloud.githubusercontent.com/assets/5126590/17760834/6302b87c-6522-11e6-818e-4da65eaa9ec6.png">

I removed **sizePerPage** but no luck:

```
options={{
            sizePerPageList: [5,10,15,20],
            paginationShowsTotal: true
          }}
```

**Comment by bontibon** [comment]
`sizePerPageList` does not work for me either.

**Comment by AllenFang** [comment]
check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/pagination/custom-pagination-table.js example, I cant find any issue here, please show me for to reproduce it.

Clear again, 

Use ```sizePerPage``` to set the default ```sizePerPage``` option.
Use ```sizePerPageList``` to set the dropdown list for sizePerPage.

So I really have no idea about **what's that means for sizePerPageList does not work**
