### ISSUE TITLE
afterColumnFilter option for TableHeaderColumn

### ISSUE THREAD

**Issue by lioralt** [AllenFang/react-bootstrap-table#639]
Hi,
I saw that BootstrapTable has an afterColumnFilter option, in order to trigger actions after filtering ( which works great by the way) .

When using TableHeaderColumn component, does it have an afterColumnFilter action as well ( or something similar ) ?

Thanks :)

**Comment by AllenFang** [comment]
@lioralt, I'll support it in near future.

**Comment by lioralt** [comment]
@AllenFang, 
Is there any workaround until you will ?
Thanks.

**Comment by AllenFang** [comment]
@lioralt, sorry I cant give any workaround... I'll try to fix it quickly

**Comment by AllenFang** [comment]
@lioralt, I found ```react-bootstrap-table``` support the ```afterColumnFilter```, sorry, there are too many thing need to remember...

```js
export default class TextFilter extends React.Component {

  afterColumnFilter = (filterConds, result) => {
    console.log('Filter Conditions: ');
    for (const prop in filterConds) {
      console.log('Filter column= ' + prop + ', Filter value= ' + filterConds[prop]);
    }
    console.log('Result is:');
    for (let i = 0; i < result.length; i++) {
      console.log('Product: ' + result[i].id + ', ' + result[i].name + ', ' + result[i].price);
    }
  }

  render() {
    const options = {
      afterColumnFilter: this.afterColumnFilter
    };
    return (
      <BootstrapTable data={ products } options={ options }>
        <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
        <TableHeaderColumn dataField='name' filter={ { type: 'TextFilter', delay: 1000 } }>Product Name</TableHeaderColumn>
        <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
}

```

**Comment by lioralt** [comment]
@AllenFang , sorry for the delayed response, just wanted to say it's working properly.
Once again, thanks a lot :)
