### ISSUE TITLE
"Export to CSV" button should be hidden when printing

### ISSUE THREAD

**Issue by bontibon** [AllenFang/react-bootstrap-table#641]

**Comment by AllenFang** [comment]
printing? How do you to do the print?

**Comment by bontibon** [comment]
Ctrl+P

**Comment by AllenFang** [comment]
@bontibon, I need to do some survey, because i dont know how to hide the button when printing..... have any idea?

**Comment by bontibon** [comment]
@AllenFang 

Add `hidden-print` class to the button

https://getbootstrap.com/css/#responsive-utilities-print

**Comment by AllenFang** [comment]
@bontibon thanks..  I'll check this out

**Comment by AllenFang** [comment]
Released on ```v2.4.3```
