### ISSUE TITLE
select row pagination

### ISSUE THREAD

**Issue by wenit123** [AllenFang/react-bootstrap-table#643]
Every time I select the row which is at the last page. It jump to the default page go the table. Is any way to solve it . thanks

**Comment by AllenFang** [comment]
which version you used, and show me your code. Thanks you :)

**Comment by wenit123** [comment]
I am using ^2.3.2

here is my code.
-------------------------------


import React from 'react'
import {BootstrapTable, TableHeaderColumn} from 'react-bootstrap-table'; 

    function enumFormatter(cell, row, enumObject) {
        return enumObject[cell];
    };

    function glyphsFormatter(cell, row){
        return  '<li class="fa fa-angle-right"></li> '; 
    };

    function getCaret(direction) {
        if (direction === 'asc') {
            return (
                <span className="fa fa-long-arrow-up"/>
            );
        }
        if (direction === 'desc') {
            return (
                <span className="fa fa-long-arrow-down"/>
            );
        }
        return (
            <span className="fa fa-long-arrow-down"/>
        );
    }

export default React.createClass({
    getInitialState(){
        return{
           ..........
        }
    },

    componentDidUpdate(prevProps, prevState) {
        if (prevState.row !== this.state.row) {
            this.props.onClickMsg(this.state.row)
        }
    },

    enumFormatter(cell, row, enumObject){
        return enumObject[cell];
    },

    onRowSelect(row, isSelected){
        console.log(row);        
        console.log("selected: " + isSelected)
        this.setState({
            row: row,
            id : row.id,
            array: row.array,
            author: row.author,
            recipients: row.recipients,
            content: row.content,
            date: row.date,
            year: row.year,
            month: row.month,            
            day: row.day,
            time: row.time,
        })
    },

    render() {

        var options = {
           //page: null,                          // which page you want to show as default
           prePage: "Previous",                 // previous page button text
           nextPage: "Next",                    // next page button text
           paginationSize: 4,                   // pagination bar size, default is 5.
           firstPage: "First",                  // first page button text
           lastPage: "Last"                     // last page button text
        }

        var selectRowProp = {
            mode: "radio",
            clickToSelect: true,
            bgColor: "#F2F6F8",  // color when it be selected
            onSelect: this.onRowSelect,
            hideSelectColumn: true, // to hide the radio select
        }

        return(
            <div className="">
                <div className="">
                    <BootstrapTable data={data} pagination={true} ref='table' selectRow={selectRowProp} options={options}>
                        <TableHeaderColumn dataField="id" isKey hidden>ID</TableHeaderColumn>
                        <TableHeaderColumn dataField="date" dataSort={true} width="30" caretRender={getCaret}>DATE</TableHeaderColumn>
                        <TableHeaderColumn dataField="author" dataSort={true} width="30" caretRender={getCaret}>AUTHOR</TableHeaderColumn>
                        <TableHeaderColumn dataField="title" dataSort={true} width="30" caretRender={getCaret}>TITLE</TableHeaderColumn>
                        <TableHeaderColumn dataField="content" dataSort={true} width="40" caretRender={getCaret}>CONTENT</TableHeaderColumn>
                        <TableHeaderColumn dataField=" " width="5" dataFormat={glyphsFormatter}> </TableHeaderColumn>
                    </BootstrapTable>
                </div>
            </div>
        );     
    },
})

-----------

thank you  :)

**Comment by AllenFang** [comment]
How about upgrade to newest version and try again. BTW why call ```setState``` in ```onRowSelect```

**Comment by wenit123** [comment]
np, I get ^2.4.3 now. Because I need to grab the data that users selected and pass to another component. 

but this:
componentDidUpdate(prevProps, prevState) {
        if (prevState.row !== this.state.row) {
            this.props.onClickMsg(this.state.row)
        }
    },

**Comment by AllenFang** [comment]
Great, feel free to ask my anything :)
