### ISSUE TITLE
Select field (drop down) on cell edit

### ISSUE THREAD

**Issue by edulis8** [AllenFang/react-bootstrap-table#651]
Hello, 
Can you please give another example of how to use drop downs on cell edit? Currently you have `editable={{type:'select', options:{values:jobTypes}}}` but there's no definition of the variable jobTypes in the example. What does it expect as an input and how should it be structured?

Thanks for the awesome.

**Comment by AllenFang** [comment]
Sorry, I'll improve my document.

This is [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/advance/edit-type-table.js) and you can check [this](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js) folder, we have a lots of example code here. Thanks. Feel Free to ask me anything.

**Comment by snsarma** [comment]
Hi Allen

The drop down doesn't appear for me when I include the above in the TableHeader.
I am here with attaching my code where I referred your example : Please provide your inputs ,Your help is much appreciated.

<BootstrapTable data={ products } insertRow={ true } options={ options } >
      <TableHeaderColumn isKey dataField='id'>Field 1</TableHeaderColumn>
      <TableHeaderColumn dataField='name'>Field 2</TableHeaderColumn>
<TableHeaderColumn dataField='name'editable={ { type: 'select', options: { values: 'Y:N' } }}>Field3</TableHeaderColumn>
    </BootstrapTable>  

Fields 1 and 2 also have table header tags but do not appear here , But yes the drop down option for field 3 isn't working in my code

**Comment by mscodes-2496** [comment]
How to auto generate id in react bootstrap table, without giving it manually each time?
