### ISSUE TITLE
About css files

### ISSUE THREAD

**Issue by pvnr0082t** [AllenFang/react-bootstrap-table#653]
Hi @AllenFang ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host this project in cdnjs.
I'd like to confirm if the files under `css` folder also need to be hosted in cdnjs. If yes, is it possible to put files under `css` folder into `dist` folder? 
Thank you.

https://github.com/cdnjs/cdnjs/pull/8776
https://github.com/cdnjs/cdnjs/issues/8751

**Comment by AllenFang** [comment]
@pvnr0082t, ok I'll move the css file to ```dist``` folder **in next version**. Thanks

**Comment by AllenFang** [comment]
Fixed on ```v2.4.4```

**Comment by pvnr0082t** [comment]
Thank you. @AllenFang
