### ISSUE TITLE
Insert Row Modal Dark

### ISSUE THREAD

**Issue by tomc944** [AllenFang/react-bootstrap-table#655]
Whenever I try to insert a new row, the new row modal pops up and the whole screen goes dim instead of just the screen behind the modal. In addition as soon as I press the modal it immediately disappears. Similar behavior for constant dimming is outlined in this issue: #334.

Any help would be appreciated!

**Comment by yjj457** [comment]
I have solved the problem by change the version of bootstrap to 3.3.6

**Comment by AllenFang** [comment]
@tomc944 abd @yjj457, I know there's some issue about this, and I've used ```react-modal``` in ```v3.0.0-dev```. so I think in ```v3.0.0```, this issue will be fixed.

check #497. thanks

**Comment by AllenFang** [comment]
Fixed on `v3.0.0`
