### ISSUE TITLE
What bit of code is doing the popup over the column header?

### ISSUE THREAD

**Issue by dukedougal** [AllenFang/react-bootstrap-table#657]
When I roll the mouse over the column header a little popup appears under the mouse with the column header text in it.

What bit of code is doing that? I want to see how you are doing the popup.

**Comment by bontibon** [comment]
That is just an HTML `title`. See here:

https://github.com/AllenFang/react-bootstrap-table/blob/2e6144c9994ce38d03fff58d50c04f04f343647d/src/TableHeaderColumn.js#L106-L112

**Comment by AllenFang** [comment]
Thanks @bontibon  :)

**Comment by dukedougal** [comment]
Well ya learn something new every day.  I thought I had to make my own popup but there it is built in.
