### ISSUE TITLE
Pagination Feature

### ISSUE THREAD

**Issue by GJ2511** [AllenFang/react-bootstrap-table#658]
Hi,

Is there any kind of feature available  that pagination will work according to some key in the payload like (totalCount)

ex:- `{totalCount: 100, data:[{name:'a'},{name:'a'},{name:'a'}]}`

I want to know How pagination is working.

**Comment by AllenFang** [comment]
@GJ2511, you means you only have three datas but you got ```totalCount``` 100 from you payload?

**Comment by GJ2511** [comment]
@AllenFang It's just an example ,
I have 10000 records but I want to shoe 10 at a time.

**Comment by GJ2511** [comment]
@AllenFang 

My Bad.. anyway thanks for ur support
