### ISSUE TITLE
Support for SelectFilter to use true/false values

### ISSUE THREAD

**Issue by riguy724** [AllenFang/react-bootstrap-table#660]
It seems like there is no support for this presently.  I may put a PR together for this, but just figured i'd open it as an issue to see who else is interested in support for this, or has a suggestion for a workaround.

**Comment by AllenFang** [comment]
@riguy724, PR is welcome and I'll try to reproduce this issue and figure the root cause. Thanks :)

**Comment by AllenFang** [comment]
@riguy724, I'll fix it in next version.

**Comment by AllenFang** [comment]
Fixed on ```v2.4.4```.

**Comment by riguy724** [comment]
Thanks @AllenFang , excited to try this out!

**Comment by AllenFang** [comment]
@riguy724, there's one thing to notice, on ```v2.4.4``` I move the css files from ```css``` to ```dist``` folder, remember to update the css path. I apologize for it.
