### ISSUE TITLE
pagination covers table when setting maxheight

### ISSUE THREAD

**Issue by grigored** [AllenFang/react-bootstrap-table#666]
See attached image.
<img width="1433" alt="screen shot 2016-08-30 at 3 51 35 am" src="https://cloud.githubusercontent.com/assets/12827406/18072239/376a896e-6e65-11e6-95b8-21495ee7d27e.png">

**Comment by grigored** [comment]
Turns out the .react-bs-container-body gets the same maxheight as the .react-bs-table. If we set .react-bs-container-body to maxheight-40px, it looks fine.

**Comment by AllenFang** [comment]
@grigored, I'll check this out. Thanks

**Comment by AllenFang** [comment]
@grigored, what's version of ```react-bootstrap-table``` you used?

**Comment by grigored** [comment]
@AllenFang I had 2.5.0, just upgraded to 2.5.1, same problem. My current fix is:
let reactBsContainerBody = document.getElementsByClassName("react-bs-container-body");
        for (var i = 0; i < reactBsContainerBody.length; i++ ) {
            reactBsContainerBody[i].style['max-height'] = (window.innerHeight - 245) + 'px';
        }

**Comment by AllenFang** [comment]
@grigored,  thanks, one more question, what value of  ```maxheight``` you given?  and did you configured ```hieght```?

**Comment by grigored** [comment]
Sorry for forgetting to mention this, the table `maxheight` is `(window.innerHeight - 200) + 'px';`, and height is not configured. Thanks for your help.

**Comment by AllenFang** [comment]
@grigored, Fixed on ```v2.5.2```, make it a try 👍
