### ISSUE TITLE
this.refs.inputRef.focus is not a function

### ISSUE THREAD

**Issue by cytim** [AllenFang/react-bootstrap-table#667]
I am using `customEditor` on `TableHeaderColumn`.
The custom editor is a [react-select](https://jedwatson.github.io/react-select/) component instead of any HTML input element.

It throw the following error whenever I click on the cell to render the editor:
```
TableEditColumn.js:129 Uncaught TypeError: this.refs.inputRef.focus is not a function
```

I am not sure if I am using `customEditor` correctly. Thanks for any help!

---

**`table.js`**

```js
  ...

  const Table = React.createClass({
    ...

    cellEditProp: {
      mode: 'click'
    },

    createLocationCell: function(cellData, row) {
      return <div className="tags">{cellData.join(',')}</div>
    },

    createLocationEditor: function(onSave, props) {
      return (
        <SelectEditor
          multi
          options={ [ { value: 'A', label: 'Loc A' }, { value: 'B', label: 'Loc B' }, { value: 'C', label: 'Loc C' } ] }
          value={props.row.locations}
          onSave={onSave}
          {...props}
        />
      )
    },

    render: function() {
      const rows = [ { id: 1, locations: ['B'] }, { id: 2, locations: ['B', 'C'] } ]
      return (
        <BootstrapTable data={rows} striped={true} bordered={false} hover={true} pagination={true} cellEdit={this.cellEditProp}>
          <TableHeaderColumn dataField="id" isKey={true} hidden={true}>ID</TableHeaderColumn>
          <TableHeaderColumn
              dataField="locations"
              dataFormat={this.createLocationCell}
              dataSort={false}
              customEditor={{getElement: this.createLocationEditor}}
              width="150">
            Locations
          </TableHeaderColumn>
        </BootstrapTable>
      )
    }
  })

  module.exports = Table
```

---

**`select-editor.js`**

```js
import Select from 'react-select'
...

const SelectEditor = React.createClass({
  getInitialState: function() {
    return { value: this.props.value }
  },

  onChange: function(selectedOptions) {
    const value = _.map(selectedOptions, 'value')
    this.setState({ value: selectedOptions })
  },

  onSave: function() {
    this.props.onSave(this.state.value)
  },

  render: function() {
    return (
      <div ref="inputRef" className="select-editor">
        <Select
          multi={this.props.multi}
          placeholder="Pick your options..."
          value={this.state.value}
          options={this.props.options}
          onChange={this.onChange}
        />
        <Button onClick={this.onSave}>Save</Button>
      </div>
    )
  }
})

module.exports = SelectEditor
```

---

**Comment by cytim** [comment]
I tried to put the `ref="inputRef"` inside the `<Select />`, but it doesn't help.
Another trial was to add `<input ref="inputRef" type="text" />`, failed as well...

**Comment by cytim** [comment]
I am not sure if another issue should be opened.

I found that the editor fails to toggle if I do the following:

1. Click to open Row 1 location editor
2. Click to open Row 2 location editor
    * (Row 1 editor is closed without save)
    * (Row 2 editor is opened)
3. Click to open Row 1 location editor again
    * (Row 2 editor is closed without save)
    * (Row 1 editor is opened)
4. Try to open Row 2 location editor --> Fail (but no error is consoled)

**Comment by cytim** [comment]
The `Uncaught TypeError` has been fixed by adding an empty `focus` function in the SelectEditor class.

```js
const SelectEditor = React.createClass({
  ...
  focus: function() {}
  ...
})
```

[This issue](#issuecomment-243320115) is solved subsequently. Haha =P

**Comment by AllenFang** [comment]
@cytim, good job :)

**Comment by konghoiwai** [comment]
I am seeing the same issue using customEditor.   Adding focus function doesn't work for me.  @cytim any other pointers you can provide ?   Thx

**Comment by EnriqueAbricot** [comment]
@cytim I did what you pointed out but I still get **Uncaught TypeError: this.refs.inputRef.focus is not a function at TableEditColumn.componentDidMount**, there is something else to solve this problem...

**Comment by AllenFang** [comment]
@EnriqueAbricot, which version you use now?
