### ISSUE TITLE
table direction

### ISSUE THREAD

**Issue by Ka1beatsCN** [AllenFang/react-bootstrap-table#669]
can i fix my table header to the left while table content to the right?

**Comment by AllenFang** [comment]
you means the text align on header and body?

**Comment by Ka1beatsCN** [comment]
no, I just want rotate the whole table by 90 degrees anti-clock

**Comment by AllenFang** [comment]
@Ka1beatsCN, sorry ```react-bootstrap-table``` can't support this feature and I wont support it in near future.
