### ISSUE TITLE
Only enable delete on inserted rows

### ISSUE THREAD

**Issue by edulis8** [AllenFang/react-bootstrap-table#673]
Hello,
Is there a way that I can only enable deletion for rows that have been inserted by the user? The user shouldn't be able to delete the original dataset, only the rows that he/she adds to the table before saving.
Thanks.

**Comment by AllenFang** [comment]
use ```unselectable``` in ```selectRow``` props. because ```react-bootstrap-table``` only drop row which being selected.  so if you add the rowkey to ```unselectable``` after user inserted, you can make these inserted row unselectable.

BTW, there's known bug about ```unselectable```, check #670.  I'll fix it quickly. Thanks

If you have any question or dont know how to write it, I can provide a example for you :)

**Comment by edulis8** [comment]
Hi Allen,
Thank you for your quick response. I would love an example.

Thanks,
Eric

**Comment by AllenFang** [comment]
@edulis8, ok, wait #670 fixed, I'll give an example for you 👍

**Comment by AllenFang** [comment]
```js
/* eslint max-len: 0 */
import React from 'react';
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';


const products = [];

function addProducts(quantity) {
  const startId = products.length;
  for (let i = 0; i < quantity; i++) {
    const id = startId + i;
    products.push({
      id: id,
      name: 'Item name ' + id,
      price: 2100 + i
    });
  }
}

addProducts(5);

const selectRowProp = {
  mode: 'checkbox',
  clickToSelect: true,
  unselectable: products.map(p => p.id)
};

export default class DemoTable extends React.Component {
  render() {
    return (
      <BootstrapTable data={ products } selectRow={ selectRowProp } insertRow deleteRow>
          <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
}

```
