### ISSUE TITLE
Object object on every row

### ISSUE THREAD

**Issue by devanandb** [AllenFang/react-bootstrap-table#675]
In the latest update from 2.4.4 and 2.5 the table just shows Object Object instead of values

**Comment by AllenFang** [comment]
@devanandb, could you show me your example?

**Comment by bartbone** [comment]
Got the same problem since 2.4.4.:
`<BootstrapTable data={this.state.brands} pagination={true} bordered={false} striped={true} options={{paginationShowsTotal:true }}keyField={"brandId"}>
              <TableHeaderColumn dataField="countryCode" dataAlign="center" className="td-header-metro" width="150" dataSort={true}>CC</TableHeaderColumn>
              <TableHeaderColumn dataField="brandId" dataAlign="center" className="td-header-metro" width="150" dataSort={true}>ID</TableHeaderColumn>
              <TableHeaderColumn dataField="link" dataAlign="center" className="td-header-metro" width="150">Supplier linkage</TableHeaderColumn>
            </BootstrapTable>`

The link dataFiled contains the following:
brands.link=(<Button id={i} bsStyle="primary" onClick={this.handleLinkClick}>></Button>);

From version 2.4.4. it doesn't show the Button anymore but [object Object]

**Comment by AllenFang** [comment]
@bartbone, good example, but could you please show me your data(```brands```)?

I guess the each object in brands array that all contain the link field and the content is a JSX ?

**Comment by bartbone** [comment]
Yes they all contain them, also some other objects, here you got a view on the brand data:
![image](https://cloud.githubusercontent.com/assets/7192078/18440703/6b267b32-790a-11e6-967b-0d7c28037ee5.png)

**Comment by bartbone** [comment]
Ok if I use the dataFormat function and just return the row.link it works.
``
<TableHeaderColumn dataField="link" dataFormat={this.format} dataAlign="center" className="td-header-metro" width="150">Supplier linkage</TableHeaderColumn>

format(cell, row){
    return row.link;
}

**Comment by AllenFang** [comment]
@bartbone, sorry for lately reply. You should just use ```dataFromat``` to customize your cell or JSX.  Thanks.

**Comment by HASSANI8046** [comment]
Could not solve this issue
