### ISSUE TITLE
Column-show-hide function

### ISSUE THREAD

**Issue by erikagrebur** [AllenFang/react-bootstrap-table#676]
I would like to be able to choose with a dropdown, which columns are shown in my table. 

Something like in this example: http://issues.wenzhixin.net.cn/bootstrap-table/

I would like to use the "column" dropdown button in a toolbar. 

How can I do that with react-bootstrap-table? Someone has an idea?
Thanks!

**Comment by AllenFang** [comment]
@erikagrebur, there's some issue to implement column toggle function. BTW, if you want to create custom component on toolbar, just wait ```v3.0.0```.  check #497.  Thanks
