### ISSUE TITLE
Is it possible to freeze/fix columns?

### ISSUE THREAD

**Issue by LoriTillery** [AllenFang/react-bootstrap-table#677]
I tried the keywords fixed  and frozen.  Also searched the examples and the repo but I can't find related attributes to use to fix columns during horizontal scrolling.   I'm looking to freeze 2 columns in the beginning of a 27 column table.  Thanks.

**Comment by AllenFang** [comment]
@LoriTillery, sorry for lately reply. It's unable to do this and there not any plan for this feature. PR is welcome
