### ISSUE TITLE
Retrieve the exported .csv or get the current filtered rows 

### ISSUE THREAD

**Issue by jonasostrom** [AllenFang/react-bootstrap-table#678]
Hi,
Is it possible to get all the current filtered rows from the table?
I want to convert the .csv file to a pdf or excel on the same time the user clicks "export to csv".

Great work!

/Jonas

**Comment by AllenFang** [comment]
> I want to convert the .csv file to a pdf or excel on the same time the user clicks "export to csv".

@jonasostrom, ```exportCSV``` only export the filtered data to csv file

Hop I've answer it or any feature you want?  Feel free to discuss with me. Thanks 👍

**Comment by jonasostrom** [comment]
I want to access the rows that is exported so that I can export it with my own functions as well.

**Comment by jonasostrom** [comment]
something like: onExport={this.userExportedRows} // new props on table to call my own function
then:

_userExportedRows(rows){

}

**Comment by AllenFang** [comment]
call ```onExportToCSV``` which exposed by ```BootstrapTable```. and you can current data(filtered) by calling ```getTableDataIgnorePaging``` also exposed by ```BootstrapTable```.

**Comment by AllenFang** [comment]
BTW, you have to return the result which you want to be exported in ```onExportToCSV````

**Comment by jonasostrom** [comment]
Ah cool. Thank you so much!

**Comment by wazzzzza** [comment]
Hi quick one on this, where is the best place to call the `getTableDataIgnorePaging` function? I need to call it as soon as the table is filtered through `applyFilter` so I thought the `componentWillReceiveProps` method would make sense but when I do that, I get an infinite loop with maximum call stack size exceeded error message. 
`componentWillReceiveProps(nextProps){
          this.props.callAF_filteredData(this.refs.ttpTable.getTableDataIgnorePaging);
    }`
Any idea?
