### ISSUE TITLE
Handle search with an external API call

### ISSUE THREAD

**Issue by Clafouti** [AllenFang/react-bootstrap-table#679]
Hi, I'm trying to implement a search with a server-side logic.

What I currently do is :

1. Provide the react-bootstrap-table a function to handle the search : 
`options={{ onSearchChange: this.props.handleSearchChange, searchDelayTime: 2000 }}`
I also set the delay time to 2000ms so the API call isn't triggered too often.

2. Make the API call on `handleSearchChange` : 
`handleSearchChange(searchText) {
    specificAPICall(searchText).then(function (data) {
      this.setState({
        // change state with data, re-render the table
      });
    }, function(error) {
      console.log(error);
    });
  },`

I really want to use the "search" field you provide with the table. The problem is that I don't know how to "cancel" the default behavior of the table, which is to perform a search inside the data I provide earlier. Is there a way I can perform a better custom search with the "search" field you provide ?

EDIT : I was reading the doc and saw the `remote` attribute. I'm now using this as it seems to be what I'm asking for on this issue. I'm leaving it opened but if I'm right with the `remote`use, I'll take it as a "That's the right way".

**Comment by AllenFang** [comment]
> EDIT : I was reading the doc and saw the remote attribute. I'm now using this as it seems to be what I'm asking for on this issue. I'm leaving it opened but if I'm right with the remoteuse, I'll take it as a "That's the right way".

Absolutely right 👍 

```remote``` is a mechanism for you to handle any state changing(sort, paging, filter, search, insert etc.) on your store(flux), and make the component more stateless and pure.
