### ISSUE TITLE
React 0.14 support

### ISSUE THREAD

**Issue by aaronhayes** [AllenFang/react-bootstrap-table#68]
Should update the package to support React 0.14.

Current warnings:
Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `TableHeaderColumn`.

**Comment by AllenFang** [comment]
HI @aaronhayes, I'll patch it, thanks your contributions :)

**Comment by AllenFang** [comment]
Upgrade to react@0.14 in newest version. But not yet fix warning, I'll spend some time to patch.

**Comment by Lothiraldan** [comment]
Argh hit the bug today, did you have the time to fix compatibility with react 0.14?

**Comment by AllenFang** [comment]
HI @Lothiraldan, what bugs you found? it's about <code>react-bootstrap-table</code>?

**Comment by Lothiraldan** [comment]
Yes the same problem:

~~~
Uncaught TypeError: Cannot read property 'getDOMNode' of undefined
~~~

in ```TableHeaderColumn.js:35```

**Comment by AllenFang** [comment]
Ensure you use react@1.4.0 and react-bootstrap-table@1.2.0

**Comment by Lothiraldan** [comment]
Ok now it works but I have the warning, will wait for a future release, thank you!

**Comment by AllenFang** [comment]
Great! :)
