### ISSUE TITLE
Regarding sizePerPageList 

### ISSUE THREAD

**Issue by nuwanprabhath** [AllenFang/react-bootstrap-table#682]
Hi, 
Is there anyway to get size per page as "All" in page size drop down. Currently we can pass a numeric array. Example would be 5, 10, 20 and "All" in drop down.

Thanks

**Comment by nuwanprabhath** [comment]
Hi, 
thanks for reply.
Yah I guess this is totally fine. Highly appreciate if you can make it in next version. 

Thanks.

**Comment by AllenFang** [comment]
@nuwanprabhath, released on ```v2.5.2```, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/pagination/custom-pagination-table.js#L35) example

**Comment by nuwanprabhath** [comment]
Thanks :)

**Comment by nuwanprabhath** [comment]
Hi tried your example and it is working except for small concern. When I select "All" from the drop down it shows the exact number instead of "All" as selected item in drop down. For example if there are 101 entries it shows 101 in drop down after selecting "All" option in drop down.  

Thanks

**Comment by AllenFang** [comment]
@nuwanprabhath, ok I'll try to fix it, sorry ;(

**Comment by AllenFang** [comment]
@nuwanprabhath, sorry for lately fix, released on ```v2.5.6```. Thanks
