### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by razagill** [AllenFang/react-bootstrap-table#683]
Hey guys,
Trying it out with bootstrap 4 but looks like the pagination doesn't have the correct CSS. They are just appearing as a list. Anyone else experiencing it?

**Comment by AllenFang** [comment]
@razagill, I haven't yet to test with bootstrap 4. Maybe we need a good plan to do this job :)  But before this, I need to get ```v3.0.0``` done in near future.

**Comment by razagill** [comment]
@AllenFang cool. I noticed there are some new classes that Bootstrap 4 adds to the pagination ```ul``` and ```li``` elements. I added those classes and it's working fine for now. Maybe we can have a small conditional to check if the version of bootstrap is 4 then add those classes.

**Comment by AllenFang** [comment]
@razagill, PR is welcome :)

**Comment by philohelp** [comment]
That would be a great help, thanks !

**Comment by philohelp** [comment]
@razagill Meanwhile would you mind releasing the trick concerning bs4 new classes ? Thanks !

**Comment by razagill** [comment]
@philohelp Sure, here you go: https://github.com/razagill/react-bootstrap-table/blob/master/src/pagination/PageButton.js

**Comment by AllenFang** [comment]
Fixed on ```v2.5.4```. Thanks :)
