### ISSUE TITLE
Cant select a diferent value on the dropdown pagination

### ISSUE THREAD

**Issue by CusProjects** [AllenFang/react-bootstrap-table#686]
`<BootstrapTable options={options} paginationSize={2} data={products} striped={true} hover={true} pagination={true} selectRow={selectRowProp} >
					      <TableHeaderColumn isKey={true} dataField="id" dataSort={true}>Product ID</TableHeaderColumn>
					      <TableHeaderColumn dataField="name" dataSort={true}>Product Name</TableHeaderColumn>
					      <TableHeaderColumn dataField="price" dataSort={true}>Product Price</TableHeaderColumn>
					  </BootstrapTable>`

**Comment by CusProjects** [comment]
The Dropdown Button doesn't work!...

**Comment by AllenFang** [comment]
@CusProjects, you have to include ```bootstrap.js```. After ```v3.0.0```(on developing), we hope remove this dependency. Thanks.

Feel free to discuss with me

**Comment by CusProjects** [comment]
@AllenFang Thank you so much , i will try it

**Comment by CusProjects** [comment]
@AllenFang What can i do if im using react-bootstrap ? i don't want to import bootstrap.js as CDN

**Comment by AllenFang** [comment]
you can still use ```react-bootstrap```, but currently, you should add bootstrap.js. Like my mention, I'll try to remove this dependency in ```v3.0.0```
