### ISSUE TITLE
isKey problem

### ISSUE THREAD

**Issue by NaviivaN21** [AllenFang/react-bootstrap-table#687]
Hello Guys,

I have a question below.
**Edited.**
I got the following warning: 
warning.js:36 Warning: flattenChildren(...): Encountered two children with the same key, `1010111`. Child keys must be unique; when two children share a key, only the first child will be used.

Is there anyway that I can hide this in console logs? 
It is doing the job for me at least.

Please check.

**Comment by AllenFang** [comment]
hello, would you please show me your example? and you mean you have duplicated key in your data?

**Comment by NaviivaN21** [comment]
Hello!

I already fixed this problem.

Thanks!
