### ISSUE TITLE
Table throws error saying Uncaught TypeError: Cannot read property 'props' of null

### ISSUE THREAD

**Issue by smartameer** [AllenFang/react-bootstrap-table#69]
Even after using one ``` isKey={true}``` TableHeaderColumn throws ```column.props.isKey``` :- props undefined and columns gives ```null```

I have recently upgraded all dependency, 
    "react": "^0.14.0",
    "react-bootstrap": "^0.27.1",
    "react-dom": "^0.14.0",
    "react-router": "^1.0.0-rc3",
    "react-bootstrap-table": "^1.0.3"

VM4387 is nothing but BootstrapTable.js

> (anonymous function)	@	VM4387:44
> forEachSingleChild	@	ReactChildren.js?d440:39
> traverseAllChildrenImpl	@	traverseAllChildren.js?7ca8:111
> traverseAllChildrenImpl	@	traverseAllChildren.js?7ca8:210
> traverseAllChildrenImpl	@	traverseAllChildren.js?7ca8:133
> traverseAllChildren	@	traverseAllChildren.js?7ca8:246
> forEachChildren	@	ReactChildren.js?d440:60
> BootstrapTable	@	VM4387:43
> ReactCompositeComponentMixin.mountComponent	@	ReactCompositeComponent.js?cd59:148
> ReactPerf.measure.wrapper	@	ReactPerf.js?ef93:66
> ReactReconciler.mountComponent	@	ReactReconciler.js?6bfa:37
> ReactCompositeComponentMixin.mountComponent	@	ReactCompositeComponent.js?cd59:225
> ReactPerf.measure.wrapper	@	ReactPerf.js?ef93:66
> ReactReconciler.mountComponent	@	ReactReconciler.js?6bfa:37
> ReactMultiChild.Mixin.mountChildren	@	ReactMultiChild.js?c87d:241
> ReactDOMComponent.Mixin._createContentMarkup	@	ReactDOMComponent.js?1302:592
> ReactDOMComponent.Mixin.mountComponent	@	ReactDOMComponent.js?1302:482
> ReactReconciler.mountComponent	@	ReactReconciler.js?6bfa:37
> ReactCompositeComponentMixin.mountComponent	@	ReactCompositeComponent.js?cd59:225
> ReactPerf.measure.wrapper	@	ReactPerf.js?ef93:66
> ReactReconciler.mountComponent	@	ReactReconciler.js?6bfa:37
> ReactCompositeComponentMixin.mountComponent	@	ReactCompositeComponent.js?cd59:225
> ReactPerf.measure.wrapper	@	ReactPerf.js?ef93:66
> ReactReconciler.mountComponent	@	ReactReconciler.js?6bfa:37
> ReactMultiChild.Mixin.mountChildren	@	ReactMultiChild.js?c87d:241
> ReactDOMComponent.Mixin._createContentMarkup	@	ReactDOMComponent.js?1302:592
> ReactDOMComponent.Mixin.mountComponent	@	ReactDOMComponent.js?1302:482
> ReactReconciler.mountComponent	@	ReactReconciler.js?6bfa:37
> ReactCompositeComponentMixin.mountComponent	@	ReactCompositeComponent.js?cd59:225
> ReactPerf.measure.wrapper	@	ReactPerf.js?ef93:66
> ReactReconciler.mountComponent	@	ReactReconciler.js?6bfa:37
> ReactMultiChild.Mixin.mountChildren	@	ReactMultiChild.js?c87d:241
> ReactDOMComponent.Mixin._createContentMarkup	@	ReactDOMComponent.js?1302:592
> ReactDOMComponent.Mixin.mountComponent	@	ReactDOMComponent.js?1302:482
> ReactReconciler.mountComponent	@	ReactReconciler.js?6bfa:37
> ReactCompositeComponentMixin.mountComponent	@	ReactCompositeComponent.js?cd59:225
> ReactPerf.measure.wrapper	@	ReactPerf.js?ef93:66
> ReactReconciler.mountComponent	@	ReactReconciler.js?6bfa:37
> ReactMultiChild.Mixin.mountChildren	@	ReactMultiChild.js?c87d:241
> ReactDOMComponent.Mixin._createContentMarkup	@	ReactDOMComponent.js?1302:592
> ReactDOMComponent.Mixin.mountComponent	@	ReactDOMComponent.js?1302:482
> ReactReconciler.mountComponent	@	ReactReconciler.js?6bfa:37
> ReactCompositeComponentMixin.mountComponent	@	ReactCompositeComponent.js?cd59:225
> ReactPerf.measure.wrapper	@	ReactPerf.js?ef93:66
> ReactReconciler.mountComponent	@	ReactReconciler.js?6bfa:37
> ReactMultiChild.Mixin.mountChildren	@	ReactMultiChild.js?c87d:241
> ReactDOMComponent.Mixin._createContentMarkup	@	ReactDOMComponent.js?1302:592
> ReactDOMComponent.Mixin.mountComponent	@	ReactDOMComponent.js?1302:482
> ReactReconciler.mountComponent	@	ReactReconciler.js?6bfa:37
> ReactCompositeComponentMixin.mountComponent	@	ReactCompositeComponent.js?cd59:225
> ReactPerf.measure.wrapper	@	ReactPerf.js?ef93:66
> ReactReconciler.mountComponent	@	ReactReconciler.js?6bfa:37
> ReactCompositeComponentMixin.mountComponent	@	ReactCompositeComponent.js?cd59:225
> ReactPerf.measure.wrapper	@	ReactPerf.js?ef93:66
> ReactReconciler.mountComponent	@	ReactReconciler.js?6bfa:37
> ReactCompositeComponentMixin.mountComponent	@	ReactCompositeComponent.js?cd59:225
> ReactPerf.measure.wrapper	@	ReactPerf.js?ef93:66
> ReactReconciler.mountComponent	@	ReactReconciler.js?6bfa:37
> ReactCompositeComponentMixin.mountComponent	@	ReactCompositeComponent.js?cd59:225
> ReactPerf.measure.wrapper	@	ReactPerf.js?ef93:66
> ReactReconciler.mountComponent	@	ReactReconciler.js?6bfa:37
> mountComponentIntoNode	@	ReactMount.js?2f23:266
> Mixin.perform	@	Transaction.js?6dff:136
> batchedMountComponentIntoNode	@	ReactMount.js?2f23:282
> Mixin.perform	@	Transaction.js?6dff:136
> ReactDefaultBatchingStrategy.batchedUpdates	@	ReactDefaultBatchingStrategy.js?ef70:62
> batchedUpdates	@	ReactUpdates.js?ce09:94
> ReactMount._renderNewRootComponent	@	ReactMount.js?2f23:476
> ReactPerf.measure.wrapper	@	ReactPerf.js?ef93:66
> ReactMount._renderSubtreeIntoContainer	@	ReactMount.js?2f23:545
> ReactMount.render	@	ReactMount.js?2f23:565
> ReactPerf.measure.wrapper	@	ReactPerf.js?ef93:66
> (anonymous function)	@	module.js?983c:15
> webpackJsonp.996	@	module.js?ece69743e32c95b710ff:16
> _ _webpack_require__	@	common.js?ece69743e32c95b710ff:540
> fn @ common.js?ece69743e32c95b710ff:99
> webpackJsonp.0	@	module.js?ece69743e32c95b710ff:8
> _ _webpack_require_ _	@	common.js?ece69743e32c95b710ff:540
> webpackJsonpCallback	@	common.js?ece69743e32c95b710ff:22
> (anonymous function)	@	module.js?ece69743e32c95b710ff:1
```

**Comment by AllenFang** [comment]
hi @smartameer , can you give me the code, show how you use <code>react-bootstrap-table</code> ?

**Comment by smartameer** [comment]
This is a sample file.
https://gist.githubusercontent.com/smartameer/8383989d276adda133b9/raw/edea22d6abd95b6dd617003a06c0b440ea93e6e2/table.js

**Comment by AllenFang** [comment]
HI @smartameer, I know the root cause, because you use the react 0.14, I've tried it, the error message is same as your, but <code>react-bootstrap-table</code> does not support react 0.14. However, these <a href='https://github.com/AllenFang/react-bootstrap-table/issues/68'>issues</a> about upgrade to react 0.14 and I'll patch this problem quickly :)

**Comment by smartameer** [comment]
Ok. I was unaware as it is not opposing while upgrading.
Another enhancement if possible, I did all customization like formatting and hiding some columns using raw data. Can i get that formatted data(combination of headername and value) as json so that we don't have to worry about exporting.

**Comment by AllenFang** [comment]
HI @smartameer, sorry, <code>react-bootstrap-table</code> doesn't not support export feature currently :)

**Comment by AllenFang** [comment]
Upgrade to react@0.14 in newest version. But not yet fix warning, I'll spend some time to patch.
