### ISSUE TITLE
Add tabbing functionality to editable cells

### ISSUE THREAD

**Issue by Smedzlatko** [AllenFang/react-bootstrap-table#693]
It would be nice if user could tab through all editable cells in the table. At the moment, only buttons and links can be accessed with TAB.

**Comment by AllenFang** [comment]
@Smedzlatko, thanks this suggestion.  I'll consider to add this feature in the future :)

**Comment by AllenFang** [comment]
Forgot to close it and already fixed on `v3.0.0`
