### ISSUE TITLE
How to reset all column filters?

### ISSUE THREAD

**Issue by obiwarn** [AllenFang/react-bootstrap-table#694]

**Comment by AllenFang** [comment]
HI @obiwarn, sorry for lately reply, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/all-filters.js#L62)

**Comment by juanpasolano** [comment]
Hi @AllenFang Is there a way to get every column without making them a `ref` first. 
May be somewhere in the BootstrapTable Ref?
