### ISSUE TITLE
Row wrap

### ISSUE THREAD

**Issue by philohelp** [AllenFang/react-bootstrap-table#698]
Hello !

Thanks for the amazing job you've been doing with react-bootstrap-table, it's a great experience to use ! 

I was wondering how it would be possible to achieve this kind of layout with the table : 
<img width="442" alt="capture d ecran 2016-09-11 10 29 08" src="https://cloud.githubusercontent.com/assets/12623963/18416131/3e070f36-780b-11e6-8b37-d84b33deaf13.png">

I did it rapidly on a single column data-formatted as a react component but that wasn't satisfying because I lost the built-in edit functionality. 

Thanks for your help

**Comment by AllenFang** [comment]
HI @philohelp, I think it's hard to implement this row formatting and I may not support this feature in near future, sorry.

BTW, you said you have already implement this style by ```dataFormat``` but lost the cell editing? I think you can need to customize a cell editing.

You can show me your example, I'm not sure that I can help you but maybe I can give you some idea :)
