### ISSUE TITLE
customization of the rows

### ISSUE THREAD

**Issue by accateo** [AllenFang/react-bootstrap-table#699]
Hi, I'm using your code, but I have different problems. This is my code:

```
<BootstrapTable
                data={this.state.exchanges}
                hover={true}
                condensed={true}
                pagination={true}>
              <TableHeaderColumn dataField="name" isKey={true} dataAlign="right">Nome</TableHeaderColumn>
              <TableHeaderColumn dataField="exchangeProgram" >Programma</TableHeaderColumn>
              <TableHeaderColumn dataField="exchangeCountry" dataAlign="center" >Paese</TableHeaderColumn>
              <TableHeaderColumn dataField="exchangeCity" dataAlign="center">Città</TableHeaderColumn>
              <TableHeaderColumn dataField="university" dataAlign="center">Università</TableHeaderColumn>
            </BootstrapTable>
```

- If I wanted two fields in the same column? For example name and surname?
- I have "university" object in my "exchanges". This "university" object is composed by "name, location, etc" fileds. How can I access to these sub-fields? What is the command for dataFields? "university.name"?
- I want to put a link in the first column. This link is composed by the id of the single row. How can I put it?
- Last question: when I render the table, under it there is a selection of "how many results I want to see". This selection is default 10. How can I change this?
Thanks

**Comment by philohelp** [comment]
It's pretty easy to have wo fields in the same column : 
`<TableHeaderColumn dataFormat={FullName}...` 
then 
```
function FullName(cell, row){
  return	(
    <div>{row.name} {row.surname}</div>
  )
}
```
But maybe (?) you lose some functionalities, as cell-edit. 

With question n°3, I believe you can do : 
`<TableHeaderColumn dataField="name" dataFormat={linkedName} dataAlign="right">Nome</TableHeaderColumn>`

then

**Comment by AllenFang** [comment]
@philohelp, good anwsering.

1. like @philohelp said, use ```dataFormat```, and you can give either field to ```dataField```.
2. ```react-bootstrap-table``` doesn't support the nest data object, you can just give ```university``` on ```dataField``` and use ```dataFormat``` to pick up the data you want.
3. answered by @philohelp 
4. https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/pagination/custom-pagination-table.js#L42

**Comment by accateo** [comment]
Thanks for all! Nice package!
