### ISSUE TITLE
Not Preserving Pagination and Ordering after setData

### ISSUE THREAD

**Issue by ben-ward** [AllenFang/react-bootstrap-table#70]
I'm using the BootstrapTable with the following options.

<BootstrapTable search={true} data={this.dataSet} pagination={true} striped={true} hover={true} className="table table-striped table-bordered nowrap" width="100%">

After I use setData the current page and any ordering is lost. 

I could rerender the component if I had some way of passing the current page and ordering field via the options attribute. Is there anyway to get the current page or ordering?

Great work BTW. This was really helpful.

Thanks,
Ben

**Comment by 02ps719** [comment]
I have fixed this. Shall send in a pull request soon. Also fixed the an issue with search filter not filtering when setData was being used to add/edit/delete rows matching the search criteria.

**Comment by ben-ward** [comment]
@02ps719 nice! that would be great

**Comment by AllenFang** [comment]
Thanks @02ps719's work :)  :+1:  and about @ben-ward's said, I'll think about how to get curr page and ordering, but if I give you some hook for page changing or data sorting and pass data which you want, maybe it's a good way to this enhancement.

**Comment by AllenFang** [comment]
HI all, this issue has been solved on v1.2.1 :)

**Comment by AllenFang** [comment]
About how to get current page and get ordering, can use the newest version and see <a href="https://github.com/AllenFang/react-bootstrap-table/blob/master/CHANGELOG.md">CHANGELOG.md</a>
