### ISSUE TITLE
pagination show totals

### ISSUE THREAD

**Issue by bartbone** [AllenFang/react-bootstrap-table#702]
Got a table with 19 rows and a size of 10 per page.
First the totals shows "Showing rows 1 to 10 of 19"
If I switch to 25 per page I got "Showing rows 1 to 10 of 20" so one more?

For a table with 6 rows it shows "Showing rows 1 to 7 of 6"

**Comment by jflayhart** [comment]
Yes this is also an issue, `1 to 5 of 4`

**Comment by AllenFang** [comment]
I'll check this out.

**Comment by AllenFang** [comment]
Fixed on ```v2.5.3```

**Comment by jflayhart** [comment]
Keep up the good work, @AllenFang!
