### ISSUE TITLE
table content <a> other webpage

### ISSUE THREAD

**Issue by ryanbelt** [AllenFang/react-bootstrap-table#703]
```
<BootstrapTable data={[{_id:1}]}>
        <TableHeaderColumn dataField="_id" isKey={true}>Product ID</TableHeaderColumn>
</BootstrapTable>
```
how can I link each product id to some other web page

e.g when I click the the 1, it will direct me to http://****/products/1

**Comment by AllenFang** [comment]
@ryanbelt, sorry for lately reply. You can use ```dataFormat``` to custom the anchor. Feel free to discuss with me :)
