### ISSUE TITLE
Should not deselect disabled checked checkbox on click on unselected all

### ISSUE THREAD

**Issue by anujemc** [AllenFang/react-bootstrap-table#704]
There is an issue we face where there are some rows which shows as checked and disabled , and there should not be any action expected on these rows , since we are not able to do any action on check of check box because those are disabled but when we click on unselected all it deselect the disabled selected rows but it should not do any action on disabled rows as per the expectation , not able to restrict this action by implementation of function call on "unselected all" click  

please check below screen shots of current implementation , for more clarity 
please suggest how we can implement this functionality , or its a bug , we are stuck here .
we are currently using version 4.x of react-bootstrap-table

**At the initial point when TableSelect loads -** 
![disablechackbox](https://cloud.githubusercontent.com/assets/19282193/18482498/f94244a2-79fd-11e6-9d15-f39ec1bcc86e.PNG)

**After click on "unselected all" checkbox click, disable checkbox also unchecked but it should not** 
![disabledcheckbos](https://cloud.githubusercontent.com/assets/19282193/18482507/029983ee-79fe-11e6-8456-adbdd3dadb4b.PNG)

**Comment by AllenFang** [comment]
@anujemc, what's the version you used?

**Comment by anujemc** [comment]
I am currently using latest version of react-bootstrap-table , which is v2.5.2

**Comment by AllenFang** [comment]
ok, it's a bug, I'll fix it quickly.

**Comment by AllenFang** [comment]
Fixed on ```2.5.3```. Thanks

**Comment by anujemc** [comment]
Thanks for your quick fix ..
