### ISSUE TITLE
clearSearch needs support for languages/i18n

### ISSUE THREAD

**Issue by L5eoneill** [AllenFang/react-bootstrap-table#706]
Options for search should include clearSearchText to support languages/i18n, icons, etc, instead of the word "Clear"

So we could do 
options={
  {clearSearch: true,
   clearSearchText: (a string or icon such as FontAwesome glyph for the button text)
  }}

**Comment by AllenFang** [comment]
ok, I'll consider to add this feature in ```v3.0.0```. check #497   Thanks :)

**Comment by anita166** [comment]
Hi @AllenFang, are there any new information about this feature? I'm working on a international project so this would be really useful :)! Tnx!

**Comment by AllenFang** [comment]
@anita166, sorry I dont have enough resource to do this in near future, but maybe you can tell me where you want to change the translation, I can tell you how to custom the text or component.

**Comment by anita166** [comment]
@AllenFang I just need to custom the text, so that tip would be great 😉

**Comment by AllenFang** [comment]
@anita166, you means the text on clear search button?

**Comment by anita166** [comment]
@AllenFang yes

**Comment by AllenFang** [comment]
@anita166, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/search/default-custom-search-clear-button.js) example and you can just custom it like following:

```js
return (
      <ClearSearchButton btnText='MyClear' />
    );
```
