### ISSUE TITLE
Adding logical operators to text filter

### ISSUE THREAD

**Issue by sparrownet** [AllenFang/react-bootstrap-table#708]
Hi,

Is there a built-in mechanism to apply logical operators on text filtering? 
e.g. 'AAB OR AAC' which will filter only words of the template AABXXX or AACXXX 
If not, any idea on how to implement it via custom filter?

Also, is there a selection filter with multiple selection capability?

Thanks!

**Comment by AllenFang** [comment]
HI @sparrownet, we dont support these built in filter and I suggest to customize a filter by yourself, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js) example.

If you got any trouble or question, just feel free to discuss with me, Thanks you :)
