### ISSUE TITLE
Redirecting to first page after changing table properties when you on last page

### ISSUE THREAD

**Issue by odzhurko** [AllenFang/react-bootstrap-table#712]
Hi,
1. I created some gridTable based on ReactBootstrapTable;
2. I have ReactBootstrapTable with pagination and row selection;
3. My gridTable remember some parameters in state, that parameters are bounded to ReactBootstrapTable as properties. (for example: selectRow.selected = this.state.selectedRow);  
Now, imagine some scenario:
1. My data rows count is 29, SizePerPage is set to 10. I'll have 3 pages;
2. I'll go to the last page and clicked to some row. 
3.  onRowSelect event is fired and i put some data to the state of my gridTable. (onRowSelect it means: selectRow.onSelect event);
4. After that i'm redirected to the first page of ReactBootstrapTable. Changing state in my gridTable causes rerendering ReactBootstrapTable and throwing new properties to ReactBootstrapTable.
After some researching i found that problem is in BootstrapTable.js row number = 576. After changing some properties in reactBootstrapTable the "componentWillReceiveProps" event is fired, and in that event implementation there is some condition:
`// #125`
`        if (!options.page && page >= Math.ceil(nextProps.data.length / sizePerPage)) {`
`          page = 1;`
`        }`
That condition causes redirecting to first page. Let us look to the second part of that condition, in my case there will be (3 >= Math.ceil(29 / 10)) === (3 >= 3) === (true). As we can see the condition is fulfilled and i am redirected to the first page. `!options.page` is fulfilled also.

I think that there must be `page > Math.ceil(...` instead of `page >= Math.ceil(...`.
What are your thoughts? Cause i see that it is the solution for #125 issue, but do we realy need `>=` condition to solve that issue?

**Comment by AllenFang** [comment]
@odzhurko, I'll check this out, but could you please show me an simple example for reproducing this issue?

**Comment by odzhurko** [comment]
@AllenFang , i'll send you a short film.  This will be  enough? [http://www.screencast.com/t/7lnQ7LWc](url)

**Comment by AllenFang** [comment]
@odzhurko, I cant reproduce this issue, anything I missing?

**Comment by odzhurko** [comment]
@AllenFang it's weird. I'll send You a test project, try that. After starting of that project You'll see a bootstrap table with 3 pages. Try to move to third page and select some record on third page, You'll be redirected to first page.   [ReactJs_ Start_Table_test.zip](https://github.com/AllenFang/react-bootstrap-table/files/479393/ReactJs_.Start_Table_test.zip)

**Comment by AllenFang** [comment]
@odzhurko, thanks, I'll check this out :)

**Comment by AllenFang** [comment]
@odzhurko, upgrade ```react-bootstrap-table``` to higher version will solve this issue. Thanks

**Comment by odzhurko** [comment]
@AllenFang, thank You for reply and for help. New version doesn't have that issue
