### ISSUE TITLE
How to reload a row

### ISSUE THREAD

**Issue by bcolucci** [AllenFang/react-bootstrap-table#714]
Hi. 
It's more a question than a bug, but it's quite blocking for me :)

This is the situation : I've a form, from which I can insert/update an entity. And I've the entities table beside the form.

I use the built-in-delete-handler to manage deletions but I don't want to use the cell-edit functionality.

The way it works now: When you click on an entity's row's edit button, I change the state of my form in order to edit the entity. It works but I looking for a way to update the table row now, because I've no access to the rows. 

We could imagine fetchRows method on the table, like this:

myDT.fetchRows((key, row) => ...)

Or directly :
myDT.getRow(key)

Plus, a method on a row like :
row.updateValue({ ... })

Or directly :

myDT.updateRow(key, {...})

In this way, I could find a row and update it's value after an update from my app. I don't work to find a row outside the current values in my table. In fact, it's also a row in the current page...

What do you think guys, do you know another way?

Thx

**Comment by AllenFang** [comment]
HI @bcolucci, the ```data``` props for ```<BootstrapTable>``` is from the store? I means did you use flux(e.g redux?)

**Comment by bcolucci** [comment]
No it's a very small project. For now, if I can avoid to use redux (because I'm quite new with react and I've not a lot of time on this project :s)

I've an ajax request that fill the state of a Guests component which contains a GuestForm and the GuestsTable. When the Guest component retrieve the guests, the state of the table is updated.
I just need to say to the table "Update this row with this value". I know it's possible to make something like updating the table with the current page and the current filter in order to avoid the table reloading visible.
For now I just reload window.location, which is not awesome.

**Comment by bcolucci** [comment]
Ok I'm stupid :)
It works if I just change my state yes... because I pass to the table the guests which is a part of my state.

```
// updating the modified guest
this.setState({
  guests: this.state.guests.map((guest) => guest._id === updatedGuest._id ? updatedGuest : guest)
})
```

**Comment by AllenFang** [comment]
@bcolucci great :0  Feel free to ask my anything :)

**Comment by uttara2611** [comment]
Hi,. I am using redux. I have implemented custom insert functionality but after clickling on save button, react bootstrap table is not getting updated. Can you please tell me how to do that?

**Comment by AllenFang** [comment]
@uttara2611, sorry for lately reply, please open another issue and put you example but remember to keep it simple and minimal, also show me your description more detail, it will be very helpful for me to help you. thanks
