### ISSUE TITLE
Table column displays `[object Object]` if field's value is a React element.

### ISSUE THREAD

**Issue by ryerh** [AllenFang/react-bootstrap-table#715]
I think this [line](https://github.com/AllenFang/react-bootstrap-table/blob/master/src/TableBody.js#L69) caused the problem.

I recommend that allowing data field to be a React element.

**Comment by AllenFang** [comment]
#675 
HI, In my opinion, maybe use the ```dataFormat``` is more better if you content is react component.

**Comment by AllenFang** [comment]
BTW, I know this issue cause by line in recent releases. If too many people has same issue, I'll consider to avoid it. Thanks :)
