### ISSUE TITLE
implementing sub columns into table

### ISSUE THREAD

**Issue by VEDA95** [AllenFang/react-bootstrap-table#718]
I was looking through some of the documentation for the table and I had a question when I was reading through it. Is it possible to create sub-columns for one of the header column? Some of my data has sub-columns in it and I would like to display the sub columns along with their respective parent columns.

**Comment by AllenFang** [comment]
HI @VEDA95, we dont support sub column currently, however, I think you have some nest columns in your data, so you want to apply them to the table, right.  There's same issue that somebody open, you can check https://github.com/AllenFang/react-bootstrap-table/pull/508  and https://github.com/AllenFang/react-bootstrap-table/issues/50.

In my opinion, I may support the nest data in future, but nest column is not, so PR is welcome 👍 

I'll close this issue, if you have any concern, feel free to discuss with me. Thanks :)
