### ISSUE TITLE
Large Tables get wrong width?

### ISSUE THREAD

**Issue by obiwarn** [AllenFang/react-bootstrap-table#720]
I set the width for every column, but this is ignored when my table is about to exceed the screen. So far max.-width: seems to be locked to 100%.

**Comment by helsont** [comment]
Large table: Whenever I click on a column to sort, the width gets extended more and more with each click.

**Comment by AllenFang** [comment]
large table means there's many columns or rows?

**Comment by helsont** [comment]
Columns

**Comment by obiwarn** [comment]
yes columns.

**Comment by obiwarn** [comment]
and when i sort my columns they also change width (however they do not get extended every  time).

**Comment by altayaydemir** [comment]
Here's an example:

**Full table**
<img width="1396" alt="screen shot 2016-09-25 at 11 20 18" src="https://cloud.githubusercontent.com/assets/9790196/18813878/192c912e-8312-11e6-9434-f09425561033.png">

**Right after I've made a search**
<img width="1399" alt="screen shot 2016-09-25 at 11 20 28" src="https://cloud.githubusercontent.com/assets/9790196/18813880/1d23d558-8312-11e6-9c8f-3170b842ac49.png">

**Comment by AllenFang** [comment]
hi all, I'll try to figure this and any repo or example for me to reproduce this? Thanks.

**Comment by AllenFang** [comment]
@altayaydemir, which browser and ```react-bootstrap-table``` you used?

**Comment by altayaydemir** [comment]
@AllenFang Chrome 53 on macOS sierra, with `react-bootstrap-table": "^2.5.3"`. I use react-bootstrap instead of JQuery and Bootstrap's core JS.

**Comment by AllenFang** [comment]
ok, anyone can give me a repo for reproducing this issue(I've tried a lots, but got nothing)? Also show me your browser. Thanks

**Comment by obiwarn** [comment]
I cannot publish my repo but this example only works when I add a min-width:1620px;  to my table css.

```
        <BootstrapTable {...this.props}
                        remote={ true }
                        pagination={ true }
                        striped={false}
                        hover={true}
                        search={ false }
                        exportCSV={ false }
                        ref='table'
        >
          <TableHeaderColumn dataField='_id' isKey={true} hidden={true}>Id</TableHeaderColumn>
          <TableHeaderColumn width='150' dataField='createdAt' dataSort={true}
                             dataFormat={ dateFormatter }>Date</TableHeaderColumn>
          <TableHeaderColumn width='250' dataField='userEmail' dataSort={true} filter={ textFilter } ref='userEmail'>Email</TableHeaderColumn>
          <TableHeaderColumn width='100' dataField='spotShortName' dataSort={true} filter={ textFilter }
                             ref='spotShortName'>Spot</TableHeaderColumn>
          <TableHeaderColumn width='100' dataField='keyCode' filter={ textFilter }
                             ref='keyCode'>Code</TableHeaderColumn>
          <TableHeaderColumn width='250' dataField='dropDate' dataSort={true}
                             dataFormat={ dateFormatter }>Drop</TableHeaderColumn>
          <TableHeaderColumn width='250' dataField='pickDate' dataSort={true}
                             dataFormat={ dateFormatter }>Pick</TableHeaderColumn>
          <TableHeaderColumn width='100' dataField='tagLabel' filter={ textFilter }
                             ref='tagLabel'>Tag</TableHeaderColumn>
          <TableHeaderColumn width='120' dataField='paymentInstrument' filter={ textFilter } ref='paymentInstrument'>Payment</TableHeaderColumn>
          <TableHeaderColumn width='100' dataField='transactionId' filter={ textFilter }
                             ref='transactionId'>Transaction</TableHeaderColumn>
          <TableHeaderColumn width='100' dataField='state' filter={ textFilter } ref='state'>State</TableHeaderColumn>
        </BootstrapTable>
```

![image](https://cloud.githubusercontent.com/assets/9539797/18879930/5f448246-84d6-11e6-8c79-1f6b9da018c5.png)


Without min-width it looks like this on load:

![image](https://cloud.githubusercontent.com/assets/9539797/18879817/f58c7ca0-84d5-11e6-9a76-8ad02438a6c2.png)

**Comment by AllenFang** [comment]
@obiwarn, thanks you 👍

**Comment by AllenFang** [comment]
@obiwarn, some question I would like to ask, 
1. could you show me the ```textFilter``` you customize?
2. the ```min-width``` you apply on which DOM?
3. did you have the same problem that you got unalign table when sorting?

Thanks

**Comment by obiwarn** [comment]
1.)
```
const searchFieldPlaceholder = 'Search...';
export const textFilter = {type: 'TextFilter', placeholder: searchFieldPlaceholder};
```
2.)

    <table>

3.) yes. header and table widths both change + they unalign. it seems like they are both running some  separate auto resize routine.
 
One problem seem to be empty fields. e.g. when I click sort by email twice it shows all records with no email , then the table gets cluttered.

maybe you could **add a boolean to stop any auto resizing** of the table?

**Comment by AllenFang** [comment]
@obiwarn, thanks, I will check this out, BTW, I'll think your solution, but before that, I would like to find the root cause for why the width changed every time.

**Comment by jvallarvisp** [comment]
I have the same issue with this one only to find out that the css is not loaded. I am using Meteor and React. for some reason Meteor does not load css from node_modules.

**Comment by AllenFang** [comment]
Sorry for lately fixed...
Try the `react-bootstrap-table@2.10.0-beta.1` I fix couples unalign column problems in this release. Let me know if the problem still there.
