### ISSUE TITLE
Size per page dropdown not working

### ISSUE THREAD

**Issue by Gothbag** [AllenFang/react-bootstrap-table#722]
Greetings,
I'm using version 2.5.3 and for some reason, the size per page dropdown doesn't respond; the list is there but it does nothing. One thing is that I've noticed is that on my version, the data-reactid attribute hasn't been generated but it seems that only has to do with React's version. The only thing I'm doing differently from the example is that I render the columns through a map funciton. What could be wrong?

Thank you very much

**Comment by AllenFang** [comment]
@Gothbag, sorry for lately reply...  check https://github.com/AllenFang/react-bootstrap-table/issues/710, if the problem still there, feel free to ask me anything :)
