### ISSUE TITLE
Cell edit issue

### ISSUE THREAD

**Issue by eclipse88** [AllenFang/react-bootstrap-table#724]
I'm listening to a socket for new data to update the table, data is coming at an interval of 5 sec and if i'm in edit mode the component is rendering and i lose the data if updating process is not completed.How to update the table, without losing the value from editing cell?

**Comment by AllenFang** [comment]
@eclipse88, sorry for lately reply.. busy on work. How do you update the ```react-bootstrap-table```?

**Comment by eclipse88** [comment]
hi, no problem.I use redux for update the store and pass the rows like a parameter to this component

**Comment by eclipse88** [comment]
there is a possibility for partial update, not to render all table, maybe a row or a cell from the table?

**Comment by AllenFang** [comment]
> there is a possibility for partial update, not to render all table, maybe a row or a cell from the table?

I think it's possible(80%), but in my opinion, it's very complicated to implement.

**Comment by AllenFang** [comment]
@eclipse88, I'll fix it in next version :)

**Comment by AllenFang** [comment]
Fixed on ```v2.5.4```. Check this out

**Comment by eclipse88** [comment]
thank you for your effort,now it's working great

**Comment by riguy724** [comment]
Hey so, what exactly was done here?  It seems like functionality was removed, not added?  I'm on v2.5.5 and am encountering the same issue that was supposedly resolved here.

In-flight edits are blown away by new state changes, even when they don't affect the tables data.

**Comment by AllenFang** [comment]
@riguy724, how about describe your scenario step by step? Thanks

**Comment by riguy724** [comment]
hey I lost this ticket.  I was on an outdated version of things, working now :)  Thanks!
