### ISSUE TITLE
Insert Issue

### ISSUE THREAD

**Issue by docmur** [AllenFang/react-bootstrap-table#726]
Hey

I copied the code from the Insert Example:

import React from 'react';
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';

const jobs = [];
const jobTypes = [ 'A', 'B', 'C', 'D' ];

function addJobs(quantity) {
    const startId = jobs.length;
    for (let i = 0; i < quantity; i++) {
        const id = startId + i;
        jobs.push({
            id: id,
            name: 'Item name ' + id,
            type: 'B',
            active: i % 2 === 0 ? 'Y' : 'N'
        });
    }
}

addJobs(5);

export default class DataInsertTypeTable extends React.Component {
    render() {
        return (
            <BootstrapTable data={ jobs } insertRow={ true }>
                <TableHeaderColumn dataField='id' isKey={ true }>Job ID</TableHeaderColumn>
                <TableHeaderColumn dataField='name' editable={ { type: 'textarea' } }>Job Name</TableHeaderColumn>
                <TableHeaderColumn dataField='type' editable={ { type: 'select', options: { values: jobTypes } } }>Job Type</TableHeaderColumn>
                <TableHeaderColumn dataField='active' editable={ { type: 'checkbox', options: { values: 'Y:N' } } }>Active</TableHeaderColumn>
            </BootstrapTable>
        );
    }
}

And when I try to run it, I can't use the insert button.  I'm running:

    "jquery": "^3.1.0",
    "react": "^0.14.6",
    "react-bootstrap-table": "^2.5.0",
    "bootstrap": "^3.3.7",

Any idea why it wouldn't work?

Thanks
Docmur

**Comment by AllenFang** [comment]
> And when I try to run it, I can't use the insert button

is mean the insert modal is not popup?

**Comment by gforge** [comment]
I had the same issue that the modal wasn't appearing but it turned out that I was only loading the CSS and not the js-file. Hope this helps.

**Comment by docmur** [comment]
Got it to work, was a JavaScript issue in the index.html file, so thanks :)
