### ISSUE TITLE
"Add" modal does not show

### ISSUE THREAD

**Issue by nanoaguayo** [AllenFang/react-bootstrap-table#727]
I'm using the table in my project and everything was working fine until the Add row feature. When I click the button nothing happens (the modal doesn't show) and no console log or warning are generated. 
Any idea why this happens?

Thanks

**Comment by hustshawn** [comment]
Same issue. Any suggestion? Even the button event cannot be captured by any of existing API!!!

**Comment by AllenFang** [comment]
sorry for lately reply, check this https://github.com/AllenFang/react-bootstrap-table/issues/593. If the problem still remain, feel free to ask me, thanks
