### ISSUE TITLE
Where is react-bootstrap-table V3.0.0?

### ISSUE THREAD

**Issue by hustshawn** [AllenFang/react-bootstrap-table#729]
Where is react-bootstrap-table V3.0.0?
The current version in npm is 2.5.3. Since the 'milestone' achieved, where can I get the new version? @AllenFang

**Comment by AllenFang** [comment]
@hustshawn, it's on development. not yet release.. But I've no any schedule for it, cause I'm also busy on work.  Hope it can be done in near future.  If you want to contribute, just checkout to the branch of ```v3.0.0-dev```
