### ISSUE TITLE
Question: Default sort order?

### ISSUE THREAD

**Issue by thevangelist** [AllenFang/react-bootstrap-table#730]
I was looking at the docs but unsure how to solve this...

I have data with prices in it. How can I order the data by default based on price?

Thanks!

**Comment by AllenFang** [comment]
> How can I order the data by default based on price?

any more description or example?

if the the built-in sorting is not suite for you, how about custom your sorting function for price?

**Comment by thevangelist** [comment]
I'd like to set the table so that every time it loads, it's sorted by default with the price column

**Comment by thevangelist** [comment]
Hey, I found out that using this helps: `this.refs.table.handleSort('desc', 'field');`

**Comment by AllenFang** [comment]
yap, ```handleSort``` is also exposed API by ```BootstrapTable```. Good finding :)
