### ISSUE TITLE
TextFilter on exact term

### ISSUE THREAD

**Issue by samuelmartineau** [AllenFang/react-bootstrap-table#732]
Hi @AllenFang 

Sorry in advance if the issue has already an answer but I didn't find it...

I am trying to fix an "issue" with a **TextFilter** filter.
I have 2 values: "_valid_" and "_invalid_" and I would like to filter with "exact" term.
But if I search for "val" I get all datas... because it matches!

So is there any way to do that? Something like check if indexOf sub-string is equal to 0 instead of >-1?

**Comment by samuelmartineau** [comment]
Never mind, I find the solution by using custom filter.

**Comment by AllenFang** [comment]
@samuelmartineau, great, feel free to open issue or ask me anything 👍
