### ISSUE TITLE
Create a new line, jump to end of paginated table

### ISSUE THREAD

**Issue by edulis8** [AllenFang/react-bootstrap-table#733]
Hello,
Any tips on how I could add this functionality:
Upon adding a new line, the interface would jump to the last page of the paginated table so the user could see their new line immediately...?

Thanks,
Eric

**Comment by AllenFang** [comment]
@edulis8, we have this kind of feature, for example, 
1. there's three page totally, and you stay on first page.
2. Insert a row
3. will jump to third page for showing the newest row

if I misunderstand your question, plz remind me and I'll open it again :)
Thanks

**Comment by edulis8** [comment]
Hi Allen,
This is default functionality?

Do you have an example of this working?

For me, I have a table with 16 pages. I enter a new row, and I stay on page 1.

Thanks,
Eric

**Comment by AllenFang** [comment]
How about showing your code? Maybe there's some bug I think. Thanks :)
```js
/* eslint max-len: 0 */
import React from 'react';
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';

const products = [];

function addProducts(quantity) {
  const startId = products.length;
  for (let i = 0; i < quantity; i++) {
    const id = startId + i;
    products.push({
      id: id,
      name: 'Item name ' + id,
      price: 2100 + i
    });
  }
}

addProducts(70);

export default class DefaultPaginationTable extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div>
        <BootstrapTable
          data={ products }
          pagination
          insertRow>
          <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
        </BootstrapTable>
      </div>
    );
  }
}
```

**Comment by edulis8** [comment]
The issue is that I have made my own custom “Insert Row” modal because I wanted a small modal and the user only can enter two fields…I didn’t want to see the 10 other disabled fields.

The new row is inserted but it doesn’t “jump” to the end…mind explaining how that works behind the scenes, maybe I can recreate it.

Thanks!

**Comment by AllenFang** [comment]
@edulis8, oh.. I got you. if you use your own insert modal, you can jump to the end page by

1. calling ```handlePaginationData``` which is a API exposed by  ```BootstrapTable```.
2. call setState of ```BootstrapTable```, there's a state ```currPage```.

For the first solution, You have to pass two arguments, ```page``` and ```sizePerPage```.

Feel free to discuss with me if you got any trouble. thanks you :)

**Comment by edulis8** [comment]
Hi Allen,
Do you have any further examples or documentation on handlePaginationData API? Not sure how to use it. Thanks!

Eric

**Comment by AllenFang** [comment]
sorry for lately reply, check following example:
```js
/* eslint max-len: 0 */
import React from 'react';
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';


const products = [];

function addProducts(quantity) {
  const startId = products.length;
  for (let i = 0; i < quantity; i++) {
    const id = startId + i;
    products.push({
      id: id,
      name: 'Item name ' + id,
      price: 2100 + i
    });
  }
}

addProducts(70);

export default class DefaultPaginationTable extends React.Component {
  constructor(props) {
    super(props);
  }

  jump2Page3 = () => {
    this.refs.table.handlePaginationData(3, this.refs.table.state.sizePerPage);
  }

  render() {
    return (
      <div>
        <button onClick={ this.jump2Page3 }>Jump to Page 3</button>
        <BootstrapTable
          ref='table'
          data={ products }
          pagination>
          <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
        </BootstrapTable>
      </div>
    );
  }
}

```

**Comment by edulis8** [comment]
Hi Allen,
Thanks. Is there a way to access lastPage as well? I need something like jump2Page3 but that jumps to whatever the last page might be.

I could do sizePerPage / myData.length but the user can change sizePerPage. Not sure how to access the current page size, to be honest.

Thanks for your help I really appreciate it :)

Eric

**Comment by AllenFang** [comment]
> I could do sizePerPage / myData.length

it's the answer



> but the user can change sizePerPage

you can get the ```sizePerPage``` by ```this.refs.table.state.sizePerPage```

Give it a try ~

**Comment by edulis8** [comment]
Thanks Allen,
To be honest I didn’t even know how to use refs until you told me this.

You are awesome.

Eric
