### ISSUE TITLE
JSX rendering dynamic TableHeaderColumn

### ISSUE THREAD

**Issue by tester5** [AllenFang/react-bootstrap-table#734]
I am trying to dynamically generate the TableHeaderColumn within the BootstrapTable component, although cannot do it and receive an error.

The following works:

    <BootstrapTable
                data={products2} striped={true} hover={true} condensed={true} columnFilter={true} pagination={true} search={true}>
                <TableHeaderColumn dataField="id" isKey={true} dataAlign="left" width="70px" dataSort={true}>#</TableHeaderColumn>
                <TableHeaderColumn dataField="carfilename" dataSort={true} width="300px">Car filename</TableHeaderColumn>
                <TableHeaderColumn dataField="local" dataSort={true} width="300px">local</TableHeaderColumn>
                <TableHeaderColumn dataField="localDev" dataSort={true} width="300px">localDEV</TableHeaderColumn>
                <TableHeaderColumn dataField="DEV" dataSort={true} width="300px">DEV</TableHeaderColumn>
                <TableHeaderColumn dataField="TRN" dataSort={true} width="300px">TRN</TableHeaderColumn>
    </BootstrapTable>

However I need to generate the environment columns dynamically, but the following does not work:

    <BootstrapTable data={products2} striped={true} hover={true} condensed={true} columnFilter={true} pagination={true} search={true}>
          <TableHeaderColumn dataField="id" isKey={true} dataAlign="left" width="70px" dataSort={true}>#</TableHeaderColumn><TableHeaderColumn dataField="carfilename" dataSort={true} width="300px">Car filename</TableHeaderColumn>
          {envColumns}            
    </BootstrapTable>

Related code:
      `envColumns.push(<EnvironmentHeaderColumn envname={envvalue.envName} key={envkey} />);`

    var EnvironmentHeaderColumn = React.createClass({
        render: function () {
            var env = this.props.envname;
            // console.log('env is ' + env);

            return (
                <TableHeaderColumn dataField={env} dataAlign="center">{env}</TableHeaderColumn>
            );
        }
    });

I receive the following error in Google Chrome:

> Uncaught TypeError: Cannot read property 'children' of undefined

**Comment by AllenFang** [comment]
@tester5, sorry for lately reply, 

Cause you leave one column in the BootstrapTable child, like your snippet, 
```js
<BootstrapTable data={products2} striped={true} hover={true} condensed={true} columnFilter={true} pagination={true} search={true}>
      <TableHeaderColumn dataField="id" isKey={true} dataAlign="left" width="70px" dataSort={true}>#</TableHeaderColumn><TableHeaderColumn dataField="carfilename" dataSort={true} width="300px">Car filename</TableHeaderColumn>
      {envColumns}            
</BootstrapTable>
```

you can fix it by following:
```js
<BootstrapTable data={products2} striped={true} hover={true} condensed={true} columnFilter={true} pagination={true} search={true} keyField='id'>
      {envColumns}            
</BootstrapTable>
```

Thanks :)

**Comment by tester5** [comment]
Hi Allen,  thanks very much for your reply.  That did indeed fix the issue :)

**Comment by tester5** [comment]
I have a complicated json file that I have processed to render into a table.  However I wish to use this to populate the rows, athough the json file isn't in the format required, i.e. an array of objects with column names.  Do you have a suggested approach for dealing with this?

**Comment by AllenFang** [comment]
hi @tester5, we dont support this feature, like json imported or an array of objects for columns. so I think you can keep your solution currently. hope I've answer your question  ;P

Feel free to discuss with me

**Comment by tester5** [comment]
Hi Allen,  thanks for your reply.  We like your solution because it has column filtering, global search and sorting.  If we produce a json file that complies with your table, how can we apply conditional styling based on the value of a cell?  For example, cells with "Faulty" would be red or have a red label, and others would be normal.

**Comment by tester5** [comment]
Also, wondering how we can get the column headers and column filters to all align nicely by default?

![image](https://cloud.githubusercontent.com/assets/2029583/18978583/b337013e-8707-11e6-841f-b0bd8bbade55.png)

**Comment by tester5** [comment]
thanks very much for your help Allen.  I managed to resolve some issues with column alignment (i.e. by fixing the # width) as well as use the advanced column filter.  I also used the column formatter and applied some conditional styling to it.  All good so far :)
