### ISSUE TITLE
Is there any way to change edit inline to popover edit ?

### ISSUE THREAD

**Issue by haunguyen90** [AllenFang/react-bootstrap-table#736]
Is there any way to change edit inline to popover edit ? @AllenFang

**Comment by AllenFang** [comment]
@haunguyen90, we support the custom editor but the custom component will be injected into the cell instead popup. Maybe I can make it available via some configuration or props(I need to give some try). Thanks

BTW, hope it can be done in next version or near future.

**Comment by AllenFang** [comment]
HI @haunguyen90, check [https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/cell-edit/custom-cell-edit-table.js#L178] example, I custom the name field as a pop editor. Feel free to discuss with me

**Comment by haunguyen90** [comment]
@AllenFang Thank you very much. I'll take a look at this
