### ISSUE TITLE
TableHeaderColumn does not accept function as className attribute

### ISSUE THREAD

**Issue by mirkobeine** [AllenFang/react-bootstrap-table#737]
According to the [docs](http://allenfang.github.io/react-bootstrap-table/docs.html), the TableHeaderColumn should accept passing a function to the className attribute.
However, the current implementation restricts the PropType to String:
`
TableHeaderColumn.propTypes = {
...
  className: PropTypes.string,
...
`

**Comment by AllenFang** [comment]
I'll support it in next version

**Comment by mirkobeine** [comment]
I'll try to do a PR if my schedule will allow it.

**Comment by AllenFang** [comment]
@mirkobeine, Fixed on ```v2.5.5```.
