### ISSUE TITLE
Two separate tables???

### ISSUE THREAD

**Issue by innopal** [AllenFang/react-bootstrap-table#738]
Hi Allen,

Congrats on great work on this component!
I am just wondering why you decided on two separate tables for header and body?
It sounds crazy to me to go that route! You have to spend so much effort to keep them aligned.
I would have just had a single element with config and data parameters, like:

`<BootstrapTable {...tableConfig} {...data} {...columns} />
`
This would generate a single table like:
```
<table class='table'>
  <thead>
  </thead>
  <tbody>
  </tbody>
</table>

```
Cheers

**Comment by AllenFang** [comment]
> It sounds crazy to me to go that route! You have to spend so much effort to keep them aligned.

yap...there'r some guys have the same question, I know it is very crazy, but I stuck on how to support the horizontal and vertical scroll in **single bootstrap table**.

so if you have any idea, feel free to tell me, even if it's just a simple example :) 

Thanks 👍

**Comment by tacomanator** [comment]
@AllenFang I may have misunderstood your point but in any case, where does something like this fall short: https://jsfiddle.net/0ho7dxy1/1/

**Comment by AllenFang** [comment]
@tacomanator,[this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/basic/large-column-table.js) is an example code.

BTW, There is one restriction when you want to make a large column table scrollable, You need set the width on some column to make the total width of table exceed the width of outer.

This restriction is begin from ```v2.0.0``` to now. Like I mentioned above, It's hard to make vertical and horizontal scroll easily with one single table.  so if any idea or simple example which can do it, welcome to tell me, I'll very appreciated 👍

**Comment by innopal** [comment]
I appreciate your attention to this fundamental issue @AllenFang and @tacomanator!
I would say though that you really should not be worried about large number of columns.
That to me is a design issue. A table/grid is for a limited number of columns that can be displayed in a sane fashion in a viewport. 
If there are more detailed data that is directly related to the entity that is represented in a row, you could either provide a link or maybe even implement an expandable row that can be a custom component and people can put whatever they want in that custom component.
There seems to be a discussion already about expandable row here: [https://github.com/AllenFang/react-bootstrap-table/issues/362]

If you are trying to build a spreadsheet component then that's a different story. In which case I would suggest a cell-based approach instead something similar to [https://handsontable.com/](Handsontable)

Cheers

**Comment by AllenFang** [comment]
@innopal, in ```v2.6.0```, we support expand row, check [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/expandRow.js). We will update document in these day
