### ISSUE TITLE
Is there a way to change state afterTableComplete?

### ISSUE THREAD

**Issue by jbkaplan** [AllenFang/react-bootstrap-table#739]
Not sure if I am doing this correct or if there's is a better way to solve this, but is there a way to change state based on the ```afterTableComplete``` results of the table?

I have a ```trClassFormat``` to set the first row to a class, then want to pull out info, and change state based on what is returned. I have tried through the ```onSortChange```, but that returns the previous sorted value, whereas using the ```afterTableComplete```option returns the correct info. When I try to use ```.bind(this)``` on my ```onAfterTableComplete``` function it runs into an infinite loop.

Thanks!

**Comment by jbkaplan** [comment]
Never mind, I solved this by using ```componentDidUpdate``` and then putting a break condition to avoid a infinite loop.

**Comment by AllenFang** [comment]
@jbkaplan, great, feel free to ask me anything. 👍
