### ISSUE TITLE
Columns reordering feature

### ISSUE THREAD

**Issue by edigley** [AllenFang/react-bootstrap-table#742]
Is there a way to do a column reordering by dragging on the react-bootstrap-table? Or a way to extend the componente to do so?

**Comment by AllenFang** [comment]
@edigley, sorry for that we dont support this feature and I think it's impossible to extend the component to do this. however, I think it's hard to implement due to our complicated DOM structure. If you got any interesting on that, PR is welcome. Thanks

Feel free to discuss with me.
