### ISSUE TITLE
Warnings for manually calling a React.PropTypes validation functions

### ISSUE THREAD

**Issue by g3blv** [AllenFang/react-bootstrap-table#750]
Hi,

First I have to say that react-bootstrap-table is fantastic. It is a pleasure to work with. I'm getting a few warning messages when I add `New`, `Delete` and `Search`.

I'm running 

`react-bootstrap-table@2.5.5 `

and 

```
├── react@0.14.8 
└─┬ react-bootstrap-table@2.5.5
  └─┬ react-toastr@2.8.1
    └── react@15.3.2 
```

I get the following warning message: 

`Warning: You are manually calling a React.PropTypes validation function for the **`toastType` prop on `ToastContainer`**. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.`

I get the same warning message for the props below. 

```
**`id` prop on `ToastContainer`
`toastMessageFactory` prop on `ToastContainer`
`preventDuplicates` prop on `ToastContainer`
`newestOnTop` prop on `ToastContainer`
`onClick` prop on `ToastContainer`**
```

Not sure if it is a version issue or something else.

**Comment by g3blv** [comment]
I think this is the same issue as [(https://github.com/tomchentw/react-toastr/issues/75)] which it looks like it hasn't been fixed yet.

**Comment by AllenFang** [comment]
@g3blv, good finding, hope there's someone can fix it in ```react-toastr```. I'll close this issue. BTW, maybe you can open a PR to ```react-toastr``. Thanks you :)

**Comment by g3blv** [comment]
@AllenFang I've checked with the author of `react-toastr` [issue #75](https://github.com/tomchentw/react-toastr/issues/75#issuecomment-251950021). He no longer sees the issue while I do. Could the issue be somewhere else in `react-boostrap-table`?

**Comment by AllenFang** [comment]
@g3blv, I've no idea about this issue, because the warning message is all about the ```react-toastr```.  But i'll spend some time to check this out.

**Comment by stavlevy** [comment]
+1
