### ISSUE TITLE
Question: Is it possible to add custom components in the TableHeader next to the search bar?

### ISSUE THREAD

**Issue by jonicious** [AllenFang/react-bootstrap-table#752]
Hi,

I would like to add custom action buttons next to the search bar. Is that possible? If so, how am I able to achieve that? I am thinking of a prop like `customHeaderComponent` for `BootstrapTable` that takes some JSX. I was not able to find something like this in the documentation.

If that does not exist, would you be be interested in this functionality?

**Comment by jonicious** [comment]
Something very similar to this: https://github.com/neelvadgama-hailo/react-bootstrap-table/commit/c58cd84dfd441d63e37c3cd4560255fd33a8130f

**Comment by jonicious** [comment]
Was this removed?

**Comment by jonicious** [comment]
As I have seen #497, this sounds more like a feature for 3.0 to provide more flexibility?

**Comment by AllenFang** [comment]
@jonicious, exactly, please wait the ```v3.0.0```. Thanks :)

**Comment by jonicious** [comment]
Is this already part of `v.3.3.0`?

**Comment by AllenFang** [comment]
```v3.0.0``` still on development. and I'll make all the components more customizable. BTW, you hope is add an button beside the search field, this functionality has been done, but there're many feature not yet complete....

**Comment by jonicious** [comment]
I need this feature in production. Would you recommend forking the repo and getting it in there or would you use `v.3.0.0`?

**Comment by AllenFang** [comment]
I dont recommend  that you use the branch of ```v3.0.0-dev```, it's still unstable. BTW, there's workaround you can take it, but did you enable the ```insertRow```, ```deleteRow```, ```exportCSV``` ?

**Comment by AllenFang** [comment]
if you only use search, and you can only see there's only a search bar on the top of table, you can drop the built-in and custom the search bar by yourself.

BTW, you can call ```handleSearch``` which exposed by ```BootstrapTable``` to achieve the search functionality

**Comment by jonicious** [comment]
I had the idea to use one of `insertRow`, `deleteRow` or `exportCSV` and overwrite the text via prop and styling with CSS?

**Comment by AllenFang** [comment]
ok, you can custom the button text by a simple way, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/custom-btn-text-table.js

**Comment by AllenFang** [comment]
BTW, if you  use one of these and I think the last solution is get the DOM of search bar and append you  custom button on it dynamically...  I know this is a worst case for now.

**Comment by jonicious** [comment]
Okay. Customising the text and sing on the of the props to add a button sounds like the best solution for now. But how can I handle the click on a button?

**Comment by AllenFang** [comment]
@jonicious, an example for you :)

```js
export default class BasicTable extends React.Component {

  handleBtnClick = () => {
    console.log(this);  // this will be this react component
  }

  componentDidMount() {
    const searchbar = document.getElementsByClassName('react-bs-table-search-form')[0];
    searchbar.className += ' input-group input-group-sm';
    const btnGroup = searchbar.childNodes[1];

    const button = document.createElement('BUTTON');
    button.setAttribute('type', 'button');
    button.className = 'btn btn-default';
    button.textContent = 'Custom Btn';
    button.onclick = this.handleBtnClick.bind(this);
    btnGroup.appendChild(button);
  }

  render() {
    return (
      <BootstrapTable data={ products } search={ true }>
          <TableHeaderColumn dataField='id' isKey={ true } searchable={ false }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Fruit Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
}
```

**Comment by jonicious** [comment]
Basically how I thought I would do it :) Thanks for your great help!

**Comment by jonicious** [comment]
Closed the issue as I think, you answered all my questions very well. Thank you very much! :)

**Comment by AllenFang** [comment]
I'll remind you here after ```v3.0.0``` released, feel free to discuss with me :)
