### ISSUE TITLE
Is It Possible To Responsively Show/Hide Columns Based on Viewport Size?

### ISSUE THREAD

**Issue by jflayhart** [AllenFang/react-bootstrap-table#753]
In bootstrap we have the ability to show/hide elements using the classe(s) `.hidden-sm` as documented here http://getbootstrap.com/css/#responsive-utilities-classes

Does this library leverage this feature built-in to bootstrap or can it be done in some way eventually? I REALLY need this to work in the case where I have a users table, which shows avatars and other ancillary information that I would love to hide when viewing on small devices or window sizes.

For example, in a large viewport we show all columns, avatars, images, etc, but on small viewports we hide those extra columns to make room for the important columns like name and email.

**Comment by jflayhart** [comment]
I have already tried adding these classes to the TableColumnHeaders, but it seems that only hides the table headers, not the column!

**Comment by innopal** [comment]
className: 'hidden-xs'
columnClassName: 'hidden-xs'

**Comment by innopal** [comment]
you need both!

**Comment by jflayhart** [comment]
Thank you so much, I was actually hoping that it was that easy. Keep doing your thing, @AllenFang.

**Comment by AllenFang** [comment]
@innopal, good job.
