### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by edulis8** [AllenFang/react-bootstrap-table#754]
Hello,
Any tips on creating a link within the table?

My data set could contain html like an anchor tag if there was a way to resolve that into a DOM element instead of a string.

Or is there another way? Attaching an onClick to a cell?

Thanks.

**Comment by AllenFang** [comment]
use ```dataFormat```, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-format/react-column-format-table.js or https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-format/html-column-format-table.js.

Thanks 👍

**Comment by edulis8** [comment]
Hi Allen,
That is awesome, thanks! However I have one more question here. What if I am already passing enumFormatter to dataFormat in order to enable filtering on that column? 

(I’d like a filterable column, made up of links)

Thanks!
Eric

**Comment by AllenFang** [comment]
> What if I am already passing enumFormatter to dataFormat in order to enable filtering on that column?

I think it's impossible, if you want to use column filter, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/text-filter.js) example.(it's a filter on the column of table header)



> (I’d like a filterable column, made up of links)

How about use a custom filter?
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js

Hope I've answered your question :)

Feel free to discuss wit me.

**Comment by dongcai** [comment]
Hi Allen,
I understand that we can use formatter to add a link. But I tried to add onClick event, and it seems to be ignored. Do you know why? Please take a look at the code below, and I don't see alert popup.

> goToProduct() {
>     alert('hi');
>     console.log('hi');
> }
> linkFormatter(cell, row) {
>     const sku = row.id;
>     return (
>       <span id={sku} onClick={this.goToProduct}>{cell}</span>
>     );
>   }

Thanks,
Dong

**Comment by AllenFang** [comment]
@dongcai, I've no idea about this, could you please show the whole example? I think it's a wired issue. Thanks
