### ISSUE TITLE
Problem Sorting on dataFormat columns

### ISSUE THREAD

**Issue by Draccan** [AllenFang/react-bootstrap-table#756]
Hi all,

I have a problem sorting my BootstrapTable using defaultSortName and defaultSortOrder.

I want to sort by a column and this column has a specific dataFormat. This is the format function:
`_dateFormat(cell, row){
		return cell ? moment(cell, "DD/MM/YYYY hh:mm:ss").format("DD/MM/YYYY") : "";
}`

As you can see the input has a date field in the date format: "DD/MM/YYYY hh:mm:ss". I want to format in "DD/MM/YYYY" and it's happening.
Using the "options" it orders for all the fields, but not for my field "DATE".
```
var options = {
			defaultSortName: "DATE", 
			defaultSortOrder: "desc"
		};
```

Now I want to apply a descending order to this column when componentDidMount:
`componentDidMount(){
		this.refs.table.handleSort("desc", "DATE");
		order = 'desc';
}`

Even in this case the table sorts all the columns well, but not my column "DATE".

Is there a way to change this behaviour? Can you help me?

**Comment by AllenFang** [comment]
Sorry for lately reply,
> Using the "options" it orders for all the fields, but not for my field "DATE".

what's that means?

**Comment by Draccan** [comment]
Hi @AllenFang,

I'm sorry for my bad explanation. I will try with an example.

I have an array of data like this one:
`myData = [{Id: 1, Name: "Paul", Surname: "Bristol", Date: "01/'08/1992 09:22:33"}, {Id: 2, Name: "Allen", Surname: "Fang", Date: "05/'07/1995 10:02:45"}]`

I have my BootstrapTable configured like this:
`<BootstrapTable 
                               data = {myData} 
				striped = {true}
				condensed={true} 
				pagination = {true}
				search = {true}
				options = {options}
				ref="table">
                                 <TableHeaderColumn dataField = {"Id"}  
									dataSort = {true} 
									key = {"Id"} 
									isKey = {true}> 
									"Id" 
				</TableHeaderColumn>
				<TableHeaderColumn dataField = {"Date"}  
									dataSort = {true} 
									key = {"Date"} 
									isKey = {false}
									dataFormat = {this._dateFormat.bind(this)> 
									"Date" 
				</TableHeaderColumn>
                               <TableHeaderColumn dataField = {"Name"}  
									dataSort = {true} 
									key = {"Name"} 
									isKey = {false}> 
									"Name" 
				</TableHeaderColumn>
                                <TableHeaderColumn dataField = {"Surname"}  
									dataSort = {true} 
									key = {"Surname"} 
									isKey = {false}> 
									"Surname" 
				</TableHeaderColumn>
</BootstrapTable>`

I want that table is sort by "Date" by default. So in options I have an object like this:
`var options = {
			defaultSortName: "Date", 
			defaultSortOrder: "desc"
		};`

As you can see, one of the TableHeaderColumn has as dataField, the field "Date" and has a dataFormat like this:
`_dateFormat(cell, row){
		return cell ? moment(cell, "DD/MM/YYYY hh:mm:ss").format("DD/MM/YYYY") : "";
	}`

So the dataFormat for the TableHeaderColumn which represents the field "Date" is the "_dateFormat". "_dateFormat" uses "moment" to format the date.

So, if in my "options"  I say that "defaultSortName" is "Name", or "Id", or "Surname", table sorts correctly. If in my options I say that "defaultSortName" is "Date", it doesn't sort correctly (only when I use dataFormat).

I hope to have been more clear this time :) Thank you for your reply.

**Comment by Draccan** [comment]
Hi @AllenFang ,

The problem appears with an array of 1000 objects using pagination.
So I can find in the first page all rows with this sort:
dd/mm/2016
dd/mm/2016
dd/mm/2016
dd/mm/2016
dd/mm/2015
dd/mm/2015
etc..

And next in the second page I see these rows:
dd/mm/2016
dd/mm/2016
dd/mm/2015
dd/mm/2015
dd/mm/2014
dd/mm/2014
dd/mm/2014
etc.

I don't understand why some "2016" rows are in the second page and not in the first one.

Please help me..!

**Comment by AllenFang** [comment]
@Draccan, thanks the very detail explanation. I guess the problem is sorting does not apply with dataFormat..  BTW, is ```01/'08/1992 09:22:33``` that your date data? there's a single quotation before month. (Because I would like to reproduce this issue on my local, so I need to know what's the look for your actual date value ).

**Comment by Draccan** [comment]
Hi @AllenFang,

This is the date how it comes from the server: "15/05/2016 12:47:36.000".
The single quote was a mistype.

Thank you :)

**Comment by AllenFang** [comment]
@Draccan, maybe I know the problem.., because I use the [localeCompare](https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) to compare the string, you should check this out.

Take the following example, you will know the root cause

```
"01/08/2015".localeCompare("03/09/2016")
ans: -1
"09/08/2015".localeCompare("03/09/2016")
ans: 1
```

In you case, I suggest you custom a sort function by yourself, ```react-bootstrap-table``` support this feature, check [this](https://github.com/AllenFang/react-bootstrap-table/issues/756) example.

Feel free to discuss with me if you got any trouble. Thank you

**Comment by dileepmiahra** [comment]
but it is not working for Date

**Comment by libasoles** [comment]
This one works for spanish like date (dd/mm/YYYY): 

https://github.com/AllenFang/react-bootstrap-table/issues/1142

**Comment by libasoles** [comment]
Me again.
This one is also working for me. Using _moment_ js library.

```
export function sortDates (a, b, order) {
 
    if(order === 'desc') 
        return moment(a.date, "DD/MM/YYYY") - moment(b.date, "DD/MM/YYYY");  
    return moment(b.date, "DD/MM/YYYY") - moment(a.date, "DD/MM/YYYY");  
}
```

NOTE: I edited my comment. First I was complaining about functions not working. Then I found a bug in my code. So far, date sorting seems to be working for me now.

**Comment by dileepmiahra** [comment]
I think there is no way to do the sorting by using bootstrap table.i just
handle my requirement by using custom function(API calls).

**Comment by AdnanBoota** [comment]
Any idea about sorting the field? or any approach to dataSort and also dataFormat with formatExtraData?

![image](https://user-images.githubusercontent.com/14972616/54446358-08f47780-4747-11e9-848d-136b690dd82b.png)
