### ISSUE TITLE
css overflow: hidden property causes customfilter to display behind the table

### ISSUE THREAD

**Issue by riguy724** [AllenFang/react-bootstrap-table#758]
Hello!  I have implemented my own filtering class for a multiselect with custom filtering logic,  it uses the react-select library to display a multiselect option dropdown.  The only problem is, the overflow: hidden property of the react bootstrap table headercolumn is causing the selection list to be hidden from view.

Any idea how I might get around this, or how things might be modified to allow for proper behavior here.

![screenshot from 2016-10-04 16 26 25](https://cloud.githubusercontent.com/assets/379612/19091142/582aa0c0-8a4f-11e6-97bf-7bc3f917adbb.png)

In the screenshot you can see that the list is appearing behind the table (thin blueish bar under the select box)

**Comment by AllenFang** [comment]
Hello @riguy724, how about overwrite the hidden property?

**Comment by riguy724** [comment]
Hey @AllenFang , we ended up just using a normal select element, which seemed to work out just fine.  If we end up having to go back to this though, I will try it.
