### ISSUE TITLE
Custom Pagination Function

### ISSUE THREAD

**Issue by sureshvarman** [AllenFang/react-bootstrap-table#76]
Is it possible to write a custom function for pagination 
i want to achieve a lazy loading in table using pagination for that i need to call my own function when a user clicks on a particular page

**Comment by AllenFang** [comment]
HI @sureshvarman , sorry for slow response. I'll  think about that in near future. but need some time :)

**Comment by AllenFang** [comment]
Support on ```remote``` data, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-paging.js)
