### ISSUE TITLE
trClassName as a function seems to mess up column widths

### ISSUE THREAD

**Issue by jflayhart** [AllenFang/react-bootstrap-table#760]
I am using `trClassName` as a function to programmatically insert class names based on certain conditions. Since doing this, however, I have found that the TH widths are all messed up.

For example, I am using a selectable table and where the inline CSS elements used to be
```
<th style="text-align: center; width: 30px; min-width: 30px;">
  <input type="checkbox" class="react-bs-select-all" value="on">
</th>
```

IS NOW

```
<th style="text-align: center">
  <input type="checkbox" class="react-bs-select-all" value="on">
</th>
```

for ALL TH elements. This makes the table look like this:

![screen shot 2016-10-05 at 1 19 43 pm](https://cloud.githubusercontent.com/assets/6808172/19125909/6de5b792-8afe-11e6-9998-238f1fceea90.png)

Of course removing the trClassName prop fixes this width issue.

**Comment by jflayhart** [comment]
My function is simply:

```
setTrClassName = (rowData) => {
    const { clickable, unselectable } = this.props
    let className = null
    const unselectableRows = unselectable || []
    // we want to either add a class to clickable rows or ones that aren't selectable
    // to accommodate two different table types
    if (clickable) {
      className = 'clickable'
    } else if (contains(rowData.id, unselectableRows)) {
      className = 'row-hidden'
    }

    return className
  }
```

where row-hidden is, well, hidden.

**Comment by jflayhart** [comment]
After looking into this, it seems if I use CSS to hide a row using `display: none` (applied to the row-hidden class), this happens. I found a work around where I just change the background color of the disabled row instead of hiding it, and this seems to work for now...

Any way we can programmatically hide a row instead?

**Comment by AllenFang** [comment]
@jflayhart, sorry for lately reply. 

> Any way we can programmatically hide a row instead?

Maybe I can support this feature in future, but I'm focus on ```v3.0.0``` development, so PR is welcome. :)
