### ISSUE TITLE
example page dropdown menu weird broken by clicked

### ISSUE THREAD

**Issue by madeinfree** [AllenFang/react-bootstrap-table#761]
Today I merge the latest v3.0.0-dev branch and `npm start` but I can't click the dropdown menu from example page, it work fine in v2.x
![2016-10-06 10 21 59](https://cloud.githubusercontent.com/assets/4027049/19138431/b7324798-8bae-11e6-8176-698678e9889c.png)

**Comment by AllenFang** [comment]
Fixed it. Thanks 👍
