### ISSUE TITLE
Whether to package the detailView

### ISSUE THREAD

**Issue by xyy94813** [AllenFang/react-bootstrap-table#764]
Whether to package the detailView？
how to write a detailView and its detailFormatter

**Comment by AllenFang** [comment]
Hi @xyy94813, How about explain what is detailView for you?

**Comment by xyy94813** [comment]
i am thinking about the relationship between react-bootstrap-table and bootstrap-table.
uh huh ......
the detailView i said is bootstrap-table's detailView
it is a panel  can show some hidden data.
and it can be customized by a callback function.

**Comment by AllenFang** [comment]
@xyy94813, sorry we dont support this feature, but I think it can custom by yourself, but it depend.

Feel free to discuss with me for further detail. Thanks
