### ISSUE TITLE
Lots of columns -then table alignment goes wrong

### ISSUE THREAD

**Issue by venkat-vs-id** [AllenFang/react-bootstrap-table#765]
Looks like the header row is a separate table and the data is a separate table? because of this the header row and the data row goes out of allignment when there are lots of columns
![bootstraptable](https://cloud.githubusercontent.com/assets/3398404/19225706/47457cb4-8ee4-11e6-830b-70f9314647ae.png)

**Comment by venkat-vs-id** [comment]
I worked out a solution for this. call the below function after rending the table. The below function adjusts the header column width and data-table column width programmatically. 

Everytime you render the ReactBootstrapTable, call this function and this works like a treat.

You also need to set the below CSS. remeber this logic works only with STRIPED data-tables. 

---------------------------------------------------------------------------------
div.react-bs-table-container{
    overflow: auto;
}

.table>thead>tr>th {
    background-color: #616161;
    color: white;
}
.table-hover>tbody>tr:hover{
    background-color:#E3EEF5;
}
.table{
   margin-bottom:0px;
}
.table-striped{
   width: auto;
}
.h1class{
    text-align:center
}

td, th {
    padding: 0;
    white-space: nowrap;
}
---------------------------------------------------------------------------------

function myReactBootstrapTable_adj(){

    //---fix the data table based on the header if the header size is greater than the column width(datatable)
    var tables = document.getElementsByClassName("table");
    console.log( "total no of tables", tables.length )
    console.log( tables )

    var l_header_table = null;
    var l_row_table = null;
    var l_wd = null;
    for ( var i = 0; i < tables.length; i++){
        console.log( "---total no of tables", tables.length )
        console.log( "tables ----------------------------------", i)
        if (i%2 == 0){ //header
            console.log("header", i)
            l_header_table = tables[i]
        }else{ // row table
            console.log("row", i)
            l_row_table = tables[i]
            var first_row = l_row_table.getElementsByTagName("TR")[0];
            var tds = first_row.getElementsByTagName('TD');
            var larr_col_size = []
            for ( var j = 0; j < tds.length; j++){ // width of each cell
                console.log( tds[j].innerText, tds[j].style.width, tds[j].style.offsetWidth, tds[j].getBoundingClientRect().width)
                larr_col_size.push(tds[j].getBoundingClientRect().width)
            }

            console.log(l_row_table )
            console.log(larr_col_size)
            console.log(l_header_table)

            var first_row = l_header_table.getElementsByTagName("TR")[0];
            var h_tds = first_row.getElementsByTagName('TH');
            for ( var k = 0; k < h_tds.length; k++){ // each cell
                console.log( h_tds[k].innerText, larr_col_size[k])
                l_wd = h_tds[k].getBoundingClientRect().width
                console.log( l_wd, ' ...>... ', larr_col_size[k] )
                if (  l_wd > larr_col_size[k]){// if header width is greater than row width then apply that to row
                    tds[k].style.width = l_wd+'px'
                    tds[k].style.minWidth  = l_wd+'px'
                }else{
                    tds[k].style.width = larr_col_size[k]+'px'
                    tds[k].style.minWidth  = larr_col_size[k]+'px'
                }

            }

        }
    }

    //---fix the header table based on column width in the data table
    var tables = document.getElementsByClassName("table");
    console.log( tables )

    l_header_table = null;
    for ( var i = 0; i < tables.length; i++){
        console.log( "tables *******************************************-", i)
        if (i%2 == 0){ //header
            console.log("header", i)
            l_header_table = tables[i]
        }else{ // row table
            console.log("row", i)
            l_row_table = tables[i]
            var first_row = l_row_table.getElementsByTagName("TR")[0];
            var tds = first_row.getElementsByTagName('TD');
            var larr_col_size = []
            for ( var j = 0; j < tds.length; j++){ // width of each cell
                console.log( tds[j].innerText, tds[j].style.width, tds[j].style.offsetWidth, tds[j].getBoundingClientRect().width)
                larr_col_size.push(tds[j].getBoundingClientRect().width)
            }
            console.log(l_row_table )
            console.log(larr_col_size)
            console.log(l_header_table)
            var first_row = l_header_table.getElementsByTagName("TR")[0];
            var h_tds = first_row.getElementsByTagName('TH');

            for ( var k = 0; k < h_tds.length; k++){
                console.log( h_tds[k].innerText, larr_col_size[k])
                l_wd = h_tds[k].getBoundingClientRect().width
                console.log( l_wd, ' __>__ ', larr_col_size[k] )

                h_tds[k].style.width = larr_col_size[k]+'px'
                h_tds[k].style.minWidth  = larr_col_size[k]+'px'
            }

        }
    }
}

exports.myReactBootstrapTable_adj = myReactBootstrapTable_adj; //public function

**Comment by AllenFang** [comment]
First of all, you forgot include the css of ```react-bootstrap-table```, you can find it in ```dist``` folder.

BTW, you write down a well document, I'll spend some time to check this out. Thanks you :)

**Comment by venkat-vs-id** [comment]
I used it and still it was the same. But my fix fixed it...

**Comment by AllenFang** [comment]
HI @venkat-vs-id, anyway thanks this problem solving. I'm still sticking on development for ```v.3.0.0```. I'll  be back and review this solution.
