### ISSUE TITLE
Edit button for a cell?

### ISSUE THREAD

**Issue by lmeyerov** [AllenFang/react-bootstrap-table#766]
We're trying to make it so that, by clicking an explicit "edit" button, a cell switches into editing mode. Any pointers on what we should do for the JS side of things? (E.g., how to synthesize & send the appropriate event to mimic the cell being clicked.)

Example from Jira & Expensify: hovering over the bottom element reveals an edit button (doable via CSS), and upon clicking the edit icon, the text area switches into editing mode.

![image](https://cloud.githubusercontent.com/assets/4249447/19253307/0c41274c-8eff-11e6-81e6-13874b255848.png)

**Comment by AllenFang** [comment]
hi @lmeyerov, where's the edit button, in the target cell? for example, click the button in the cell, then the cell become editable?

**Comment by lmeyerov** [comment]
Yes. Here are two possibilities:

* Custom renderer: I want to make an OnClick handler for a custom DOM element in the same cell that switches the cell to edit mode.  I'm hoping this is may be doable with the current release via some sort of trigger event..

* Out-of-the-box: I've seen variants where the edit button was always there, and other variants where the cell changes style on hover.

I'm wanting to do this right now for the cell, though this can make sense for the column header as well. 

This is helpful for making it easier for users to discern that something is editable and how to trigger that editing. In addition, we want rich rendering of the non-edit mode, e.g., hyperlinks within the cell contents, so this helps separate clicking modes.

**Comment by AllenFang** [comment]
> Custom renderer: I want to make an OnClick handler for a custom DOM element in the same cell that switches the cell to edit mode. I'm hoping this is may be doable with the current release via some sort of trigger event..

how about trying the cell edit?  [There](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/cell-edit) have some example you can take it~

if this is not your wanted, feel free to tell me.

**Comment by lmeyerov** [comment]
I unfortunately did not see how to do that. Do you mean I should do a fully custom cell, similar to custom-cell-edit? I was hoping to be able to reuse the existing editor, not rewrite it.

E.g., I'd love to be able to write something like:

```
function urlFormatter (url, row) {
    return (<div>
          <a href={url}>link</a>
          <button onClick={ row[url].toggle('edit') }>
       </div>);
}
...
<TableHeaderColumn dataField="url" dataFormat={urlFormatter} />
...

The expected result would be that it initially loads as a link and a button. Then, on button click, the cell switches to edit mode. On completion of editing, e.g., hitting enter, it would switch back 
to an updated link and button.

**Comment by AllenFang** [comment]
@lmeyerov, sorry for lately reply.



> Do you mean I should do a fully custom cell, similar to custom-cell-edit

yes, you can custom a cell editor by yourself.



> The expected result would be that it initially loads as a link and a button. Then, on button click, the cell switches to edit mode. On completion of editing, e.g., hitting enter, it would switch back 
> to an updated link and button.

Actually, if you can check this example, the cell editing in ```react-bootstrap-table``` have the two way for triggering cell editing:  ```click``` and ```dbclick```. So you dont need to implement it by yourself, you just need to implement the editor.

Feel free to discuss with me if you still got the trouble when implement. Thanks

**Comment by JAmesBrian1217** [comment]
@AllenFang  How to create delete button from each rows ?

**Comment by AllenFang** [comment]
use `dataFormat`

**Comment by camel2243** [comment]
@AllenFang I try to return BoostrapButton component (JSX)in dataFormat function(), but dataFormat function must return HTML string?

**Comment by AllenFang** [comment]
You can also return a React JSX

**Comment by kamarajuPrathi** [comment]
@AllenFang as per the comment posted on oct17th 2016 
The expected result would be that it initially loads as a link and a button. Then, on button click, the cell switches to edit mode. On completion of editing, e.g., hitting enter, it would switch back
to an updated link and button.

Do you have an example to this feature ?

**Comment by AllenFang** [comment]
@kamarajuPrathi, could you please open an issue for requesting this your requirement? thanks~

**Comment by dhananjayd232** [comment]
@AllenFang  
I want to open editable mode for all cell of a row after click on some button(instead of click or double click on cell)
Is it possible ?

**Comment by AllenFang** [comment]
@dhananjayd232 I'm sorry that we are not support this feature currently. but we will consider to implement this feature on [`react-bootstrap-table2`](https://github.com/react-bootstrap-table/react-bootstrap-table2).

**Comment by dhananjayd232** [comment]
@AllenFang, Sorry for late reply,
Thanks for your consideration on this, waiting for this functionality.

**Comment by karanpasrija** [comment]
@AllenFang ,  Is this functionality available now?

**Comment by SurajBong** [comment]
is there any way to implement cell edit on button click in a row in react-bootstrap-table version 1?

**Comment by SurajBong** [comment]
https://github.com/SurajBong/React-Project-App/blob/base-Features/src/App.js

I have added sort of cell edit on checkbox click.
