### ISSUE TITLE
Search fails on number 0 

### ISSUE THREAD

**Issue by sgentile** [AllenFang/react-bootstrap-table#768]
When binding to a column with a value of 0 and then typing 0 in the search box doesn't properly return the intended results.

TableDataStore.js

line 489

if (this.colInfos[key] && row[key]) {

This returns 0 (which is false)

Converting the data first to a string gets around the issue, but not the desired solution.

**Comment by AllenFang** [comment]
@sgentile thank you, but why you give a column width with zero? you can use ```hidden```

**Comment by sgentile** [comment]
It's the data not a column.  The data is a zero - I type zero into search
it returns false instead of checking the value as zero and doing a proper
compare

**Comment by AllenFang** [comment]
Fixed on ```v2.5.6```

**Comment by sgentile** [comment]
Thank you
