### ISSUE TITLE
Fill a column with components

### ISSUE THREAD

**Issue by welcoMattic** [AllenFang/react-bootstrap-table#770]
It could be very useful to be able to fill a column with React component or simple HTML objects.

My instance for this use case is :

I have technical type column that I want to display as icons. I want to be able to declare my `type` property passed to `data` attribute of BootstrapTable, as (simplified) :

```javascript
getIconFromType(type) => {
  return (
    <img src="{type}.png" />
  );
}
```

```jsx
<BootstrapTable ref="table" data={{
  ...
  type: this.getIconFromType(type);
  ...
}} ...>
```

**Comment by AllenFang** [comment]
hi @welcoMattic, I think ```dataFormat``` can answer this question, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-format/react-column-format-table.js).

Feel free to discuss with me :)

**Comment by welcoMattic** [comment]
I'll try it soon! Thanks for answer
