### ISSUE TITLE
Datepicker in new record not returning a date for validation

### ISSUE THREAD

**Issue by g3blv** [AllenFang/react-bootstrap-table#773]
I'm using version `2.5.5` of `react-bootstrap-table`. I'm using the date picker as per [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/advance/edit-type-table.js#L38). In the `New Record` modal the date picker comes up and it is possible to select a date but once `Save` is clicked in the modal there is no date sent if `validator` is enabled. Not sure if the issue comes from that when a date is selected it comes up as "13/10/2016, --:--". 

Some more general observations with the date picker. The format for the `datetime` should it be [ISO datetime](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) less the "Z" on the end of the ISO datetime? Also Is it possible to format the field to have just `date` rather than `date` and `time` and always show it as "YYYY-MM-DD" instead of "DD/MM/YYYY"?

**Comment by AllenFang** [comment]
@g3blv, sorry for lately reply, I'll check this out. thanks 👍

**Comment by AllenFang** [comment]
> Not sure if the issue comes from that when a date is selected it comes up as "13/10/2016, --:--".

Absolutely right, you can check this [example](http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_datetime-local_get).

> The format for the datetime should it be ISO datetime less the "Z" on the end of the ISO datetime?

```react-bootstrap-table``` only support very simple date time picker, I follow this [one](http://www.w3schools.com/html/html_form_input_types.asp)


> lso Is it possible to format the field to have just date rather than date and time and always show it as "YYYY-MM-DD" instead of "DD/MM/YYYY"?

Currently on way, but in ```v.3.0.0```, you can customize one by yourself.

Feel free to discuss with me. Thanks you

**Comment by cristina321** [comment]
Hi AllenFang and a datepicker only for date and not hours?

**Comment by AllenFang** [comment]
@cristina321, include to the hour, minute and seconds
