### ISSUE TITLE
when field validator message is displayed and clicking New button will cause infinite loop

### ISSUE THREAD

**Issue by konghoiwai** [AllenFang/react-bootstrap-table#774]
Hi, this is an edge case which will cause the browser to hang.  
# Repro steps:

1) Run the react-bootstrap-table example project locally
2) Navigate to the "Advanced data edit & Insert" option under Examples
3) Scroll to the last example
4) click the job name cell. Remove some characters so validator will display validation msg
5) before the msg disappear, click the "+new" button.
# Result

browser will hang

**Comment by AllenFang** [comment]
@konghoiwai, thanks you, this issue has been solved on ```v3.0.0-dev```, check #497 for details.  I we release ```v3.0.0``` as soon as possible

**Comment by AllenFang** [comment]
The `v3.0.0-beta.7` already released and fixed on it, check this out, it's certainly stable for developer :)
