### ISSUE TITLE
Table height, Chrome

### ISSUE THREAD

**Issue by docmur** [AllenFang/react-bootstrap-table#776]
Hey

If I set the height on the table, it works fine across Firefox and Chrome.  If I don't set the height, Firefox seems to render find but Chrome seems to pin the table at 100% of the screen.  

Thanks
Andrew

**Comment by AllenFang** [comment]
@docmur, any screenshot? and what's version of your firefox and chrome.

I remember the 100% height is correct without configuring the ```height```.

**Comment by docmur** [comment]
Screenshot attached, with the versions of the browser's on the screens.

Both of the tables show have the same information

![datatable](https://cloud.githubusercontent.com/assets/6304369/19443439/c4e5ad12-945a-11e6-881b-453c8effcbe6.png)

**Comment by robbert229** [comment]
I also have encountered this issue.

**Comment by achraf-jeday** [comment]
Same bug found in Firefox 50.1.0.

**Comment by AllenFang** [comment]
ok, I'll check this out, BTW, does you guys enable the ```pagination```?

**Comment by achraf-jeday** [comment]
Yes I am using the pagination and it gets pushed down and overlaps the footer.

**Comment by AllenFang** [comment]
@achraf-jeday, would you please help me to disable it and test again? thank 👍

**Comment by achraf-jeday** [comment]
@AllenFang, disabling the pagination doesn't fix the issue because I still see some extra height added at the bottom of the table but the overlapping is gone.

**Comment by AllenFang** [comment]
ok, last one request, could you give me a screenshot?  Thanks 👍

**Comment by achraf-jeday** [comment]
![pagination_pushed_down](https://cloud.githubusercontent.com/assets/4772404/21854219/44170952-d81a-11e6-9e86-9cb996a3ae7d.png)

### Note

Removing the inline css rules (height: 100%) would fix the issue.

**Comment by achraf-jeday** [comment]
I fixed the issue using this :

`.react-bs-table {
  height: auto !important;
}`

**Comment by AllenFang** [comment]
awesome, a great workaround, so there's no any gap between pagination and body?

**Comment by AllenFang** [comment]
anyone can try this one: `react-bootstrap-table@2.10.0-beta`  by
```npm install react-bootstrap-table@2.10.0-beta.1```

Let me know if the problem still there.

**Comment by hehaijin** [comment]
Hi All,  
I am using 
"react-bootstrap-table": "^3.1.7"
and I am still having this issue.
Is is solved? and the workaround seems not working. 
I am on Chrome 59.

**Comment by Kebie** [comment]
I am having this issue when I compile for production but not when I am just running locally on hot loading dev setup. It is very weird.
