### ISSUE TITLE
Custom filter in modal window can't be edited 

### ISSUE THREAD

**Issue by oakley808** [AllenFang/react-bootstrap-table#778]
Hi. 
I've found a bug where I can't enter numbers in a filter `<input>` that is created inside a bootstrap modal and popover menu.
Here's a fiddle demo: https://jsfiddle.net/oakley808/69z2wepo/60029/
Steps to reproduce:
1.  Click Open table button
2.  Click Open filter menu
3.  Try to enter a value in one of the inputs.
Any ideas? 
(note: I can edit checkbox inputs in my full app. Just not text inputs.)

**Comment by oakley808** [comment]
On second thought, this looks like an issue on ReactBootstrap's popover/overlay. Go ahead and close this issue.

**Comment by AllenFang** [comment]
hi @oakley808, could you confirm this is the issue from ```ReactBootstrap```?

**Comment by oakley808** [comment]
It is. https://github.com/react-bootstrap/react-bootstrap/issues/1551

Go ahead and close it. Thank you!
