### ISSUE TITLE
insertRow Button Does not Work

### ISSUE THREAD

**Issue by inonpeled** [AllenFang/react-bootstrap-table#78]
Upon specifying insertRow in the properties of BootstrapTable, a "new" button appears, but this button doesn't add any new rows. Check e.g. demo.js with version 1.2.0.

**Comment by AllenFang** [comment]
HI @inonpeled, if click insertRow button, will pop a modal and you need input your new row and save it. Did you see the modal or any error?

**Comment by inonpeled** [comment]
No modal pops up on my Chrome with version 1.2.0.

**Comment by AllenFang** [comment]
Didi you import Bootstrap's css and javascript? Or any error ?

**Comment by inonpeled** [comment]
You're right, I've been using the react-bootstrap library which only requires Bootstrap's CSS, and so I didn't include the javascript.

Either way, I think you should consider depending on react-bootstrap yourself instead of wrapping bootstrap directly. What do you think?

**Comment by AllenFang** [comment]
maybe you r right, but I dont want <code>react-bootstrap-table</code> to depend a lots of module, and <code>react-bootstrap</code> has a lots of things which I dont want to include. Anyway, thanks your comments and glad of your problem has been solved :)

**Comment by Tolteque** [comment]
Hello,
  I have a similar problem. I use Table in REACT. I have included the CSS file "react-bootstrap-table/css/react-bootstrap-table-all.min.css" and also "https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css" and the open doesn't open the nodal window.
  When I do not include these two files, I get a flat layout as shown in the attached file.

![flatlayout](https://cloud.githubusercontent.com/assets/16269431/15793201/c592abf8-29e2-11e6-8e22-b25e2022a8e8.jpeg)

**Comment by AllenFang** [comment]
@Tolteque, it's necessary to include the css for ```bootstrap``` and ```react-bootstrap-table```, so dont miss them. And I guess the problem you encounter is you missing ```bootstrap.js``` too.

**Comment by Tolteque** [comment]
@AllenFang,  thx for the response.
In the main.html, I have included:
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">

react-bootstrap is installed in the project using babel, and the js import is done in my  .jsx files using ES6 synthax ( for instance: import Button form "react-bootstrap/lib/Button"). Is it correct for you, or do I miss something ?

**Comment by AllenFang** [comment]
@Toloteque, it's seems to be perfect. Any error log on browser console? and any repo for me to reproduce this error?

**Comment by Tolteque** [comment]
@AllenFang, No repo for the moment :( and yes a lot of warning in the console.
[warning.txt](https://github.com/AllenFang/react-bootstrap-table/files/299325/warning.txt)

**Comment by AllenFang** [comment]
@Tolteque, ok, I've no idea about that, so it's better to make a simple repo to reproduce this issue.
