### ISSUE TITLE
Wrong header items width

### ISSUE THREAD

**Issue by jdelafon** [AllenFang/react-bootstrap-table#781]
The table header's width is not calculated the same way as the table's body, ending up in situations like this (note the header overflowing on the right):

![capture d ecran 2016-10-19 08 50 07](https://cloud.githubusercontent.com/assets/12040845/19508361/236bc428-95d9-11e6-95dd-0a2e72228292.png)

**[Edit: actually it happens even without this, see below]** It happened because the bar on the left appears after a transition, and the whole layout re-rendered accordingly but the header did not.

**[Edit: just missing CSS files]** Also probably related: the width of a menu item is calculated before the sorting arrows are placed, which can produce this:

![image](https://cloud.githubusercontent.com/assets/12040845/19508407/6564b09c-95d9-11e6-8abd-59e2e39ac5e8.png)

I could solve this by setting the `width` property, but I don't want fixed with, and no `minWidth` prop is available.

**Comment by AllenFang** [comment]
@jdelafon, first of all, you forgot to add the css of ```react-bootstrap-table```. you can find it under the ```dist``` folder.  If the problem still there, feel free to tell me :)

**Comment by jdelafon** [comment]
Indeed, thanks, it works now. I naively thought npm would do that, but I had to add it to the webpack config entry points.

**Comment by jdelafon** [comment]
Actually with the CSS added there is still an issue: instead of being shifted, a header item completely disappeared. If I remove the side bar, it works fine.

![2016-10-19_16-02-55](https://cloud.githubusercontent.com/assets/12040845/19521887/a55705ec-9615-11e6-9cb1-1598c6a2bdac.png)

**Comment by jdelafon** [comment]
And this is with a simple 2-10 bootstrap columns layout, no more animation, no added css. : the column headers are misplaced:

![2016-10-19_17-56-38](https://cloud.githubusercontent.com/assets/12040845/19526713/98e7578e-9625-11e6-9319-36308ad4ee92.png)

**Comment by AllenFang** [comment]
> For some reason, according to changes I can make in dev tools, if there was no "width" not "min-width" properties to the th element, it would work just fine.

you means no any ```width``` or ```min-width``` on ```<TableHeaderColumn>```?


> And it is written in the "style" prop instead of in the CSS of a class, which makes it untouchable. I think a flexbox design would do that just fine, too.

Sorry, I cant get you, any example or detail explanation?

BTW, what's browser and version you use?  if you use newest chrome, there's known unalign issues.

if you can, maybe a repo got me to reproduce this issue is good, sometimes, this unalign is hard to reproduce on my local.

Thanks :)

**Comment by jdelafon** [comment]
I tried the latest Chrome and Firefox. 
I had to remove both width and min-width to get a normal layout in Chrome devtools, "element.style" section. I meant that using the new flexbox CSS properties, these sizing issues may go away.
I will try to make an minimal example but it will take some time.

**Comment by AllenFang** [comment]
that's ok, take your time. I'll keep to figure out

**Comment by jdelafon** [comment]
Here is a short part of my app reproducing the issue.

[Archive.zip](https://github.com/AllenFang/react-bootstrap-table/files/541877/Archive.zip)

The archive contains a complete project. Run "npm install", then "node run start" and go to localhost:3000.

I fail to understand what is special in this example, because I saw it happen without this react-sidebar component, but I can't reproduce yet. But at least it should point out differences between the body rows and the menu row with respect to layout.

**Comment by AllenFang** [comment]
@jdelafon, thanks you 👍

**Comment by thienanle** [comment]
Hey @AllenFang @jdelafon, I'm also having a similar issue. I've included the CSS, but it seems the issue is in the JS calculation of widths (it sets inline styles).

The widths are wrong:
![image](https://cloud.githubusercontent.com/assets/874402/19624040/c576ae36-9930-11e6-865b-252997296093.png)

Here's what my table looks like:
![image](https://cloud.githubusercontent.com/assets/874402/19624037/9afc327a-9930-11e6-949f-dadb7d231ce1.png)

**Comment by AllenFang** [comment]
@thienanle, what's your browser and version?  any simple repo for me to reproduce this issue? Thanks

**Comment by thienanle** [comment]
@AllenFang I'll set something up. I'm on Chrome version 54.0.2840.71 (64-bit)

**Comment by thienanle** [comment]
Ah my mistake, it's happening to me because I didn't include the bootstrap css file. Probably unrelated to OP's issue.

**Comment by thienanle** [comment]
@jdelafon We have the same setup (using React Static Boilerplate). It seems the issue stems from the CSS being applied *after* JS runs. JS runs in order to calculate header item widths, and since the CSS hasn't been applied yet, it calculates the wrong widths.

I believe this isn't an issue with `react-bootstrap-table`, but with our setup or perhaps React Static Boilerplate.

**Comment by jdelafon** [comment]
@thienanle Good point. But I'd argue that since we can make every other component work, including the table's body itself, why should the table's header not scale correctly?

**Comment by thienanle** [comment]
@jdelafon The table body doesn't have any widths applied to it from JS (at least in my setup). It is dynamically sized per the default behavior of HTML tables.

CSS isn't always applied after. I think this has something to do with webpack's loading of modules. From what I know, the chunks all load asynchronously, so there's no way to know if the CSS loads before or after. I think switching the CSS loading to synchronous should solve our issue.

**Comment by jdelafon** [comment]
@thienanle That suggests that there is a way to calculate proper widths without JS, among which the now all-browsers-compatible CSS3 "[flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)", or a "display: table/table-row/table-cell" pattern. I am quite sure that Facebook's "fixed-data-table" module uses flexbox for that.

**Comment by AllenFang** [comment]
@thienanle, you are right, ```react-bootstrap-table``` will calculate and set the width on column for aligning header and body(Actually, header and body are two separate tables).

@jdelafon, yes, there's some people who suggest me to use ```flexbox```, but base on ```Bootstrap```, I need to study more to think about how to use flex with bootstrap.

BTW, because I want to make the vertical and horizontal scroll available on bootstrap table, I just make a table as two separated table for header and body, so I need the other effort to align them.

so if any idea or any simple html + css to implement bootstrap table with scrollable, feel free to discuss with me :)

**Comment by AllenFang** [comment]
Forgot something, you said you use React Static Boilerplate and cause this problem, but why and where's make this unalign issue?

**Comment by thienanle** [comment]
@AllenFang 

> It seems the issue stems from the CSS being applied after JS runs. JS runs in order to calculate header item widths, and since the CSS hasn't been applied yet, it calculates the wrong widths.

It's not necessarily the boilerplate's issue, but the way webpack loads the modules. I think since they're all loading asynchronously, there's no guarantee that CSS loads before JS.

**Comment by AllenFang** [comment]
got it. thank you.

**Comment by thienanle** [comment]
@AllenFang Definitely understand why you use JS to help align the table header widths to the rest of the table. It's probably the best way to achieve a scrollable body.

Here's another solution: [https://codepen.io/tjvantoll/pen/JEKIu](https://codepen.io/tjvantoll/pen/JEKIu)

Your solution is probably better in terms of compatibility. Ideally CSS should load before JS anyway.

Here's another solution using `requestAnimationFrame`, I wonder if it would make a difference?
http://stackoverflow.com/a/28748160/4066098

**Comment by AllenFang** [comment]
I'm not sure that ```requestAnimationFrame``` can help us. But like you said, we need to find a solution to ensure the css file be loaded than JS, because ```react-bootstrap-table``` give the js and css for you to add them. Anyway, I'll find some times to try the example by @jdelafon. Really thanks your helping, if any findings, welcome to share :)

💯

**Comment by alonfai** [comment]
@AllenFang  I resolve it in the meantime using the forceUpdate() API. 
Inside my component I register to the "componentWillUpdate"  event and call the table forceUpdate() method and the grid re-renders with header and body columns aligned.

**Comment by polyakoff** [comment]
@jdelafon Could you please share a sample of your config for including these CSS to the webpack entry points?

**Comment by jdelafon** [comment]
Sure:
  entry: [
    /* Bootstrap */
    'bootstrap-loader',

    /* Material Design Lite (https://getmdl.io) */
    /*'!!style!css!react-mdl/extra/material.min.css',*/
    /*'react-mdl/extra/material.min.js',*/

    /* React-bootstrap-table CSS */
    '!!style!css!react-bootstrap-table/css/react-bootstrap-table.css',
    'react-bootstrap-table/css/react-bootstrap-table.css',

    /* The main entry point of your JavaScript application */
    './main.js',
  ],

**Comment by polyakoff** [comment]
@jdelafon 
Many thanks!

I figured out how to do it myself. Downloaded `react-bootstrap-table.min.css` and placed this line `require("../css/react-bootstrap-table.min.css");` in my component. This overrides application-level `import 'bootstrap/dist/css/bootstrap.css';` which is needed for reac-webpack. Works well without changes to the webpack config. Hope this is ok too.

**Comment by AllenFang** [comment]
HI there, I release `react-bootstrap-table@2.10.0-beta.1` for fixing couples unalign issues, try it out, if it work and stablilty, I'll consider to release to production as soon as possible.
Let me know if the problem still there.  
Sorry for lately fixing.

**Comment by jdelafon** [comment]
React-static-boilerplate issue, for reference: https://github.com/kriasoft/react-static-boilerplate/issues/162

**Comment by AllenFang** [comment]
thanks for feedback 👍
