### ISSUE TITLE
Removing a column with filter set will filter all data

### ISSUE THREAD

**Issue by snowzach** [AllenFang/react-bootstrap-table#787]
I am dynamically adding and removing columns from the table. If I remove a column that has a filter set, it seems to filter all of the rows from what's left in the table until I re-enable the column and then change the filter value.

**Comment by snowzach** [comment]
Okay, if I call applyFilter('') on a column just before it is removed it doesn't cause a problem.

**Comment by AllenFang** [comment]
ok, feel free to discuss with me if you got some trouble, I'll spend some time to check this out. Thanks

**Comment by snowzach** [comment]
It still kind of feels like a bug to me. If a column is removed from the table, it's like the filter remains but there is no data to filter (because the column is gone) on so it somehow defaults to filtering all the data.

**Comment by AllenFang** [comment]
@snowzach, any simple example for me to reproduce this issue? thanks you 👍

**Comment by louisblin** [comment]
Hi @AllenFang ,

I ran into the same issue recently, here is a minimal example that reproduces the problem - https://jsfiddle.net/x631b92m/. It does feel like a bug, I could work on a PR if that's something you'd like to fix.

Thanks :)

**Comment by AllenFang** [comment]
@louisblin, thanks your example code, 👍 it's real a bug and any idea to fix it? i think I can fix it in near future, but if you want to contribute, will be welcome :)

**Comment by louisblin** [comment]
Hi @AllenFang ,

It took me ages to find some time to spend on that, but I eventually got something working. I guess we should move the implementation discussing to the PR now

**Comment by AllenFang** [comment]
Released on `v4.0.5`, thanks 👍
