### ISSUE TITLE
Number of rows to display fixed at 10

### ISSUE THREAD

**Issue by udalrich** [AllenFang/react-bootstrap-table#789]
I have a table which only allows me to select to 10 rows.

    const cellFormat = (cell, row) => {
        const style = levelStyles[row.level] || levelStyles['Default'];
        return ( <Panel bsClass="{style}"> {cell} </Panel> );
    };

    export default ({logMessages}) => {
        return (
        <Panel className="logMessages" header={title} >
        <BootstrapTable id="LogMessages"
                        data={logMessages}
                        keyField="domainId"
                        tableStyle={{tableLayout: "fixed"}}
                        pagination={true}
                        columnFilter={true}
                        defaultSortName="timeStamp"
                        defaultSortOrder="asc">
            <TableHeaderColumn dataField="level" dataAlign="left" dataSort={true}
                               filter={{type: "SelectFilter", options: level}}
                               width="100px" >
                Level
            </TableHeaderColumn>
            <TableHeaderColumn dataField="timeStamp"
                               dataAlign="left"
                               dataSort={true}
                               dataFormat={dateFormat}
                               filterFormatted={true}
                               width="210px">
                Date
            </TableHeaderColumn>
            <TableHeaderColumn dataField="message" dataAlign="left" dataSort={true}
                               columnClassName="wrapContents"
                dataFormat={cellFormat}>
                Message
            </TableHeaderColumn>
        </BootstrapTable>
    </Panel>
    );
    }
It shows the widget at the bottom to change the number of rows, but the clicking it does not bring up a menu of other options.  This is on Safari 10.0, but it also fails on a Windows machine (probably running Chrome or Firefox).

**Comment by AllenFang** [comment]
Add ```bootstrap.js``` to you dependency. BTW, this dependency will be remove in the near future.

**Comment by udalrich** [comment]
Did you mean `bootstrapjs` as a dependency?  I already had

    "bootstrap": "^3.3.7",

in my dependencies.  I could not find `bootstrap.js` and adding `bootstrapjs` did not help.

My full dependencies are

    "dependencies": {
    "atmosphere": "0.0.2",
    "atmosphere.js": "^2.3.2",
    "babel-plugin-transform-object-rest-spread": "^6.16.0",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react": "^6.16.0",
    "bootstrap": "^3.3.7",
    "bootstrapjs": "^2.0.0",
    "browserify": "^13.1.1",
    "leaflet": "^0.7.7",
    "react": "^15.3.2",
    "react-bootstrap-table": "^2.5.6",
    "react-dom": "^15.3.2",
    "react-redux": "^4.4.5",
    "react-redux-form": "^1.0.15",
    "redux": "^3.6.0",
    "redux-actions": "^0.12.0",
    "redux-thunk": "^2.1.0",
    "whatwg-fetch": "^1.0.0"
    },
    "devDependencies": {
    "babel-plugin-transform-object-rest-spread": "^6.8.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.5.0",
    "babelify": "^7.3.0",
    "browserify": "^13.0.1",
    "deep-freeze": "0.0.1",
    "gulp": "^3.9.1",
    "immutable": "^3.8.1",
    "mkdirp": "^0.5.1",
    "react-bootstrap": "^0.29.5",
    "redux-devtools": "^3.2.0"
    },

**Comment by AllenFang** [comment]
@udalrich, check http://getbootstrap.com/getting-started/#download, I means 
```
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
```

BTW, you can try ```v3.0.0-beta.2```, after v3.0.0, I remove the ```bootstrap.js``` and ```jQuery``` dependencies from this project. But currently, this beta release is not stable but you can give it a try.

Anyway, before ```v.3.0.0```, you should add ```bootstrap.js``` and ```jquery``` as your dependency

**Comment by udalrich** [comment]
I switched to 3.0.0-beta.2 and it works for me.
