### ISSUE TITLE
get selected data which only show in table when onSelectAll be called

### ISSUE THREAD

**Issue by luqin** [AllenFang/react-bootstrap-table#79]
在做服务端分页时，[Row selection(Multiple)] 的 `onSelectAll` 如何获取选中的项？能否使用 `selectedKeys` 替代 `isSelected`

**Comment by AllenFang** [comment]
HI @luqin, if you enable the onSelectAll hook, you can just verify the <code>isSelected</code>, if true, means your all data in table been selected, so you must have your all data on <code>react-bootstrap-table</code> right? that's all selected data.  >>>  select all means all data you selected, and you must know your all data

**Comment by luqin** [comment]
我如果仅仅只需要列表上选中的数据呢？而不是所有的

**Comment by AllenFang** [comment]
good question, I will add the data which show in the table if onSelectAll hook be called, but in next version.

**Comment by AllenFang** [comment]
HI @luqin, fix this issue in v1.2.1, here is a example: 
<pre>
function onSelectAll(isSelected, currentDisplayAndSelectedData){
     //currentDisplayAndSelectedData is which you want 
}
</pre>

**Comment by luqin** [comment]
@AllenFang good

**Comment by luqin** [comment]
可以参考下这个 Table：
demo：http://ant.design/components/table/
source：https://github.com/ant-design/ant-design/blob/master/components/table/index.jsx

**Comment by AllenFang** [comment]
@luqin, I think we should talk about remote data in #73 , and share some idea about how you implement it and what ajax library use? :)
