### ISSUE TITLE
Remove tooltip on hover on table header?

### ISSUE THREAD

**Issue by flipjs** [AllenFang/react-bootstrap-table#793]
When you mouseover on table header/column name, it shows a tooltip showing the column header name. To me its redundant. How can I disable it? Thanks.

**Comment by AllenFang** [comment]
@flipjs, I'll support this in these day. Thanks

**Comment by AllenFang** [comment]
Add ```headerTitle={ false }``` on ```<TableHeaderColumn>``` and upgrade to ```v2.5.7```. Thanks :)

**Comment by flipjs** [comment]
Cool stuff! Thanks so much @AllenFang !

**Comment by ptadas** [comment]
Related question. How would one modify the text displayed in the tooltip? I've tried using headerText, but it seems to have no effect when the column name is not an object. For instance, I'd like to name my column "YoY" and display "Year over year" in the tooltip. Thanks
