### ISSUE TITLE
Question: Can columns be grouped?

### ISSUE THREAD

**Issue by orangecoding** [AllenFang/react-bootstrap-table#794]
Hi,

Is it possible to group columns?
For instance like so:

Customer -------------- **|** Revenue
Name | Number | Activity **|** Activity | Number of Agents

Please ignore the -----. This is only for formatting..

**Comment by AllenFang** [comment]
https://github.com/AllenFang/react-bootstrap-table/pull/748  I thinks this PR is what you want, right?

if true, we are still wait the bug fix, you can watch this PR for more detail.

**Comment by AllenFang** [comment]
Fixed on ```v2.8.0```, there're some example you can check https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/column-header-span
