### ISSUE TITLE
ScrollBars

### ISSUE THREAD

**Issue by jmc420** [AllenFang/react-bootstrap-table#803]
Hi

I had a problem in version 1.4.6 with scrollbars. See:

https://github.com/AllenFang/react-bootstrap-table/issues/254

I recently upgraded from version 1.4.6 to version 2.5.6 and I cannot get vertical scroll bars added.

In version 1.4.6 the DOM structure was

 div class="react-bs-container
  div class="react-bs-table-container" style="height:100%;">
  div class="table-header-wrapper">
  div class="table-header">
  div class="table-container" style="height:100%;">"

 I added these css rules to make scrolling work then:

.react-bs-table-container {
  height:100% !important;
}

.react-bs-table-container .table-container {
  height:90% !important;
}

In version 2.5.6 the DOM structure has changed to:

div class="react-bs-table-container"
 div class="react-bs-table" style="height: 100%;"
  div class="react-bs-container-header table-header-wrapper"
  div class="react-bs-container-body" style="height: 100%;">
   table>
    thead>
    tbody>"

I have not been able to get scrolling to work. Is there something else I need to do to get it to work?

James

**Comment by AllenFang** [comment]
@jmc420, sorry for lately reply. If you wanna get the vertical bar appear, you need to set the ```height``` on ```BootstrapTable```, because default height is ```100%```.

Feel free to discuss with me if problem still remain.

**Comment by jmc420** [comment]
yes I tracked it down and fixed it with these css rules:

.react-bs-table-container {
  height:100%;
}

.react-bs-container-body {
  height:95% !important;
  overflow:auto;
}

Getting percentage heights and scrollbars to work is always a pain:

http://stackoverflow.com/questions/17060168/scroll-bar-on-div-with-overflowauto-and-percentage-height
