### ISSUE TITLE
Filter + selectAll issue

### ISSUE THREAD

**Issue by lioralt** [AllenFang/react-bootstrap-table#804]
Hi,
I have an issue with the following scenario:
1. filter by column
2. check the "select all" checkbox (to select all the filtered rows)
3. clean the filter

The result is that all the rows are shown as checked.

thanks :)

**Comment by AllenFang** [comment]
hi @lioralt, this is a default condition. the select all in ```react-bootstrap-table``` which means select the all row without any condition. There're some people ask the same question, but it's hard to decide and to change currently. 

if you really want this feature, you can try following workaround,

```js
class Example extends React.Component {

  handleSelectAll = (isSelect) => {
    if (isSelect) return this.refs.table.state.data.map(row => row.id);
  }

  render() {
    const selectRow = {
      mode: 'checkbox',
      onSelectAll: this.handleSelectAll
    };
    return (
      <div>
        <BootstrapTable ref='table' data={ products } selectRow={ selectRow } pagination>
          <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn ref='nameCol' dataField='name' filter={ { type: 'TextFilter', delay: 1000 } }>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
        </BootstrapTable>
      </div>
    );
  }
}
```

**Comment by lioralt** [comment]
Hi @AllenFang ,
I'm already able to select only the ones that are filtered with the following code:

```
  _onSelectAll(isSelected) {
    if (isSelected) {
      this.setState({selectedRows : this.state.shownRows});
    } 
    else {
      this.setState ({selectedRows : []});
    }
  }


  afterColumnFilter(filterConds, result){
    this.setState ({shownRows : result});
  }
```

The problem is once i remove the filter, all the checkboxes are shown as checked (although they arn't really checked and arn't included in my "selectedRows ").

thanks.

**Comment by AllenFang** [comment]
> he problem is once i remove the filter, all the checkboxes are shown as checked (although they arn't really checked and arn't included in my "selectedRows ").

Like the example I mentioned before, return a keys array if isSelected is true. which is mean what's row key you want to be selected when select all trigger!!
