### ISSUE TITLE
A bug displaying boolean value

### ISSUE THREAD

**Issue by wy19900814** [AllenFang/react-bootstrap-table#805]
Hi,

I had some data like [{test:true},{test:true},{test:false}]
The True value could display well, but the false value was empty.

Could you check this?

Best,
Yang

**Comment by AllenFang** [comment]
Will be fixed on next version. Thanks 👍

**Comment by AllenFang** [comment]
Released on ```v2.5.7```. Check it out~

**Comment by wy19900814** [comment]
Thanks so much!
