### ISSUE TITLE
Navigating to last page even when row is added in the beginning

### ISSUE THREAD

**Issue by harshjv** [AllenFang/react-bootstrap-table#808]
This method navigates to the last page when pagination is enabled.

    var result = this.refs.table.handleAddRowAtBegin(fakeRow)

## Expected behavior
Navigate to the first page

**Comment by AllenFang** [comment]
@harshjv, got it. I'll improve this in next version. Thanks

**Comment by harshjv** [comment]
@AllenFang I've already created a fix for this. Will send a PR soon.

**Comment by AllenFang** [comment]
@harshjv, ok, PR is welcome :)

**Comment by harshjv** [comment]
@AllenFang Done :) PR #809

**Comment by AllenFang** [comment]
@harshjv, released on ```v2.5.7```. Thanks your PR.
