### ISSUE TITLE
Transition to new url without reloading page using onRowClick

### ISSUE THREAD

**Issue by Luis-Ex** [AllenFang/react-bootstrap-table#813]
Is there anyway to do this with the onRowClick attribute, I'm not really sure how to pass the event: 

[http://stackoverflow.com/questions/40384956/transition-to-new-url-without-reloading-page-with-react-bootstrap-table-onrowcli](url)

Any help is greatly appreciated, thanks!

**Comment by AllenFang** [comment]
@Luis-Ex, i think it should be work. Just call ```changeURL``` in ```onRowClick```? maybe you can tell me what's problem you encounter :)

**Comment by Luis-Ex** [comment]
The thing is that I'm not really sure how that should be done. I've been trying something like this:

`onRowClick: function(row) {
    	(e) => this.displaySystemInfo(row, e);
  }`

`displaySystemInfo(row, event) {
	event.preventDefault();
	const systemId = row._id;
	this.context.router.transitionTo(`/system/${systemId}`)
}`

But it's not working at all, how should I be doing it? Thank you by the way!

**Comment by AllenFang** [comment]
> But it's not working at all

so, any error message or nothing happen?

**Comment by Luis-Ex** [comment]
Just this warning:

`warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions`

but nothing occurs on click.

**Comment by AllenFang** [comment]
try following
```onRowClick: function(row) { this.displaySystemInfo(row); }```

**Comment by Luis-Ex** [comment]
Hi, I ended up using ES6 arrow function to make it work:

`onRowClick: row => {
        const systemId = row._id;
        this.context.router.transitionTo(`/system/${systemId}`);
      }`
