### ISSUE TITLE
Huge performance issues (using redux as store)

### ISSUE THREAD

**Issue by daniel1943** [AllenFang/react-bootstrap-table#815]
Sometimes I get 1000 new objects within 1-10 seconds that I would like to display inside tables, if I don't use react-bootstrap-table then it's added to store normally... but if I do, it pretty much makes browser unresponsive for a ~ 2 minutes.

I tried with the most basic table(1 column, no fancy settings) and it doesn't seem to help.

```
<BootstrapTable
          data={this.props.treeData}
        >
          <TableHeaderColumn
            dataField="keyword"         
            isKey
          >Branch
          </TableHeaderColumn> 

        </BootstrapTable>
```

What options do I have ?

**Comment by AllenFang** [comment]
There's a known performance issue particular enabling ```selectRow``` and or ```cellEdit```. But in your case, you dont. so maybe you can try to add new row by exposed API, but it's not a very redux way(practice)...

```js

handleAddingNewRow(newRow) {
    this.refs.table.handleAddRow(newRow);
}

render(){
    return(
        <BootstrapTable ref='table' ...>
    );
}
```

After v3.0.0 released, I'll try to fix this issue, if I still have time. Thanks

**Comment by daniel1943** [comment]
If somebody else runs into this problem, solution was to buffer data (I did it with RxJS) before updating redux store, so it doesn't re-render 1000 times in a second :)
