### ISSUE TITLE
Remote filtering, paging functionality

### ISSUE THREAD

**Issue by shahromil88** [AllenFang/react-bootstrap-table#816]
Hi,

I found react-bootstrap-table nice component to use as grid in react app. However, it's still missing functionality of server side/remote paging, filtering, sorting etc which is very crucial. 

Can you please let me know when it will be released? I want to start development of new project in react. 

Cheers,
Romil

**Comment by AllenFang** [comment]
hi @shahromil88, would you please describe which part is missing that you think?

I'm not sure that [these](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/remote) is that you want?

**Comment by shahromil88** [comment]
Hi Allen,

Apologize for my misunderstanding. The functionality which I wanted is already there as per your given link.

Thanks for the prompt response.

Cheers,
Romiol

**Comment by AllenFang** [comment]
@shahromil88, that's ok, feel free to ask me anything if you have any problem.
