### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Component' of undefined

### ISSUE THREAD

**Issue by axay** [AllenFang/react-bootstrap-table#817]
I am trying to use this with [express-react-views](https://github.com/reactjs/express-react-views). This is my view file - 

    import React, { PropTypes } from 'react';
    import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';
    
    const TableLayout = props => (
      <html lang="en">
      <head>
        <title>{props.title}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="/react-bootstrap-table-all.min.css"/>
        <script src="http://code.jquery.com/jquery-2.1.3.min.js"></script>
      </head>
      <body>
      <BootstrapTable data={props.products} search={true} striped={true} hover={true} pagination={true}>
        <TableHeaderColumn isKey={true} dataField="id">Product ID</TableHeaderColumn>
        <TableHeaderColumn dataField="name">Product Name</TableHeaderColumn>
        <TableHeaderColumn dataField="price">Product Price</TableHeaderColumn>
      </BootstrapTable>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
      <script src="/react-bootstrap-table.min.js"></script>
      </body>
      </html>
    );
    
    TableLayout.propTypes = {
      title: PropTypes.string.isRequired,
      products: PropTypes,
    };
    
    export default TableLayout;

 
 Declaration of view engine in express :
 
     app.set('views', path.join(__dirname, '../../views'));
     app.set('view engine', 'jsx');
     
     const options = {
       beautify: true,
       babel: {
         presets: [
           'latest',
           'react',
         ],
       },
       transformViews: true,
       harmony: true,
     };
     
     app.engine('jsx', expressReactViews.createEngine(options));

This is how I am trying to render the view : 

    res.render('table', {
          title: 'Static Table',
          products: [
            {
              id: 1,
              name: 'Product1',
              price: 120,
            }, {
              id: 2,
              name: 'Product2',
              price: 80,
            }, {
              id: 3,
              name: 'Product3',
              price: 207,
            },
          ],
        });
      });

The data is being displayed correctly but while using search functionality, `search={true}`, I am getting the following error :

    Uncaught TypeError: Cannot read property 'Component' of undefined
        at Object.e.__esModule.default (http://localhost:3000/react-bootstrap-table.min.js:7:5483)
        at t (http://localhost:3000/react-bootstrap-table.min.js:1:462)
        at Object.e.__esModule.default (http://localhost:3000/react-bootstrap-table.min.js:7:24044)
        at t (http://localhost:3000/react-bootstrap-table.min.js:1:462)
        at Object.e.__esModule.default (http://localhost:3000/react-bootstrap-table.min.js:6:10956)
        at t (http://localhost:3000/react-bootstrap-table.min.js:1:462)
        at Object.t.exports (http://localhost:3000/react-bootstrap-table.min.js:1:693)
        at t (http://localhost:3000/react-bootstrap-table.min.js:1:462)
        at e.__esModule.default (http://localhost:3000/react-bootstrap-table.min.js:1:549)
        at http://localhost:3000/react-bootstrap-table.min.js:1:554
        
Any help would be appreciated

**Comment by AllenFang** [comment]
hi, I've no idea about this, but how about put the following two line in the ```<head>```?
```html
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<script src="/react-bootstrap-table.min.js"></script>
```

**Comment by axay** [comment]
Tried already, doesn't work

**Comment by AllenFang** [comment]
@axay, I really have no idea about this issue, could you use the unmin files to debug it? The unmin version is also under the ```dist``` folder

**Comment by erapatil** [comment]
Hi..m new to ReactJs and was trying to run the react code from eclipse using the typescript plugin. The error i am facing is this : 
    Uncaught TypeError: Cannot read property 'getHeaderColGroup' of undefined
    at t.value (BootstrapTable.js:1168)
    at t.n._adjustHeaderWidth (BootstrapTable.js:154)
    at t.value (BootstrapTable.js:1161)
    at t.n._adjustTable (BootstrapTable.js:150)
    at t.value (BootstrapTable.js:394)
    at s.notifyAll (CallbackQueue.js:67)
    at p.close (ReactReconcileTransaction.js:81)
    at p.closeAll (Transaction.js:204)
    at perform (Transaction.js:151)
    at f.perform (Transaction.js:138)

in Bootstrap.js file. I am not understanding the meaning of the error. i can retrive the data from the database into the table but, the error is shown simultaneously. Please Help! 
Also wheni click the butttons the same error pops up.
This is my screen. 

![image](https://cloud.githubusercontent.com/assets/24955463/21713066/0e735d78-d41e-11e6-855f-6bf02acc87fe.png)

**Comment by AllenFang** [comment]
@erapatil, firstly you forgot to include the css, please check [README](https://github.com/AllenFang/react-bootstrap-table#cimport-css). 

Second, I'm not very familiar with ts, so I think I can not help you here.

**Comment by AllenFang** [comment]
BTW, because @axay have no any response, so I'll open this issue until he has response.

**Comment by frossigneux** [comment]
I have this issue too:
```
TypeError: Cannot read property 'getHeaderColGrouop' of undefined
    at BootstrapTable._adjustHeaderWidth
```
Is there a mistake getHeaderColGrouop => getHeaderColGroup ?
