### ISSUE TITLE
Fixed pagination buttons

### ISSUE THREAD

**Issue by davidmendoza** [AllenFang/react-bootstrap-table#819]
Is there a way to have the pagination buttons (first, prev, next, last) fixed in the table? It seems that the buttons appear only depending on the total rows, size per page and pagination size. I'm using version 2.4.1 by the way.

**Comment by AllenFang** [comment]
HI @davidmendoza, This feature can be done on ```v3.0.0```, but this version is still on development, but almost complete. Plz wait to the release of ```v3.0.0```. Thanks

#497

**Comment by AllenFang** [comment]
@davidmendoza, try `v3.0.0-beta.7`, use `alwaysShowAllBtns` in `options` props. Let me know if you have any question,  it's a little [example](https://github.com/AllenFang/react-bootstrap-table/blob/v3.0.0-dev/examples/js/pagination/custom-pagination-table.js)

**Comment by arun-kumar-codes** [comment]
@AllenFang `alwaysShowAllBtns` is working for prev and next but not for first and last.
Is it not implemented for first and last buttons to show always. using `v4.1.1`
