### ISSUE TITLE
Sorting, don't include certain column data

### ISSUE THREAD

**Issue by retcheltapayan** [AllenFang/react-bootstrap-table#821]
Hi,

I am working on a feature that would allow sorting for certain columns but should not sort specific column data. My columns are Ranking (1-12), Name, Age. 
Name and Age are sortable but when sorting those column the ranking column should not be sorted along with it. It should always display 1-12 regardless of the sorting position of Name and Age column.

Please help.

**Comment by AllenFang** [comment]
@retcheltapayan, we don't support this fixed column when sorting. so PR is welcome.

**Comment by DevAxia** [comment]
Hi,
anyone found a solution to this ?  I am haveing the same issue.

**Comment by AllenFang** [comment]
@DevAxia, actually, I have no time to dig deep into this feature. maybe you need spend some time on it, and PR is really welcome. sorry

**Comment by DevAxia** [comment]
For now, I have created a specially named field, and in your lib, when I get this field, I rewrite the column with row indexes.  Thank you for your answer.
