### ISSUE TITLE
"Lock" rows from being edited ?

### ISSUE THREAD

**Issue by edulis8** [AllenFang/react-bootstrap-table#824]
Hi Allen,
I am hoping there is a way to do this. Based on certain criteria, I'd like to make certain entire rows uneditable. Currently from what I have seen, columns can be either editable or not; I don't know if I can put logic somewhere that will control whether or not to "lock" certain rows, so no cells can be edited within those rows. Possible?

Thanks,
Eric.

**Comment by AllenFang** [comment]
@edulis8, ok, I'll spend some time to do this

**Comment by edulis8** [comment]
Hi Allen,
I am trying that solution, but it is not working. I can still edit the rows that should be uneditable.

See following code. 

cellEditProps.nonEditableRows returns ["2", "3"]. My data set (this.props.sublistData) has four rows, their key is called "index." Rows with index 2 and 3 are still editable. 

    const cellEditProps = {
      mode: 'click',
      blurToSave: true, 
      beforeSaveCell: this.props.beforeSaveCell,
      nonEditableRows: this.props.sublistData && this.props.sublistData.filter((d) => {
        return !!d.purchase_order;
      }).map(d => d.index),
    };


    <BootstrapTable
        ref="table"
        search
        options={options}
        data={this.props.sublistData || []} 
        pagination 
        striped 
        hover
        deleteRow={this.props.editMode}
        selectRow={selectRowProps}
        cellEdit={cellEditProps}
      >

**Comment by AllenFang** [comment]
@edulis8, I cant reproduce this issue, please make sure you dont have any mistake. And actuallt, the ```nonEditableRows``` accept a callback function instead of an array or expression

**Comment by edulis8** [comment]
Hi Allen,
I changed nonEditableRows so it accepts a callback function, like this:

    const cellEditProp = {
      nonEditableRows: function () {
        return this.props.sublistData && this.props.sublistData.filter((d) => {
          return !!d.purchase_order;
        }).map(d => d.index);
      }.bind(this),
    };

And cellEditProp.nonEditableRows()); returns ["2", "3"]

Still I can edit the rows. Maybe the problem is that I have a boolean in state that controls if a row is editable, when the user clicks the Edit Mode button.

Like this:

<TableHeaderColumn width="75" editable={this.props.editMode} dataField="quantity">Quantity</TableHeaderColumn>

this.props.editMode is set to true when the user clicks the button. I imagine this is the problem.

**Comment by edulis8** [comment]
Hi Allen,
I implemented your example code for this, but I can still edit the Product Price for Product IDs < 3. See screenshot:

**Comment by AllenFang** [comment]
> this.props.editMode is set to true when the user clicks the button. I imagine this is the problem.

I think maybe this is the root cause for why you can still edit the cell. I'll check this out.

BTW, for the editing level, I think the cell level should greater than row level, so if you set ```editable={ true }``` on the column, which should be edited no matter what's condition for row level
