### ISSUE TITLE
react-router dependencies for examples

### ISSUE THREAD

**Issue by AdeelK93** [AllenFang/react-bootstrap-table#825]
For running the examples, the code provided is:
$ git clone https://github.com/AllenFang/react-bootstrap-table.git
$ cd react-bootstrap-table
$ npm install
$ gulp example-server #after start, open browser and go to http://localhost:3004

but this doesn't include installing the dependencies for react-router. Might I suggest adding a line in there somewhere for:
$ cd node_modules/react-router && npm i && cd .. && cd ..

**Comment by AllenFang** [comment]
@AdeelK93, did you use npm@3?

**Comment by AdeelK93** [comment]
Updating to the newest npm fixed the problem, my mistake!
