### ISSUE TITLE
Nested Rows

### ISSUE THREAD

**Issue by mayanksahai** [AllenFang/react-bootstrap-table#826]
Hi , i am planning to use this as data table component and wanted to know whether component supports row grouping feature and allows adding new Rows on the fly..

for example 

LMV Vehicles (Row group heading)
(-) ----- Scooter
(-) ----- Car
(-)----- Mini truck
(-) ------- XXXX   Add new Row/Delete Row

**Comment by AllenFang** [comment]
@mayanksahai, we support add row with multiple ways but we dont support nest row or row grouping.
This feature has been asked before, but I'm focus on development of ```v3.0.0```. so PR is welcome. Thanks :)
