### ISSUE TITLE
Making a service call onAfterSaveCell

### ISSUE THREAD

**Issue by martinpinto** [AllenFang/react-bootstrap-table#827]
Hi @AllenFang,

after a cell value has been modified:
is it possible to pass a service to `react-bootstrap-table` to make an http request `onAfterSaveCell` in order to persist the cell data on a server?

e.g.
```javascript 
export default class ReactTable extends Component {

  constructor() {
    super();
    this.service = new TableService();
  }

  onAfterSaveCell(row, cellName, cellValue){
      if (typeof row._id !== 'undefined') {
        this.service.patch(row); // updates the current row on the server
      } else {
        this.service.post(row); // inserts a new row on the server
      }
   }

render() {
    return (
        <BootstrapTable service={this.service} ... >
        ...
        </BootstrapTable>
    )
}
```
thank you :)

**Comment by AllenFang** [comment]
@martinpinto, you can do anything in ```afterSaveCell```, include calling a ajax request and you event dont pass ```service``` to ```react-bootstrap-table```, you can use it directly(Just make sure the ```this``` is ```ReactTable``` instead of ```BootstrapTable```).
