### ISSUE TITLE
improve examples

### ISSUE THREAD

**Issue by luqin** [AllenFang/react-bootstrap-table#83]
How about this : https://github.com/luqin/react-bootstrap-table/blob/react-router/examples/js/routes.js

**Comment by AllenFang** [comment]
Good~

**Comment by luqin** [comment]
如果合适的话我就再完善一下，然后提交 PR

**Comment by luqin** [comment]
我先按这个效果实现：http://luqin.github.io/react-DataTables/#/
你觉得怎么样？
后续你再修改模板成你希望的样子？

**Comment by AllenFang** [comment]
OK, I open mind for this example demo style or html chang, so feel free to modify :+1:

**Comment by luqin** [comment]
:+1:
