### ISSUE TITLE
How I can change date format in date-filter?

### ISSUE THREAD

**Issue by clairekh** [AllenFang/react-bootstrap-table#833]
How I can change date format in date-filter?
Now in date-filter we see this date format: **mm/dd/yyyy.** 

![screenshot from 2016-11-16 15-26-53](https://cloud.githubusercontent.com/assets/12009649/20339890/c89f21aa-ac19-11e6-8727-f98f6fa0aa90.png)

But I need change it to: **dd.mm.yyyy**. Can I do this?

**Comment by AllenFang** [comment]
We dont support this feature, but I think it should be support. I'll try to add this feature in near future but I'm busy recently, so PR is welcome.

**Comment by clairekh** [comment]
AllenFang, рhank you very much. I'll wait for the update.

**Comment by AllenFang** [comment]
@clairekh, firstly, I cant change the format, because I use ```<input type='date'/>```

according http://stackoverflow.com/questions/7372038/is-there-any-way-to-change-input-type-date-format, the input date cant change the format, and the format seems like depend on the user’s system settings’ date format.

**Comment by kapoorruchi** [comment]
Any updates on this?

**Comment by HZSamir** [comment]
Hello,
same question as the above: Can we still not switch to the dd/mm/yyyy format?
Thank you.

**Comment by gustavomdle** [comment]
Any updates?

**Comment by gustavomdle** [comment]
Any updates?
