### ISSUE TITLE
Question: is it able to get a cell value within TableHeaderColumn

### ISSUE THREAD

**Issue by tifa2chan** [AllenFang/react-bootstrap-table#834]
Hi.  I want to make a cell **editable = {true | false}** based on the initial cell value.
I don't know if I can get the cell value or other column cell value within TableHeaderColumn.

```
 <TableHeaderColumn
    dataField="authName"
    editable={ authName === '-' ? true : false}  // I want to get the cell value (authName) here...
>  
```

**Comment by AllenFang** [comment]
sorry @tifa2chan, we dont support this feature, but **maybe** I can support this like following:
```js

checkEditable(cell) {
    // return true or false
}

render() {
    return(
        <BootstrapTable ... >
            <TableHeaderColumn editableByCell={this.checkEditable}>...</TableHeaderColumn>
        </BootstrapTable>
    );
}

```

**Comment by tifa2chan** [comment]
@AllenFang , Thanks for your reply.  I didn't know that it takes the cell value as parameter.   It works perfectly!  
Just one thing, I think _editable_ is correct, not _editableByCell_ :)

**Comment by AllenFang** [comment]
@tifa2chan, so close this issue? because the code that I mentioned above can let you decide what cell can be edited.  The ```editable``` only make the column editable```.

**Comment by tifa2chan** [comment]
@AllenFang Yes, close this issue! Thank you!
I couldn't find ```editableByCell``` attribute in the document ( http://allenfang.github.io/react-bootstrap-table/docs.html ),  but I could use ```editable``` to make it work!

**Comment by AllenFang** [comment]
@tifa2chan, the ```editableByCell``` is for your case. Anyway, let me know if you still have any questions.
