### ISSUE TITLE
How to actually export table data as CSV

### ISSUE THREAD

**Issue by bnlambert** [AllenFang/react-bootstrap-table#836]
Hi!
After doing a lot of search I finally settle with react-bootstrap-table. I wish to know how to export table data to csv. I will so much appreciate if some code samples are presented. I was expecting to find such in the doc.

Thanks

**Comment by AllenFang** [comment]
hi @bnlambert, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/export-csv-table.js). Feel free to discuss with me if you have any question.

**Comment by bnlambert** [comment]
Thank you very much. 

I wish to know if react-bootstrap-table supports `<Link to="/user/:id">edit</Link>` links.

**Comment by AllenFang** [comment]
you can use ```dataFormat``` to customize your column, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-format/react-column-format-table.js#L44) example

**Comment by bnlambert** [comment]
Thank you very much. Good day!
