### ISSUE TITLE
Column Dropdown Filter exact match

### ISSUE THREAD

**Issue by mkasek** [AllenFang/react-bootstrap-table#840]
I am not sure if this is where I should post this or not, but I do not see anywhere else to post..

Is there any chance you would be willing to add a parameter to the filterText functionality so we can do an exact match of the filter value and target value instead of just checking to see if the filter value is in the target value? In my scenario, I have 3 different filter options of Undelivered, Delivered and Acknowledged. When I do a filter to only see the Delivered options, I am still getting all of the Undelivered results. 

When looking through the code, you are taking the targetVal and checking to see if there is an indexOf the filterVal and then returning a result based on that. Maybe having the option to do a direct comparison of the two values and only returning the results that match exactly? This is the code in question -

``` javascript
key: 'filterText',
    value: function filterText(targetVal, filterVal) {
        targetVal = targetVal.toString().toLowerCase();
        filterVal = filterVal.toString().toLowerCase();
        if (targetVal.indexOf(filterVal) === -1) {
            return false;
        }
        return true;
    }
```

Since there is the option to just do a search of Delivered and get both results, I think having the option of having a direct comparison for the filter dropdown would be beneficial when two of your values are similar like it is in my case. 

Or if there is a better way of handling this, I would be open to it.

Thanks.

**Comment by AllenFang** [comment]
@mkasek, there's always have any conditions in any filter, just like your case, so in my opinion, a custom filter will be a better solution :)
check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js

Feel free to discuss with me 👍

**Comment by mkasek** [comment]
I briefly looked at the custom filter but did not spend much time on it. I will look at more closely and see if I can get it working how I want it to.

Thanks for the reply and info.
