### ISSUE TITLE
Datepicker in date-filter does'n work in Mozilla FireFox and Internet Explorer

### ISSUE THREAD

**Issue by clairekh** [AllenFang/react-bootstrap-table#841]
Datepicker in date-filter does'n work in Mozilla FireFox. I use Firefox v.49.0.2 for Ubuntu and Firefox v.50.0 for Windows, Internet Explorer v.11.447.14393.0

![screenshot from 2016-11-17 08-59-30](https://cloud.githubusercontent.com/assets/12009649/20373538/72133170-acad-11e6-9296-83eb1799374c.png)

**Comment by AllenFang** [comment]
hi @clairekh, check http://caniuse.com/#search=date and http://www.w3schools.com/html/html_form_input_types.asp

I dont want to spend too many times to solve this issue, there's only a workaround, use custom filter to customize your date filter.

check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js

Feel free to discuss with me
