### ISSUE TITLE
Reset table display 

### ISSUE THREAD

**Issue by mjmhall** [AllenFang/react-bootstrap-table#848]
Hi

I've reset my table programmatically by using handleSearch('') to clear the search so that all rows are displayed. That works fine but now I need to clear the users input from the search box. Is there a   way to do that?

Thanks

**Comment by AllenFang** [comment]
hi @mjmhall, sorry for lateyl reply. I'll fix it in recent. Thanks

**Comment by AllenFang** [comment]
@mjmhall, released on ```v2.7.0```.

**Comment by mjmhall** [comment]
Hi @AllenFang 
Thanks, all working as expected.
