### ISSUE TITLE
Multiple date filters are not updating the filter object

### ISSUE THREAD

**Issue by email2vimalraj** [AllenFang/react-bootstrap-table#853]
I have two columns with Start Date and End Date with date objects. And I have DateFilter for both of these columns. I'm using `remote` btw.

**_Reproducing steps_**:
1. Filter date value from the start date column and observe the new filter object is created with startDate as a key.
2. Filter date value from the end date column and observe the endDate key is appended with the existing filter object created in the 1st step.

**_Expected Result_**:
The endDate should be appended to the existing filter object if initialized already.

**_Actual Result_**:
The filter object is overridden by the endDate filter. But for other type of filters, the object is keep getting appended.

**Version**: 2.5.8

**Comment by AllenFang** [comment]
@email2vimalraj, thanks for such detail explanation, I'll check this out. BTW, if you have time, could you please show me a minimal example for reproducing?

Thanks :)

**Comment by email2vimalraj** [comment]
@AllenFang : Sure I'll do it. BTW, I've started a blog post with some real-time examples for the react-bootstrap-table. Mind having a look? http://www.vimalselvam.com/2016/11/23/react-bootstrap-table-part-1/

**Comment by AllenFang** [comment]
hi @email2vimalraj, that's great, I thinks this repo need the people who like you would like to share this project. Anyway, your writing is very well, it's also a good promotion 👍  

Thanks your contribution :)

**Comment by email2vimalraj** [comment]
@AllenFang : Thanks a lot for your great words.
BTW, I'm unable to reproduce the reported issue now. So I'll close and re-open if I reproduce again with the sample code. Sorry for inconvenience.
