### ISSUE TITLE
unique "key" prop Error

### ISSUE THREAD

**Issue by AlessandroPilastrini** [AllenFang/react-bootstrap-table#856]
Hi, I would like make TableHeaderColumn name dynamic.
So I decide to use forEach() and push ` <TableHeaderColumn .../>`  inside a variable for each name in my array: 

```
render(){
this.props.colName.forEach( (e, i) => {
      tableHeaderColumn.push(
        <TableHeaderColumn 
           editable={{type:'text', validator:this.props.validator}} 
           dataField='value'
         > 
             {this.props.colName[i].company}
         
         </TableHeaderColumn>
      )
    });

  return (
     <BootstrapTable
        keyField='value' 
        data={service} 
        cellEdit={cellEditProp}
      >

          <TableHeaderColumn dataField="data" >{this.props.tableTitle}</TableHeaderColumn>
                {tableHeaderColumn}
          </BootstrapTable>

```
After that, the table is rendered but receive the following error in console:

```
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `SimpleTableDynamic`. See https://fb.me/react-warning-keys for more information.
    in TableHeaderColumn (created by SimpleTableDynamic)
    in SimpleTableDynamic (created by ConfigPanelContent)
    in div (created by ConfigPanelContent)
    in div (created by ConfigPanelContent)
    in div (created by ConfigPanelContent)
    in form (created by ConfigPanelContent)
    in div (created by ConfigPanelContent)
    in div (created by ConfigPanelContent)
    in ConfigPanelContent (created by RouterContext)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in divprintWarning @ bundle.js:1316
```

I also use the equivalent props isKey={true}, same error! what's wrong?

**Comment by AllenFang** [comment]
you can use ```keyField``` on ```BootstrapTable```

**Comment by AlessandroPilastrini** [comment]
I used it!

**Comment by AllenFang** [comment]
key is unique. so remove all the ```isKey``` and use ```keyField```.  or only use ```isKey``` on one column.

**Comment by AllenFang** [comment]
> Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `SimpleTableDynamic`. See https://fb.me/react-warning-keys for more information.
>     in TableHeaderColumn (created by SimpleTableDynamic)
>     in SimpleTableDynamic (created by ConfigPanelContent)
>     in div (created by ConfigPanelContent)
>     in div (created by ConfigPanelContent)
>     in div (created by ConfigPanelContent)
>     in form (created by ConfigPanelContent)
>     in div (created by ConfigPanelContent)
>     in div (created by ConfigPanelContent)
>     in ConfigPanelContent (created by RouterContext)
>     in div (created by App)
>     in div (created by App)
>     in div (created by App)
>     in div (created by App)
>     in App (created by RouterContext)
>     in RouterContext (created by Router)
>     in Router
>     in divprintWarning @ bundle.js:1316

BTW, this error is the problem about react key, you should check the react document, it's not related with react-bootstrap-table

**Comment by AlessandroPilastrini** [comment]
@AllenFang  I know the react problem but I can't use`key` props on `<TableHeaderColumn>` component

**Comment by AllenFang** [comment]
> I can't use key props on <TableHeaderColumn> component

Any error message?  following is not work?
```js
this.props.colName.forEach( (e, i) => {
      tableHeaderColumn.push(
        <TableHeaderColumn 
           key={ i }
           editable={{type:'text', validator:this.props.validator}} 
           dataField='value'
         > 
             {this.props.colName[i].company}
         
         </TableHeaderColumn>
      )
    });
```

**Comment by AlessandroPilastrini** [comment]
No...is not possible:

in the library should be added `key` props in TableHeaderColumn.js:

```
    let defaultCaret;
    const {
      dataAlign,
      dataField,
      headerAlign,
      headerTitle,
      hidden,
      sort,
      dataSort,
      sortIndicator,
      children,
      caretRender,
      className,
      **key**
    } = this.props;
```

and in th:

```
<th ref='header-col'
          className={ classes }
          style={ thStyle }
          **key={key}**
          onClick={ this.handleColumnClick }
          { ...title }>
        { children }{ sortCaret }
        <div onClick={ e => e.stopPropagation() }>
```

so it could be possible pass a `key`

**Comment by AllenFang** [comment]
I try following code, it work.
```js
const meta = [ {
  field: 'id', key: true, text: 'Product ID'
}, {
  field: 'name', key: false, text: 'Product Name'
}, {
  field: 'price', key: false, text: 'Product sssss'
} ];

export default class BasicTable extends React.Component {
  render() {
    return (
      <BootstrapTable data={ products } keyField='id'>
          {
            meta.map(m => {
              return <TableHeaderColumn key={ m.field } dataField={ m.field }>{ m.text }</TableHeaderColumn>;
            })
          }
      </BootstrapTable>
    );
  }
}
```

And I just want to know what error or message you see when you apply the ```key``` on ```TableHeaderColumn```. Because you said **You can't use key props on component**

Anyway, the TableHeaderColumn dont get the key prop and render on dom, I remember I saw some document. but if I misunderstand, please correct me with some reference. In addition, I think you should tell me firstly why you can't apply key on TableHeaderColumn?
