### ISSUE TITLE
Q: How can I add unique ID's to each row?

### ISSUE THREAD

**Issue by thevangelist** [AllenFang/react-bootstrap-table#859]
I'd like to add unique ID's to rows so I can programmatically clicking those, any tips?

**Comment by email2vimalraj** [comment]
Implement `linkCellFormatter` method as like this:

```javascript
// A simple formatter to turn the cell to a link
linkCellFormatter(cell, row) {
  return (<a onClick={this.navigateToProduct} id={row.id}>{cell}</a>);
}

// Navigates to the product where the id of the product will be coming from linkCellFormatter
navigateToProduct(event) {
  console.log(event.target.id);
}
```

And your table should look like this:

```javascript
<BootstrapTable data={data}>
  <TableHeaderColumn isKey dataField="id">ID</TableHeaderColumn>
  <TableHeaderColumn dataField="productName" dataFormat={this.linkCellFormatter}>Product</TableHeaderColumn>
</BootstrapTable>
```

Note `dataFormat` in the 2nd TableHeaderColumn which uses the `linkCellFormatter` to turn your cell into link which has the id attribute to your id field in your data.

Hope this answers your question.

**Comment by AllenFang** [comment]
@thevangelist, did your use any flux implementation?(ex: redux, mobx)

**Comment by thevangelist** [comment]
Yes I am using redux. I have a custom expandable sidebar --- so probably possibly the expandable rows feature will be a consideration as well.

**Comment by AllenFang** [comment]
maybe you can handle **add unique ID's to each row``` in your reducer? or initial state?

> so probably possibly the expandable rows feature will be a consideration as well.

You are lucky men, I just release ```v2.6.0``` and have the new feature for expandable row, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/expandRow.js) example. 

Let me know if you have any question
