### ISSUE TITLE
Automatic scroll to end of table

### ISSUE THREAD

**Issue by hermanfenderson** [AllenFang/react-bootstrap-table#860]
I am using react-bootstsp-table to show a list of items submitted by users in a form.
I am using "height" to show only a few rows but as long as users submit items they will get out of view.
Any way to make the table auto scroll to the end so that the more recent items will be displayed?
Of course I could feed the table in reverse order but it is much less intuitive.

**Comment by hermanfenderson** [comment]
I made it work... but I am not too proud of my workaround... I wrapped your component like this: 

import React from 'react';
import ReactDOM from 'react-dom';
import {BootstrapTable, TableHeaderColumn} from 'react-bootstrap-table';


class GestioneBolla extends React.Component {
componentDidMount()
  {
  	  this.node = ReactDOM.findDOMNode(this.refs.bsTable).childNodes[0].childNodes[1];
  }
  
  componentDidUpdate() {
	this.node.scrollTop = this.node.scrollHeight;
	}
  
    render ()
     {
     return (
        <BootstrapTable height='400' ref='bsTable'  data={this.props.data} striped hover>
          <TableHeaderColumn isKey dataField='key' hidden>Key</TableHeaderColumn>
          <TableHeaderColumn dataField='titolo' filter={ { type: 'TextFilter', delay: 100 } }>Titolo</TableHeaderColumn>
          <TableHeaderColumn dataField='autore'>Autore</TableHeaderColumn>
       <TableHeaderColumn width='50' dataFormat={ this.props.dataFormat }></TableHeaderColumn>
      </BootstrapTable>
       );
     }
 }
 
 export default GestioneBolla;

**Comment by AllenFang** [comment]
@hermanfenderson, I'll find the solution, and take your example as workaround is good currently.

**Comment by hermanfenderson** [comment]
@AllenFang sounds great. I appreciate that...

**Comment by AllenFang** [comment]
One question, scroll to the end of that table, I wanna know the actual position that you want to scroll

**Comment by hermanfenderson** [comment]
Up to the last row of the table...(cannot scroll any further)

**Comment by AllenFang** [comment]
hi, @hermanfenderson, fixed on ```v2.7.0```, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/basic/scroll-table.js#L25

the ```scrollTop``` props accept 'Top', 'Bottom' or a numeric value.

**Comment by hermanfenderson** [comment]
Great!

**Comment by hermanfenderson** [comment]
I am afraid the problem is still there...
Tried with latest version...

**Comment by challapruthvi** [comment]
@AllenFang  I am trying to use scrollTop={'Bottom'} but it seems to not work (Or I am missing something here). I expected the vertical scroll bar on my page to move to the bottom of the screen / table when I have added " scrollTop " props but it just stays on the top as before (It remains same as before adding the scrollTop). 

Please verify this. Any working examples will be appreciated. Thank you.

**Comment by hermanfenderson** [comment]
No... AFAIK. 
I had to provide the solution you read above.

**Comment by AllenFang** [comment]
it's wired... it still work fine in my local. @hermanfenderson do you know when this still came back again? and what browser and `react-bootstrap-table` version you used? thanks

**Comment by hermanfenderson** [comment]
Unfortunately I changed to antd... Therefore I cannot give you any hint.


Il giorno mar 7 nov 2017 alle ore 14:01 Allen <notifications@github.com> ha
scritto:

**Comment by AllenFang** [comment]
@hermanfenderson anyway, thank you 👍

**Comment by hermanfenderson** [comment]
Your software is brilliant!
But now antd fits more than bootstrap overall my requirements....

Il dom 12 nov 2017, 07:46 Allen <notifications@github.com> ha scritto:

**Comment by challapruthvi** [comment]
@AllenFang  Hey I am still having problem while trying to use scrollTop. It is not working as expected on my end. I am using Google Chrome Browser and the react-bootstrap-table version is 4.1.1

I would really appreciate if you could look into this issue and it would be great if you can provide a couple of examples using scrollTop (may be assigining Bottom or a number to it). Thank you

**Comment by challapruthvi** [comment]
Hello @AllenFang I have done some debugging on why scrollTop was not getting set appropriately on my end. It turned out to be that when I have asynchronous way of fetching data and giving it to the table the scrollTop is not getting set.

**More Details:**
scrollTop method is being called in componentDidMount() in BootstrapTable.js so it happens to trigger the scrollTop only once after the table is mounted and later when I get my data asynchronously the table is getting rendered again and its not triggering the scrollTop method. Hope this info helps.
