### ISSUE TITLE
Module not found D:\Users\nrabbitt\WebstormProjects\search copy\node_modules\react/lib/ReactDOM

### ISSUE THREAD

**Issue by UX-Unicorn** [AllenFang/react-bootstrap-table#862]
I updated to 2.6.0 and am using react 15.4.1.  When webpack tries to bundle I am getting the following error.  Can anyone please help me with this?  If you need more information let me know. Thank you in advance.

ERROR in ./~/react-bootstrap-table/~/react-toastr/~/react-dom/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' D:\Users\nrabbitt\WebstormProjects\search copy\node_modules\react/lib/ReactDOM in D:\Users\nrabbitt\WebstormProjects\search copy\node_
modules\react-bootstrap-table\node_modules\react-toastr\node_modules\react-dom
 @ ./~/react-bootstrap-table/~/react-toastr/~/react-dom/index.js 3:17-46

**Comment by AllenFang** [comment]
hi @UX-Unicorn, could you remove node_module and install again?  it may related with #838

**Comment by UX-Unicorn** [comment]
That worked thanks
