### ISSUE TITLE
get row and cell attribute from a customized cell

### ISSUE THREAD

**Issue by qiusli** [AllenFang/react-bootstrap-table#864]
I have a table with multiple rows and in each row I have a customized cell element using dataformat, within that cell is a button. What I want to achieve is when I click on the button for a particularrow, I can also get the corresponding row/cell information. But what happens now is when I click on one of the button I get all rows' information (not actually the one I clicked on). I know I can achieve this by first selecting one row and then click on the button in that row but for better user experience I would prefer be able to click on the button directly wihtout selecting a row first. Any suggestions? Thanks.

**Comment by AllenFang** [comment]
I'm not sure what' you want actually, but this [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-format/react-column-format-table.js#L32) is that a ```dataFormat``` will pass ```cell``` and ```row``` as arguments to your customization function.

So if you want to get the cell data when you click a button in a cell, I think you can set a attribute on that button is about cell value.

Let me know if you still have questions :)
