### ISSUE TITLE
SelectRow breaks pagination

### ISSUE THREAD

**Issue by simonhock** [AllenFang/react-bootstrap-table#87]
Hi, 

I've been trying to use your react-bootstrap-table (which works pretty well, i got to say) but when i try to use the pagination and the checkbox row-select, the pagination does not work. No matter what i select in the dropdown, the table always shows the whole data. 

I'm using v1.1.1 due to the react version i use. (react @ 0.13.3)

Thanks in advance.

**Comment by AllenFang** [comment]
HI @simonhock , you means you select the pagination dropdown?

**Comment by simonhock** [comment]
yes, no matter what i select in the pagination dropdown, the table does not update.

The page selection (
![image](https://cloud.githubusercontent.com/assets/9982963/10610837/e00a8c68-7749-11e5-92da-0bd443989903.png) ) does update

**Comment by AllenFang** [comment]
did you see any error on console? or did you import Bootstrap javascript?

**Comment by simonhock** [comment]
i did import the bootstrap js, and the jQuery js that bootstrap js needs. i think i found where the problem comes from the usage of a dynamic pagination (paginate only if data size > x ) 


        pagination = { data.length > 10 }

**Comment by simonhock** [comment]
(confirmed)

**Comment by AllenFang** [comment]
so did you solve this problem?

**Comment by simonhock** [comment]
The problem comes only from the "dynamic pagination" i tried to do and does not come from row selection.

**Comment by AllenFang** [comment]
sorry, can you explain what is the "dynamic pagination", and is it <code>react-bootstrap-table</code>'s bug?

**Comment by simonhock** [comment]
i tried to only activate pagination when dataset has more then 10 items and to set table height accodringly to fit in the page as in the code below

      <BootstrapTable
        data={items}
        striped={true}
        hover={true}
        pagination={ items.length > 10 }
        height={ items.length > 10 ? 510 : false}
        selectRow={selectRowProps}
      > ...

**Comment by AllenFang** [comment]
OK, I understand, so anything issue or problem?

**Comment by simonhock** [comment]
No, thank you !
