### ISSUE TITLE
Change data in table when changing pages

### ISSUE THREAD

**Issue by kaustav1992** [AllenFang/react-bootstrap-table#870]
Hi,

I was taking a look at your custom pagination hook out here http://allenfang.github.io/react-bootstrap-table/example.html#pagination

I do not want to load all my data onto my table when I load my page. So when I change pages, I want to use the onPageChange() hook and the load the data based on the page number and size per page. Is there an option where I can load the data such that it displays the data only for that page.

Thanks,
Kaustav

**Comment by AllenFang** [comment]
hello @kaustav1992, I think remote mode is what you want, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-paging.js and https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-paging.js

Let me know if you have any question :)

**Comment by kaustav1992** [comment]
Hi,

So I'm able to fetch my data for different pages based on the page number but my value in the paginator is not changing although I change the page option in table options.

<img width="249" alt="screen shot 2016-12-06 at 3 14 06 pm" src="https://cloud.githubusercontent.com/assets/7247658/20948097/1422c318-bbc7-11e6-8d83-82e204ddc36c.png">
