### ISSUE TITLE
Custom filter drop down menu having check boxes to allow the user to select multiple values in filter 

### ISSUE THREAD

**Issue by hctslm** [AllenFang/react-bootstrap-table#871]
@Hi 

I am trying to add a custom filter drop down menu with check boxes  as below in custom filter.

<div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Dropdown Example
  <span class="caret"></span></button>
  <ul class="dropdown-menu">
    <li><input type="checkbox" /><a href="#">HTML</a></li>
    <li><input type="checkbox" /><a href="#">CSS</a></li>
    <li><input type="checkbox" /><a href="#">JavaScript</a></li>
  </ul>
</div>

In header the drop down menu is behind the table body when ever I click on drop down menu to open, so I am not able to filter the table.
I have tried with z-index and some other css but the list is not on top of table

See the below screen shot and give me a solution

Thanks in advance

**Comment by hctslm** [comment]
![capture](https://cloud.githubusercontent.com/assets/24388651/20913794/bae37fa2-bba0-11e6-85c3-8c30a0f9b789.PNG)

**Comment by hctslm** [comment]
![capture](https://cloud.githubusercontent.com/assets/24388651/20914023/65f10d1e-bba2-11e6-8151-6b95b5231260.PNG)

**Comment by AllenFang** [comment]
> Dropdown Example
> HTML
> CSS
> JavaScript

Sorry, the links is broken.

**Comment by hctslm** [comment]
bootstrap css drop down menu with check boxes inside list
http://www.w3schools.com/bootstrap/bootstrap_dropdowns.asp

**Comment by AllenFang** [comment]
ok, I'll check this out 👍

**Comment by AllenFang** [comment]
@hctslm, this is because bootstrap select menu is hidden on DOM, if you tuning the ```z-index``` is always not working. There's only one workaround is tuning the hight of the wrapper for custom filter,  like following:
```js
return (
      <div style={ { height: '90px' } }>
        <div className='dropdown'>
          <button className='btn btn-primary dropdown-toggle' type='button' data-toggle='dropdown'>Dropdown Example
          <span className='caret'></span></button>
          <ul className='dropdown-menu'>
            <li><a href='#'>HTML</a></li>
            <li><a href='#'>CSS</a></li>
            <li><a href='#'>JavaScript</a></li>
          </ul>
        </div>
      </div>
    );
```
