### ISSUE TITLE
sizePerPageList Problem

### ISSUE THREAD

**Issue by wy19900814** [AllenFang/react-bootstrap-table#873]
Hi Allen,

The sizePerPageList option didn't work for me. I know it is caused by I'm not including bootstrap.js
But as a react project, I really want to use npm to manage all files, so lets try to fix this bug.

I checked the element that affect sizePerPageList. It is in the picture below. There's a span called dropdown.
![screen shot 2016-12-06 at 3 59 48 pm](https://cloud.githubusercontent.com/assets/2552144/20949249/3a68e880-bbcd-11e6-9d7b-1fdf090b25cc.png)

I believe this is a bootstrap component. Bootstrap should handle this onClick event, it toggles an "open" class when user clicking sizePerPage Dropdown list.
So originally, the class name is "dropdown", after one click, it is "dropdown open", if you click other place or click itself or choose a value, it comes back to "dropdown".

Now the problem is, if I don't include bootstrap.js, this function won't work. But in my project I've already include a component called "react-bootstrap" which is bootstrap build for react. Even if I didn't had that module, doing <script src="XXXXX.js"></script> in react is inappropriate.

So I just put some candidate solutions here for consideration.
1) Include bootstrap.js in react-bootstrap-table module, so that developer don't need to do that again.
2) Maybe we can write code to control the dropdown event, but I thought it might be extra work and not necessary.

Anyway, thanks for the work. It's a great project.

Best,
Yang

**Comment by AllenFang** [comment]
HI Yang

> Now the problem is, if I don't include bootstrap.js, this function won't work. But in my project I've already include a component called "react-bootstrap"

Include ```react-bootstrap``` cant solve this issue absolutely.

Currently, you should include ```bootstrap.js```, and I know it wired. So in ```v3.0.0```, I have plan to remove this dependency and I've done it on ```v3.0.0-beta.2```

so you can try the beta version for ```v3.0.0```, there're some developer already try this work without any ```bootstrap.js``` and ```jquery```. 

BTW, ```v3.0.0``` only focus on component customization,  so no any exist api changed. You can give a try.  check #497 

Feel free to discuss with me 👍
