### ISSUE TITLE
Pagination: when I set the options, the first page and last page button disappear

### ISSUE THREAD

**Issue by caesarjuly** [AllenFang/react-bootstrap-table#874]
How to make them work as normal? Is there an option?

```javascript
render: function() {
    const options = {
      pageStartIndex: 1,
      sizePerPage: 20,
      prePage: '上一页',
      nextPage: '下一页',
      firstPage: '首页',
      lastPage: '末页',
      paginationShowsTotal: this.renderShowsTotal,
      hideSizePerPage: true,
      paginationSize: 6
    };
    return (
      <BootstrapTable data={this.props.data} ref='table' pagination options={options} striped hover>
        {this.props.children}
      </BootstrapTable>
    );
  }
```

**Comment by AllenFang** [comment]
@caesarjuly, you assign a unknow sizePerPage as 20, but there no 20 in sizePerPage list default. The sizePerPage list default value is [ 10, 25, 30, 50 ], but you can custom it by ```sizePerPageList```. 

Anyway, I'll find some solution to improve this condition

**Comment by caesarjuly** [comment]
@AllenFang Thanks for ur quick reply. So by now if I want to make them work, I have to set the sizePerPage value in the sizePerPage list.
Let the two options be independent should be a better way :).

**Comment by caesarjuly** [comment]
@AllenFang I try to set the options as u mentioned above. Nor does this work.
```javascript
    const options = {
      pageStartIndex: 1,
      sizePerPage: 20,
      prePage: '上一页',
      nextPage: '下一页',
      firstPage: '首页',
      lastPage: '末页',
      paginationShowsTotal: this.renderShowsTotal,
      hideSizePerPage: true,
      paginationSize: 6,
      sizePerPageList: [
        {
          text: '10', value: 10
        },
        {
          text: '20', value: 20
        },
        {
          text: '30', value: 30
        },
        {
          text: 'All', value: this.props.data.length
        }
      ]
    };
```

**Comment by AllenFang** [comment]
There's something wrong, I'll check this out. Thanks.

**Comment by AllenFang** [comment]
@caesarjuly, sorry for my misunderstand, as I know, there's no any issue there, if you dont see the first and last page, which means the pagination list include all the page number, for example:

you have 70 rows and 20 as your size per page, so you you will see four pages: 1, 2, 3, 4
like you configuration, you configure ```paginationSize``` as 6, but only for page here, 
which means we dont need the first and last page, because you can see page 1 and page 4 in pagination list.

if you configure the ```sizePerPage``` as 10, you will see the first and last page.

**Comment by AllenFang** [comment]
BTW, if you use ```v3.0.0-beta.3```, we support ```withFirstAndLast``` in ```options``` props, if you give true, the first and last page always show no matter the first and last appear on pagination list.

But this version still on beta, maybe a little unstable. 👍

**Comment by caesarjuly** [comment]
@AllenFang 
![screen shot 2016-12-23 at 5 26 56 pm](https://cloud.githubusercontent.com/assets/927521/21450806/0c13d7f4-c935-11e6-9e43-db314713674e.png)
As the picture shows above, there are hundreds of pages in my pagination. However, the first and last page don't appear. My configure is the same as I mentioned before.
My version is v3.0.0-beta.2. Can u show an working example for me, thank u very much.

**Comment by AllenFang** [comment]
@caesarjuly, this is a bug since ```v3.0.0-beta.1```, I've fixed on https://github.com/AllenFang/react-bootstrap-table/releases/tag/v3.0.0-beta.5

so now, you don't need to configure ```withFirstAndLast```, its default value it true, and the pagination will show the first and last page.

**Comment by caesarjuly** [comment]
really appreciate it 👍
