### ISSUE TITLE
Scrolling table rows with fixed header

### ISSUE THREAD

**Issue by Ksushik** [AllenFang/react-bootstrap-table#875]
Hello, I can't find the way to make my react-bootstrap-table scrollable with fixed header, is it possible to configure such behaver? Thank's ahead

**Comment by AllenFang** [comment]
HI @Ksushik, it's a default behavior, just you set the ```height``` on ```BootstrapTable```, if the data is too long, there's a scroll bar appear.  👍

**Comment by sidewayskumara** [comment]
Wondering if there is any way to incorporate inertial scroll for mobile devices when using this solution

**Comment by 9005** [comment]
@AllenFang : I have requirement where on scroll down i need to have table headers fixed. Does react bootstrap table provide any options for that?
