### ISSUE TITLE
custom cell edit mode can we have on keyboard events like pressing 'tab' key 'enter' key 

### ISSUE THREAD

**Issue by hctslm** [AllenFang/react-bootstrap-table#876]
I am having a requirement of table inline editing, I need to allow the user to edit row wise from one cell to other by pressing tab (and the previous cell content should be saved when user moved from one cell to another cell by pressing tab)

Is there any solution to add multiple event to 
const cellEditProp = {
		  mode: ['click','keydown','keypress']
		};
If we achieve this it will a big help to user without using mouse he can edit the table with in less time

Thanks in advance

**Comment by AllenFang** [comment]
@hctslm, thanks for advice, I know this feature will be useful, but currently I have no much time to do this, so PR is welcome :)

If I have time in the future, I'll back to support this feature 👍 
Thanks

**Comment by samfisher908** [comment]
Is anyone working on this right now? I'm planning on giving it a try for a project I'm working on right now and am happy to contribute my work to the codebase if everything goes smoothly.

**Comment by AllenFang** [comment]
@samfisher908, I think there's no one work on it and this issue may start to handle after v3.0.0 release for me(current still on beta), so you can take a look for codebase and let me know if you have any question.

PR is welcome, thank you :)

**Comment by madeinfree** [comment]
Sorry @samfisher908, I didn't see your comment on this work.., #1015 is my solution to resolve this features, if you would like to PR, you just sent your PR welcome :D

**Comment by madeinfree** [comment]
duplicate #693 ?

**Comment by AllenFang** [comment]
Forgot to close it and already fixed on `v3.0.0`
