### ISSUE TITLE
Save data only on table in browser, not in the original data object

### ISSUE THREAD

**Issue by hctslm** [AllenFang/react-bootstrap-table#879]
Hi Allen,

I am using custom editor on each cell in my table to allow the user to modify the data,
OnBlur of my custom element I am calling updateData method to show the updated value in the browser

I will have a button **save to db** ,after clicking on that, I need to compare original values and the user modified values with proper validation and if he follows all the rules, then only I need to replace the original data with user latest data

But with
updateData() {
    this.props.onUpdate(this.state.name);
  }
the original object is modifying every time the user changes the value, So I need to stop this functionality,  it should update only on cell value in browser not the actual object 

How can I do this, Is there any other function to update content only in cell rather than in all places

All my issues are very important and I need a solution as soon as possible. I didn't have more time to wait
Please give any solution 

Thanks in advance

**Comment by AllenFang** [comment]
@hctslm, you can integrate with flux(redux, mobx) and enable ```remote``` on ```BootstrapTable```, which means you need to control all the data change(ex: sorting, paging, updating, insert, delete etc) instead of ```react-bootstrap-table``` itself. In this mode, you can do anything on your program.
