### ISSUE TITLE
an option for fixed/sticky table header?

### ISSUE THREAD

**Issue by DanielSmith** [AllenFang/react-bootstrap-table#880]
Am looking for an example that illustrates a fixed table header with react-bootstrap-table.  I'm surprised it is not an option (or is it, and I missed it?)  Just seeing if the option is there before I have to go to some pure css override route..

**Comment by AllenFang** [comment]
hi @DanielSmith, sorry for lately reply, check #875.  It's actually not a options, in the default, ```react-bootstrap-table``` display all the data without fixed header, because ```height``` is auto by default. if you give a ```height``` the header will fixed when data is too long.

**Comment by DanielSmith** [comment]
thanks for following up.  Would be good to document that.

**Comment by AllenFang** [comment]
ok, got it 👍

**Comment by JohnVLinton** [comment]
I'm still seeing issues with fixed height of say 800 for "react-bootstrap-table": "^4.3.1".

What I see is a footer that stays fixed now relative to top of table, but the whole thing (including many more rows of data) scrolls the header off the screen (and the footer as well).  So if first screen looks like this:

header
data
data
data
....
data
data
data
footer
data
data
data
data

Then the second screen is just further down all data from lower in the table with neither header nor footer (as they scrolled off top).
