### ISSUE TITLE
Question: updateData exception with custom editor

### ISSUE THREAD

**Issue by elosoman** [AllenFang/react-bootstrap-table#882]
I recently found your package ... kudos! Anyway I have a PriceEditor based on your example. I receiving this exception after the updateData call in the PriceEditor. 

`Uncaught Error: Objects are not valid as a React child (found: object with keys {cost, players, hours, fixed, fixedPerHour, playerFixed, playerPerHour}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `TableBody`.`

Otherwise the editor works as expected although the exception is causing follow on functionality to fail. It would seem that the object being returned is the state of the PriceEditor. Not sure what i missed. Suggestions. Thanks

**Comment by AllenFang** [comment]
@elosoman, sorry for lately reply, could you please show me your code? Thanks

**Comment by elosoman** [comment]
It is pretty much a clone of the PriceEditor example but with 4 states to compute the price.

`class PriceEditor extends React.Component {
  constructor(props) {
    super(props);
    this.updateData = this.updateData.bind(this);

    let type = 'fixed';
    let cost = this.props.row.cost;
    let players = this.props.row.players;
    let hours = this.props.row.hours;
    let fixed = this.props.row.fixed;
    let fixedPerHour = this.props.row.fixedPerHour;
    let playerFixed = this.props.row.playerFixed;
    let playerPerHour = this.props.row.playerPerHour;

    if (this.props.row.fixed && this.props.row.fixed > 0) {
      type = 'fixed';
    }
    if (this.props.row.fixedPerHour && this.props.row.fixedPerHour > 0) {
      type = 'fixedPerHour';
    }
    if (this.props.row.playerFixed && this.props.row.playerFixed > 0) {
      type = 'playerFixed';
    }
    if (this.props.row.playerPerHour && this.props.row.playerPerHour > 0) {
      type = 'playerPerHour';
    }

    this.state = {
      type, players, hours,
      cost, fixed, fixedPerHour, playerFixed, playerPerHour
    };
  }

  componentWillReceiveProps(nextProps) {
    console.log({nextProps});
  }

  focus() {
    this.refs.inputRef.focus();
  }

  cancel() {
    this.props.onKeyDown({ keyCode: 27 });
  }

  updateData() {
    let cost = 0;
    const update = {
      cost,
      players: 0,
      hours: 0,
      fixed: 0,
      fixedPerHour: 0,
      playerFixed: 0,
      playerPerHour: 0,
    };

    if (this.state.type === 'fixed') {
      update.fixed = parseFloat(this.state.fixed);
      cost = update.fixed; }
    else if (this.state.type === 'fixedPerHour') {
      update.fixedPerHour = parseFloat(this.state.fixedPerHour);
      update.hours = parseFloat(this.state.hours);
      cost = update.hours * update.fixedPerHour; }
    else if (this.state.type === 'playerFixed') {
      update.playerFixed = parseFloat(this.state.playerFixed);
      update.players = parseInt(this.state.players, 10);
      cost = update.players * update.playerFixed; }
    else if (this.state.type === 'playerPerHour') {
      update.playerPerHour = parseFloat(this.state.playerPerHour);
      update.players = parseInt(this.state.players, 10);
      update.hours = parseFloat(this.state.hours);
      cost = update.players * update.hours * update.playerPerHour; }

    update.cost = Math.round(cost * 100) / 100;

    this.props.onUpdate(update);
  }

  render() {
    return (
      <span>
        <select ref='inputRef' value={this.state.type}
          onChange={(ev) => this.setState({ type: ev.currentTarget.value })}
        >
          <option key="fixed" value="fixed">Fixed Cost</option>
          <option key="fixedPerHour" value="fixedPerHour">Cost/Hour</option>
          <option key="playerFixed" value="playerFixed">Cost/Player</option>
          <option key="playerPerHour" value="playerPerHour">Cost/Player/Hour</option>
        </select>
        <br/>
        {/* <pre>{JSON.stringify(this.state, null, 2)}</pre> */}

        {this.state.type === 'fixed' &&
          <span>
            $<input ref='fixed' type="number"
              className={ ( this.props.editorClass || '') + ' form-control editor edit-text' }
              style={{ display: 'inline' }}
              value={this.state.fixed}
              onKeyDown={ this.props.onKeyDown }
              onChange={(ev) => this.setState({ fixed: ev.currentTarget.value })} />
          </span>
        }

        {this.state.type === 'fixedPerHour' &&
          <span>
            <input ref='hours' type="number"
              className={ ( this.props.editorClass || '') + ' form-control editor edit-text' }
              style={{ display: 'inline', width: '75px' }}
              value={this.state.hours}
              onKeyDown={ this.props.onKeyDown }
              onChange={(ev) => this.setState({ hours: ev.currentTarget.value }) } />
            {' '} Hours
            <br/>
            @ {' '}
            <input ref='fixedPerHour' type="number"
              className={ ( this.props.editorClass || '') + ' form-control editor edit-text' }
              style={{ display: 'inline', width: '75px' }}
              value={this.state.fixedPerHour}
              onKeyDown={ this.props.onKeyDown }
              onChange={(ev) => this.setState({ fixedPerHour: ev.currentTarget.value }) } /> $/Hour
          </span>
        }

        {this.state.type === 'playerFixed' &&
          <span>
            <input ref='players' type="number"
              className={ ( this.props.editorClass || '') + ' form-control editor edit-text' }
              style={{ display: 'inline', width: '75px' }}
              value={this.state.players}
              onKeyDown={ this.props.onKeyDown }
              onChange={(ev) => this.setState({ players: ev.currentTarget.value }) } />
            {' '} Players
            <br/>
            @ {' '}
            <input ref='playerFixed' type="number"
              className={ ( this.props.editorClass || '') + ' form-control editor edit-text' }
              style={{ display: 'inline', width: '75px' }}
              value={this.state.playerFixed}
              onKeyDown={ this.props.onKeyDown }
              onChange={(ev) => this.setState({ playerFixed: ev.currentTarget.value }) } /> $/Hour
          </span>
        }

        {this.state.type === 'playerPerHour' &&
          <span>
            <input ref='players' type="number"
              className={ ( this.props.editorClass || '') + ' form-control editor edit-text' }
              style={ { display: 'inline', width: '75px' } }
              value={ this.state.players }
              onKeyDown={ this.props.onKeyDown }
              onChange={(ev) => this.setState({ players: ev.currentTarget.value }) } />
            {' '} Players
            <br/>
            <input ref='hours' type="number"
              className={ ( this.props.editorClass || '') + ' form-control editor edit-text' }
              style={{ display: 'inline', width: '75px' }}
              value={this.state.hours}
              onKeyDown={ this.props.onKeyDown }
              onChange={(ev) => this.setState({ hours: ev.currentTarget.value })} />
            {' '} Hours
            <br/>
            @ {' '}
            <input ref='playerPerHour' type="number"
              className={ ( this.props.editorClass || '') + ' form-control editor edit-text' }
              style={{ display: 'inline', width: '75px' }}
              value={this.state.playerPerHour}
              onKeyDown={ this.props.onKeyDown }
              onChange={(ev) => this.setState({ playerPerHour: ev.currentTarget.value }) } /> $/Hour
          </span>
        }
        <br/>

        <button className='btn btn-success btn-xs textarea-save-btn' onClick={ this.updateData }>
          save
        </button>

        {' '}

        <button className='btn btn-danger btn-xs textarea-save-btn' onClick={this.cancel}>
          cancel
        </button>
      </span>
    );
  }
}`

It is linked to the cell using

`customEditor={{
  getElement: (onUpdate, props) => (
    <PriceEditor onUpdate={onUpdate} {...props}/>
  ),
  customEditorParameters: {},
}}
`

**Comment by elosoman** [comment]
sorry ... that code block is ugly.

**Comment by elosoman** [comment]
Please forgive me for the nube question ... it looks as though this exception is being thrown in the dataFormat function on the table column. It would appear that when using the custom editor the row dataField value is an object containing the state of customEditor and not an atomic value. Sorry for the confusion.
