### ISSUE TITLE
Space Between Table Head and Table Body 

### ISSUE THREAD

**Issue by robbieyng** [AllenFang/react-bootstrap-table#883]
I cannot figure out how to remove the space between my table head and the table body, or where it is coming from...It looks like it is a 20px bottom margin on `<table class="table table-hover table-condensed">`

![image](https://cloud.githubusercontent.com/assets/9204282/21070385/02fbb59e-be52-11e6-9788-04432a2248de.png)

![selection_018](https://cloud.githubusercontent.com/assets/9204282/21070267/7fd68d20-be50-11e6-95a3-bbe444b67682.png)

Thanks for taking a look!

**Comment by AllenFang** [comment]
@robbieyng, you forgot to include the css, the css files under [here](https://github.com/AllenFang/react-bootstrap-table/tree/master/dist). 👍

**Comment by sopheakreth** [comment]
Hi Allen, 
These files are many. so how to import? 
We import into index.html or anywhere?

**Comment by AllenFang** [comment]
The css files you can found in ```dist``` folder, 
```react-bootstrap-table-all.min.css``` include ```toastr```, the other one is not, I recommend you add ```react-bootstrap-table-all.min.css```.

Let me know if you still have any problems

**Comment by prajapati-parth** [comment]
@AllenFang This works when importing css to HTML file using link tag. I tried importing the css in a component where I'm using react-bootstrap-table by doing so 
ES6:
`import './react-bootstrap-table.min.css'`
ES5:
`require('./react-bootstrap-table.min.css')`
But none of the above works :cry:

**Comment by robbieyng** [comment]
@prajapati-parth did you move the css file into your component's root folder? In most cases you'll have to import like this: `import 'react-bootstrap-table/css/react-bootstrap-table.css';`

**Comment by prajapati-parth** [comment]
@robbieyng Yes I did! I can assure that the file is definitely present as I have a webpack watcher running, which shown an error if it doesn't find the file.

**Comment by AllenFang** [comment]
I think there's something wrong but I'm not sure what happen, I can help you if you have small repo, but please give some instructions for me to run your project, thanks

**Comment by prajapati-parth** [comment]
Yes sure Allen. Here's the demo repo https://github.com/prajapati-parth/react-bootstrap-table-demo. 
I've created a detailed README file for easiness. 

// This doesn't work
As you can see [here](https://github.com/prajapati-parth/react-bootstrap-table-demo/blob/master/index.html#L7), I've commented out the react-bootstrap-table.min.css in index.html and instead imported it in [here](https://github.com/prajapati-parth/react-bootstrap-table-demo/blob/master/App.js#L3)

// This works
But if you just comment out the [import line](https://github.com/prajapati-parth/react-bootstrap-table-demo/blob/master/App.js#L3) in App.js and uncommnet the [link tag](https://github.com/prajapati-parth/react-bootstrap-table-demo/blob/master/index.html#L7) in index.html everything works. 

Thanks for investing your time here Allen. :+1:

**Comment by prajapati-parth** [comment]
As per @robbieyng comment above, I've even tried moving the css file to my root folder and did an import accordingly, but even that doesn't work.

**Comment by AllenFang** [comment]
@prajapati-parth, I've some comments on your repo, https://github.com/prajapati-parth/react-bootstrap-table-demo/issues/1, please have a look, thanks

**Comment by prajapati-parth** [comment]
@AllenFang Great! It worked! I didn't know I was missing the obvious.

**Comment by prajapati-parth** [comment]
@AllenFang Just a word of concern, what would be the best practice here? To move the react-bootstrap-table css to somewhere in src and then import or directly import from node_modules/react-bootstrap-table/dist.

**Comment by AllenFang** [comment]
I think both is ok for me, but if you move css into your folder, you need to remember to update it if version upgraded.

So import css directly from node_modules will be better, and you can use webpack `resolve` or `alias` to import css without `node_modules` explicit, like

import 'react-bootstrap-table/dist/react-bootstrap-table-all.min.css';

**Comment by prajapati-parth** [comment]
@AllenFang Right! That seems fair. :+1:
