### ISSUE TITLE
Add SerialColumn

### ISSUE THREAD

**Issue by cipulaida** [AllenFang/react-bootstrap-table#884]
Hi,

Wondering how to add Serial Column on the table, just like SerialColumn class on Yii 2 GridView.

Any idea ?

**Comment by AllenFang** [comment]
@cipulaida, sorry for lately reply

> Yii 2 GridView

I'm not familiar with that, but I think if you data have no any column could be presented as key column, you can generate it by yourself, and you can hide it if you want.

so I wont support this feature if there're too many requests are like this one.

Thanks, feel free to discuss with me.
