### ISSUE TITLE
Layout error while expanding row in table has hidden column.

### ISSUE THREAD

**Issue by droyuki** [AllenFang/react-bootstrap-table#885]
This error occurs when we have a hidden column and expand row simultaneously.

In ExpandRow example, I add a hidden property in a Table Header Column:
 ``<TableHeaderColumn dataField='price' hidden>``
when we expand a row, hidden column will become a empty block just like the screenshot below:

![](http://i.imgur.com/r7cl4Xxr.png)

**Comment by AllenFang** [comment]
@droyuki, thanks, I'll check this out !

**Comment by AllenFang** [comment]
Fixed on ```v2.7.1```
