### ISSUE TITLE
Row select without a radio button

### ISSUE THREAD

**Issue by jabberwo** [AllenFang/react-bootstrap-table#887]
Be nice to have the single row select functionality w/o requiring a radio button.  I don't wish to have one in my design, just the selection background color.

**Comment by droyuki** [comment]
render() {
      const selectRow = {
        mode: 'radio',
        bgColor: '#fefefe'
        hideSelectColumn: true
      };
      return(
        <BootstrapTable
          data={ data }
          selectRow={ selectRow }>
          //...
        </BootstrapTable>
      );
    }
you can set `hideSelectColumn: true` if you don't want to show a radio button.
[Here is the document](http://allenfang.github.io/react-bootstrap-table/docs.html#hideSelectColumn)

**Comment by jabberwo** [comment]
Thanks!

Can you point me to doc for custom cell rendering, or whatever it's called do I can put an image in a cell and sort on a data value (that's also used to pick the image)?

Chuck

**Comment by droyuki** [comment]
maybe you can use [dataFormat](http://allenfang.github.io/react-bootstrap-table/docs.html#dataFormat) to customize your data value.

**Comment by jabberwo** [comment]
Thanks again!  I'll try that in the morning.  I didn't see that in my first pass through the doc.  

Chuck

**Comment by AllenFang** [comment]
thanks your answer @droyuki !!
