### ISSUE TITLE
Select filter with multiple selection option

### ISSUE THREAD

**Issue by hctslm** [AllenFang/react-bootstrap-table#888]
Hi Allen

I need a column wise select filter, but it should allow the user to filter with multiple options
Can we have multiple=true and filter with multiple values at a time in select filter

So I am writing a custom filter with check boxes inside, for this I am using bootstrap drop down menu css, but as you said we need to give height to that div then only it will be visible. but it's not looking as the header is having so much height

Could you have any solution for my requirement, please provide, if you have any solution or at least the approach, how to do

Thanks in advance

**Comment by AllenFang** [comment]
yap, the best solution is that we support the multiple select filter, close this cause of duplicated with https://github.com/AllenFang/react-bootstrap-table/issues/832.

BTW, sorry for lately fixing, I'm busy on work, so PR is welcome 👍
