### ISSUE TITLE
Enhancement request for a way to indicate columns that are editable.

### ISSUE THREAD

**Issue by rrameshkumar76** [AllenFang/react-bootstrap-table#890]
I tried to add an image to the column header to indicate that its editable. This renders as needed but does throw error below. 

It only accepts strings as headers. Is there any other way to indicate that only particular columns are editable in the table column headers?

**Error Message:**
warning.js:36 Warning: Failed prop type: Invalid prop `columnName` of type `array` supplied to `NumberFilter`, expected `string`.
    in NumberFilter (created by TableHeaderColumn)
    in TableHeaderColumn (created by ManagedTable)

**Code:**
  
[code.txt](https://github.com/AllenFang/react-bootstrap-table/files/649656/code.txt)

**Comment by AllenFang** [comment]
@rrameshkumar76, sorry for current newest version, you cant do it, we only allow you to add class on header. BTW, I wanna support to custom the header column in the ```v3.0.0```, there're some people also ask this issue, and we still working. Thanks

**Comment by rrameshkumar76** [comment]
That would be awesome, Thanks for the response.

**Comment by AllenFang** [comment]
@rrameshkumar76, I add a new props called ```headerText```, if the child in ```<TableHeaderColumn>``` is not a pure text, please add ```headerText``` props on ```<TableHeaderColumn>``` for describing this column!

for example, this is a simplest case:
```<TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>```

if a DOM or JSX in ```TableHeaderColumn```, you should give a ```headerText``` to avoid this warning:
```<TableHeaderColumn dataField='price' headerText='Product Price'><p>Product Price</p></TableHeaderColumn>```

**Comment by rrameshkumar76** [comment]
Thanks for getting this added so quickly. For now i am unable to use this because of facin issue(npm ERR! 404 '@allenfang/react-toastr' is not in the npm registry.).
I do see open issue mentioned in https://github.com/AllenFang/react-bootstrap-table/issues/898
