### ISSUE TITLE
Support multiple rows (grouped) for table heads?

### ISSUE THREAD

**Issue by cheapsteak** [AllenFang/react-bootstrap-table#891]
Hi,

I really want this:

![image](https://cloud.githubusercontent.com/assets/743976/21154654/f4c8cdac-c123-11e6-8a9a-63f7cc18b9a8.png)

```html
<table>
  <thead>
    <tr>
      <th rowspan="2">---</th>
      <th colspan="3">AAA</th>
      <th colspan="2">BBB</th>
    </tr>
    <tr>
      <th>aa1</th>
      <th>aa2</th>
      <th>aa3</th>
      <th>bb1</th>
      <th>bb2</th>
    </tr>
  </thead>
</table>
```

https://jsfiddle.net/1o6zmp9v/1/

When there are a lot of columns it is useful to be able to group them somehow

I don't believe this is currently possible?

**Comment by AllenFang** [comment]
sorry for lately reply, @cheapsteak, we currently not support this feature yet and there's a PR can fix it, check https://github.com/AllenFang/react-bootstrap-table/pull/748  but it still have a lots of bug need to fix...

**Comment by cheapsteak** [comment]
Ah, didn't realize there was already a PR for this. Awesome!

**Comment by AllenFang** [comment]
@cheapsteak, that's fine, but it really need some time, so don't have much expectation ;(  But I'll work hardly to make this project being well.

**Comment by AllenFang** [comment]
@cheapsteak, this feature was support on ```v2.8.0```, check [example](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/column-header-span) here 👍

**Comment by cheapsteak** [comment]
Sweet, thanks! :D
