### ISSUE TITLE
columnClassName attr is cleared when customEditor is enabled

### ISSUE THREAD

**Issue by jsangilve** [AllenFang/react-bootstrap-table#892]
I noticed that using `customEditor` attribute of `TableHeaderColumn`, when a cell gets into edit mode (`customEditor` is enabled), the `<td>`s `className` defined by `columnClassName` attribute is cleared. Once the cell isn't being edited anymore, the className is restored.

```jsx
<TableHeaderColumn
  key={'column-' + h.id}
  columnClassName={(h.cellEditor) ? 'editable-td': ''}
  customEditor={this.formatEditor(h.id, h.cellEditor)}>
  {h.label}
</TableHeaderColumn>
```

Is there any way to keep the `className` in edit mode or pass a `className` to the `<td>` element when cell is in edit mode?

**Comment by AllenFang** [comment]
@jsangilve, I'll improve it, actually it's not lost or override the classname on editing, because it's different component between the normal cell and editing cell. There're some solution, but as my consideration, I'll prefer to add a new props called ```editColumnClassName``` to separate from the ```columnClassName```.

**Comment by jsangilve** [comment]
@AllenFang sounds good. Thanks for adding this feature!

**Comment by AllenFang** [comment]
Fixed on ```v2.7.1```, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/style/edit-td-class-table.js#L32) example 👍

**Comment by jsangilve** [comment]
@AllenFang I was wondering if this `editColumnClassName` property could also make it to branch v3.0.0. Unless you have an alternative in mind, I could PR to v3.0.0-dev if you want.

**Comment by AllenFang** [comment]
@jsangilve, https://github.com/AllenFang/react-bootstrap-table/releases/tag/v3.0.0-beta.6  check this out.

**Comment by jsangilve** [comment]
@AllenFang you rock man!
