### ISSUE TITLE
row selection is not working with pagination

### ISSUE THREAD

**Issue by hctslm** [AllenFang/react-bootstrap-table#893]
Hi Allen,

I have pagination and row selection in my table, after going to some page ex 3 page when I select a row it giving me the previous record or previous row as selected, It's happening only some times when page is changed and selecting different rows in less span of time. 

How can i fix this, it's an important fix need to be done from my end 

Thanks in advance

**Comment by AllenFang** [comment]
@hctslm, it wired that I never saw. Could you please show me how to reproduce it?  and give me a minimal and simple code. Thank you

**Comment by AllenFang** [comment]
Reopen it until there's a example which can reproduce.
