### ISSUE TITLE
how to increase width of row selection custom image cell 

### ISSUE THREAD

**Issue by hctslm** [AllenFang/react-bootstrap-table#894]
Hi Allen,

I have replaced the radio button for row selection with my custom image. I need to increase the width of that cell, how can I do this

Thanks

**Comment by hctslm** [comment]
Hi Allen,

This is an important fix need to be done as soon as possible, please give reply

Thanks

**Comment by AllenFang** [comment]
@hctslm, it's impossible for increase the width of selection column, we only support the customization for the inside of selection column. But ad my consideration, I think you can try to control the width by your css.
