### ISSUE TITLE
Add ability to give a component to render the selection column (header and rows)

### ISSUE THREAD

**Issue by jbrey** [AllenFang/react-bootstrap-table#895]
Is it possible to add an option to give the renderer of the selection column. Indeed I have difficulty to style the checkboxes or radios (on IE and Firefox) because there's only an input without label (and these browsers don't allow :before and :after on inputs)

Giving the ability to render by ourselves these cells would give me the ability to apply our styles and also allow to add our accessibility information.

**Comment by AllenFang** [comment]
hello @jbrey, check this [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/custom-multi-select-table.js). Let me know if you still have question.

**Comment by jbrey** [comment]
I didn't find this example... It should be ok then.
Thanks
