### ISSUE TITLE
Custom function before doing sorting,filtering and pagination

### ISSUE THREAD

**Issue by hctslm** [AllenFang/react-bootstrap-table#896]
Hi Allen,

I have a requirement that
When the user clicked on sort button to sort on a particular column or click on pagination to go another page or click select filter on a particular column, before getting changes in the table like sorting, pagination or filtering,  I need to check that whether it should be done or not for my condition and then only I need to allow the functionality

So how to call a custom function before re rendered the changes

Please give me reply it is a high priority to me

Thanks

**Comment by AllenFang** [comment]
@hctslm, 
for sorting: ```onSortChange``` in ```options``` props, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/sort-hook-table.js#L33)

for selection: ```onSelect``` in ```selectRow``` props, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/select-validation-table.js#L43)

for filter: check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-filtering.js#L67)

for pagination: check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-paging.js#L30)
