### ISSUE TITLE
Expanded rows problems

### ISSUE THREAD

**Issue by OlegVach** [AllenFang/react-bootstrap-table#897]
I want expand row by clicking on icon, but when I cliked for another columns expand works too. How I can disable click for each columns exclude my column with icon??? I saw you delete  enableExpandRow props from component?

**Comment by AllenFang** [comment]
> I saw you delete enableExpandRow props from component?

where?

The click event for expandable row is not restricts on any column, is on the row. And you said you click a icon for expanding a row, but where's the icon?  in your custom column?

**Comment by OlegVach** [comment]
Sorry, I don`t saw that is not you page https://github.com/droyuki/react-bootstrap-table/commit/6d898b9b0942155e3ca4ab8b95ddcf8a1dfc01fd

Yeah I have icon in my custom column.
![1](https://cloud.githubusercontent.com/assets/17565510/21255655/e79272b0-c375-11e6-9fc0-e0753db29477.png)

**Comment by AllenFang** [comment]
@OlegVach, I'll find the solution for triggering expandable row by specified column. Anyway, you icon column is the customization from selection column?, could you please show me your code?
Thank you

**Comment by AllenFang** [comment]
@OlegVach, check ```v2.7.1```, the expand row trigger by column is supported, https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/expand-row-by-column.js#L74-L84

Let me know if you still have question.

**Comment by OlegVach** [comment]
Yeah, this resolve my problem, thank you =)

**Comment by hi-bazinga** [comment]
"Expand by column" cannot work if the table is configured with "selectRow", could you help look at this?

**Comment by AllenFang** [comment]
@hi-bazinga, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/expand-row-with-selection.js#L78

**Comment by hi-bazinga** [comment]
@AllenFang Sorry for not describing it clearly. "Expand by row" works well with "selectRow" configured, but "Expand by **column**" cannot, here is my code in "render()":

```
    const options = {
      expandRowBgColor: 'rgb(242, 255, 163)',
      expandBy: 'column'
    };

    const selectRow = {
      mode: 'checkbox',
      clickToSelect: false,  // click to select, default is false
      clickToExpand: true  // click to expand row, default is false
    };

    return (
      <BootstrapTable data={ products }
        options={ options }
        expandableRow={ this.isExpandableRow }
        expandComponent={ this.expandComponent }
        selectRow={ selectRow }
        search>
        <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
        <TableHeaderColumn dataField='name' expandable={ false }>Product Name</TableHeaderColumn>
        <TableHeaderColumn dataField='price' expandable={ false }>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
```

What I expect is clicking on specific columns to expand the row, and click the checkbox before the row to select this row, but the code above seems not work.

**Comment by AllenFang** [comment]
@hi-bazinga, it's actually a issue, I've open an issue and will fix it soon, https://github.com/AllenFang/react-bootstrap-table/issues/970

**Comment by AllenFang** [comment]
@hi-bazinga, fixed on ```v2.9.2```

**Comment by francescabassi** [comment]
Hi, 

I'm using the 3.1.1 version and I notice that the expandable={false} property is ignored, the column is altough used to expand the row.

Any solution? 

Thanks

**Comment by AllenFang** [comment]
@francescabassi, could you show me your example? please keep it simple and minimal, thanks

**Comment by supiash1** [comment]
@AllenFang 
Could you let me know does the search functionality includes the data across the expandable rows as well please?

**Comment by florentcuret** [comment]
Clicking the radio button does not expand the row (event though I could not explicitly set expandable={ false } on it). And I am ok with this behaviour.
However clicking the "+" expand button (when expandColumnVisible is true) does select the row.
How can I make in sort that the click on the "+" column only triggers the expand but not the select.
Eventually I still would like to be able to select by clicking other columns.

**Comment by washif12** [comment]
I know there is new version but I used this. Need some help. Can the content of each expandable row be different?? If so, how?
