### ISSUE TITLE
npm install fails due to non-public dependency

### ISSUE THREAD

**Issue by mvolkmann** [AllenFang/react-bootstrap-table#898]
I get the following error trying to run "npm install" in a clone of the master branch:

npm ERR! 404  '@allenfang/react-toastr' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by droyuki** [comment]
If you use windows, your cmd environment must be able to run git command.
you can use Git bash to run npm install.

**Comment by mvolkmann** [comment]
That's not the issue. I'm on a Mac and I use git daily. Isn't the issue that @allenfang is a private git repo that I can't access?

**Comment by jcavandoli** [comment]
I'm facing the same issue since this [commit](https://github.com/AllenFang/react-bootstrap-table/commit/d652fca2c5dc68217caf33a4b4abaa71d955f160)

Looks like the react-toastr is set as a scope module, but maybe not published to the npm registry with the  [public access settings](https://docs.npmjs.com/misc/scope#publishing-public-scoped-packages-to-the-public-npm-registry)?

**Comment by AllenFang** [comment]
@jcavandoli, I published the npm registry with public access. I'll found the problem, there's a workaround that you can replace 
```"@allenfang/react-toastr": "2.8.2"```
as 
```"react-toastr": "git+https://github.com/AllenFang/react-toastr.git"```
It's a workaround that allow you can run locally.

it's my scope module: https://www.npmjs.com/package/@allenfang/react-toastr

Anyway, I'll try to figure why

**Comment by AllenFang** [comment]
BTW, what's the version of ```npm``` and ```node``` in your local?

**Comment by rrameshkumar76** [comment]
I am facing the same issue. My npm version is 2.15.1 and node version is 4.4.4

**Comment by jcavandoli** [comment]
My npm version: 3.10.6, node version: v4.4.7

**Comment by AllenFang** [comment]
ok, actually, I guess this should not the problems of npm or node. and all you guys facing this issue when running ```npm install``` in the clone of ```react-bootstrap-table```?

**Comment by jcavandoli** [comment]
Yup, just tried with a fresh clone of the repo and still got that no such package available error.

**Comment by doshisunny** [comment]
I am also getting error '@allenfang/react-toastr' is not in the npm registry.' on npm install in my project.
I have "react-bootstrap-table": "2.7.1" in package.json

**Comment by jcavandoli** [comment]
From the npm [doc](https://docs.npmjs.com/cli/install), if you omit the @ of the scope name, npm will fetch the module from github. It can be a workaround but not sure it's the proper way to fix that.

**Comment by rrameshkumar76** [comment]
Do you all face this error in "npm Enterprise" or a private npm registry?

**Comment by AllenFang** [comment]
> From the npm doc, if you omit the @ of the scope name, npm will fetch the module from github. It can be a workaround but not sure it's the proper way to fix that.

yap, this is a workaround for now if you clone and install this repo.

@rrameshkumar76 
when did you encounter this issue? is that you clone ```react-bootstrap-table``` and install it?

**Comment by rrameshkumar76** [comment]
Allen, Thanks a lot for the response.

we are using npm enterprise. I encounter it when i run npm install in my project which has react bootstrap table as dependency.

I also tried just doing npm install react-bootstrap-table or npm install @allenfang/react-toastr , both give the same error. 

Would it help creating a new version for react-toastr and using that in table as dependency. Versions earlier to 2.7.1 work fine.I am currently using 2.6.0 for the table and that works fine.

**Comment by rrameshkumar76** [comment]
@AllenFang  My issue got fixed, for react toastr as its a scoped module, i had add below line to my project npmrc file.

@allenfang:registry=https://replicate.npmjs.com

**Comment by AllenFang** [comment]
@rrameshkumar76, that's awesome, I think your solution may solve the other people's problems.
Nice share 👍

**Comment by chalda** [comment]
@AllenFang 
@rrameshkumar76 
i am facing this similar issue now. I upped my version of bootstrap-table because of the react-toastr issue (that i reported 2 months ago and still have no effin response to!!!! https://github.com/tomchentw/react-toastr/issues/85)

unfortunately I am working in a corporate environment and we already have our own private registry so I dont think i can run 2 separate registries... what do? any help would be appreciated!

**Comment by chalda** [comment]
@AllenFang can we make a push to the react-toastr maintainer to merge your fix? This is honestly ridiculous.

**Comment by AllenFang** [comment]
I have no idea about how to fix the issue from ```react-toastr``` so I lock down the version of react in ```react-toastr```. Best solution is the creator of ```react-toastr``` to fix the issue, but I think he is not there....

**Comment by chalda** [comment]
@AllenFang getting a lot of invariant issues after the last install. i think the separate npm repo really messes with npm/webpack. perhaps even better would be to move the react dependancy to a peer or dev Dependancy. seeing how this fork will only ever get used by this project.. getting invariant errors unless i manually deleete node_modules/react-bootstrap-table/node_modules/react . Really messes with jenkins and automated tests.

**Comment by AllenFang** [comment]
> perhaps even better would be to move the react dependancy to a peer or dev Dependancy.

I've the same consideration and I actually did it at before(last year?), but it's very dangerous that you remove a very important dependencies from `peer`. Anyway, this issue cause by `react-toastr`, and I think the creator of `react-toastr` have no time to fix, and maybe I'll consider other toastr solution in near future.

**Comment by Wenzil** [comment]
For us, the cause of the problem was this bug: https://github.com/rlidwka/sinopia/issues/278

**Comment by AllenFang** [comment]
https://github.com/AllenFang/react-bootstrap-table/issues/1152

**Comment by AllenFang** [comment]
please check #1216, if you have any concern or question, let me know in #1216
