### ISSUE TITLE
Questions: select all items (from all pages) even after filter?

### ISSUE THREAD

**Issue by raphaelfabeni** [AllenFang/react-bootstrap-table#899]
Is it possible to select all items (from all pages)? Like if I have 100 items with 4 pages with 25 items each, if I select all, the 100 items are marked as selected.
And also, if I type something to filter the table, and I click to select all, could I have the same behavior (select all the items, but now the filtered items)?

I searched some issues but I did not find about something them. 
Thanks, and congratulations for the project!
It's awesome!

**Comment by AllenFang** [comment]
@raphaelfabeni, sorry for lately reply, what's the ```react-bootstrap-table``` version you uesd? Because I remember the select all behavior changed at before.

**Comment by AllenFang** [comment]
BTW, for your first requirement, you can check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/all-select.js#L29) out.

**Comment by AllenFang** [comment]
Let me know if you still have any question 👍

**Comment by raphaelfabeni** [comment]
Hey @AllenFang ! No problem..
You answered really fast. I'm using the version _2.5.3_.
And what you sent, it worked for me.

Again, THANKS!
🤘
