### ISSUE TITLE
Table Header doesn't resize

### ISSUE THREAD

**Issue by aaronhayes** [AllenFang/react-bootstrap-table#9]
Noticed the table header doesn't resize when the window does. 
The data table does resize causing misaligned headers/columns.

go to http://allenfang.github.io/react-bootstrap-table/example.html and resize your browser, you'll see what I mean quickly.

**Comment by AllenFang** [comment]
I found this problem, cause of the scroll bar appear in table, I need to adjust head's width to fit body's width. So I always to adjust head's with a fix size. I will fix this bug quickly :)

**Comment by AllenFang** [comment]
Hi @aaronhayes, this problem is solved in version v0.8.6.
