### ISSUE TITLE
selectedRowKeys return wrong selected values

### ISSUE THREAD

**Issue by erezre** [AllenFang/react-bootstrap-table#906]
Hi,

I'm trying to get the rows been selected by the selectedRowKeys attribute.
It's all work good when checking the rows, but unchecking one of them doesn't remove it from the selectedRowKeys list.

I'm using the onSelected: attribute to print selectedRowKeys values for both check and uncheck.

I think I'm using the last version cause I preformed my npm install 3 weeks ago.

Thank you!
Erez.

**Comment by AllenFang** [comment]
> I'm using the onSelected: attribute to print selectedRowKeys values for both check and uncheck.

if you get the ```selectedRowKeys``` in the ```onSelected``` function, you should always got the previous one ```selectedRowKeys```. Because ```onSelected``` function being called before apply the check\uncheck
