### ISSUE TITLE
SyntaxError: import is a reserved identifier

### ISSUE THREAD

**Issue by owen-TCM** [AllenFang/react-bootstrap-table#908]
When I use import {BootstrapTable, TableHeaderColumn} from 'react-bootstrap-table', 
I get the "SyntaxError: Import is a reserved identifier" on firefox in my bundle.js output file when I use webpack.

**Comment by AllenFang** [comment]
hi @owen-TCM, you need to think why you still get ```import``` error after webpacking, you should use babel or other es6 transpiler to transform es6 to es5
