### ISSUE TITLE
TableHeader: prop type `colGroups` is invalid

### ISSUE THREAD

**Issue by Trudko** [AllenFang/react-bootstrap-table#909]
Hi :),

I am getting a warning: 

Warning: Failed prop type: TableHeader: prop type `colGroups` is invalid; it must be a function, usually from React.PropTypes.
    in TableHeader (created by BootstrapTable)

with even the simple code as:

    render() {
        return (
            <BootstrapTable data={[{id:1}]} >
                <TableHeaderColumn isKey={true} dataField='id'>ID</TableHeaderColumn>
            </BootstrapTable>
        )
    }

Using 15.4.1 react and latest version of react boostrap table

**Comment by bryankennedy** [comment]
I'm seeing this same behavior with React 15.3.2

**Comment by AllenFang** [comment]
thanks for issue report, I think I made a little mistake on ```v2.8.0```, I'll fix it soon.

**Comment by jflayhart** [comment]
A changelog would be nice for these latest versions as well. Thanks for all your hard work @AllenFang!

**Comment by AllenFang** [comment]
@jflayhart, I'll add the changelog today, I'll figure out what happen to this warning. BTW, this warning  was happened before?

**Comment by jflayhart** [comment]
I am not certain of @Trudko issue, but seems that this only happened when I updated to your plugin to 2.8.0

**Comment by AllenFang** [comment]
@jflayhart, ```prop type `colGroups` is invalid``` is a known issue, but I dont see the warning you mentioned above, could you please show me your code?

**Comment by ashabi** [comment]
Great component! But we are having the same error of "TableHeader: prop type `colGroups` is invalid". We are using React 15.4.1 with react-bootstrap-table 2.8.0
Thank you

**Comment by nguyenchanhnghia** [comment]
I'm using v2.7.1, and it Warning: Failed prop type: TableHeader: prop type `colGroups` is invalid; it must be a function, usually from React.PropTypes.
    in TableHeader (created by BootstrapTable)
<img width="1432" alt="screen shot 2016-12-28 at 9 32 55 pm" src="https://cloud.githubusercontent.com/assets/7939078/21524061/d3369d62-cd45-11e6-8612-4518b1f52187.png">
with even the simple code in tutorial.

**Comment by AllenFang** [comment]
hi all, this issue fixed on ```v2.8.1```, let me know if this problem still remain.

**Comment by jflayhart** [comment]
@AllenFang, whatever fix you applied in 2.8.1 seemed to fix the additional error about `"key" prop` I was seeing. Thanks!

**Comment by nguyenchanhnghia** [comment]
@AllenFang i updated version but warning not disappear. this is my code:
`<BootstrapTable
            data={[{ id: 1 }]}
            striped
            hover
            headerStyle={{ marginBottom: '-20px' }}
            search
            searchPlaceholder="Search ..."
            pagination
            options={options}
          >
            <TableHeaderColumn dataField="id" key={_.uniqueId()} isKey dataAlign="center">
              <span className="cursor-pointer">No</span>
            </TableHeaderColumn>
          </BootstrapTable>
`

**Comment by ashabi** [comment]
the warning disappeared but it seemed to have messed up the Sort ability on the table.

**Comment by AllenFang** [comment]
> the warning disappeared but it seemed to have messed up the Sort ability on the table.

have more detail?

**Comment by AllenFang** [comment]
@nguyenchanhnghia, make sure you have already upgraded to ```v2.8.1```, BTW, as your this [mentioned](https://github.com/AllenFang/react-bootstrap-table/issues/909#issuecomment-269485673), you never get this warning on ```v2.7.1``` because ```v2.8.0``` start to support header column group, so make sure the version you used first.

**Comment by ashabi** [comment]
i upgraded to 2.8.1 because if I go back to 2.8.0 then the sort function works but the error exists. When i use v2.8.1 there is no error but the sort does not work. the caret arrows don't even appear.

**Comment by AllenFang** [comment]
Sorry, that's my mistake, I've patch it on ```v2.8.2```, please upgrade it. Let me know if problem still there.

**Comment by Trudko** [comment]
Looks great ! thank you for the quick fix.

**Comment by ferrwanz** [comment]
I got warning `prop invalid` for tdStyle and trStyle.
```
Warning: Failed prop type: TableHeaderColumn: prop type `tdStyle` is invalid; it must be a function, usually from React.PropTypes.
Warning: Failed prop type: TableHeaderColumn: prop type `tdStyle` is invalid; it must be a function, usually from React.PropTypes.
```
I didn't customize those things though. Any clue?

**Comment by AllenFang** [comment]
@ferrwanz, what's the version you are using?

**Comment by ferrwanz** [comment]
@AllenFang I'm using v2.11.1

**Comment by AllenFang** [comment]
upgrade to `v2.11.2` will fix this issue
