### ISSUE TITLE
Setting column width with percentage

### ISSUE THREAD

**Issue by zorganovic** [AllenFang/react-bootstrap-table#910]
Hi 
This is an improvement suggestion ! So that the columns widths will better adapt when resizing the application window.

By the way, how the column width is calculated by default ?

**Comment by AllenFang** [comment]
> This is an improvement suggestion ! So that the columns widths will better adapt when resizing the application window.

absolutely right, I'll consider to add this feature. The column width be calculate by bootstrap at default(with setting width), is responsive from outer wrapper

**Comment by AllenFang** [comment]
Fixed on `v2.11.0`, You can use `width='20%'` on `TableHeaderColumn`

**Comment by pedro-eira** [comment]
Total width is 100%. If entire columns' width is over 100%, how does it work?
