### ISSUE TITLE
can i embed one table into another?

### ISSUE THREAD

**Issue by ashabi** [AllenFang/react-bootstrap-table#920]
i have a table and within the table there is an action button that is supposed to open below it another table. is that possible? if so, what would be the best way to go about it?

**Comment by AllenFang** [comment]
@ashabi, I think you want a expandable row, you can check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/expandRow.js) out, let me know if you have any questions.
