### ISSUE TITLE
Select filter with more than 10 options returns wrong rows

### ISSUE THREAD

**Issue by elmoro666** [AllenFang/react-bootstrap-table#922]
Hi

If you have a select filter with more than 10 options, the wrong rows are returned. I have created a fiddle that shows this:

https://jsfiddle.net/elmoro666/69z2wepo/66338/

If you select quality1 from the list, all rows with quality1, quality10 and quality 11 are returned. It seems it only checks the leftmost digit for some reason

**Comment by AllenFang** [comment]
@elmoro666, sorry for lately reply. actually, the search and filter is all use the ```String.indexOf``` to find the match data, so I think this is not a bug, but I can support the ```eq``` or ```like``` in configuration for user to choose the mode they wanted. 

I'll spend some time to implement this feature because there're some people have the same issue or question. Currently, you can custom a select filter for a workaround before I support this feature. 

Thanks, let me know if you still have any question :)

**Comment by elmoro666** [comment]
@AllenFang Thanks for looking into this. I will try a custom filter in the meantime.

**Comment by elmoro666** [comment]
Do you want me to close this one?

**Comment by AllenFang** [comment]
let it open, I'll try to support this feature and give you response here.

**Comment by elmoro666** [comment]
@AllenFang Would you mind pointing me to an example/docs for implementing custom select-filter logic? This is the closest thing I can find:

https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/select-filter-programmatically.js

**Comment by AllenFang** [comment]
check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js), I'll support this feature as soon as possible.

**Comment by AllenFang** [comment]
@elmoro666, fixed on ```v2.8.3```, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/select-filter-with-eq-condition.js) and let me know if you still have question. Thanks

**Comment by elmoro666** [comment]
Sweet! It works perfectly. Thanks a bunch. I personally think condition = "eq" should be the default. It makes more sense to me than "like". I'm happy anyway

**Comment by AllenFang** [comment]
> I personally think condition = "eq" should be the default

It's hard to do that, because I always use ```String.indexOf``` in the past version, it will be incompatible if I do it.
