### ISSUE TITLE
How to make first row always be a specific entry

### ISSUE THREAD

**Issue by GregorioDiStefano** [AllenFang/react-bootstrap-table#924]
Hi, 

Is there anyway to always have the first entry in the table a specific row?
For example, my table must always have "../" as the first element in my table.

I've attemped using 'afterTableComplete', but it doesn't take any parameters.

Any ideas?

**Comment by AllenFang** [comment]
Sorry for lately reply.

it's most like a brainstorm for me and I think we haven't this feature directly for user. The only way I think is use ```remote``` mode and handle all the data changing(sort, search, pagination, filter etc), in your store or something like that, you alway put the specific row at first.

Let me know if you have any question 👍
