### ISSUE TITLE
expandable row + a with href

### ISSUE THREAD

**Issue by lironess** [AllenFang/react-bootstrap-table#927]
Hi.
I'm using this library (latest version) and its awesome, but I didn't succeed to do 1 thing:
my first table column looks like:
```javascript
<TableHeaderColumn
  dataField="company"
  className={ appStyles['table-header'] }
  dataFormat={ cell => (
    <a href="/company">{ cell }</a>
  )}>
  Company
</TableHeaderColumn>
```
also - every row on my table is expandable.
I want to make an stop the expanding event when clicking on the <a> element inside that specific column, and moving to the page its href show to. The row will be expanded when I click on every other column or any other place inside this column. (which is not on the <a> element)

Is it possible at all ?

**Comment by ptitFicus** [comment]
I don't think it's possible with the current API, however here is a workaroung that does the trick for me.
The idea is to prevent the click event propagation, therefore the expand of the row is not triggered. 

```js
<TableHeaderColumn
  dataField="company"
  className={ appStyles['table-header'] }
  dataFormat={ cell => (
    <a href="/company" onClick={ e => e.stopPropagation() }>{ cell }</a>
  )}>
  Company
</TableHeaderColumn>
```

**Comment by AllenFang** [comment]
thanks @ptitFicus, it's workaround. anyway, ```react-bootstrap-table``` support the ```expandBy``` in ```options``` props, default is ```row```, you can choose ```column``` and configure ```expandable``` on ```TableHeaderColumn``` which you want to make this column expandable, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/expand-row-by-column.js) example 


Note: *expandable is a new feature for ```react-bootstrap-table``` after ```v2.8.0```, let me know if you have any question*
