### ISSUE TITLE
can we add custom bootstrap confirm modal ?

### ISSUE THREAD

**Issue by rdroshan24** [AllenFang/react-bootstrap-table#929]
I would like to show bootstrap confirm modal dialog instead of default browser conform dialog before delete, how can we do so?

**Comment by AllenFang** [comment]
we dont support the custom confirm modal, but you can use the ```options.handleConfirmDeleteRow``` to  avoid the default browser confirm, following is a simple example

```js
function customConfirm(next, dropRowKeys) {
  const dropRowKeysStr = dropRowKeys.join(',');
  //  Here, you can use a custom modal instead confirm at this demo
  if (confirm(`(It's a custom confirm)Are you sure you want to delete ${dropRowKeysStr}?`)) {
    // If the confirmation is true, call the function that
    // continues the deletion of the record.
    next();
  }
}

const options = {
  handleConfirmDeleteRow: customConfirm
};

// If you want to enable deleteRow, you must enable row selection also.
const selectRowProp = {
  mode: 'checkbox'
};

export default class DeleteRowCustomComfirmTable extends React.Component {
  render() {
    return (
      <BootstrapTable data={ products } deleteRow={ true } selectRow={ selectRowProp } options={ options }>
          <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
}
```

Let me know if you have any questions

**Comment by rdroshan24** [comment]
@AllenFang thanks for your reply, it works for me.

**Comment by Rosteach** [comment]
Hello Allen, could you please provide an explicit example of how to render custom modal component, in case of next() function, because confirm action seems like a boolean function... I'm trying to render some JSX but nothing happens... How to propagate some component within your customConfirm() method?

**Comment by AllenFang** [comment]
Here, we got some examples: https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/custom/insert-modal
