### ISSUE TITLE
Strange behaviour with Pagination + sorting

### ISSUE THREAD

**Issue by tonthon** [AllenFang/react-bootstrap-table#934]
I've got a large table with 3000 entries that is displayed using pagination
When first filtering on column A, sorting is working well.
If I filter on column B and now on column A again, datas doesn't seem sorted correctly anymore.

Any idea ?

**Comment by AllenFang** [comment]
@tonthon, could you please explain more detail?  which column is on sorting? The flow of reproducing is like following:

1. Sort column A
2. filter column A
3. filter column B
4. filter column A again with other condition???
5. the problem appear?

**Comment by tonthon** [comment]
sorry I mixed words, it's all about sorting here
1- Sort column A : ok
2- Sort column B : ok
3- Sort column A again : sorting doesn't work anymore.

**Comment by AllenFang** [comment]
hi @tonthon, sorry for lately reply, so there's nothing about filtering?

**Comment by tonthon** [comment]
Sorry, I'm also very long in reacting.
There's nothing about filtering (filtering is activated but not involved in the problematic scenario).
But we're using pagination, I dont' know if it may interfere.

**Comment by tonthon** [comment]
If I've got some time, I'll try to extract an example illustrating the problem.

**Comment by AllenFang** [comment]
I'll open this issue until the issue can be reproduce there certainly.  thanks you
