### ISSUE TITLE
custom page size dropdown style

### ISSUE THREAD

**Issue by pepepaco** [AllenFang/react-bootstrap-table#936]
I'm using a custom bootstrap theme without JS and the page size dropdown doesn't look OK, 
what version of bootstrap is required for it to work? or even better, how could i replace this dropdown with a simple styled select without using the bootstrap one?
im using 3.0.0-beta.6 version that doesn't depend on JS files, but something in my theme interferes with the included dropdown.
thank you !

**Comment by AllenFang** [comment]
Before ```v3.0.0```, you need the ```bootstrap.js``` absolutely, but you can get ride of it on ```v3.0.0-beta```


> but something in my theme interferes with the included dropdown.

sorry I cant get you, which that mean?

BTW, on ```v.3.0.0```, you can custom size per page dropdown, check https://github.com/AllenFang/react-bootstrap-table/blob/v3.0.0-dev/examples/js/custom/pagination/custom-size-per-page.js

**Comment by pepepaco** [comment]
Thank you ill try that, regards.

**Comment by AllenFang** [comment]
Let me know if you still have any question.

**Comment by pepepaco** [comment]
Hello I tried to replace the dropdown but the page size is not being changed:
```
onToggleDropDown = (onToggleDropDown) => {
    // do your stuff here
    console.log('toggle dropdown');
    onToggleDropDown(); **//this is not a function error here**  
  }
  renderSizePerPageDropDown = (props) => {
    return (        
        <select id='select' name='group' className='form-control input-sm' size='1' value={5} onClick={ () => this.onToggleDropDown(props.onToggleDropDown) }>
                  <option value='5'>5</option>
                  <option value='10'>10</option>                  
        </select>
    );
  }
```
is this even possible to do? any help will be really appreciated. thanks!

**Comment by pepepaco** [comment]
I fixed this by changing the code like this:

```
  onToggleDropDown = (option) => {
    // do your stuff here
    console.log('toggle dropdown');
    this.props.onSizePerPageList(option.target.value)
  }

  renderSizePerPageDropDown = (props) => {
    return (      
      <select id='select' name='group' className='form-control input-sm' size='1' onChange={this.onToggleDropDown}>
        <option value='5'>5</option>
        <option value='10'>10</option>
      </select>
    );
  }
```
it is working now thanks!
