### ISSUE TITLE
export file format as pdf

### ISSUE THREAD

**Issue by hctslm** [AllenFang/react-bootstrap-table#937]
Hi Allen,

After applying the select filter the result needs to be exported into excel as well as pdf formats, It's my requirement
So I have tried exportCSV in my bootstrap table along with the option 
csvFileName='table-export', it is exporting the content in text file 
csvFileName='table-export.csv', it is exporting the content into excel sheet

same way I need to export the data in pdf format, so I have tried with csvFileName='table-export.pdf', it's creating a pdf file, but not able to open 
Giving the following error

![table-exports](https://cloud.githubusercontent.com/assets/24388651/21670533/e60f7c24-d33a-11e6-92b6-5a0dc20dfd18.PNG)

**Comment by AllenFang** [comment]
> same way I need to export the data in pdf format, so I have tried with csvFileName='table-export.pdf'

it's impossible that you can get a PDF well, because csv and pdf have the different format, so is not work that you just change the file name.

BTW, I have no any plan to support the pdf format, so PR is welcome 👍

**Comment by bruno-sartori** [comment]
+1 for this issue, this feature is really important

**Comment by prajapati-parth** [comment]
@bruno-sartori This can be handled server side, making a call to your service and then using data and converting it to pdf using [this library](https://github.com/wkhtmltopdf/wkhtmltopdf). You can then get the PDF downloaded.

Thanks.
