### ISSUE TITLE
custom class to export button

### ISSUE THREAD

**Issue by hctslm** [AllenFang/react-bootstrap-table#938]
Hi Allen,

Is there any option to have my own css style or custom class for export button 

Thanks in advance

**Comment by AllenFang** [comment]
@hctslm, sorry it's can be done in current stable version, but you can try the ```v3.0.0-beta.6```, [there](https://github.com/AllenFang/react-bootstrap-table/tree/v3.0.0-dev/examples/js/custom/csv-button)'re some example for showing how to custom the export csv button.

BTW, I think the beta version for ```v.3.0.0``` is very stable, you can try it.
