### ISSUE TITLE
Table Groups functionality

### ISSUE THREAD

**Issue by sidoruk-sv** [AllenFang/react-bootstrap-table#939]
Hi, can you help me to find a solution for such table with "Grouping row" (grayed on example image) with saving all others sorting/selecting functionality from this awesome component?

![Grouping table example](http://www.publicissue.gr/en/wp-content/gallery/tomos-meros-2-1/table-7a.jpg)

**Comment by AllenFang** [comment]
@sidoruk-sv, I think it's hard to do it currently, we only support the header group, but body not yet. BTW, I can try to support it, but it really take some time. BTW, if the sorting the one of the column, what the behavior you expect?

**Comment by sidoruk-sv** [comment]
I think it would be logical to sort each group separately. Maybe you can route me and I'll try to help you add this functionality to v3 or later.

**Comment by AllenFang** [comment]
> what components should handle this changes and I'll try to help you adding this functionality to v3 or later

I'm not very sure that what's component will be change, I think it's a big change for ```react-bootstrap-table``` and there's a [PR](https://github.com/AllenFang/react-bootstrap-table/pull/721) is for that, but it's not yet ready to merge, still on WIP.

BTW, if want to on each group, it'll be more complex to implement and we need to take care more data manipulation.

**Comment by venkat-vs-id** [comment]
Yo u have said >>we only support the header group<<
can you please tell me or show me an example of what you mean by "header group"

**Comment by AllenFang** [comment]
hi @venkat-vs-id, check these [examples](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/column-header-span)

Let me know if you have any question 👍

**Comment by ialbd** [comment]
Any update on this Allen? I am in the same boat as the OP and looking for a workaround with this fantastic library.

Is there any way I can do sth with a dummy row with static text?

**Comment by AllenFang** [comment]
@ialbd, sorry, we still doesn't support this feature currently. I'll try to support this feature if I have time, but if supported, will be on the `v4.x`

**Comment by ankushrgv** [comment]
Hey @AllenFang are you still working on this feature or do you have pending PRs for the same? Or do you need help with this?

**Comment by AllenFang** [comment]
@ankushrgv no, I'm not working on it. `react-bootstrap-table` already stop development and start to move to [`react-bootstrap-table2`](https://react-bootstrap-table.github.io/react-bootstrap-table2/).  Anyway, PR is welcome, thank you
