### ISSUE TITLE
Where is the gh-pages source code ?

### ISSUE THREAD

**Issue by luqin** [AllenFang/react-bootstrap-table#94]

**Comment by AllenFang** [comment]
in <code>gh-pages</code> branch https://github.com/AllenFang/react-bootstrap-table/tree/gh-pages

**Comment by luqin** [comment]
请问怎么构建 gh-pages？

**Comment by AllenFang** [comment]
it's not necessary to build this branch, it's a static html file, you just pull the html file into your browser.
