### ISSUE TITLE
Clarity of `filterFormatted` in Documentation

### ISSUE THREAD

**Issue by alanqthomas** [AllenFang/react-bootstrap-table#940]
## Issue
The `filterFormatted` prop has an unclear description in the documentation. I spent hours trying to figure out why my select filter wouldn't work. It turns out I had included `filterFormatted` in the column (because of the [examples for the select filter](http://allenfang.github.io/react-bootstrap-table/example.html#column-filter)) without fully understanding what it did. Looking at the documentation it seemed like I just needed to include it in the column to enable filtering. 

## Proposed fix
Make the documentation for `filterFormatted` clearer. To get started in the right direction, I'd suggest something as follows.

> When true, the column will filter using the value returned by the column's formatter. When false (default), the column will filter using the pre-formatted value.

Also consider changing the [filter examples](http://allenfang.github.io/react-bootstrap-table/example.html#column-filter) to not include `filterFormatted` and possibly include one extra example to showcase the use of `filterFormatted` explicitly.

Anyways, thanks to everyone who's worked on this component. It's extremely powerful and versatile.

**Comment by AllenFang** [comment]
@alanqthomas, that's awesome explain for ```filterFormatted``` and I think [filter examples](http://allenfang.github.io/react-bootstrap-table/example.html#column-filter) is not very clear for I dont show you the source data which cause you cant understand what's happen in ```enumFormatter```.

Anyway,  ```filterFormatted``` can be used on filter and search, for the purpose of ```filterFormatted``` is for filtering the formatted data(Which means you want to filter the data that you define on the ```dataFormat```).

I'll fix the document quickly, thanks your suggestion, It's very helpful.

**Comment by AllenFang** [comment]
Update Docs, thanks your feedback 👍
