### ISSUE TITLE
Gap between table header and body

### ISSUE THREAD

**Issue by nitishkumar71** [AllenFang/react-bootstrap-table#941]
Hi,

I am new to React. I was trying to use react-bootstrap-table, but I am stuck with one strange behaviour.
Don't know why but There is gap between table header and Body.

Plunker Link:

https://embed.plnkr.co/ovKjkeMpUP7UhOvvxvZ9/

**Comment by AllenFang** [comment]
Forgot to include the css file, https://github.com/AllenFang/react-bootstrap-table#cimport-css 👍

**Comment by nitishkumar71** [comment]
I have already included <link rel="stylesheet" src="https://npmcdn.com/react-bootstrap-table/dist/react-bootstrap-table-all.min.css" /> in html, is it wrong?

**Comment by AllenFang** [comment]
@nitishkumar71, I'm not very suggest you to develop a react application in a online editor, bundle it as webpack. I saw your example and the css does't include success, because I inspect the table in the browser, but the styling didn't apply correctly.

**Comment by AllenFang** [comment]
I found it 

`<link rel="stylesheet" href="http://npmcdn.com/react-bootstrap-table/dist/react-bootstrap-table-all.min.css" />`

instead of 

`<link rel="stylesheet" src="http://npmcdn.com/react-bootstrap-table/dist/react-bootstrap-table-all.min.css" />`

**Comment by nitishkumar71** [comment]
ohh I am Sorry, I should have looked more closely earlier. Thank You for your time.
