### ISSUE TITLE
Clear Filter Button

### ISSUE THREAD

**Issue by CHRISTOPHERDIEHL** [AllenFang/react-bootstrap-table#942]
I know that v3.0.0 will allow you to create custom toolbars, but until v3 is out of Beta, is there any way to create a Clear Filter Button beside the Export To Csv button on the toolbar? 

I'm sure there is a way using some cluster of JQuery, but I would prefer no to go that route if possible.

**Comment by AllenFang** [comment]
I dont know why closing this issue, but you can take [this](https://github.com/AllenFang/react-bootstrap-table/blob/v3.0.0-dev/examples/js/custom/toolbar/custom-button-group.js) example.

Let me know if you still have any question.
