### ISSUE TITLE
Wrapping a <TableHeaderColumn> component

### ISSUE THREAD

**Issue by bobderrico** [AllenFang/react-bootstrap-table#943]
I am running into an issue with wrapping <TableHeaderColumn> in another component. Here is what I am trying to do...

```jsx
import React from 'react';
import { TableHeaderColumn } from 'react-bootstrap-table';

export default function IndicatorColumn(props) {
  function getIndicator(value) {
    return <span className={`indicator indicator--${value ? 'on' : 'off' }`}></span>
  }

  return (
    <TableHeaderColumn {...props} dataFormat={getIndicator}>
       {props.children}
    </TableHeaderColumn>
  )
}
```

Essentially, I am abstracting away the `dataFormat` attribute, so that I can reuse this column later without duplicating the logic of creating my `<span className=indicator...>` element.

The usage would look like this:

```jsx
<BootstrapTable ...>
  ...
  <IndicatorColumn dataField='foo'>Foo</IndicatorColumn>
  ...
</BootstrapTable>
```

However, this approach is not working. My attempts to add properties to `<TableHeaderColumn>` fails, as the `dataFormat` property is never added.

It seems as if the props passed to `<IndicatorColumn>` are always implicitly passed as-is to `<TableHeaderColumn>`. As an experiment, I even removed the `{...props}` (so, effectively passing no props at all), and all of the props are still passed.

I am about two weeks into learning React, so there might be something I'm missing here, but I was able to do something similar with just some components I created (not related to this library). 

Is what I am trying to do possible with this library? If it is, what would be a working approach. I have been doing some research on this, but have not been able to figure it out.

Thank you!

**Comment by AllenFang** [comment]
@bobderrico, I guess because in ```react-bootstrap-table```, I use ```this.props.children``` in the ```BootstrapTable``` to get all the ```TableHeaderColumn```, then get all the props on these children, so as the code you mentioned above,  ```IndicatorColumn``` is actually the child so I can only get the ```dataField```.

Anyway, did you have any concern that you need to wrap ```TableHeaderColumn``` again?

**Comment by AllenFang** [comment]
close it due to this is not a issue actually. Let me know if you have any concern or question 👍

**Comment by bobderrico** [comment]
That makes more sense then. Thank you!
