### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Component' of undefined at Object.defineProperty.value

### ISSUE THREAD

**Issue by amshim** [AllenFang/react-bootstrap-table#944]
I am getting the following typeError coming from the react-bootstrap-table.js file. I am trying to get column filtering to work (not columnFilter, but just filter).

`<TableHeaderColumn dataField="id"  filter={{ type: 'TextFilter' }} isKey hidden></TableHeaderColumn>
`

[Screenshot of error](https://i.gyazo.com/397a268cd94cda1ae7b96f3634f90187.png)

**Comment by AllenFang** [comment]
@amshim, I can't reproduce this issue, could you please show me the whole example code?  Thank you

**Comment by amshim** [comment]
@AllenFang 

This is the exact error: [Screenshot Here](https://i.gyazo.com/6d20cc22c98c18df126c64b7b362f8df.png)

``` 

 render() {
    const tableOptions = {
      onRowClick: this.onRowSelect,
      sizePerPage: 20,  // which size per page you want to locate as default
      sizePerPageList: [ 20, 50, 100 ], // you can change the dropdown list for size per page
      paginationShowsTotal: this.renderShowsTotal // Accept bool or function
    };
    return(
      <BootstrapTable striped hover search
                      headerStyle={{ marginBottom: '-20px' }}
                      data={this.props.printTests}
                      options={tableOptions} 
                      pagination={true}>
        <TableHeaderColumn dataField="id" filter={{ type: 'TextFilter' }} isKey hidden>ID</TableHeaderColumn>
        <TableHeaderColumn dataField="name" filter={{ type: 'TextFilter' }}>Name</TableHeaderColumn>
      </BootstrapTable>
    );
  }

```

The above is the sample code. I am trying to use the `filter` option per column. I have the `react-bootstrap-table.css` file inside my app/assets/index.html. For some reason, the column search boxes do not appear when I run this locally, but shows up when I push it up to my server. 

Regardless, the error happens in both cases still (locally and on my server).

**Comment by amshim** [comment]
Actually, this COULD be an unrelated issue to your library. I am still investigating. H

However, the main problem still stands, that the `filter` option does not show up when I run my code locally.

**Comment by AllenFang** [comment]
@amshim, actually, I follow your code but still  cant reproduce this error, BTW, you should add `react-bootstrap-table.min.css` and I thought the error is not related with css file. Anyway, I thought this error really not related with this library. I'll open this issue if there're the same issue for other people or I can reproduce this issue on my local. 

BTW, according to your example, if it's a bug, it was supposed to be opened early.
