### ISSUE TITLE
Give Link to or anchor tag on record data

### ISSUE THREAD

**Issue by stephennyu** [AllenFang/react-bootstrap-table#945]
Hi,

I tried to read the documentation and try to look into several examples on how to leverage this bootstrap table, however I am unable to find the implementation for my needs here.
Example on what I would like to achieve

```
id     name              product       date
-----------------------------------------
1      Invoice #10     Product A   10-01-17
2     Invoice #11      Product B    11-01-17

```
I would like that I can click on invoice name and redirect to invoice detail route, and when I click on product name, it can be redirected to product detail route

How can I achieve this using react bootstrap table ? Any help would be highly appreactied

Thank you

**Comment by AllenFang** [comment]
@stephennyu, you can try to use the ```dataFormat```, there are couple [example](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/column-format).

Let me know if you still have question.
