### ISSUE TITLE
How to know checkbox is checked or not for automation

### ISSUE THREAD

**Issue by anujemc** [AllenFang/react-bootstrap-table#946]
**Usecase:** In order to write automation test for a component which is based on react-bootstrap-table , we are unable to get checkbox value at any point of time , when I see in developer tool in browser it shows checkbox's attribute value as "on" and it remains "on" whether checkbox is checked or not .

when we use normal checkbox in a form it gives value as "true" in case of checked and "false" in case of unchecked so this helps us in automation.

please let us know how we know the current state of checkbox problematically for automation.

**Comment by AllenFang** [comment]
jquery:
```js
$("#checkbox").is(':checked')
```
javascript:
```
document.getElementById("checkbox").checked
```
it's very simple, for your testing, you can get the DOM and try the ```DOM.checked```

Let me know if you still have problem
