### ISSUE TITLE
Filter DateTime

### ISSUE THREAD

**Issue by cristina321** [AllenFang/react-bootstrap-table#948]
The date search filter does not look good for the signs = y! =

The date search filter does not filter well with the "! =" and "="

**Comment by AllenFang** [comment]
I cant got you, I'll open this issue if you can give me more detail or examples. thank you

**Comment by Tommyhank** [comment]
If you go to http://allenfang.github.io/react-bootstrap-table/example.html#column-filter and go to the date filter example. The "=" and "!=" doesn't work perfectly.

**Comment by AllenFang** [comment]
https://github.com/AllenFang/react-bootstrap-table/issues/1186

**Comment by echinveeraphan-zen** [comment]
Was a fix implemented for the "=" date filter? It doesn't seem to be working on the example page either: http://allenfang.github.io/react-bootstrap-table/example.html#column-filter
<img width="422" alt="screen shot 2018-01-12 at 2 40 57 pm" src="https://user-images.githubusercontent.com/31740366/34898206-ad86c8b2-f7a6-11e7-8d9e-fd2c0308b253.png">
<img width="1239" alt="screen shot 2018-01-12 at 2 41 12 pm" src="https://user-images.githubusercontent.com/31740366/34898207-b07bf13c-f7a6-11e7-920f-4dd7ef3779da.png">
From the screenshots, we would expect 1 row to be displayed. Instead, no rows are displayed..

**Comment by AllenFang** [comment]
@echinveeraphan-zen the website doesn't update, this issue already fixed definitly
