### ISSUE TITLE
header widths wrong on first render when using selectRow

### ISSUE THREAD

**Issue by mvolkmann** [AllenFang/react-bootstrap-table#950]
The header widths in the table are wrong when my table initial renders, only when using selectRow.
If I do something that causes the table to re-render, the widths are corrected.
See the attached before and after screenshots.
<img width="367" alt="screen shot 2017-01-10 at 12 40 28 pm" src="https://cloud.githubusercontent.com/assets/79312/21819660/3f8b77e4-d732-11e6-8b49-4623cb03e03a.png">
<img width="360" alt="screen shot 2017-01-10 at 12 40 47 pm" src="https://cloud.githubusercontent.com/assets/79312/21819661/3f8cb0b4-d732-11e6-933e-5b243f391716.png">

**Comment by AllenFang** [comment]
@mvolkmann, in the newest version and what browser you used?  You got this issue at previous version? thanks

**Comment by AllenFang** [comment]
hi, try `react-bootstrap-table@2.10.0-beta.1` will fix this issue and if it work and stability, I'll consider to release to production. Let me know if the problem still there. thanks
