### ISSUE TITLE
ExportCSV Row & Column Width

### ISSUE THREAD

**Issue by Abuitime** [AllenFang/react-bootstrap-table#951]
Hello,

Is there a way to customize or at least format the CSV document that is being downloaded? At least make the column and rows fit to the width of the text, and maybe wrap text? 

-Thanks,
Alex

**Comment by AllenFang** [comment]
> At least make the column and rows fit to the width of the text, and maybe wrap text?

you can try the ```csvFormat```, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/export-csv-table.js#L34

BTW, i think it's hard to fit the column to the width of text, but you may use ```csvFormat``` and append some empty string to make them align.

Let me know if you have any question.
