### ISSUE TITLE
Expandable Row error 'Uncaught TypeError: _this3.props.adjustHeaderWidth is not a function'

### ISSUE THREAD

**Issue by iruslani** [AllenFang/react-bootstrap-table#952]
I'm trying the expandable row example and I'm getting this error in the console every time I click a column or row to expand. 

Here is the error I'm getting: 
`
Uncaught TypeError: _this3.props.adjustHeaderWidth is not a function`

Anyone else experiencing this also?

**Comment by AllenFang** [comment]
it's wired for this error. I will try to make some improvement but I'm not sure my patch can solve this issue. thanks

**Comment by iruslani** [comment]
Hello Allen,

Thanks for your reply.
When do you think you will release this patch.

**Comment by AllenFang** [comment]
I'm not sure, due to busy on work, and this issue its rarely happen, also I can't reproduce it. anyway, I think in sunday or next monday.

**Comment by AllenFang** [comment]
Fixed on ```v2.9.1```, check it out 👍
