### ISSUE TITLE
Hide noDataText

### ISSUE THREAD

**Issue by song-hao** [AllenFang/react-bootstrap-table#954]
Hi, Allen.
I am wondering if I can hide the NoDataText area, and only show the header of the table when there is no data in the table.

![image](https://cloud.githubusercontent.com/assets/7380836/21840219/437b5b9a-d817-11e6-9624-a6a53c3f1db7.png)

**Comment by AllenFang** [comment]
@song-hao, sorry, we dont support it, but I think I can add this feature in next version

**Comment by AllenFang** [comment]
@song-hao, supported on ```v2.9.1```, set true to ```options.withoutNoDataText```, check https://github.com/AllenFang/react-bootstrap-table/commit/b003927f983026d1aa08fd313fdb8570d49c7419
