### ISSUE TITLE
Props warning from ToolBar in v3.0.0-beta.6

### ISSUE THREAD

**Issue by sidoruk-sv** [AllenFang/react-bootstrap-table#955]
> "Failed prop type: The prop `contentLabel` is marked as required in `Modal`, but its value is `undefined`."

Since React modal v1.6 there are two required props `contentLabel` and `isOpen`: https://github.com/reactjs/react-modal#usage

**Comment by AllenFang** [comment]
thanks for reminding, I'll fix it. 👍

**Comment by AllenFang** [comment]
Fix on `v3.0.0-beta.7` https://github.com/AllenFang/react-bootstrap-table/releases/tag/v3.0.0-beta.7
