### ISSUE TITLE
export file save format as (.xlsx) instead of .csv

### ISSUE THREAD

**Issue by hctslm** [AllenFang/react-bootstrap-table#957]
Hi Allen,

I should save my data in excel sheet  (.xlsx). Is there any option to make this

Thanks in advance

**Comment by AllenFang** [comment]
hi @hctslm, ```react-bootstrap-table``` is only support the csv format and I think it's also hard to transfer the table into a style sheet, I guess it need some library to handle it and it's not a critical feature for this component, so PR is welcome. 

Let me know if you still have any concern or you can find a solution for it, I'll consider it
