### ISSUE TITLE
Example with colspan & rowspan

### ISSUE THREAD

**Issue by josselinh** [AllenFang/react-bootstrap-table#960]
Hello,

I've followed the example you provide : column-header-span-complex.js

I would like to add a width to the last TableHeaderColumn.
The result is good but I have an error :
``Uncaught TypeError: Cannot read property 'style' of undefined
    at eval (BootstrapTable.js:1222)``

Do you know why ?

Thank you

```js
<BootstrapTable data={ this.state.stats2 }>
                <TableHeaderColumn row='0' rowSpan='2' dataField='id' isKey={ true } >ID</TableHeaderColumn>
                <TableHeaderColumn row='0' colSpan='3' dataSort csvHeader='Product' headerAlign='right'>Product</TableHeaderColumn>
                <TableHeaderColumn row='1' dataField='name' width='175' dataAlign='center'>name</TableHeaderColumn>
                <TableHeaderColumn row='1' dataField='price' width='70' dataSort>price</TableHeaderColumn>
                <TableHeaderColumn row='1' dataField='coupon' width='70'>Coupon</TableHeaderColumn>
                <TableHeaderColumn row='0' csvHeader='In stock' rowSpan='2' dataField='status'>In stock</TableHeaderColumn>
                <TableHeaderColumn row='0' colSpan='2' csvHeader='Customer' filter={ { type: 'TextFilter', delay: 1000 } }>Customer</TableHeaderColumn>
                <TableHeaderColumn row='1' csvHeader='name' dataField='customer'>name</TableHeaderColumn>
                <TableHeaderColumn row='1' csvHeader='order' width='70' dataField='order' dataSort>order</TableHeaderColumn>
              </BootstrapTable>
```

**Comment by josselinh** [comment]
My "hack" is to add a hidden column :-)

**Comment by AllenFang** [comment]
@josselinh, sorry I can reproduce this issue, and where's the hidden column, is that a workaround that avoid this issue?

**Comment by josselinh** [comment]
Hello @AllenFang,
Thank you for your response.
I've made another example :
`<BootstrapTable data={ this.state.stats }>
                                <TableHeaderColumn row="0" colSpan="2">Informations</TableHeaderColumn>
                                <TableHeaderColumn row="1" dataField="id" isKey>Id</TableHeaderColumn>
                                <TableHeaderColumn row="1" dataField="name">Name</TableHeaderColumn>

                                <TableHeaderColumn row="0" colSpan="2">Stats</TableHeaderColumn>
                                <TableHeaderColumn row="1" width="90" dataField="sum_pages_likes">Likes</TableHeaderColumn>
                                <TableHeaderColumn row="1" width="90" dataField="sum_pages_talking_about">Talks</TableHeaderColumn>
                            </BootstrapTable>`

Because I add width property on the two last TableHeaderColumn, I have the error.
My hack is to add a hidden group :
`<BootstrapTable data={ this.state.stats }>
                                <TableHeaderColumn row="0" colSpan="2">Informations</TableHeaderColumn>
                                <TableHeaderColumn row="1" dataField="id" isKey>Id</TableHeaderColumn>
                                <TableHeaderColumn row="1" dataField="name">Name</TableHeaderColumn>

                                <TableHeaderColumn row="0" colSpan="2">Stats</TableHeaderColumn>
                                <TableHeaderColumn row="1" width="90" dataField="sum_pages_likes">Likes</TableHeaderColumn>
                                <TableHeaderColumn row="1" width="90" dataField="sum_pages_talking_about">Talks</TableHeaderColumn>

                                <TableHeaderColumn row="0" colSpan="2" hidden>Hidden</TableHeaderColumn>
                                <TableHeaderColumn row="1" hidden>Likes</TableHeaderColumn>
                                <TableHeaderColumn row="1" hidden>Talks</TableHeaderColumn>
                            </BootstrapTable>`

Note : the problem doesn't exist if I don't have any group column.

**Comment by AllenFang** [comment]
I follow your code and did a simple example like folloinwg:

```js
<BootstrapTable data={ products }>
        <TableHeaderColumn row='0' colSpan='2'>Book</TableHeaderColumn>
        <TableHeaderColumn row='1' dataField='id' isKey>ID</TableHeaderColumn>
        <TableHeaderColumn row='1' dataField='baba'>BABA</TableHeaderColumn>
        <TableHeaderColumn row='0' colSpan='2'>Product</TableHeaderColumn>
        <TableHeaderColumn row='1' width='90' dataField='name'>Name</TableHeaderColumn>
        <TableHeaderColumn row='1' width='90' dataField='price'>Price</TableHeaderColumn>
</BootstrapTable>
```

And this is result, the table is fine and still not found any error message in console

<img width="709" alt="2017-01-16 9 17 03" src="https://cloud.githubusercontent.com/assets/5351390/21984568/7b7a05b4-dc31-11e6-806a-7a66a233d601.png">

what's browser your used? or did I miss something?

**Comment by josselinh** [comment]
I'm using Chrome.

![tablebootstrap](https://cloud.githubusercontent.com/assets/1784811/21984804/f371daf4-dbf7-11e6-9862-305db8fb53aa.png)

`"react-bootstrap": "^0.30.3",
    "react-bootstrap-table": "^2.9.0",`

**Comment by AllenFang** [comment]
you got this error when initial load?

**Comment by josselinh** [comment]
Yes.
The table displays well, as you

**Comment by AllenFang** [comment]
ok, it's very wired, could you give me a favor? I want a simple and minimal repo which can reproduce this error certainly, I'm not very hurry for this issue, but just want to figure out. Anyway, take your times

**Comment by AllenFang** [comment]
BTW, what's the version of Chrome you used

**Comment by josselinh** [comment]
55.0.2883.87 m

**Comment by josselinh** [comment]
Aha, you're gonna laugh ...
I had forgotten to import the CSS :-/
Sorry to have wasted your time
