### ISSUE TITLE
search field is not reverting back when no result found

### ISSUE THREAD

**Issue by Sandip-pal** [AllenFang/react-bootstrap-table#961]
While i used some matching criterion in search field, I am getting desired results.
But if search criterion is not matched and no results to display, If I clear also i am not getting the old table back.
Instead I am getting an error 'BootstrapTable.js?028a:1199 -Uncaught TypeError: Cannot read property 'style' of undefined'

**Comment by AllenFang** [comment]
hi @Sandip-pal, sorry for lately reply, could you please create a simple and minimal example for me to reproduce? Cause of I cant reproduce this issue.  Thanks 👍

**Comment by AllenFang** [comment]
@Sandip-pal, upgrade to newest version is supposed to fixed.
