### ISSUE TITLE
Overriding autovalue id with the actual database id?

### ISSUE THREAD

**Issue by pceccato** [AllenFang/react-bootstrap-table#964]
My id field is actually the database key and when a cell is updated I use the id field to persist the change to the database.

However when a new row is inserted the key is automatically generated due to the autoValue property on the <TableHeaderColumn>. 

Now if the user edits the newly created row, I can't update the database because the id field is not the same as the newly created record in the database.

When the  afterInsertRow() hook is called  I write the new row to the database, which gives me a new id, however the Bootstrap table has already been updated with the autovalue id.

What is the best way to update my data with this the new id field obtained from the database insert?

**Comment by pceccato** [comment]
Actually I did some experimenting and it looks like I can change the id in the afterInsertRow() handler and the changed id appears in the grid.

Feel free to close...

**Comment by AllenFang** [comment]
> Actually I did some experimenting and it looks like I can change the id in the afterInsertRow() handler and the changed id appears in the grid.

surely, you can change it, the auto id value is just for the application which doesn't have a database or state management used and it prevent the new row insert fail without rowkey.
