### ISSUE TITLE
sizePerPage list not shown

### ISSUE THREAD

**Issue by sergio-finanzero** [AllenFang/react-bootstrap-table#966]
Hello,

I'm having a problem with the sizePerPage list that is not showing (opening the drop-down menu) and consequently is not changing its value.

I tried different approaches but it seems that I'm experiencing a permanent inconsistence, probably on the way I build my application. I'm using create-react-app. 

In order to isolate the problem, I had created a very simple application, using `create-react-app` and got the same issue.
![image](https://cloud.githubusercontent.com/assets/20519034/22003182/b740859e-dc38-11e6-9e47-cd132c634903.png)

As you can see on image, I included a DropdownButton control in the page just to make sure it was not a react-bootstrap issue.

My package.js looks like this:
`{
  "name": "test-react",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-scripts": "0.8.5"
  },
  "dependencies": {
    "bootstrap": "^3.3.7",
    "react": "^15.4.2",
    "react-bootstrap": "^0.30.7",
    "react-bootstrap-table": "^2.9.1",
    "react-dom": "^15.4.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}`

Any help will be appreciated.

**Comment by tan31989** [comment]
The same opens when we include the js files for jquery and boostrap:

```
<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js">
</script>
```

which is wrong, I wouldn't want to use the above said js files.
I guess this fix needs to use [react bootstrap drop down control](https://react-bootstrap.github.io/components.html#btn-dropdowns)

**Comment by AllenFang** [comment]
it should be fixed after include the jquery and bootstrap basically. Anyway, they are noisy dependencies so that I've remove them from ```v3.0.0-beta```, you can give it a try for```v3.0.0-beta.6```. There're some people have used it successfully.

let me know if you have any question. thanks

**Comment by batjko** [comment]
Hi @AllenFang . The npm package says we're on v3.1.1 already and that jQuery dependency has been removed. But it seems that's not the case?
Can at least the README be updated please?

**Comment by AllenFang** [comment]
@batjko, README dose not ask user to use `jQuery` and I'll add update it to tell people that you dont need `jQuery` and `bootstrap.js` anymore.
