### ISSUE TITLE
react-toastr version causing duplicate react packages in bundle

### ISSUE THREAD

**Issue by ianks** [AllenFang/react-bootstrap-table#969]
Currently, `allenfeng/react-toastr` locks in React like so:

```
"react": "^0.14.0 || <15.4.0"
```

However, I am currently using react `15.4.1`, so I have duplicate React packages in my bundle. Thus, react-toastr comprise 5.65% of my bundle. Funnily enough, I don't even use the toastr parts of this package :/

```
font-awesome: 1.42 MB (13.0%)
lodash: 688.56 KB (6.14%)
@allenfang/react-toastr: 633.7 KB (5.65%)
  react: 580.18 KB (91.6%)
  fbjs: 32.93 KB (5.20%)
  react-dom: 63 B (0.00971%)
  <self>: 20.53 KB (3.24%)
```

Can you upgrade the dep to allow for newer versions of react?

**Comment by AllenFang** [comment]
I saw you comment on https://github.com/AllenFang/react-bootstrap-table/issues/838, close this one and answer there

**Comment by AllenFang** [comment]
please check #1216, if you have any concern or question, let me know in #1216
