### ISSUE TITLE
Hide Column but keep in table

### ISSUE THREAD

**Issue by Abuitime** [AllenFang/react-bootstrap-table#971]
Hello,

I am pulling data from the table after it has been edited. I included the id of each row when generating the data for the table. Is there a way to hide the column containing the ID. 

Basically is there a way to hide a column? 

Thank you

-Alex

**Comment by Abuitime** [comment]
I just needed to check for the column I wanted to hide within the bootstrap tag and modify the style of the TableHeaderColumn to include "display:none"

**Comment by AllenFang** [comment]
hello, 
`<TableHeaderColumn dataField='ID' hidden></TableHeaderColumn>
