### ISSUE TITLE
Sort not working, don't quite understand the error message

### ISSUE THREAD

**Issue by cheapsteak** [AllenFang/react-bootstrap-table#973]
Hi there!

I'm getting this error when I try to sort on a column, not quite sure what it means

```
The type of sort field and order should be both with String or Array
```

I have provided a sortFunc

**Comment by AllenFang** [comment]
@cheapsteak, could you please show me your code and did you use multiple sort?

**Comment by cheapsteak** [comment]
Yup! Here you go

```js
<BootstrapTable
  data={this.reports}
  keyField="id"
>
  <TableHeaderColumn
    dataSort
    dataFormat={(cell, row) => row.blubrry.periodDownloads}
    sortFunc={(a, b, order, sortField, path) => (_.get(a, path) >= _.get(b, path) ? 1 : -1) * (order === 'asc' ? 1 : -1)}
    sortFuncExtraData={'blubbry.periodDownloads'}
  >Blubrry Weekly Downloads</TableHeaderColumn>

</BootstrapTable>
```

**Comment by AllenFang** [comment]
@cheapsteak, I guess because you dont assign a `dataField` on  `TableHeaderColumn`, could you help me to add a `dataField` as a string value on it?

**Comment by cheapsteak** [comment]
That works! I assigned an empty string to `dataField` and sorting is now working. Thanks!

**Comment by cheapsteak** [comment]
Sorry nvm, the sort order seems inconsistent, not sorting as expected :\

**Comment by AllenFang** [comment]
> the sort order seems inconsistent

sorry, is revert? or what?

**Comment by cheapsteak** [comment]
Sorry about that, here's a pen!

http://codepen.io/cheapsteak/pen/MJmbzV

Behaviour is kind of odd, it only sorts after clicking the table header twice, and the sort indicator arrows don't quite match with the sort order

**Comment by AllenFang** [comment]
ok, that's a great example 👍

**Comment by varak69** [comment]
Hi @cheapsteak 

Your codepen isn't sorting because you misspelled 'blubrry' in line 26

**Comment by cheapsteak** [comment]
Oh my god.
So sorry about that X|

**Comment by varak69** [comment]
@cheapsteak No worries, it happens to all of us :P

As for your initial error:
The type of sort field and order should be both with String or Array

If you specify an initial sort order in the options then you have to specify both sortName and sortOrder. If not using multiColumnSort then you can specify them as string:
<BootstrapTable options={{ sortName: 'periodDownloads', sortOrder: 'asc' }}>
...
</BootstrapTable>

If using multiColumnSort then you can specify more than one column to sort on and BOTH sortName and sortOrder should be arrays:
<BootstrapTable multiColumnSort={2} options={{ sortName: ['periodDownloads', 'allTimeDownloads'], sortOrder: ['asc', 'desc'] }}>
...
</BootstrapTable>

This will sort primarily on allTimeDownloads and then on periodDownloads.

Hope that helps
