### ISSUE TITLE
Is there a way to reset the table when prop changes? As in when the new data come in, i want the currPage to go back to 1 and remove the sorted table and so on.

### ISSUE THREAD

**Issue by kadariyp** [AllenFang/react-bootstrap-table#975]

**Comment by AllenFang** [comment]
@kadariyp, I thought there are something I am supposed to improve

**Comment by mjmhall** [comment]
I reset the table in componentDidUpdate by using the table handlers

componentDidUpdate() {
    if (this.props.forceTableSort) {
      /*
       force the table data to the first page, clear any searches
       and make sure the 1st page of the table is displayed
        */
      this.table.handlePaginationData(1, 10);
      this.table.handleSearch('');
      this.table.handleSort('desc', 'rowId');
    }
  }

**Comment by AllenFang** [comment]
yap, these exposed function is a workaround, but just no very react style~

**Comment by kadariyp** [comment]
Any update on this feature?

**Comment by AllenFang** [comment]
@kadariyp, sorry for lately fixing, it still work in process, I only few hours a day and need to handle all the issue here, and I've tag this issue as `inprocess` which means I'll handle it or I'm handling, so just be patient :)

BTW, I thought there's some bugs in `componentWillReceiveProps` so it really be handled more carefully.

**Comment by AllenFang** [comment]
Just a question, @kadariyp, did you use the `remote` mode?

**Comment by AllenFang** [comment]
@kadariyp, try `this.refs.table.reset()` when you table ready to update, upgrade to `v2.11.1`, let me know if you got any trouble

**Comment by kadariyp** [comment]
Thanks @AllenFang. I tried to update the version to this one but it throws an npm error. react toastr issue. any idea on when this issue will be resolved?

**Comment by AllenFang** [comment]
what's version you used before and is that same with https://github.com/AllenFang/react-bootstrap-table/issues/838 or https://github.com/AllenFang/react-bootstrap-table/issues/898 or https://github.com/AllenFang/react-bootstrap-table/issues/863?

**Comment by kadariyp** [comment]
Its same as 863. Trying to install new version but react-toastr throws the error.

**Comment by AllenFang** [comment]
sorry about this issue, because it happen some time and I can't reproduce it and if somebody can give me all the environment setting, dependencies version and a minimal and simple repo will be better.
