### ISSUE TITLE
Hi Allen

### ISSUE THREAD

**Issue by xiaoyue123789** [AllenFang/react-bootstrap-table#977]
Hi Allen.  when i use custom insert modal, i got "cannot read property  reset of undefined". is a bug? @

**Comment by AllenFang** [comment]
is that same with https://github.com/AllenFang/react-bootstrap-table/issues/958?

**Comment by AllenFang** [comment]
Fix on `v3.0.0-beta.7` https://github.com/AllenFang/react-bootstrap-table/releases/tag/v3.0.0-beta.7
