### ISSUE TITLE
export to csv header name is always the datafield attribute

### ISSUE THREAD

**Issue by Sandip-pal** [AllenFang/react-bootstrap-table#978]
When I export my table to CSV , the headers are always taking datafield attribute i.e the datafield coming from Backend.
Is there any way to customize the headers of the exported excel?

**Comment by AllenFang** [comment]
hello, use `csvHeader`, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/export-csv-table.js#L33
