### ISSUE TITLE
Add eslint or jshint rules.

### ISSUE THREAD

**Issue by kirstein** [AllenFang/react-bootstrap-table#98]
Formatting matters, lets generate a specific style-guide for this project. The best way to start is to add `.eslintrc` or `.jshintrc` file.

**Comment by AllenFang** [comment]
you means the https://github.com/AllenFang/react-bootstrap-table/blob/master/.eslintrc ?

**Comment by kirstein** [comment]
oh shit, how did I miss that... welp!
