### ISSUE TITLE
Limit number of selectable rows in table??

### ISSUE THREAD

**Issue by dnbr2002** [AllenFang/react-bootstrap-table#980]
Forgive me if there is already a simple way of doing this.  I just started doing React a few weeks ago and I'm loving these react-bootstrap-tables!  I need to limit the number of rows a user can select.  What is the best way to do this??

**Comment by AllenFang** [comment]
@dnbr2002, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/externally-managed-selection.js), 

In line 44, return false to tell `react-bootstrap-table` does not select this row.

Let me know if you get in the trouble in implementation. thanks :)

**Comment by dnbr2002** [comment]
@AllenFang  line 44??  Where do you mean line 44??  Just not sure what line 44 you are referring too.  Thanks for the quick response.
