### ISSUE TITLE
Problem with filesaver.js

### ISSUE THREAD

**Issue by remy-poirier** [AllenFang/react-bootstrap-table#982]
Hello,

I would like to understand why in the src folder the filesaver.js contain these lines : 
` typeof self !== "undefined" && self
	|| typeof window !== "undefined" && window
	|| this.content`

Whereas in the dist folder the minified file has : 
`typeof self !== "undefined" && self || typeof window !== "undefined" && window || undefined.content`

The `this`is replaced by `undefined`which causes errors when I try to access to my application.
Do you have any idea ?

**Comment by AllenFang** [comment]
The problem is solved?
