### ISSUE TITLE
Dataformatted cell is not exported to CSV

### ISSUE THREAD

**Issue by Sandip-pal** [AllenFang/react-bootstrap-table#984]
I am using dataformat option for a particular cell.
The scenario is : I am getting min and max value from backend and with dataformat method I am combining them as 'min-max' and displaying this combined value in one cell of the Table.
While exporting the table into CSV, I was getting empty value for that particular cell because data didn't come to that field directly with datafield option.
Is there a way to export that cell if I use dataformat method?

**Comment by ziolomu** [comment]
http://allenfang.github.io/react-bootstrap-table/docs.html#csvFormat

**Comment by AllenFang** [comment]
@ziolomu thanks 👍
