### ISSUE TITLE
Is there a way to mark rows as non editable?

### ISSUE THREAD

**Issue by usepe** [AllenFang/react-bootstrap-table#986]
Hello,

I was wondering if there is a way to mark certain rows on a table as "non editable", instead of make all the row "non editable".

Great module :)

Thanks in advance

**Comment by AllenFang** [comment]
@usepe, just check again, you wanna have some way to *make* some row non editable or *mark* some row non editable?

**Comment by usepe** [comment]
@AllenFang mmm, made some mistakes in what I tried to say :P let's go again.

I have a table for which I need to make a row non editable when they have (lets say) it active field in false.
```
const rows = [
  {
     id: 1,
     name: 'Something',
     active: true // Im editable
  },
  {
     id: 2,
     name: 'Another something',
     active: false // Im not editable
  }
]
```

But, they can be enabled again if we change that field (from inside the table would be awesome, if not, I can figure out another way to interact with it)

Thanks!

**Comment by AllenFang** [comment]
I thought [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/cell-edit/non-editable-table.js#L27) is what you want, check it out and let me know if you have any problem on implementation.  thanks 👍

**Comment by usepe** [comment]
@AllenFang Thanks! That's what I needed 😄
