### ISSUE TITLE
How to extract the input of the filter value?

### ISSUE THREAD

**Issue by meghanarora** [AllenFang/react-bootstrap-table#991]
I have implemented a table with a filter for some columns, and would like to save the inputted filters. How can I get the input?
ex. 
<TableHeaderColumn dataSort dataField={'abc'} ref={'abc'} filter={{type: 'TextFilter', placeholder: ''}}>ABC</TableHeaderColumn>

**Comment by AllenFang** [comment]
```js
render() {
  var options = {
     onFilterChange = function(filterObj, columnsInfo) {
        //... 
     }
  }
  return ( <BootstrapTable options={options}> );
}
```
Because user may apply multiple filter, so I wrap these filter information as an object and pass as first argument for `onFilterChange`.

Let me know if you got trouble on implementation.
