### ISSUE TITLE
Add background-color to the appropriate row and made it non-editable depending on provided value

### ISSUE THREAD

**Issue by evgimov** [AllenFang/react-bootstrap-table#992]
First, thank for such amazing library. I have explored a lot of features so far.
But recently I have faced with issue:

 I want to add background-color to the appropriate row and made it non-editable depending on provided value
I got the array of objects from database. The object format:
{"answer":"",
"category":"W",
"date_from":"2017-01-11 01:13:00",
"date_till":"0000-00-00 00:00:00",
"description":"Lost Angeles",
"employee_id":"2",
"id":"25",
"status":"Pending"}

I have three types of statuses: "Pending","Approved", "Rejected". Depending on these statuses I want to display a table with different types of rows. If status is "approved" or "rejected" the rows needs to be noneditable and have appropriate background.  For "Pending" status  I want to set only background-color.

**Comment by AllenFang** [comment]
@evgimov, you can make some row as non editable by [cellEdit.nonEditableRows](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/cell-edit/non-editable-table.js#L27), 

and you can use [trClassName](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/style/tr-class-function-table.js#L31) to custom the row level styling.

Let me know if you got any question on implementation. thanks 👍
