### ISSUE TITLE
Column filtering uses equal matching per default since 2.9.2

### ISSUE THREAD

**Issue by simonberger** [AllenFang/react-bootstrap-table#997]
The column filtering changed to eq matching per default in the latest build 2.10.0.

https://jsfiddle.net/69z2wepo/68697/

EDIT:
Problem seems to be introduced already before 2.10.0 release.

Edit:
Came in 2.9.2. -> 2.9.1 the last correct one.

**Comment by AllenFang** [comment]
@simonberger, that's my mistake, I'll patch this as soon as possible.
